QtFit: WeatherAlertMessage Class Reference
WeatherAlertMessage Class Reference
The WeatherAlertMessage class represents a FIT WeatherAlertMessage data message.
Public Member Functions
WeatherAlertMessage ()
Constructs a WeatherAlertMessage object.
DateTime timestamp () const
Returns the WeatherAlertMessage data message's timestamp field's current value.
QString reportId () const
Returns the WeatherAlertMessage data message's reportId field's current value.
DateTime issueTime () const
Returns the WeatherAlertMessage data message's issueTime field's current value.
DateTime expireTime () const
Returns the WeatherAlertMessage data message's expireTime field's current value.
WeatherSeverity severity () const
Returns the WeatherAlertMessage data message's severity field's current value.
WeatherSevereType type () const
Returns the WeatherAlertMessage data message's type field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setReportId (const QString reportId)
Sets the reportId field to reportId.
void setIssueTime (const DateTime issueTime)
Sets the issueTime field to issueTime.
void setExpireTime (const DateTime expireTime)
Sets the expireTime field to expireTime.
void setSeverity (const WeatherSeverity severity)
Sets the severity field to severity.
void setType (const WeatherSevereType type)
Sets the type field to type.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
WeatherAlertMessage (WeatherAlertMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The WeatherAlertMessage class represents a FIT WeatherAlertMessage data message.
See also
DataMessage
Definition at line 39 of file weatheralertmessage.h.
Constructor & Destructor Documentation
WeatherAlertMessage() [1/2]
WeatherAlertMessage::WeatherAlertMessage ()
Constructs a WeatherAlertMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file weatheralertmessage.cpp.
                                          : AbstractDataMessage(new WeatherAlertMessagePrivate(this))
 {
 }
WeatherAlertMessage() [2/2]
WeatherAlertMessage::WeatherAlertMessage (WeatherAlertMessagePrivate *const d) explicit protected
Constructs a WeatherAlertMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file weatheralertmessage.cpp.
                                                                              : AbstractDataMessage(d)
 {
 }
Member Function Documentation
expireTime()
DateTime WeatherAlertMessage::expireTime () const
Returns the WeatherAlertMessage data message's expireTime field's current value.
Time alert expires
Returns
the expireTime field value.
Definition at line 113 of file weatheralertmessage.cpp.
 {
     Q_D(const WeatherAlertMessage);
     return d->expireTime;
 }
Referenced by setExpireTime().
issueTime()
DateTime WeatherAlertMessage::issueTime () const
Returns the WeatherAlertMessage data message's issueTime field's current value.
Time alert was issued
Returns
the issueTime field value.
Definition at line 100 of file weatheralertmessage.cpp.
 {
     Q_D(const WeatherAlertMessage);
     return d->issueTime;
 }
Referenced by setIssueTime().
reportId()
QString WeatherAlertMessage::reportId () const
Returns the WeatherAlertMessage data message's reportId field's current value.
Unique identifier from GCS report ID string, length is 12
Returns
the reportId field value.
Definition at line 87 of file weatheralertmessage.cpp.
 {
     Q_D(const WeatherAlertMessage);
     return d->reportId;
 }
Referenced by setReportId().
setExpireTime()
void WeatherAlertMessage::setExpireTime (const DateTime expireTime)
Sets the expireTime field to expireTime.
Parameters
expireTime The field value to set.
Definition at line 180 of file weatheralertmessage.cpp.
 {
     Q_D(WeatherAlertMessage);
     d->expireTime = expireTime;
 }
References expireTime().
setIssueTime()
void WeatherAlertMessage::setIssueTime (const DateTime issueTime)
Sets the issueTime field to issueTime.
Parameters
issueTime The field value to set.
Definition at line 170 of file weatheralertmessage.cpp.
 {
     Q_D(WeatherAlertMessage);
     d->issueTime = issueTime;
 }
References issueTime().
setReportId()
void WeatherAlertMessage::setReportId (const QString reportId)
Sets the reportId field to reportId.
Parameters
reportId The field value to set.
Definition at line 160 of file weatheralertmessage.cpp.
 {
     Q_D(WeatherAlertMessage);
     d->reportId = reportId;
 }
References reportId().
setSeverity()
void WeatherAlertMessage::setSeverity (const WeatherSeverity severity)
Sets the severity field to severity.
Parameters
severity The field value to set.
Definition at line 190 of file weatheralertmessage.cpp.
 {
     Q_D(WeatherAlertMessage);
     d->severity = severity;
 }
References severity().
setTimestamp()
void WeatherAlertMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 150 of file weatheralertmessage.cpp.
 {
     Q_D(WeatherAlertMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setType()
void WeatherAlertMessage::setType (const WeatherSevereType type)
Sets the type field to type.
Parameters
type The field value to set.
Definition at line 200 of file weatheralertmessage.cpp.
 {
     Q_D(WeatherAlertMessage);
     d->type = type;
 }
References type().
severity()
WeatherSeverity WeatherAlertMessage::severity () const
Returns the WeatherAlertMessage data message's severity field's current value.
Warning, Watch, Advisory, Statement
Returns
the severity field value.
Definition at line 126 of file weatheralertmessage.cpp.
 {
     Q_D(const WeatherAlertMessage);
     return d->severity;
 }
Referenced by setSeverity().
timestamp()
DateTime WeatherAlertMessage::timestamp () const
Returns the WeatherAlertMessage data message's timestamp field's current value.
Returns
the timestamp field value.
Definition at line 74 of file weatheralertmessage.cpp.
 {
     Q_D(const WeatherAlertMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
type()
WeatherSevereType WeatherAlertMessage::type () const
Returns the WeatherAlertMessage data message's type field's current value.
Tornado, Severe Thunderstorm, etc.
Returns
the type field value.
Definition at line 139 of file weatheralertmessage.cpp.
 {
     Q_D(const WeatherAlertMessage);
     return d->type;
 }
Referenced by setType().
The documentation for this class was generated from the following files:
weatheralertmessage.h
weatheralertmessage.cpp