QtFit: TrainingFileMessage Class Reference
TrainingFileMessage Class Reference
The TrainingFileMessage class represents a FIT TrainingFileMessage data message.
Public Member Functions
TrainingFileMessage ()
Constructs a TrainingFileMessage object.
DateTime timestamp () const
Returns the TrainingFileMessage data message's timestamp field's current value.
File type () const
Returns the TrainingFileMessage data message's type field's current value.
Manufacturer manufacturer () const
Returns the TrainingFileMessage data message's manufacturer field's current value.
quint16 product () const
Returns the TrainingFileMessage data message's product field's current value.
quint32z serialNumber () const
Returns the TrainingFileMessage data message's serialNumber field's current value.
DateTime timeCreated () const
Returns the TrainingFileMessage data message's timeCreated field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setType (const File type)
Sets the type field to type.
void setManufacturer (const Manufacturer manufacturer)
Sets the manufacturer field to manufacturer.
void setProduct (const quint16 product)
Sets the product field to product.
void setSerialNumber (const quint32z serialNumber)
Sets the serialNumber field to serialNumber.
void setTimeCreated (const DateTime timeCreated)
Sets the timeCreated field to timeCreated.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
TrainingFileMessage (TrainingFileMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The TrainingFileMessage class represents a FIT TrainingFileMessage data message.
See also
DataMessage
Definition at line 34 of file trainingfilemessage.h.
Constructor & Destructor Documentation
TrainingFileMessage() [1/2]
TrainingFileMessage::TrainingFileMessage ()
Constructs a TrainingFileMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file trainingfilemessage.cpp.
                                          : AbstractDataMessage(new TrainingFileMessagePrivate(this))
 {
 }
TrainingFileMessage() [2/2]
TrainingFileMessage::TrainingFileMessage (TrainingFileMessagePrivate *const d) explicit protected
Constructs a TrainingFileMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file trainingfilemessage.cpp.
                                                                              : AbstractDataMessage(d)
 {
 }
Member Function Documentation
manufacturer()
Manufacturer TrainingFileMessage::manufacturer () const
Returns the TrainingFileMessage data message's manufacturer field's current value.
Returns
the manufacturer field value.
Definition at line 91 of file trainingfilemessage.cpp.
 {
     Q_D(const TrainingFileMessage);
     return d->manufacturer;
 }
Referenced by setManufacturer().
product()
quint16 TrainingFileMessage::product () const
Returns the TrainingFileMessage data message's product field's current value.
Returns
the product field value.
Definition at line 102 of file trainingfilemessage.cpp.
 {
     Q_D(const TrainingFileMessage);
     return d->product;
 }
Referenced by setProduct().
serialNumber()
quint32z TrainingFileMessage::serialNumber () const
Returns the TrainingFileMessage data message's serialNumber field's current value.
Returns
the serialNumber field value.
Definition at line 113 of file trainingfilemessage.cpp.
 {
     Q_D(const TrainingFileMessage);
     return d->serialNumber;
 }
Referenced by setSerialNumber().
setManufacturer()
void TrainingFileMessage::setManufacturer (const Manufacturer manufacturer)
Sets the manufacturer field to manufacturer.
Parameters
manufacturer The field value to set.
Definition at line 155 of file trainingfilemessage.cpp.
 {
     Q_D(TrainingFileMessage);
     d->manufacturer = manufacturer;
 }
References manufacturer().
setProduct()
void TrainingFileMessage::setProduct (const quint16 product)
Sets the product field to product.
Parameters
product The field value to set.
Definition at line 165 of file trainingfilemessage.cpp.
 {
     Q_D(TrainingFileMessage);
     d->product = product;
 }
References product().
setSerialNumber()
void TrainingFileMessage::setSerialNumber (const quint32z serialNumber)
Sets the serialNumber field to serialNumber.
Parameters
serialNumber The field value to set.
Definition at line 175 of file trainingfilemessage.cpp.
 {
     Q_D(TrainingFileMessage);
     d->serialNumber = serialNumber;
 }
References serialNumber().
setTimeCreated()
void TrainingFileMessage::setTimeCreated (const DateTime timeCreated)
Sets the timeCreated field to timeCreated.
Parameters
timeCreated The field value to set.
Definition at line 185 of file trainingfilemessage.cpp.
 {
     Q_D(TrainingFileMessage);
     d->timeCreated = timeCreated;
 }
References timeCreated().
setTimestamp()
void TrainingFileMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 135 of file trainingfilemessage.cpp.
 {
     Q_D(TrainingFileMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setType()
void TrainingFileMessage::setType (const File type)
Sets the type field to type.
Parameters
type The field value to set.
Definition at line 145 of file trainingfilemessage.cpp.
 {
     Q_D(TrainingFileMessage);
     d->type = type;
 }
References type().
timeCreated()
DateTime TrainingFileMessage::timeCreated () const
Returns the TrainingFileMessage data message's timeCreated field's current value.
Returns
the timeCreated field value.
Definition at line 124 of file trainingfilemessage.cpp.
 {
     Q_D(const TrainingFileMessage);
     return d->timeCreated;
 }
Referenced by setTimeCreated().
timestamp()
DateTime TrainingFileMessage::timestamp () const
Returns the TrainingFileMessage data message's timestamp field's current value.
Returns
the timestamp field value.
Definition at line 69 of file trainingfilemessage.cpp.
 {
     Q_D(const TrainingFileMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
type()
File TrainingFileMessage::type () const
Returns the TrainingFileMessage data message's type field's current value.
Returns
the type field value.
Definition at line 80 of file trainingfilemessage.cpp.
 {
     Q_D(const TrainingFileMessage);
     return d->type;
 }
Referenced by setType().
The documentation for this class was generated from the following files:
trainingfilemessage.h
trainingfilemessage.cpp