QtFit: LapMessage Class Reference
LapMessage Class Reference
The LapMessage class represents a FIT LapMessage data message.
Public Member Functions
LapMessage ()
Constructs a LapMessage object.
MessageIndex messageIndex () const
Returns the LapMessage data message's messageIndex field's current value.
DateTime timestamp () const
Returns the LapMessage data message's timestamp field's current value.
Event event () const
Returns the LapMessage data message's event field's current value.
EventType eventType () const
Returns the LapMessage data message's eventType field's current value.
DateTime startTime () const
Returns the LapMessage data message's startTime field's current value.
qint32 startPositionLat () const
Returns the LapMessage data message's startPositionLat field's current value.
qint32 startPositionLong () const
Returns the LapMessage data message's startPositionLong field's current value.
qint32 endPositionLat () const
Returns the LapMessage data message's endPositionLat field's current value.
qint32 endPositionLong () const
Returns the LapMessage data message's endPositionLong field's current value.
quint32 totalElapsedTime () const
Returns the LapMessage data message's totalElapsedTime field's current value.
quint32 totalTimerTime () const
Returns the LapMessage data message's totalTimerTime field's current value.
quint32 totalDistance () const
Returns the LapMessage data message's totalDistance field's current value.
quint32 totalCycles () const
Returns the LapMessage data message's totalCycles field's current value.
quint16 totalCalories () const
Returns the LapMessage data message's totalCalories field's current value.
quint16 totalFatCalories () const
Returns the LapMessage data message's totalFatCalories field's current value.
quint16 avgSpeed () const
Returns the LapMessage data message's avgSpeed field's current value.
quint16 maxSpeed () const
Returns the LapMessage data message's maxSpeed field's current value.
quint8 avgHeartRate () const
Returns the LapMessage data message's avgHeartRate field's current value.
quint8 maxHeartRate () const
Returns the LapMessage data message's maxHeartRate field's current value.
quint8 avgCadence () const
Returns the LapMessage data message's avgCadence field's current value.
quint8 maxCadence () const
Returns the LapMessage data message's maxCadence field's current value.
quint16 avgPower () const
Returns the LapMessage data message's avgPower field's current value.
quint16 maxPower () const
Returns the LapMessage data message's maxPower field's current value.
quint16 totalAscent () const
Returns the LapMessage data message's totalAscent field's current value.
quint16 totalDescent () const
Returns the LapMessage data message's totalDescent field's current value.
Intensity intensity () const
Returns the LapMessage data message's intensity field's current value.
LapTrigger lapTrigger () const
Returns the LapMessage data message's lapTrigger field's current value.
Sport sport () const
Returns the LapMessage data message's sport field's current value.
quint8 eventGroup () const
Returns the LapMessage data message's eventGroup field's current value.
quint16 numLengths () const
Returns the LapMessage data message's numLengths field's current value.
quint16 normalizedPower () const
Returns the LapMessage data message's normalizedPower field's current value.
LeftRightBalance100 leftRightBalance () const
Returns the LapMessage data message's leftRightBalance field's current value.
quint16 firstLengthIndex () const
Returns the LapMessage data message's firstLengthIndex field's current value.
quint16 avgStrokeDistance () const
Returns the LapMessage data message's avgStrokeDistance field's current value.
SwimStroke swimStroke () const
Returns the LapMessage data message's swimStroke field's current value.
SubSport subSport () const
Returns the LapMessage data message's subSport field's current value.
quint16 numActiveLengths () const
Returns the LapMessage data message's numActiveLengths field's current value.
quint32 totalWork () const
Returns the LapMessage data message's totalWork field's current value.
quint16 avgAltitude () const
Returns the LapMessage data message's avgAltitude field's current value.
quint16 maxAltitude () const
Returns the LapMessage data message's maxAltitude field's current value.
quint8 gpsAccuracy () const
Returns the LapMessage data message's gpsAccuracy field's current value.
qint16 avgGrade () const
Returns the LapMessage data message's avgGrade field's current value.
qint16 avgPosGrade () const
Returns the LapMessage data message's avgPosGrade field's current value.
qint16 avgNegGrade () const
Returns the LapMessage data message's avgNegGrade field's current value.
qint16 maxPosGrade () const
Returns the LapMessage data message's maxPosGrade field's current value.
qint16 maxNegGrade () const
Returns the LapMessage data message's maxNegGrade field's current value.
qint8 avgTemperature () const
Returns the LapMessage data message's avgTemperature field's current value.
qint8 maxTemperature () const
Returns the LapMessage data message's maxTemperature field's current value.
quint32 totalMovingTime () const
Returns the LapMessage data message's totalMovingTime field's current value.
qint16 avgPosVerticalSpeed () const
Returns the LapMessage data message's avgPosVerticalSpeed field's current value.
qint16 avgNegVerticalSpeed () const
Returns the LapMessage data message's avgNegVerticalSpeed field's current value.
qint16 maxPosVerticalSpeed () const
Returns the LapMessage data message's maxPosVerticalSpeed field's current value.
qint16 maxNegVerticalSpeed () const
Returns the LapMessage data message's maxNegVerticalSpeed field's current value.
quint32 timeInHrZone () const
Returns the LapMessage data message's timeInHrZone field's current value.
quint32 timeInSpeedZone () const
Returns the LapMessage data message's timeInSpeedZone field's current value.
quint32 timeInCadenceZone () const
Returns the LapMessage data message's timeInCadenceZone field's current value.
quint32 timeInPowerZone () const
Returns the LapMessage data message's timeInPowerZone field's current value.
quint16 repetitionNum () const
Returns the LapMessage data message's repetitionNum field's current value.
quint16 minAltitude () const
Returns the LapMessage data message's minAltitude field's current value.
quint8 minHeartRate () const
Returns the LapMessage data message's minHeartRate field's current value.
MessageIndex wktStepIndex () const
Returns the LapMessage data message's wktStepIndex field's current value.
quint16 opponentScore () const
Returns the LapMessage data message's opponentScore field's current value.
quint16 strokeCount () const
Returns the LapMessage data message's strokeCount field's current value.
quint16 zoneCount () const
Returns the LapMessage data message's zoneCount field's current value.
quint16 avgVerticalOscillation () const
Returns the LapMessage data message's avgVerticalOscillation field's current value.
quint16 avgStanceTimePercent () const
Returns the LapMessage data message's avgStanceTimePercent field's current value.
quint16 avgStanceTime () const
Returns the LapMessage data message's avgStanceTime field's current value.
quint8 avgFractionalCadence () const
Returns the LapMessage data message's avgFractionalCadence field's current value.
quint8 maxFractionalCadence () const
Returns the LapMessage data message's maxFractionalCadence field's current value.
quint8 totalFractionalCycles () const
Returns the LapMessage data message's totalFractionalCycles field's current value.
quint16 playerScore () const
Returns the LapMessage data message's playerScore field's current value.
quint16 avgTotalHemoglobinConc () const
Returns the LapMessage data message's avgTotalHemoglobinConc field's current value.
quint16 minTotalHemoglobinConc () const
Returns the LapMessage data message's minTotalHemoglobinConc field's current value.
quint16 maxTotalHemoglobinConc () const
Returns the LapMessage data message's maxTotalHemoglobinConc field's current value.
quint16 avgSaturatedHemoglobinPercent () const
Returns the LapMessage data message's avgSaturatedHemoglobinPercent field's current value.
quint16 minSaturatedHemoglobinPercent () const
Returns the LapMessage data message's minSaturatedHemoglobinPercent field's current value.
quint16 maxSaturatedHemoglobinPercent () const
Returns the LapMessage data message's maxSaturatedHemoglobinPercent field's current value.
quint8 avgLeftTorqueEffectiveness () const
Returns the LapMessage data message's avgLeftTorqueEffectiveness field's current value.
quint8 avgRightTorqueEffectiveness () const
Returns the LapMessage data message's avgRightTorqueEffectiveness field's current value.
quint8 avgLeftPedalSmoothness () const
Returns the LapMessage data message's avgLeftPedalSmoothness field's current value.
quint8 avgRightPedalSmoothness () const
Returns the LapMessage data message's avgRightPedalSmoothness field's current value.
quint8 avgCombinedPedalSmoothness () const
Returns the LapMessage data message's avgCombinedPedalSmoothness field's current value.
quint32 timeStanding () const
Returns the LapMessage data message's timeStanding field's current value.
quint16 standCount () const
Returns the LapMessage data message's standCount field's current value.
qint8 avgLeftPco () const
Returns the LapMessage data message's avgLeftPco field's current value.
qint8 avgRightPco () const
Returns the LapMessage data message's avgRightPco field's current value.
quint8 avgLeftPowerPhase () const
Returns the LapMessage data message's avgLeftPowerPhase field's current value.
quint8 avgLeftPowerPhasePeak () const
Returns the LapMessage data message's avgLeftPowerPhasePeak field's current value.
quint8 avgRightPowerPhase () const
Returns the LapMessage data message's avgRightPowerPhase field's current value.
quint8 avgRightPowerPhasePeak () const
Returns the LapMessage data message's avgRightPowerPhasePeak field's current value.
quint16 avgPowerPosition () const
Returns the LapMessage data message's avgPowerPosition field's current value.
quint16 maxPowerPosition () const
Returns the LapMessage data message's maxPowerPosition field's current value.
quint8 avgCadencePosition () const
Returns the LapMessage data message's avgCadencePosition field's current value.
quint8 maxCadencePosition () const
Returns the LapMessage data message's maxCadencePosition field's current value.
quint32 enhancedAvgSpeed () const
Returns the LapMessage data message's enhancedAvgSpeed field's current value.
quint32 enhancedMaxSpeed () const
Returns the LapMessage data message's enhancedMaxSpeed field's current value.
quint32 enhancedAvgAltitude () const
Returns the LapMessage data message's enhancedAvgAltitude field's current value.
quint32 enhancedMinAltitude () const
Returns the LapMessage data message's enhancedMinAltitude field's current value.
quint32 enhancedMaxAltitude () const
Returns the LapMessage data message's enhancedMaxAltitude field's current value.
quint16 avgLevMotorPower () const
Returns the LapMessage data message's avgLevMotorPower field's current value.
quint16 maxLevMotorPower () const
Returns the LapMessage data message's maxLevMotorPower field's current value.
quint8 levBatteryConsumption () const
Returns the LapMessage data message's levBatteryConsumption field's current value.
quint16 avgVerticalRatio () const
Returns the LapMessage data message's avgVerticalRatio field's current value.
quint16 avgStanceTimeBalance () const
Returns the LapMessage data message's avgStanceTimeBalance field's current value.
quint16 avgStepLength () const
Returns the LapMessage data message's avgStepLength field's current value.
quint16 avgVam () const
Returns the LapMessage data message's avgVam field's current value.
float totalGrit () const
Returns the LapMessage data message's totalGrit field's current value.
float totalFlow () const
Returns the LapMessage data message's totalFlow field's current value.
quint16 jumpCount () const
Returns the LapMessage data message's jumpCount field's current value.
float avgGrit () const
Returns the LapMessage data message's avgGrit field's current value.
float avgFlow () const
Returns the LapMessage data message's avgFlow field's current value.
quint8 totalFractionalAscent () const
Returns the LapMessage data message's totalFractionalAscent field's current value.
quint8 totalFractionalDescent () const
Returns the LapMessage data message's totalFractionalDescent field's current value.
quint16 avgCoreTemperature () const
Returns the LapMessage data message's avgCoreTemperature field's current value.
quint16 minCoreTemperature () const
Returns the LapMessage data message's minCoreTemperature field's current value.
quint16 maxCoreTemperature () const
Returns the LapMessage data message's maxCoreTemperature field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setEvent (const Event event)
Sets the event field to event.
void setEventType (const EventType eventType)
Sets the eventType field to eventType.
void setStartTime (const DateTime startTime)
Sets the startTime field to startTime.
void setStartPositionLat (const qint32 startPositionLat)
Sets the startPositionLat field to startPositionLat.
void setStartPositionLong (const qint32 startPositionLong)
Sets the startPositionLong field to startPositionLong.
void setEndPositionLat (const qint32 endPositionLat)
Sets the endPositionLat field to endPositionLat.
void setEndPositionLong (const qint32 endPositionLong)
Sets the endPositionLong field to endPositionLong.
void setTotalElapsedTime (const quint32 totalElapsedTime)
Sets the totalElapsedTime field to totalElapsedTime.
void setTotalTimerTime (const quint32 totalTimerTime)
Sets the totalTimerTime field to totalTimerTime.
void setTotalDistance (const quint32 totalDistance)
Sets the totalDistance field to totalDistance.
void setTotalCycles (const quint32 totalCycles)
Sets the totalCycles field to totalCycles.
void setTotalCalories (const quint16 totalCalories)
Sets the totalCalories field to totalCalories.
void setTotalFatCalories (const quint16 totalFatCalories)
Sets the totalFatCalories field to totalFatCalories.
void setAvgSpeed (const quint16 avgSpeed)
Sets the avgSpeed field to avgSpeed.
void setMaxSpeed (const quint16 maxSpeed)
Sets the maxSpeed field to maxSpeed.
void setAvgHeartRate (const quint8 avgHeartRate)
Sets the avgHeartRate field to avgHeartRate.
void setMaxHeartRate (const quint8 maxHeartRate)
Sets the maxHeartRate field to maxHeartRate.
void setAvgCadence (const quint8 avgCadence)
Sets the avgCadence field to avgCadence.
void setMaxCadence (const quint8 maxCadence)
Sets the maxCadence field to maxCadence.
void setAvgPower (const quint16 avgPower)
Sets the avgPower field to avgPower.
void setMaxPower (const quint16 maxPower)
Sets the maxPower field to maxPower.
void setTotalAscent (const quint16 totalAscent)
Sets the totalAscent field to totalAscent.
void setTotalDescent (const quint16 totalDescent)
Sets the totalDescent field to totalDescent.
void setIntensity (const Intensity intensity)
Sets the intensity field to intensity.
void setLapTrigger (const LapTrigger lapTrigger)
Sets the lapTrigger field to lapTrigger.
void setSport (const Sport sport)
Sets the sport field to sport.
void setEventGroup (const quint8 eventGroup)
Sets the eventGroup field to eventGroup.
void setNumLengths (const quint16 numLengths)
Sets the numLengths field to numLengths.
void setNormalizedPower (const quint16 normalizedPower)
Sets the normalizedPower field to normalizedPower.
void setLeftRightBalance (const LeftRightBalance100 leftRightBalance)
Sets the leftRightBalance field to leftRightBalance.
void setFirstLengthIndex (const quint16 firstLengthIndex)
Sets the firstLengthIndex field to firstLengthIndex.
void setAvgStrokeDistance (const quint16 avgStrokeDistance)
Sets the avgStrokeDistance field to avgStrokeDistance.
void setSwimStroke (const SwimStroke swimStroke)
Sets the swimStroke field to swimStroke.
void setSubSport (const SubSport subSport)
Sets the subSport field to subSport.
void setNumActiveLengths (const quint16 numActiveLengths)
Sets the numActiveLengths field to numActiveLengths.
void setTotalWork (const quint32 totalWork)
Sets the totalWork field to totalWork.
void setAvgAltitude (const quint16 avgAltitude)
Sets the avgAltitude field to avgAltitude.
void setMaxAltitude (const quint16 maxAltitude)
Sets the maxAltitude field to maxAltitude.
void setGpsAccuracy (const quint8 gpsAccuracy)
Sets the gpsAccuracy field to gpsAccuracy.
void setAvgGrade (const qint16 avgGrade)
Sets the avgGrade field to avgGrade.
void setAvgPosGrade (const qint16 avgPosGrade)
Sets the avgPosGrade field to avgPosGrade.
void setAvgNegGrade (const qint16 avgNegGrade)
Sets the avgNegGrade field to avgNegGrade.
void setMaxPosGrade (const qint16 maxPosGrade)
Sets the maxPosGrade field to maxPosGrade.
void setMaxNegGrade (const qint16 maxNegGrade)
Sets the maxNegGrade field to maxNegGrade.
void setAvgTemperature (const qint8 avgTemperature)
Sets the avgTemperature field to avgTemperature.
void setMaxTemperature (const qint8 maxTemperature)
Sets the maxTemperature field to maxTemperature.
void setTotalMovingTime (const quint32 totalMovingTime)
Sets the totalMovingTime field to totalMovingTime.
void setAvgPosVerticalSpeed (const qint16 avgPosVerticalSpeed)
Sets the avgPosVerticalSpeed field to avgPosVerticalSpeed.
void setAvgNegVerticalSpeed (const qint16 avgNegVerticalSpeed)
Sets the avgNegVerticalSpeed field to avgNegVerticalSpeed.
void setMaxPosVerticalSpeed (const qint16 maxPosVerticalSpeed)
Sets the maxPosVerticalSpeed field to maxPosVerticalSpeed.
void setMaxNegVerticalSpeed (const qint16 maxNegVerticalSpeed)
Sets the maxNegVerticalSpeed field to maxNegVerticalSpeed.
void setTimeInHrZone (const quint32 timeInHrZone)
Sets the timeInHrZone field to timeInHrZone.
void setTimeInSpeedZone (const quint32 timeInSpeedZone)
Sets the timeInSpeedZone field to timeInSpeedZone.
void setTimeInCadenceZone (const quint32 timeInCadenceZone)
Sets the timeInCadenceZone field to timeInCadenceZone.
void setTimeInPowerZone (const quint32 timeInPowerZone)
Sets the timeInPowerZone field to timeInPowerZone.
void setRepetitionNum (const quint16 repetitionNum)
Sets the repetitionNum field to repetitionNum.
void setMinAltitude (const quint16 minAltitude)
Sets the minAltitude field to minAltitude.
void setMinHeartRate (const quint8 minHeartRate)
Sets the minHeartRate field to minHeartRate.
void setWktStepIndex (const MessageIndex wktStepIndex)
Sets the wktStepIndex field to wktStepIndex.
void setOpponentScore (const quint16 opponentScore)
Sets the opponentScore field to opponentScore.
void setStrokeCount (const quint16 strokeCount)
Sets the strokeCount field to strokeCount.
void setZoneCount (const quint16 zoneCount)
Sets the zoneCount field to zoneCount.
void setAvgVerticalOscillation (const quint16 avgVerticalOscillation)
Sets the avgVerticalOscillation field to avgVerticalOscillation.
void setAvgStanceTimePercent (const quint16 avgStanceTimePercent)
Sets the avgStanceTimePercent field to avgStanceTimePercent.
void setAvgStanceTime (const quint16 avgStanceTime)
Sets the avgStanceTime field to avgStanceTime.
void setAvgFractionalCadence (const quint8 avgFractionalCadence)
Sets the avgFractionalCadence field to avgFractionalCadence.
void setMaxFractionalCadence (const quint8 maxFractionalCadence)
Sets the maxFractionalCadence field to maxFractionalCadence.
void setTotalFractionalCycles (const quint8 totalFractionalCycles)
Sets the totalFractionalCycles field to totalFractionalCycles.
void setPlayerScore (const quint16 playerScore)
Sets the playerScore field to playerScore.
void setAvgTotalHemoglobinConc (const quint16 avgTotalHemoglobinConc)
Sets the avgTotalHemoglobinConc field to avgTotalHemoglobinConc.
void setMinTotalHemoglobinConc (const quint16 minTotalHemoglobinConc)
Sets the minTotalHemoglobinConc field to minTotalHemoglobinConc.
void setMaxTotalHemoglobinConc (const quint16 maxTotalHemoglobinConc)
Sets the maxTotalHemoglobinConc field to maxTotalHemoglobinConc.
void setAvgSaturatedHemoglobinPercent (const quint16 avgSaturatedHemoglobinPercent)
Sets the avgSaturatedHemoglobinPercent field to avgSaturatedHemoglobinPercent.
void setMinSaturatedHemoglobinPercent (const quint16 minSaturatedHemoglobinPercent)
Sets the minSaturatedHemoglobinPercent field to minSaturatedHemoglobinPercent.
void setMaxSaturatedHemoglobinPercent (const quint16 maxSaturatedHemoglobinPercent)
Sets the maxSaturatedHemoglobinPercent field to maxSaturatedHemoglobinPercent.
void setAvgLeftTorqueEffectiveness (const quint8 avgLeftTorqueEffectiveness)
Sets the avgLeftTorqueEffectiveness field to avgLeftTorqueEffectiveness.
void setAvgRightTorqueEffectiveness (const quint8 avgRightTorqueEffectiveness)
Sets the avgRightTorqueEffectiveness field to avgRightTorqueEffectiveness.
void setAvgLeftPedalSmoothness (const quint8 avgLeftPedalSmoothness)
Sets the avgLeftPedalSmoothness field to avgLeftPedalSmoothness.
void setAvgRightPedalSmoothness (const quint8 avgRightPedalSmoothness)
Sets the avgRightPedalSmoothness field to avgRightPedalSmoothness.
void setAvgCombinedPedalSmoothness (const quint8 avgCombinedPedalSmoothness)
Sets the avgCombinedPedalSmoothness field to avgCombinedPedalSmoothness.
void setTimeStanding (const quint32 timeStanding)
Sets the timeStanding field to timeStanding.
void setStandCount (const quint16 standCount)
Sets the standCount field to standCount.
void setAvgLeftPco (const qint8 avgLeftPco)
Sets the avgLeftPco field to avgLeftPco.
void setAvgRightPco (const qint8 avgRightPco)
Sets the avgRightPco field to avgRightPco.
void setAvgLeftPowerPhase (const quint8 avgLeftPowerPhase)
Sets the avgLeftPowerPhase field to avgLeftPowerPhase.
void setAvgLeftPowerPhasePeak (const quint8 avgLeftPowerPhasePeak)
Sets the avgLeftPowerPhasePeak field to avgLeftPowerPhasePeak.
void setAvgRightPowerPhase (const quint8 avgRightPowerPhase)
Sets the avgRightPowerPhase field to avgRightPowerPhase.
void setAvgRightPowerPhasePeak (const quint8 avgRightPowerPhasePeak)
Sets the avgRightPowerPhasePeak field to avgRightPowerPhasePeak.
void setAvgPowerPosition (const quint16 avgPowerPosition)
Sets the avgPowerPosition field to avgPowerPosition.
void setMaxPowerPosition (const quint16 maxPowerPosition)
Sets the maxPowerPosition field to maxPowerPosition.
void setAvgCadencePosition (const quint8 avgCadencePosition)
Sets the avgCadencePosition field to avgCadencePosition.
void setMaxCadencePosition (const quint8 maxCadencePosition)
Sets the maxCadencePosition field to maxCadencePosition.
void setEnhancedAvgSpeed (const quint32 enhancedAvgSpeed)
Sets the enhancedAvgSpeed field to enhancedAvgSpeed.
void setEnhancedMaxSpeed (const quint32 enhancedMaxSpeed)
Sets the enhancedMaxSpeed field to enhancedMaxSpeed.
void setEnhancedAvgAltitude (const quint32 enhancedAvgAltitude)
Sets the enhancedAvgAltitude field to enhancedAvgAltitude.
void setEnhancedMinAltitude (const quint32 enhancedMinAltitude)
Sets the enhancedMinAltitude field to enhancedMinAltitude.
void setEnhancedMaxAltitude (const quint32 enhancedMaxAltitude)
Sets the enhancedMaxAltitude field to enhancedMaxAltitude.
void setAvgLevMotorPower (const quint16 avgLevMotorPower)
Sets the avgLevMotorPower field to avgLevMotorPower.
void setMaxLevMotorPower (const quint16 maxLevMotorPower)
Sets the maxLevMotorPower field to maxLevMotorPower.
void setLevBatteryConsumption (const quint8 levBatteryConsumption)
Sets the levBatteryConsumption field to levBatteryConsumption.
void setAvgVerticalRatio (const quint16 avgVerticalRatio)
Sets the avgVerticalRatio field to avgVerticalRatio.
void setAvgStanceTimeBalance (const quint16 avgStanceTimeBalance)
Sets the avgStanceTimeBalance field to avgStanceTimeBalance.
void setAvgStepLength (const quint16 avgStepLength)
Sets the avgStepLength field to avgStepLength.
void setAvgVam (const quint16 avgVam)
Sets the avgVam field to avgVam.
void setTotalGrit (const float totalGrit)
Sets the totalGrit field to totalGrit.
void setTotalFlow (const float totalFlow)
Sets the totalFlow field to totalFlow.
void setJumpCount (const quint16 jumpCount)
Sets the jumpCount field to jumpCount.
void setAvgGrit (const float avgGrit)
Sets the avgGrit field to avgGrit.
void setAvgFlow (const float avgFlow)
Sets the avgFlow field to avgFlow.
void setTotalFractionalAscent (const quint8 totalFractionalAscent)
Sets the totalFractionalAscent field to totalFractionalAscent.
void setTotalFractionalDescent (const quint8 totalFractionalDescent)
Sets the totalFractionalDescent field to totalFractionalDescent.
void setAvgCoreTemperature (const quint16 avgCoreTemperature)
Sets the avgCoreTemperature field to avgCoreTemperature.
void setMinCoreTemperature (const quint16 minCoreTemperature)
Sets the minCoreTemperature field to minCoreTemperature.
void setMaxCoreTemperature (const quint16 maxCoreTemperature)
Sets the maxCoreTemperature field to maxCoreTemperature.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
LapMessage (LapMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The LapMessage class represents a FIT LapMessage data message.
See also
DataMessage
Definition at line 39 of file lapmessage.h.
Constructor & Destructor Documentation
LapMessage() [1/2]
LapMessage::LapMessage ()
Constructs a LapMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file lapmessage.cpp.
                        : AbstractDataMessage(new LapMessagePrivate(this))
 {
 }
LapMessage() [2/2]
LapMessage::LapMessage (LapMessagePrivate *const d) explicit protected
Constructs a LapMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file lapmessage.cpp.
                                                   : AbstractDataMessage(d)
 {
 }
Member Function Documentation
avgAltitude()
quint16 LapMessage::avgAltitude () const
Returns the LapMessage data message's avgAltitude field's current value.
Returns
the avgAltitude field value.
Definition at line 510 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgAltitude;
 }
Referenced by setAvgAltitude().
avgCadence()
quint8 LapMessage::avgCadence () const
Returns the LapMessage data message's avgCadence field's current value.
total_cycles / total_timer_time if non_zero_avg_cadence otherwise total_cycles / total_elapsed_time
Returns
the avgCadence field value.
Definition at line 294 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgCadence;
 }
Referenced by setAvgCadence().
avgCadencePosition()
quint8 LapMessage::avgCadencePosition () const
Returns the LapMessage data message's avgCadencePosition field's current value.
Average cadence by position. Data value indexes defined by rider_position_type.
Returns
the avgCadencePosition field value.
Definition at line 1148 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgCadencePosition;
 }
Referenced by setAvgCadencePosition().
avgCombinedPedalSmoothness()
quint8 LapMessage::avgCombinedPedalSmoothness () const
Returns the LapMessage data message's avgCombinedPedalSmoothness field's current value.
Returns
the avgCombinedPedalSmoothness field value.
Definition at line 1005 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgCombinedPedalSmoothness;
 }
Referenced by setAvgCombinedPedalSmoothness().
avgCoreTemperature()
quint16 LapMessage::avgCoreTemperature () const
Returns the LapMessage data message's avgCoreTemperature field's current value.
Returns
the avgCoreTemperature field value.
Definition at line 1403 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgCoreTemperature;
 }
Referenced by setAvgCoreTemperature().
avgFlow()
float LapMessage::avgFlow () const
Returns the LapMessage data message's avgFlow field's current value.
The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.
Returns
the avgFlow field value.
Definition at line 1366 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgFlow;
 }
Referenced by setAvgFlow().
avgFractionalCadence()
quint8 LapMessage::avgFractionalCadence () const
Returns the LapMessage data message's avgFractionalCadence field's current value.
fractional part of the avg_cadence
Returns
the avgFractionalCadence field value.
Definition at line 835 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgFractionalCadence;
 }
Referenced by setAvgFractionalCadence().
avgGrade()
qint16 LapMessage::avgGrade () const
Returns the LapMessage data message's avgGrade field's current value.
Returns
the avgGrade field value.
Definition at line 543 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgGrade;
 }
Referenced by setAvgGrade().
avgGrit()
float LapMessage::avgGrit () const
Returns the LapMessage data message's avgGrit field's current value.
The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.
Returns
the avgGrit field value.
Definition at line 1352 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgGrit;
 }
Referenced by setAvgGrit().
avgHeartRate()
quint8 LapMessage::avgHeartRate () const
Returns the LapMessage data message's avgHeartRate field's current value.
Returns
the avgHeartRate field value.
Definition at line 269 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgHeartRate;
 }
Referenced by setAvgHeartRate().
avgLeftPco()
qint8 LapMessage::avgLeftPco () const
Returns the LapMessage data message's avgLeftPco field's current value.
Average left platform center offset
Returns
the avgLeftPco field value.
Definition at line 1044 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgLeftPco;
 }
Referenced by setAvgLeftPco().
avgLeftPedalSmoothness()
quint8 LapMessage::avgLeftPedalSmoothness () const
Returns the LapMessage data message's avgLeftPedalSmoothness field's current value.
Returns
the avgLeftPedalSmoothness field value.
Definition at line 983 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgLeftPedalSmoothness;
 }
Referenced by setAvgLeftPedalSmoothness().
avgLeftPowerPhase()
quint8 LapMessage::avgLeftPowerPhase () const
Returns the LapMessage data message's avgLeftPowerPhase field's current value.
Average left power phase angles. Data value indexes defined by power_phase_type.
Returns
the avgLeftPowerPhase field value.
Definition at line 1070 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgLeftPowerPhase;
 }
Referenced by setAvgLeftPowerPhase().
avgLeftPowerPhasePeak()
quint8 LapMessage::avgLeftPowerPhasePeak () const
Returns the LapMessage data message's avgLeftPowerPhasePeak field's current value.
Average left power phase peak angles. Data value indexes defined by power_phase_type.
Returns
the avgLeftPowerPhasePeak field value.
Definition at line 1083 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgLeftPowerPhasePeak;
 }
Referenced by setAvgLeftPowerPhasePeak().
avgLeftTorqueEffectiveness()
quint8 LapMessage::avgLeftTorqueEffectiveness () const
Returns the LapMessage data message's avgLeftTorqueEffectiveness field's current value.
Returns
the avgLeftTorqueEffectiveness field value.
Definition at line 961 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgLeftTorqueEffectiveness;
 }
Referenced by setAvgLeftTorqueEffectiveness().
avgLevMotorPower()
quint16 LapMessage::avgLevMotorPower () const
Returns the LapMessage data message's avgLevMotorPower field's current value.
lev average motor power during lap
Returns
the avgLevMotorPower field value.
Definition at line 1229 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgLevMotorPower;
 }
Referenced by setAvgLevMotorPower().
avgNegGrade()
qint16 LapMessage::avgNegGrade () const
Returns the LapMessage data message's avgNegGrade field's current value.
Returns
the avgNegGrade field value.
Definition at line 565 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgNegGrade;
 }
Referenced by setAvgNegGrade().
avgNegVerticalSpeed()
qint16 LapMessage::avgNegVerticalSpeed () const
Returns the LapMessage data message's avgNegVerticalSpeed field's current value.
Returns
the avgNegVerticalSpeed field value.
Definition at line 642 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgNegVerticalSpeed;
 }
Referenced by setAvgNegVerticalSpeed().
avgPosGrade()
qint16 LapMessage::avgPosGrade () const
Returns the LapMessage data message's avgPosGrade field's current value.
Returns
the avgPosGrade field value.
Definition at line 554 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgPosGrade;
 }
Referenced by setAvgPosGrade().
avgPosVerticalSpeed()
qint16 LapMessage::avgPosVerticalSpeed () const
Returns the LapMessage data message's avgPosVerticalSpeed field's current value.
Returns
the avgPosVerticalSpeed field value.
Definition at line 631 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgPosVerticalSpeed;
 }
Referenced by setAvgPosVerticalSpeed().
avgPower()
quint16 LapMessage::avgPower () const
Returns the LapMessage data message's avgPower field's current value.
total_power / total_timer_time if non_zero_avg_power otherwise total_power / total_elapsed_time
Returns
the avgPower field value.
Definition at line 319 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgPower;
 }
Referenced by setAvgPower().
avgPowerPosition()
quint16 LapMessage::avgPowerPosition () const
Returns the LapMessage data message's avgPowerPosition field's current value.
Average power by position. Data value indexes defined by rider_position_type.
Returns
the avgPowerPosition field value.
Definition at line 1122 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgPowerPosition;
 }
Referenced by setAvgPowerPosition().
avgRightPco()
qint8 LapMessage::avgRightPco () const
Returns the LapMessage data message's avgRightPco field's current value.
Average right platform center offset
Returns
the avgRightPco field value.
Definition at line 1057 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgRightPco;
 }
Referenced by setAvgRightPco().
avgRightPedalSmoothness()
quint8 LapMessage::avgRightPedalSmoothness () const
Returns the LapMessage data message's avgRightPedalSmoothness field's current value.
Returns
the avgRightPedalSmoothness field value.
Definition at line 994 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgRightPedalSmoothness;
 }
Referenced by setAvgRightPedalSmoothness().
avgRightPowerPhase()
quint8 LapMessage::avgRightPowerPhase () const
Returns the LapMessage data message's avgRightPowerPhase field's current value.
Average right power phase angles. Data value indexes defined by power_phase_type.
Returns
the avgRightPowerPhase field value.
Definition at line 1096 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgRightPowerPhase;
 }
Referenced by setAvgRightPowerPhase().
avgRightPowerPhasePeak()
quint8 LapMessage::avgRightPowerPhasePeak () const
Returns the LapMessage data message's avgRightPowerPhasePeak field's current value.
Average right power phase peak angles. Data value indexes defined by power_phase_type.
Returns
the avgRightPowerPhasePeak field value.
Definition at line 1109 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgRightPowerPhasePeak;
 }
Referenced by setAvgRightPowerPhasePeak().
avgRightTorqueEffectiveness()
quint8 LapMessage::avgRightTorqueEffectiveness () const
Returns the LapMessage data message's avgRightTorqueEffectiveness field's current value.
Returns
the avgRightTorqueEffectiveness field value.
Definition at line 972 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgRightTorqueEffectiveness;
 }
Referenced by setAvgRightTorqueEffectiveness().
avgSaturatedHemoglobinPercent()
quint16 LapMessage::avgSaturatedHemoglobinPercent () const
Returns the LapMessage data message's avgSaturatedHemoglobinPercent field's current value.
Avg percentage of hemoglobin saturated with oxygen
Returns
the avgSaturatedHemoglobinPercent field value.
Definition at line 924 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgSaturatedHemoglobinPercent;
 }
Referenced by setAvgSaturatedHemoglobinPercent().
avgSpeed()
quint16 LapMessage::avgSpeed () const
Returns the LapMessage data message's avgSpeed field's current value.
Returns
the avgSpeed field value.
Definition at line 247 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgSpeed;
 }
Referenced by setAvgSpeed().
avgStanceTime()
quint16 LapMessage::avgStanceTime () const
Returns the LapMessage data message's avgStanceTime field's current value.
Returns
the avgStanceTime field value.
Definition at line 822 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgStanceTime;
 }
Referenced by setAvgStanceTime().
avgStanceTimeBalance()
quint16 LapMessage::avgStanceTimeBalance () const
Returns the LapMessage data message's avgStanceTimeBalance field's current value.
Returns
the avgStanceTimeBalance field value.
Definition at line 1277 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgStanceTimeBalance;
 }
Referenced by setAvgStanceTimeBalance().
avgStanceTimePercent()
quint16 LapMessage::avgStanceTimePercent () const
Returns the LapMessage data message's avgStanceTimePercent field's current value.
Returns
the avgStanceTimePercent field value.
Definition at line 811 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgStanceTimePercent;
 }
Referenced by setAvgStanceTimePercent().
avgStepLength()
quint16 LapMessage::avgStepLength () const
Returns the LapMessage data message's avgStepLength field's current value.
Returns
the avgStepLength field value.
Definition at line 1288 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgStepLength;
 }
Referenced by setAvgStepLength().
avgStrokeDistance()
quint16 LapMessage::avgStrokeDistance () const
Returns the LapMessage data message's avgStrokeDistance field's current value.
Returns
the avgStrokeDistance field value.
Definition at line 453 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgStrokeDistance;
 }
Referenced by setAvgStrokeDistance().
avgTemperature()
qint8 LapMessage::avgTemperature () const
Returns the LapMessage data message's avgTemperature field's current value.
Returns
the avgTemperature field value.
Definition at line 598 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgTemperature;
 }
Referenced by setAvgTemperature().
avgTotalHemoglobinConc()
quint16 LapMessage::avgTotalHemoglobinConc () const
Returns the LapMessage data message's avgTotalHemoglobinConc field's current value.
Avg saturated and unsaturated hemoglobin
Returns
the avgTotalHemoglobinConc field value.
Definition at line 885 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgTotalHemoglobinConc;
 }
Referenced by setAvgTotalHemoglobinConc().
avgVam()
quint16 LapMessage::avgVam () const
Returns the LapMessage data message's avgVam field's current value.
Returns
the avgVam field value.
Definition at line 1299 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgVam;
 }
Referenced by setAvgVam().
avgVerticalOscillation()
quint16 LapMessage::avgVerticalOscillation () const
Returns the LapMessage data message's avgVerticalOscillation field's current value.
Returns
the avgVerticalOscillation field value.
Definition at line 800 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgVerticalOscillation;
 }
Referenced by setAvgVerticalOscillation().
avgVerticalRatio()
quint16 LapMessage::avgVerticalRatio () const
Returns the LapMessage data message's avgVerticalRatio field's current value.
Returns
the avgVerticalRatio field value.
Definition at line 1266 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->avgVerticalRatio;
 }
Referenced by setAvgVerticalRatio().
endPositionLat()
qint32 LapMessage::endPositionLat () const
Returns the LapMessage data message's endPositionLat field's current value.
Returns
the endPositionLat field value.
Definition at line 153 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->endPositionLat;
 }
Referenced by setEndPositionLat().
endPositionLong()
qint32 LapMessage::endPositionLong () const
Returns the LapMessage data message's endPositionLong field's current value.
Returns
the endPositionLong field value.
Definition at line 164 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->endPositionLong;
 }
Referenced by setEndPositionLong().
enhancedAvgAltitude()
quint32 LapMessage::enhancedAvgAltitude () const
Returns the LapMessage data message's enhancedAvgAltitude field's current value.
Returns
the enhancedAvgAltitude field value.
Definition at line 1194 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->enhancedAvgAltitude;
 }
Referenced by setEnhancedAvgAltitude().
enhancedAvgSpeed()
quint32 LapMessage::enhancedAvgSpeed () const
Returns the LapMessage data message's enhancedAvgSpeed field's current value.
Returns
the enhancedAvgSpeed field value.
Definition at line 1172 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->enhancedAvgSpeed;
 }
Referenced by setEnhancedAvgSpeed().
enhancedMaxAltitude()
quint32 LapMessage::enhancedMaxAltitude () const
Returns the LapMessage data message's enhancedMaxAltitude field's current value.
Returns
the enhancedMaxAltitude field value.
Definition at line 1216 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->enhancedMaxAltitude;
 }
Referenced by setEnhancedMaxAltitude().
enhancedMaxSpeed()
quint32 LapMessage::enhancedMaxSpeed () const
Returns the LapMessage data message's enhancedMaxSpeed field's current value.
Returns
the enhancedMaxSpeed field value.
Definition at line 1183 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->enhancedMaxSpeed;
 }
Referenced by setEnhancedMaxSpeed().
enhancedMinAltitude()
quint32 LapMessage::enhancedMinAltitude () const
Returns the LapMessage data message's enhancedMinAltitude field's current value.
Returns
the enhancedMinAltitude field value.
Definition at line 1205 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->enhancedMinAltitude;
 }
Referenced by setEnhancedMinAltitude().
event()
Event LapMessage::event () const
Returns the LapMessage data message's event field's current value.
Returns
the event field value.
Definition at line 98 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->event;
 }
Referenced by setEvent().
eventGroup()
quint8 LapMessage::eventGroup () const
Returns the LapMessage data message's eventGroup field's current value.
Returns
the eventGroup field value.
Definition at line 396 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->eventGroup;
 }
Referenced by setEventGroup().
eventType()
EventType LapMessage::eventType () const
Returns the LapMessage data message's eventType field's current value.
Returns
the eventType field value.
Definition at line 109 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->eventType;
 }
Referenced by setEventType().
firstLengthIndex()
quint16 LapMessage::firstLengthIndex () const
Returns the LapMessage data message's firstLengthIndex field's current value.
Returns
the firstLengthIndex field value.
Definition at line 442 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->firstLengthIndex;
 }
Referenced by setFirstLengthIndex().
gpsAccuracy()
quint8 LapMessage::gpsAccuracy () const
Returns the LapMessage data message's gpsAccuracy field's current value.
Returns
the gpsAccuracy field value.
Definition at line 532 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->gpsAccuracy;
 }
Referenced by setGpsAccuracy().
intensity()
Intensity LapMessage::intensity () const
Returns the LapMessage data message's intensity field's current value.
Returns
the intensity field value.
Definition at line 363 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->intensity;
 }
Referenced by setIntensity().
jumpCount()
quint16 LapMessage::jumpCount () const
Returns the LapMessage data message's jumpCount field's current value.
Returns
the jumpCount field value.
Definition at line 1338 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->jumpCount;
 }
Referenced by setJumpCount().
lapTrigger()
LapTrigger LapMessage::lapTrigger () const
Returns the LapMessage data message's lapTrigger field's current value.
Returns
the lapTrigger field value.
Definition at line 374 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->lapTrigger;
 }
Referenced by setLapTrigger().
leftRightBalance()
LeftRightBalance100 LapMessage::leftRightBalance () const
Returns the LapMessage data message's leftRightBalance field's current value.
Returns
the leftRightBalance field value.
Definition at line 431 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->leftRightBalance;
 }
Referenced by setLeftRightBalance().
levBatteryConsumption()
quint8 LapMessage::levBatteryConsumption () const
Returns the LapMessage data message's levBatteryConsumption field's current value.
lev battery consumption during lap
Returns
the levBatteryConsumption field value.
Definition at line 1255 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->levBatteryConsumption;
 }
Referenced by setLevBatteryConsumption().
maxAltitude()
quint16 LapMessage::maxAltitude () const
Returns the LapMessage data message's maxAltitude field's current value.
Returns
the maxAltitude field value.
Definition at line 521 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->maxAltitude;
 }
Referenced by setMaxAltitude().
maxCadence()
quint8 LapMessage::maxCadence () const
Returns the LapMessage data message's maxCadence field's current value.
Returns
the maxCadence field value.
Definition at line 305 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->maxCadence;
 }
Referenced by setMaxCadence().
maxCadencePosition()
quint8 LapMessage::maxCadencePosition () const
Returns the LapMessage data message's maxCadencePosition field's current value.
Maximum cadence by position. Data value indexes defined by rider_position_type.
Returns
the maxCadencePosition field value.
Definition at line 1161 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->maxCadencePosition;
 }
Referenced by setMaxCadencePosition().
maxCoreTemperature()
quint16 LapMessage::maxCoreTemperature () const
Returns the LapMessage data message's maxCoreTemperature field's current value.
Returns
the maxCoreTemperature field value.
Definition at line 1425 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->maxCoreTemperature;
 }
Referenced by setMaxCoreTemperature().
maxFractionalCadence()
quint8 LapMessage::maxFractionalCadence () const
Returns the LapMessage data message's maxFractionalCadence field's current value.
fractional part of the max_cadence
Returns
the maxFractionalCadence field value.
Definition at line 848 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->maxFractionalCadence;
 }
Referenced by setMaxFractionalCadence().
maxHeartRate()
quint8 LapMessage::maxHeartRate () const
Returns the LapMessage data message's maxHeartRate field's current value.
Returns
the maxHeartRate field value.
Definition at line 280 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->maxHeartRate;
 }
Referenced by setMaxHeartRate().
maxLevMotorPower()
quint16 LapMessage::maxLevMotorPower () const
Returns the LapMessage data message's maxLevMotorPower field's current value.
lev maximum motor power during lap
Returns
the maxLevMotorPower field value.
Definition at line 1242 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->maxLevMotorPower;
 }
Referenced by setMaxLevMotorPower().
maxNegGrade()
qint16 LapMessage::maxNegGrade () const
Returns the LapMessage data message's maxNegGrade field's current value.
Returns
the maxNegGrade field value.
Definition at line 587 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->maxNegGrade;
 }
Referenced by setMaxNegGrade().
maxNegVerticalSpeed()
qint16 LapMessage::maxNegVerticalSpeed () const
Returns the LapMessage data message's maxNegVerticalSpeed field's current value.
Returns
the maxNegVerticalSpeed field value.
Definition at line 664 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->maxNegVerticalSpeed;
 }
Referenced by setMaxNegVerticalSpeed().
maxPosGrade()
qint16 LapMessage::maxPosGrade () const
Returns the LapMessage data message's maxPosGrade field's current value.
Returns
the maxPosGrade field value.
Definition at line 576 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->maxPosGrade;
 }
Referenced by setMaxPosGrade().
maxPosVerticalSpeed()
qint16 LapMessage::maxPosVerticalSpeed () const
Returns the LapMessage data message's maxPosVerticalSpeed field's current value.
Returns
the maxPosVerticalSpeed field value.
Definition at line 653 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->maxPosVerticalSpeed;
 }
Referenced by setMaxPosVerticalSpeed().
maxPower()
quint16 LapMessage::maxPower () const
Returns the LapMessage data message's maxPower field's current value.
Returns
the maxPower field value.
Definition at line 330 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->maxPower;
 }
Referenced by setMaxPower().
maxPowerPosition()
quint16 LapMessage::maxPowerPosition () const
Returns the LapMessage data message's maxPowerPosition field's current value.
Maximum power by position. Data value indexes defined by rider_position_type.
Returns
the maxPowerPosition field value.
Definition at line 1135 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->maxPowerPosition;
 }
Referenced by setMaxPowerPosition().
maxSaturatedHemoglobinPercent()
quint16 LapMessage::maxSaturatedHemoglobinPercent () const
Returns the LapMessage data message's maxSaturatedHemoglobinPercent field's current value.
Max percentage of hemoglobin saturated with oxygen
Returns
the maxSaturatedHemoglobinPercent field value.
Definition at line 950 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->maxSaturatedHemoglobinPercent;
 }
Referenced by setMaxSaturatedHemoglobinPercent().
maxSpeed()
quint16 LapMessage::maxSpeed () const
Returns the LapMessage data message's maxSpeed field's current value.
Returns
the maxSpeed field value.
Definition at line 258 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->maxSpeed;
 }
Referenced by setMaxSpeed().
maxTemperature()
qint8 LapMessage::maxTemperature () const
Returns the LapMessage data message's maxTemperature field's current value.
Returns
the maxTemperature field value.
Definition at line 609 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->maxTemperature;
 }
Referenced by setMaxTemperature().
maxTotalHemoglobinConc()
quint16 LapMessage::maxTotalHemoglobinConc () const
Returns the LapMessage data message's maxTotalHemoglobinConc field's current value.
Max saturated and unsaturated hemoglobin
Returns
the maxTotalHemoglobinConc field value.
Definition at line 911 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->maxTotalHemoglobinConc;
 }
Referenced by setMaxTotalHemoglobinConc().
messageIndex()
MessageIndex LapMessage::messageIndex () const
Returns the LapMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 74 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
minAltitude()
quint16 LapMessage::minAltitude () const
Returns the LapMessage data message's minAltitude field's current value.
Returns
the minAltitude field value.
Definition at line 730 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->minAltitude;
 }
Referenced by setMinAltitude().
minCoreTemperature()
quint16 LapMessage::minCoreTemperature () const
Returns the LapMessage data message's minCoreTemperature field's current value.
Returns
the minCoreTemperature field value.
Definition at line 1414 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->minCoreTemperature;
 }
Referenced by setMinCoreTemperature().
minHeartRate()
quint8 LapMessage::minHeartRate () const
Returns the LapMessage data message's minHeartRate field's current value.
Returns
the minHeartRate field value.
Definition at line 741 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->minHeartRate;
 }
Referenced by setMinHeartRate().
minSaturatedHemoglobinPercent()
quint16 LapMessage::minSaturatedHemoglobinPercent () const
Returns the LapMessage data message's minSaturatedHemoglobinPercent field's current value.
Min percentage of hemoglobin saturated with oxygen
Returns
the minSaturatedHemoglobinPercent field value.
Definition at line 937 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->minSaturatedHemoglobinPercent;
 }
Referenced by setMinSaturatedHemoglobinPercent().
minTotalHemoglobinConc()
quint16 LapMessage::minTotalHemoglobinConc () const
Returns the LapMessage data message's minTotalHemoglobinConc field's current value.
Min saturated and unsaturated hemoglobin
Returns
the minTotalHemoglobinConc field value.
Definition at line 898 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->minTotalHemoglobinConc;
 }
Referenced by setMinTotalHemoglobinConc().
normalizedPower()
quint16 LapMessage::normalizedPower () const
Returns the LapMessage data message's normalizedPower field's current value.
Returns
the normalizedPower field value.
Definition at line 420 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->normalizedPower;
 }
Referenced by setNormalizedPower().
numActiveLengths()
quint16 LapMessage::numActiveLengths () const
Returns the LapMessage data message's numActiveLengths field's current value.
of active lengths of swim pool
Returns
the numActiveLengths field value.
Definition at line 488 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->numActiveLengths;
 }
Referenced by setNumActiveLengths().
numLengths()
quint16 LapMessage::numLengths () const
Returns the LapMessage data message's numLengths field's current value.
of lengths of swim pool
Returns
the numLengths field value.
Definition at line 409 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->numLengths;
 }
Referenced by setNumLengths().
opponentScore()
quint16 LapMessage::opponentScore () const
Returns the LapMessage data message's opponentScore field's current value.
Returns
the opponentScore field value.
Definition at line 763 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->opponentScore;
 }
Referenced by setOpponentScore().
playerScore()
quint16 LapMessage::playerScore () const
Returns the LapMessage data message's playerScore field's current value.
Returns
the playerScore field value.
Definition at line 872 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->playerScore;
 }
Referenced by setPlayerScore().
repetitionNum()
quint16 LapMessage::repetitionNum () const
Returns the LapMessage data message's repetitionNum field's current value.
Returns
the repetitionNum field value.
Definition at line 719 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->repetitionNum;
 }
Referenced by setRepetitionNum().
setAvgAltitude()
void LapMessage::setAvgAltitude (const quint16 avgAltitude)
Sets the avgAltitude field to avgAltitude.
Parameters
avgAltitude The field value to set.
Definition at line 1816 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgAltitude = avgAltitude;
 }
References avgAltitude().
setAvgCadence()
void LapMessage::setAvgCadence (const quint8 avgCadence)
Sets the avgCadence field to avgCadence.
Parameters
avgCadence The field value to set.
Definition at line 1626 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgCadence = avgCadence;
 }
References avgCadence().
setAvgCadencePosition()
void LapMessage::setAvgCadencePosition (const quint8 avgCadencePosition)
Sets the avgCadencePosition field to avgCadencePosition.
Parameters
avgCadencePosition The field value to set.
Definition at line 2356 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgCadencePosition = avgCadencePosition;
 }
References avgCadencePosition().
setAvgCombinedPedalSmoothness()
void LapMessage::setAvgCombinedPedalSmoothness (const quint8 avgCombinedPedalSmoothness)
Sets the avgCombinedPedalSmoothness field to avgCombinedPedalSmoothness.
Parameters
avgCombinedPedalSmoothness The field value to set.
Definition at line 2246 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgCombinedPedalSmoothness = avgCombinedPedalSmoothness;
 }
References avgCombinedPedalSmoothness().
setAvgCoreTemperature()
void LapMessage::setAvgCoreTemperature (const quint16 avgCoreTemperature)
Sets the avgCoreTemperature field to avgCoreTemperature.
Parameters
avgCoreTemperature The field value to set.
Definition at line 2566 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgCoreTemperature = avgCoreTemperature;
 }
References avgCoreTemperature().
setAvgFlow()
void LapMessage::setAvgFlow (const float avgFlow)
Sets the avgFlow field to avgFlow.
Parameters
avgFlow The field value to set.
Definition at line 2536 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgFlow = avgFlow;
 }
References avgFlow().
setAvgFractionalCadence()
void LapMessage::setAvgFractionalCadence (const quint8 avgFractionalCadence)
Sets the avgFractionalCadence field to avgFractionalCadence.
Parameters
avgFractionalCadence The field value to set.
Definition at line 2106 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgFractionalCadence = avgFractionalCadence;
 }
References avgFractionalCadence().
setAvgGrade()
void LapMessage::setAvgGrade (const qint16 avgGrade)
Sets the avgGrade field to avgGrade.
Parameters
avgGrade The field value to set.
Definition at line 1846 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgGrade = avgGrade;
 }
References avgGrade().
setAvgGrit()
void LapMessage::setAvgGrit (const float avgGrit)
Sets the avgGrit field to avgGrit.
Parameters
avgGrit The field value to set.
Definition at line 2526 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgGrit = avgGrit;
 }
References avgGrit().
setAvgHeartRate()
void LapMessage::setAvgHeartRate (const quint8 avgHeartRate)
Sets the avgHeartRate field to avgHeartRate.
Parameters
avgHeartRate The field value to set.
Definition at line 1606 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgHeartRate = avgHeartRate;
 }
References avgHeartRate().
setAvgLeftPco()
void LapMessage::setAvgLeftPco (const qint8 avgLeftPco)
Sets the avgLeftPco field to avgLeftPco.
Parameters
avgLeftPco The field value to set.
Definition at line 2276 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgLeftPco = avgLeftPco;
 }
References avgLeftPco().
setAvgLeftPedalSmoothness()
void LapMessage::setAvgLeftPedalSmoothness (const quint8 avgLeftPedalSmoothness)
Sets the avgLeftPedalSmoothness field to avgLeftPedalSmoothness.
Parameters
avgLeftPedalSmoothness The field value to set.
Definition at line 2226 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgLeftPedalSmoothness = avgLeftPedalSmoothness;
 }
References avgLeftPedalSmoothness().
setAvgLeftPowerPhase()
void LapMessage::setAvgLeftPowerPhase (const quint8 avgLeftPowerPhase)
Sets the avgLeftPowerPhase field to avgLeftPowerPhase.
Parameters
avgLeftPowerPhase The field value to set.
Definition at line 2296 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgLeftPowerPhase = avgLeftPowerPhase;
 }
References avgLeftPowerPhase().
setAvgLeftPowerPhasePeak()
void LapMessage::setAvgLeftPowerPhasePeak (const quint8 avgLeftPowerPhasePeak)
Sets the avgLeftPowerPhasePeak field to avgLeftPowerPhasePeak.
Parameters
avgLeftPowerPhasePeak The field value to set.
Definition at line 2306 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgLeftPowerPhasePeak = avgLeftPowerPhasePeak;
 }
References avgLeftPowerPhasePeak().
setAvgLeftTorqueEffectiveness()
void LapMessage::setAvgLeftTorqueEffectiveness (const quint8 avgLeftTorqueEffectiveness)
Sets the avgLeftTorqueEffectiveness field to avgLeftTorqueEffectiveness.
Parameters
avgLeftTorqueEffectiveness The field value to set.
Definition at line 2206 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgLeftTorqueEffectiveness = avgLeftTorqueEffectiveness;
 }
References avgLeftTorqueEffectiveness().
setAvgLevMotorPower()
void LapMessage::setAvgLevMotorPower (const quint16 avgLevMotorPower)
Sets the avgLevMotorPower field to avgLevMotorPower.
Parameters
avgLevMotorPower The field value to set.
Definition at line 2426 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgLevMotorPower = avgLevMotorPower;
 }
References avgLevMotorPower().
setAvgNegGrade()
void LapMessage::setAvgNegGrade (const qint16 avgNegGrade)
Sets the avgNegGrade field to avgNegGrade.
Parameters
avgNegGrade The field value to set.
Definition at line 1866 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgNegGrade = avgNegGrade;
 }
References avgNegGrade().
setAvgNegVerticalSpeed()
void LapMessage::setAvgNegVerticalSpeed (const qint16 avgNegVerticalSpeed)
Sets the avgNegVerticalSpeed field to avgNegVerticalSpeed.
Parameters
avgNegVerticalSpeed The field value to set.
Definition at line 1936 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgNegVerticalSpeed = avgNegVerticalSpeed;
 }
References avgNegVerticalSpeed().
setAvgPosGrade()
void LapMessage::setAvgPosGrade (const qint16 avgPosGrade)
Sets the avgPosGrade field to avgPosGrade.
Parameters
avgPosGrade The field value to set.
Definition at line 1856 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgPosGrade = avgPosGrade;
 }
References avgPosGrade().
setAvgPosVerticalSpeed()
void LapMessage::setAvgPosVerticalSpeed (const qint16 avgPosVerticalSpeed)
Sets the avgPosVerticalSpeed field to avgPosVerticalSpeed.
Parameters
avgPosVerticalSpeed The field value to set.
Definition at line 1926 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgPosVerticalSpeed = avgPosVerticalSpeed;
 }
References avgPosVerticalSpeed().
setAvgPower()
void LapMessage::setAvgPower (const quint16 avgPower)
Sets the avgPower field to avgPower.
Parameters
avgPower The field value to set.
Definition at line 1646 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgPower = avgPower;
 }
References avgPower().
setAvgPowerPosition()
void LapMessage::setAvgPowerPosition (const quint16 avgPowerPosition)
Sets the avgPowerPosition field to avgPowerPosition.
Parameters
avgPowerPosition The field value to set.
Definition at line 2336 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgPowerPosition = avgPowerPosition;
 }
References avgPowerPosition().
setAvgRightPco()
void LapMessage::setAvgRightPco (const qint8 avgRightPco)
Sets the avgRightPco field to avgRightPco.
Parameters
avgRightPco The field value to set.
Definition at line 2286 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgRightPco = avgRightPco;
 }
References avgRightPco().
setAvgRightPedalSmoothness()
void LapMessage::setAvgRightPedalSmoothness (const quint8 avgRightPedalSmoothness)
Sets the avgRightPedalSmoothness field to avgRightPedalSmoothness.
Parameters
avgRightPedalSmoothness The field value to set.
Definition at line 2236 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgRightPedalSmoothness = avgRightPedalSmoothness;
 }
References avgRightPedalSmoothness().
setAvgRightPowerPhase()
void LapMessage::setAvgRightPowerPhase (const quint8 avgRightPowerPhase)
Sets the avgRightPowerPhase field to avgRightPowerPhase.
Parameters
avgRightPowerPhase The field value to set.
Definition at line 2316 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgRightPowerPhase = avgRightPowerPhase;
 }
References avgRightPowerPhase().
setAvgRightPowerPhasePeak()
void LapMessage::setAvgRightPowerPhasePeak (const quint8 avgRightPowerPhasePeak)
Sets the avgRightPowerPhasePeak field to avgRightPowerPhasePeak.
Parameters
avgRightPowerPhasePeak The field value to set.
Definition at line 2326 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgRightPowerPhasePeak = avgRightPowerPhasePeak;
 }
References avgRightPowerPhasePeak().
setAvgRightTorqueEffectiveness()
void LapMessage::setAvgRightTorqueEffectiveness (const quint8 avgRightTorqueEffectiveness)
Sets the avgRightTorqueEffectiveness field to avgRightTorqueEffectiveness.
Parameters
avgRightTorqueEffectiveness The field value to set.
Definition at line 2216 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgRightTorqueEffectiveness = avgRightTorqueEffectiveness;
 }
References avgRightTorqueEffectiveness().
setAvgSaturatedHemoglobinPercent()
void LapMessage::setAvgSaturatedHemoglobinPercent (const quint16 avgSaturatedHemoglobinPercent)
Sets the avgSaturatedHemoglobinPercent field to avgSaturatedHemoglobinPercent.
Parameters
avgSaturatedHemoglobinPercent The field value to set.
Definition at line 2176 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgSaturatedHemoglobinPercent = avgSaturatedHemoglobinPercent;
 }
References avgSaturatedHemoglobinPercent().
setAvgSpeed()
void LapMessage::setAvgSpeed (const quint16 avgSpeed)
Sets the avgSpeed field to avgSpeed.
Parameters
avgSpeed The field value to set.
Definition at line 1586 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgSpeed = avgSpeed;
 }
References avgSpeed().
setAvgStanceTime()
void LapMessage::setAvgStanceTime (const quint16 avgStanceTime)
Sets the avgStanceTime field to avgStanceTime.
Parameters
avgStanceTime The field value to set.
Definition at line 2096 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgStanceTime = avgStanceTime;
 }
References avgStanceTime().
setAvgStanceTimeBalance()
void LapMessage::setAvgStanceTimeBalance (const quint16 avgStanceTimeBalance)
Sets the avgStanceTimeBalance field to avgStanceTimeBalance.
Parameters
avgStanceTimeBalance The field value to set.
Definition at line 2466 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgStanceTimeBalance = avgStanceTimeBalance;
 }
References avgStanceTimeBalance().
setAvgStanceTimePercent()
void LapMessage::setAvgStanceTimePercent (const quint16 avgStanceTimePercent)
Sets the avgStanceTimePercent field to avgStanceTimePercent.
Parameters
avgStanceTimePercent The field value to set.
Definition at line 2086 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgStanceTimePercent = avgStanceTimePercent;
 }
References avgStanceTimePercent().
setAvgStepLength()
void LapMessage::setAvgStepLength (const quint16 avgStepLength)
Sets the avgStepLength field to avgStepLength.
Parameters
avgStepLength The field value to set.
Definition at line 2476 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgStepLength = avgStepLength;
 }
References avgStepLength().
setAvgStrokeDistance()
void LapMessage::setAvgStrokeDistance (const quint16 avgStrokeDistance)
Sets the avgStrokeDistance field to avgStrokeDistance.
Parameters
avgStrokeDistance The field value to set.
Definition at line 1766 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgStrokeDistance = avgStrokeDistance;
 }
References avgStrokeDistance().
setAvgTemperature()
void LapMessage::setAvgTemperature (const qint8 avgTemperature)
Sets the avgTemperature field to avgTemperature.
Parameters
avgTemperature The field value to set.
Definition at line 1896 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgTemperature = avgTemperature;
 }
References avgTemperature().
setAvgTotalHemoglobinConc()
void LapMessage::setAvgTotalHemoglobinConc (const quint16 avgTotalHemoglobinConc)
Sets the avgTotalHemoglobinConc field to avgTotalHemoglobinConc.
Parameters
avgTotalHemoglobinConc The field value to set.
Definition at line 2146 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgTotalHemoglobinConc = avgTotalHemoglobinConc;
 }
References avgTotalHemoglobinConc().
setAvgVam()
void LapMessage::setAvgVam (const quint16 avgVam)
Sets the avgVam field to avgVam.
Parameters
avgVam The field value to set.
Definition at line 2486 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgVam = avgVam;
 }
References avgVam().
setAvgVerticalOscillation()
void LapMessage::setAvgVerticalOscillation (const quint16 avgVerticalOscillation)
Sets the avgVerticalOscillation field to avgVerticalOscillation.
Parameters
avgVerticalOscillation The field value to set.
Definition at line 2076 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgVerticalOscillation = avgVerticalOscillation;
 }
References avgVerticalOscillation().
setAvgVerticalRatio()
void LapMessage::setAvgVerticalRatio (const quint16 avgVerticalRatio)
Sets the avgVerticalRatio field to avgVerticalRatio.
Parameters
avgVerticalRatio The field value to set.
Definition at line 2456 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->avgVerticalRatio = avgVerticalRatio;
 }
References avgVerticalRatio().
setEndPositionLat()
void LapMessage::setEndPositionLat (const qint32 endPositionLat)
Sets the endPositionLat field to endPositionLat.
Parameters
endPositionLat The field value to set.
Definition at line 1506 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->endPositionLat = endPositionLat;
 }
References endPositionLat().
setEndPositionLong()
void LapMessage::setEndPositionLong (const qint32 endPositionLong)
Sets the endPositionLong field to endPositionLong.
Parameters
endPositionLong The field value to set.
Definition at line 1516 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->endPositionLong = endPositionLong;
 }
References endPositionLong().
setEnhancedAvgAltitude()
void LapMessage::setEnhancedAvgAltitude (const quint32 enhancedAvgAltitude)
Sets the enhancedAvgAltitude field to enhancedAvgAltitude.
Parameters
enhancedAvgAltitude The field value to set.
Definition at line 2396 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->enhancedAvgAltitude = enhancedAvgAltitude;
 }
References enhancedAvgAltitude().
setEnhancedAvgSpeed()
void LapMessage::setEnhancedAvgSpeed (const quint32 enhancedAvgSpeed)
Sets the enhancedAvgSpeed field to enhancedAvgSpeed.
Parameters
enhancedAvgSpeed The field value to set.
Definition at line 2376 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->enhancedAvgSpeed = enhancedAvgSpeed;
 }
References enhancedAvgSpeed().
setEnhancedMaxAltitude()
void LapMessage::setEnhancedMaxAltitude (const quint32 enhancedMaxAltitude)
Sets the enhancedMaxAltitude field to enhancedMaxAltitude.
Parameters
enhancedMaxAltitude The field value to set.
Definition at line 2416 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->enhancedMaxAltitude = enhancedMaxAltitude;
 }
References enhancedMaxAltitude().
setEnhancedMaxSpeed()
void LapMessage::setEnhancedMaxSpeed (const quint32 enhancedMaxSpeed)
Sets the enhancedMaxSpeed field to enhancedMaxSpeed.
Parameters
enhancedMaxSpeed The field value to set.
Definition at line 2386 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->enhancedMaxSpeed = enhancedMaxSpeed;
 }
References enhancedMaxSpeed().
setEnhancedMinAltitude()
void LapMessage::setEnhancedMinAltitude (const quint32 enhancedMinAltitude)
Sets the enhancedMinAltitude field to enhancedMinAltitude.
Parameters
enhancedMinAltitude The field value to set.
Definition at line 2406 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->enhancedMinAltitude = enhancedMinAltitude;
 }
References enhancedMinAltitude().
setEvent()
void LapMessage::setEvent (const Event event)
Sets the event field to event.
Parameters
event The field value to set.
Definition at line 1456 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->event = event;
 }
References event().
setEventGroup()
void LapMessage::setEventGroup (const quint8 eventGroup)
Sets the eventGroup field to eventGroup.
Parameters
eventGroup The field value to set.
Definition at line 1716 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->eventGroup = eventGroup;
 }
References eventGroup().
setEventType()
void LapMessage::setEventType (const EventType eventType)
Sets the eventType field to eventType.
Parameters
eventType The field value to set.
Definition at line 1466 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->eventType = eventType;
 }
References eventType().
setFirstLengthIndex()
void LapMessage::setFirstLengthIndex (const quint16 firstLengthIndex)
Sets the firstLengthIndex field to firstLengthIndex.
Parameters
firstLengthIndex The field value to set.
Definition at line 1756 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->firstLengthIndex = firstLengthIndex;
 }
References firstLengthIndex().
setGpsAccuracy()
void LapMessage::setGpsAccuracy (const quint8 gpsAccuracy)
Sets the gpsAccuracy field to gpsAccuracy.
Parameters
gpsAccuracy The field value to set.
Definition at line 1836 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->gpsAccuracy = gpsAccuracy;
 }
References gpsAccuracy().
setIntensity()
void LapMessage::setIntensity (const Intensity intensity)
Sets the intensity field to intensity.
Parameters
intensity The field value to set.
Definition at line 1686 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->intensity = intensity;
 }
References intensity().
setJumpCount()
void LapMessage::setJumpCount (const quint16 jumpCount)
Sets the jumpCount field to jumpCount.
Parameters
jumpCount The field value to set.
Definition at line 2516 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->jumpCount = jumpCount;
 }
References jumpCount().
setLapTrigger()
void LapMessage::setLapTrigger (const LapTrigger lapTrigger)
Sets the lapTrigger field to lapTrigger.
Parameters
lapTrigger The field value to set.
Definition at line 1696 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->lapTrigger = lapTrigger;
 }
References lapTrigger().
setLeftRightBalance()
void LapMessage::setLeftRightBalance (const LeftRightBalance100 leftRightBalance)
Sets the leftRightBalance field to leftRightBalance.
Parameters
leftRightBalance The field value to set.
Definition at line 1746 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->leftRightBalance = leftRightBalance;
 }
References leftRightBalance().
setLevBatteryConsumption()
void LapMessage::setLevBatteryConsumption (const quint8 levBatteryConsumption)
Sets the levBatteryConsumption field to levBatteryConsumption.
Parameters
levBatteryConsumption The field value to set.
Definition at line 2446 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->levBatteryConsumption = levBatteryConsumption;
 }
References levBatteryConsumption().
setMaxAltitude()
void LapMessage::setMaxAltitude (const quint16 maxAltitude)
Sets the maxAltitude field to maxAltitude.
Parameters
maxAltitude The field value to set.
Definition at line 1826 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->maxAltitude = maxAltitude;
 }
References maxAltitude().
setMaxCadence()
void LapMessage::setMaxCadence (const quint8 maxCadence)
Sets the maxCadence field to maxCadence.
Parameters
maxCadence The field value to set.
Definition at line 1636 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->maxCadence = maxCadence;
 }
References maxCadence().
setMaxCadencePosition()
void LapMessage::setMaxCadencePosition (const quint8 maxCadencePosition)
Sets the maxCadencePosition field to maxCadencePosition.
Parameters
maxCadencePosition The field value to set.
Definition at line 2366 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->maxCadencePosition = maxCadencePosition;
 }
References maxCadencePosition().
setMaxCoreTemperature()
void LapMessage::setMaxCoreTemperature (const quint16 maxCoreTemperature)
Sets the maxCoreTemperature field to maxCoreTemperature.
Parameters
maxCoreTemperature The field value to set.
Definition at line 2586 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->maxCoreTemperature = maxCoreTemperature;
 }
References maxCoreTemperature().
setMaxFractionalCadence()
void LapMessage::setMaxFractionalCadence (const quint8 maxFractionalCadence)
Sets the maxFractionalCadence field to maxFractionalCadence.
Parameters
maxFractionalCadence The field value to set.
Definition at line 2116 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->maxFractionalCadence = maxFractionalCadence;
 }
References maxFractionalCadence().
setMaxHeartRate()
void LapMessage::setMaxHeartRate (const quint8 maxHeartRate)
Sets the maxHeartRate field to maxHeartRate.
Parameters
maxHeartRate The field value to set.
Definition at line 1616 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->maxHeartRate = maxHeartRate;
 }
References maxHeartRate().
setMaxLevMotorPower()
void LapMessage::setMaxLevMotorPower (const quint16 maxLevMotorPower)
Sets the maxLevMotorPower field to maxLevMotorPower.
Parameters
maxLevMotorPower The field value to set.
Definition at line 2436 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->maxLevMotorPower = maxLevMotorPower;
 }
References maxLevMotorPower().
setMaxNegGrade()
void LapMessage::setMaxNegGrade (const qint16 maxNegGrade)
Sets the maxNegGrade field to maxNegGrade.
Parameters
maxNegGrade The field value to set.
Definition at line 1886 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->maxNegGrade = maxNegGrade;
 }
References maxNegGrade().
setMaxNegVerticalSpeed()
void LapMessage::setMaxNegVerticalSpeed (const qint16 maxNegVerticalSpeed)
Sets the maxNegVerticalSpeed field to maxNegVerticalSpeed.
Parameters
maxNegVerticalSpeed The field value to set.
Definition at line 1956 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->maxNegVerticalSpeed = maxNegVerticalSpeed;
 }
References maxNegVerticalSpeed().
setMaxPosGrade()
void LapMessage::setMaxPosGrade (const qint16 maxPosGrade)
Sets the maxPosGrade field to maxPosGrade.
Parameters
maxPosGrade The field value to set.
Definition at line 1876 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->maxPosGrade = maxPosGrade;
 }
References maxPosGrade().
setMaxPosVerticalSpeed()
void LapMessage::setMaxPosVerticalSpeed (const qint16 maxPosVerticalSpeed)
Sets the maxPosVerticalSpeed field to maxPosVerticalSpeed.
Parameters
maxPosVerticalSpeed The field value to set.
Definition at line 1946 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->maxPosVerticalSpeed = maxPosVerticalSpeed;
 }
References maxPosVerticalSpeed().
setMaxPower()
void LapMessage::setMaxPower (const quint16 maxPower)
Sets the maxPower field to maxPower.
Parameters
maxPower The field value to set.
Definition at line 1656 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->maxPower = maxPower;
 }
References maxPower().
setMaxPowerPosition()
void LapMessage::setMaxPowerPosition (const quint16 maxPowerPosition)
Sets the maxPowerPosition field to maxPowerPosition.
Parameters
maxPowerPosition The field value to set.
Definition at line 2346 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->maxPowerPosition = maxPowerPosition;
 }
References maxPowerPosition().
setMaxSaturatedHemoglobinPercent()
void LapMessage::setMaxSaturatedHemoglobinPercent (const quint16 maxSaturatedHemoglobinPercent)
Sets the maxSaturatedHemoglobinPercent field to maxSaturatedHemoglobinPercent.
Parameters
maxSaturatedHemoglobinPercent The field value to set.
Definition at line 2196 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->maxSaturatedHemoglobinPercent = maxSaturatedHemoglobinPercent;
 }
References maxSaturatedHemoglobinPercent().
setMaxSpeed()
void LapMessage::setMaxSpeed (const quint16 maxSpeed)
Sets the maxSpeed field to maxSpeed.
Parameters
maxSpeed The field value to set.
Definition at line 1596 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->maxSpeed = maxSpeed;
 }
References maxSpeed().
setMaxTemperature()
void LapMessage::setMaxTemperature (const qint8 maxTemperature)
Sets the maxTemperature field to maxTemperature.
Parameters
maxTemperature The field value to set.
Definition at line 1906 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->maxTemperature = maxTemperature;
 }
References maxTemperature().
setMaxTotalHemoglobinConc()
void LapMessage::setMaxTotalHemoglobinConc (const quint16 maxTotalHemoglobinConc)
Sets the maxTotalHemoglobinConc field to maxTotalHemoglobinConc.
Parameters
maxTotalHemoglobinConc The field value to set.
Definition at line 2166 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->maxTotalHemoglobinConc = maxTotalHemoglobinConc;
 }
References maxTotalHemoglobinConc().
setMessageIndex()
void LapMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 1436 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setMinAltitude()
void LapMessage::setMinAltitude (const quint16 minAltitude)
Sets the minAltitude field to minAltitude.
Parameters
minAltitude The field value to set.
Definition at line 2016 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->minAltitude = minAltitude;
 }
References minAltitude().
setMinCoreTemperature()
void LapMessage::setMinCoreTemperature (const quint16 minCoreTemperature)
Sets the minCoreTemperature field to minCoreTemperature.
Parameters
minCoreTemperature The field value to set.
Definition at line 2576 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->minCoreTemperature = minCoreTemperature;
 }
References minCoreTemperature().
setMinHeartRate()
void LapMessage::setMinHeartRate (const quint8 minHeartRate)
Sets the minHeartRate field to minHeartRate.
Parameters
minHeartRate The field value to set.
Definition at line 2026 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->minHeartRate = minHeartRate;
 }
References minHeartRate().
setMinSaturatedHemoglobinPercent()
void LapMessage::setMinSaturatedHemoglobinPercent (const quint16 minSaturatedHemoglobinPercent)
Sets the minSaturatedHemoglobinPercent field to minSaturatedHemoglobinPercent.
Parameters
minSaturatedHemoglobinPercent The field value to set.
Definition at line 2186 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->minSaturatedHemoglobinPercent = minSaturatedHemoglobinPercent;
 }
References minSaturatedHemoglobinPercent().
setMinTotalHemoglobinConc()
void LapMessage::setMinTotalHemoglobinConc (const quint16 minTotalHemoglobinConc)
Sets the minTotalHemoglobinConc field to minTotalHemoglobinConc.
Parameters
minTotalHemoglobinConc The field value to set.
Definition at line 2156 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->minTotalHemoglobinConc = minTotalHemoglobinConc;
 }
References minTotalHemoglobinConc().
setNormalizedPower()
void LapMessage::setNormalizedPower (const quint16 normalizedPower)
Sets the normalizedPower field to normalizedPower.
Parameters
normalizedPower The field value to set.
Definition at line 1736 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->normalizedPower = normalizedPower;
 }
References normalizedPower().
setNumActiveLengths()
void LapMessage::setNumActiveLengths (const quint16 numActiveLengths)
Sets the numActiveLengths field to numActiveLengths.
Parameters
numActiveLengths The field value to set.
Definition at line 1796 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->numActiveLengths = numActiveLengths;
 }
References numActiveLengths().
setNumLengths()
void LapMessage::setNumLengths (const quint16 numLengths)
Sets the numLengths field to numLengths.
Parameters
numLengths The field value to set.
Definition at line 1726 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->numLengths = numLengths;
 }
References numLengths().
setOpponentScore()
void LapMessage::setOpponentScore (const quint16 opponentScore)
Sets the opponentScore field to opponentScore.
Parameters
opponentScore The field value to set.
Definition at line 2046 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->opponentScore = opponentScore;
 }
References opponentScore().
setPlayerScore()
void LapMessage::setPlayerScore (const quint16 playerScore)
Sets the playerScore field to playerScore.
Parameters
playerScore The field value to set.
Definition at line 2136 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->playerScore = playerScore;
 }
References playerScore().
setRepetitionNum()
void LapMessage::setRepetitionNum (const quint16 repetitionNum)
Sets the repetitionNum field to repetitionNum.
Parameters
repetitionNum The field value to set.
Definition at line 2006 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->repetitionNum = repetitionNum;
 }
References repetitionNum().
setSport()
void LapMessage::setSport (const Sport sport)
Sets the sport field to sport.
Parameters
sport The field value to set.
Definition at line 1706 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->sport = sport;
 }
References sport().
setStandCount()
void LapMessage::setStandCount (const quint16 standCount)
Sets the standCount field to standCount.
Parameters
standCount The field value to set.
Definition at line 2266 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->standCount = standCount;
 }
References standCount().
setStartPositionLat()
void LapMessage::setStartPositionLat (const qint32 startPositionLat)
Sets the startPositionLat field to startPositionLat.
Parameters
startPositionLat The field value to set.
Definition at line 1486 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->startPositionLat = startPositionLat;
 }
References startPositionLat().
setStartPositionLong()
void LapMessage::setStartPositionLong (const qint32 startPositionLong)
Sets the startPositionLong field to startPositionLong.
Parameters
startPositionLong The field value to set.
Definition at line 1496 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->startPositionLong = startPositionLong;
 }
References startPositionLong().
setStartTime()
void LapMessage::setStartTime (const DateTime startTime)
Sets the startTime field to startTime.
Parameters
startTime The field value to set.
Definition at line 1476 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->startTime = startTime;
 }
References startTime().
setStrokeCount()
void LapMessage::setStrokeCount (const quint16 strokeCount)
Sets the strokeCount field to strokeCount.
Parameters
strokeCount The field value to set.
Definition at line 2056 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->strokeCount = strokeCount;
 }
References strokeCount().
setSubSport()
void LapMessage::setSubSport (const SubSport subSport)
Sets the subSport field to subSport.
Parameters
subSport The field value to set.
Definition at line 1786 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->subSport = subSport;
 }
References subSport().
setSwimStroke()
void LapMessage::setSwimStroke (const SwimStroke swimStroke)
Sets the swimStroke field to swimStroke.
Parameters
swimStroke The field value to set.
Definition at line 1776 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->swimStroke = swimStroke;
 }
References swimStroke().
setTimeInCadenceZone()
void LapMessage::setTimeInCadenceZone (const quint32 timeInCadenceZone)
Sets the timeInCadenceZone field to timeInCadenceZone.
Parameters
timeInCadenceZone The field value to set.
Definition at line 1986 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->timeInCadenceZone = timeInCadenceZone;
 }
References timeInCadenceZone().
setTimeInHrZone()
void LapMessage::setTimeInHrZone (const quint32 timeInHrZone)
Sets the timeInHrZone field to timeInHrZone.
Parameters
timeInHrZone The field value to set.
Definition at line 1966 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->timeInHrZone = timeInHrZone;
 }
References timeInHrZone().
setTimeInPowerZone()
void LapMessage::setTimeInPowerZone (const quint32 timeInPowerZone)
Sets the timeInPowerZone field to timeInPowerZone.
Parameters
timeInPowerZone The field value to set.
Definition at line 1996 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->timeInPowerZone = timeInPowerZone;
 }
References timeInPowerZone().
setTimeInSpeedZone()
void LapMessage::setTimeInSpeedZone (const quint32 timeInSpeedZone)
Sets the timeInSpeedZone field to timeInSpeedZone.
Parameters
timeInSpeedZone The field value to set.
Definition at line 1976 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->timeInSpeedZone = timeInSpeedZone;
 }
References timeInSpeedZone().
setTimestamp()
void LapMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 1446 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setTimeStanding()
void LapMessage::setTimeStanding (const quint32 timeStanding)
Sets the timeStanding field to timeStanding.
Parameters
timeStanding The field value to set.
Definition at line 2256 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->timeStanding = timeStanding;
 }
References timeStanding().
setTotalAscent()
void LapMessage::setTotalAscent (const quint16 totalAscent)
Sets the totalAscent field to totalAscent.
Parameters
totalAscent The field value to set.
Definition at line 1666 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->totalAscent = totalAscent;
 }
References totalAscent().
setTotalCalories()
void LapMessage::setTotalCalories (const quint16 totalCalories)
Sets the totalCalories field to totalCalories.
Parameters
totalCalories The field value to set.
Definition at line 1566 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->totalCalories = totalCalories;
 }
References totalCalories().
setTotalCycles()
void LapMessage::setTotalCycles (const quint32 totalCycles)
Sets the totalCycles field to totalCycles.
Parameters
totalCycles The field value to set.
Definition at line 1556 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->totalCycles = totalCycles;
 }
References totalCycles().
setTotalDescent()
void LapMessage::setTotalDescent (const quint16 totalDescent)
Sets the totalDescent field to totalDescent.
Parameters
totalDescent The field value to set.
Definition at line 1676 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->totalDescent = totalDescent;
 }
References totalDescent().
setTotalDistance()
void LapMessage::setTotalDistance (const quint32 totalDistance)
Sets the totalDistance field to totalDistance.
Parameters
totalDistance The field value to set.
Definition at line 1546 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->totalDistance = totalDistance;
 }
References totalDistance().
setTotalElapsedTime()
void LapMessage::setTotalElapsedTime (const quint32 totalElapsedTime)
Sets the totalElapsedTime field to totalElapsedTime.
Parameters
totalElapsedTime The field value to set.
Definition at line 1526 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->totalElapsedTime = totalElapsedTime;
 }
References totalElapsedTime().
setTotalFatCalories()
void LapMessage::setTotalFatCalories (const quint16 totalFatCalories)
Sets the totalFatCalories field to totalFatCalories.
Parameters
totalFatCalories The field value to set.
Definition at line 1576 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->totalFatCalories = totalFatCalories;
 }
References totalFatCalories().
setTotalFlow()
void LapMessage::setTotalFlow (const float totalFlow)
Sets the totalFlow field to totalFlow.
Parameters
totalFlow The field value to set.
Definition at line 2506 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->totalFlow = totalFlow;
 }
References totalFlow().
setTotalFractionalAscent()
void LapMessage::setTotalFractionalAscent (const quint8 totalFractionalAscent)
Sets the totalFractionalAscent field to totalFractionalAscent.
Parameters
totalFractionalAscent The field value to set.
Definition at line 2546 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->totalFractionalAscent = totalFractionalAscent;
 }
References totalFractionalAscent().
setTotalFractionalCycles()
void LapMessage::setTotalFractionalCycles (const quint8 totalFractionalCycles)
Sets the totalFractionalCycles field to totalFractionalCycles.
Parameters
totalFractionalCycles The field value to set.
Definition at line 2126 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->totalFractionalCycles = totalFractionalCycles;
 }
References totalFractionalCycles().
setTotalFractionalDescent()
void LapMessage::setTotalFractionalDescent (const quint8 totalFractionalDescent)
Sets the totalFractionalDescent field to totalFractionalDescent.
Parameters
totalFractionalDescent The field value to set.
Definition at line 2556 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->totalFractionalDescent = totalFractionalDescent;
 }
References totalFractionalDescent().
setTotalGrit()
void LapMessage::setTotalGrit (const float totalGrit)
Sets the totalGrit field to totalGrit.
Parameters
totalGrit The field value to set.
Definition at line 2496 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->totalGrit = totalGrit;
 }
References totalGrit().
setTotalMovingTime()
void LapMessage::setTotalMovingTime (const quint32 totalMovingTime)
Sets the totalMovingTime field to totalMovingTime.
Parameters
totalMovingTime The field value to set.
Definition at line 1916 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->totalMovingTime = totalMovingTime;
 }
References totalMovingTime().
setTotalTimerTime()
void LapMessage::setTotalTimerTime (const quint32 totalTimerTime)
Sets the totalTimerTime field to totalTimerTime.
Parameters
totalTimerTime The field value to set.
Definition at line 1536 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->totalTimerTime = totalTimerTime;
 }
References totalTimerTime().
setTotalWork()
void LapMessage::setTotalWork (const quint32 totalWork)
Sets the totalWork field to totalWork.
Parameters
totalWork The field value to set.
Definition at line 1806 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->totalWork = totalWork;
 }
References totalWork().
setWktStepIndex()
void LapMessage::setWktStepIndex (const MessageIndex wktStepIndex)
Sets the wktStepIndex field to wktStepIndex.
Parameters
wktStepIndex The field value to set.
Definition at line 2036 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->wktStepIndex = wktStepIndex;
 }
References wktStepIndex().
setZoneCount()
void LapMessage::setZoneCount (const quint16 zoneCount)
Sets the zoneCount field to zoneCount.
Parameters
zoneCount The field value to set.
Definition at line 2066 of file lapmessage.cpp.
 {
     Q_D(LapMessage);
     d->zoneCount = zoneCount;
 }
References zoneCount().
sport()
Sport LapMessage::sport () const
Returns the LapMessage data message's sport field's current value.
Returns
the sport field value.
Definition at line 385 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->sport;
 }
Referenced by setSport().
standCount()
quint16 LapMessage::standCount () const
Returns the LapMessage data message's standCount field's current value.
Number of transitions to the standing state
Returns
the standCount field value.
Definition at line 1031 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->standCount;
 }
Referenced by setStandCount().
startPositionLat()
qint32 LapMessage::startPositionLat () const
Returns the LapMessage data message's startPositionLat field's current value.
Returns
the startPositionLat field value.
Definition at line 131 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->startPositionLat;
 }
Referenced by setStartPositionLat().
startPositionLong()
qint32 LapMessage::startPositionLong () const
Returns the LapMessage data message's startPositionLong field's current value.
Returns
the startPositionLong field value.
Definition at line 142 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->startPositionLong;
 }
Referenced by setStartPositionLong().
startTime()
DateTime LapMessage::startTime () const
Returns the LapMessage data message's startTime field's current value.
Returns
the startTime field value.
Definition at line 120 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->startTime;
 }
Referenced by setStartTime().
strokeCount()
quint16 LapMessage::strokeCount () const
Returns the LapMessage data message's strokeCount field's current value.
stroke_type enum used as the index
Returns
the strokeCount field value.
Definition at line 776 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->strokeCount;
 }
Referenced by setStrokeCount().
subSport()
SubSport LapMessage::subSport () const
Returns the LapMessage data message's subSport field's current value.
Returns
the subSport field value.
Definition at line 475 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->subSport;
 }
Referenced by setSubSport().
swimStroke()
SwimStroke LapMessage::swimStroke () const
Returns the LapMessage data message's swimStroke field's current value.
Returns
the swimStroke field value.
Definition at line 464 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->swimStroke;
 }
Referenced by setSwimStroke().
timeInCadenceZone()
quint32 LapMessage::timeInCadenceZone () const
Returns the LapMessage data message's timeInCadenceZone field's current value.
Returns
the timeInCadenceZone field value.
Definition at line 697 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->timeInCadenceZone;
 }
Referenced by setTimeInCadenceZone().
timeInHrZone()
quint32 LapMessage::timeInHrZone () const
Returns the LapMessage data message's timeInHrZone field's current value.
Returns
the timeInHrZone field value.
Definition at line 675 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->timeInHrZone;
 }
Referenced by setTimeInHrZone().
timeInPowerZone()
quint32 LapMessage::timeInPowerZone () const
Returns the LapMessage data message's timeInPowerZone field's current value.
Returns
the timeInPowerZone field value.
Definition at line 708 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->timeInPowerZone;
 }
Referenced by setTimeInPowerZone().
timeInSpeedZone()
quint32 LapMessage::timeInSpeedZone () const
Returns the LapMessage data message's timeInSpeedZone field's current value.
Returns
the timeInSpeedZone field value.
Definition at line 686 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->timeInSpeedZone;
 }
Referenced by setTimeInSpeedZone().
timestamp()
DateTime LapMessage::timestamp () const
Returns the LapMessage data message's timestamp field's current value.
Lap end time.
Returns
the timestamp field value.
Definition at line 87 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
timeStanding()
quint32 LapMessage::timeStanding () const
Returns the LapMessage data message's timeStanding field's current value.
Total time spent in the standing position
Returns
the timeStanding field value.
Definition at line 1018 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->timeStanding;
 }
Referenced by setTimeStanding().
totalAscent()
quint16 LapMessage::totalAscent () const
Returns the LapMessage data message's totalAscent field's current value.
Returns
the totalAscent field value.
Definition at line 341 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->totalAscent;
 }
Referenced by setTotalAscent().
totalCalories()
quint16 LapMessage::totalCalories () const
Returns the LapMessage data message's totalCalories field's current value.
Returns
the totalCalories field value.
Definition at line 223 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->totalCalories;
 }
Referenced by setTotalCalories().
totalCycles()
quint32 LapMessage::totalCycles () const
Returns the LapMessage data message's totalCycles field's current value.
Returns
the totalCycles field value.
Definition at line 212 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->totalCycles;
 }
Referenced by setTotalCycles().
totalDescent()
quint16 LapMessage::totalDescent () const
Returns the LapMessage data message's totalDescent field's current value.
Returns
the totalDescent field value.
Definition at line 352 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->totalDescent;
 }
Referenced by setTotalDescent().
totalDistance()
quint32 LapMessage::totalDistance () const
Returns the LapMessage data message's totalDistance field's current value.
Returns
the totalDistance field value.
Definition at line 201 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->totalDistance;
 }
Referenced by setTotalDistance().
totalElapsedTime()
quint32 LapMessage::totalElapsedTime () const
Returns the LapMessage data message's totalElapsedTime field's current value.
Time (includes pauses)
Returns
the totalElapsedTime field value.
Definition at line 177 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->totalElapsedTime;
 }
Referenced by setTotalElapsedTime().
totalFatCalories()
quint16 LapMessage::totalFatCalories () const
Returns the LapMessage data message's totalFatCalories field's current value.
If New Leaf
Returns
the totalFatCalories field value.
Definition at line 236 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->totalFatCalories;
 }
Referenced by setTotalFatCalories().
totalFlow()
float LapMessage::totalFlow () const
Returns the LapMessage data message's totalFlow field's current value.
The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.
Returns
the totalFlow field value.
Definition at line 1327 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->totalFlow;
 }
Referenced by setTotalFlow().
totalFractionalAscent()
quint8 LapMessage::totalFractionalAscent () const
Returns the LapMessage data message's totalFractionalAscent field's current value.
fractional part of total_ascent
Returns
the totalFractionalAscent field value.
Definition at line 1379 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->totalFractionalAscent;
 }
Referenced by setTotalFractionalAscent().
totalFractionalCycles()
quint8 LapMessage::totalFractionalCycles () const
Returns the LapMessage data message's totalFractionalCycles field's current value.
fractional part of the total_cycles
Returns
the totalFractionalCycles field value.
Definition at line 861 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->totalFractionalCycles;
 }
Referenced by setTotalFractionalCycles().
totalFractionalDescent()
quint8 LapMessage::totalFractionalDescent () const
Returns the LapMessage data message's totalFractionalDescent field's current value.
fractional part of total_descent
Returns
the totalFractionalDescent field value.
Definition at line 1392 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->totalFractionalDescent;
 }
Referenced by setTotalFractionalDescent().
totalGrit()
float LapMessage::totalGrit () const
Returns the LapMessage data message's totalGrit field's current value.
The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.
Returns
the totalGrit field value.
Definition at line 1313 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->totalGrit;
 }
Referenced by setTotalGrit().
totalMovingTime()
quint32 LapMessage::totalMovingTime () const
Returns the LapMessage data message's totalMovingTime field's current value.
Returns
the totalMovingTime field value.
Definition at line 620 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->totalMovingTime;
 }
Referenced by setTotalMovingTime().
totalTimerTime()
quint32 LapMessage::totalTimerTime () const
Returns the LapMessage data message's totalTimerTime field's current value.
Timer Time (excludes pauses)
Returns
the totalTimerTime field value.
Definition at line 190 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->totalTimerTime;
 }
Referenced by setTotalTimerTime().
totalWork()
quint32 LapMessage::totalWork () const
Returns the LapMessage data message's totalWork field's current value.
Returns
the totalWork field value.
Definition at line 499 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->totalWork;
 }
Referenced by setTotalWork().
wktStepIndex()
MessageIndex LapMessage::wktStepIndex () const
Returns the LapMessage data message's wktStepIndex field's current value.
Returns
the wktStepIndex field value.
Definition at line 752 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->wktStepIndex;
 }
Referenced by setWktStepIndex().
zoneCount()
quint16 LapMessage::zoneCount () const
Returns the LapMessage data message's zoneCount field's current value.
zone number used as the index
Returns
the zoneCount field value.
Definition at line 789 of file lapmessage.cpp.
 {
     Q_D(const LapMessage);
     return d->zoneCount;
 }
Referenced by setZoneCount().
The documentation for this class was generated from the following files:
lapmessage.h
lapmessage.cpp