QtFit: WeatherConditionsMessage Class Reference
WeatherConditionsMessage Class Reference
The WeatherConditionsMessage class represents a FIT WeatherConditionsMessage data message.
Public Member Functions
WeatherConditionsMessage ()
Constructs a WeatherConditionsMessage object.
DateTime timestamp () const
Returns the WeatherConditionsMessage data message's timestamp field's current value.
WeatherReport weatherReport () const
Returns the WeatherConditionsMessage data message's weatherReport field's current value.
qint8 temperature () const
Returns the WeatherConditionsMessage data message's temperature field's current value.
WeatherStatus condition () const
Returns the WeatherConditionsMessage data message's condition field's current value.
quint16 windDirection () const
Returns the WeatherConditionsMessage data message's windDirection field's current value.
quint16 windSpeed () const
Returns the WeatherConditionsMessage data message's windSpeed field's current value.
quint8 precipitationProbability () const
Returns the WeatherConditionsMessage data message's precipitationProbability field's current value.
qint8 temperatureFeelsLike () const
Returns the WeatherConditionsMessage data message's temperatureFeelsLike field's current value.
quint8 relativeHumidity () const
Returns the WeatherConditionsMessage data message's relativeHumidity field's current value.
QString location () const
Returns the WeatherConditionsMessage data message's location field's current value.
DateTime observedAtTime () const
Returns the WeatherConditionsMessage data message's observedAtTime field's current value.
qint32 observedLocationLat () const
Returns the WeatherConditionsMessage data message's observedLocationLat field's current value.
qint32 observedLocationLong () const
Returns the WeatherConditionsMessage data message's observedLocationLong field's current value.
DayOfWeek dayOfWeek () const
Returns the WeatherConditionsMessage data message's dayOfWeek field's current value.
qint8 highTemperature () const
Returns the WeatherConditionsMessage data message's highTemperature field's current value.
qint8 lowTemperature () const
Returns the WeatherConditionsMessage data message's lowTemperature field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setWeatherReport (const WeatherReport weatherReport)
Sets the weatherReport field to weatherReport.
void setTemperature (const qint8 temperature)
Sets the temperature field to temperature.
void setCondition (const WeatherStatus condition)
Sets the condition field to condition.
void setWindDirection (const quint16 windDirection)
Sets the windDirection field to windDirection.
void setWindSpeed (const quint16 windSpeed)
Sets the windSpeed field to windSpeed.
void setPrecipitationProbability (const quint8 precipitationProbability)
Sets the precipitationProbability field to precipitationProbability.
void setTemperatureFeelsLike (const qint8 temperatureFeelsLike)
Sets the temperatureFeelsLike field to temperatureFeelsLike.
void setRelativeHumidity (const quint8 relativeHumidity)
Sets the relativeHumidity field to relativeHumidity.
void setLocation (const QString location)
Sets the location field to location.
void setObservedAtTime (const DateTime observedAtTime)
Sets the observedAtTime field to observedAtTime.
void setObservedLocationLat (const qint32 observedLocationLat)
Sets the observedLocationLat field to observedLocationLat.
void setObservedLocationLong (const qint32 observedLocationLong)
Sets the observedLocationLong field to observedLocationLong.
void setDayOfWeek (const DayOfWeek dayOfWeek)
Sets the dayOfWeek field to dayOfWeek.
void setHighTemperature (const qint8 highTemperature)
Sets the highTemperature field to highTemperature.
void setLowTemperature (const qint8 lowTemperature)
Sets the lowTemperature field to lowTemperature.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
WeatherConditionsMessage (WeatherConditionsMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The WeatherConditionsMessage class represents a FIT WeatherConditionsMessage data message.
See also
DataMessage
Definition at line 39 of file weatherconditionsmessage.h.
Constructor & Destructor Documentation
WeatherConditionsMessage() [1/2]
WeatherConditionsMessage::WeatherConditionsMessage ()
Constructs a WeatherConditionsMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file weatherconditionsmessage.cpp.
                                                    : AbstractDataMessage(new WeatherConditionsMessagePrivate(this))
 {
 }
WeatherConditionsMessage() [2/2]
WeatherConditionsMessage::WeatherConditionsMessage (WeatherConditionsMessagePrivate *const d) explicit protected
Constructs a WeatherConditionsMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file weatherconditionsmessage.cpp.
                                                                                             : AbstractDataMessage(d)
 {
 }
Member Function Documentation
condition()
WeatherStatus WeatherConditionsMessage::condition () const
Returns the WeatherConditionsMessage data message's condition field's current value.
Corresponds to GSC Response weatherIcon field
Returns
the condition field value.
Definition at line 113 of file weatherconditionsmessage.cpp.
 {
     Q_D(const WeatherConditionsMessage);
     return d->condition;
 }
Referenced by setCondition().
dayOfWeek()
DayOfWeek WeatherConditionsMessage::dayOfWeek () const
Returns the WeatherConditionsMessage data message's dayOfWeek field's current value.
Returns
the dayOfWeek field value.
Definition at line 230 of file weatherconditionsmessage.cpp.
 {
     Q_D(const WeatherConditionsMessage);
     return d->dayOfWeek;
 }
Referenced by setDayOfWeek().
highTemperature()
qint8 WeatherConditionsMessage::highTemperature () const
Returns the WeatherConditionsMessage data message's highTemperature field's current value.
Returns
the highTemperature field value.
Definition at line 241 of file weatherconditionsmessage.cpp.
 {
     Q_D(const WeatherConditionsMessage);
     return d->highTemperature;
 }
Referenced by setHighTemperature().
location()
QString WeatherConditionsMessage::location () const
Returns the WeatherConditionsMessage data message's location field's current value.
string corresponding to GCS response location string
Returns
the location field value.
Definition at line 186 of file weatherconditionsmessage.cpp.
 {
     Q_D(const WeatherConditionsMessage);
     return d->location;
 }
Referenced by setLocation().
lowTemperature()
qint8 WeatherConditionsMessage::lowTemperature () const
Returns the WeatherConditionsMessage data message's lowTemperature field's current value.
Returns
the lowTemperature field value.
Definition at line 252 of file weatherconditionsmessage.cpp.
 {
     Q_D(const WeatherConditionsMessage);
     return d->lowTemperature;
 }
Referenced by setLowTemperature().
observedAtTime()
DateTime WeatherConditionsMessage::observedAtTime () const
Returns the WeatherConditionsMessage data message's observedAtTime field's current value.
Returns
the observedAtTime field value.
Definition at line 197 of file weatherconditionsmessage.cpp.
 {
     Q_D(const WeatherConditionsMessage);
     return d->observedAtTime;
 }
Referenced by setObservedAtTime().
observedLocationLat()
qint32 WeatherConditionsMessage::observedLocationLat () const
Returns the WeatherConditionsMessage data message's observedLocationLat field's current value.
Returns
the observedLocationLat field value.
Definition at line 208 of file weatherconditionsmessage.cpp.
 {
     Q_D(const WeatherConditionsMessage);
     return d->observedLocationLat;
 }
Referenced by setObservedLocationLat().
observedLocationLong()
qint32 WeatherConditionsMessage::observedLocationLong () const
Returns the WeatherConditionsMessage data message's observedLocationLong field's current value.
Returns
the observedLocationLong field value.
Definition at line 219 of file weatherconditionsmessage.cpp.
 {
     Q_D(const WeatherConditionsMessage);
     return d->observedLocationLong;
 }
Referenced by setObservedLocationLong().
precipitationProbability()
quint8 WeatherConditionsMessage::precipitationProbability () const
Returns the WeatherConditionsMessage data message's precipitationProbability field's current value.
range 0-100
Returns
the precipitationProbability field value.
Definition at line 148 of file weatherconditionsmessage.cpp.
 {
     Q_D(const WeatherConditionsMessage);
     return d->precipitationProbability;
 }
Referenced by setPrecipitationProbability().
relativeHumidity()
quint8 WeatherConditionsMessage::relativeHumidity () const
Returns the WeatherConditionsMessage data message's relativeHumidity field's current value.
Returns
the relativeHumidity field value.
Definition at line 173 of file weatherconditionsmessage.cpp.
 {
     Q_D(const WeatherConditionsMessage);
     return d->relativeHumidity;
 }
Referenced by setRelativeHumidity().
setCondition()
void WeatherConditionsMessage::setCondition (const WeatherStatus condition)
Sets the condition field to condition.
Parameters
condition The field value to set.
Definition at line 293 of file weatherconditionsmessage.cpp.
 {
     Q_D(WeatherConditionsMessage);
     d->condition = condition;
 }
References condition().
setDayOfWeek()
void WeatherConditionsMessage::setDayOfWeek (const DayOfWeek dayOfWeek)
Sets the dayOfWeek field to dayOfWeek.
Parameters
dayOfWeek The field value to set.
Definition at line 393 of file weatherconditionsmessage.cpp.
 {
     Q_D(WeatherConditionsMessage);
     d->dayOfWeek = dayOfWeek;
 }
References dayOfWeek().
setHighTemperature()
void WeatherConditionsMessage::setHighTemperature (const qint8 highTemperature)
Sets the highTemperature field to highTemperature.
Parameters
highTemperature The field value to set.
Definition at line 403 of file weatherconditionsmessage.cpp.
 {
     Q_D(WeatherConditionsMessage);
     d->highTemperature = highTemperature;
 }
References highTemperature().
setLocation()
void WeatherConditionsMessage::setLocation (const QString location)
Sets the location field to location.
Parameters
location The field value to set.
Definition at line 353 of file weatherconditionsmessage.cpp.
 {
     Q_D(WeatherConditionsMessage);
     d->location = location;
 }
References location().
setLowTemperature()
void WeatherConditionsMessage::setLowTemperature (const qint8 lowTemperature)
Sets the lowTemperature field to lowTemperature.
Parameters
lowTemperature The field value to set.
Definition at line 413 of file weatherconditionsmessage.cpp.
 {
     Q_D(WeatherConditionsMessage);
     d->lowTemperature = lowTemperature;
 }
References lowTemperature().
setObservedAtTime()
void WeatherConditionsMessage::setObservedAtTime (const DateTime observedAtTime)
Sets the observedAtTime field to observedAtTime.
Parameters
observedAtTime The field value to set.
Definition at line 363 of file weatherconditionsmessage.cpp.
 {
     Q_D(WeatherConditionsMessage);
     d->observedAtTime = observedAtTime;
 }
References observedAtTime().
setObservedLocationLat()
void WeatherConditionsMessage::setObservedLocationLat (const qint32 observedLocationLat)
Sets the observedLocationLat field to observedLocationLat.
Parameters
observedLocationLat The field value to set.
Definition at line 373 of file weatherconditionsmessage.cpp.
 {
     Q_D(WeatherConditionsMessage);
     d->observedLocationLat = observedLocationLat;
 }
References observedLocationLat().
setObservedLocationLong()
void WeatherConditionsMessage::setObservedLocationLong (const qint32 observedLocationLong)
Sets the observedLocationLong field to observedLocationLong.
Parameters
observedLocationLong The field value to set.
Definition at line 383 of file weatherconditionsmessage.cpp.
 {
     Q_D(WeatherConditionsMessage);
     d->observedLocationLong = observedLocationLong;
 }
References observedLocationLong().
setPrecipitationProbability()
void WeatherConditionsMessage::setPrecipitationProbability (const quint8 precipitationProbability)
Sets the precipitationProbability field to precipitationProbability.
Parameters
precipitationProbability The field value to set.
Definition at line 323 of file weatherconditionsmessage.cpp.
 {
     Q_D(WeatherConditionsMessage);
     d->precipitationProbability = precipitationProbability;
 }
References precipitationProbability().
setRelativeHumidity()
void WeatherConditionsMessage::setRelativeHumidity (const quint8 relativeHumidity)
Sets the relativeHumidity field to relativeHumidity.
Parameters
relativeHumidity The field value to set.
Definition at line 343 of file weatherconditionsmessage.cpp.
 {
     Q_D(WeatherConditionsMessage);
     d->relativeHumidity = relativeHumidity;
 }
References relativeHumidity().
setTemperature()
void WeatherConditionsMessage::setTemperature (const qint8 temperature)
Sets the temperature field to temperature.
Parameters
temperature The field value to set.
Definition at line 283 of file weatherconditionsmessage.cpp.
 {
     Q_D(WeatherConditionsMessage);
     d->temperature = temperature;
 }
References temperature().
setTemperatureFeelsLike()
void WeatherConditionsMessage::setTemperatureFeelsLike (const qint8 temperatureFeelsLike)
Sets the temperatureFeelsLike field to temperatureFeelsLike.
Parameters
temperatureFeelsLike The field value to set.
Definition at line 333 of file weatherconditionsmessage.cpp.
 {
     Q_D(WeatherConditionsMessage);
     d->temperatureFeelsLike = temperatureFeelsLike;
 }
References temperatureFeelsLike().
setTimestamp()
void WeatherConditionsMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 263 of file weatherconditionsmessage.cpp.
 {
     Q_D(WeatherConditionsMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setWeatherReport()
void WeatherConditionsMessage::setWeatherReport (const WeatherReport weatherReport)
Sets the weatherReport field to weatherReport.
Parameters
weatherReport The field value to set.
Definition at line 273 of file weatherconditionsmessage.cpp.
 {
     Q_D(WeatherConditionsMessage);
     d->weatherReport = weatherReport;
 }
References weatherReport().
setWindDirection()
void WeatherConditionsMessage::setWindDirection (const quint16 windDirection)
Sets the windDirection field to windDirection.
Parameters
windDirection The field value to set.
Definition at line 303 of file weatherconditionsmessage.cpp.
 {
     Q_D(WeatherConditionsMessage);
     d->windDirection = windDirection;
 }
References windDirection().
setWindSpeed()
void WeatherConditionsMessage::setWindSpeed (const quint16 windSpeed)
Sets the windSpeed field to windSpeed.
Parameters
windSpeed The field value to set.
Definition at line 313 of file weatherconditionsmessage.cpp.
 {
     Q_D(WeatherConditionsMessage);
     d->windSpeed = windSpeed;
 }
References windSpeed().
temperature()
qint8 WeatherConditionsMessage::temperature () const
Returns the WeatherConditionsMessage data message's temperature field's current value.
Returns
the temperature field value.
Definition at line 100 of file weatherconditionsmessage.cpp.
 {
     Q_D(const WeatherConditionsMessage);
     return d->temperature;
 }
Referenced by setTemperature().
temperatureFeelsLike()
qint8 WeatherConditionsMessage::temperatureFeelsLike () const
Returns the WeatherConditionsMessage data message's temperatureFeelsLike field's current value.
Heat Index if GCS heatIdx above or equal to 90F or wind chill if GCS windChill below or equal to 32F
Returns
the temperatureFeelsLike field value.
Definition at line 162 of file weatherconditionsmessage.cpp.
 {
     Q_D(const WeatherConditionsMessage);
     return d->temperatureFeelsLike;
 }
Referenced by setTemperatureFeelsLike().
timestamp()
DateTime WeatherConditionsMessage::timestamp () const
Returns the WeatherConditionsMessage data message's timestamp field's current value.
time of update for current conditions, else forecast time
Returns
the timestamp field value.
Definition at line 76 of file weatherconditionsmessage.cpp.
 {
     Q_D(const WeatherConditionsMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
weatherReport()
WeatherReport WeatherConditionsMessage::weatherReport () const
Returns the WeatherConditionsMessage data message's weatherReport field's current value.
Current or forecast
Returns
the weatherReport field value.
Definition at line 89 of file weatherconditionsmessage.cpp.
 {
     Q_D(const WeatherConditionsMessage);
     return d->weatherReport;
 }
Referenced by setWeatherReport().
windDirection()
quint16 WeatherConditionsMessage::windDirection () const
Returns the WeatherConditionsMessage data message's windDirection field's current value.
Returns
the windDirection field value.
Definition at line 124 of file weatherconditionsmessage.cpp.
 {
     Q_D(const WeatherConditionsMessage);
     return d->windDirection;
 }
Referenced by setWindDirection().
windSpeed()
quint16 WeatherConditionsMessage::windSpeed () const
Returns the WeatherConditionsMessage data message's windSpeed field's current value.
Returns
the windSpeed field value.
Definition at line 135 of file weatherconditionsmessage.cpp.
 {
     Q_D(const WeatherConditionsMessage);
     return d->windSpeed;
 }
Referenced by setWindSpeed().
The documentation for this class was generated from the following files:
weatherconditionsmessage.h
weatherconditionsmessage.cpp