QtFit: WeightScaleMessage Class Reference
WeightScaleMessage Class Reference
The WeightScaleMessage class represents a FIT WeightScaleMessage data message.
Public Member Functions
WeightScaleMessage ()
Constructs a WeightScaleMessage object.
DateTime timestamp () const
Returns the WeightScaleMessage data message's timestamp field's current value.
Weight weight () const
Returns the WeightScaleMessage data message's weight field's current value.
quint16 percentFat () const
Returns the WeightScaleMessage data message's percentFat field's current value.
quint16 percentHydration () const
Returns the WeightScaleMessage data message's percentHydration field's current value.
quint16 visceralFatMass () const
Returns the WeightScaleMessage data message's visceralFatMass field's current value.
quint16 boneMass () const
Returns the WeightScaleMessage data message's boneMass field's current value.
quint16 muscleMass () const
Returns the WeightScaleMessage data message's muscleMass field's current value.
quint16 basalMet () const
Returns the WeightScaleMessage data message's basalMet field's current value.
quint8 physiqueRating () const
Returns the WeightScaleMessage data message's physiqueRating field's current value.
quint16 activeMet () const
Returns the WeightScaleMessage data message's activeMet field's current value.
quint8 metabolicAge () const
Returns the WeightScaleMessage data message's metabolicAge field's current value.
quint8 visceralFatRating () const
Returns the WeightScaleMessage data message's visceralFatRating field's current value.
MessageIndex userProfileIndex () const
Returns the WeightScaleMessage data message's userProfileIndex field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setWeight (const Weight weight)
Sets the weight field to weight.
void setPercentFat (const quint16 percentFat)
Sets the percentFat field to percentFat.
void setPercentHydration (const quint16 percentHydration)
Sets the percentHydration field to percentHydration.
void setVisceralFatMass (const quint16 visceralFatMass)
Sets the visceralFatMass field to visceralFatMass.
void setBoneMass (const quint16 boneMass)
Sets the boneMass field to boneMass.
void setMuscleMass (const quint16 muscleMass)
Sets the muscleMass field to muscleMass.
void setBasalMet (const quint16 basalMet)
Sets the basalMet field to basalMet.
void setPhysiqueRating (const quint8 physiqueRating)
Sets the physiqueRating field to physiqueRating.
void setActiveMet (const quint16 activeMet)
Sets the activeMet field to activeMet.
void setMetabolicAge (const quint8 metabolicAge)
Sets the metabolicAge field to metabolicAge.
void setVisceralFatRating (const quint8 visceralFatRating)
Sets the visceralFatRating field to visceralFatRating.
void setUserProfileIndex (const MessageIndex userProfileIndex)
Sets the userProfileIndex field to userProfileIndex.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
WeightScaleMessage (WeightScaleMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The WeightScaleMessage class represents a FIT WeightScaleMessage data message.
See also
DataMessage
Definition at line 39 of file weightscalemessage.h.
Constructor & Destructor Documentation
WeightScaleMessage() [1/2]
WeightScaleMessage::WeightScaleMessage ()
Constructs a WeightScaleMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file weightscalemessage.cpp.
                                        : AbstractDataMessage(new WeightScaleMessagePrivate(this))
 {
 }
WeightScaleMessage() [2/2]
WeightScaleMessage::WeightScaleMessage (WeightScaleMessagePrivate *const d) explicit protected
Constructs a WeightScaleMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file weightscalemessage.cpp.
                                                                           : AbstractDataMessage(d)
 {
 }
Member Function Documentation
activeMet()
quint16 WeightScaleMessage::activeMet () const
Returns the WeightScaleMessage data message's activeMet field's current value.
~4kJ per kcal, 0.25 allows max 16384 kcal
Returns
the activeMet field value.
Definition at line 175 of file weightscalemessage.cpp.
 {
     Q_D(const WeightScaleMessage);
     return d->activeMet;
 }
Referenced by setActiveMet().
basalMet()
quint16 WeightScaleMessage::basalMet () const
Returns the WeightScaleMessage data message's basalMet field's current value.
Returns
the basalMet field value.
Definition at line 151 of file weightscalemessage.cpp.
 {
     Q_D(const WeightScaleMessage);
     return d->basalMet;
 }
Referenced by setBasalMet().
boneMass()
quint16 WeightScaleMessage::boneMass () const
Returns the WeightScaleMessage data message's boneMass field's current value.
Returns
the boneMass field value.
Definition at line 129 of file weightscalemessage.cpp.
 {
     Q_D(const WeightScaleMessage);
     return d->boneMass;
 }
Referenced by setBoneMass().
metabolicAge()
quint8 WeightScaleMessage::metabolicAge () const
Returns the WeightScaleMessage data message's metabolicAge field's current value.
Returns
the metabolicAge field value.
Definition at line 186 of file weightscalemessage.cpp.
 {
     Q_D(const WeightScaleMessage);
     return d->metabolicAge;
 }
Referenced by setMetabolicAge().
muscleMass()
quint16 WeightScaleMessage::muscleMass () const
Returns the WeightScaleMessage data message's muscleMass field's current value.
Returns
the muscleMass field value.
Definition at line 140 of file weightscalemessage.cpp.
 {
     Q_D(const WeightScaleMessage);
     return d->muscleMass;
 }
Referenced by setMuscleMass().
percentFat()
quint16 WeightScaleMessage::percentFat () const
Returns the WeightScaleMessage data message's percentFat field's current value.
Returns
the percentFat field value.
Definition at line 96 of file weightscalemessage.cpp.
 {
     Q_D(const WeightScaleMessage);
     return d->percentFat;
 }
Referenced by setPercentFat().
percentHydration()
quint16 WeightScaleMessage::percentHydration () const
Returns the WeightScaleMessage data message's percentHydration field's current value.
Returns
the percentHydration field value.
Definition at line 107 of file weightscalemessage.cpp.
 {
     Q_D(const WeightScaleMessage);
     return d->percentHydration;
 }
Referenced by setPercentHydration().
physiqueRating()
quint8 WeightScaleMessage::physiqueRating () const
Returns the WeightScaleMessage data message's physiqueRating field's current value.
Returns
the physiqueRating field value.
Definition at line 162 of file weightscalemessage.cpp.
 {
     Q_D(const WeightScaleMessage);
     return d->physiqueRating;
 }
Referenced by setPhysiqueRating().
setActiveMet()
void WeightScaleMessage::setActiveMet (const quint16 activeMet)
Sets the activeMet field to activeMet.
Parameters
activeMet The field value to set.
Definition at line 312 of file weightscalemessage.cpp.
 {
     Q_D(WeightScaleMessage);
     d->activeMet = activeMet;
 }
References activeMet().
setBasalMet()
void WeightScaleMessage::setBasalMet (const quint16 basalMet)
Sets the basalMet field to basalMet.
Parameters
basalMet The field value to set.
Definition at line 292 of file weightscalemessage.cpp.
 {
     Q_D(WeightScaleMessage);
     d->basalMet = basalMet;
 }
References basalMet().
setBoneMass()
void WeightScaleMessage::setBoneMass (const quint16 boneMass)
Sets the boneMass field to boneMass.
Parameters
boneMass The field value to set.
Definition at line 272 of file weightscalemessage.cpp.
 {
     Q_D(WeightScaleMessage);
     d->boneMass = boneMass;
 }
References boneMass().
setMetabolicAge()
void WeightScaleMessage::setMetabolicAge (const quint8 metabolicAge)
Sets the metabolicAge field to metabolicAge.
Parameters
metabolicAge The field value to set.
Definition at line 322 of file weightscalemessage.cpp.
 {
     Q_D(WeightScaleMessage);
     d->metabolicAge = metabolicAge;
 }
References metabolicAge().
setMuscleMass()
void WeightScaleMessage::setMuscleMass (const quint16 muscleMass)
Sets the muscleMass field to muscleMass.
Parameters
muscleMass The field value to set.
Definition at line 282 of file weightscalemessage.cpp.
 {
     Q_D(WeightScaleMessage);
     d->muscleMass = muscleMass;
 }
References muscleMass().
setPercentFat()
void WeightScaleMessage::setPercentFat (const quint16 percentFat)
Sets the percentFat field to percentFat.
Parameters
percentFat The field value to set.
Definition at line 242 of file weightscalemessage.cpp.
 {
     Q_D(WeightScaleMessage);
     d->percentFat = percentFat;
 }
References percentFat().
setPercentHydration()
void WeightScaleMessage::setPercentHydration (const quint16 percentHydration)
Sets the percentHydration field to percentHydration.
Parameters
percentHydration The field value to set.
Definition at line 252 of file weightscalemessage.cpp.
 {
     Q_D(WeightScaleMessage);
     d->percentHydration = percentHydration;
 }
References percentHydration().
setPhysiqueRating()
void WeightScaleMessage::setPhysiqueRating (const quint8 physiqueRating)
Sets the physiqueRating field to physiqueRating.
Parameters
physiqueRating The field value to set.
Definition at line 302 of file weightscalemessage.cpp.
 {
     Q_D(WeightScaleMessage);
     d->physiqueRating = physiqueRating;
 }
References physiqueRating().
setTimestamp()
void WeightScaleMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 222 of file weightscalemessage.cpp.
 {
     Q_D(WeightScaleMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setUserProfileIndex()
void WeightScaleMessage::setUserProfileIndex (const MessageIndex userProfileIndex)
Sets the userProfileIndex field to userProfileIndex.
Parameters
userProfileIndex The field value to set.
Definition at line 342 of file weightscalemessage.cpp.
 {
     Q_D(WeightScaleMessage);
     d->userProfileIndex = userProfileIndex;
 }
References userProfileIndex().
setVisceralFatMass()
void WeightScaleMessage::setVisceralFatMass (const quint16 visceralFatMass)
Sets the visceralFatMass field to visceralFatMass.
Parameters
visceralFatMass The field value to set.
Definition at line 262 of file weightscalemessage.cpp.
 {
     Q_D(WeightScaleMessage);
     d->visceralFatMass = visceralFatMass;
 }
References visceralFatMass().
setVisceralFatRating()
void WeightScaleMessage::setVisceralFatRating (const quint8 visceralFatRating)
Sets the visceralFatRating field to visceralFatRating.
Parameters
visceralFatRating The field value to set.
Definition at line 332 of file weightscalemessage.cpp.
 {
     Q_D(WeightScaleMessage);
     d->visceralFatRating = visceralFatRating;
 }
References visceralFatRating().
setWeight()
void WeightScaleMessage::setWeight (const Weight weight)
Sets the weight field to weight.
Parameters
weight The field value to set.
Definition at line 232 of file weightscalemessage.cpp.
 {
     Q_D(WeightScaleMessage);
     d->weight = weight;
 }
References weight().
timestamp()
DateTime WeightScaleMessage::timestamp () const
Returns the WeightScaleMessage data message's timestamp field's current value.
Returns
the timestamp field value.
Definition at line 74 of file weightscalemessage.cpp.
 {
     Q_D(const WeightScaleMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
userProfileIndex()
MessageIndex WeightScaleMessage::userProfileIndex () const
Returns the WeightScaleMessage data message's userProfileIndex field's current value.
Associates this weight scale message to a user. This corresponds to the index of the user profile message in the weight scale file.
Returns
the userProfileIndex field value.
Definition at line 211 of file weightscalemessage.cpp.
 {
     Q_D(const WeightScaleMessage);
     return d->userProfileIndex;
 }
Referenced by setUserProfileIndex().
visceralFatMass()
quint16 WeightScaleMessage::visceralFatMass () const
Returns the WeightScaleMessage data message's visceralFatMass field's current value.
Returns
the visceralFatMass field value.
Definition at line 118 of file weightscalemessage.cpp.
 {
     Q_D(const WeightScaleMessage);
     return d->visceralFatMass;
 }
Referenced by setVisceralFatMass().
visceralFatRating()
quint8 WeightScaleMessage::visceralFatRating () const
Returns the WeightScaleMessage data message's visceralFatRating field's current value.
Returns
the visceralFatRating field value.
Definition at line 197 of file weightscalemessage.cpp.
 {
     Q_D(const WeightScaleMessage);
     return d->visceralFatRating;
 }
Referenced by setVisceralFatRating().
weight()
Weight WeightScaleMessage::weight () const
Returns the WeightScaleMessage data message's weight field's current value.
Returns
the weight field value.
Definition at line 85 of file weightscalemessage.cpp.
 {
     Q_D(const WeightScaleMessage);
     return d->weight;
 }
Referenced by setWeight().
The documentation for this class was generated from the following files:
weightscalemessage.h
weightscalemessage.cpp