QtFit: DeviceInfoMessage Class Reference
DeviceInfoMessage Class Reference
The DeviceInfoMessage class represents a FIT DeviceInfoMessage data message.
Public Member Functions
DeviceInfoMessage ()
Constructs a DeviceInfoMessage object.
DateTime timestamp () const
Returns the DeviceInfoMessage data message's timestamp field's current value.
DeviceIndex deviceIndex () const
Returns the DeviceInfoMessage data message's deviceIndex field's current value.
quint8 deviceType () const
Returns the DeviceInfoMessage data message's deviceType field's current value.
Manufacturer manufacturer () const
Returns the DeviceInfoMessage data message's manufacturer field's current value.
quint32z serialNumber () const
Returns the DeviceInfoMessage data message's serialNumber field's current value.
quint16 product () const
Returns the DeviceInfoMessage data message's product field's current value.
quint16 softwareVersion () const
Returns the DeviceInfoMessage data message's softwareVersion field's current value.
quint8 hardwareVersion () const
Returns the DeviceInfoMessage data message's hardwareVersion field's current value.
quint32 cumOperatingTime () const
Returns the DeviceInfoMessage data message's cumOperatingTime field's current value.
quint16 batteryVoltage () const
Returns the DeviceInfoMessage data message's batteryVoltage field's current value.
BatteryStatus batteryStatus () const
Returns the DeviceInfoMessage data message's batteryStatus field's current value.
BodyLocation sensorPosition () const
Returns the DeviceInfoMessage data message's sensorPosition field's current value.
QString descriptor () const
Returns the DeviceInfoMessage data message's descriptor field's current value.
quint8z antTransmissionType () const
Returns the DeviceInfoMessage data message's antTransmissionType field's current value.
quint16z antDeviceNumber () const
Returns the DeviceInfoMessage data message's antDeviceNumber field's current value.
AntNetwork antNetwork () const
Returns the DeviceInfoMessage data message's antNetwork field's current value.
SourceType sourceType () const
Returns the DeviceInfoMessage data message's sourceType field's current value.
QString productName () const
Returns the DeviceInfoMessage data message's productName field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setDeviceIndex (const DeviceIndex deviceIndex)
Sets the deviceIndex field to deviceIndex.
void setDeviceType (const quint8 deviceType)
Sets the deviceType field to deviceType.
void setManufacturer (const Manufacturer manufacturer)
Sets the manufacturer field to manufacturer.
void setSerialNumber (const quint32z serialNumber)
Sets the serialNumber field to serialNumber.
void setProduct (const quint16 product)
Sets the product field to product.
void setSoftwareVersion (const quint16 softwareVersion)
Sets the softwareVersion field to softwareVersion.
void setHardwareVersion (const quint8 hardwareVersion)
Sets the hardwareVersion field to hardwareVersion.
void setCumOperatingTime (const quint32 cumOperatingTime)
Sets the cumOperatingTime field to cumOperatingTime.
void setBatteryVoltage (const quint16 batteryVoltage)
Sets the batteryVoltage field to batteryVoltage.
void setBatteryStatus (const BatteryStatus batteryStatus)
Sets the batteryStatus field to batteryStatus.
void setSensorPosition (const BodyLocation sensorPosition)
Sets the sensorPosition field to sensorPosition.
void setDescriptor (const QString descriptor)
Sets the descriptor field to descriptor.
void setAntTransmissionType (const quint8z antTransmissionType)
Sets the antTransmissionType field to antTransmissionType.
void setAntDeviceNumber (const quint16z antDeviceNumber)
Sets the antDeviceNumber field to antDeviceNumber.
void setAntNetwork (const AntNetwork antNetwork)
Sets the antNetwork field to antNetwork.
void setSourceType (const SourceType sourceType)
Sets the sourceType field to sourceType.
void setProductName (const QString productName)
Sets the productName field to productName.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
DeviceInfoMessage (DeviceInfoMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The DeviceInfoMessage class represents a FIT DeviceInfoMessage data message.
See also
DataMessage
Definition at line 39 of file deviceinfomessage.h.
Constructor & Destructor Documentation
DeviceInfoMessage() [1/2]
DeviceInfoMessage::DeviceInfoMessage ()
Constructs a DeviceInfoMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file deviceinfomessage.cpp.
                                      : AbstractDataMessage(new DeviceInfoMessagePrivate(this))
 {
 }
DeviceInfoMessage() [2/2]
DeviceInfoMessage::DeviceInfoMessage (DeviceInfoMessagePrivate *const d) explicit protected
Constructs a DeviceInfoMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file deviceinfomessage.cpp.
                                                                        : AbstractDataMessage(d)
 {
 }
Member Function Documentation
antDeviceNumber()
quint16z DeviceInfoMessage::antDeviceNumber () const
Returns the DeviceInfoMessage data message's antDeviceNumber field's current value.
Returns
the antDeviceNumber field value.
Definition at line 234 of file deviceinfomessage.cpp.
 {
     Q_D(const DeviceInfoMessage);
     return d->antDeviceNumber;
 }
Referenced by setAntDeviceNumber().
antNetwork()
AntNetwork DeviceInfoMessage::antNetwork () const
Returns the DeviceInfoMessage data message's antNetwork field's current value.
Returns
the antNetwork field value.
Definition at line 245 of file deviceinfomessage.cpp.
 {
     Q_D(const DeviceInfoMessage);
     return d->antNetwork;
 }
Referenced by setAntNetwork().
antTransmissionType()
quint8z DeviceInfoMessage::antTransmissionType () const
Returns the DeviceInfoMessage data message's antTransmissionType field's current value.
Returns
the antTransmissionType field value.
Definition at line 223 of file deviceinfomessage.cpp.
 {
     Q_D(const DeviceInfoMessage);
     return d->antTransmissionType;
 }
Referenced by setAntTransmissionType().
batteryStatus()
BatteryStatus DeviceInfoMessage::batteryStatus () const
Returns the DeviceInfoMessage data message's batteryStatus field's current value.
Returns
the batteryStatus field value.
Definition at line 186 of file deviceinfomessage.cpp.
 {
     Q_D(const DeviceInfoMessage);
     return d->batteryStatus;
 }
Referenced by setBatteryStatus().
batteryVoltage()
quint16 DeviceInfoMessage::batteryVoltage () const
Returns the DeviceInfoMessage data message's batteryVoltage field's current value.
Returns
the batteryVoltage field value.
Definition at line 175 of file deviceinfomessage.cpp.
 {
     Q_D(const DeviceInfoMessage);
     return d->batteryVoltage;
 }
Referenced by setBatteryVoltage().
cumOperatingTime()
quint32 DeviceInfoMessage::cumOperatingTime () const
Returns the DeviceInfoMessage data message's cumOperatingTime field's current value.
Reset by new battery or charge.
Returns
the cumOperatingTime field value.
Definition at line 164 of file deviceinfomessage.cpp.
 {
     Q_D(const DeviceInfoMessage);
     return d->cumOperatingTime;
 }
Referenced by setCumOperatingTime().
descriptor()
QString DeviceInfoMessage::descriptor () const
Returns the DeviceInfoMessage data message's descriptor field's current value.
Used to describe the sensor or location
Returns
the descriptor field value.
Definition at line 212 of file deviceinfomessage.cpp.
 {
     Q_D(const DeviceInfoMessage);
     return d->descriptor;
 }
Referenced by setDescriptor().
deviceIndex()
DeviceIndex DeviceInfoMessage::deviceIndex () const
Returns the DeviceInfoMessage data message's deviceIndex field's current value.
Returns
the deviceIndex field value.
Definition at line 85 of file deviceinfomessage.cpp.
 {
     Q_D(const DeviceInfoMessage);
     return d->deviceIndex;
 }
Referenced by setDeviceIndex().
deviceType()
quint8 DeviceInfoMessage::deviceType () const
Returns the DeviceInfoMessage data message's deviceType field's current value.
Returns
the deviceType field value.
Definition at line 96 of file deviceinfomessage.cpp.
 {
     Q_D(const DeviceInfoMessage);
     return d->deviceType;
 }
Referenced by setDeviceType().
hardwareVersion()
quint8 DeviceInfoMessage::hardwareVersion () const
Returns the DeviceInfoMessage data message's hardwareVersion field's current value.
Returns
the hardwareVersion field value.
Definition at line 151 of file deviceinfomessage.cpp.
 {
     Q_D(const DeviceInfoMessage);
     return d->hardwareVersion;
 }
Referenced by setHardwareVersion().
manufacturer()
Manufacturer DeviceInfoMessage::manufacturer () const
Returns the DeviceInfoMessage data message's manufacturer field's current value.
Returns
the manufacturer field value.
Definition at line 107 of file deviceinfomessage.cpp.
 {
     Q_D(const DeviceInfoMessage);
     return d->manufacturer;
 }
Referenced by setManufacturer().
product()
quint16 DeviceInfoMessage::product () const
Returns the DeviceInfoMessage data message's product field's current value.
Returns
the product field value.
Definition at line 129 of file deviceinfomessage.cpp.
 {
     Q_D(const DeviceInfoMessage);
     return d->product;
 }
Referenced by setProduct().
productName()
QString DeviceInfoMessage::productName () const
Returns the DeviceInfoMessage data message's productName field's current value.
Optional free form string to indicate the devices name or model
Returns
the productName field value.
Definition at line 269 of file deviceinfomessage.cpp.
 {
     Q_D(const DeviceInfoMessage);
     return d->productName;
 }
Referenced by setProductName().
sensorPosition()
BodyLocation DeviceInfoMessage::sensorPosition () const
Returns the DeviceInfoMessage data message's sensorPosition field's current value.
Indicates the location of the sensor
Returns
the sensorPosition field value.
Definition at line 199 of file deviceinfomessage.cpp.
 {
     Q_D(const DeviceInfoMessage);
     return d->sensorPosition;
 }
Referenced by setSensorPosition().
serialNumber()
quint32z DeviceInfoMessage::serialNumber () const
Returns the DeviceInfoMessage data message's serialNumber field's current value.
Returns
the serialNumber field value.
Definition at line 118 of file deviceinfomessage.cpp.
 {
     Q_D(const DeviceInfoMessage);
     return d->serialNumber;
 }
Referenced by setSerialNumber().
setAntDeviceNumber()
void DeviceInfoMessage::setAntDeviceNumber (const quint16z antDeviceNumber)
Sets the antDeviceNumber field to antDeviceNumber.
Parameters
antDeviceNumber The field value to set.
Definition at line 420 of file deviceinfomessage.cpp.
 {
     Q_D(DeviceInfoMessage);
     d->antDeviceNumber = antDeviceNumber;
 }
References antDeviceNumber().
setAntNetwork()
void DeviceInfoMessage::setAntNetwork (const AntNetwork antNetwork)
Sets the antNetwork field to antNetwork.
Parameters
antNetwork The field value to set.
Definition at line 430 of file deviceinfomessage.cpp.
 {
     Q_D(DeviceInfoMessage);
     d->antNetwork = antNetwork;
 }
References antNetwork().
setAntTransmissionType()
void DeviceInfoMessage::setAntTransmissionType (const quint8z antTransmissionType)
Sets the antTransmissionType field to antTransmissionType.
Parameters
antTransmissionType The field value to set.
Definition at line 410 of file deviceinfomessage.cpp.
 {
     Q_D(DeviceInfoMessage);
     d->antTransmissionType = antTransmissionType;
 }
References antTransmissionType().
setBatteryStatus()
void DeviceInfoMessage::setBatteryStatus (const BatteryStatus batteryStatus)
Sets the batteryStatus field to batteryStatus.
Parameters
batteryStatus The field value to set.
Definition at line 380 of file deviceinfomessage.cpp.
 {
     Q_D(DeviceInfoMessage);
     d->batteryStatus = batteryStatus;
 }
References batteryStatus().
setBatteryVoltage()
void DeviceInfoMessage::setBatteryVoltage (const quint16 batteryVoltage)
Sets the batteryVoltage field to batteryVoltage.
Parameters
batteryVoltage The field value to set.
Definition at line 370 of file deviceinfomessage.cpp.
 {
     Q_D(DeviceInfoMessage);
     d->batteryVoltage = batteryVoltage;
 }
References batteryVoltage().
setCumOperatingTime()
void DeviceInfoMessage::setCumOperatingTime (const quint32 cumOperatingTime)
Sets the cumOperatingTime field to cumOperatingTime.
Parameters
cumOperatingTime The field value to set.
Definition at line 360 of file deviceinfomessage.cpp.
 {
     Q_D(DeviceInfoMessage);
     d->cumOperatingTime = cumOperatingTime;
 }
References cumOperatingTime().
setDescriptor()
void DeviceInfoMessage::setDescriptor (const QString descriptor)
Sets the descriptor field to descriptor.
Parameters
descriptor The field value to set.
Definition at line 400 of file deviceinfomessage.cpp.
 {
     Q_D(DeviceInfoMessage);
     d->descriptor = descriptor;
 }
References descriptor().
setDeviceIndex()
void DeviceInfoMessage::setDeviceIndex (const DeviceIndex deviceIndex)
Sets the deviceIndex field to deviceIndex.
Parameters
deviceIndex The field value to set.
Definition at line 290 of file deviceinfomessage.cpp.
 {
     Q_D(DeviceInfoMessage);
     d->deviceIndex = deviceIndex;
 }
References deviceIndex().
setDeviceType()
void DeviceInfoMessage::setDeviceType (const quint8 deviceType)
Sets the deviceType field to deviceType.
Parameters
deviceType The field value to set.
Definition at line 300 of file deviceinfomessage.cpp.
 {
     Q_D(DeviceInfoMessage);
     d->deviceType = deviceType;
 }
References deviceType().
setHardwareVersion()
void DeviceInfoMessage::setHardwareVersion (const quint8 hardwareVersion)
Sets the hardwareVersion field to hardwareVersion.
Parameters
hardwareVersion The field value to set.
Definition at line 350 of file deviceinfomessage.cpp.
 {
     Q_D(DeviceInfoMessage);
     d->hardwareVersion = hardwareVersion;
 }
References hardwareVersion().
setManufacturer()
void DeviceInfoMessage::setManufacturer (const Manufacturer manufacturer)
Sets the manufacturer field to manufacturer.
Parameters
manufacturer The field value to set.
Definition at line 310 of file deviceinfomessage.cpp.
 {
     Q_D(DeviceInfoMessage);
     d->manufacturer = manufacturer;
 }
References manufacturer().
setProduct()
void DeviceInfoMessage::setProduct (const quint16 product)
Sets the product field to product.
Parameters
product The field value to set.
Definition at line 330 of file deviceinfomessage.cpp.
 {
     Q_D(DeviceInfoMessage);
     d->product = product;
 }
References product().
setProductName()
void DeviceInfoMessage::setProductName (const QString productName)
Sets the productName field to productName.
Parameters
productName The field value to set.
Definition at line 450 of file deviceinfomessage.cpp.
 {
     Q_D(DeviceInfoMessage);
     d->productName = productName;
 }
References productName().
setSensorPosition()
void DeviceInfoMessage::setSensorPosition (const BodyLocation sensorPosition)
Sets the sensorPosition field to sensorPosition.
Parameters
sensorPosition The field value to set.
Definition at line 390 of file deviceinfomessage.cpp.
 {
     Q_D(DeviceInfoMessage);
     d->sensorPosition = sensorPosition;
 }
References sensorPosition().
setSerialNumber()
void DeviceInfoMessage::setSerialNumber (const quint32z serialNumber)
Sets the serialNumber field to serialNumber.
Parameters
serialNumber The field value to set.
Definition at line 320 of file deviceinfomessage.cpp.
 {
     Q_D(DeviceInfoMessage);
     d->serialNumber = serialNumber;
 }
References serialNumber().
setSoftwareVersion()
void DeviceInfoMessage::setSoftwareVersion (const quint16 softwareVersion)
Sets the softwareVersion field to softwareVersion.
Parameters
softwareVersion The field value to set.
Definition at line 340 of file deviceinfomessage.cpp.
 {
     Q_D(DeviceInfoMessage);
     d->softwareVersion = softwareVersion;
 }
References softwareVersion().
setSourceType()
void DeviceInfoMessage::setSourceType (const SourceType sourceType)
Sets the sourceType field to sourceType.
Parameters
sourceType The field value to set.
Definition at line 440 of file deviceinfomessage.cpp.
 {
     Q_D(DeviceInfoMessage);
     d->sourceType = sourceType;
 }
References sourceType().
setTimestamp()
void DeviceInfoMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 280 of file deviceinfomessage.cpp.
 {
     Q_D(DeviceInfoMessage);
     d->timestamp = timestamp;
 }
References timestamp().
softwareVersion()
quint16 DeviceInfoMessage::softwareVersion () const
Returns the DeviceInfoMessage data message's softwareVersion field's current value.
Returns
the softwareVersion field value.
Definition at line 140 of file deviceinfomessage.cpp.
 {
     Q_D(const DeviceInfoMessage);
     return d->softwareVersion;
 }
Referenced by setSoftwareVersion().
sourceType()
SourceType DeviceInfoMessage::sourceType () const
Returns the DeviceInfoMessage data message's sourceType field's current value.
Returns
the sourceType field value.
Definition at line 256 of file deviceinfomessage.cpp.
 {
     Q_D(const DeviceInfoMessage);
     return d->sourceType;
 }
Referenced by setSourceType().
timestamp()
DateTime DeviceInfoMessage::timestamp () const
Returns the DeviceInfoMessage data message's timestamp field's current value.
Returns
the timestamp field value.
Definition at line 74 of file deviceinfomessage.cpp.
 {
     Q_D(const DeviceInfoMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
The documentation for this class was generated from the following files:
deviceinfomessage.h
deviceinfomessage.cpp