QtFit: VideoDescriptionMessage Class Reference
VideoDescriptionMessage Class Reference
The VideoDescriptionMessage class represents a FIT VideoDescriptionMessage data message.
Public Member Functions
VideoDescriptionMessage ()
Constructs a VideoDescriptionMessage object.
MessageIndex messageIndex () const
Returns the VideoDescriptionMessage data message's messageIndex field's current value.
quint16 messageCount () const
Returns the VideoDescriptionMessage data message's messageCount field's current value.
QString text () const
Returns the VideoDescriptionMessage data message's text field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setMessageCount (const quint16 messageCount)
Sets the messageCount field to messageCount.
void setText (const QString text)
Sets the text field to text.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
VideoDescriptionMessage (VideoDescriptionMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The VideoDescriptionMessage class represents a FIT VideoDescriptionMessage data message.
See also
DataMessage
Definition at line 39 of file videodescriptionmessage.h.
Constructor & Destructor Documentation
VideoDescriptionMessage() [1/2]
VideoDescriptionMessage::VideoDescriptionMessage ()
Constructs a VideoDescriptionMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file videodescriptionmessage.cpp.
                                                  : AbstractDataMessage(new VideoDescriptionMessagePrivate(this))
 {
 }
VideoDescriptionMessage() [2/2]
VideoDescriptionMessage::VideoDescriptionMessage (VideoDescriptionMessagePrivate *const d) explicit protected
Constructs a VideoDescriptionMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file videodescriptionmessage.cpp.
                                                                                          : AbstractDataMessage(d)
 {
 }
Member Function Documentation
messageCount()
quint16 VideoDescriptionMessage::messageCount () const
Returns the VideoDescriptionMessage data message's messageCount field's current value.
Total number of description parts
Returns
the messageCount field value.
Definition at line 89 of file videodescriptionmessage.cpp.
 {
     Q_D(const VideoDescriptionMessage);
     return d->messageCount;
 }
Referenced by setMessageCount().
messageIndex()
MessageIndex VideoDescriptionMessage::messageIndex () const
Returns the VideoDescriptionMessage data message's messageIndex field's current value.
Long descriptions will be split into multiple parts
Returns
the messageIndex field value.
Definition at line 76 of file videodescriptionmessage.cpp.
 {
     Q_D(const VideoDescriptionMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
setMessageCount()
void VideoDescriptionMessage::setMessageCount (const quint16 messageCount)
Sets the messageCount field to messageCount.
Parameters
messageCount The field value to set.
Definition at line 121 of file videodescriptionmessage.cpp.
 {
     Q_D(VideoDescriptionMessage);
     d->messageCount = messageCount;
 }
References messageCount().
setMessageIndex()
void VideoDescriptionMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 111 of file videodescriptionmessage.cpp.
 {
     Q_D(VideoDescriptionMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setText()
void VideoDescriptionMessage::setText (const QString text)
Sets the text field to text.
Parameters
text The field value to set.
Definition at line 131 of file videodescriptionmessage.cpp.
 {
     Q_D(VideoDescriptionMessage);
     d->text = text;
 }
References text().
text()
QString VideoDescriptionMessage::text () const
Returns the VideoDescriptionMessage data message's text field's current value.
Returns
the text field value.
Definition at line 100 of file videodescriptionmessage.cpp.
 {
     Q_D(const VideoDescriptionMessage);
     return d->text;
 }
Referenced by setText().
The documentation for this class was generated from the following files:
videodescriptionmessage.h
videodescriptionmessage.cpp