QtFit: ThreeDSensorCalibrationMessage Class Reference
ThreeDSensorCalibrationMessage Class Reference
The ThreeDSensorCalibrationMessage class represents a FIT ThreeDSensorCalibrationMessage data message.
Public Member Functions
ThreeDSensorCalibrationMessage ()
Constructs a ThreeDSensorCalibrationMessage object.
DateTime timestamp () const
Returns the ThreeDSensorCalibrationMessage data message's timestamp field's current value.
SensorType sensorType () const
Returns the ThreeDSensorCalibrationMessage data message's sensorType field's current value.
quint32 calibrationFactor () const
Returns the ThreeDSensorCalibrationMessage data message's calibrationFactor field's current value.
quint32 calibrationDivisor () const
Returns the ThreeDSensorCalibrationMessage data message's calibrationDivisor field's current value.
quint32 levelShift () const
Returns the ThreeDSensorCalibrationMessage data message's levelShift field's current value.
qint32 offsetCal () const
Returns the ThreeDSensorCalibrationMessage data message's offsetCal field's current value.
qint32 orientationMatrix () const
Returns the ThreeDSensorCalibrationMessage data message's orientationMatrix field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setSensorType (const SensorType sensorType)
Sets the sensorType field to sensorType.
void setCalibrationFactor (const quint32 calibrationFactor)
Sets the calibrationFactor field to calibrationFactor.
void setCalibrationDivisor (const quint32 calibrationDivisor)
Sets the calibrationDivisor field to calibrationDivisor.
void setLevelShift (const quint32 levelShift)
Sets the levelShift field to levelShift.
void setOffsetCal (const qint32 offsetCal)
Sets the offsetCal field to offsetCal.
void setOrientationMatrix (const qint32 orientationMatrix)
Sets the orientationMatrix field to orientationMatrix.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
ThreeDSensorCalibrationMessage (ThreeDSensorCalibrationMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The ThreeDSensorCalibrationMessage class represents a FIT ThreeDSensorCalibrationMessage data message.
See also
DataMessage
Definition at line 39 of file threedsensorcalibrationmessage.h.
Constructor & Destructor Documentation
ThreeDSensorCalibrationMessage() [1/2]
ThreeDSensorCalibrationMessage::ThreeDSensorCalibrationMessage ()
Constructs a ThreeDSensorCalibrationMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file threedsensorcalibrationmessage.cpp.
                                                                : AbstractDataMessage(new ThreeDSensorCalibrationMessagePrivate(this))
 {
 }
ThreeDSensorCalibrationMessage() [2/2]
ThreeDSensorCalibrationMessage::ThreeDSensorCalibrationMessage (ThreeDSensorCalibrationMessagePrivate *const d) explicit protected
Constructs a ThreeDSensorCalibrationMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file threedsensorcalibrationmessage.cpp.
                                                                                                               : AbstractDataMessage(d)
 {
 }
Member Function Documentation
calibrationDivisor()
quint32 ThreeDSensorCalibrationMessage::calibrationDivisor () const
Returns the ThreeDSensorCalibrationMessage data message's calibrationDivisor field's current value.
Calibration factor divisor
Returns
the calibrationDivisor field value.
Definition at line 115 of file threedsensorcalibrationmessage.cpp.
 {
     Q_D(const ThreeDSensorCalibrationMessage);
     return d->calibrationDivisor;
 }
Referenced by setCalibrationDivisor().
calibrationFactor()
quint32 ThreeDSensorCalibrationMessage::calibrationFactor () const
Returns the ThreeDSensorCalibrationMessage data message's calibrationFactor field's current value.
Calibration factor used to convert from raw ADC value to degrees, g, etc.
Returns
the calibrationFactor field value.
Definition at line 102 of file threedsensorcalibrationmessage.cpp.
 {
     Q_D(const ThreeDSensorCalibrationMessage);
     return d->calibrationFactor;
 }
Referenced by setCalibrationFactor().
levelShift()
quint32 ThreeDSensorCalibrationMessage::levelShift () const
Returns the ThreeDSensorCalibrationMessage data message's levelShift field's current value.
Level shift value used to shift the ADC value back into range
Returns
the levelShift field value.
Definition at line 128 of file threedsensorcalibrationmessage.cpp.
 {
     Q_D(const ThreeDSensorCalibrationMessage);
     return d->levelShift;
 }
Referenced by setLevelShift().
offsetCal()
qint32 ThreeDSensorCalibrationMessage::offsetCal () const
Returns the ThreeDSensorCalibrationMessage data message's offsetCal field's current value.
Internal calibration factors, one for each: xy, yx, zx
Returns
the offsetCal field value.
Definition at line 141 of file threedsensorcalibrationmessage.cpp.
 {
     Q_D(const ThreeDSensorCalibrationMessage);
     return d->offsetCal;
 }
Referenced by setOffsetCal().
orientationMatrix()
qint32 ThreeDSensorCalibrationMessage::orientationMatrix () const
Returns the ThreeDSensorCalibrationMessage data message's orientationMatrix field's current value.
3 x 3 rotation matrix (row major)
Returns
the orientationMatrix field value.
Definition at line 154 of file threedsensorcalibrationmessage.cpp.
 {
     Q_D(const ThreeDSensorCalibrationMessage);
     return d->orientationMatrix;
 }
Referenced by setOrientationMatrix().
sensorType()
SensorType ThreeDSensorCalibrationMessage::sensorType () const
Returns the ThreeDSensorCalibrationMessage data message's sensorType field's current value.
Indicates which sensor the calibration is for
Returns
the sensorType field value.
Definition at line 89 of file threedsensorcalibrationmessage.cpp.
 {
     Q_D(const ThreeDSensorCalibrationMessage);
     return d->sensorType;
 }
Referenced by setSensorType().
setCalibrationDivisor()
void ThreeDSensorCalibrationMessage::setCalibrationDivisor (const quint32 calibrationDivisor)
Sets the calibrationDivisor field to calibrationDivisor.
Parameters
calibrationDivisor The field value to set.
Definition at line 195 of file threedsensorcalibrationmessage.cpp.
 {
     Q_D(ThreeDSensorCalibrationMessage);
     d->calibrationDivisor = calibrationDivisor;
 }
References calibrationDivisor().
setCalibrationFactor()
void ThreeDSensorCalibrationMessage::setCalibrationFactor (const quint32 calibrationFactor)
Sets the calibrationFactor field to calibrationFactor.
Parameters
calibrationFactor The field value to set.
Definition at line 185 of file threedsensorcalibrationmessage.cpp.
 {
     Q_D(ThreeDSensorCalibrationMessage);
     d->calibrationFactor = calibrationFactor;
 }
References calibrationFactor().
setLevelShift()
void ThreeDSensorCalibrationMessage::setLevelShift (const quint32 levelShift)
Sets the levelShift field to levelShift.
Parameters
levelShift The field value to set.
Definition at line 205 of file threedsensorcalibrationmessage.cpp.
 {
     Q_D(ThreeDSensorCalibrationMessage);
     d->levelShift = levelShift;
 }
References levelShift().
setOffsetCal()
void ThreeDSensorCalibrationMessage::setOffsetCal (const qint32 offsetCal)
Sets the offsetCal field to offsetCal.
Parameters
offsetCal The field value to set.
Definition at line 215 of file threedsensorcalibrationmessage.cpp.
 {
     Q_D(ThreeDSensorCalibrationMessage);
     d->offsetCal = offsetCal;
 }
References offsetCal().
setOrientationMatrix()
void ThreeDSensorCalibrationMessage::setOrientationMatrix (const qint32 orientationMatrix)
Sets the orientationMatrix field to orientationMatrix.
Parameters
orientationMatrix The field value to set.
Definition at line 225 of file threedsensorcalibrationmessage.cpp.
 {
     Q_D(ThreeDSensorCalibrationMessage);
     d->orientationMatrix = orientationMatrix;
 }
References orientationMatrix().
setSensorType()
void ThreeDSensorCalibrationMessage::setSensorType (const SensorType sensorType)
Sets the sensorType field to sensorType.
Parameters
sensorType The field value to set.
Definition at line 175 of file threedsensorcalibrationmessage.cpp.
 {
     Q_D(ThreeDSensorCalibrationMessage);
     d->sensorType = sensorType;
 }
References sensorType().
setTimestamp()
void ThreeDSensorCalibrationMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 165 of file threedsensorcalibrationmessage.cpp.
 {
     Q_D(ThreeDSensorCalibrationMessage);
     d->timestamp = timestamp;
 }
References timestamp().
timestamp()
DateTime ThreeDSensorCalibrationMessage::timestamp () const
Returns the ThreeDSensorCalibrationMessage data message's timestamp field's current value.
Whole second part of the timestamp
Returns
the timestamp field value.
Definition at line 76 of file threedsensorcalibrationmessage.cpp.
 {
     Q_D(const ThreeDSensorCalibrationMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
The documentation for this class was generated from the following files:
threedsensorcalibrationmessage.h
threedsensorcalibrationmessage.cpp