QtFit: MemoGlobMessage Class Reference
MemoGlobMessage Class Reference
The MemoGlobMessage class represents a FIT MemoGlobMessage data message.
#include <memoglobmessage.h>
Public Member Functions
MemoGlobMessage ()
Constructs an invalid MemoGlobMessage object.
~MemoGlobMessage ()
quint32 partIndex () const
Returns the MemoGlobMessage data message's partIndex field's current value.
quint8 memo () const
Returns the MemoGlobMessage data message's memo field's current value.
quint16 messageNumber () const
Returns the MemoGlobMessage data message's messageNumber field's current value.
MessageIndex messageIndex () const
Returns the MemoGlobMessage data message's messageIndex field's current value.
void setPartIndex (const quint32 partIndex)
Sets the partIndex field to partIndex.
void setMemo (const quint8 memo)
Sets the memo field to memo.
void setMessageNumber (const quint16 messageNumber)
Sets the messageNumber field to messageNumber.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Public Member Functions inherited from FitDataMessage
FitDataMessage ()
Constructs a invalid, null FitDataMessage object.
FitDataMessage (const FitDataMessage &other)
Copies a FitDataMessage.
FitDataMessage & operator= (const FitDataMessage &other)
Assigns a FitDataMessage to this one.
~FitDataMessage ()
Destroys the FitDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
bool isNull () const
Returns true if this is not a valid data message, otherwise false.
Additional Inherited Members
Static Public Member Functions inherited from FitDataMessage
static FitDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant FitDataMessage-derived class to parse record according to defn.
Detailed Description
The MemoGlobMessage class represents a FIT MemoGlobMessage data message.
See also
DataMessage
Definition at line 34 of file memoglobmessage.h.
Constructor & Destructor Documentation
MemoGlobMessage()
MemoGlobMessage::MemoGlobMessage ()
Constructs an invalid MemoGlobMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file memoglobmessage.cpp.
                                  : FitDataMessage(new MemoGlobMessagePrivate(this))
 {
 }
~MemoGlobMessage()
MemoGlobMessage::~MemoGlobMessage ()
Member Function Documentation
memo()
quint8 MemoGlobMessage::memo () const
Returns the MemoGlobMessage data message's memo field's current value.
Returns
the memo field value.
Definition at line 68 of file memoglobmessage.cpp.
 {
     Q_D(const MemoGlobMessage);
     return d->memo;
 }
Referenced by setMemo().
messageIndex()
MessageIndex MemoGlobMessage::messageIndex () const
Returns the MemoGlobMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 90 of file memoglobmessage.cpp.
 {
     Q_D(const MemoGlobMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
messageNumber()
quint16 MemoGlobMessage::messageNumber () const
Returns the MemoGlobMessage data message's messageNumber field's current value.
Returns
the messageNumber field value.
Definition at line 79 of file memoglobmessage.cpp.
 {
     Q_D(const MemoGlobMessage);
     return d->messageNumber;
 }
Referenced by setMessageNumber().
partIndex()
quint32 MemoGlobMessage::partIndex () const
Returns the MemoGlobMessage data message's partIndex field's current value.
Returns
the partIndex field value.
Definition at line 57 of file memoglobmessage.cpp.
 {
     Q_D(const MemoGlobMessage);
     return d->partIndex;
 }
Referenced by setPartIndex().
setMemo()
void MemoGlobMessage::setMemo (const quint8 memo)
Sets the memo field to memo.
Parameters
memo The field value to set.
Definition at line 111 of file memoglobmessage.cpp.
 {
     Q_D(MemoGlobMessage);
     d->memo = memo;
 }
References memo().
setMessageIndex()
void MemoGlobMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 131 of file memoglobmessage.cpp.
 {
     Q_D(MemoGlobMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setMessageNumber()
void MemoGlobMessage::setMessageNumber (const quint16 messageNumber)
Sets the messageNumber field to messageNumber.
Parameters
messageNumber The field value to set.
Definition at line 121 of file memoglobmessage.cpp.
 {
     Q_D(MemoGlobMessage);
     d->messageNumber = messageNumber;
 }
References messageNumber().
setPartIndex()
void MemoGlobMessage::setPartIndex (const quint32 partIndex)
Sets the partIndex field to partIndex.
Parameters
partIndex The field value to set.
Definition at line 101 of file memoglobmessage.cpp.
 {
     Q_D(MemoGlobMessage);
     d->partIndex = partIndex;
 }
References partIndex().
The documentation for this class was generated from the following files:
memoglobmessage.h
memoglobmessage.cpp