QtFit: FileIdMessage Class Reference
FileIdMessage Class Reference
The FileIdMessage class represents a FIT FileIdMessage data message.
Public Member Functions
FileIdMessage ()
Constructs a FileIdMessage object.
File type () const
Returns the FileIdMessage data message's type field's current value.
Manufacturer manufacturer () const
Returns the FileIdMessage data message's manufacturer field's current value.
quint16 product () const
Returns the FileIdMessage data message's product field's current value.
quint32z serialNumber () const
Returns the FileIdMessage data message's serialNumber field's current value.
DateTime timeCreated () const
Returns the FileIdMessage data message's timeCreated field's current value.
quint16 number () const
Returns the FileIdMessage data message's number field's current value.
QString productName () const
Returns the FileIdMessage data message's productName field's current value.
void setType (const File type)
Sets the type field to type.
void setManufacturer (const Manufacturer manufacturer)
Sets the manufacturer field to manufacturer.
void setProduct (const quint16 product)
Sets the product field to product.
void setSerialNumber (const quint32z serialNumber)
Sets the serialNumber field to serialNumber.
void setTimeCreated (const DateTime timeCreated)
Sets the timeCreated field to timeCreated.
void setNumber (const quint16 number)
Sets the number field to number.
void setProductName (const QString productName)
Sets the productName field to productName.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
FileIdMessage (FileIdMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The FileIdMessage class represents a FIT FileIdMessage data message.
See also
DataMessage
Definition at line 39 of file fileidmessage.h.
Constructor & Destructor Documentation
FileIdMessage() [1/2]
FileIdMessage::FileIdMessage ()
Constructs a FileIdMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file fileidmessage.cpp.
                              : AbstractDataMessage(new FileIdMessagePrivate(this))
 {
 }
FileIdMessage() [2/2]
FileIdMessage::FileIdMessage (FileIdMessagePrivate *const d) explicit protected
Constructs a FileIdMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file fileidmessage.cpp.
                                                            : AbstractDataMessage(d)
 {
 }
Member Function Documentation
manufacturer()
Manufacturer FileIdMessage::manufacturer () const
Returns the FileIdMessage data message's manufacturer field's current value.
Returns
the manufacturer field value.
Definition at line 85 of file fileidmessage.cpp.
 {
     Q_D(const FileIdMessage);
     return d->manufacturer;
 }
Referenced by setManufacturer().
number()
quint16 FileIdMessage::number () const
Returns the FileIdMessage data message's number field's current value.
Only set for files that are not created/erased.
Returns
the number field value.
Definition at line 133 of file fileidmessage.cpp.
 {
     Q_D(const FileIdMessage);
     return d->number;
 }
Referenced by setNumber().
product()
quint16 FileIdMessage::product () const
Returns the FileIdMessage data message's product field's current value.
Returns
the product field value.
Definition at line 96 of file fileidmessage.cpp.
 {
     Q_D(const FileIdMessage);
     return d->product;
 }
Referenced by setProduct().
productName()
QString FileIdMessage::productName () const
Returns the FileIdMessage data message's productName field's current value.
Optional free form string to indicate the devices name or model
Returns
the productName field value.
Definition at line 146 of file fileidmessage.cpp.
 {
     Q_D(const FileIdMessage);
     return d->productName;
 }
Referenced by setProductName().
serialNumber()
quint32z FileIdMessage::serialNumber () const
Returns the FileIdMessage data message's serialNumber field's current value.
Returns
the serialNumber field value.
Definition at line 107 of file fileidmessage.cpp.
 {
     Q_D(const FileIdMessage);
     return d->serialNumber;
 }
Referenced by setSerialNumber().
setManufacturer()
void FileIdMessage::setManufacturer (const Manufacturer manufacturer)
Sets the manufacturer field to manufacturer.
Parameters
manufacturer The field value to set.
Definition at line 167 of file fileidmessage.cpp.
 {
     Q_D(FileIdMessage);
     d->manufacturer = manufacturer;
 }
References manufacturer().
setNumber()
void FileIdMessage::setNumber (const quint16 number)
Sets the number field to number.
Parameters
number The field value to set.
Definition at line 207 of file fileidmessage.cpp.
 {
     Q_D(FileIdMessage);
     d->number = number;
 }
References number().
setProduct()
void FileIdMessage::setProduct (const quint16 product)
Sets the product field to product.
Parameters
product The field value to set.
Definition at line 177 of file fileidmessage.cpp.
 {
     Q_D(FileIdMessage);
     d->product = product;
 }
References product().
setProductName()
void FileIdMessage::setProductName (const QString productName)
Sets the productName field to productName.
Parameters
productName The field value to set.
Definition at line 217 of file fileidmessage.cpp.
 {
     Q_D(FileIdMessage);
     d->productName = productName;
 }
References productName().
setSerialNumber()
void FileIdMessage::setSerialNumber (const quint32z serialNumber)
Sets the serialNumber field to serialNumber.
Parameters
serialNumber The field value to set.
Definition at line 187 of file fileidmessage.cpp.
 {
     Q_D(FileIdMessage);
     d->serialNumber = serialNumber;
 }
References serialNumber().
setTimeCreated()
void FileIdMessage::setTimeCreated (const DateTime timeCreated)
Sets the timeCreated field to timeCreated.
Parameters
timeCreated The field value to set.
Definition at line 197 of file fileidmessage.cpp.
 {
     Q_D(FileIdMessage);
     d->timeCreated = timeCreated;
 }
References timeCreated().
setType()
void FileIdMessage::setType (const File type)
Sets the type field to type.
Parameters
type The field value to set.
Definition at line 157 of file fileidmessage.cpp.
 {
     Q_D(FileIdMessage);
     d->type = type;
 }
References type().
timeCreated()
DateTime FileIdMessage::timeCreated () const
Returns the FileIdMessage data message's timeCreated field's current value.
Only set for files that are can be created/erased.
Returns
the timeCreated field value.
Definition at line 120 of file fileidmessage.cpp.
 {
     Q_D(const FileIdMessage);
     return d->timeCreated;
 }
Referenced by setTimeCreated().
type()
File FileIdMessage::type () const
Returns the FileIdMessage data message's type field's current value.
Returns
the type field value.
Definition at line 74 of file fileidmessage.cpp.
 {
     Q_D(const FileIdMessage);
     return d->type;
 }
Referenced by setType().
The documentation for this class was generated from the following files:
fileidmessage.h
fileidmessage.cpp