QtFit: SpeedZoneMessage Class Reference
SpeedZoneMessage Class Reference
The SpeedZoneMessage class represents a FIT SpeedZoneMessage data message.
Public Member Functions
SpeedZoneMessage ()
Constructs a SpeedZoneMessage object.
MessageIndex messageIndex () const
Returns the SpeedZoneMessage data message's messageIndex field's current value.
quint16 highValue () const
Returns the SpeedZoneMessage data message's highValue field's current value.
QString name () const
Returns the SpeedZoneMessage data message's name field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setHighValue (const quint16 highValue)
Sets the highValue field to highValue.
void setName (const QString name)
Sets the name field to name.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
SpeedZoneMessage (SpeedZoneMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The SpeedZoneMessage class represents a FIT SpeedZoneMessage data message.
See also
DataMessage
Definition at line 39 of file speedzonemessage.h.
Constructor & Destructor Documentation
SpeedZoneMessage() [1/2]
SpeedZoneMessage::SpeedZoneMessage ()
Constructs a SpeedZoneMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file speedzonemessage.cpp.
                                    : AbstractDataMessage(new SpeedZoneMessagePrivate(this))
 {
 }
SpeedZoneMessage() [2/2]
SpeedZoneMessage::SpeedZoneMessage (SpeedZoneMessagePrivate *const d) explicit protected
Constructs a SpeedZoneMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file speedzonemessage.cpp.
                                                                     : AbstractDataMessage(d)
 {
 }
Member Function Documentation
highValue()
quint16 SpeedZoneMessage::highValue () const
Returns the SpeedZoneMessage data message's highValue field's current value.
Returns
the highValue field value.
Definition at line 85 of file speedzonemessage.cpp.
 {
     Q_D(const SpeedZoneMessage);
     return d->highValue;
 }
Referenced by setHighValue().
messageIndex()
MessageIndex SpeedZoneMessage::messageIndex () const
Returns the SpeedZoneMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 74 of file speedzonemessage.cpp.
 {
     Q_D(const SpeedZoneMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
name()
QString SpeedZoneMessage::name () const
Returns the SpeedZoneMessage data message's name field's current value.
Returns
the name field value.
Definition at line 96 of file speedzonemessage.cpp.
 {
     Q_D(const SpeedZoneMessage);
     return d->name;
 }
Referenced by setName().
setHighValue()
void SpeedZoneMessage::setHighValue (const quint16 highValue)
Sets the highValue field to highValue.
Parameters
highValue The field value to set.
Definition at line 117 of file speedzonemessage.cpp.
 {
     Q_D(SpeedZoneMessage);
     d->highValue = highValue;
 }
References highValue().
setMessageIndex()
void SpeedZoneMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 107 of file speedzonemessage.cpp.
 {
     Q_D(SpeedZoneMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setName()
void SpeedZoneMessage::setName (const QString name)
Sets the name field to name.
Parameters
name The field value to set.
Definition at line 127 of file speedzonemessage.cpp.
 {
     Q_D(SpeedZoneMessage);
     d->name = name;
 }
References name().
The documentation for this class was generated from the following files:
speedzonemessage.h
speedzonemessage.cpp