QtFit: ScheduleMessage Class Reference
ScheduleMessage Class Reference
The ScheduleMessage class represents a FIT ScheduleMessage data message.
Public Member Functions
ScheduleMessage ()
Constructs a ScheduleMessage object.
Manufacturer manufacturer () const
Returns the ScheduleMessage data message's manufacturer field's current value.
quint16 product () const
Returns the ScheduleMessage data message's product field's current value.
quint32z serialNumber () const
Returns the ScheduleMessage data message's serialNumber field's current value.
DateTime timeCreated () const
Returns the ScheduleMessage data message's timeCreated field's current value.
bool completed () const
Returns the ScheduleMessage data message's completed field's current value.
Schedule type () const
Returns the ScheduleMessage data message's type field's current value.
LocalDateTime scheduledTime () const
Returns the ScheduleMessage data message's scheduledTime field's current value.
void setManufacturer (const Manufacturer manufacturer)
Sets the manufacturer field to manufacturer.
void setProduct (const quint16 product)
Sets the product field to product.
void setSerialNumber (const quint32z serialNumber)
Sets the serialNumber field to serialNumber.
void setTimeCreated (const DateTime timeCreated)
Sets the timeCreated field to timeCreated.
void setCompleted (const bool completed)
Sets the completed field to completed.
void setType (const Schedule type)
Sets the type field to type.
void setScheduledTime (const LocalDateTime scheduledTime)
Sets the scheduledTime field to scheduledTime.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
ScheduleMessage (ScheduleMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The ScheduleMessage class represents a FIT ScheduleMessage data message.
See also
DataMessage
Definition at line 39 of file schedulemessage.h.
Constructor & Destructor Documentation
ScheduleMessage() [1/2]
ScheduleMessage::ScheduleMessage ()
Constructs a ScheduleMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file schedulemessage.cpp.
                                  : AbstractDataMessage(new ScheduleMessagePrivate(this))
 {
 }
ScheduleMessage() [2/2]
ScheduleMessage::ScheduleMessage (ScheduleMessagePrivate *const d) explicit protected
Constructs a ScheduleMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file schedulemessage.cpp.
                                                                  : AbstractDataMessage(d)
 {
 }
Member Function Documentation
completed()
bool ScheduleMessage::completed () const
Returns the ScheduleMessage data message's completed field's current value.
TRUE if this activity has been started
Returns
the completed field value.
Definition at line 128 of file schedulemessage.cpp.
 {
     Q_D(const ScheduleMessage);
     return d->completed;
 }
Referenced by setCompleted().
manufacturer()
Manufacturer ScheduleMessage::manufacturer () const
Returns the ScheduleMessage data message's manufacturer field's current value.
Corresponds to file_id of scheduled workout / course.
Returns
the manufacturer field value.
Definition at line 76 of file schedulemessage.cpp.
 {
     Q_D(const ScheduleMessage);
     return d->manufacturer;
 }
Referenced by setManufacturer().
product()
quint16 ScheduleMessage::product () const
Returns the ScheduleMessage data message's product field's current value.
Corresponds to file_id of scheduled workout / course.
Returns
the product field value.
Definition at line 89 of file schedulemessage.cpp.
 {
     Q_D(const ScheduleMessage);
     return d->product;
 }
Referenced by setProduct().
scheduledTime()
LocalDateTime ScheduleMessage::scheduledTime () const
Returns the ScheduleMessage data message's scheduledTime field's current value.
Returns
the scheduledTime field value.
Definition at line 150 of file schedulemessage.cpp.
 {
     Q_D(const ScheduleMessage);
     return d->scheduledTime;
 }
Referenced by setScheduledTime().
serialNumber()
quint32z ScheduleMessage::serialNumber () const
Returns the ScheduleMessage data message's serialNumber field's current value.
Corresponds to file_id of scheduled workout / course.
Returns
the serialNumber field value.
Definition at line 102 of file schedulemessage.cpp.
 {
     Q_D(const ScheduleMessage);
     return d->serialNumber;
 }
Referenced by setSerialNumber().
setCompleted()
void ScheduleMessage::setCompleted (const bool completed)
Sets the completed field to completed.
Parameters
completed The field value to set.
Definition at line 201 of file schedulemessage.cpp.
 {
     Q_D(ScheduleMessage);
     d->completed = completed;
 }
References completed().
setManufacturer()
void ScheduleMessage::setManufacturer (const Manufacturer manufacturer)
Sets the manufacturer field to manufacturer.
Parameters
manufacturer The field value to set.
Definition at line 161 of file schedulemessage.cpp.
 {
     Q_D(ScheduleMessage);
     d->manufacturer = manufacturer;
 }
References manufacturer().
setProduct()
void ScheduleMessage::setProduct (const quint16 product)
Sets the product field to product.
Parameters
product The field value to set.
Definition at line 171 of file schedulemessage.cpp.
 {
     Q_D(ScheduleMessage);
     d->product = product;
 }
References product().
setScheduledTime()
void ScheduleMessage::setScheduledTime (const LocalDateTime scheduledTime)
Sets the scheduledTime field to scheduledTime.
Parameters
scheduledTime The field value to set.
Definition at line 221 of file schedulemessage.cpp.
 {
     Q_D(ScheduleMessage);
     d->scheduledTime = scheduledTime;
 }
References scheduledTime().
setSerialNumber()
void ScheduleMessage::setSerialNumber (const quint32z serialNumber)
Sets the serialNumber field to serialNumber.
Parameters
serialNumber The field value to set.
Definition at line 181 of file schedulemessage.cpp.
 {
     Q_D(ScheduleMessage);
     d->serialNumber = serialNumber;
 }
References serialNumber().
setTimeCreated()
void ScheduleMessage::setTimeCreated (const DateTime timeCreated)
Sets the timeCreated field to timeCreated.
Parameters
timeCreated The field value to set.
Definition at line 191 of file schedulemessage.cpp.
 {
     Q_D(ScheduleMessage);
     d->timeCreated = timeCreated;
 }
References timeCreated().
setType()
void ScheduleMessage::setType (const Schedule type)
Sets the type field to type.
Parameters
type The field value to set.
Definition at line 211 of file schedulemessage.cpp.
 {
     Q_D(ScheduleMessage);
     d->type = type;
 }
References type().
timeCreated()
DateTime ScheduleMessage::timeCreated () const
Returns the ScheduleMessage data message's timeCreated field's current value.
Corresponds to file_id of scheduled workout / course.
Returns
the timeCreated field value.
Definition at line 115 of file schedulemessage.cpp.
 {
     Q_D(const ScheduleMessage);
     return d->timeCreated;
 }
Referenced by setTimeCreated().
type()
Schedule ScheduleMessage::type () const
Returns the ScheduleMessage data message's type field's current value.
Returns
the type field value.
Definition at line 139 of file schedulemessage.cpp.
 {
     Q_D(const ScheduleMessage);
     return d->type;
 }
Referenced by setType().
The documentation for this class was generated from the following files:
schedulemessage.h
schedulemessage.cpp