QtFit: AntChannelIdMessage Class Reference
AntChannelIdMessage Class Reference
The AntChannelIdMessage class represents a FIT AntChannelIdMessage data message.
Public Member Functions
AntChannelIdMessage ()
Constructs a AntChannelIdMessage object.
quint8 channelNumber () const
Returns the AntChannelIdMessage data message's channelNumber field's current value.
quint8z deviceType () const
Returns the AntChannelIdMessage data message's deviceType field's current value.
quint16z deviceNumber () const
Returns the AntChannelIdMessage data message's deviceNumber field's current value.
quint8z transmissionType () const
Returns the AntChannelIdMessage data message's transmissionType field's current value.
DeviceIndex deviceIndex () const
Returns the AntChannelIdMessage data message's deviceIndex field's current value.
void setChannelNumber (const quint8 channelNumber)
Sets the channelNumber field to channelNumber.
void setDeviceType (const quint8z deviceType)
Sets the deviceType field to deviceType.
void setDeviceNumber (const quint16z deviceNumber)
Sets the deviceNumber field to deviceNumber.
void setTransmissionType (const quint8z transmissionType)
Sets the transmissionType field to transmissionType.
void setDeviceIndex (const DeviceIndex deviceIndex)
Sets the deviceIndex field to deviceIndex.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
AntChannelIdMessage (AntChannelIdMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The AntChannelIdMessage class represents a FIT AntChannelIdMessage data message.
See also
DataMessage
Definition at line 39 of file antchannelidmessage.h.
Constructor & Destructor Documentation
AntChannelIdMessage() [1/2]
AntChannelIdMessage::AntChannelIdMessage ()
Constructs a AntChannelIdMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file antchannelidmessage.cpp.
                                          : AbstractDataMessage(new AntChannelIdMessagePrivate(this))
 {
 }
AntChannelIdMessage() [2/2]
AntChannelIdMessage::AntChannelIdMessage (AntChannelIdMessagePrivate *const d) explicit protected
Constructs a AntChannelIdMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file antchannelidmessage.cpp.
                                                                              : AbstractDataMessage(d)
 {
 }
Member Function Documentation
channelNumber()
quint8 AntChannelIdMessage::channelNumber () const
Returns the AntChannelIdMessage data message's channelNumber field's current value.
Returns
the channelNumber field value.
Definition at line 74 of file antchannelidmessage.cpp.
 {
     Q_D(const AntChannelIdMessage);
     return d->channelNumber;
 }
Referenced by setChannelNumber().
deviceIndex()
DeviceIndex AntChannelIdMessage::deviceIndex () const
Returns the AntChannelIdMessage data message's deviceIndex field's current value.
Returns
the deviceIndex field value.
Definition at line 118 of file antchannelidmessage.cpp.
 {
     Q_D(const AntChannelIdMessage);
     return d->deviceIndex;
 }
Referenced by setDeviceIndex().
deviceNumber()
quint16z AntChannelIdMessage::deviceNumber () const
Returns the AntChannelIdMessage data message's deviceNumber field's current value.
Returns
the deviceNumber field value.
Definition at line 96 of file antchannelidmessage.cpp.
 {
     Q_D(const AntChannelIdMessage);
     return d->deviceNumber;
 }
Referenced by setDeviceNumber().
deviceType()
quint8z AntChannelIdMessage::deviceType () const
Returns the AntChannelIdMessage data message's deviceType field's current value.
Returns
the deviceType field value.
Definition at line 85 of file antchannelidmessage.cpp.
 {
     Q_D(const AntChannelIdMessage);
     return d->deviceType;
 }
Referenced by setDeviceType().
setChannelNumber()
void AntChannelIdMessage::setChannelNumber (const quint8 channelNumber)
Sets the channelNumber field to channelNumber.
Parameters
channelNumber The field value to set.
Definition at line 129 of file antchannelidmessage.cpp.
 {
     Q_D(AntChannelIdMessage);
     d->channelNumber = channelNumber;
 }
References channelNumber().
setDeviceIndex()
void AntChannelIdMessage::setDeviceIndex (const DeviceIndex deviceIndex)
Sets the deviceIndex field to deviceIndex.
Parameters
deviceIndex The field value to set.
Definition at line 169 of file antchannelidmessage.cpp.
 {
     Q_D(AntChannelIdMessage);
     d->deviceIndex = deviceIndex;
 }
References deviceIndex().
setDeviceNumber()
void AntChannelIdMessage::setDeviceNumber (const quint16z deviceNumber)
Sets the deviceNumber field to deviceNumber.
Parameters
deviceNumber The field value to set.
Definition at line 149 of file antchannelidmessage.cpp.
 {
     Q_D(AntChannelIdMessage);
     d->deviceNumber = deviceNumber;
 }
References deviceNumber().
setDeviceType()
void AntChannelIdMessage::setDeviceType (const quint8z deviceType)
Sets the deviceType field to deviceType.
Parameters
deviceType The field value to set.
Definition at line 139 of file antchannelidmessage.cpp.
 {
     Q_D(AntChannelIdMessage);
     d->deviceType = deviceType;
 }
References deviceType().
setTransmissionType()
void AntChannelIdMessage::setTransmissionType (const quint8z transmissionType)
Sets the transmissionType field to transmissionType.
Parameters
transmissionType The field value to set.
Definition at line 159 of file antchannelidmessage.cpp.
 {
     Q_D(AntChannelIdMessage);
     d->transmissionType = transmissionType;
 }
References transmissionType().
transmissionType()
quint8z AntChannelIdMessage::transmissionType () const
Returns the AntChannelIdMessage data message's transmissionType field's current value.
Returns
the transmissionType field value.
Definition at line 107 of file antchannelidmessage.cpp.
 {
     Q_D(const AntChannelIdMessage);
     return d->transmissionType;
 }
Referenced by setTransmissionType().
The documentation for this class was generated from the following files:
antchannelidmessage.h
antchannelidmessage.cpp