QtFit: AccelerometerDataMessage Class Reference
AccelerometerDataMessage Class Reference
The AccelerometerDataMessage class represents a FIT AccelerometerDataMessage data message.
Public Member Functions
AccelerometerDataMessage ()
Constructs a AccelerometerDataMessage object.
DateTime timestamp () const
Returns the AccelerometerDataMessage data message's timestamp field's current value.
quint16 timestampMs () const
Returns the AccelerometerDataMessage data message's timestampMs field's current value.
quint16 sampleTimeOffset () const
Returns the AccelerometerDataMessage data message's sampleTimeOffset field's current value.
quint16 accelX () const
Returns the AccelerometerDataMessage data message's accelX field's current value.
quint16 accelY () const
Returns the AccelerometerDataMessage data message's accelY field's current value.
quint16 accelZ () const
Returns the AccelerometerDataMessage data message's accelZ field's current value.
float calibratedAccelX () const
Returns the AccelerometerDataMessage data message's calibratedAccelX field's current value.
float calibratedAccelY () const
Returns the AccelerometerDataMessage data message's calibratedAccelY field's current value.
float calibratedAccelZ () const
Returns the AccelerometerDataMessage data message's calibratedAccelZ field's current value.
qint16 compressedCalibratedAccelX () const
Returns the AccelerometerDataMessage data message's compressedCalibratedAccelX field's current value.
qint16 compressedCalibratedAccelY () const
Returns the AccelerometerDataMessage data message's compressedCalibratedAccelY field's current value.
qint16 compressedCalibratedAccelZ () const
Returns the AccelerometerDataMessage data message's compressedCalibratedAccelZ field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
void setSampleTimeOffset (const quint16 sampleTimeOffset)
Sets the sampleTimeOffset field to sampleTimeOffset.
void setAccelX (const quint16 accelX)
Sets the accelX field to accelX.
void setAccelY (const quint16 accelY)
Sets the accelY field to accelY.
void setAccelZ (const quint16 accelZ)
Sets the accelZ field to accelZ.
void setCalibratedAccelX (const float calibratedAccelX)
Sets the calibratedAccelX field to calibratedAccelX.
void setCalibratedAccelY (const float calibratedAccelY)
Sets the calibratedAccelY field to calibratedAccelY.
void setCalibratedAccelZ (const float calibratedAccelZ)
Sets the calibratedAccelZ field to calibratedAccelZ.
void setCompressedCalibratedAccelX (const qint16 compressedCalibratedAccelX)
Sets the compressedCalibratedAccelX field to compressedCalibratedAccelX.
void setCompressedCalibratedAccelY (const qint16 compressedCalibratedAccelY)
Sets the compressedCalibratedAccelY field to compressedCalibratedAccelY.
void setCompressedCalibratedAccelZ (const qint16 compressedCalibratedAccelZ)
Sets the compressedCalibratedAccelZ field to compressedCalibratedAccelZ.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
AccelerometerDataMessage (AccelerometerDataMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The AccelerometerDataMessage class represents a FIT AccelerometerDataMessage data message.
See also
DataMessage
Definition at line 34 of file accelerometerdatamessage.h.
Constructor & Destructor Documentation
AccelerometerDataMessage() [1/2]
AccelerometerDataMessage::AccelerometerDataMessage ()
Constructs a AccelerometerDataMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file accelerometerdatamessage.cpp.
                                                    : AbstractDataMessage(new AccelerometerDataMessagePrivate(this))
 {
 }
AccelerometerDataMessage() [2/2]
AccelerometerDataMessage::AccelerometerDataMessage (AccelerometerDataMessagePrivate *const d) explicit protected
Constructs a AccelerometerDataMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file accelerometerdatamessage.cpp.
                                                                                             : AbstractDataMessage(d)
 {
 }
Member Function Documentation
accelX()
quint16 AccelerometerDataMessage::accelX () const
Returns the AccelerometerDataMessage data message's accelX field's current value.
These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
Returns
the accelX field value.
Definition at line 114 of file accelerometerdatamessage.cpp.
 {
     Q_D(const AccelerometerDataMessage);
     return d->accelX;
 }
Referenced by setAccelX().
accelY()
quint16 AccelerometerDataMessage::accelY () const
Returns the AccelerometerDataMessage data message's accelY field's current value.
These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
Returns
the accelY field value.
Definition at line 128 of file accelerometerdatamessage.cpp.
 {
     Q_D(const AccelerometerDataMessage);
     return d->accelY;
 }
Referenced by setAccelY().
accelZ()
quint16 AccelerometerDataMessage::accelZ () const
Returns the AccelerometerDataMessage data message's accelZ field's current value.
These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
Returns
the accelZ field value.
Definition at line 142 of file accelerometerdatamessage.cpp.
 {
     Q_D(const AccelerometerDataMessage);
     return d->accelZ;
 }
Referenced by setAccelZ().
calibratedAccelX()
float AccelerometerDataMessage::calibratedAccelX () const
Returns the AccelerometerDataMessage data message's calibratedAccelX field's current value.
Calibrated accel reading
Returns
the calibratedAccelX field value.
Definition at line 155 of file accelerometerdatamessage.cpp.
 {
     Q_D(const AccelerometerDataMessage);
     return d->calibratedAccelX;
 }
Referenced by setCalibratedAccelX().
calibratedAccelY()
float AccelerometerDataMessage::calibratedAccelY () const
Returns the AccelerometerDataMessage data message's calibratedAccelY field's current value.
Calibrated accel reading
Returns
the calibratedAccelY field value.
Definition at line 168 of file accelerometerdatamessage.cpp.
 {
     Q_D(const AccelerometerDataMessage);
     return d->calibratedAccelY;
 }
Referenced by setCalibratedAccelY().
calibratedAccelZ()
float AccelerometerDataMessage::calibratedAccelZ () const
Returns the AccelerometerDataMessage data message's calibratedAccelZ field's current value.
Calibrated accel reading
Returns
the calibratedAccelZ field value.
Definition at line 181 of file accelerometerdatamessage.cpp.
 {
     Q_D(const AccelerometerDataMessage);
     return d->calibratedAccelZ;
 }
Referenced by setCalibratedAccelZ().
compressedCalibratedAccelX()
qint16 AccelerometerDataMessage::compressedCalibratedAccelX () const
Returns the AccelerometerDataMessage data message's compressedCalibratedAccelX field's current value.
Calibrated accel reading
Returns
the compressedCalibratedAccelX field value.
Definition at line 194 of file accelerometerdatamessage.cpp.
 {
     Q_D(const AccelerometerDataMessage);
     return d->compressedCalibratedAccelX;
 }
Referenced by setCompressedCalibratedAccelX().
compressedCalibratedAccelY()
qint16 AccelerometerDataMessage::compressedCalibratedAccelY () const
Returns the AccelerometerDataMessage data message's compressedCalibratedAccelY field's current value.
Calibrated accel reading
Returns
the compressedCalibratedAccelY field value.
Definition at line 207 of file accelerometerdatamessage.cpp.
 {
     Q_D(const AccelerometerDataMessage);
     return d->compressedCalibratedAccelY;
 }
Referenced by setCompressedCalibratedAccelY().
compressedCalibratedAccelZ()
qint16 AccelerometerDataMessage::compressedCalibratedAccelZ () const
Returns the AccelerometerDataMessage data message's compressedCalibratedAccelZ field's current value.
Calibrated accel reading
Returns
the compressedCalibratedAccelZ field value.
Definition at line 220 of file accelerometerdatamessage.cpp.
 {
     Q_D(const AccelerometerDataMessage);
     return d->compressedCalibratedAccelZ;
 }
Referenced by setCompressedCalibratedAccelZ().
sampleTimeOffset()
quint16 AccelerometerDataMessage::sampleTimeOffset () const
Returns the AccelerometerDataMessage data message's sampleTimeOffset field's current value.
Each time in the array describes the time at which the accelerometer sample with the corrosponding index was taken. Limited to 30 samples in each message. The samples may span across seconds. Array size must match the number of samples in accel_x and accel_y and accel_z
Returns
the sampleTimeOffset field value.
Definition at line 100 of file accelerometerdatamessage.cpp.
 {
     Q_D(const AccelerometerDataMessage);
     return d->sampleTimeOffset;
 }
Referenced by setSampleTimeOffset().
setAccelX()
void AccelerometerDataMessage::setAccelX (const quint16 accelX)
Sets the accelX field to accelX.
Parameters
accelX The field value to set.
Definition at line 261 of file accelerometerdatamessage.cpp.
 {
     Q_D(AccelerometerDataMessage);
     d->accelX = accelX;
 }
References accelX().
setAccelY()
void AccelerometerDataMessage::setAccelY (const quint16 accelY)
Sets the accelY field to accelY.
Parameters
accelY The field value to set.
Definition at line 271 of file accelerometerdatamessage.cpp.
 {
     Q_D(AccelerometerDataMessage);
     d->accelY = accelY;
 }
References accelY().
setAccelZ()
void AccelerometerDataMessage::setAccelZ (const quint16 accelZ)
Sets the accelZ field to accelZ.
Parameters
accelZ The field value to set.
Definition at line 281 of file accelerometerdatamessage.cpp.
 {
     Q_D(AccelerometerDataMessage);
     d->accelZ = accelZ;
 }
References accelZ().
setCalibratedAccelX()
void AccelerometerDataMessage::setCalibratedAccelX (const float calibratedAccelX)
Sets the calibratedAccelX field to calibratedAccelX.
Parameters
calibratedAccelX The field value to set.
Definition at line 291 of file accelerometerdatamessage.cpp.
 {
     Q_D(AccelerometerDataMessage);
     d->calibratedAccelX = calibratedAccelX;
 }
References calibratedAccelX().
setCalibratedAccelY()
void AccelerometerDataMessage::setCalibratedAccelY (const float calibratedAccelY)
Sets the calibratedAccelY field to calibratedAccelY.
Parameters
calibratedAccelY The field value to set.
Definition at line 301 of file accelerometerdatamessage.cpp.
 {
     Q_D(AccelerometerDataMessage);
     d->calibratedAccelY = calibratedAccelY;
 }
References calibratedAccelY().
setCalibratedAccelZ()
void AccelerometerDataMessage::setCalibratedAccelZ (const float calibratedAccelZ)
Sets the calibratedAccelZ field to calibratedAccelZ.
Parameters
calibratedAccelZ The field value to set.
Definition at line 311 of file accelerometerdatamessage.cpp.
 {
     Q_D(AccelerometerDataMessage);
     d->calibratedAccelZ = calibratedAccelZ;
 }
References calibratedAccelZ().
setCompressedCalibratedAccelX()
void AccelerometerDataMessage::setCompressedCalibratedAccelX (const qint16 compressedCalibratedAccelX)
Sets the compressedCalibratedAccelX field to compressedCalibratedAccelX.
Parameters
compressedCalibratedAccelX The field value to set.
Definition at line 321 of file accelerometerdatamessage.cpp.
 {
     Q_D(AccelerometerDataMessage);
     d->compressedCalibratedAccelX = compressedCalibratedAccelX;
 }
References compressedCalibratedAccelX().
setCompressedCalibratedAccelY()
void AccelerometerDataMessage::setCompressedCalibratedAccelY (const qint16 compressedCalibratedAccelY)
Sets the compressedCalibratedAccelY field to compressedCalibratedAccelY.
Parameters
compressedCalibratedAccelY The field value to set.
Definition at line 331 of file accelerometerdatamessage.cpp.
 {
     Q_D(AccelerometerDataMessage);
     d->compressedCalibratedAccelY = compressedCalibratedAccelY;
 }
References compressedCalibratedAccelY().
setCompressedCalibratedAccelZ()
void AccelerometerDataMessage::setCompressedCalibratedAccelZ (const qint16 compressedCalibratedAccelZ)
Sets the compressedCalibratedAccelZ field to compressedCalibratedAccelZ.
Parameters
compressedCalibratedAccelZ The field value to set.
Definition at line 341 of file accelerometerdatamessage.cpp.
 {
     Q_D(AccelerometerDataMessage);
     d->compressedCalibratedAccelZ = compressedCalibratedAccelZ;
 }
References compressedCalibratedAccelZ().
setSampleTimeOffset()
void AccelerometerDataMessage::setSampleTimeOffset (const quint16 sampleTimeOffset)
Sets the sampleTimeOffset field to sampleTimeOffset.
Parameters
sampleTimeOffset The field value to set.
Definition at line 251 of file accelerometerdatamessage.cpp.
 {
     Q_D(AccelerometerDataMessage);
     d->sampleTimeOffset = sampleTimeOffset;
 }
References sampleTimeOffset().
setTimestamp()
void AccelerometerDataMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 231 of file accelerometerdatamessage.cpp.
 {
     Q_D(AccelerometerDataMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setTimestampMs()
void AccelerometerDataMessage::setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
Parameters
timestampMs The field value to set.
Definition at line 241 of file accelerometerdatamessage.cpp.
 {
     Q_D(AccelerometerDataMessage);
     d->timestampMs = timestampMs;
 }
References timestampMs().
timestamp()
DateTime AccelerometerDataMessage::timestamp () const
Returns the AccelerometerDataMessage data message's timestamp field's current value.
Whole second part of the timestamp
Returns
the timestamp field value.
Definition at line 71 of file accelerometerdatamessage.cpp.
 {
     Q_D(const AccelerometerDataMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
timestampMs()
quint16 AccelerometerDataMessage::timestampMs () const
Returns the AccelerometerDataMessage data message's timestampMs field's current value.
Millisecond part of the timestamp.
Returns
the timestampMs field value.
Definition at line 84 of file accelerometerdatamessage.cpp.
 {
     Q_D(const AccelerometerDataMessage);
     return d->timestampMs;
 }
Referenced by setTimestampMs().
The documentation for this class was generated from the following files:
accelerometerdatamessage.h
accelerometerdatamessage.cpp