QtFit: FileCreatorMessage Class Reference
FileCreatorMessage Class Reference
The FileCreatorMessage class represents a FIT FileCreatorMessage data message.
Public Member Functions
FileCreatorMessage ()
Constructs a FileCreatorMessage object.
quint16 softwareVersion () const
Returns the FileCreatorMessage data message's softwareVersion field's current value.
quint8 hardwareVersion () const
Returns the FileCreatorMessage data message's hardwareVersion field's current value.
void setSoftwareVersion (const quint16 softwareVersion)
Sets the softwareVersion field to softwareVersion.
void setHardwareVersion (const quint8 hardwareVersion)
Sets the hardwareVersion field to hardwareVersion.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
FileCreatorMessage (FileCreatorMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The FileCreatorMessage class represents a FIT FileCreatorMessage data message.
See also
DataMessage
Definition at line 39 of file filecreatormessage.h.
Constructor & Destructor Documentation
FileCreatorMessage() [1/2]
FileCreatorMessage::FileCreatorMessage ()
Constructs a FileCreatorMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file filecreatormessage.cpp.
                                        : AbstractDataMessage(new FileCreatorMessagePrivate(this))
 {
 }
FileCreatorMessage() [2/2]
FileCreatorMessage::FileCreatorMessage (FileCreatorMessagePrivate *const d) explicit protected
Constructs a FileCreatorMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file filecreatormessage.cpp.
                                                                           : AbstractDataMessage(d)
 {
 }
Member Function Documentation
hardwareVersion()
quint8 FileCreatorMessage::hardwareVersion () const
Returns the FileCreatorMessage data message's hardwareVersion field's current value.
Returns
the hardwareVersion field value.
Definition at line 85 of file filecreatormessage.cpp.
 {
     Q_D(const FileCreatorMessage);
     return d->hardwareVersion;
 }
Referenced by setHardwareVersion().
setHardwareVersion()
void FileCreatorMessage::setHardwareVersion (const quint8 hardwareVersion)
Sets the hardwareVersion field to hardwareVersion.
Parameters
hardwareVersion The field value to set.
Definition at line 106 of file filecreatormessage.cpp.
 {
     Q_D(FileCreatorMessage);
     d->hardwareVersion = hardwareVersion;
 }
References hardwareVersion().
setSoftwareVersion()
void FileCreatorMessage::setSoftwareVersion (const quint16 softwareVersion)
Sets the softwareVersion field to softwareVersion.
Parameters
softwareVersion The field value to set.
Definition at line 96 of file filecreatormessage.cpp.
 {
     Q_D(FileCreatorMessage);
     d->softwareVersion = softwareVersion;
 }
References softwareVersion().
softwareVersion()
quint16 FileCreatorMessage::softwareVersion () const
Returns the FileCreatorMessage data message's softwareVersion field's current value.
Returns
the softwareVersion field value.
Definition at line 74 of file filecreatormessage.cpp.
 {
     Q_D(const FileCreatorMessage);
     return d->softwareVersion;
 }
Referenced by setSoftwareVersion().
The documentation for this class was generated from the following files:
filecreatormessage.h
filecreatormessage.cpp