QtFit: MagnetometerDataMessage Class Reference
MagnetometerDataMessage Class Reference
The MagnetometerDataMessage class represents a FIT MagnetometerDataMessage data message.
Public Member Functions
MagnetometerDataMessage ()
Constructs a MagnetometerDataMessage object.
DateTime timestamp () const
Returns the MagnetometerDataMessage data message's timestamp field's current value.
quint16 timestampMs () const
Returns the MagnetometerDataMessage data message's timestampMs field's current value.
quint16 sampleTimeOffset () const
Returns the MagnetometerDataMessage data message's sampleTimeOffset field's current value.
quint16 magX () const
Returns the MagnetometerDataMessage data message's magX field's current value.
quint16 magY () const
Returns the MagnetometerDataMessage data message's magY field's current value.
quint16 magZ () const
Returns the MagnetometerDataMessage data message's magZ field's current value.
float calibratedMagX () const
Returns the MagnetometerDataMessage data message's calibratedMagX field's current value.
float calibratedMagY () const
Returns the MagnetometerDataMessage data message's calibratedMagY field's current value.
float calibratedMagZ () const
Returns the MagnetometerDataMessage data message's calibratedMagZ field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
void setSampleTimeOffset (const quint16 sampleTimeOffset)
Sets the sampleTimeOffset field to sampleTimeOffset.
void setMagX (const quint16 magX)
Sets the magX field to magX.
void setMagY (const quint16 magY)
Sets the magY field to magY.
void setMagZ (const quint16 magZ)
Sets the magZ field to magZ.
void setCalibratedMagX (const float calibratedMagX)
Sets the calibratedMagX field to calibratedMagX.
void setCalibratedMagY (const float calibratedMagY)
Sets the calibratedMagY field to calibratedMagY.
void setCalibratedMagZ (const float calibratedMagZ)
Sets the calibratedMagZ field to calibratedMagZ.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
MagnetometerDataMessage (MagnetometerDataMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The MagnetometerDataMessage class represents a FIT MagnetometerDataMessage data message.
See also
DataMessage
Definition at line 39 of file magnetometerdatamessage.h.
Constructor & Destructor Documentation
MagnetometerDataMessage() [1/2]
MagnetometerDataMessage::MagnetometerDataMessage ()
Constructs a MagnetometerDataMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file magnetometerdatamessage.cpp.
                                                  : AbstractDataMessage(new MagnetometerDataMessagePrivate(this))
 {
 }
MagnetometerDataMessage() [2/2]
MagnetometerDataMessage::MagnetometerDataMessage (MagnetometerDataMessagePrivate *const d) explicit protected
Constructs a MagnetometerDataMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file magnetometerdatamessage.cpp.
                                                                                          : AbstractDataMessage(d)
 {
 }
Member Function Documentation
calibratedMagX()
float MagnetometerDataMessage::calibratedMagX () const
Returns the MagnetometerDataMessage data message's calibratedMagX field's current value.
Calibrated Magnetometer reading
Returns
the calibratedMagX field value.
Definition at line 159 of file magnetometerdatamessage.cpp.
 {
     Q_D(const MagnetometerDataMessage);
     return d->calibratedMagX;
 }
Referenced by setCalibratedMagX().
calibratedMagY()
float MagnetometerDataMessage::calibratedMagY () const
Returns the MagnetometerDataMessage data message's calibratedMagY field's current value.
Calibrated Magnetometer reading
Returns
the calibratedMagY field value.
Definition at line 172 of file magnetometerdatamessage.cpp.
 {
     Q_D(const MagnetometerDataMessage);
     return d->calibratedMagY;
 }
Referenced by setCalibratedMagY().
calibratedMagZ()
float MagnetometerDataMessage::calibratedMagZ () const
Returns the MagnetometerDataMessage data message's calibratedMagZ field's current value.
Calibrated Magnetometer reading
Returns
the calibratedMagZ field value.
Definition at line 185 of file magnetometerdatamessage.cpp.
 {
     Q_D(const MagnetometerDataMessage);
     return d->calibratedMagZ;
 }
Referenced by setCalibratedMagZ().
magX()
quint16 MagnetometerDataMessage::magX () const
Returns the MagnetometerDataMessage data message's magX field's current value.
These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
Returns
the magX field value.
Definition at line 118 of file magnetometerdatamessage.cpp.
 {
     Q_D(const MagnetometerDataMessage);
     return d->magX;
 }
Referenced by setMagX().
magY()
quint16 MagnetometerDataMessage::magY () const
Returns the MagnetometerDataMessage data message's magY field's current value.
These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
Returns
the magY field value.
Definition at line 132 of file magnetometerdatamessage.cpp.
 {
     Q_D(const MagnetometerDataMessage);
     return d->magY;
 }
Referenced by setMagY().
magZ()
quint16 MagnetometerDataMessage::magZ () const
Returns the MagnetometerDataMessage data message's magZ field's current value.
These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
Returns
the magZ field value.
Definition at line 146 of file magnetometerdatamessage.cpp.
 {
     Q_D(const MagnetometerDataMessage);
     return d->magZ;
 }
Referenced by setMagZ().
sampleTimeOffset()
quint16 MagnetometerDataMessage::sampleTimeOffset () const
Returns the MagnetometerDataMessage data message's sampleTimeOffset field's current value.
Each time in the array describes the time at which the compass sample with the corrosponding index was taken. Limited to 30 samples in each message. The samples may span across seconds. Array size must match the number of samples in cmps_x and cmps_y and cmps_z
Returns
the sampleTimeOffset field value.
Definition at line 104 of file magnetometerdatamessage.cpp.
 {
     Q_D(const MagnetometerDataMessage);
     return d->sampleTimeOffset;
 }
Referenced by setSampleTimeOffset().
setCalibratedMagX()
void MagnetometerDataMessage::setCalibratedMagX (const float calibratedMagX)
Sets the calibratedMagX field to calibratedMagX.
Parameters
calibratedMagX The field value to set.
Definition at line 256 of file magnetometerdatamessage.cpp.
 {
     Q_D(MagnetometerDataMessage);
     d->calibratedMagX = calibratedMagX;
 }
References calibratedMagX().
setCalibratedMagY()
void MagnetometerDataMessage::setCalibratedMagY (const float calibratedMagY)
Sets the calibratedMagY field to calibratedMagY.
Parameters
calibratedMagY The field value to set.
Definition at line 266 of file magnetometerdatamessage.cpp.
 {
     Q_D(MagnetometerDataMessage);
     d->calibratedMagY = calibratedMagY;
 }
References calibratedMagY().
setCalibratedMagZ()
void MagnetometerDataMessage::setCalibratedMagZ (const float calibratedMagZ)
Sets the calibratedMagZ field to calibratedMagZ.
Parameters
calibratedMagZ The field value to set.
Definition at line 276 of file magnetometerdatamessage.cpp.
 {
     Q_D(MagnetometerDataMessage);
     d->calibratedMagZ = calibratedMagZ;
 }
References calibratedMagZ().
setMagX()
void MagnetometerDataMessage::setMagX (const quint16 magX)
Sets the magX field to magX.
Parameters
magX The field value to set.
Definition at line 226 of file magnetometerdatamessage.cpp.
 {
     Q_D(MagnetometerDataMessage);
     d->magX = magX;
 }
References magX().
setMagY()
void MagnetometerDataMessage::setMagY (const quint16 magY)
Sets the magY field to magY.
Parameters
magY The field value to set.
Definition at line 236 of file magnetometerdatamessage.cpp.
 {
     Q_D(MagnetometerDataMessage);
     d->magY = magY;
 }
References magY().
setMagZ()
void MagnetometerDataMessage::setMagZ (const quint16 magZ)
Sets the magZ field to magZ.
Parameters
magZ The field value to set.
Definition at line 246 of file magnetometerdatamessage.cpp.
 {
     Q_D(MagnetometerDataMessage);
     d->magZ = magZ;
 }
References magZ().
setSampleTimeOffset()
void MagnetometerDataMessage::setSampleTimeOffset (const quint16 sampleTimeOffset)
Sets the sampleTimeOffset field to sampleTimeOffset.
Parameters
sampleTimeOffset The field value to set.
Definition at line 216 of file magnetometerdatamessage.cpp.
 {
     Q_D(MagnetometerDataMessage);
     d->sampleTimeOffset = sampleTimeOffset;
 }
References sampleTimeOffset().
setTimestamp()
void MagnetometerDataMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 196 of file magnetometerdatamessage.cpp.
 {
     Q_D(MagnetometerDataMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setTimestampMs()
void MagnetometerDataMessage::setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
Parameters
timestampMs The field value to set.
Definition at line 206 of file magnetometerdatamessage.cpp.
 {
     Q_D(MagnetometerDataMessage);
     d->timestampMs = timestampMs;
 }
References timestampMs().
timestamp()
DateTime MagnetometerDataMessage::timestamp () const
Returns the MagnetometerDataMessage data message's timestamp field's current value.
Whole second part of the timestamp
Returns
the timestamp field value.
Definition at line 76 of file magnetometerdatamessage.cpp.
 {
     Q_D(const MagnetometerDataMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
timestampMs()
quint16 MagnetometerDataMessage::timestampMs () const
Returns the MagnetometerDataMessage data message's timestampMs field's current value.
Millisecond part of the timestamp.
Returns
the timestampMs field value.
Definition at line 89 of file magnetometerdatamessage.cpp.
 {
     Q_D(const MagnetometerDataMessage);
     return d->timestampMs;
 }
Referenced by setTimestampMs().
The documentation for this class was generated from the following files:
magnetometerdatamessage.h
magnetometerdatamessage.cpp