QtFit: JumpMessage Class Reference
JumpMessage Class Reference
The JumpMessage class represents a FIT JumpMessage data message.
Public Member Functions
JumpMessage ()
Constructs a JumpMessage object.
DateTime timestamp () const
Returns the JumpMessage data message's timestamp field's current value.
float distance () const
Returns the JumpMessage data message's distance field's current value.
float height () const
Returns the JumpMessage data message's height field's current value.
quint8 rotations () const
Returns the JumpMessage data message's rotations field's current value.
float hangTime () const
Returns the JumpMessage data message's hangTime field's current value.
float score () const
Returns the JumpMessage data message's score field's current value.
qint32 positionLat () const
Returns the JumpMessage data message's positionLat field's current value.
qint32 positionLong () const
Returns the JumpMessage data message's positionLong field's current value.
quint16 speed () const
Returns the JumpMessage data message's speed field's current value.
quint32 enhancedSpeed () const
Returns the JumpMessage data message's enhancedSpeed field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setDistance (const float distance)
Sets the distance field to distance.
void setHeight (const float height)
Sets the height field to height.
void setRotations (const quint8 rotations)
Sets the rotations field to rotations.
void setHangTime (const float hangTime)
Sets the hangTime field to hangTime.
void setScore (const float score)
Sets the score field to score.
void setPositionLat (const qint32 positionLat)
Sets the positionLat field to positionLat.
void setPositionLong (const qint32 positionLong)
Sets the positionLong field to positionLong.
void setSpeed (const quint16 speed)
Sets the speed field to speed.
void setEnhancedSpeed (const quint32 enhancedSpeed)
Sets the enhancedSpeed field to enhancedSpeed.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
JumpMessage (JumpMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The JumpMessage class represents a FIT JumpMessage data message.
See also
DataMessage
Definition at line 34 of file jumpmessage.h.
Constructor & Destructor Documentation
JumpMessage() [1/2]
JumpMessage::JumpMessage ()
Constructs a JumpMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file jumpmessage.cpp.
                          : AbstractDataMessage(new JumpMessagePrivate(this))
 {
 }
JumpMessage() [2/2]
JumpMessage::JumpMessage (JumpMessagePrivate *const d) explicit protected
Constructs a JumpMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file jumpmessage.cpp.
                                                      : AbstractDataMessage(d)
 {
 }
Member Function Documentation
distance()
float JumpMessage::distance () const
Returns the JumpMessage data message's distance field's current value.
Returns
the distance field value.
Definition at line 80 of file jumpmessage.cpp.
 {
     Q_D(const JumpMessage);
     return d->distance;
 }
Referenced by setDistance().
enhancedSpeed()
quint32 JumpMessage::enhancedSpeed () const
Returns the JumpMessage data message's enhancedSpeed field's current value.
Returns
the enhancedSpeed field value.
Definition at line 170 of file jumpmessage.cpp.
 {
     Q_D(const JumpMessage);
     return d->enhancedSpeed;
 }
Referenced by setEnhancedSpeed().
hangTime()
float JumpMessage::hangTime () const
Returns the JumpMessage data message's hangTime field's current value.
Returns
the hangTime field value.
Definition at line 113 of file jumpmessage.cpp.
 {
     Q_D(const JumpMessage);
     return d->hangTime;
 }
Referenced by setHangTime().
height()
float JumpMessage::height () const
Returns the JumpMessage data message's height field's current value.
Returns
the height field value.
Definition at line 91 of file jumpmessage.cpp.
 {
     Q_D(const JumpMessage);
     return d->height;
 }
Referenced by setHeight().
positionLat()
qint32 JumpMessage::positionLat () const
Returns the JumpMessage data message's positionLat field's current value.
Returns
the positionLat field value.
Definition at line 137 of file jumpmessage.cpp.
 {
     Q_D(const JumpMessage);
     return d->positionLat;
 }
Referenced by setPositionLat().
positionLong()
qint32 JumpMessage::positionLong () const
Returns the JumpMessage data message's positionLong field's current value.
Returns
the positionLong field value.
Definition at line 148 of file jumpmessage.cpp.
 {
     Q_D(const JumpMessage);
     return d->positionLong;
 }
Referenced by setPositionLong().
rotations()
quint8 JumpMessage::rotations () const
Returns the JumpMessage data message's rotations field's current value.
Returns
the rotations field value.
Definition at line 102 of file jumpmessage.cpp.
 {
     Q_D(const JumpMessage);
     return d->rotations;
 }
Referenced by setRotations().
score()
float JumpMessage::score () const
Returns the JumpMessage data message's score field's current value.
A score for a jump calculated based on hang time, rotations, and distance.
Returns
the score field value.
Definition at line 126 of file jumpmessage.cpp.
 {
     Q_D(const JumpMessage);
     return d->score;
 }
Referenced by setScore().
setDistance()
void JumpMessage::setDistance (const float distance)
Sets the distance field to distance.
Parameters
distance The field value to set.
Definition at line 191 of file jumpmessage.cpp.
 {
     Q_D(JumpMessage);
     d->distance = distance;
 }
References distance().
setEnhancedSpeed()
void JumpMessage::setEnhancedSpeed (const quint32 enhancedSpeed)
Sets the enhancedSpeed field to enhancedSpeed.
Parameters
enhancedSpeed The field value to set.
Definition at line 271 of file jumpmessage.cpp.
 {
     Q_D(JumpMessage);
     d->enhancedSpeed = enhancedSpeed;
 }
References enhancedSpeed().
setHangTime()
void JumpMessage::setHangTime (const float hangTime)
Sets the hangTime field to hangTime.
Parameters
hangTime The field value to set.
Definition at line 221 of file jumpmessage.cpp.
 {
     Q_D(JumpMessage);
     d->hangTime = hangTime;
 }
References hangTime().
setHeight()
void JumpMessage::setHeight (const float height)
Sets the height field to height.
Parameters
height The field value to set.
Definition at line 201 of file jumpmessage.cpp.
 {
     Q_D(JumpMessage);
     d->height = height;
 }
References height().
setPositionLat()
void JumpMessage::setPositionLat (const qint32 positionLat)
Sets the positionLat field to positionLat.
Parameters
positionLat The field value to set.
Definition at line 241 of file jumpmessage.cpp.
 {
     Q_D(JumpMessage);
     d->positionLat = positionLat;
 }
References positionLat().
setPositionLong()
void JumpMessage::setPositionLong (const qint32 positionLong)
Sets the positionLong field to positionLong.
Parameters
positionLong The field value to set.
Definition at line 251 of file jumpmessage.cpp.
 {
     Q_D(JumpMessage);
     d->positionLong = positionLong;
 }
References positionLong().
setRotations()
void JumpMessage::setRotations (const quint8 rotations)
Sets the rotations field to rotations.
Parameters
rotations The field value to set.
Definition at line 211 of file jumpmessage.cpp.
 {
     Q_D(JumpMessage);
     d->rotations = rotations;
 }
References rotations().
setScore()
void JumpMessage::setScore (const float score)
Sets the score field to score.
Parameters
score The field value to set.
Definition at line 231 of file jumpmessage.cpp.
 {
     Q_D(JumpMessage);
     d->score = score;
 }
References score().
setSpeed()
void JumpMessage::setSpeed (const quint16 speed)
Sets the speed field to speed.
Parameters
speed The field value to set.
Definition at line 261 of file jumpmessage.cpp.
 {
     Q_D(JumpMessage);
     d->speed = speed;
 }
References speed().
setTimestamp()
void JumpMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 181 of file jumpmessage.cpp.
 {
     Q_D(JumpMessage);
     d->timestamp = timestamp;
 }
References timestamp().
speed()
quint16 JumpMessage::speed () const
Returns the JumpMessage data message's speed field's current value.
Returns
the speed field value.
Definition at line 159 of file jumpmessage.cpp.
 {
     Q_D(const JumpMessage);
     return d->speed;
 }
Referenced by setSpeed().
timestamp()
DateTime JumpMessage::timestamp () const
Returns the JumpMessage data message's timestamp field's current value.
Returns
the timestamp field value.
Definition at line 69 of file jumpmessage.cpp.
 {
     Q_D(const JumpMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
The documentation for this class was generated from the following files:
jumpmessage.h
jumpmessage.cpp