QtFit: FileCapabilitiesMessage Class Reference
FileCapabilitiesMessage Class Reference
The FileCapabilitiesMessage class represents a FIT FileCapabilitiesMessage data message.
Public Member Functions
FileCapabilitiesMessage ()
Constructs a FileCapabilitiesMessage object.
MessageIndex messageIndex () const
Returns the FileCapabilitiesMessage data message's messageIndex field's current value.
File type () const
Returns the FileCapabilitiesMessage data message's type field's current value.
FileFlags flags () const
Returns the FileCapabilitiesMessage data message's flags field's current value.
QString directory () const
Returns the FileCapabilitiesMessage data message's directory field's current value.
quint16 maxCount () const
Returns the FileCapabilitiesMessage data message's maxCount field's current value.
quint32 maxSize () const
Returns the FileCapabilitiesMessage data message's maxSize field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setType (const File type)
Sets the type field to type.
void setFlags (const FileFlags flags)
Sets the flags field to flags.
void setDirectory (const QString directory)
Sets the directory field to directory.
void setMaxCount (const quint16 maxCount)
Sets the maxCount field to maxCount.
void setMaxSize (const quint32 maxSize)
Sets the maxSize field to maxSize.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
FileCapabilitiesMessage (FileCapabilitiesMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The FileCapabilitiesMessage class represents a FIT FileCapabilitiesMessage data message.
See also
DataMessage
Definition at line 34 of file filecapabilitiesmessage.h.
Constructor & Destructor Documentation
FileCapabilitiesMessage() [1/2]
FileCapabilitiesMessage::FileCapabilitiesMessage ()
Constructs a FileCapabilitiesMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file filecapabilitiesmessage.cpp.
                                                  : AbstractDataMessage(new FileCapabilitiesMessagePrivate(this))
 {
 }
FileCapabilitiesMessage() [2/2]
FileCapabilitiesMessage::FileCapabilitiesMessage (FileCapabilitiesMessagePrivate *const d) explicit protected
Constructs a FileCapabilitiesMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file filecapabilitiesmessage.cpp.
                                                                                          : AbstractDataMessage(d)
 {
 }
Member Function Documentation
directory()
QString FileCapabilitiesMessage::directory () const
Returns the FileCapabilitiesMessage data message's directory field's current value.
Returns
the directory field value.
Definition at line 102 of file filecapabilitiesmessage.cpp.
 {
     Q_D(const FileCapabilitiesMessage);
     return d->directory;
 }
Referenced by setDirectory().
flags()
FileFlags FileCapabilitiesMessage::flags () const
Returns the FileCapabilitiesMessage data message's flags field's current value.
Returns
the flags field value.
Definition at line 91 of file filecapabilitiesmessage.cpp.
 {
     Q_D(const FileCapabilitiesMessage);
     return d->flags;
 }
Referenced by setFlags().
maxCount()
quint16 FileCapabilitiesMessage::maxCount () const
Returns the FileCapabilitiesMessage data message's maxCount field's current value.
Returns
the maxCount field value.
Definition at line 113 of file filecapabilitiesmessage.cpp.
 {
     Q_D(const FileCapabilitiesMessage);
     return d->maxCount;
 }
Referenced by setMaxCount().
maxSize()
quint32 FileCapabilitiesMessage::maxSize () const
Returns the FileCapabilitiesMessage data message's maxSize field's current value.
Returns
the maxSize field value.
Definition at line 124 of file filecapabilitiesmessage.cpp.
 {
     Q_D(const FileCapabilitiesMessage);
     return d->maxSize;
 }
Referenced by setMaxSize().
messageIndex()
MessageIndex FileCapabilitiesMessage::messageIndex () const
Returns the FileCapabilitiesMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 69 of file filecapabilitiesmessage.cpp.
 {
     Q_D(const FileCapabilitiesMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
setDirectory()
void FileCapabilitiesMessage::setDirectory (const QString directory)
Sets the directory field to directory.
Parameters
directory The field value to set.
Definition at line 165 of file filecapabilitiesmessage.cpp.
 {
     Q_D(FileCapabilitiesMessage);
     d->directory = directory;
 }
References directory().
setFlags()
void FileCapabilitiesMessage::setFlags (const FileFlags flags)
Sets the flags field to flags.
Parameters
flags The field value to set.
Definition at line 155 of file filecapabilitiesmessage.cpp.
 {
     Q_D(FileCapabilitiesMessage);
     d->flags = flags;
 }
References flags().
setMaxCount()
void FileCapabilitiesMessage::setMaxCount (const quint16 maxCount)
Sets the maxCount field to maxCount.
Parameters
maxCount The field value to set.
Definition at line 175 of file filecapabilitiesmessage.cpp.
 {
     Q_D(FileCapabilitiesMessage);
     d->maxCount = maxCount;
 }
References maxCount().
setMaxSize()
void FileCapabilitiesMessage::setMaxSize (const quint32 maxSize)
Sets the maxSize field to maxSize.
Parameters
maxSize The field value to set.
Definition at line 185 of file filecapabilitiesmessage.cpp.
 {
     Q_D(FileCapabilitiesMessage);
     d->maxSize = maxSize;
 }
References maxSize().
setMessageIndex()
void FileCapabilitiesMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 135 of file filecapabilitiesmessage.cpp.
 {
     Q_D(FileCapabilitiesMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setType()
void FileCapabilitiesMessage::setType (const File type)
Sets the type field to type.
Parameters
type The field value to set.
Definition at line 145 of file filecapabilitiesmessage.cpp.
 {
     Q_D(FileCapabilitiesMessage);
     d->type = type;
 }
References type().
type()
File FileCapabilitiesMessage::type () const
Returns the FileCapabilitiesMessage data message's type field's current value.
Returns
the type field value.
Definition at line 80 of file filecapabilitiesmessage.cpp.
 {
     Q_D(const FileCapabilitiesMessage);
     return d->type;
 }
Referenced by setType().
The documentation for this class was generated from the following files:
filecapabilitiesmessage.h
filecapabilitiesmessage.cpp