QtFit: WorkoutSessionMessage Class Reference
WorkoutSessionMessage Class Reference
#include <workoutsessionmessage.h>
Public Member Functions
WorkoutSessionMessage ()
~WorkoutSessionMessage ()
MessageIndex messageIndex () const
Sport sport () const
SubSport subSport () const
quint16 numValidSteps () const
quint16 firstStepIndex () const
quint16 poolLength () const
DisplayMeasure poolLengthUnit () const
void setMessageIndex (const MessageIndex messageIndex)
void setSport (const Sport sport)
void setSubSport (const SubSport subSport)
void setNumValidSteps (const quint16 numValidSteps)
void setFirstStepIndex (const quint16 firstStepIndex)
void setPoolLength (const quint16 poolLength)
void setPoolLengthUnit (const DisplayMeasure poolLengthUnit)
Public Member Functions inherited from FitDataMessage
FitDataMessage ()
FitDataMessage (const FitDataMessage &other)
FitDataMessage & operator= (const FitDataMessage &other)
~FitDataMessage ()
MesgNum globalMessageNumber () const
bool isNull () const
Additional Inherited Members
Static Public Member Functions inherited from FitDataMessage
static FitDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Detailed Description
Definition at line 34 of file workoutsessionmessage.h.
Constructor & Destructor Documentation
WorkoutSessionMessage()
QTFIT_BEGIN_NAMESPACE WorkoutSessionMessage::WorkoutSessionMessage ()
Definition at line 30 of file workoutsessionmessage.cpp.
                                              : FitDataMessage(new WorkoutSessionMessagePrivate(this))
 {
 }
~WorkoutSessionMessage()
WorkoutSessionMessage::~WorkoutSessionMessage ()
Member Function Documentation
firstStepIndex()
quint16 WorkoutSessionMessage::firstStepIndex () const
Definition at line 59 of file workoutsessionmessage.cpp.
 {
     Q_D(const WorkoutSessionMessage);
     return d->firstStepIndex;
 }
Referenced by setFirstStepIndex().
messageIndex()
MessageIndex WorkoutSessionMessage::messageIndex () const
Definition at line 35 of file workoutsessionmessage.cpp.
 {
     Q_D(const WorkoutSessionMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
numValidSteps()
quint16 WorkoutSessionMessage::numValidSteps () const
Definition at line 53 of file workoutsessionmessage.cpp.
 {
     Q_D(const WorkoutSessionMessage);
     return d->numValidSteps;
 }
Referenced by setNumValidSteps().
poolLength()
quint16 WorkoutSessionMessage::poolLength () const
Definition at line 65 of file workoutsessionmessage.cpp.
 {
     Q_D(const WorkoutSessionMessage);
     return d->poolLength;
 }
Referenced by setPoolLength().
poolLengthUnit()
DisplayMeasure WorkoutSessionMessage::poolLengthUnit () const
Definition at line 71 of file workoutsessionmessage.cpp.
 {
     Q_D(const WorkoutSessionMessage);
     return d->poolLengthUnit;
 }
Referenced by setPoolLengthUnit().
setFirstStepIndex()
void WorkoutSessionMessage::setFirstStepIndex (const quint16 firstStepIndex)
Definition at line 97 of file workoutsessionmessage.cpp.
 {
     Q_D(WorkoutSessionMessage);
     d->firstStepIndex = firstStepIndex;
 }
References firstStepIndex().
setMessageIndex()
void WorkoutSessionMessage::setMessageIndex (const MessageIndex messageIndex)
Definition at line 77 of file workoutsessionmessage.cpp.
 {
     Q_D(WorkoutSessionMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setNumValidSteps()
void WorkoutSessionMessage::setNumValidSteps (const quint16 numValidSteps)
Definition at line 92 of file workoutsessionmessage.cpp.
 {
     Q_D(WorkoutSessionMessage);
     d->numValidSteps = numValidSteps;
 }
References numValidSteps().
setPoolLength()
void WorkoutSessionMessage::setPoolLength (const quint16 poolLength)
Definition at line 102 of file workoutsessionmessage.cpp.
 {
     Q_D(WorkoutSessionMessage);
     d->poolLength = poolLength;
 }
References poolLength().
setPoolLengthUnit()
void WorkoutSessionMessage::setPoolLengthUnit (const DisplayMeasure poolLengthUnit)
Definition at line 107 of file workoutsessionmessage.cpp.
 {
     Q_D(WorkoutSessionMessage);
     d->poolLengthUnit = poolLengthUnit;
 }
References poolLengthUnit().
setSport()
void WorkoutSessionMessage::setSport (const Sport sport)
Definition at line 82 of file workoutsessionmessage.cpp.
 {
     Q_D(WorkoutSessionMessage);
     d->sport = sport;
 }
References sport().
setSubSport()
void WorkoutSessionMessage::setSubSport (const SubSport subSport)
Definition at line 87 of file workoutsessionmessage.cpp.
 {
     Q_D(WorkoutSessionMessage);
     d->subSport = subSport;
 }
References subSport().
sport()
Sport WorkoutSessionMessage::sport () const
Definition at line 41 of file workoutsessionmessage.cpp.
 {
     Q_D(const WorkoutSessionMessage);
     return d->sport;
 }
Referenced by setSport().
subSport()
SubSport WorkoutSessionMessage::subSport () const
Definition at line 47 of file workoutsessionmessage.cpp.
 {
     Q_D(const WorkoutSessionMessage);
     return d->subSport;
 }
Referenced by setSubSport().
The documentation for this class was generated from the following files:
workoutsessionmessage.h
workoutsessionmessage.cpp