QtFit: SportMessage Class Reference
SportMessage Class Reference
The SportMessage class represents a FIT SportMessage data message.
Public Member Functions
SportMessage ()
Constructs a SportMessage object.
Sport sport () const
Returns the SportMessage data message's sport field's current value.
SubSport subSport () const
Returns the SportMessage data message's subSport field's current value.
QString name () const
Returns the SportMessage data message's name field's current value.
void setSport (const Sport sport)
Sets the sport field to sport.
void setSubSport (const SubSport subSport)
Sets the subSport field to subSport.
void setName (const QString name)
Sets the name field to name.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
SportMessage (SportMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The SportMessage class represents a FIT SportMessage data message.
See also
DataMessage
Definition at line 39 of file sportmessage.h.
Constructor & Destructor Documentation
SportMessage() [1/2]
SportMessage::SportMessage ()
Constructs a SportMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file sportmessage.cpp.
                            : AbstractDataMessage(new SportMessagePrivate(this))
 {
 }
SportMessage() [2/2]
SportMessage::SportMessage (SportMessagePrivate *const d) explicit protected
Constructs a SportMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file sportmessage.cpp.
                                                         : AbstractDataMessage(d)
 {
 }
Member Function Documentation
name()
QString SportMessage::name () const
Returns the SportMessage data message's name field's current value.
Returns
the name field value.
Definition at line 96 of file sportmessage.cpp.
 {
     Q_D(const SportMessage);
     return d->name;
 }
Referenced by setName().
setName()
void SportMessage::setName (const QString name)
Sets the name field to name.
Parameters
name The field value to set.
Definition at line 127 of file sportmessage.cpp.
 {
     Q_D(SportMessage);
     d->name = name;
 }
References name().
setSport()
void SportMessage::setSport (const Sport sport)
Sets the sport field to sport.
Parameters
sport The field value to set.
Definition at line 107 of file sportmessage.cpp.
 {
     Q_D(SportMessage);
     d->sport = sport;
 }
References sport().
setSubSport()
void SportMessage::setSubSport (const SubSport subSport)
Sets the subSport field to subSport.
Parameters
subSport The field value to set.
Definition at line 117 of file sportmessage.cpp.
 {
     Q_D(SportMessage);
     d->subSport = subSport;
 }
References subSport().
sport()
Sport SportMessage::sport () const
Returns the SportMessage data message's sport field's current value.
Returns
the sport field value.
Definition at line 74 of file sportmessage.cpp.
 {
     Q_D(const SportMessage);
     return d->sport;
 }
Referenced by setSport().
subSport()
SubSport SportMessage::subSport () const
Returns the SportMessage data message's subSport field's current value.
Returns
the subSport field value.
Definition at line 85 of file sportmessage.cpp.
 {
     Q_D(const SportMessage);
     return d->subSport;
 }
Referenced by setSubSport().
The documentation for this class was generated from the following files:
sportmessage.h
sportmessage.cpp