QtFit: CapabilitiesMessage Class Reference
CapabilitiesMessage Class Reference
The CapabilitiesMessage class represents a FIT CapabilitiesMessage data message.
Public Member Functions
CapabilitiesMessage ()
Constructs a CapabilitiesMessage object.
quint8z languages () const
Returns the CapabilitiesMessage data message's languages field's current value.
SportBits0 sports () const
Returns the CapabilitiesMessage data message's sports field's current value.
WorkoutCapabilities workoutsSupported () const
Returns the CapabilitiesMessage data message's workoutsSupported field's current value.
ConnectivityCapabilities connectivitySupported () const
Returns the CapabilitiesMessage data message's connectivitySupported field's current value.
void setLanguages (const quint8z languages)
Sets the languages field to languages.
void setSports (const SportBits0 sports)
Sets the sports field to sports.
void setWorkoutsSupported (const WorkoutCapabilities workoutsSupported)
Sets the workoutsSupported field to workoutsSupported.
void setConnectivitySupported (const ConnectivityCapabilities connectivitySupported)
Sets the connectivitySupported field to connectivitySupported.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
CapabilitiesMessage (CapabilitiesMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The CapabilitiesMessage class represents a FIT CapabilitiesMessage data message.
See also
DataMessage
Definition at line 34 of file capabilitiesmessage.h.
Constructor & Destructor Documentation
CapabilitiesMessage() [1/2]
CapabilitiesMessage::CapabilitiesMessage ()
Constructs a CapabilitiesMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file capabilitiesmessage.cpp.
                                          : AbstractDataMessage(new CapabilitiesMessagePrivate(this))
 {
 }
CapabilitiesMessage() [2/2]
CapabilitiesMessage::CapabilitiesMessage (CapabilitiesMessagePrivate *const d) explicit protected
Constructs a CapabilitiesMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file capabilitiesmessage.cpp.
                                                                              : AbstractDataMessage(d)
 {
 }
Member Function Documentation
connectivitySupported()
ConnectivityCapabilities CapabilitiesMessage::connectivitySupported () const
Returns the CapabilitiesMessage data message's connectivitySupported field's current value.
Returns
the connectivitySupported field value.
Definition at line 106 of file capabilitiesmessage.cpp.
 {
     Q_D(const CapabilitiesMessage);
     return d->connectivitySupported;
 }
Referenced by setConnectivitySupported().
languages()
quint8z CapabilitiesMessage::languages () const
Returns the CapabilitiesMessage data message's languages field's current value.
Use language_bits_x types where x is index of array.
Returns
the languages field value.
Definition at line 71 of file capabilitiesmessage.cpp.
 {
     Q_D(const CapabilitiesMessage);
     return d->languages;
 }
Referenced by setLanguages().
setConnectivitySupported()
void CapabilitiesMessage::setConnectivitySupported (const ConnectivityCapabilities connectivitySupported)
Sets the connectivitySupported field to connectivitySupported.
Parameters
connectivitySupported The field value to set.
Definition at line 147 of file capabilitiesmessage.cpp.
 {
     Q_D(CapabilitiesMessage);
     d->connectivitySupported = connectivitySupported;
 }
References connectivitySupported().
setLanguages()
void CapabilitiesMessage::setLanguages (const quint8z languages)
Sets the languages field to languages.
Parameters
languages The field value to set.
Definition at line 117 of file capabilitiesmessage.cpp.
 {
     Q_D(CapabilitiesMessage);
     d->languages = languages;
 }
References languages().
setSports()
void CapabilitiesMessage::setSports (const SportBits0 sports)
Sets the sports field to sports.
Parameters
sports The field value to set.
Definition at line 127 of file capabilitiesmessage.cpp.
 {
     Q_D(CapabilitiesMessage);
     d->sports = sports;
 }
References sports().
setWorkoutsSupported()
void CapabilitiesMessage::setWorkoutsSupported (const WorkoutCapabilities workoutsSupported)
Sets the workoutsSupported field to workoutsSupported.
Parameters
workoutsSupported The field value to set.
Definition at line 137 of file capabilitiesmessage.cpp.
 {
     Q_D(CapabilitiesMessage);
     d->workoutsSupported = workoutsSupported;
 }
References workoutsSupported().
sports()
SportBits0 CapabilitiesMessage::sports () const
Returns the CapabilitiesMessage data message's sports field's current value.
Use sport_bits_x types where x is index of array.
Returns
the sports field value.
Definition at line 84 of file capabilitiesmessage.cpp.
 {
     Q_D(const CapabilitiesMessage);
     return d->sports;
 }
Referenced by setSports().
workoutsSupported()
WorkoutCapabilities CapabilitiesMessage::workoutsSupported () const
Returns the CapabilitiesMessage data message's workoutsSupported field's current value.
Returns
the workoutsSupported field value.
Definition at line 95 of file capabilitiesmessage.cpp.
 {
     Q_D(const CapabilitiesMessage);
     return d->workoutsSupported;
 }
Referenced by setWorkoutsSupported().
The documentation for this class was generated from the following files:
capabilitiesmessage.h
capabilitiesmessage.cpp