QtFit: HrMessage Class Reference
HrMessage Class Reference
The HrMessage class represents a FIT HrMessage data message.
Public Member Functions
HrMessage ()
Constructs a HrMessage object.
DateTime timestamp () const
Returns the HrMessage data message's timestamp field's current value.
quint16 fractionalTimestamp () const
Returns the HrMessage data message's fractionalTimestamp field's current value.
quint8 time256 () const
Returns the HrMessage data message's time256 field's current value.
quint8 filteredBpm () const
Returns the HrMessage data message's filteredBpm field's current value.
quint32 eventTimestamp () const
Returns the HrMessage data message's eventTimestamp field's current value.
quint8 eventTimestamp12 () const
Returns the HrMessage data message's eventTimestamp12 field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setFractionalTimestamp (const quint16 fractionalTimestamp)
Sets the fractionalTimestamp field to fractionalTimestamp.
void setTime256 (const quint8 time256)
Sets the time256 field to time256.
void setFilteredBpm (const quint8 filteredBpm)
Sets the filteredBpm field to filteredBpm.
void setEventTimestamp (const quint32 eventTimestamp)
Sets the eventTimestamp field to eventTimestamp.
void setEventTimestamp12 (const quint8 eventTimestamp12)
Sets the eventTimestamp12 field to eventTimestamp12.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
HrMessage (HrMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The HrMessage class represents a FIT HrMessage data message.
See also
DataMessage
Definition at line 34 of file hrmessage.h.
Constructor & Destructor Documentation
HrMessage() [1/2]
HrMessage::HrMessage ()
Constructs a HrMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file hrmessage.cpp.
                      : AbstractDataMessage(new HrMessagePrivate(this))
 {
 }
HrMessage() [2/2]
HrMessage::HrMessage (HrMessagePrivate *const d) explicit protected
Constructs a HrMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file hrmessage.cpp.
                                                : AbstractDataMessage(d)
 {
 }
Member Function Documentation
eventTimestamp()
quint32 HrMessage::eventTimestamp () const
Returns the HrMessage data message's eventTimestamp field's current value.
Returns
the eventTimestamp field value.
Definition at line 113 of file hrmessage.cpp.
 {
     Q_D(const HrMessage);
     return d->eventTimestamp;
 }
Referenced by setEventTimestamp().
eventTimestamp12()
quint8 HrMessage::eventTimestamp12 () const
Returns the HrMessage data message's eventTimestamp12 field's current value.
Returns
the eventTimestamp12 field value.
Definition at line 124 of file hrmessage.cpp.
 {
     Q_D(const HrMessage);
     return d->eventTimestamp12;
 }
Referenced by setEventTimestamp12().
filteredBpm()
quint8 HrMessage::filteredBpm () const
Returns the HrMessage data message's filteredBpm field's current value.
Returns
the filteredBpm field value.
Definition at line 102 of file hrmessage.cpp.
 {
     Q_D(const HrMessage);
     return d->filteredBpm;
 }
Referenced by setFilteredBpm().
fractionalTimestamp()
quint16 HrMessage::fractionalTimestamp () const
Returns the HrMessage data message's fractionalTimestamp field's current value.
Returns
the fractionalTimestamp field value.
Definition at line 80 of file hrmessage.cpp.
 {
     Q_D(const HrMessage);
     return d->fractionalTimestamp;
 }
Referenced by setFractionalTimestamp().
setEventTimestamp()
void HrMessage::setEventTimestamp (const quint32 eventTimestamp)
Sets the eventTimestamp field to eventTimestamp.
Parameters
eventTimestamp The field value to set.
Definition at line 175 of file hrmessage.cpp.
 {
     Q_D(HrMessage);
     d->eventTimestamp = eventTimestamp;
 }
References eventTimestamp().
setEventTimestamp12()
void HrMessage::setEventTimestamp12 (const quint8 eventTimestamp12)
Sets the eventTimestamp12 field to eventTimestamp12.
Parameters
eventTimestamp12 The field value to set.
Definition at line 185 of file hrmessage.cpp.
 {
     Q_D(HrMessage);
     d->eventTimestamp12 = eventTimestamp12;
 }
References eventTimestamp12().
setFilteredBpm()
void HrMessage::setFilteredBpm (const quint8 filteredBpm)
Sets the filteredBpm field to filteredBpm.
Parameters
filteredBpm The field value to set.
Definition at line 165 of file hrmessage.cpp.
 {
     Q_D(HrMessage);
     d->filteredBpm = filteredBpm;
 }
References filteredBpm().
setFractionalTimestamp()
void HrMessage::setFractionalTimestamp (const quint16 fractionalTimestamp)
Sets the fractionalTimestamp field to fractionalTimestamp.
Parameters
fractionalTimestamp The field value to set.
Definition at line 145 of file hrmessage.cpp.
 {
     Q_D(HrMessage);
     d->fractionalTimestamp = fractionalTimestamp;
 }
References fractionalTimestamp().
setTime256()
void HrMessage::setTime256 (const quint8 time256)
Sets the time256 field to time256.
Parameters
time256 The field value to set.
Definition at line 155 of file hrmessage.cpp.
 {
     Q_D(HrMessage);
     d->time256 = time256;
 }
References time256().
setTimestamp()
void HrMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 135 of file hrmessage.cpp.
 {
     Q_D(HrMessage);
     d->timestamp = timestamp;
 }
References timestamp().
time256()
quint8 HrMessage::time256 () const
Returns the HrMessage data message's time256 field's current value.
Returns
the time256 field value.
Definition at line 91 of file hrmessage.cpp.
 {
     Q_D(const HrMessage);
     return d->time256;
 }
Referenced by setTime256().
timestamp()
DateTime HrMessage::timestamp () const
Returns the HrMessage data message's timestamp field's current value.
Returns
the timestamp field value.
Definition at line 69 of file hrmessage.cpp.
 {
     Q_D(const HrMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
The documentation for this class was generated from the following files:
hrmessage.h
hrmessage.cpp