QtFit: MesgCapabilitiesMessage Class Reference
MesgCapabilitiesMessage Class Reference
The MesgCapabilitiesMessage class represents a FIT MesgCapabilitiesMessage data message.
Public Member Functions
MesgCapabilitiesMessage ()
Constructs a MesgCapabilitiesMessage object.
MessageIndex messageIndex () const
Returns the MesgCapabilitiesMessage data message's messageIndex field's current value.
File file () const
Returns the MesgCapabilitiesMessage data message's file field's current value.
MesgNum mesgNum () const
Returns the MesgCapabilitiesMessage data message's mesgNum field's current value.
MesgCount countType () const
Returns the MesgCapabilitiesMessage data message's countType field's current value.
quint16 count () const
Returns the MesgCapabilitiesMessage data message's count field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setFile (const File file)
Sets the file field to file.
void setMesgNum (const MesgNum mesgNum)
Sets the mesgNum field to mesgNum.
void setCountType (const MesgCount countType)
Sets the countType field to countType.
void setCount (const quint16 count)
Sets the count field to count.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
MesgCapabilitiesMessage (MesgCapabilitiesMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The MesgCapabilitiesMessage class represents a FIT MesgCapabilitiesMessage data message.
See also
DataMessage
Definition at line 34 of file mesgcapabilitiesmessage.h.
Constructor & Destructor Documentation
MesgCapabilitiesMessage() [1/2]
MesgCapabilitiesMessage::MesgCapabilitiesMessage ()
Constructs a MesgCapabilitiesMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file mesgcapabilitiesmessage.cpp.
                                                  : AbstractDataMessage(new MesgCapabilitiesMessagePrivate(this))
 {
 }
MesgCapabilitiesMessage() [2/2]
MesgCapabilitiesMessage::MesgCapabilitiesMessage (MesgCapabilitiesMessagePrivate *const d) explicit protected
Constructs a MesgCapabilitiesMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file mesgcapabilitiesmessage.cpp.
                                                                                          : AbstractDataMessage(d)
 {
 }
Member Function Documentation
count()
quint16 MesgCapabilitiesMessage::count () const
Returns the MesgCapabilitiesMessage data message's count field's current value.
Returns
the count field value.
Definition at line 113 of file mesgcapabilitiesmessage.cpp.
 {
     Q_D(const MesgCapabilitiesMessage);
     return d->count;
 }
Referenced by setCount().
countType()
MesgCount MesgCapabilitiesMessage::countType () const
Returns the MesgCapabilitiesMessage data message's countType field's current value.
Returns
the countType field value.
Definition at line 102 of file mesgcapabilitiesmessage.cpp.
 {
     Q_D(const MesgCapabilitiesMessage);
     return d->countType;
 }
Referenced by setCountType().
file()
File MesgCapabilitiesMessage::file () const
Returns the MesgCapabilitiesMessage data message's file field's current value.
Returns
the file field value.
Definition at line 80 of file mesgcapabilitiesmessage.cpp.
 {
     Q_D(const MesgCapabilitiesMessage);
     return d->file;
 }
Referenced by setFile().
mesgNum()
MesgNum MesgCapabilitiesMessage::mesgNum () const
Returns the MesgCapabilitiesMessage data message's mesgNum field's current value.
Returns
the mesgNum field value.
Definition at line 91 of file mesgcapabilitiesmessage.cpp.
 {
     Q_D(const MesgCapabilitiesMessage);
     return d->mesgNum;
 }
Referenced by setMesgNum().
messageIndex()
MessageIndex MesgCapabilitiesMessage::messageIndex () const
Returns the MesgCapabilitiesMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 69 of file mesgcapabilitiesmessage.cpp.
 {
     Q_D(const MesgCapabilitiesMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
setCount()
void MesgCapabilitiesMessage::setCount (const quint16 count)
Sets the count field to count.
Parameters
count The field value to set.
Definition at line 164 of file mesgcapabilitiesmessage.cpp.
 {
     Q_D(MesgCapabilitiesMessage);
     d->count = count;
 }
References count().
setCountType()
void MesgCapabilitiesMessage::setCountType (const MesgCount countType)
Sets the countType field to countType.
Parameters
countType The field value to set.
Definition at line 154 of file mesgcapabilitiesmessage.cpp.
 {
     Q_D(MesgCapabilitiesMessage);
     d->countType = countType;
 }
References countType().
setFile()
void MesgCapabilitiesMessage::setFile (const File file)
Sets the file field to file.
Parameters
file The field value to set.
Definition at line 134 of file mesgcapabilitiesmessage.cpp.
 {
     Q_D(MesgCapabilitiesMessage);
     d->file = file;
 }
References file().
setMesgNum()
void MesgCapabilitiesMessage::setMesgNum (const MesgNum mesgNum)
Sets the mesgNum field to mesgNum.
Parameters
mesgNum The field value to set.
Definition at line 144 of file mesgcapabilitiesmessage.cpp.
 {
     Q_D(MesgCapabilitiesMessage);
     d->mesgNum = mesgNum;
 }
References mesgNum().
setMessageIndex()
void MesgCapabilitiesMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 124 of file mesgcapabilitiesmessage.cpp.
 {
     Q_D(MesgCapabilitiesMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
The documentation for this class was generated from the following files:
mesgcapabilitiesmessage.h
mesgcapabilitiesmessage.cpp