QtFit: AviationAttitudeMessage Class Reference
AviationAttitudeMessage Class Reference
The AviationAttitudeMessage class represents a FIT AviationAttitudeMessage data message.
Public Member Functions
AviationAttitudeMessage ()
Constructs a AviationAttitudeMessage object.
DateTime timestamp () const
Returns the AviationAttitudeMessage data message's timestamp field's current value.
quint16 timestampMs () const
Returns the AviationAttitudeMessage data message's timestampMs field's current value.
quint32 systemTime () const
Returns the AviationAttitudeMessage data message's systemTime field's current value.
qint16 pitch () const
Returns the AviationAttitudeMessage data message's pitch field's current value.
qint16 roll () const
Returns the AviationAttitudeMessage data message's roll field's current value.
qint16 accelLateral () const
Returns the AviationAttitudeMessage data message's accelLateral field's current value.
qint16 accelNormal () const
Returns the AviationAttitudeMessage data message's accelNormal field's current value.
qint16 turnRate () const
Returns the AviationAttitudeMessage data message's turnRate field's current value.
AttitudeStage stage () const
Returns the AviationAttitudeMessage data message's stage field's current value.
quint8 attitudeStageComplete () const
Returns the AviationAttitudeMessage data message's attitudeStageComplete field's current value.
quint16 track () const
Returns the AviationAttitudeMessage data message's track field's current value.
AttitudeValidity validity () const
Returns the AviationAttitudeMessage data message's validity field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
void setSystemTime (const quint32 systemTime)
Sets the systemTime field to systemTime.
void setPitch (const qint16 pitch)
Sets the pitch field to pitch.
void setRoll (const qint16 roll)
Sets the roll field to roll.
void setAccelLateral (const qint16 accelLateral)
Sets the accelLateral field to accelLateral.
void setAccelNormal (const qint16 accelNormal)
Sets the accelNormal field to accelNormal.
void setTurnRate (const qint16 turnRate)
Sets the turnRate field to turnRate.
void setStage (const AttitudeStage stage)
Sets the stage field to stage.
void setAttitudeStageComplete (const quint8 attitudeStageComplete)
Sets the attitudeStageComplete field to attitudeStageComplete.
void setTrack (const quint16 track)
Sets the track field to track.
void setValidity (const AttitudeValidity validity)
Sets the validity field to validity.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
AviationAttitudeMessage (AviationAttitudeMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The AviationAttitudeMessage class represents a FIT AviationAttitudeMessage data message.
See also
DataMessage
Definition at line 39 of file aviationattitudemessage.h.
Constructor & Destructor Documentation
AviationAttitudeMessage() [1/2]
AviationAttitudeMessage::AviationAttitudeMessage ()
Constructs a AviationAttitudeMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file aviationattitudemessage.cpp.
                                                  : AbstractDataMessage(new AviationAttitudeMessagePrivate(this))
 {
 }
AviationAttitudeMessage() [2/2]
AviationAttitudeMessage::AviationAttitudeMessage (AviationAttitudeMessagePrivate *const d) explicit protected
Constructs a AviationAttitudeMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file aviationattitudemessage.cpp.
                                                                                          : AbstractDataMessage(d)
 {
 }
Member Function Documentation
accelLateral()
qint16 AviationAttitudeMessage::accelLateral () const
Returns the AviationAttitudeMessage data message's accelLateral field's current value.
Range -78.4 to +78.4 (-8 Gs to 8 Gs)
Returns
the accelLateral field value.
Definition at line 141 of file aviationattitudemessage.cpp.
 {
     Q_D(const AviationAttitudeMessage);
     return d->accelLateral;
 }
Referenced by setAccelLateral().
accelNormal()
qint16 AviationAttitudeMessage::accelNormal () const
Returns the AviationAttitudeMessage data message's accelNormal field's current value.
Range -78.4 to +78.4 (-8 Gs to 8 Gs)
Returns
the accelNormal field value.
Definition at line 154 of file aviationattitudemessage.cpp.
 {
     Q_D(const AviationAttitudeMessage);
     return d->accelNormal;
 }
Referenced by setAccelNormal().
attitudeStageComplete()
quint8 AviationAttitudeMessage::attitudeStageComplete () const
Returns the AviationAttitudeMessage data message's attitudeStageComplete field's current value.
The percent complete of the current attitude stage. Set to 0 for attitude stages 0, 1 and 2 and to 100 for attitude stage 3 by AHRS modules that do not support it. Range - 100
Returns
the attitudeStageComplete field value.
Definition at line 192 of file aviationattitudemessage.cpp.
 {
     Q_D(const AviationAttitudeMessage);
     return d->attitudeStageComplete;
 }
Referenced by setAttitudeStageComplete().
pitch()
qint16 AviationAttitudeMessage::pitch () const
Returns the AviationAttitudeMessage data message's pitch field's current value.
Range -PI/2 to +PI/2
Returns
the pitch field value.
Definition at line 115 of file aviationattitudemessage.cpp.
 {
     Q_D(const AviationAttitudeMessage);
     return d->pitch;
 }
Referenced by setPitch().
roll()
qint16 AviationAttitudeMessage::roll () const
Returns the AviationAttitudeMessage data message's roll field's current value.
Range -PI to +PI
Returns
the roll field value.
Definition at line 128 of file aviationattitudemessage.cpp.
 {
     Q_D(const AviationAttitudeMessage);
     return d->roll;
 }
Referenced by setRoll().
setAccelLateral()
void AviationAttitudeMessage::setAccelLateral (const qint16 accelLateral)
Sets the accelLateral field to accelLateral.
Parameters
accelLateral The field value to set.
Definition at line 277 of file aviationattitudemessage.cpp.
 {
     Q_D(AviationAttitudeMessage);
     d->accelLateral = accelLateral;
 }
References accelLateral().
setAccelNormal()
void AviationAttitudeMessage::setAccelNormal (const qint16 accelNormal)
Sets the accelNormal field to accelNormal.
Parameters
accelNormal The field value to set.
Definition at line 287 of file aviationattitudemessage.cpp.
 {
     Q_D(AviationAttitudeMessage);
     d->accelNormal = accelNormal;
 }
References accelNormal().
setAttitudeStageComplete()
void AviationAttitudeMessage::setAttitudeStageComplete (const quint8 attitudeStageComplete)
Sets the attitudeStageComplete field to attitudeStageComplete.
Parameters
attitudeStageComplete The field value to set.
Definition at line 317 of file aviationattitudemessage.cpp.
 {
     Q_D(AviationAttitudeMessage);
     d->attitudeStageComplete = attitudeStageComplete;
 }
References attitudeStageComplete().
setPitch()
void AviationAttitudeMessage::setPitch (const qint16 pitch)
Sets the pitch field to pitch.
Parameters
pitch The field value to set.
Definition at line 257 of file aviationattitudemessage.cpp.
 {
     Q_D(AviationAttitudeMessage);
     d->pitch = pitch;
 }
References pitch().
setRoll()
void AviationAttitudeMessage::setRoll (const qint16 roll)
Sets the roll field to roll.
Parameters
roll The field value to set.
Definition at line 267 of file aviationattitudemessage.cpp.
 {
     Q_D(AviationAttitudeMessage);
     d->roll = roll;
 }
References roll().
setStage()
void AviationAttitudeMessage::setStage (const AttitudeStage stage)
Sets the stage field to stage.
Parameters
stage The field value to set.
Definition at line 307 of file aviationattitudemessage.cpp.
 {
     Q_D(AviationAttitudeMessage);
     d->stage = stage;
 }
References stage().
setSystemTime()
void AviationAttitudeMessage::setSystemTime (const quint32 systemTime)
Sets the systemTime field to systemTime.
Parameters
systemTime The field value to set.
Definition at line 247 of file aviationattitudemessage.cpp.
 {
     Q_D(AviationAttitudeMessage);
     d->systemTime = systemTime;
 }
References systemTime().
setTimestamp()
void AviationAttitudeMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 227 of file aviationattitudemessage.cpp.
 {
     Q_D(AviationAttitudeMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setTimestampMs()
void AviationAttitudeMessage::setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
Parameters
timestampMs The field value to set.
Definition at line 237 of file aviationattitudemessage.cpp.
 {
     Q_D(AviationAttitudeMessage);
     d->timestampMs = timestampMs;
 }
References timestampMs().
setTrack()
void AviationAttitudeMessage::setTrack (const quint16 track)
Sets the track field to track.
Parameters
track The field value to set.
Definition at line 327 of file aviationattitudemessage.cpp.
 {
     Q_D(AviationAttitudeMessage);
     d->track = track;
 }
References track().
setTurnRate()
void AviationAttitudeMessage::setTurnRate (const qint16 turnRate)
Sets the turnRate field to turnRate.
Parameters
turnRate The field value to set.
Definition at line 297 of file aviationattitudemessage.cpp.
 {
     Q_D(AviationAttitudeMessage);
     d->turnRate = turnRate;
 }
References turnRate().
setValidity()
void AviationAttitudeMessage::setValidity (const AttitudeValidity validity)
Sets the validity field to validity.
Parameters
validity The field value to set.
Definition at line 337 of file aviationattitudemessage.cpp.
 {
     Q_D(AviationAttitudeMessage);
     d->validity = validity;
 }
References validity().
stage()
AttitudeStage AviationAttitudeMessage::stage () const
Returns the AviationAttitudeMessage data message's stage field's current value.
Returns
the stage field value.
Definition at line 178 of file aviationattitudemessage.cpp.
 {
     Q_D(const AviationAttitudeMessage);
     return d->stage;
 }
Referenced by setStage().
systemTime()
quint32 AviationAttitudeMessage::systemTime () const
Returns the AviationAttitudeMessage data message's systemTime field's current value.
System time associated with sample expressed in ms.
Returns
the systemTime field value.
Definition at line 102 of file aviationattitudemessage.cpp.
 {
     Q_D(const AviationAttitudeMessage);
     return d->systemTime;
 }
Referenced by setSystemTime().
timestamp()
DateTime AviationAttitudeMessage::timestamp () const
Returns the AviationAttitudeMessage data message's timestamp field's current value.
Timestamp message was output
Returns
the timestamp field value.
Definition at line 76 of file aviationattitudemessage.cpp.
 {
     Q_D(const AviationAttitudeMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
timestampMs()
quint16 AviationAttitudeMessage::timestampMs () const
Returns the AviationAttitudeMessage data message's timestampMs field's current value.
Fractional part of timestamp, added to timestamp
Returns
the timestampMs field value.
Definition at line 89 of file aviationattitudemessage.cpp.
 {
     Q_D(const AviationAttitudeMessage);
     return d->timestampMs;
 }
Referenced by setTimestampMs().
track()
quint16 AviationAttitudeMessage::track () const
Returns the AviationAttitudeMessage data message's track field's current value.
Track Angle/Heading Range 0 - 2pi
Returns
the track field value.
Definition at line 205 of file aviationattitudemessage.cpp.
 {
     Q_D(const AviationAttitudeMessage);
     return d->track;
 }
Referenced by setTrack().
turnRate()
qint16 AviationAttitudeMessage::turnRate () const
Returns the AviationAttitudeMessage data message's turnRate field's current value.
Range -8.727 to +8.727 (-500 degs/sec to +500 degs/sec)
Returns
the turnRate field value.
Definition at line 167 of file aviationattitudemessage.cpp.
 {
     Q_D(const AviationAttitudeMessage);
     return d->turnRate;
 }
Referenced by setTurnRate().
validity()
AttitudeValidity AviationAttitudeMessage::validity () const
Returns the AviationAttitudeMessage data message's validity field's current value.
Returns
the validity field value.
Definition at line 216 of file aviationattitudemessage.cpp.
 {
     Q_D(const AviationAttitudeMessage);
     return d->validity;
 }
Referenced by setValidity().
The documentation for this class was generated from the following files:
aviationattitudemessage.h
aviationattitudemessage.cpp