QtFit: DiveGasMessage Class Reference
DiveGasMessage Class Reference
The DiveGasMessage class represents a FIT DiveGasMessage data message.
Public Member Functions
DiveGasMessage ()
Constructs a DiveGasMessage object.
MessageIndex messageIndex () const
Returns the DiveGasMessage data message's messageIndex field's current value.
quint8 heliumContent () const
Returns the DiveGasMessage data message's heliumContent field's current value.
quint8 oxygenContent () const
Returns the DiveGasMessage data message's oxygenContent field's current value.
DiveGasStatus status () const
Returns the DiveGasMessage data message's status field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setHeliumContent (const quint8 heliumContent)
Sets the heliumContent field to heliumContent.
void setOxygenContent (const quint8 oxygenContent)
Sets the oxygenContent field to oxygenContent.
void setStatus (const DiveGasStatus status)
Sets the status field to status.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
DiveGasMessage (DiveGasMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The DiveGasMessage class represents a FIT DiveGasMessage data message.
See also
DataMessage
Definition at line 39 of file divegasmessage.h.
Constructor & Destructor Documentation
DiveGasMessage() [1/2]
DiveGasMessage::DiveGasMessage ()
Constructs a DiveGasMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file divegasmessage.cpp.
                                : AbstractDataMessage(new DiveGasMessagePrivate(this))
 {
 }
DiveGasMessage() [2/2]
DiveGasMessage::DiveGasMessage (DiveGasMessagePrivate *const d) explicit protected
Constructs a DiveGasMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file divegasmessage.cpp.
                                                               : AbstractDataMessage(d)
 {
 }
Member Function Documentation
heliumContent()
quint8 DiveGasMessage::heliumContent () const
Returns the DiveGasMessage data message's heliumContent field's current value.
Returns
the heliumContent field value.
Definition at line 85 of file divegasmessage.cpp.
 {
     Q_D(const DiveGasMessage);
     return d->heliumContent;
 }
Referenced by setHeliumContent().
messageIndex()
MessageIndex DiveGasMessage::messageIndex () const
Returns the DiveGasMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 74 of file divegasmessage.cpp.
 {
     Q_D(const DiveGasMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
oxygenContent()
quint8 DiveGasMessage::oxygenContent () const
Returns the DiveGasMessage data message's oxygenContent field's current value.
Returns
the oxygenContent field value.
Definition at line 96 of file divegasmessage.cpp.
 {
     Q_D(const DiveGasMessage);
     return d->oxygenContent;
 }
Referenced by setOxygenContent().
setHeliumContent()
void DiveGasMessage::setHeliumContent (const quint8 heliumContent)
Sets the heliumContent field to heliumContent.
Parameters
heliumContent The field value to set.
Definition at line 128 of file divegasmessage.cpp.
 {
     Q_D(DiveGasMessage);
     d->heliumContent = heliumContent;
 }
References heliumContent().
setMessageIndex()
void DiveGasMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 118 of file divegasmessage.cpp.
 {
     Q_D(DiveGasMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setOxygenContent()
void DiveGasMessage::setOxygenContent (const quint8 oxygenContent)
Sets the oxygenContent field to oxygenContent.
Parameters
oxygenContent The field value to set.
Definition at line 138 of file divegasmessage.cpp.
 {
     Q_D(DiveGasMessage);
     d->oxygenContent = oxygenContent;
 }
References oxygenContent().
setStatus()
void DiveGasMessage::setStatus (const DiveGasStatus status)
Sets the status field to status.
Parameters
status The field value to set.
Definition at line 148 of file divegasmessage.cpp.
 {
     Q_D(DiveGasMessage);
     d->status = status;
 }
References status().
status()
DiveGasStatus DiveGasMessage::status () const
Returns the DiveGasMessage data message's status field's current value.
Returns
the status field value.
Definition at line 107 of file divegasmessage.cpp.
 {
     Q_D(const DiveGasMessage);
     return d->status;
 }
Referenced by setStatus().
The documentation for this class was generated from the following files:
divegasmessage.h
divegasmessage.cpp