QtFit: SegmentLapMessage Class Reference
SegmentLapMessage Class Reference
The SegmentLapMessage class represents a FIT SegmentLapMessage data message.
Public Member Functions
SegmentLapMessage ()
Constructs a SegmentLapMessage object.
MessageIndex messageIndex () const
Returns the SegmentLapMessage data message's messageIndex field's current value.
DateTime timestamp () const
Returns the SegmentLapMessage data message's timestamp field's current value.
Event event () const
Returns the SegmentLapMessage data message's event field's current value.
EventType eventType () const
Returns the SegmentLapMessage data message's eventType field's current value.
DateTime startTime () const
Returns the SegmentLapMessage data message's startTime field's current value.
qint32 startPositionLat () const
Returns the SegmentLapMessage data message's startPositionLat field's current value.
qint32 startPositionLong () const
Returns the SegmentLapMessage data message's startPositionLong field's current value.
qint32 endPositionLat () const
Returns the SegmentLapMessage data message's endPositionLat field's current value.
qint32 endPositionLong () const
Returns the SegmentLapMessage data message's endPositionLong field's current value.
quint32 totalElapsedTime () const
Returns the SegmentLapMessage data message's totalElapsedTime field's current value.
quint32 totalTimerTime () const
Returns the SegmentLapMessage data message's totalTimerTime field's current value.
quint32 totalDistance () const
Returns the SegmentLapMessage data message's totalDistance field's current value.
quint32 totalCycles () const
Returns the SegmentLapMessage data message's totalCycles field's current value.
quint16 totalCalories () const
Returns the SegmentLapMessage data message's totalCalories field's current value.
quint16 totalFatCalories () const
Returns the SegmentLapMessage data message's totalFatCalories field's current value.
quint16 avgSpeed () const
Returns the SegmentLapMessage data message's avgSpeed field's current value.
quint16 maxSpeed () const
Returns the SegmentLapMessage data message's maxSpeed field's current value.
quint8 avgHeartRate () const
Returns the SegmentLapMessage data message's avgHeartRate field's current value.
quint8 maxHeartRate () const
Returns the SegmentLapMessage data message's maxHeartRate field's current value.
quint8 avgCadence () const
Returns the SegmentLapMessage data message's avgCadence field's current value.
quint8 maxCadence () const
Returns the SegmentLapMessage data message's maxCadence field's current value.
quint16 avgPower () const
Returns the SegmentLapMessage data message's avgPower field's current value.
quint16 maxPower () const
Returns the SegmentLapMessage data message's maxPower field's current value.
quint16 totalAscent () const
Returns the SegmentLapMessage data message's totalAscent field's current value.
quint16 totalDescent () const
Returns the SegmentLapMessage data message's totalDescent field's current value.
Sport sport () const
Returns the SegmentLapMessage data message's sport field's current value.
quint8 eventGroup () const
Returns the SegmentLapMessage data message's eventGroup field's current value.
qint32 necLat () const
Returns the SegmentLapMessage data message's necLat field's current value.
qint32 necLong () const
Returns the SegmentLapMessage data message's necLong field's current value.
qint32 swcLat () const
Returns the SegmentLapMessage data message's swcLat field's current value.
qint32 swcLong () const
Returns the SegmentLapMessage data message's swcLong field's current value.
QString name () const
Returns the SegmentLapMessage data message's name field's current value.
quint16 normalizedPower () const
Returns the SegmentLapMessage data message's normalizedPower field's current value.
LeftRightBalance100 leftRightBalance () const
Returns the SegmentLapMessage data message's leftRightBalance field's current value.
SubSport subSport () const
Returns the SegmentLapMessage data message's subSport field's current value.
quint32 totalWork () const
Returns the SegmentLapMessage data message's totalWork field's current value.
quint16 avgAltitude () const
Returns the SegmentLapMessage data message's avgAltitude field's current value.
quint16 maxAltitude () const
Returns the SegmentLapMessage data message's maxAltitude field's current value.
quint8 gpsAccuracy () const
Returns the SegmentLapMessage data message's gpsAccuracy field's current value.
qint16 avgGrade () const
Returns the SegmentLapMessage data message's avgGrade field's current value.
qint16 avgPosGrade () const
Returns the SegmentLapMessage data message's avgPosGrade field's current value.
qint16 avgNegGrade () const
Returns the SegmentLapMessage data message's avgNegGrade field's current value.
qint16 maxPosGrade () const
Returns the SegmentLapMessage data message's maxPosGrade field's current value.
qint16 maxNegGrade () const
Returns the SegmentLapMessage data message's maxNegGrade field's current value.
qint8 avgTemperature () const
Returns the SegmentLapMessage data message's avgTemperature field's current value.
qint8 maxTemperature () const
Returns the SegmentLapMessage data message's maxTemperature field's current value.
quint32 totalMovingTime () const
Returns the SegmentLapMessage data message's totalMovingTime field's current value.
qint16 avgPosVerticalSpeed () const
Returns the SegmentLapMessage data message's avgPosVerticalSpeed field's current value.
qint16 avgNegVerticalSpeed () const
Returns the SegmentLapMessage data message's avgNegVerticalSpeed field's current value.
qint16 maxPosVerticalSpeed () const
Returns the SegmentLapMessage data message's maxPosVerticalSpeed field's current value.
qint16 maxNegVerticalSpeed () const
Returns the SegmentLapMessage data message's maxNegVerticalSpeed field's current value.
quint32 timeInHrZone () const
Returns the SegmentLapMessage data message's timeInHrZone field's current value.
quint32 timeInSpeedZone () const
Returns the SegmentLapMessage data message's timeInSpeedZone field's current value.
quint32 timeInCadenceZone () const
Returns the SegmentLapMessage data message's timeInCadenceZone field's current value.
quint32 timeInPowerZone () const
Returns the SegmentLapMessage data message's timeInPowerZone field's current value.
quint16 repetitionNum () const
Returns the SegmentLapMessage data message's repetitionNum field's current value.
quint16 minAltitude () const
Returns the SegmentLapMessage data message's minAltitude field's current value.
quint8 minHeartRate () const
Returns the SegmentLapMessage data message's minHeartRate field's current value.
quint32 activeTime () const
Returns the SegmentLapMessage data message's activeTime field's current value.
MessageIndex wktStepIndex () const
Returns the SegmentLapMessage data message's wktStepIndex field's current value.
SportEvent sportEvent () const
Returns the SegmentLapMessage data message's sportEvent field's current value.
quint8 avgLeftTorqueEffectiveness () const
Returns the SegmentLapMessage data message's avgLeftTorqueEffectiveness field's current value.
quint8 avgRightTorqueEffectiveness () const
Returns the SegmentLapMessage data message's avgRightTorqueEffectiveness field's current value.
quint8 avgLeftPedalSmoothness () const
Returns the SegmentLapMessage data message's avgLeftPedalSmoothness field's current value.
quint8 avgRightPedalSmoothness () const
Returns the SegmentLapMessage data message's avgRightPedalSmoothness field's current value.
quint8 avgCombinedPedalSmoothness () const
Returns the SegmentLapMessage data message's avgCombinedPedalSmoothness field's current value.
SegmentLapStatus status () const
Returns the SegmentLapMessage data message's status field's current value.
QString uuid () const
Returns the SegmentLapMessage data message's uuid field's current value.
quint8 avgFractionalCadence () const
Returns the SegmentLapMessage data message's avgFractionalCadence field's current value.
quint8 maxFractionalCadence () const
Returns the SegmentLapMessage data message's maxFractionalCadence field's current value.
quint8 totalFractionalCycles () const
Returns the SegmentLapMessage data message's totalFractionalCycles field's current value.
quint16 frontGearShiftCount () const
Returns the SegmentLapMessage data message's frontGearShiftCount field's current value.
quint16 rearGearShiftCount () const
Returns the SegmentLapMessage data message's rearGearShiftCount field's current value.
quint32 timeStanding () const
Returns the SegmentLapMessage data message's timeStanding field's current value.
quint16 standCount () const
Returns the SegmentLapMessage data message's standCount field's current value.
qint8 avgLeftPco () const
Returns the SegmentLapMessage data message's avgLeftPco field's current value.
qint8 avgRightPco () const
Returns the SegmentLapMessage data message's avgRightPco field's current value.
quint8 avgLeftPowerPhase () const
Returns the SegmentLapMessage data message's avgLeftPowerPhase field's current value.
quint8 avgLeftPowerPhasePeak () const
Returns the SegmentLapMessage data message's avgLeftPowerPhasePeak field's current value.
quint8 avgRightPowerPhase () const
Returns the SegmentLapMessage data message's avgRightPowerPhase field's current value.
quint8 avgRightPowerPhasePeak () const
Returns the SegmentLapMessage data message's avgRightPowerPhasePeak field's current value.
quint16 avgPowerPosition () const
Returns the SegmentLapMessage data message's avgPowerPosition field's current value.
quint16 maxPowerPosition () const
Returns the SegmentLapMessage data message's maxPowerPosition field's current value.
quint8 avgCadencePosition () const
Returns the SegmentLapMessage data message's avgCadencePosition field's current value.
quint8 maxCadencePosition () const
Returns the SegmentLapMessage data message's maxCadencePosition field's current value.
Manufacturer manufacturer () const
Returns the SegmentLapMessage data message's manufacturer field's current value.
float totalGrit () const
Returns the SegmentLapMessage data message's totalGrit field's current value.
float totalFlow () const
Returns the SegmentLapMessage data message's totalFlow field's current value.
float avgGrit () const
Returns the SegmentLapMessage data message's avgGrit field's current value.
float avgFlow () const
Returns the SegmentLapMessage data message's avgFlow field's current value.
quint8 totalFractionalAscent () const
Returns the SegmentLapMessage data message's totalFractionalAscent field's current value.
quint8 totalFractionalDescent () const
Returns the SegmentLapMessage data message's totalFractionalDescent field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setEvent (const Event event)
Sets the event field to event.
void setEventType (const EventType eventType)
Sets the eventType field to eventType.
void setStartTime (const DateTime startTime)
Sets the startTime field to startTime.
void setStartPositionLat (const qint32 startPositionLat)
Sets the startPositionLat field to startPositionLat.
void setStartPositionLong (const qint32 startPositionLong)
Sets the startPositionLong field to startPositionLong.
void setEndPositionLat (const qint32 endPositionLat)
Sets the endPositionLat field to endPositionLat.
void setEndPositionLong (const qint32 endPositionLong)
Sets the endPositionLong field to endPositionLong.
void setTotalElapsedTime (const quint32 totalElapsedTime)
Sets the totalElapsedTime field to totalElapsedTime.
void setTotalTimerTime (const quint32 totalTimerTime)
Sets the totalTimerTime field to totalTimerTime.
void setTotalDistance (const quint32 totalDistance)
Sets the totalDistance field to totalDistance.
void setTotalCycles (const quint32 totalCycles)
Sets the totalCycles field to totalCycles.
void setTotalCalories (const quint16 totalCalories)
Sets the totalCalories field to totalCalories.
void setTotalFatCalories (const quint16 totalFatCalories)
Sets the totalFatCalories field to totalFatCalories.
void setAvgSpeed (const quint16 avgSpeed)
Sets the avgSpeed field to avgSpeed.
void setMaxSpeed (const quint16 maxSpeed)
Sets the maxSpeed field to maxSpeed.
void setAvgHeartRate (const quint8 avgHeartRate)
Sets the avgHeartRate field to avgHeartRate.
void setMaxHeartRate (const quint8 maxHeartRate)
Sets the maxHeartRate field to maxHeartRate.
void setAvgCadence (const quint8 avgCadence)
Sets the avgCadence field to avgCadence.
void setMaxCadence (const quint8 maxCadence)
Sets the maxCadence field to maxCadence.
void setAvgPower (const quint16 avgPower)
Sets the avgPower field to avgPower.
void setMaxPower (const quint16 maxPower)
Sets the maxPower field to maxPower.
void setTotalAscent (const quint16 totalAscent)
Sets the totalAscent field to totalAscent.
void setTotalDescent (const quint16 totalDescent)
Sets the totalDescent field to totalDescent.
void setSport (const Sport sport)
Sets the sport field to sport.
void setEventGroup (const quint8 eventGroup)
Sets the eventGroup field to eventGroup.
void setNecLat (const qint32 necLat)
Sets the necLat field to necLat.
void setNecLong (const qint32 necLong)
Sets the necLong field to necLong.
void setSwcLat (const qint32 swcLat)
Sets the swcLat field to swcLat.
void setSwcLong (const qint32 swcLong)
Sets the swcLong field to swcLong.
void setName (const QString name)
Sets the name field to name.
void setNormalizedPower (const quint16 normalizedPower)
Sets the normalizedPower field to normalizedPower.
void setLeftRightBalance (const LeftRightBalance100 leftRightBalance)
Sets the leftRightBalance field to leftRightBalance.
void setSubSport (const SubSport subSport)
Sets the subSport field to subSport.
void setTotalWork (const quint32 totalWork)
Sets the totalWork field to totalWork.
void setAvgAltitude (const quint16 avgAltitude)
Sets the avgAltitude field to avgAltitude.
void setMaxAltitude (const quint16 maxAltitude)
Sets the maxAltitude field to maxAltitude.
void setGpsAccuracy (const quint8 gpsAccuracy)
Sets the gpsAccuracy field to gpsAccuracy.
void setAvgGrade (const qint16 avgGrade)
Sets the avgGrade field to avgGrade.
void setAvgPosGrade (const qint16 avgPosGrade)
Sets the avgPosGrade field to avgPosGrade.
void setAvgNegGrade (const qint16 avgNegGrade)
Sets the avgNegGrade field to avgNegGrade.
void setMaxPosGrade (const qint16 maxPosGrade)
Sets the maxPosGrade field to maxPosGrade.
void setMaxNegGrade (const qint16 maxNegGrade)
Sets the maxNegGrade field to maxNegGrade.
void setAvgTemperature (const qint8 avgTemperature)
Sets the avgTemperature field to avgTemperature.
void setMaxTemperature (const qint8 maxTemperature)
Sets the maxTemperature field to maxTemperature.
void setTotalMovingTime (const quint32 totalMovingTime)
Sets the totalMovingTime field to totalMovingTime.
void setAvgPosVerticalSpeed (const qint16 avgPosVerticalSpeed)
Sets the avgPosVerticalSpeed field to avgPosVerticalSpeed.
void setAvgNegVerticalSpeed (const qint16 avgNegVerticalSpeed)
Sets the avgNegVerticalSpeed field to avgNegVerticalSpeed.
void setMaxPosVerticalSpeed (const qint16 maxPosVerticalSpeed)
Sets the maxPosVerticalSpeed field to maxPosVerticalSpeed.
void setMaxNegVerticalSpeed (const qint16 maxNegVerticalSpeed)
Sets the maxNegVerticalSpeed field to maxNegVerticalSpeed.
void setTimeInHrZone (const quint32 timeInHrZone)
Sets the timeInHrZone field to timeInHrZone.
void setTimeInSpeedZone (const quint32 timeInSpeedZone)
Sets the timeInSpeedZone field to timeInSpeedZone.
void setTimeInCadenceZone (const quint32 timeInCadenceZone)
Sets the timeInCadenceZone field to timeInCadenceZone.
void setTimeInPowerZone (const quint32 timeInPowerZone)
Sets the timeInPowerZone field to timeInPowerZone.
void setRepetitionNum (const quint16 repetitionNum)
Sets the repetitionNum field to repetitionNum.
void setMinAltitude (const quint16 minAltitude)
Sets the minAltitude field to minAltitude.
void setMinHeartRate (const quint8 minHeartRate)
Sets the minHeartRate field to minHeartRate.
void setActiveTime (const quint32 activeTime)
Sets the activeTime field to activeTime.
void setWktStepIndex (const MessageIndex wktStepIndex)
Sets the wktStepIndex field to wktStepIndex.
void setSportEvent (const SportEvent sportEvent)
Sets the sportEvent field to sportEvent.
void setAvgLeftTorqueEffectiveness (const quint8 avgLeftTorqueEffectiveness)
Sets the avgLeftTorqueEffectiveness field to avgLeftTorqueEffectiveness.
void setAvgRightTorqueEffectiveness (const quint8 avgRightTorqueEffectiveness)
Sets the avgRightTorqueEffectiveness field to avgRightTorqueEffectiveness.
void setAvgLeftPedalSmoothness (const quint8 avgLeftPedalSmoothness)
Sets the avgLeftPedalSmoothness field to avgLeftPedalSmoothness.
void setAvgRightPedalSmoothness (const quint8 avgRightPedalSmoothness)
Sets the avgRightPedalSmoothness field to avgRightPedalSmoothness.
void setAvgCombinedPedalSmoothness (const quint8 avgCombinedPedalSmoothness)
Sets the avgCombinedPedalSmoothness field to avgCombinedPedalSmoothness.
void setStatus (const SegmentLapStatus status)
Sets the status field to status.
void setUuid (const QString uuid)
Sets the uuid field to uuid.
void setAvgFractionalCadence (const quint8 avgFractionalCadence)
Sets the avgFractionalCadence field to avgFractionalCadence.
void setMaxFractionalCadence (const quint8 maxFractionalCadence)
Sets the maxFractionalCadence field to maxFractionalCadence.
void setTotalFractionalCycles (const quint8 totalFractionalCycles)
Sets the totalFractionalCycles field to totalFractionalCycles.
void setFrontGearShiftCount (const quint16 frontGearShiftCount)
Sets the frontGearShiftCount field to frontGearShiftCount.
void setRearGearShiftCount (const quint16 rearGearShiftCount)
Sets the rearGearShiftCount field to rearGearShiftCount.
void setTimeStanding (const quint32 timeStanding)
Sets the timeStanding field to timeStanding.
void setStandCount (const quint16 standCount)
Sets the standCount field to standCount.
void setAvgLeftPco (const qint8 avgLeftPco)
Sets the avgLeftPco field to avgLeftPco.
void setAvgRightPco (const qint8 avgRightPco)
Sets the avgRightPco field to avgRightPco.
void setAvgLeftPowerPhase (const quint8 avgLeftPowerPhase)
Sets the avgLeftPowerPhase field to avgLeftPowerPhase.
void setAvgLeftPowerPhasePeak (const quint8 avgLeftPowerPhasePeak)
Sets the avgLeftPowerPhasePeak field to avgLeftPowerPhasePeak.
void setAvgRightPowerPhase (const quint8 avgRightPowerPhase)
Sets the avgRightPowerPhase field to avgRightPowerPhase.
void setAvgRightPowerPhasePeak (const quint8 avgRightPowerPhasePeak)
Sets the avgRightPowerPhasePeak field to avgRightPowerPhasePeak.
void setAvgPowerPosition (const quint16 avgPowerPosition)
Sets the avgPowerPosition field to avgPowerPosition.
void setMaxPowerPosition (const quint16 maxPowerPosition)
Sets the maxPowerPosition field to maxPowerPosition.
void setAvgCadencePosition (const quint8 avgCadencePosition)
Sets the avgCadencePosition field to avgCadencePosition.
void setMaxCadencePosition (const quint8 maxCadencePosition)
Sets the maxCadencePosition field to maxCadencePosition.
void setManufacturer (const Manufacturer manufacturer)
Sets the manufacturer field to manufacturer.
void setTotalGrit (const float totalGrit)
Sets the totalGrit field to totalGrit.
void setTotalFlow (const float totalFlow)
Sets the totalFlow field to totalFlow.
void setAvgGrit (const float avgGrit)
Sets the avgGrit field to avgGrit.
void setAvgFlow (const float avgFlow)
Sets the avgFlow field to avgFlow.
void setTotalFractionalAscent (const quint8 totalFractionalAscent)
Sets the totalFractionalAscent field to totalFractionalAscent.
void setTotalFractionalDescent (const quint8 totalFractionalDescent)
Sets the totalFractionalDescent field to totalFractionalDescent.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
SegmentLapMessage (SegmentLapMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The SegmentLapMessage class represents a FIT SegmentLapMessage data message.
See also
DataMessage
Definition at line 39 of file segmentlapmessage.h.
Constructor & Destructor Documentation
SegmentLapMessage() [1/2]
SegmentLapMessage::SegmentLapMessage ()
Constructs a SegmentLapMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file segmentlapmessage.cpp.
                                      : AbstractDataMessage(new SegmentLapMessagePrivate(this))
 {
 }
SegmentLapMessage() [2/2]
SegmentLapMessage::SegmentLapMessage (SegmentLapMessagePrivate *const d) explicit protected
Constructs a SegmentLapMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file segmentlapmessage.cpp.
                                                                        : AbstractDataMessage(d)
 {
 }
Member Function Documentation
activeTime()
quint32 SegmentLapMessage::activeTime () const
Returns the SegmentLapMessage data message's activeTime field's current value.
Returns
the activeTime field value.
Definition at line 734 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->activeTime;
 }
Referenced by setActiveTime().
avgAltitude()
quint16 SegmentLapMessage::avgAltitude () const
Returns the SegmentLapMessage data message's avgAltitude field's current value.
Returns
the avgAltitude field value.
Definition at line 492 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgAltitude;
 }
Referenced by setAvgAltitude().
avgCadence()
quint8 SegmentLapMessage::avgCadence () const
Returns the SegmentLapMessage data message's avgCadence field's current value.
total_cycles / total_timer_time if non_zero_avg_cadence otherwise total_cycles / total_elapsed_time
Returns
the avgCadence field value.
Definition at line 294 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgCadence;
 }
Referenced by setAvgCadence().
avgCadencePosition()
quint8 SegmentLapMessage::avgCadencePosition () const
Returns the SegmentLapMessage data message's avgCadencePosition field's current value.
Average cadence by position. Data value indexes defined by rider_position_type.
Returns
the avgCadencePosition field value.
Definition at line 1037 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgCadencePosition;
 }
Referenced by setAvgCadencePosition().
avgCombinedPedalSmoothness()
quint8 SegmentLapMessage::avgCombinedPedalSmoothness () const
Returns the SegmentLapMessage data message's avgCombinedPedalSmoothness field's current value.
Returns
the avgCombinedPedalSmoothness field value.
Definition at line 811 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgCombinedPedalSmoothness;
 }
Referenced by setAvgCombinedPedalSmoothness().
avgFlow()
float SegmentLapMessage::avgFlow () const
Returns the SegmentLapMessage data message's avgFlow field's current value.
The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.
Returns
the avgFlow field value.
Definition at line 1119 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgFlow;
 }
Referenced by setAvgFlow().
avgFractionalCadence()
quint8 SegmentLapMessage::avgFractionalCadence () const
Returns the SegmentLapMessage data message's avgFractionalCadence field's current value.
fractional part of the avg_cadence
Returns
the avgFractionalCadence field value.
Definition at line 846 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgFractionalCadence;
 }
Referenced by setAvgFractionalCadence().
avgGrade()
qint16 SegmentLapMessage::avgGrade () const
Returns the SegmentLapMessage data message's avgGrade field's current value.
Returns
the avgGrade field value.
Definition at line 525 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgGrade;
 }
Referenced by setAvgGrade().
avgGrit()
float SegmentLapMessage::avgGrit () const
Returns the SegmentLapMessage data message's avgGrit field's current value.
The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.
Returns
the avgGrit field value.
Definition at line 1105 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgGrit;
 }
Referenced by setAvgGrit().
avgHeartRate()
quint8 SegmentLapMessage::avgHeartRate () const
Returns the SegmentLapMessage data message's avgHeartRate field's current value.
Returns
the avgHeartRate field value.
Definition at line 269 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgHeartRate;
 }
Referenced by setAvgHeartRate().
avgLeftPco()
qint8 SegmentLapMessage::avgLeftPco () const
Returns the SegmentLapMessage data message's avgLeftPco field's current value.
Average left platform center offset
Returns
the avgLeftPco field value.
Definition at line 933 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgLeftPco;
 }
Referenced by setAvgLeftPco().
avgLeftPedalSmoothness()
quint8 SegmentLapMessage::avgLeftPedalSmoothness () const
Returns the SegmentLapMessage data message's avgLeftPedalSmoothness field's current value.
Returns
the avgLeftPedalSmoothness field value.
Definition at line 789 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgLeftPedalSmoothness;
 }
Referenced by setAvgLeftPedalSmoothness().
avgLeftPowerPhase()
quint8 SegmentLapMessage::avgLeftPowerPhase () const
Returns the SegmentLapMessage data message's avgLeftPowerPhase field's current value.
Average left power phase angles. Data value indexes defined by power_phase_type.
Returns
the avgLeftPowerPhase field value.
Definition at line 959 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgLeftPowerPhase;
 }
Referenced by setAvgLeftPowerPhase().
avgLeftPowerPhasePeak()
quint8 SegmentLapMessage::avgLeftPowerPhasePeak () const
Returns the SegmentLapMessage data message's avgLeftPowerPhasePeak field's current value.
Average left power phase peak angles. Data value indexes defined by power_phase_type.
Returns
the avgLeftPowerPhasePeak field value.
Definition at line 972 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgLeftPowerPhasePeak;
 }
Referenced by setAvgLeftPowerPhasePeak().
avgLeftTorqueEffectiveness()
quint8 SegmentLapMessage::avgLeftTorqueEffectiveness () const
Returns the SegmentLapMessage data message's avgLeftTorqueEffectiveness field's current value.
Returns
the avgLeftTorqueEffectiveness field value.
Definition at line 767 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgLeftTorqueEffectiveness;
 }
Referenced by setAvgLeftTorqueEffectiveness().
avgNegGrade()
qint16 SegmentLapMessage::avgNegGrade () const
Returns the SegmentLapMessage data message's avgNegGrade field's current value.
Returns
the avgNegGrade field value.
Definition at line 547 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgNegGrade;
 }
Referenced by setAvgNegGrade().
avgNegVerticalSpeed()
qint16 SegmentLapMessage::avgNegVerticalSpeed () const
Returns the SegmentLapMessage data message's avgNegVerticalSpeed field's current value.
Returns
the avgNegVerticalSpeed field value.
Definition at line 624 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgNegVerticalSpeed;
 }
Referenced by setAvgNegVerticalSpeed().
avgPosGrade()
qint16 SegmentLapMessage::avgPosGrade () const
Returns the SegmentLapMessage data message's avgPosGrade field's current value.
Returns
the avgPosGrade field value.
Definition at line 536 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgPosGrade;
 }
Referenced by setAvgPosGrade().
avgPosVerticalSpeed()
qint16 SegmentLapMessage::avgPosVerticalSpeed () const
Returns the SegmentLapMessage data message's avgPosVerticalSpeed field's current value.
Returns
the avgPosVerticalSpeed field value.
Definition at line 613 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgPosVerticalSpeed;
 }
Referenced by setAvgPosVerticalSpeed().
avgPower()
quint16 SegmentLapMessage::avgPower () const
Returns the SegmentLapMessage data message's avgPower field's current value.
total_power / total_timer_time if non_zero_avg_power otherwise total_power / total_elapsed_time
Returns
the avgPower field value.
Definition at line 319 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgPower;
 }
Referenced by setAvgPower().
avgPowerPosition()
quint16 SegmentLapMessage::avgPowerPosition () const
Returns the SegmentLapMessage data message's avgPowerPosition field's current value.
Average power by position. Data value indexes defined by rider_position_type.
Returns
the avgPowerPosition field value.
Definition at line 1011 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgPowerPosition;
 }
Referenced by setAvgPowerPosition().
avgRightPco()
qint8 SegmentLapMessage::avgRightPco () const
Returns the SegmentLapMessage data message's avgRightPco field's current value.
Average right platform center offset
Returns
the avgRightPco field value.
Definition at line 946 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgRightPco;
 }
Referenced by setAvgRightPco().
avgRightPedalSmoothness()
quint8 SegmentLapMessage::avgRightPedalSmoothness () const
Returns the SegmentLapMessage data message's avgRightPedalSmoothness field's current value.
Returns
the avgRightPedalSmoothness field value.
Definition at line 800 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgRightPedalSmoothness;
 }
Referenced by setAvgRightPedalSmoothness().
avgRightPowerPhase()
quint8 SegmentLapMessage::avgRightPowerPhase () const
Returns the SegmentLapMessage data message's avgRightPowerPhase field's current value.
Average right power phase angles. Data value indexes defined by power_phase_type.
Returns
the avgRightPowerPhase field value.
Definition at line 985 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgRightPowerPhase;
 }
Referenced by setAvgRightPowerPhase().
avgRightPowerPhasePeak()
quint8 SegmentLapMessage::avgRightPowerPhasePeak () const
Returns the SegmentLapMessage data message's avgRightPowerPhasePeak field's current value.
Average right power phase peak angles. Data value indexes defined by power_phase_type.
Returns
the avgRightPowerPhasePeak field value.
Definition at line 998 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgRightPowerPhasePeak;
 }
Referenced by setAvgRightPowerPhasePeak().
avgRightTorqueEffectiveness()
quint8 SegmentLapMessage::avgRightTorqueEffectiveness () const
Returns the SegmentLapMessage data message's avgRightTorqueEffectiveness field's current value.
Returns
the avgRightTorqueEffectiveness field value.
Definition at line 778 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgRightTorqueEffectiveness;
 }
Referenced by setAvgRightTorqueEffectiveness().
avgSpeed()
quint16 SegmentLapMessage::avgSpeed () const
Returns the SegmentLapMessage data message's avgSpeed field's current value.
Returns
the avgSpeed field value.
Definition at line 247 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgSpeed;
 }
Referenced by setAvgSpeed().
avgTemperature()
qint8 SegmentLapMessage::avgTemperature () const
Returns the SegmentLapMessage data message's avgTemperature field's current value.
Returns
the avgTemperature field value.
Definition at line 580 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->avgTemperature;
 }
Referenced by setAvgTemperature().
endPositionLat()
qint32 SegmentLapMessage::endPositionLat () const
Returns the SegmentLapMessage data message's endPositionLat field's current value.
Returns
the endPositionLat field value.
Definition at line 153 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->endPositionLat;
 }
Referenced by setEndPositionLat().
endPositionLong()
qint32 SegmentLapMessage::endPositionLong () const
Returns the SegmentLapMessage data message's endPositionLong field's current value.
Returns
the endPositionLong field value.
Definition at line 164 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->endPositionLong;
 }
Referenced by setEndPositionLong().
event()
Event SegmentLapMessage::event () const
Returns the SegmentLapMessage data message's event field's current value.
Returns
the event field value.
Definition at line 98 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->event;
 }
Referenced by setEvent().
eventGroup()
quint8 SegmentLapMessage::eventGroup () const
Returns the SegmentLapMessage data message's eventGroup field's current value.
Returns
the eventGroup field value.
Definition at line 374 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->eventGroup;
 }
Referenced by setEventGroup().
eventType()
EventType SegmentLapMessage::eventType () const
Returns the SegmentLapMessage data message's eventType field's current value.
Returns
the eventType field value.
Definition at line 109 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->eventType;
 }
Referenced by setEventType().
frontGearShiftCount()
quint16 SegmentLapMessage::frontGearShiftCount () const
Returns the SegmentLapMessage data message's frontGearShiftCount field's current value.
Returns
the frontGearShiftCount field value.
Definition at line 883 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->frontGearShiftCount;
 }
Referenced by setFrontGearShiftCount().
gpsAccuracy()
quint8 SegmentLapMessage::gpsAccuracy () const
Returns the SegmentLapMessage data message's gpsAccuracy field's current value.
Returns
the gpsAccuracy field value.
Definition at line 514 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->gpsAccuracy;
 }
Referenced by setGpsAccuracy().
leftRightBalance()
LeftRightBalance100 SegmentLapMessage::leftRightBalance () const
Returns the SegmentLapMessage data message's leftRightBalance field's current value.
Returns
the leftRightBalance field value.
Definition at line 459 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->leftRightBalance;
 }
Referenced by setLeftRightBalance().
manufacturer()
Manufacturer SegmentLapMessage::manufacturer () const
Returns the SegmentLapMessage data message's manufacturer field's current value.
Manufacturer that produced the segment
Returns
the manufacturer field value.
Definition at line 1063 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->manufacturer;
 }
Referenced by setManufacturer().
maxAltitude()
quint16 SegmentLapMessage::maxAltitude () const
Returns the SegmentLapMessage data message's maxAltitude field's current value.
Returns
the maxAltitude field value.
Definition at line 503 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->maxAltitude;
 }
Referenced by setMaxAltitude().
maxCadence()
quint8 SegmentLapMessage::maxCadence () const
Returns the SegmentLapMessage data message's maxCadence field's current value.
Returns
the maxCadence field value.
Definition at line 305 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->maxCadence;
 }
Referenced by setMaxCadence().
maxCadencePosition()
quint8 SegmentLapMessage::maxCadencePosition () const
Returns the SegmentLapMessage data message's maxCadencePosition field's current value.
Maximum cadence by position. Data value indexes defined by rider_position_type.
Returns
the maxCadencePosition field value.
Definition at line 1050 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->maxCadencePosition;
 }
Referenced by setMaxCadencePosition().
maxFractionalCadence()
quint8 SegmentLapMessage::maxFractionalCadence () const
Returns the SegmentLapMessage data message's maxFractionalCadence field's current value.
fractional part of the max_cadence
Returns
the maxFractionalCadence field value.
Definition at line 859 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->maxFractionalCadence;
 }
Referenced by setMaxFractionalCadence().
maxHeartRate()
quint8 SegmentLapMessage::maxHeartRate () const
Returns the SegmentLapMessage data message's maxHeartRate field's current value.
Returns
the maxHeartRate field value.
Definition at line 280 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->maxHeartRate;
 }
Referenced by setMaxHeartRate().
maxNegGrade()
qint16 SegmentLapMessage::maxNegGrade () const
Returns the SegmentLapMessage data message's maxNegGrade field's current value.
Returns
the maxNegGrade field value.
Definition at line 569 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->maxNegGrade;
 }
Referenced by setMaxNegGrade().
maxNegVerticalSpeed()
qint16 SegmentLapMessage::maxNegVerticalSpeed () const
Returns the SegmentLapMessage data message's maxNegVerticalSpeed field's current value.
Returns
the maxNegVerticalSpeed field value.
Definition at line 646 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->maxNegVerticalSpeed;
 }
Referenced by setMaxNegVerticalSpeed().
maxPosGrade()
qint16 SegmentLapMessage::maxPosGrade () const
Returns the SegmentLapMessage data message's maxPosGrade field's current value.
Returns
the maxPosGrade field value.
Definition at line 558 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->maxPosGrade;
 }
Referenced by setMaxPosGrade().
maxPosVerticalSpeed()
qint16 SegmentLapMessage::maxPosVerticalSpeed () const
Returns the SegmentLapMessage data message's maxPosVerticalSpeed field's current value.
Returns
the maxPosVerticalSpeed field value.
Definition at line 635 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->maxPosVerticalSpeed;
 }
Referenced by setMaxPosVerticalSpeed().
maxPower()
quint16 SegmentLapMessage::maxPower () const
Returns the SegmentLapMessage data message's maxPower field's current value.
Returns
the maxPower field value.
Definition at line 330 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->maxPower;
 }
Referenced by setMaxPower().
maxPowerPosition()
quint16 SegmentLapMessage::maxPowerPosition () const
Returns the SegmentLapMessage data message's maxPowerPosition field's current value.
Maximum power by position. Data value indexes defined by rider_position_type.
Returns
the maxPowerPosition field value.
Definition at line 1024 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->maxPowerPosition;
 }
Referenced by setMaxPowerPosition().
maxSpeed()
quint16 SegmentLapMessage::maxSpeed () const
Returns the SegmentLapMessage data message's maxSpeed field's current value.
Returns
the maxSpeed field value.
Definition at line 258 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->maxSpeed;
 }
Referenced by setMaxSpeed().
maxTemperature()
qint8 SegmentLapMessage::maxTemperature () const
Returns the SegmentLapMessage data message's maxTemperature field's current value.
Returns
the maxTemperature field value.
Definition at line 591 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->maxTemperature;
 }
Referenced by setMaxTemperature().
messageIndex()
MessageIndex SegmentLapMessage::messageIndex () const
Returns the SegmentLapMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 74 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
minAltitude()
quint16 SegmentLapMessage::minAltitude () const
Returns the SegmentLapMessage data message's minAltitude field's current value.
Returns
the minAltitude field value.
Definition at line 712 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->minAltitude;
 }
Referenced by setMinAltitude().
minHeartRate()
quint8 SegmentLapMessage::minHeartRate () const
Returns the SegmentLapMessage data message's minHeartRate field's current value.
Returns
the minHeartRate field value.
Definition at line 723 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->minHeartRate;
 }
Referenced by setMinHeartRate().
name()
QString SegmentLapMessage::name () const
Returns the SegmentLapMessage data message's name field's current value.
Returns
the name field value.
Definition at line 437 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->name;
 }
Referenced by setName().
necLat()
qint32 SegmentLapMessage::necLat () const
Returns the SegmentLapMessage data message's necLat field's current value.
North east corner latitude.
Returns
the necLat field value.
Definition at line 387 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->necLat;
 }
Referenced by setNecLat().
necLong()
qint32 SegmentLapMessage::necLong () const
Returns the SegmentLapMessage data message's necLong field's current value.
North east corner longitude.
Returns
the necLong field value.
Definition at line 400 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->necLong;
 }
Referenced by setNecLong().
normalizedPower()
quint16 SegmentLapMessage::normalizedPower () const
Returns the SegmentLapMessage data message's normalizedPower field's current value.
Returns
the normalizedPower field value.
Definition at line 448 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->normalizedPower;
 }
Referenced by setNormalizedPower().
rearGearShiftCount()
quint16 SegmentLapMessage::rearGearShiftCount () const
Returns the SegmentLapMessage data message's rearGearShiftCount field's current value.
Returns
the rearGearShiftCount field value.
Definition at line 894 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->rearGearShiftCount;
 }
Referenced by setRearGearShiftCount().
repetitionNum()
quint16 SegmentLapMessage::repetitionNum () const
Returns the SegmentLapMessage data message's repetitionNum field's current value.
Returns
the repetitionNum field value.
Definition at line 701 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->repetitionNum;
 }
Referenced by setRepetitionNum().
setActiveTime()
void SegmentLapMessage::setActiveTime (const quint32 activeTime)
Sets the activeTime field to activeTime.
Parameters
activeTime The field value to set.
Definition at line 1736 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->activeTime = activeTime;
 }
References activeTime().
setAvgAltitude()
void SegmentLapMessage::setAvgAltitude (const quint16 avgAltitude)
Sets the avgAltitude field to avgAltitude.
Parameters
avgAltitude The field value to set.
Definition at line 1516 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgAltitude = avgAltitude;
 }
References avgAltitude().
setAvgCadence()
void SegmentLapMessage::setAvgCadence (const quint8 avgCadence)
Sets the avgCadence field to avgCadence.
Parameters
avgCadence The field value to set.
Definition at line 1346 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgCadence = avgCadence;
 }
References avgCadence().
setAvgCadencePosition()
void SegmentLapMessage::setAvgCadencePosition (const quint8 avgCadencePosition)
Sets the avgCadencePosition field to avgCadencePosition.
Parameters
avgCadencePosition The field value to set.
Definition at line 1986 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgCadencePosition = avgCadencePosition;
 }
References avgCadencePosition().
setAvgCombinedPedalSmoothness()
void SegmentLapMessage::setAvgCombinedPedalSmoothness (const quint8 avgCombinedPedalSmoothness)
Sets the avgCombinedPedalSmoothness field to avgCombinedPedalSmoothness.
Parameters
avgCombinedPedalSmoothness The field value to set.
Definition at line 1806 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgCombinedPedalSmoothness = avgCombinedPedalSmoothness;
 }
References avgCombinedPedalSmoothness().
setAvgFlow()
void SegmentLapMessage::setAvgFlow (const float avgFlow)
Sets the avgFlow field to avgFlow.
Parameters
avgFlow The field value to set.
Definition at line 2046 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgFlow = avgFlow;
 }
References avgFlow().
setAvgFractionalCadence()
void SegmentLapMessage::setAvgFractionalCadence (const quint8 avgFractionalCadence)
Sets the avgFractionalCadence field to avgFractionalCadence.
Parameters
avgFractionalCadence The field value to set.
Definition at line 1836 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgFractionalCadence = avgFractionalCadence;
 }
References avgFractionalCadence().
setAvgGrade()
void SegmentLapMessage::setAvgGrade (const qint16 avgGrade)
Sets the avgGrade field to avgGrade.
Parameters
avgGrade The field value to set.
Definition at line 1546 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgGrade = avgGrade;
 }
References avgGrade().
setAvgGrit()
void SegmentLapMessage::setAvgGrit (const float avgGrit)
Sets the avgGrit field to avgGrit.
Parameters
avgGrit The field value to set.
Definition at line 2036 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgGrit = avgGrit;
 }
References avgGrit().
setAvgHeartRate()
void SegmentLapMessage::setAvgHeartRate (const quint8 avgHeartRate)
Sets the avgHeartRate field to avgHeartRate.
Parameters
avgHeartRate The field value to set.
Definition at line 1326 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgHeartRate = avgHeartRate;
 }
References avgHeartRate().
setAvgLeftPco()
void SegmentLapMessage::setAvgLeftPco (const qint8 avgLeftPco)
Sets the avgLeftPco field to avgLeftPco.
Parameters
avgLeftPco The field value to set.
Definition at line 1906 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgLeftPco = avgLeftPco;
 }
References avgLeftPco().
setAvgLeftPedalSmoothness()
void SegmentLapMessage::setAvgLeftPedalSmoothness (const quint8 avgLeftPedalSmoothness)
Sets the avgLeftPedalSmoothness field to avgLeftPedalSmoothness.
Parameters
avgLeftPedalSmoothness The field value to set.
Definition at line 1786 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgLeftPedalSmoothness = avgLeftPedalSmoothness;
 }
References avgLeftPedalSmoothness().
setAvgLeftPowerPhase()
void SegmentLapMessage::setAvgLeftPowerPhase (const quint8 avgLeftPowerPhase)
Sets the avgLeftPowerPhase field to avgLeftPowerPhase.
Parameters
avgLeftPowerPhase The field value to set.
Definition at line 1926 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgLeftPowerPhase = avgLeftPowerPhase;
 }
References avgLeftPowerPhase().
setAvgLeftPowerPhasePeak()
void SegmentLapMessage::setAvgLeftPowerPhasePeak (const quint8 avgLeftPowerPhasePeak)
Sets the avgLeftPowerPhasePeak field to avgLeftPowerPhasePeak.
Parameters
avgLeftPowerPhasePeak The field value to set.
Definition at line 1936 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgLeftPowerPhasePeak = avgLeftPowerPhasePeak;
 }
References avgLeftPowerPhasePeak().
setAvgLeftTorqueEffectiveness()
void SegmentLapMessage::setAvgLeftTorqueEffectiveness (const quint8 avgLeftTorqueEffectiveness)
Sets the avgLeftTorqueEffectiveness field to avgLeftTorqueEffectiveness.
Parameters
avgLeftTorqueEffectiveness The field value to set.
Definition at line 1766 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgLeftTorqueEffectiveness = avgLeftTorqueEffectiveness;
 }
References avgLeftTorqueEffectiveness().
setAvgNegGrade()
void SegmentLapMessage::setAvgNegGrade (const qint16 avgNegGrade)
Sets the avgNegGrade field to avgNegGrade.
Parameters
avgNegGrade The field value to set.
Definition at line 1566 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgNegGrade = avgNegGrade;
 }
References avgNegGrade().
setAvgNegVerticalSpeed()
void SegmentLapMessage::setAvgNegVerticalSpeed (const qint16 avgNegVerticalSpeed)
Sets the avgNegVerticalSpeed field to avgNegVerticalSpeed.
Parameters
avgNegVerticalSpeed The field value to set.
Definition at line 1636 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgNegVerticalSpeed = avgNegVerticalSpeed;
 }
References avgNegVerticalSpeed().
setAvgPosGrade()
void SegmentLapMessage::setAvgPosGrade (const qint16 avgPosGrade)
Sets the avgPosGrade field to avgPosGrade.
Parameters
avgPosGrade The field value to set.
Definition at line 1556 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgPosGrade = avgPosGrade;
 }
References avgPosGrade().
setAvgPosVerticalSpeed()
void SegmentLapMessage::setAvgPosVerticalSpeed (const qint16 avgPosVerticalSpeed)
Sets the avgPosVerticalSpeed field to avgPosVerticalSpeed.
Parameters
avgPosVerticalSpeed The field value to set.
Definition at line 1626 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgPosVerticalSpeed = avgPosVerticalSpeed;
 }
References avgPosVerticalSpeed().
setAvgPower()
void SegmentLapMessage::setAvgPower (const quint16 avgPower)
Sets the avgPower field to avgPower.
Parameters
avgPower The field value to set.
Definition at line 1366 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgPower = avgPower;
 }
References avgPower().
setAvgPowerPosition()
void SegmentLapMessage::setAvgPowerPosition (const quint16 avgPowerPosition)
Sets the avgPowerPosition field to avgPowerPosition.
Parameters
avgPowerPosition The field value to set.
Definition at line 1966 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgPowerPosition = avgPowerPosition;
 }
References avgPowerPosition().
setAvgRightPco()
void SegmentLapMessage::setAvgRightPco (const qint8 avgRightPco)
Sets the avgRightPco field to avgRightPco.
Parameters
avgRightPco The field value to set.
Definition at line 1916 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgRightPco = avgRightPco;
 }
References avgRightPco().
setAvgRightPedalSmoothness()
void SegmentLapMessage::setAvgRightPedalSmoothness (const quint8 avgRightPedalSmoothness)
Sets the avgRightPedalSmoothness field to avgRightPedalSmoothness.
Parameters
avgRightPedalSmoothness The field value to set.
Definition at line 1796 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgRightPedalSmoothness = avgRightPedalSmoothness;
 }
References avgRightPedalSmoothness().
setAvgRightPowerPhase()
void SegmentLapMessage::setAvgRightPowerPhase (const quint8 avgRightPowerPhase)
Sets the avgRightPowerPhase field to avgRightPowerPhase.
Parameters
avgRightPowerPhase The field value to set.
Definition at line 1946 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgRightPowerPhase = avgRightPowerPhase;
 }
References avgRightPowerPhase().
setAvgRightPowerPhasePeak()
void SegmentLapMessage::setAvgRightPowerPhasePeak (const quint8 avgRightPowerPhasePeak)
Sets the avgRightPowerPhasePeak field to avgRightPowerPhasePeak.
Parameters
avgRightPowerPhasePeak The field value to set.
Definition at line 1956 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgRightPowerPhasePeak = avgRightPowerPhasePeak;
 }
References avgRightPowerPhasePeak().
setAvgRightTorqueEffectiveness()
void SegmentLapMessage::setAvgRightTorqueEffectiveness (const quint8 avgRightTorqueEffectiveness)
Sets the avgRightTorqueEffectiveness field to avgRightTorqueEffectiveness.
Parameters
avgRightTorqueEffectiveness The field value to set.
Definition at line 1776 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgRightTorqueEffectiveness = avgRightTorqueEffectiveness;
 }
References avgRightTorqueEffectiveness().
setAvgSpeed()
void SegmentLapMessage::setAvgSpeed (const quint16 avgSpeed)
Sets the avgSpeed field to avgSpeed.
Parameters
avgSpeed The field value to set.
Definition at line 1306 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgSpeed = avgSpeed;
 }
References avgSpeed().
setAvgTemperature()
void SegmentLapMessage::setAvgTemperature (const qint8 avgTemperature)
Sets the avgTemperature field to avgTemperature.
Parameters
avgTemperature The field value to set.
Definition at line 1596 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->avgTemperature = avgTemperature;
 }
References avgTemperature().
setEndPositionLat()
void SegmentLapMessage::setEndPositionLat (const qint32 endPositionLat)
Sets the endPositionLat field to endPositionLat.
Parameters
endPositionLat The field value to set.
Definition at line 1226 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->endPositionLat = endPositionLat;
 }
References endPositionLat().
setEndPositionLong()
void SegmentLapMessage::setEndPositionLong (const qint32 endPositionLong)
Sets the endPositionLong field to endPositionLong.
Parameters
endPositionLong The field value to set.
Definition at line 1236 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->endPositionLong = endPositionLong;
 }
References endPositionLong().
setEvent()
void SegmentLapMessage::setEvent (const Event event)
Sets the event field to event.
Parameters
event The field value to set.
Definition at line 1176 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->event = event;
 }
References event().
setEventGroup()
void SegmentLapMessage::setEventGroup (const quint8 eventGroup)
Sets the eventGroup field to eventGroup.
Parameters
eventGroup The field value to set.
Definition at line 1416 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->eventGroup = eventGroup;
 }
References eventGroup().
setEventType()
void SegmentLapMessage::setEventType (const EventType eventType)
Sets the eventType field to eventType.
Parameters
eventType The field value to set.
Definition at line 1186 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->eventType = eventType;
 }
References eventType().
setFrontGearShiftCount()
void SegmentLapMessage::setFrontGearShiftCount (const quint16 frontGearShiftCount)
Sets the frontGearShiftCount field to frontGearShiftCount.
Parameters
frontGearShiftCount The field value to set.
Definition at line 1866 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->frontGearShiftCount = frontGearShiftCount;
 }
References frontGearShiftCount().
setGpsAccuracy()
void SegmentLapMessage::setGpsAccuracy (const quint8 gpsAccuracy)
Sets the gpsAccuracy field to gpsAccuracy.
Parameters
gpsAccuracy The field value to set.
Definition at line 1536 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->gpsAccuracy = gpsAccuracy;
 }
References gpsAccuracy().
setLeftRightBalance()
void SegmentLapMessage::setLeftRightBalance (const LeftRightBalance100 leftRightBalance)
Sets the leftRightBalance field to leftRightBalance.
Parameters
leftRightBalance The field value to set.
Definition at line 1486 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->leftRightBalance = leftRightBalance;
 }
References leftRightBalance().
setManufacturer()
void SegmentLapMessage::setManufacturer (const Manufacturer manufacturer)
Sets the manufacturer field to manufacturer.
Parameters
manufacturer The field value to set.
Definition at line 2006 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->manufacturer = manufacturer;
 }
References manufacturer().
setMaxAltitude()
void SegmentLapMessage::setMaxAltitude (const quint16 maxAltitude)
Sets the maxAltitude field to maxAltitude.
Parameters
maxAltitude The field value to set.
Definition at line 1526 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->maxAltitude = maxAltitude;
 }
References maxAltitude().
setMaxCadence()
void SegmentLapMessage::setMaxCadence (const quint8 maxCadence)
Sets the maxCadence field to maxCadence.
Parameters
maxCadence The field value to set.
Definition at line 1356 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->maxCadence = maxCadence;
 }
References maxCadence().
setMaxCadencePosition()
void SegmentLapMessage::setMaxCadencePosition (const quint8 maxCadencePosition)
Sets the maxCadencePosition field to maxCadencePosition.
Parameters
maxCadencePosition The field value to set.
Definition at line 1996 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->maxCadencePosition = maxCadencePosition;
 }
References maxCadencePosition().
setMaxFractionalCadence()
void SegmentLapMessage::setMaxFractionalCadence (const quint8 maxFractionalCadence)
Sets the maxFractionalCadence field to maxFractionalCadence.
Parameters
maxFractionalCadence The field value to set.
Definition at line 1846 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->maxFractionalCadence = maxFractionalCadence;
 }
References maxFractionalCadence().
setMaxHeartRate()
void SegmentLapMessage::setMaxHeartRate (const quint8 maxHeartRate)
Sets the maxHeartRate field to maxHeartRate.
Parameters
maxHeartRate The field value to set.
Definition at line 1336 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->maxHeartRate = maxHeartRate;
 }
References maxHeartRate().
setMaxNegGrade()
void SegmentLapMessage::setMaxNegGrade (const qint16 maxNegGrade)
Sets the maxNegGrade field to maxNegGrade.
Parameters
maxNegGrade The field value to set.
Definition at line 1586 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->maxNegGrade = maxNegGrade;
 }
References maxNegGrade().
setMaxNegVerticalSpeed()
void SegmentLapMessage::setMaxNegVerticalSpeed (const qint16 maxNegVerticalSpeed)
Sets the maxNegVerticalSpeed field to maxNegVerticalSpeed.
Parameters
maxNegVerticalSpeed The field value to set.
Definition at line 1656 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->maxNegVerticalSpeed = maxNegVerticalSpeed;
 }
References maxNegVerticalSpeed().
setMaxPosGrade()
void SegmentLapMessage::setMaxPosGrade (const qint16 maxPosGrade)
Sets the maxPosGrade field to maxPosGrade.
Parameters
maxPosGrade The field value to set.
Definition at line 1576 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->maxPosGrade = maxPosGrade;
 }
References maxPosGrade().
setMaxPosVerticalSpeed()
void SegmentLapMessage::setMaxPosVerticalSpeed (const qint16 maxPosVerticalSpeed)
Sets the maxPosVerticalSpeed field to maxPosVerticalSpeed.
Parameters
maxPosVerticalSpeed The field value to set.
Definition at line 1646 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->maxPosVerticalSpeed = maxPosVerticalSpeed;
 }
References maxPosVerticalSpeed().
setMaxPower()
void SegmentLapMessage::setMaxPower (const quint16 maxPower)
Sets the maxPower field to maxPower.
Parameters
maxPower The field value to set.
Definition at line 1376 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->maxPower = maxPower;
 }
References maxPower().
setMaxPowerPosition()
void SegmentLapMessage::setMaxPowerPosition (const quint16 maxPowerPosition)
Sets the maxPowerPosition field to maxPowerPosition.
Parameters
maxPowerPosition The field value to set.
Definition at line 1976 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->maxPowerPosition = maxPowerPosition;
 }
References maxPowerPosition().
setMaxSpeed()
void SegmentLapMessage::setMaxSpeed (const quint16 maxSpeed)
Sets the maxSpeed field to maxSpeed.
Parameters
maxSpeed The field value to set.
Definition at line 1316 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->maxSpeed = maxSpeed;
 }
References maxSpeed().
setMaxTemperature()
void SegmentLapMessage::setMaxTemperature (const qint8 maxTemperature)
Sets the maxTemperature field to maxTemperature.
Parameters
maxTemperature The field value to set.
Definition at line 1606 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->maxTemperature = maxTemperature;
 }
References maxTemperature().
setMessageIndex()
void SegmentLapMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 1156 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setMinAltitude()
void SegmentLapMessage::setMinAltitude (const quint16 minAltitude)
Sets the minAltitude field to minAltitude.
Parameters
minAltitude The field value to set.
Definition at line 1716 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->minAltitude = minAltitude;
 }
References minAltitude().
setMinHeartRate()
void SegmentLapMessage::setMinHeartRate (const quint8 minHeartRate)
Sets the minHeartRate field to minHeartRate.
Parameters
minHeartRate The field value to set.
Definition at line 1726 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->minHeartRate = minHeartRate;
 }
References minHeartRate().
setName()
void SegmentLapMessage::setName (const QString name)
Sets the name field to name.
Parameters
name The field value to set.
Definition at line 1466 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->name = name;
 }
References name().
setNecLat()
void SegmentLapMessage::setNecLat (const qint32 necLat)
Sets the necLat field to necLat.
Parameters
necLat The field value to set.
Definition at line 1426 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->necLat = necLat;
 }
References necLat().
setNecLong()
void SegmentLapMessage::setNecLong (const qint32 necLong)
Sets the necLong field to necLong.
Parameters
necLong The field value to set.
Definition at line 1436 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->necLong = necLong;
 }
References necLong().
setNormalizedPower()
void SegmentLapMessage::setNormalizedPower (const quint16 normalizedPower)
Sets the normalizedPower field to normalizedPower.
Parameters
normalizedPower The field value to set.
Definition at line 1476 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->normalizedPower = normalizedPower;
 }
References normalizedPower().
setRearGearShiftCount()
void SegmentLapMessage::setRearGearShiftCount (const quint16 rearGearShiftCount)
Sets the rearGearShiftCount field to rearGearShiftCount.
Parameters
rearGearShiftCount The field value to set.
Definition at line 1876 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->rearGearShiftCount = rearGearShiftCount;
 }
References rearGearShiftCount().
setRepetitionNum()
void SegmentLapMessage::setRepetitionNum (const quint16 repetitionNum)
Sets the repetitionNum field to repetitionNum.
Parameters
repetitionNum The field value to set.
Definition at line 1706 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->repetitionNum = repetitionNum;
 }
References repetitionNum().
setSport()
void SegmentLapMessage::setSport (const Sport sport)
Sets the sport field to sport.
Parameters
sport The field value to set.
Definition at line 1406 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->sport = sport;
 }
References sport().
setSportEvent()
void SegmentLapMessage::setSportEvent (const SportEvent sportEvent)
Sets the sportEvent field to sportEvent.
Parameters
sportEvent The field value to set.
Definition at line 1756 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->sportEvent = sportEvent;
 }
References sportEvent().
setStandCount()
void SegmentLapMessage::setStandCount (const quint16 standCount)
Sets the standCount field to standCount.
Parameters
standCount The field value to set.
Definition at line 1896 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->standCount = standCount;
 }
References standCount().
setStartPositionLat()
void SegmentLapMessage::setStartPositionLat (const qint32 startPositionLat)
Sets the startPositionLat field to startPositionLat.
Parameters
startPositionLat The field value to set.
Definition at line 1206 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->startPositionLat = startPositionLat;
 }
References startPositionLat().
setStartPositionLong()
void SegmentLapMessage::setStartPositionLong (const qint32 startPositionLong)
Sets the startPositionLong field to startPositionLong.
Parameters
startPositionLong The field value to set.
Definition at line 1216 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->startPositionLong = startPositionLong;
 }
References startPositionLong().
setStartTime()
void SegmentLapMessage::setStartTime (const DateTime startTime)
Sets the startTime field to startTime.
Parameters
startTime The field value to set.
Definition at line 1196 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->startTime = startTime;
 }
References startTime().
setStatus()
void SegmentLapMessage::setStatus (const SegmentLapStatus status)
Sets the status field to status.
Parameters
status The field value to set.
Definition at line 1816 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->status = status;
 }
References status().
setSubSport()
void SegmentLapMessage::setSubSport (const SubSport subSport)
Sets the subSport field to subSport.
Parameters
subSport The field value to set.
Definition at line 1496 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->subSport = subSport;
 }
References subSport().
setSwcLat()
void SegmentLapMessage::setSwcLat (const qint32 swcLat)
Sets the swcLat field to swcLat.
Parameters
swcLat The field value to set.
Definition at line 1446 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->swcLat = swcLat;
 }
References swcLat().
setSwcLong()
void SegmentLapMessage::setSwcLong (const qint32 swcLong)
Sets the swcLong field to swcLong.
Parameters
swcLong The field value to set.
Definition at line 1456 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->swcLong = swcLong;
 }
References swcLong().
setTimeInCadenceZone()
void SegmentLapMessage::setTimeInCadenceZone (const quint32 timeInCadenceZone)
Sets the timeInCadenceZone field to timeInCadenceZone.
Parameters
timeInCadenceZone The field value to set.
Definition at line 1686 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->timeInCadenceZone = timeInCadenceZone;
 }
References timeInCadenceZone().
setTimeInHrZone()
void SegmentLapMessage::setTimeInHrZone (const quint32 timeInHrZone)
Sets the timeInHrZone field to timeInHrZone.
Parameters
timeInHrZone The field value to set.
Definition at line 1666 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->timeInHrZone = timeInHrZone;
 }
References timeInHrZone().
setTimeInPowerZone()
void SegmentLapMessage::setTimeInPowerZone (const quint32 timeInPowerZone)
Sets the timeInPowerZone field to timeInPowerZone.
Parameters
timeInPowerZone The field value to set.
Definition at line 1696 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->timeInPowerZone = timeInPowerZone;
 }
References timeInPowerZone().
setTimeInSpeedZone()
void SegmentLapMessage::setTimeInSpeedZone (const quint32 timeInSpeedZone)
Sets the timeInSpeedZone field to timeInSpeedZone.
Parameters
timeInSpeedZone The field value to set.
Definition at line 1676 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->timeInSpeedZone = timeInSpeedZone;
 }
References timeInSpeedZone().
setTimestamp()
void SegmentLapMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 1166 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setTimeStanding()
void SegmentLapMessage::setTimeStanding (const quint32 timeStanding)
Sets the timeStanding field to timeStanding.
Parameters
timeStanding The field value to set.
Definition at line 1886 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->timeStanding = timeStanding;
 }
References timeStanding().
setTotalAscent()
void SegmentLapMessage::setTotalAscent (const quint16 totalAscent)
Sets the totalAscent field to totalAscent.
Parameters
totalAscent The field value to set.
Definition at line 1386 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->totalAscent = totalAscent;
 }
References totalAscent().
setTotalCalories()
void SegmentLapMessage::setTotalCalories (const quint16 totalCalories)
Sets the totalCalories field to totalCalories.
Parameters
totalCalories The field value to set.
Definition at line 1286 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->totalCalories = totalCalories;
 }
References totalCalories().
setTotalCycles()
void SegmentLapMessage::setTotalCycles (const quint32 totalCycles)
Sets the totalCycles field to totalCycles.
Parameters
totalCycles The field value to set.
Definition at line 1276 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->totalCycles = totalCycles;
 }
References totalCycles().
setTotalDescent()
void SegmentLapMessage::setTotalDescent (const quint16 totalDescent)
Sets the totalDescent field to totalDescent.
Parameters
totalDescent The field value to set.
Definition at line 1396 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->totalDescent = totalDescent;
 }
References totalDescent().
setTotalDistance()
void SegmentLapMessage::setTotalDistance (const quint32 totalDistance)
Sets the totalDistance field to totalDistance.
Parameters
totalDistance The field value to set.
Definition at line 1266 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->totalDistance = totalDistance;
 }
References totalDistance().
setTotalElapsedTime()
void SegmentLapMessage::setTotalElapsedTime (const quint32 totalElapsedTime)
Sets the totalElapsedTime field to totalElapsedTime.
Parameters
totalElapsedTime The field value to set.
Definition at line 1246 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->totalElapsedTime = totalElapsedTime;
 }
References totalElapsedTime().
setTotalFatCalories()
void SegmentLapMessage::setTotalFatCalories (const quint16 totalFatCalories)
Sets the totalFatCalories field to totalFatCalories.
Parameters
totalFatCalories The field value to set.
Definition at line 1296 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->totalFatCalories = totalFatCalories;
 }
References totalFatCalories().
setTotalFlow()
void SegmentLapMessage::setTotalFlow (const float totalFlow)
Sets the totalFlow field to totalFlow.
Parameters
totalFlow The field value to set.
Definition at line 2026 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->totalFlow = totalFlow;
 }
References totalFlow().
setTotalFractionalAscent()
void SegmentLapMessage::setTotalFractionalAscent (const quint8 totalFractionalAscent)
Sets the totalFractionalAscent field to totalFractionalAscent.
Parameters
totalFractionalAscent The field value to set.
Definition at line 2056 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->totalFractionalAscent = totalFractionalAscent;
 }
References totalFractionalAscent().
setTotalFractionalCycles()
void SegmentLapMessage::setTotalFractionalCycles (const quint8 totalFractionalCycles)
Sets the totalFractionalCycles field to totalFractionalCycles.
Parameters
totalFractionalCycles The field value to set.
Definition at line 1856 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->totalFractionalCycles = totalFractionalCycles;
 }
References totalFractionalCycles().
setTotalFractionalDescent()
void SegmentLapMessage::setTotalFractionalDescent (const quint8 totalFractionalDescent)
Sets the totalFractionalDescent field to totalFractionalDescent.
Parameters
totalFractionalDescent The field value to set.
Definition at line 2066 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->totalFractionalDescent = totalFractionalDescent;
 }
References totalFractionalDescent().
setTotalGrit()
void SegmentLapMessage::setTotalGrit (const float totalGrit)
Sets the totalGrit field to totalGrit.
Parameters
totalGrit The field value to set.
Definition at line 2016 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->totalGrit = totalGrit;
 }
References totalGrit().
setTotalMovingTime()
void SegmentLapMessage::setTotalMovingTime (const quint32 totalMovingTime)
Sets the totalMovingTime field to totalMovingTime.
Parameters
totalMovingTime The field value to set.
Definition at line 1616 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->totalMovingTime = totalMovingTime;
 }
References totalMovingTime().
setTotalTimerTime()
void SegmentLapMessage::setTotalTimerTime (const quint32 totalTimerTime)
Sets the totalTimerTime field to totalTimerTime.
Parameters
totalTimerTime The field value to set.
Definition at line 1256 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->totalTimerTime = totalTimerTime;
 }
References totalTimerTime().
setTotalWork()
void SegmentLapMessage::setTotalWork (const quint32 totalWork)
Sets the totalWork field to totalWork.
Parameters
totalWork The field value to set.
Definition at line 1506 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->totalWork = totalWork;
 }
References totalWork().
setUuid()
void SegmentLapMessage::setUuid (const QString uuid)
Sets the uuid field to uuid.
Parameters
uuid The field value to set.
Definition at line 1826 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->uuid = uuid;
 }
References uuid().
setWktStepIndex()
void SegmentLapMessage::setWktStepIndex (const MessageIndex wktStepIndex)
Sets the wktStepIndex field to wktStepIndex.
Parameters
wktStepIndex The field value to set.
Definition at line 1746 of file segmentlapmessage.cpp.
 {
     Q_D(SegmentLapMessage);
     d->wktStepIndex = wktStepIndex;
 }
References wktStepIndex().
sport()
Sport SegmentLapMessage::sport () const
Returns the SegmentLapMessage data message's sport field's current value.
Returns
the sport field value.
Definition at line 363 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->sport;
 }
Referenced by setSport().
sportEvent()
SportEvent SegmentLapMessage::sportEvent () const
Returns the SegmentLapMessage data message's sportEvent field's current value.
Returns
the sportEvent field value.
Definition at line 756 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->sportEvent;
 }
Referenced by setSportEvent().
standCount()
quint16 SegmentLapMessage::standCount () const
Returns the SegmentLapMessage data message's standCount field's current value.
Number of transitions to the standing state
Returns
the standCount field value.
Definition at line 920 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->standCount;
 }
Referenced by setStandCount().
startPositionLat()
qint32 SegmentLapMessage::startPositionLat () const
Returns the SegmentLapMessage data message's startPositionLat field's current value.
Returns
the startPositionLat field value.
Definition at line 131 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->startPositionLat;
 }
Referenced by setStartPositionLat().
startPositionLong()
qint32 SegmentLapMessage::startPositionLong () const
Returns the SegmentLapMessage data message's startPositionLong field's current value.
Returns
the startPositionLong field value.
Definition at line 142 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->startPositionLong;
 }
Referenced by setStartPositionLong().
startTime()
DateTime SegmentLapMessage::startTime () const
Returns the SegmentLapMessage data message's startTime field's current value.
Returns
the startTime field value.
Definition at line 120 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->startTime;
 }
Referenced by setStartTime().
status()
SegmentLapStatus SegmentLapMessage::status () const
Returns the SegmentLapMessage data message's status field's current value.
Returns
the status field value.
Definition at line 822 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->status;
 }
Referenced by setStatus().
subSport()
SubSport SegmentLapMessage::subSport () const
Returns the SegmentLapMessage data message's subSport field's current value.
Returns
the subSport field value.
Definition at line 470 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->subSport;
 }
Referenced by setSubSport().
swcLat()
qint32 SegmentLapMessage::swcLat () const
Returns the SegmentLapMessage data message's swcLat field's current value.
South west corner latitude.
Returns
the swcLat field value.
Definition at line 413 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->swcLat;
 }
Referenced by setSwcLat().
swcLong()
qint32 SegmentLapMessage::swcLong () const
Returns the SegmentLapMessage data message's swcLong field's current value.
South west corner latitude.
Returns
the swcLong field value.
Definition at line 426 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->swcLong;
 }
Referenced by setSwcLong().
timeInCadenceZone()
quint32 SegmentLapMessage::timeInCadenceZone () const
Returns the SegmentLapMessage data message's timeInCadenceZone field's current value.
Returns
the timeInCadenceZone field value.
Definition at line 679 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->timeInCadenceZone;
 }
Referenced by setTimeInCadenceZone().
timeInHrZone()
quint32 SegmentLapMessage::timeInHrZone () const
Returns the SegmentLapMessage data message's timeInHrZone field's current value.
Returns
the timeInHrZone field value.
Definition at line 657 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->timeInHrZone;
 }
Referenced by setTimeInHrZone().
timeInPowerZone()
quint32 SegmentLapMessage::timeInPowerZone () const
Returns the SegmentLapMessage data message's timeInPowerZone field's current value.
Returns
the timeInPowerZone field value.
Definition at line 690 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->timeInPowerZone;
 }
Referenced by setTimeInPowerZone().
timeInSpeedZone()
quint32 SegmentLapMessage::timeInSpeedZone () const
Returns the SegmentLapMessage data message's timeInSpeedZone field's current value.
Returns
the timeInSpeedZone field value.
Definition at line 668 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->timeInSpeedZone;
 }
Referenced by setTimeInSpeedZone().
timestamp()
DateTime SegmentLapMessage::timestamp () const
Returns the SegmentLapMessage data message's timestamp field's current value.
Lap end time.
Returns
the timestamp field value.
Definition at line 87 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
timeStanding()
quint32 SegmentLapMessage::timeStanding () const
Returns the SegmentLapMessage data message's timeStanding field's current value.
Total time spent in the standing position
Returns
the timeStanding field value.
Definition at line 907 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->timeStanding;
 }
Referenced by setTimeStanding().
totalAscent()
quint16 SegmentLapMessage::totalAscent () const
Returns the SegmentLapMessage data message's totalAscent field's current value.
Returns
the totalAscent field value.
Definition at line 341 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->totalAscent;
 }
Referenced by setTotalAscent().
totalCalories()
quint16 SegmentLapMessage::totalCalories () const
Returns the SegmentLapMessage data message's totalCalories field's current value.
Returns
the totalCalories field value.
Definition at line 223 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->totalCalories;
 }
Referenced by setTotalCalories().
totalCycles()
quint32 SegmentLapMessage::totalCycles () const
Returns the SegmentLapMessage data message's totalCycles field's current value.
Returns
the totalCycles field value.
Definition at line 212 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->totalCycles;
 }
Referenced by setTotalCycles().
totalDescent()
quint16 SegmentLapMessage::totalDescent () const
Returns the SegmentLapMessage data message's totalDescent field's current value.
Returns
the totalDescent field value.
Definition at line 352 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->totalDescent;
 }
Referenced by setTotalDescent().
totalDistance()
quint32 SegmentLapMessage::totalDistance () const
Returns the SegmentLapMessage data message's totalDistance field's current value.
Returns
the totalDistance field value.
Definition at line 201 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->totalDistance;
 }
Referenced by setTotalDistance().
totalElapsedTime()
quint32 SegmentLapMessage::totalElapsedTime () const
Returns the SegmentLapMessage data message's totalElapsedTime field's current value.
Time (includes pauses)
Returns
the totalElapsedTime field value.
Definition at line 177 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->totalElapsedTime;
 }
Referenced by setTotalElapsedTime().
totalFatCalories()
quint16 SegmentLapMessage::totalFatCalories () const
Returns the SegmentLapMessage data message's totalFatCalories field's current value.
If New Leaf
Returns
the totalFatCalories field value.
Definition at line 236 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->totalFatCalories;
 }
Referenced by setTotalFatCalories().
totalFlow()
float SegmentLapMessage::totalFlow () const
Returns the SegmentLapMessage data message's totalFlow field's current value.
The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.
Returns
the totalFlow field value.
Definition at line 1091 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->totalFlow;
 }
Referenced by setTotalFlow().
totalFractionalAscent()
quint8 SegmentLapMessage::totalFractionalAscent () const
Returns the SegmentLapMessage data message's totalFractionalAscent field's current value.
fractional part of total_ascent
Returns
the totalFractionalAscent field value.
Definition at line 1132 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->totalFractionalAscent;
 }
Referenced by setTotalFractionalAscent().
totalFractionalCycles()
quint8 SegmentLapMessage::totalFractionalCycles () const
Returns the SegmentLapMessage data message's totalFractionalCycles field's current value.
fractional part of the total_cycles
Returns
the totalFractionalCycles field value.
Definition at line 872 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->totalFractionalCycles;
 }
Referenced by setTotalFractionalCycles().
totalFractionalDescent()
quint8 SegmentLapMessage::totalFractionalDescent () const
Returns the SegmentLapMessage data message's totalFractionalDescent field's current value.
fractional part of total_descent
Returns
the totalFractionalDescent field value.
Definition at line 1145 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->totalFractionalDescent;
 }
Referenced by setTotalFractionalDescent().
totalGrit()
float SegmentLapMessage::totalGrit () const
Returns the SegmentLapMessage data message's totalGrit field's current value.
The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.
Returns
the totalGrit field value.
Definition at line 1077 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->totalGrit;
 }
Referenced by setTotalGrit().
totalMovingTime()
quint32 SegmentLapMessage::totalMovingTime () const
Returns the SegmentLapMessage data message's totalMovingTime field's current value.
Returns
the totalMovingTime field value.
Definition at line 602 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->totalMovingTime;
 }
Referenced by setTotalMovingTime().
totalTimerTime()
quint32 SegmentLapMessage::totalTimerTime () const
Returns the SegmentLapMessage data message's totalTimerTime field's current value.
Timer Time (excludes pauses)
Returns
the totalTimerTime field value.
Definition at line 190 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->totalTimerTime;
 }
Referenced by setTotalTimerTime().
totalWork()
quint32 SegmentLapMessage::totalWork () const
Returns the SegmentLapMessage data message's totalWork field's current value.
Returns
the totalWork field value.
Definition at line 481 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->totalWork;
 }
Referenced by setTotalWork().
uuid()
QString SegmentLapMessage::uuid () const
Returns the SegmentLapMessage data message's uuid field's current value.
Returns
the uuid field value.
Definition at line 833 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->uuid;
 }
Referenced by setUuid().
wktStepIndex()
MessageIndex SegmentLapMessage::wktStepIndex () const
Returns the SegmentLapMessage data message's wktStepIndex field's current value.
Returns
the wktStepIndex field value.
Definition at line 745 of file segmentlapmessage.cpp.
 {
     Q_D(const SegmentLapMessage);
     return d->wktStepIndex;
 }
Referenced by setWktStepIndex().
The documentation for this class was generated from the following files:
segmentlapmessage.h
segmentlapmessage.cpp