QtFit: OhrSettingsMessage Class Reference
OhrSettingsMessage Class Reference
The OhrSettingsMessage class represents a FIT OhrSettingsMessage data message.
Public Member Functions
OhrSettingsMessage ()
Constructs a OhrSettingsMessage object.
DateTime timestamp () const
Returns the OhrSettingsMessage data message's timestamp field's current value.
Switch enabled () const
Returns the OhrSettingsMessage data message's enabled field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setEnabled (const Switch enabled)
Sets the enabled field to enabled.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
OhrSettingsMessage (OhrSettingsMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The OhrSettingsMessage class represents a FIT OhrSettingsMessage data message.
See also
DataMessage
Definition at line 39 of file ohrsettingsmessage.h.
Constructor & Destructor Documentation
OhrSettingsMessage() [1/2]
OhrSettingsMessage::OhrSettingsMessage ()
Constructs a OhrSettingsMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file ohrsettingsmessage.cpp.
                                        : AbstractDataMessage(new OhrSettingsMessagePrivate(this))
 {
 }
OhrSettingsMessage() [2/2]
OhrSettingsMessage::OhrSettingsMessage (OhrSettingsMessagePrivate *const d) explicit protected
Constructs a OhrSettingsMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file ohrsettingsmessage.cpp.
                                                                           : AbstractDataMessage(d)
 {
 }
Member Function Documentation
enabled()
Switch OhrSettingsMessage::enabled () const
Returns the OhrSettingsMessage data message's enabled field's current value.
Returns
the enabled field value.
Definition at line 85 of file ohrsettingsmessage.cpp.
 {
     Q_D(const OhrSettingsMessage);
     return d->enabled;
 }
Referenced by setEnabled().
setEnabled()
void OhrSettingsMessage::setEnabled (const Switch enabled)
Sets the enabled field to enabled.
Parameters
enabled The field value to set.
Definition at line 106 of file ohrsettingsmessage.cpp.
 {
     Q_D(OhrSettingsMessage);
     d->enabled = enabled;
 }
References enabled().
setTimestamp()
void OhrSettingsMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 96 of file ohrsettingsmessage.cpp.
 {
     Q_D(OhrSettingsMessage);
     d->timestamp = timestamp;
 }
References timestamp().
timestamp()
DateTime OhrSettingsMessage::timestamp () const
Returns the OhrSettingsMessage data message's timestamp field's current value.
Returns
the timestamp field value.
Definition at line 74 of file ohrsettingsmessage.cpp.
 {
     Q_D(const OhrSettingsMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
The documentation for this class was generated from the following files:
ohrsettingsmessage.h
ohrsettingsmessage.cpp