QtFit: BloodPressureMessage Class Reference
BloodPressureMessage Class Reference
The BloodPressureMessage class represents a FIT BloodPressureMessage data message.
Public Member Functions
BloodPressureMessage ()
Constructs a BloodPressureMessage object.
DateTime timestamp () const
Returns the BloodPressureMessage data message's timestamp field's current value.
quint16 systolicPressure () const
Returns the BloodPressureMessage data message's systolicPressure field's current value.
quint16 diastolicPressure () const
Returns the BloodPressureMessage data message's diastolicPressure field's current value.
quint16 meanArterialPressure () const
Returns the BloodPressureMessage data message's meanArterialPressure field's current value.
quint16 map3SampleMean () const
Returns the BloodPressureMessage data message's map3SampleMean field's current value.
quint16 mapMorningValues () const
Returns the BloodPressureMessage data message's mapMorningValues field's current value.
quint16 mapEveningValues () const
Returns the BloodPressureMessage data message's mapEveningValues field's current value.
quint8 heartRate () const
Returns the BloodPressureMessage data message's heartRate field's current value.
HrType heartRateType () const
Returns the BloodPressureMessage data message's heartRateType field's current value.
BpStatus status () const
Returns the BloodPressureMessage data message's status field's current value.
MessageIndex userProfileIndex () const
Returns the BloodPressureMessage data message's userProfileIndex field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setSystolicPressure (const quint16 systolicPressure)
Sets the systolicPressure field to systolicPressure.
void setDiastolicPressure (const quint16 diastolicPressure)
Sets the diastolicPressure field to diastolicPressure.
void setMeanArterialPressure (const quint16 meanArterialPressure)
Sets the meanArterialPressure field to meanArterialPressure.
void setMap3SampleMean (const quint16 map3SampleMean)
Sets the map3SampleMean field to map3SampleMean.
void setMapMorningValues (const quint16 mapMorningValues)
Sets the mapMorningValues field to mapMorningValues.
void setMapEveningValues (const quint16 mapEveningValues)
Sets the mapEveningValues field to mapEveningValues.
void setHeartRate (const quint8 heartRate)
Sets the heartRate field to heartRate.
void setHeartRateType (const HrType heartRateType)
Sets the heartRateType field to heartRateType.
void setStatus (const BpStatus status)
Sets the status field to status.
void setUserProfileIndex (const MessageIndex userProfileIndex)
Sets the userProfileIndex field to userProfileIndex.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
BloodPressureMessage (BloodPressureMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The BloodPressureMessage class represents a FIT BloodPressureMessage data message.
See also
DataMessage
Definition at line 34 of file bloodpressuremessage.h.
Constructor & Destructor Documentation
BloodPressureMessage() [1/2]
BloodPressureMessage::BloodPressureMessage ()
Constructs a BloodPressureMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file bloodpressuremessage.cpp.
                                            : AbstractDataMessage(new BloodPressureMessagePrivate(this))
 {
 }
BloodPressureMessage() [2/2]
BloodPressureMessage::BloodPressureMessage (BloodPressureMessagePrivate *const d) explicit protected
Constructs a BloodPressureMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file bloodpressuremessage.cpp.
                                                                                 : AbstractDataMessage(d)
 {
 }
Member Function Documentation
diastolicPressure()
quint16 BloodPressureMessage::diastolicPressure () const
Returns the BloodPressureMessage data message's diastolicPressure field's current value.
Returns
the diastolicPressure field value.
Definition at line 91 of file bloodpressuremessage.cpp.
 {
     Q_D(const BloodPressureMessage);
     return d->diastolicPressure;
 }
Referenced by setDiastolicPressure().
heartRate()
quint8 BloodPressureMessage::heartRate () const
Returns the BloodPressureMessage data message's heartRate field's current value.
Returns
the heartRate field value.
Definition at line 146 of file bloodpressuremessage.cpp.
 {
     Q_D(const BloodPressureMessage);
     return d->heartRate;
 }
Referenced by setHeartRate().
heartRateType()
HrType BloodPressureMessage::heartRateType () const
Returns the BloodPressureMessage data message's heartRateType field's current value.
Returns
the heartRateType field value.
Definition at line 157 of file bloodpressuremessage.cpp.
 {
     Q_D(const BloodPressureMessage);
     return d->heartRateType;
 }
Referenced by setHeartRateType().
map3SampleMean()
quint16 BloodPressureMessage::map3SampleMean () const
Returns the BloodPressureMessage data message's map3SampleMean field's current value.
Returns
the map3SampleMean field value.
Definition at line 113 of file bloodpressuremessage.cpp.
 {
     Q_D(const BloodPressureMessage);
     return d->map3SampleMean;
 }
Referenced by setMap3SampleMean().
mapEveningValues()
quint16 BloodPressureMessage::mapEveningValues () const
Returns the BloodPressureMessage data message's mapEveningValues field's current value.
Returns
the mapEveningValues field value.
Definition at line 135 of file bloodpressuremessage.cpp.
 {
     Q_D(const BloodPressureMessage);
     return d->mapEveningValues;
 }
Referenced by setMapEveningValues().
mapMorningValues()
quint16 BloodPressureMessage::mapMorningValues () const
Returns the BloodPressureMessage data message's mapMorningValues field's current value.
Returns
the mapMorningValues field value.
Definition at line 124 of file bloodpressuremessage.cpp.
 {
     Q_D(const BloodPressureMessage);
     return d->mapMorningValues;
 }
Referenced by setMapMorningValues().
meanArterialPressure()
quint16 BloodPressureMessage::meanArterialPressure () const
Returns the BloodPressureMessage data message's meanArterialPressure field's current value.
Returns
the meanArterialPressure field value.
Definition at line 102 of file bloodpressuremessage.cpp.
 {
     Q_D(const BloodPressureMessage);
     return d->meanArterialPressure;
 }
Referenced by setMeanArterialPressure().
setDiastolicPressure()
void BloodPressureMessage::setDiastolicPressure (const quint16 diastolicPressure)
Sets the diastolicPressure field to diastolicPressure.
Parameters
diastolicPressure The field value to set.
Definition at line 213 of file bloodpressuremessage.cpp.
 {
     Q_D(BloodPressureMessage);
     d->diastolicPressure = diastolicPressure;
 }
References diastolicPressure().
setHeartRate()
void BloodPressureMessage::setHeartRate (const quint8 heartRate)
Sets the heartRate field to heartRate.
Parameters
heartRate The field value to set.
Definition at line 263 of file bloodpressuremessage.cpp.
 {
     Q_D(BloodPressureMessage);
     d->heartRate = heartRate;
 }
References heartRate().
setHeartRateType()
void BloodPressureMessage::setHeartRateType (const HrType heartRateType)
Sets the heartRateType field to heartRateType.
Parameters
heartRateType The field value to set.
Definition at line 273 of file bloodpressuremessage.cpp.
 {
     Q_D(BloodPressureMessage);
     d->heartRateType = heartRateType;
 }
References heartRateType().
setMap3SampleMean()
void BloodPressureMessage::setMap3SampleMean (const quint16 map3SampleMean)
Sets the map3SampleMean field to map3SampleMean.
Parameters
map3SampleMean The field value to set.
Definition at line 233 of file bloodpressuremessage.cpp.
 {
     Q_D(BloodPressureMessage);
     d->map3SampleMean = map3SampleMean;
 }
References map3SampleMean().
setMapEveningValues()
void BloodPressureMessage::setMapEveningValues (const quint16 mapEveningValues)
Sets the mapEveningValues field to mapEveningValues.
Parameters
mapEveningValues The field value to set.
Definition at line 253 of file bloodpressuremessage.cpp.
 {
     Q_D(BloodPressureMessage);
     d->mapEveningValues = mapEveningValues;
 }
References mapEveningValues().
setMapMorningValues()
void BloodPressureMessage::setMapMorningValues (const quint16 mapMorningValues)
Sets the mapMorningValues field to mapMorningValues.
Parameters
mapMorningValues The field value to set.
Definition at line 243 of file bloodpressuremessage.cpp.
 {
     Q_D(BloodPressureMessage);
     d->mapMorningValues = mapMorningValues;
 }
References mapMorningValues().
setMeanArterialPressure()
void BloodPressureMessage::setMeanArterialPressure (const quint16 meanArterialPressure)
Sets the meanArterialPressure field to meanArterialPressure.
Parameters
meanArterialPressure The field value to set.
Definition at line 223 of file bloodpressuremessage.cpp.
 {
     Q_D(BloodPressureMessage);
     d->meanArterialPressure = meanArterialPressure;
 }
References meanArterialPressure().
setStatus()
void BloodPressureMessage::setStatus (const BpStatus status)
Sets the status field to status.
Parameters
status The field value to set.
Definition at line 283 of file bloodpressuremessage.cpp.
 {
     Q_D(BloodPressureMessage);
     d->status = status;
 }
References status().
setSystolicPressure()
void BloodPressureMessage::setSystolicPressure (const quint16 systolicPressure)
Sets the systolicPressure field to systolicPressure.
Parameters
systolicPressure The field value to set.
Definition at line 203 of file bloodpressuremessage.cpp.
 {
     Q_D(BloodPressureMessage);
     d->systolicPressure = systolicPressure;
 }
References systolicPressure().
setTimestamp()
void BloodPressureMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 193 of file bloodpressuremessage.cpp.
 {
     Q_D(BloodPressureMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setUserProfileIndex()
void BloodPressureMessage::setUserProfileIndex (const MessageIndex userProfileIndex)
Sets the userProfileIndex field to userProfileIndex.
Parameters
userProfileIndex The field value to set.
Definition at line 293 of file bloodpressuremessage.cpp.
 {
     Q_D(BloodPressureMessage);
     d->userProfileIndex = userProfileIndex;
 }
References userProfileIndex().
status()
BpStatus BloodPressureMessage::status () const
Returns the BloodPressureMessage data message's status field's current value.
Returns
the status field value.
Definition at line 168 of file bloodpressuremessage.cpp.
 {
     Q_D(const BloodPressureMessage);
     return d->status;
 }
Referenced by setStatus().
systolicPressure()
quint16 BloodPressureMessage::systolicPressure () const
Returns the BloodPressureMessage data message's systolicPressure field's current value.
Returns
the systolicPressure field value.
Definition at line 80 of file bloodpressuremessage.cpp.
 {
     Q_D(const BloodPressureMessage);
     return d->systolicPressure;
 }
Referenced by setSystolicPressure().
timestamp()
DateTime BloodPressureMessage::timestamp () const
Returns the BloodPressureMessage data message's timestamp field's current value.
Returns
the timestamp field value.
Definition at line 69 of file bloodpressuremessage.cpp.
 {
     Q_D(const BloodPressureMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
userProfileIndex()
MessageIndex BloodPressureMessage::userProfileIndex () const
Returns the BloodPressureMessage data message's userProfileIndex field's current value.
Associates this blood pressure message to a user. This corresponds to the index of the user profile message in the blood pressure file.
Returns
the userProfileIndex field value.
Definition at line 182 of file bloodpressuremessage.cpp.
 {
     Q_D(const BloodPressureMessage);
     return d->userProfileIndex;
 }
Referenced by setUserProfileIndex().
The documentation for this class was generated from the following files:
bloodpressuremessage.h
bloodpressuremessage.cpp