QtFit: DeveloperDataIdMessage Class Reference
DeveloperDataIdMessage Class Reference
The DeveloperDataIdMessage class represents a FIT DeveloperDataIdMessage data message.
#include <developerdataidmessage.h>
Public Member Functions
DeveloperDataIdMessage ()
Constructs an invalid DeveloperDataIdMessage object.
~DeveloperDataIdMessage ()
quint8 developerId () const
Returns the DeveloperDataIdMessage data message's developerId field's current value.
quint8 applicationId () const
Returns the DeveloperDataIdMessage data message's applicationId field's current value.
Manufacturer manufacturerId () const
Returns the DeveloperDataIdMessage data message's manufacturerId field's current value.
quint8 developerDataIndex () const
Returns the DeveloperDataIdMessage data message's developerDataIndex field's current value.
quint32 applicationVersion () const
Returns the DeveloperDataIdMessage data message's applicationVersion field's current value.
void setDeveloperId (const quint8 developerId)
Sets the developerId field to developerId.
void setApplicationId (const quint8 applicationId)
Sets the applicationId field to applicationId.
void setManufacturerId (const Manufacturer manufacturerId)
Sets the manufacturerId field to manufacturerId.
void setDeveloperDataIndex (const quint8 developerDataIndex)
Sets the developerDataIndex field to developerDataIndex.
void setApplicationVersion (const quint32 applicationVersion)
Sets the applicationVersion field to applicationVersion.
Public Member Functions inherited from FitDataMessage
FitDataMessage ()
Constructs a invalid, null FitDataMessage object.
FitDataMessage (const FitDataMessage &other)
Copies a FitDataMessage.
FitDataMessage & operator= (const FitDataMessage &other)
Assigns a FitDataMessage to this one.
~FitDataMessage ()
Destroys the FitDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
bool isNull () const
Returns true if this is not a valid data message, otherwise false.
Additional Inherited Members
Static Public Member Functions inherited from FitDataMessage
static FitDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant FitDataMessage-derived class to parse record according to defn.
Detailed Description
The DeveloperDataIdMessage class represents a FIT DeveloperDataIdMessage data message.
See also
DataMessage
Definition at line 34 of file developerdataidmessage.h.
Constructor & Destructor Documentation
DeveloperDataIdMessage()
DeveloperDataIdMessage::DeveloperDataIdMessage ()
Constructs an invalid DeveloperDataIdMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file developerdataidmessage.cpp.
                                                : FitDataMessage(new DeveloperDataIdMessagePrivate(this))
 {
 }
~DeveloperDataIdMessage()
DeveloperDataIdMessage::~DeveloperDataIdMessage ()
Member Function Documentation
applicationId()
quint8 DeveloperDataIdMessage::applicationId () const
Returns the DeveloperDataIdMessage data message's applicationId field's current value.
Returns
the applicationId field value.
Definition at line 68 of file developerdataidmessage.cpp.
 {
     Q_D(const DeveloperDataIdMessage);
     return d->applicationId;
 }
Referenced by setApplicationId().
applicationVersion()
quint32 DeveloperDataIdMessage::applicationVersion () const
Returns the DeveloperDataIdMessage data message's applicationVersion field's current value.
Returns
the applicationVersion field value.
Definition at line 101 of file developerdataidmessage.cpp.
 {
     Q_D(const DeveloperDataIdMessage);
     return d->applicationVersion;
 }
Referenced by setApplicationVersion().
developerDataIndex()
quint8 DeveloperDataIdMessage::developerDataIndex () const
Returns the DeveloperDataIdMessage data message's developerDataIndex field's current value.
Returns
the developerDataIndex field value.
Definition at line 90 of file developerdataidmessage.cpp.
 {
     Q_D(const DeveloperDataIdMessage);
     return d->developerDataIndex;
 }
Referenced by setDeveloperDataIndex().
developerId()
quint8 DeveloperDataIdMessage::developerId () const
Returns the DeveloperDataIdMessage data message's developerId field's current value.
Returns
the developerId field value.
Definition at line 57 of file developerdataidmessage.cpp.
 {
     Q_D(const DeveloperDataIdMessage);
     return d->developerId;
 }
Referenced by setDeveloperId().
manufacturerId()
Manufacturer DeveloperDataIdMessage::manufacturerId () const
Returns the DeveloperDataIdMessage data message's manufacturerId field's current value.
Returns
the manufacturerId field value.
Definition at line 79 of file developerdataidmessage.cpp.
 {
     Q_D(const DeveloperDataIdMessage);
     return d->manufacturerId;
 }
Referenced by setManufacturerId().
setApplicationId()
void DeveloperDataIdMessage::setApplicationId (const quint8 applicationId)
Sets the applicationId field to applicationId.
Parameters
applicationId The field value to set.
Definition at line 122 of file developerdataidmessage.cpp.
 {
     Q_D(DeveloperDataIdMessage);
     d->applicationId = applicationId;
 }
References applicationId().
setApplicationVersion()
void DeveloperDataIdMessage::setApplicationVersion (const quint32 applicationVersion)
Sets the applicationVersion field to applicationVersion.
Parameters
applicationVersion The field value to set.
Definition at line 152 of file developerdataidmessage.cpp.
 {
     Q_D(DeveloperDataIdMessage);
     d->applicationVersion = applicationVersion;
 }
References applicationVersion().
setDeveloperDataIndex()
void DeveloperDataIdMessage::setDeveloperDataIndex (const quint8 developerDataIndex)
Sets the developerDataIndex field to developerDataIndex.
Parameters
developerDataIndex The field value to set.
Definition at line 142 of file developerdataidmessage.cpp.
 {
     Q_D(DeveloperDataIdMessage);
     d->developerDataIndex = developerDataIndex;
 }
References developerDataIndex().
setDeveloperId()
void DeveloperDataIdMessage::setDeveloperId (const quint8 developerId)
Sets the developerId field to developerId.
Parameters
developerId The field value to set.
Definition at line 112 of file developerdataidmessage.cpp.
 {
     Q_D(DeveloperDataIdMessage);
     d->developerId = developerId;
 }
References developerId().
setManufacturerId()
void DeveloperDataIdMessage::setManufacturerId (const Manufacturer manufacturerId)
Sets the manufacturerId field to manufacturerId.
Parameters
manufacturerId The field value to set.
Definition at line 132 of file developerdataidmessage.cpp.
 {
     Q_D(DeveloperDataIdMessage);
     d->manufacturerId = manufacturerId;
 }
References manufacturerId().
The documentation for this class was generated from the following files:
developerdataidmessage.h
developerdataidmessage.cpp