QtFit: MonitoringMessage Class Reference
MonitoringMessage Class Reference
The MonitoringMessage class represents a FIT MonitoringMessage data message.
Public Member Functions
MonitoringMessage ()
Constructs a MonitoringMessage object.
DateTime timestamp () const
Returns the MonitoringMessage data message's timestamp field's current value.
DeviceIndex deviceIndex () const
Returns the MonitoringMessage data message's deviceIndex field's current value.
quint16 calories () const
Returns the MonitoringMessage data message's calories field's current value.
quint32 distance () const
Returns the MonitoringMessage data message's distance field's current value.
quint32 cycles () const
Returns the MonitoringMessage data message's cycles field's current value.
quint32 activeTime () const
Returns the MonitoringMessage data message's activeTime field's current value.
ActivityType activityType () const
Returns the MonitoringMessage data message's activityType field's current value.
ActivitySubtype activitySubtype () const
Returns the MonitoringMessage data message's activitySubtype field's current value.
ActivityLevel activityLevel () const
Returns the MonitoringMessage data message's activityLevel field's current value.
quint16 distance16 () const
Returns the MonitoringMessage data message's distance16 field's current value.
quint16 cycles16 () const
Returns the MonitoringMessage data message's cycles16 field's current value.
quint16 activeTime16 () const
Returns the MonitoringMessage data message's activeTime16 field's current value.
LocalDateTime localTimestamp () const
Returns the MonitoringMessage data message's localTimestamp field's current value.
qint16 temperature () const
Returns the MonitoringMessage data message's temperature field's current value.
qint16 temperatureMin () const
Returns the MonitoringMessage data message's temperatureMin field's current value.
qint16 temperatureMax () const
Returns the MonitoringMessage data message's temperatureMax field's current value.
quint16 activityTime () const
Returns the MonitoringMessage data message's activityTime field's current value.
quint16 activeCalories () const
Returns the MonitoringMessage data message's activeCalories field's current value.
quint8 currentActivityTypeIntensity () const
Returns the MonitoringMessage data message's currentActivityTypeIntensity field's current value.
quint8 timestampMin8 () const
Returns the MonitoringMessage data message's timestampMin8 field's current value.
quint16 timestamp16 () const
Returns the MonitoringMessage data message's timestamp16 field's current value.
quint8 heartRate () const
Returns the MonitoringMessage data message's heartRate field's current value.
quint8 intensity () const
Returns the MonitoringMessage data message's intensity field's current value.
quint16 durationMin () const
Returns the MonitoringMessage data message's durationMin field's current value.
quint32 duration () const
Returns the MonitoringMessage data message's duration field's current value.
quint32 ascent () const
Returns the MonitoringMessage data message's ascent field's current value.
quint32 descent () const
Returns the MonitoringMessage data message's descent field's current value.
quint16 moderateActivityMinutes () const
Returns the MonitoringMessage data message's moderateActivityMinutes field's current value.
quint16 vigorousActivityMinutes () const
Returns the MonitoringMessage data message's vigorousActivityMinutes field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setDeviceIndex (const DeviceIndex deviceIndex)
Sets the deviceIndex field to deviceIndex.
void setCalories (const quint16 calories)
Sets the calories field to calories.
void setDistance (const quint32 distance)
Sets the distance field to distance.
void setCycles (const quint32 cycles)
Sets the cycles field to cycles.
void setActiveTime (const quint32 activeTime)
Sets the activeTime field to activeTime.
void setActivityType (const ActivityType activityType)
Sets the activityType field to activityType.
void setActivitySubtype (const ActivitySubtype activitySubtype)
Sets the activitySubtype field to activitySubtype.
void setActivityLevel (const ActivityLevel activityLevel)
Sets the activityLevel field to activityLevel.
void setDistance16 (const quint16 distance16)
Sets the distance16 field to distance16.
void setCycles16 (const quint16 cycles16)
Sets the cycles16 field to cycles16.
void setActiveTime16 (const quint16 activeTime16)
Sets the activeTime16 field to activeTime16.
void setLocalTimestamp (const LocalDateTime localTimestamp)
Sets the localTimestamp field to localTimestamp.
void setTemperature (const qint16 temperature)
Sets the temperature field to temperature.
void setTemperatureMin (const qint16 temperatureMin)
Sets the temperatureMin field to temperatureMin.
void setTemperatureMax (const qint16 temperatureMax)
Sets the temperatureMax field to temperatureMax.
void setActivityTime (const quint16 activityTime)
Sets the activityTime field to activityTime.
void setActiveCalories (const quint16 activeCalories)
Sets the activeCalories field to activeCalories.
void setCurrentActivityTypeIntensity (const quint8 currentActivityTypeIntensity)
Sets the currentActivityTypeIntensity field to currentActivityTypeIntensity.
void setTimestampMin8 (const quint8 timestampMin8)
Sets the timestampMin8 field to timestampMin8.
void setTimestamp16 (const quint16 timestamp16)
Sets the timestamp16 field to timestamp16.
void setHeartRate (const quint8 heartRate)
Sets the heartRate field to heartRate.
void setIntensity (const quint8 intensity)
Sets the intensity field to intensity.
void setDurationMin (const quint16 durationMin)
Sets the durationMin field to durationMin.
void setDuration (const quint32 duration)
Sets the duration field to duration.
void setAscent (const quint32 ascent)
Sets the ascent field to ascent.
void setDescent (const quint32 descent)
Sets the descent field to descent.
void setModerateActivityMinutes (const quint16 moderateActivityMinutes)
Sets the moderateActivityMinutes field to moderateActivityMinutes.
void setVigorousActivityMinutes (const quint16 vigorousActivityMinutes)
Sets the vigorousActivityMinutes field to vigorousActivityMinutes.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
MonitoringMessage (MonitoringMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The MonitoringMessage class represents a FIT MonitoringMessage data message.
See also
DataMessage
Definition at line 39 of file monitoringmessage.h.
Constructor & Destructor Documentation
MonitoringMessage() [1/2]
MonitoringMessage::MonitoringMessage ()
Constructs a MonitoringMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file monitoringmessage.cpp.
                                      : AbstractDataMessage(new MonitoringMessagePrivate(this))
 {
 }
MonitoringMessage() [2/2]
MonitoringMessage::MonitoringMessage (MonitoringMessagePrivate *const d) explicit protected
Constructs a MonitoringMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file monitoringmessage.cpp.
                                                                        : AbstractDataMessage(d)
 {
 }
Member Function Documentation
activeCalories()
quint16 MonitoringMessage::activeCalories () const
Returns the MonitoringMessage data message's activeCalories field's current value.
Returns
the activeCalories field value.
Definition at line 285 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->activeCalories;
 }
Referenced by setActiveCalories().
activeTime()
quint32 MonitoringMessage::activeTime () const
Returns the MonitoringMessage data message's activeTime field's current value.
Returns
the activeTime field value.
Definition at line 143 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->activeTime;
 }
Referenced by setActiveTime().
activeTime16()
quint16 MonitoringMessage::activeTime16 () const
Returns the MonitoringMessage data message's activeTime16 field's current value.
Returns
the activeTime16 field value.
Definition at line 209 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->activeTime16;
 }
Referenced by setActiveTime16().
activityLevel()
ActivityLevel MonitoringMessage::activityLevel () const
Returns the MonitoringMessage data message's activityLevel field's current value.
Returns
the activityLevel field value.
Definition at line 176 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->activityLevel;
 }
Referenced by setActivityLevel().
activitySubtype()
ActivitySubtype MonitoringMessage::activitySubtype () const
Returns the MonitoringMessage data message's activitySubtype field's current value.
Returns
the activitySubtype field value.
Definition at line 165 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->activitySubtype;
 }
Referenced by setActivitySubtype().
activityTime()
quint16 MonitoringMessage::activityTime () const
Returns the MonitoringMessage data message's activityTime field's current value.
Indexed using minute_activity_level enum
Returns
the activityTime field value.
Definition at line 274 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->activityTime;
 }
Referenced by setActivityTime().
activityType()
ActivityType MonitoringMessage::activityType () const
Returns the MonitoringMessage data message's activityType field's current value.
Returns
the activityType field value.
Definition at line 154 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->activityType;
 }
Referenced by setActivityType().
ascent()
quint32 MonitoringMessage::ascent () const
Returns the MonitoringMessage data message's ascent field's current value.
Returns
the ascent field value.
Definition at line 375 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->ascent;
 }
Referenced by setAscent().
calories()
quint16 MonitoringMessage::calories () const
Returns the MonitoringMessage data message's calories field's current value.
Accumulated total calories. Maintained by MonitoringReader for each activity_type. See SDK documentation
Returns
the calories field value.
Definition at line 104 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->calories;
 }
Referenced by setCalories().
currentActivityTypeIntensity()
quint8 MonitoringMessage::currentActivityTypeIntensity () const
Returns the MonitoringMessage data message's currentActivityTypeIntensity field's current value.
Indicates single type / intensity for duration since last monitoring message.
Returns
the currentActivityTypeIntensity field value.
Definition at line 298 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->currentActivityTypeIntensity;
 }
Referenced by setCurrentActivityTypeIntensity().
cycles()
quint32 MonitoringMessage::cycles () const
Returns the MonitoringMessage data message's cycles field's current value.
Accumulated cycles. Maintained by MonitoringReader for each activity_type. See SDK documentation.
Returns
the cycles field value.
Definition at line 132 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->cycles;
 }
Referenced by setCycles().
cycles16()
quint16 MonitoringMessage::cycles16 () const
Returns the MonitoringMessage data message's cycles16 field's current value.
Returns
the cycles16 field value.
Definition at line 198 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->cycles16;
 }
Referenced by setCycles16().
descent()
quint32 MonitoringMessage::descent () const
Returns the MonitoringMessage data message's descent field's current value.
Returns
the descent field value.
Definition at line 386 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->descent;
 }
Referenced by setDescent().
deviceIndex()
DeviceIndex MonitoringMessage::deviceIndex () const
Returns the MonitoringMessage data message's deviceIndex field's current value.
Associates this data to device_info message. Not required for file with single device (sensor).
Returns
the deviceIndex field value.
Definition at line 90 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->deviceIndex;
 }
Referenced by setDeviceIndex().
distance()
quint32 MonitoringMessage::distance () const
Returns the MonitoringMessage data message's distance field's current value.
Accumulated distance. Maintained by MonitoringReader for each activity_type. See SDK documentation.
Returns
the distance field value.
Definition at line 118 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->distance;
 }
Referenced by setDistance().
distance16()
quint16 MonitoringMessage::distance16 () const
Returns the MonitoringMessage data message's distance16 field's current value.
Returns
the distance16 field value.
Definition at line 187 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->distance16;
 }
Referenced by setDistance16().
duration()
quint32 MonitoringMessage::duration () const
Returns the MonitoringMessage data message's duration field's current value.
Returns
the duration field value.
Definition at line 364 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->duration;
 }
Referenced by setDuration().
durationMin()
quint16 MonitoringMessage::durationMin () const
Returns the MonitoringMessage data message's durationMin field's current value.
Returns
the durationMin field value.
Definition at line 353 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->durationMin;
 }
Referenced by setDurationMin().
heartRate()
quint8 MonitoringMessage::heartRate () const
Returns the MonitoringMessage data message's heartRate field's current value.
Returns
the heartRate field value.
Definition at line 331 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->heartRate;
 }
Referenced by setHeartRate().
intensity()
quint8 MonitoringMessage::intensity () const
Returns the MonitoringMessage data message's intensity field's current value.
Returns
the intensity field value.
Definition at line 342 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->intensity;
 }
Referenced by setIntensity().
localTimestamp()
LocalDateTime MonitoringMessage::localTimestamp () const
Returns the MonitoringMessage data message's localTimestamp field's current value.
Must align to logging interval, for example, time must be 00:00:00 for daily log.
Returns
the localTimestamp field value.
Definition at line 222 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->localTimestamp;
 }
Referenced by setLocalTimestamp().
moderateActivityMinutes()
quint16 MonitoringMessage::moderateActivityMinutes () const
Returns the MonitoringMessage data message's moderateActivityMinutes field's current value.
Returns
the moderateActivityMinutes field value.
Definition at line 397 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->moderateActivityMinutes;
 }
Referenced by setModerateActivityMinutes().
setActiveCalories()
void MonitoringMessage::setActiveCalories (const quint16 activeCalories)
Sets the activeCalories field to activeCalories.
Parameters
activeCalories The field value to set.
Definition at line 589 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->activeCalories = activeCalories;
 }
References activeCalories().
setActiveTime()
void MonitoringMessage::setActiveTime (const quint32 activeTime)
Sets the activeTime field to activeTime.
Parameters
activeTime The field value to set.
Definition at line 469 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->activeTime = activeTime;
 }
References activeTime().
setActiveTime16()
void MonitoringMessage::setActiveTime16 (const quint16 activeTime16)
Sets the activeTime16 field to activeTime16.
Parameters
activeTime16 The field value to set.
Definition at line 529 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->activeTime16 = activeTime16;
 }
References activeTime16().
setActivityLevel()
void MonitoringMessage::setActivityLevel (const ActivityLevel activityLevel)
Sets the activityLevel field to activityLevel.
Parameters
activityLevel The field value to set.
Definition at line 499 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->activityLevel = activityLevel;
 }
References activityLevel().
setActivitySubtype()
void MonitoringMessage::setActivitySubtype (const ActivitySubtype activitySubtype)
Sets the activitySubtype field to activitySubtype.
Parameters
activitySubtype The field value to set.
Definition at line 489 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->activitySubtype = activitySubtype;
 }
References activitySubtype().
setActivityTime()
void MonitoringMessage::setActivityTime (const quint16 activityTime)
Sets the activityTime field to activityTime.
Parameters
activityTime The field value to set.
Definition at line 579 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->activityTime = activityTime;
 }
References activityTime().
setActivityType()
void MonitoringMessage::setActivityType (const ActivityType activityType)
Sets the activityType field to activityType.
Parameters
activityType The field value to set.
Definition at line 479 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->activityType = activityType;
 }
References activityType().
setAscent()
void MonitoringMessage::setAscent (const quint32 ascent)
Sets the ascent field to ascent.
Parameters
ascent The field value to set.
Definition at line 669 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->ascent = ascent;
 }
References ascent().
setCalories()
void MonitoringMessage::setCalories (const quint16 calories)
Sets the calories field to calories.
Parameters
calories The field value to set.
Definition at line 439 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->calories = calories;
 }
References calories().
setCurrentActivityTypeIntensity()
void MonitoringMessage::setCurrentActivityTypeIntensity (const quint8 currentActivityTypeIntensity)
Sets the currentActivityTypeIntensity field to currentActivityTypeIntensity.
Parameters
currentActivityTypeIntensity The field value to set.
Definition at line 599 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->currentActivityTypeIntensity = currentActivityTypeIntensity;
 }
References currentActivityTypeIntensity().
setCycles()
void MonitoringMessage::setCycles (const quint32 cycles)
Sets the cycles field to cycles.
Parameters
cycles The field value to set.
Definition at line 459 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->cycles = cycles;
 }
References cycles().
setCycles16()
void MonitoringMessage::setCycles16 (const quint16 cycles16)
Sets the cycles16 field to cycles16.
Parameters
cycles16 The field value to set.
Definition at line 519 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->cycles16 = cycles16;
 }
References cycles16().
setDescent()
void MonitoringMessage::setDescent (const quint32 descent)
Sets the descent field to descent.
Parameters
descent The field value to set.
Definition at line 679 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->descent = descent;
 }
References descent().
setDeviceIndex()
void MonitoringMessage::setDeviceIndex (const DeviceIndex deviceIndex)
Sets the deviceIndex field to deviceIndex.
Parameters
deviceIndex The field value to set.
Definition at line 429 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->deviceIndex = deviceIndex;
 }
References deviceIndex().
setDistance()
void MonitoringMessage::setDistance (const quint32 distance)
Sets the distance field to distance.
Parameters
distance The field value to set.
Definition at line 449 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->distance = distance;
 }
References distance().
setDistance16()
void MonitoringMessage::setDistance16 (const quint16 distance16)
Sets the distance16 field to distance16.
Parameters
distance16 The field value to set.
Definition at line 509 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->distance16 = distance16;
 }
References distance16().
setDuration()
void MonitoringMessage::setDuration (const quint32 duration)
Sets the duration field to duration.
Parameters
duration The field value to set.
Definition at line 659 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->duration = duration;
 }
References duration().
setDurationMin()
void MonitoringMessage::setDurationMin (const quint16 durationMin)
Sets the durationMin field to durationMin.
Parameters
durationMin The field value to set.
Definition at line 649 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->durationMin = durationMin;
 }
References durationMin().
setHeartRate()
void MonitoringMessage::setHeartRate (const quint8 heartRate)
Sets the heartRate field to heartRate.
Parameters
heartRate The field value to set.
Definition at line 629 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->heartRate = heartRate;
 }
References heartRate().
setIntensity()
void MonitoringMessage::setIntensity (const quint8 intensity)
Sets the intensity field to intensity.
Parameters
intensity The field value to set.
Definition at line 639 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->intensity = intensity;
 }
References intensity().
setLocalTimestamp()
void MonitoringMessage::setLocalTimestamp (const LocalDateTime localTimestamp)
Sets the localTimestamp field to localTimestamp.
Parameters
localTimestamp The field value to set.
Definition at line 539 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->localTimestamp = localTimestamp;
 }
References localTimestamp().
setModerateActivityMinutes()
void MonitoringMessage::setModerateActivityMinutes (const quint16 moderateActivityMinutes)
Sets the moderateActivityMinutes field to moderateActivityMinutes.
Parameters
moderateActivityMinutes The field value to set.
Definition at line 689 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->moderateActivityMinutes = moderateActivityMinutes;
 }
References moderateActivityMinutes().
setTemperature()
void MonitoringMessage::setTemperature (const qint16 temperature)
Sets the temperature field to temperature.
Parameters
temperature The field value to set.
Definition at line 549 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->temperature = temperature;
 }
References temperature().
setTemperatureMax()
void MonitoringMessage::setTemperatureMax (const qint16 temperatureMax)
Sets the temperatureMax field to temperatureMax.
Parameters
temperatureMax The field value to set.
Definition at line 569 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->temperatureMax = temperatureMax;
 }
References temperatureMax().
setTemperatureMin()
void MonitoringMessage::setTemperatureMin (const qint16 temperatureMin)
Sets the temperatureMin field to temperatureMin.
Parameters
temperatureMin The field value to set.
Definition at line 559 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->temperatureMin = temperatureMin;
 }
References temperatureMin().
setTimestamp()
void MonitoringMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 419 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setTimestamp16()
void MonitoringMessage::setTimestamp16 (const quint16 timestamp16)
Sets the timestamp16 field to timestamp16.
Parameters
timestamp16 The field value to set.
Definition at line 619 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->timestamp16 = timestamp16;
 }
References timestamp16().
setTimestampMin8()
void MonitoringMessage::setTimestampMin8 (const quint8 timestampMin8)
Sets the timestampMin8 field to timestampMin8.
Parameters
timestampMin8 The field value to set.
Definition at line 609 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->timestampMin8 = timestampMin8;
 }
References timestampMin8().
setVigorousActivityMinutes()
void MonitoringMessage::setVigorousActivityMinutes (const quint16 vigorousActivityMinutes)
Sets the vigorousActivityMinutes field to vigorousActivityMinutes.
Parameters
vigorousActivityMinutes The field value to set.
Definition at line 699 of file monitoringmessage.cpp.
 {
     Q_D(MonitoringMessage);
     d->vigorousActivityMinutes = vigorousActivityMinutes;
 }
References vigorousActivityMinutes().
temperature()
qint16 MonitoringMessage::temperature () const
Returns the MonitoringMessage data message's temperature field's current value.
Avg temperature during the logging interval ended at timestamp
Returns
the temperature field value.
Definition at line 235 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->temperature;
 }
Referenced by setTemperature().
temperatureMax()
qint16 MonitoringMessage::temperatureMax () const
Returns the MonitoringMessage data message's temperatureMax field's current value.
Max temperature during the logging interval ended at timestamp
Returns
the temperatureMax field value.
Definition at line 261 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->temperatureMax;
 }
Referenced by setTemperatureMax().
temperatureMin()
qint16 MonitoringMessage::temperatureMin () const
Returns the MonitoringMessage data message's temperatureMin field's current value.
Min temperature during the logging interval ended at timestamp
Returns
the temperatureMin field value.
Definition at line 248 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->temperatureMin;
 }
Referenced by setTemperatureMin().
timestamp()
DateTime MonitoringMessage::timestamp () const
Returns the MonitoringMessage data message's timestamp field's current value.
Must align to logging interval, for example, time must be 00:00:00 for daily log.
Returns
the timestamp field value.
Definition at line 76 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
timestamp16()
quint16 MonitoringMessage::timestamp16 () const
Returns the MonitoringMessage data message's timestamp16 field's current value.
Returns
the timestamp16 field value.
Definition at line 320 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->timestamp16;
 }
Referenced by setTimestamp16().
timestampMin8()
quint8 MonitoringMessage::timestampMin8 () const
Returns the MonitoringMessage data message's timestampMin8 field's current value.
Returns
the timestampMin8 field value.
Definition at line 309 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->timestampMin8;
 }
Referenced by setTimestampMin8().
vigorousActivityMinutes()
quint16 MonitoringMessage::vigorousActivityMinutes () const
Returns the MonitoringMessage data message's vigorousActivityMinutes field's current value.
Returns
the vigorousActivityMinutes field value.
Definition at line 408 of file monitoringmessage.cpp.
 {
     Q_D(const MonitoringMessage);
     return d->vigorousActivityMinutes;
 }
Referenced by setVigorousActivityMinutes().
The documentation for this class was generated from the following files:
monitoringmessage.h
monitoringmessage.cpp