QtFit: DiveSummaryMessage Class Reference
DiveSummaryMessage Class Reference
The DiveSummaryMessage class represents a FIT DiveSummaryMessage data message.
Public Member Functions
DiveSummaryMessage ()
Constructs a DiveSummaryMessage object.
DateTime timestamp () const
Returns the DiveSummaryMessage data message's timestamp field's current value.
MesgNum referenceMesg () const
Returns the DiveSummaryMessage data message's referenceMesg field's current value.
MessageIndex referenceIndex () const
Returns the DiveSummaryMessage data message's referenceIndex field's current value.
quint32 avgDepth () const
Returns the DiveSummaryMessage data message's avgDepth field's current value.
quint32 maxDepth () const
Returns the DiveSummaryMessage data message's maxDepth field's current value.
quint32 surfaceInterval () const
Returns the DiveSummaryMessage data message's surfaceInterval field's current value.
quint8 startCns () const
Returns the DiveSummaryMessage data message's startCns field's current value.
quint8 endCns () const
Returns the DiveSummaryMessage data message's endCns field's current value.
quint16 startN2 () const
Returns the DiveSummaryMessage data message's startN2 field's current value.
quint16 endN2 () const
Returns the DiveSummaryMessage data message's endN2 field's current value.
quint16 o2Toxicity () const
Returns the DiveSummaryMessage data message's o2Toxicity field's current value.
quint32 diveNumber () const
Returns the DiveSummaryMessage data message's diveNumber field's current value.
quint32 bottomTime () const
Returns the DiveSummaryMessage data message's bottomTime field's current value.
qint32 avgAscentRate () const
Returns the DiveSummaryMessage data message's avgAscentRate field's current value.
quint32 avgDescentRate () const
Returns the DiveSummaryMessage data message's avgDescentRate field's current value.
quint32 maxAscentRate () const
Returns the DiveSummaryMessage data message's maxAscentRate field's current value.
quint32 maxDescentRate () const
Returns the DiveSummaryMessage data message's maxDescentRate field's current value.
quint32 hangTime () const
Returns the DiveSummaryMessage data message's hangTime field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setReferenceMesg (const MesgNum referenceMesg)
Sets the referenceMesg field to referenceMesg.
void setReferenceIndex (const MessageIndex referenceIndex)
Sets the referenceIndex field to referenceIndex.
void setAvgDepth (const quint32 avgDepth)
Sets the avgDepth field to avgDepth.
void setMaxDepth (const quint32 maxDepth)
Sets the maxDepth field to maxDepth.
void setSurfaceInterval (const quint32 surfaceInterval)
Sets the surfaceInterval field to surfaceInterval.
void setStartCns (const quint8 startCns)
Sets the startCns field to startCns.
void setEndCns (const quint8 endCns)
Sets the endCns field to endCns.
void setStartN2 (const quint16 startN2)
Sets the startN2 field to startN2.
void setEndN2 (const quint16 endN2)
Sets the endN2 field to endN2.
void setO2Toxicity (const quint16 o2Toxicity)
Sets the o2Toxicity field to o2Toxicity.
void setDiveNumber (const quint32 diveNumber)
Sets the diveNumber field to diveNumber.
void setBottomTime (const quint32 bottomTime)
Sets the bottomTime field to bottomTime.
void setAvgAscentRate (const qint32 avgAscentRate)
Sets the avgAscentRate field to avgAscentRate.
void setAvgDescentRate (const quint32 avgDescentRate)
Sets the avgDescentRate field to avgDescentRate.
void setMaxAscentRate (const quint32 maxAscentRate)
Sets the maxAscentRate field to maxAscentRate.
void setMaxDescentRate (const quint32 maxDescentRate)
Sets the maxDescentRate field to maxDescentRate.
void setHangTime (const quint32 hangTime)
Sets the hangTime field to hangTime.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
DiveSummaryMessage (DiveSummaryMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The DiveSummaryMessage class represents a FIT DiveSummaryMessage data message.
See also
DataMessage
Definition at line 39 of file divesummarymessage.h.
Constructor & Destructor Documentation
DiveSummaryMessage() [1/2]
DiveSummaryMessage::DiveSummaryMessage ()
Constructs a DiveSummaryMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file divesummarymessage.cpp.
                                        : AbstractDataMessage(new DiveSummaryMessagePrivate(this))
 {
 }
DiveSummaryMessage() [2/2]
DiveSummaryMessage::DiveSummaryMessage (DiveSummaryMessagePrivate *const d) explicit protected
Constructs a DiveSummaryMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file divesummarymessage.cpp.
                                                                           : AbstractDataMessage(d)
 {
 }
Member Function Documentation
avgAscentRate()
qint32 DiveSummaryMessage::avgAscentRate () const
Returns the DiveSummaryMessage data message's avgAscentRate field's current value.
Average ascent rate, not including descents or stops
Returns
the avgAscentRate field value.
Definition at line 225 of file divesummarymessage.cpp.
 {
     Q_D(const DiveSummaryMessage);
     return d->avgAscentRate;
 }
Referenced by setAvgAscentRate().
avgDepth()
quint32 DiveSummaryMessage::avgDepth () const
Returns the DiveSummaryMessage data message's avgDepth field's current value.
0 if above water
Returns
the avgDepth field value.
Definition at line 109 of file divesummarymessage.cpp.
 {
     Q_D(const DiveSummaryMessage);
     return d->avgDepth;
 }
Referenced by setAvgDepth().
avgDescentRate()
quint32 DiveSummaryMessage::avgDescentRate () const
Returns the DiveSummaryMessage data message's avgDescentRate field's current value.
Average descent rate, not including ascents or stops
Returns
the avgDescentRate field value.
Definition at line 238 of file divesummarymessage.cpp.
 {
     Q_D(const DiveSummaryMessage);
     return d->avgDescentRate;
 }
Referenced by setAvgDescentRate().
bottomTime()
quint32 DiveSummaryMessage::bottomTime () const
Returns the DiveSummaryMessage data message's bottomTime field's current value.
Returns
the bottomTime field value.
Definition at line 212 of file divesummarymessage.cpp.
 {
     Q_D(const DiveSummaryMessage);
     return d->bottomTime;
 }
Referenced by setBottomTime().
diveNumber()
quint32 DiveSummaryMessage::diveNumber () const
Returns the DiveSummaryMessage data message's diveNumber field's current value.
Returns
the diveNumber field value.
Definition at line 201 of file divesummarymessage.cpp.
 {
     Q_D(const DiveSummaryMessage);
     return d->diveNumber;
 }
Referenced by setDiveNumber().
endCns()
quint8 DiveSummaryMessage::endCns () const
Returns the DiveSummaryMessage data message's endCns field's current value.
Returns
the endCns field value.
Definition at line 157 of file divesummarymessage.cpp.
 {
     Q_D(const DiveSummaryMessage);
     return d->endCns;
 }
Referenced by setEndCns().
endN2()
quint16 DiveSummaryMessage::endN2 () const
Returns the DiveSummaryMessage data message's endN2 field's current value.
Returns
the endN2 field value.
Definition at line 179 of file divesummarymessage.cpp.
 {
     Q_D(const DiveSummaryMessage);
     return d->endN2;
 }
Referenced by setEndN2().
hangTime()
quint32 DiveSummaryMessage::hangTime () const
Returns the DiveSummaryMessage data message's hangTime field's current value.
Time spent neither ascending nor descending
Returns
the hangTime field value.
Definition at line 277 of file divesummarymessage.cpp.
 {
     Q_D(const DiveSummaryMessage);
     return d->hangTime;
 }
Referenced by setHangTime().
maxAscentRate()
quint32 DiveSummaryMessage::maxAscentRate () const
Returns the DiveSummaryMessage data message's maxAscentRate field's current value.
Maximum ascent rate
Returns
the maxAscentRate field value.
Definition at line 251 of file divesummarymessage.cpp.
 {
     Q_D(const DiveSummaryMessage);
     return d->maxAscentRate;
 }
Referenced by setMaxAscentRate().
maxDepth()
quint32 DiveSummaryMessage::maxDepth () const
Returns the DiveSummaryMessage data message's maxDepth field's current value.
0 if above water
Returns
the maxDepth field value.
Definition at line 122 of file divesummarymessage.cpp.
 {
     Q_D(const DiveSummaryMessage);
     return d->maxDepth;
 }
Referenced by setMaxDepth().
maxDescentRate()
quint32 DiveSummaryMessage::maxDescentRate () const
Returns the DiveSummaryMessage data message's maxDescentRate field's current value.
Maximum descent rate
Returns
the maxDescentRate field value.
Definition at line 264 of file divesummarymessage.cpp.
 {
     Q_D(const DiveSummaryMessage);
     return d->maxDescentRate;
 }
Referenced by setMaxDescentRate().
o2Toxicity()
quint16 DiveSummaryMessage::o2Toxicity () const
Returns the DiveSummaryMessage data message's o2Toxicity field's current value.
Returns
the o2Toxicity field value.
Definition at line 190 of file divesummarymessage.cpp.
 {
     Q_D(const DiveSummaryMessage);
     return d->o2Toxicity;
 }
Referenced by setO2Toxicity().
referenceIndex()
MessageIndex DiveSummaryMessage::referenceIndex () const
Returns the DiveSummaryMessage data message's referenceIndex field's current value.
Returns
the referenceIndex field value.
Definition at line 96 of file divesummarymessage.cpp.
 {
     Q_D(const DiveSummaryMessage);
     return d->referenceIndex;
 }
Referenced by setReferenceIndex().
referenceMesg()
MesgNum DiveSummaryMessage::referenceMesg () const
Returns the DiveSummaryMessage data message's referenceMesg field's current value.
Returns
the referenceMesg field value.
Definition at line 85 of file divesummarymessage.cpp.
 {
     Q_D(const DiveSummaryMessage);
     return d->referenceMesg;
 }
Referenced by setReferenceMesg().
setAvgAscentRate()
void DiveSummaryMessage::setAvgAscentRate (const qint32 avgAscentRate)
Sets the avgAscentRate field to avgAscentRate.
Parameters
avgAscentRate The field value to set.
Definition at line 418 of file divesummarymessage.cpp.
 {
     Q_D(DiveSummaryMessage);
     d->avgAscentRate = avgAscentRate;
 }
References avgAscentRate().
setAvgDepth()
void DiveSummaryMessage::setAvgDepth (const quint32 avgDepth)
Sets the avgDepth field to avgDepth.
Parameters
avgDepth The field value to set.
Definition at line 318 of file divesummarymessage.cpp.
 {
     Q_D(DiveSummaryMessage);
     d->avgDepth = avgDepth;
 }
References avgDepth().
setAvgDescentRate()
void DiveSummaryMessage::setAvgDescentRate (const quint32 avgDescentRate)
Sets the avgDescentRate field to avgDescentRate.
Parameters
avgDescentRate The field value to set.
Definition at line 428 of file divesummarymessage.cpp.
 {
     Q_D(DiveSummaryMessage);
     d->avgDescentRate = avgDescentRate;
 }
References avgDescentRate().
setBottomTime()
void DiveSummaryMessage::setBottomTime (const quint32 bottomTime)
Sets the bottomTime field to bottomTime.
Parameters
bottomTime The field value to set.
Definition at line 408 of file divesummarymessage.cpp.
 {
     Q_D(DiveSummaryMessage);
     d->bottomTime = bottomTime;
 }
References bottomTime().
setDiveNumber()
void DiveSummaryMessage::setDiveNumber (const quint32 diveNumber)
Sets the diveNumber field to diveNumber.
Parameters
diveNumber The field value to set.
Definition at line 398 of file divesummarymessage.cpp.
 {
     Q_D(DiveSummaryMessage);
     d->diveNumber = diveNumber;
 }
References diveNumber().
setEndCns()
void DiveSummaryMessage::setEndCns (const quint8 endCns)
Sets the endCns field to endCns.
Parameters
endCns The field value to set.
Definition at line 358 of file divesummarymessage.cpp.
 {
     Q_D(DiveSummaryMessage);
     d->endCns = endCns;
 }
References endCns().
setEndN2()
void DiveSummaryMessage::setEndN2 (const quint16 endN2)
Sets the endN2 field to endN2.
Parameters
endN2 The field value to set.
Definition at line 378 of file divesummarymessage.cpp.
 {
     Q_D(DiveSummaryMessage);
     d->endN2 = endN2;
 }
References endN2().
setHangTime()
void DiveSummaryMessage::setHangTime (const quint32 hangTime)
Sets the hangTime field to hangTime.
Parameters
hangTime The field value to set.
Definition at line 458 of file divesummarymessage.cpp.
 {
     Q_D(DiveSummaryMessage);
     d->hangTime = hangTime;
 }
References hangTime().
setMaxAscentRate()
void DiveSummaryMessage::setMaxAscentRate (const quint32 maxAscentRate)
Sets the maxAscentRate field to maxAscentRate.
Parameters
maxAscentRate The field value to set.
Definition at line 438 of file divesummarymessage.cpp.
 {
     Q_D(DiveSummaryMessage);
     d->maxAscentRate = maxAscentRate;
 }
References maxAscentRate().
setMaxDepth()
void DiveSummaryMessage::setMaxDepth (const quint32 maxDepth)
Sets the maxDepth field to maxDepth.
Parameters
maxDepth The field value to set.
Definition at line 328 of file divesummarymessage.cpp.
 {
     Q_D(DiveSummaryMessage);
     d->maxDepth = maxDepth;
 }
References maxDepth().
setMaxDescentRate()
void DiveSummaryMessage::setMaxDescentRate (const quint32 maxDescentRate)
Sets the maxDescentRate field to maxDescentRate.
Parameters
maxDescentRate The field value to set.
Definition at line 448 of file divesummarymessage.cpp.
 {
     Q_D(DiveSummaryMessage);
     d->maxDescentRate = maxDescentRate;
 }
References maxDescentRate().
setO2Toxicity()
void DiveSummaryMessage::setO2Toxicity (const quint16 o2Toxicity)
Sets the o2Toxicity field to o2Toxicity.
Parameters
o2Toxicity The field value to set.
Definition at line 388 of file divesummarymessage.cpp.
 {
     Q_D(DiveSummaryMessage);
     d->o2Toxicity = o2Toxicity;
 }
References o2Toxicity().
setReferenceIndex()
void DiveSummaryMessage::setReferenceIndex (const MessageIndex referenceIndex)
Sets the referenceIndex field to referenceIndex.
Parameters
referenceIndex The field value to set.
Definition at line 308 of file divesummarymessage.cpp.
 {
     Q_D(DiveSummaryMessage);
     d->referenceIndex = referenceIndex;
 }
References referenceIndex().
setReferenceMesg()
void DiveSummaryMessage::setReferenceMesg (const MesgNum referenceMesg)
Sets the referenceMesg field to referenceMesg.
Parameters
referenceMesg The field value to set.
Definition at line 298 of file divesummarymessage.cpp.
 {
     Q_D(DiveSummaryMessage);
     d->referenceMesg = referenceMesg;
 }
References referenceMesg().
setStartCns()
void DiveSummaryMessage::setStartCns (const quint8 startCns)
Sets the startCns field to startCns.
Parameters
startCns The field value to set.
Definition at line 348 of file divesummarymessage.cpp.
 {
     Q_D(DiveSummaryMessage);
     d->startCns = startCns;
 }
References startCns().
setStartN2()
void DiveSummaryMessage::setStartN2 (const quint16 startN2)
Sets the startN2 field to startN2.
Parameters
startN2 The field value to set.
Definition at line 368 of file divesummarymessage.cpp.
 {
     Q_D(DiveSummaryMessage);
     d->startN2 = startN2;
 }
References startN2().
setSurfaceInterval()
void DiveSummaryMessage::setSurfaceInterval (const quint32 surfaceInterval)
Sets the surfaceInterval field to surfaceInterval.
Parameters
surfaceInterval The field value to set.
Definition at line 338 of file divesummarymessage.cpp.
 {
     Q_D(DiveSummaryMessage);
     d->surfaceInterval = surfaceInterval;
 }
References surfaceInterval().
setTimestamp()
void DiveSummaryMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 288 of file divesummarymessage.cpp.
 {
     Q_D(DiveSummaryMessage);
     d->timestamp = timestamp;
 }
References timestamp().
startCns()
quint8 DiveSummaryMessage::startCns () const
Returns the DiveSummaryMessage data message's startCns field's current value.
Returns
the startCns field value.
Definition at line 146 of file divesummarymessage.cpp.
 {
     Q_D(const DiveSummaryMessage);
     return d->startCns;
 }
Referenced by setStartCns().
startN2()
quint16 DiveSummaryMessage::startN2 () const
Returns the DiveSummaryMessage data message's startN2 field's current value.
Returns
the startN2 field value.
Definition at line 168 of file divesummarymessage.cpp.
 {
     Q_D(const DiveSummaryMessage);
     return d->startN2;
 }
Referenced by setStartN2().
surfaceInterval()
quint32 DiveSummaryMessage::surfaceInterval () const
Returns the DiveSummaryMessage data message's surfaceInterval field's current value.
Time since end of last dive
Returns
the surfaceInterval field value.
Definition at line 135 of file divesummarymessage.cpp.
 {
     Q_D(const DiveSummaryMessage);
     return d->surfaceInterval;
 }
Referenced by setSurfaceInterval().
timestamp()
DateTime DiveSummaryMessage::timestamp () const
Returns the DiveSummaryMessage data message's timestamp field's current value.
Returns
the timestamp field value.
Definition at line 74 of file divesummarymessage.cpp.
 {
     Q_D(const DiveSummaryMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
The documentation for this class was generated from the following files:
divesummarymessage.h
divesummarymessage.cpp