QtFit: FieldCapabilitiesMessage Class Reference
FieldCapabilitiesMessage Class Reference
The FieldCapabilitiesMessage class represents a FIT FieldCapabilitiesMessage data message.
Public Member Functions
FieldCapabilitiesMessage ()
Constructs a FieldCapabilitiesMessage object.
MessageIndex messageIndex () const
Returns the FieldCapabilitiesMessage data message's messageIndex field's current value.
File file () const
Returns the FieldCapabilitiesMessage data message's file field's current value.
MesgNum mesgNum () const
Returns the FieldCapabilitiesMessage data message's mesgNum field's current value.
quint8 fieldNum () const
Returns the FieldCapabilitiesMessage data message's fieldNum field's current value.
quint16 count () const
Returns the FieldCapabilitiesMessage data message's count field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setFile (const File file)
Sets the file field to file.
void setMesgNum (const MesgNum mesgNum)
Sets the mesgNum field to mesgNum.
void setFieldNum (const quint8 fieldNum)
Sets the fieldNum field to fieldNum.
void setCount (const quint16 count)
Sets the count field to count.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
FieldCapabilitiesMessage (FieldCapabilitiesMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The FieldCapabilitiesMessage class represents a FIT FieldCapabilitiesMessage data message.
See also
DataMessage
Definition at line 34 of file fieldcapabilitiesmessage.h.
Constructor & Destructor Documentation
FieldCapabilitiesMessage() [1/2]
FieldCapabilitiesMessage::FieldCapabilitiesMessage ()
Constructs a FieldCapabilitiesMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file fieldcapabilitiesmessage.cpp.
                                                    : AbstractDataMessage(new FieldCapabilitiesMessagePrivate(this))
 {
 }
FieldCapabilitiesMessage() [2/2]
FieldCapabilitiesMessage::FieldCapabilitiesMessage (FieldCapabilitiesMessagePrivate *const d) explicit protected
Constructs a FieldCapabilitiesMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file fieldcapabilitiesmessage.cpp.
                                                                                             : AbstractDataMessage(d)
 {
 }
Member Function Documentation
count()
quint16 FieldCapabilitiesMessage::count () const
Returns the FieldCapabilitiesMessage data message's count field's current value.
Returns
the count field value.
Definition at line 113 of file fieldcapabilitiesmessage.cpp.
 {
     Q_D(const FieldCapabilitiesMessage);
     return d->count;
 }
Referenced by setCount().
fieldNum()
quint8 FieldCapabilitiesMessage::fieldNum () const
Returns the FieldCapabilitiesMessage data message's fieldNum field's current value.
Returns
the fieldNum field value.
Definition at line 102 of file fieldcapabilitiesmessage.cpp.
 {
     Q_D(const FieldCapabilitiesMessage);
     return d->fieldNum;
 }
Referenced by setFieldNum().
file()
File FieldCapabilitiesMessage::file () const
Returns the FieldCapabilitiesMessage data message's file field's current value.
Returns
the file field value.
Definition at line 80 of file fieldcapabilitiesmessage.cpp.
 {
     Q_D(const FieldCapabilitiesMessage);
     return d->file;
 }
Referenced by setFile().
mesgNum()
MesgNum FieldCapabilitiesMessage::mesgNum () const
Returns the FieldCapabilitiesMessage data message's mesgNum field's current value.
Returns
the mesgNum field value.
Definition at line 91 of file fieldcapabilitiesmessage.cpp.
 {
     Q_D(const FieldCapabilitiesMessage);
     return d->mesgNum;
 }
Referenced by setMesgNum().
messageIndex()
MessageIndex FieldCapabilitiesMessage::messageIndex () const
Returns the FieldCapabilitiesMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 69 of file fieldcapabilitiesmessage.cpp.
 {
     Q_D(const FieldCapabilitiesMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
setCount()
void FieldCapabilitiesMessage::setCount (const quint16 count)
Sets the count field to count.
Parameters
count The field value to set.
Definition at line 164 of file fieldcapabilitiesmessage.cpp.
 {
     Q_D(FieldCapabilitiesMessage);
     d->count = count;
 }
References count().
setFieldNum()
void FieldCapabilitiesMessage::setFieldNum (const quint8 fieldNum)
Sets the fieldNum field to fieldNum.
Parameters
fieldNum The field value to set.
Definition at line 154 of file fieldcapabilitiesmessage.cpp.
 {
     Q_D(FieldCapabilitiesMessage);
     d->fieldNum = fieldNum;
 }
References fieldNum().
setFile()
void FieldCapabilitiesMessage::setFile (const File file)
Sets the file field to file.
Parameters
file The field value to set.
Definition at line 134 of file fieldcapabilitiesmessage.cpp.
 {
     Q_D(FieldCapabilitiesMessage);
     d->file = file;
 }
References file().
setMesgNum()
void FieldCapabilitiesMessage::setMesgNum (const MesgNum mesgNum)
Sets the mesgNum field to mesgNum.
Parameters
mesgNum The field value to set.
Definition at line 144 of file fieldcapabilitiesmessage.cpp.
 {
     Q_D(FieldCapabilitiesMessage);
     d->mesgNum = mesgNum;
 }
References mesgNum().
setMessageIndex()
void FieldCapabilitiesMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 124 of file fieldcapabilitiesmessage.cpp.
 {
     Q_D(FieldCapabilitiesMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
The documentation for this class was generated from the following files:
fieldcapabilitiesmessage.h
fieldcapabilitiesmessage.cpp