QtFit: GpsMetadataMessage Class Reference
GpsMetadataMessage Class Reference
The GpsMetadataMessage class represents a FIT GpsMetadataMessage data message.
Public Member Functions
GpsMetadataMessage ()
Constructs a GpsMetadataMessage object.
DateTime timestamp () const
Returns the GpsMetadataMessage data message's timestamp field's current value.
quint16 timestampMs () const
Returns the GpsMetadataMessage data message's timestampMs field's current value.
qint32 positionLat () const
Returns the GpsMetadataMessage data message's positionLat field's current value.
qint32 positionLong () const
Returns the GpsMetadataMessage data message's positionLong field's current value.
quint32 enhancedAltitude () const
Returns the GpsMetadataMessage data message's enhancedAltitude field's current value.
quint32 enhancedSpeed () const
Returns the GpsMetadataMessage data message's enhancedSpeed field's current value.
quint16 heading () const
Returns the GpsMetadataMessage data message's heading field's current value.
DateTime utcTimestamp () const
Returns the GpsMetadataMessage data message's utcTimestamp field's current value.
qint16 velocity () const
Returns the GpsMetadataMessage data message's velocity field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
void setPositionLat (const qint32 positionLat)
Sets the positionLat field to positionLat.
void setPositionLong (const qint32 positionLong)
Sets the positionLong field to positionLong.
void setEnhancedAltitude (const quint32 enhancedAltitude)
Sets the enhancedAltitude field to enhancedAltitude.
void setEnhancedSpeed (const quint32 enhancedSpeed)
Sets the enhancedSpeed field to enhancedSpeed.
void setHeading (const quint16 heading)
Sets the heading field to heading.
void setUtcTimestamp (const DateTime utcTimestamp)
Sets the utcTimestamp field to utcTimestamp.
void setVelocity (const qint16 velocity)
Sets the velocity field to velocity.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
GpsMetadataMessage (GpsMetadataMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The GpsMetadataMessage class represents a FIT GpsMetadataMessage data message.
See also
DataMessage
Definition at line 34 of file gpsmetadatamessage.h.
Constructor & Destructor Documentation
GpsMetadataMessage() [1/2]
GpsMetadataMessage::GpsMetadataMessage ()
Constructs a GpsMetadataMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file gpsmetadatamessage.cpp.
                                        : AbstractDataMessage(new GpsMetadataMessagePrivate(this))
 {
 }
GpsMetadataMessage() [2/2]
GpsMetadataMessage::GpsMetadataMessage (GpsMetadataMessagePrivate *const d) explicit protected
Constructs a GpsMetadataMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file gpsmetadatamessage.cpp.
                                                                           : AbstractDataMessage(d)
 {
 }
Member Function Documentation
enhancedAltitude()
quint32 GpsMetadataMessage::enhancedAltitude () const
Returns the GpsMetadataMessage data message's enhancedAltitude field's current value.
Returns
the enhancedAltitude field value.
Definition at line 117 of file gpsmetadatamessage.cpp.
 {
     Q_D(const GpsMetadataMessage);
     return d->enhancedAltitude;
 }
Referenced by setEnhancedAltitude().
enhancedSpeed()
quint32 GpsMetadataMessage::enhancedSpeed () const
Returns the GpsMetadataMessage data message's enhancedSpeed field's current value.
Returns
the enhancedSpeed field value.
Definition at line 128 of file gpsmetadatamessage.cpp.
 {
     Q_D(const GpsMetadataMessage);
     return d->enhancedSpeed;
 }
Referenced by setEnhancedSpeed().
heading()
quint16 GpsMetadataMessage::heading () const
Returns the GpsMetadataMessage data message's heading field's current value.
Returns
the heading field value.
Definition at line 139 of file gpsmetadatamessage.cpp.
 {
     Q_D(const GpsMetadataMessage);
     return d->heading;
 }
Referenced by setHeading().
positionLat()
qint32 GpsMetadataMessage::positionLat () const
Returns the GpsMetadataMessage data message's positionLat field's current value.
Returns
the positionLat field value.
Definition at line 95 of file gpsmetadatamessage.cpp.
 {
     Q_D(const GpsMetadataMessage);
     return d->positionLat;
 }
Referenced by setPositionLat().
positionLong()
qint32 GpsMetadataMessage::positionLong () const
Returns the GpsMetadataMessage data message's positionLong field's current value.
Returns
the positionLong field value.
Definition at line 106 of file gpsmetadatamessage.cpp.
 {
     Q_D(const GpsMetadataMessage);
     return d->positionLong;
 }
Referenced by setPositionLong().
setEnhancedAltitude()
void GpsMetadataMessage::setEnhancedAltitude (const quint32 enhancedAltitude)
Sets the enhancedAltitude field to enhancedAltitude.
Parameters
enhancedAltitude The field value to set.
Definition at line 217 of file gpsmetadatamessage.cpp.
 {
     Q_D(GpsMetadataMessage);
     d->enhancedAltitude = enhancedAltitude;
 }
References enhancedAltitude().
setEnhancedSpeed()
void GpsMetadataMessage::setEnhancedSpeed (const quint32 enhancedSpeed)
Sets the enhancedSpeed field to enhancedSpeed.
Parameters
enhancedSpeed The field value to set.
Definition at line 227 of file gpsmetadatamessage.cpp.
 {
     Q_D(GpsMetadataMessage);
     d->enhancedSpeed = enhancedSpeed;
 }
References enhancedSpeed().
setHeading()
void GpsMetadataMessage::setHeading (const quint16 heading)
Sets the heading field to heading.
Parameters
heading The field value to set.
Definition at line 237 of file gpsmetadatamessage.cpp.
 {
     Q_D(GpsMetadataMessage);
     d->heading = heading;
 }
References heading().
setPositionLat()
void GpsMetadataMessage::setPositionLat (const qint32 positionLat)
Sets the positionLat field to positionLat.
Parameters
positionLat The field value to set.
Definition at line 197 of file gpsmetadatamessage.cpp.
 {
     Q_D(GpsMetadataMessage);
     d->positionLat = positionLat;
 }
References positionLat().
setPositionLong()
void GpsMetadataMessage::setPositionLong (const qint32 positionLong)
Sets the positionLong field to positionLong.
Parameters
positionLong The field value to set.
Definition at line 207 of file gpsmetadatamessage.cpp.
 {
     Q_D(GpsMetadataMessage);
     d->positionLong = positionLong;
 }
References positionLong().
setTimestamp()
void GpsMetadataMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 177 of file gpsmetadatamessage.cpp.
 {
     Q_D(GpsMetadataMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setTimestampMs()
void GpsMetadataMessage::setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
Parameters
timestampMs The field value to set.
Definition at line 187 of file gpsmetadatamessage.cpp.
 {
     Q_D(GpsMetadataMessage);
     d->timestampMs = timestampMs;
 }
References timestampMs().
setUtcTimestamp()
void GpsMetadataMessage::setUtcTimestamp (const DateTime utcTimestamp)
Sets the utcTimestamp field to utcTimestamp.
Parameters
utcTimestamp The field value to set.
Definition at line 247 of file gpsmetadatamessage.cpp.
 {
     Q_D(GpsMetadataMessage);
     d->utcTimestamp = utcTimestamp;
 }
References utcTimestamp().
setVelocity()
void GpsMetadataMessage::setVelocity (const qint16 velocity)
Sets the velocity field to velocity.
Parameters
velocity The field value to set.
Definition at line 257 of file gpsmetadatamessage.cpp.
 {
     Q_D(GpsMetadataMessage);
     d->velocity = velocity;
 }
References velocity().
timestamp()
DateTime GpsMetadataMessage::timestamp () const
Returns the GpsMetadataMessage data message's timestamp field's current value.
Whole second part of the timestamp.
Returns
the timestamp field value.
Definition at line 71 of file gpsmetadatamessage.cpp.
 {
     Q_D(const GpsMetadataMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
timestampMs()
quint16 GpsMetadataMessage::timestampMs () const
Returns the GpsMetadataMessage data message's timestampMs field's current value.
Millisecond part of the timestamp.
Returns
the timestampMs field value.
Definition at line 84 of file gpsmetadatamessage.cpp.
 {
     Q_D(const GpsMetadataMessage);
     return d->timestampMs;
 }
Referenced by setTimestampMs().
utcTimestamp()
DateTime GpsMetadataMessage::utcTimestamp () const
Returns the GpsMetadataMessage data message's utcTimestamp field's current value.
Used to correlate UTC to system time if the timestamp of the message is in system time. This UTC time is derived from the GPS data.
Returns
the utcTimestamp field value.
Definition at line 153 of file gpsmetadatamessage.cpp.
 {
     Q_D(const GpsMetadataMessage);
     return d->utcTimestamp;
 }
Referenced by setUtcTimestamp().
velocity()
qint16 GpsMetadataMessage::velocity () const
Returns the GpsMetadataMessage data message's velocity field's current value.
velocity[0] is lon velocity. Velocity[1] is lat velocity. Velocity[2] is altitude velocity.
Returns
the velocity field value.
Definition at line 166 of file gpsmetadatamessage.cpp.
 {
     Q_D(const GpsMetadataMessage);
     return d->velocity;
 }
Referenced by setVelocity().
The documentation for this class was generated from the following files:
gpsmetadatamessage.h
gpsmetadatamessage.cpp