QtFit: FieldDescriptionMessage Class Reference
FieldDescriptionMessage Class Reference
The FieldDescriptionMessage class represents a FIT FieldDescriptionMessage data message.
Public Member Functions
FieldDescriptionMessage ()
Constructs a FieldDescriptionMessage object.
quint8 developerDataIndex () const
Returns the FieldDescriptionMessage data message's developerDataIndex field's current value.
quint8 fieldDefinitionNumber () const
Returns the FieldDescriptionMessage data message's fieldDefinitionNumber field's current value.
FitBaseType fitBaseTypeId () const
Returns the FieldDescriptionMessage data message's fitBaseTypeId field's current value.
QString fieldName () const
Returns the FieldDescriptionMessage data message's fieldName field's current value.
quint8 array () const
Returns the FieldDescriptionMessage data message's array field's current value.
QString components () const
Returns the FieldDescriptionMessage data message's components field's current value.
quint8 scale () const
Returns the FieldDescriptionMessage data message's scale field's current value.
qint8 offset () const
Returns the FieldDescriptionMessage data message's offset field's current value.
QString units () const
Returns the FieldDescriptionMessage data message's units field's current value.
QString bits () const
Returns the FieldDescriptionMessage data message's bits field's current value.
QString accumulate () const
Returns the FieldDescriptionMessage data message's accumulate field's current value.
FitBaseUnit fitBaseUnitId () const
Returns the FieldDescriptionMessage data message's fitBaseUnitId field's current value.
MesgNum nativeMesgNum () const
Returns the FieldDescriptionMessage data message's nativeMesgNum field's current value.
quint8 nativeFieldNum () const
Returns the FieldDescriptionMessage data message's nativeFieldNum field's current value.
void setDeveloperDataIndex (const quint8 developerDataIndex)
Sets the developerDataIndex field to developerDataIndex.
void setFieldDefinitionNumber (const quint8 fieldDefinitionNumber)
Sets the fieldDefinitionNumber field to fieldDefinitionNumber.
void setFitBaseTypeId (const FitBaseType fitBaseTypeId)
Sets the fitBaseTypeId field to fitBaseTypeId.
void setFieldName (const QString fieldName)
Sets the fieldName field to fieldName.
void setArray (const quint8 array)
Sets the array field to array.
void setComponents (const QString components)
Sets the components field to components.
void setScale (const quint8 scale)
Sets the scale field to scale.
void setOffset (const qint8 offset)
Sets the offset field to offset.
void setUnits (const QString units)
Sets the units field to units.
void setBits (const QString bits)
Sets the bits field to bits.
void setAccumulate (const QString accumulate)
Sets the accumulate field to accumulate.
void setFitBaseUnitId (const FitBaseUnit fitBaseUnitId)
Sets the fitBaseUnitId field to fitBaseUnitId.
void setNativeMesgNum (const MesgNum nativeMesgNum)
Sets the nativeMesgNum field to nativeMesgNum.
void setNativeFieldNum (const quint8 nativeFieldNum)
Sets the nativeFieldNum field to nativeFieldNum.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
FieldDescriptionMessage (FieldDescriptionMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The FieldDescriptionMessage class represents a FIT FieldDescriptionMessage data message.
See also
DataMessage
Definition at line 39 of file fielddescriptionmessage.h.
Constructor & Destructor Documentation
FieldDescriptionMessage() [1/2]
FieldDescriptionMessage::FieldDescriptionMessage ()
Constructs a FieldDescriptionMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file fielddescriptionmessage.cpp.
                                                  : AbstractDataMessage(new FieldDescriptionMessagePrivate(this))
 {
 }
FieldDescriptionMessage() [2/2]
FieldDescriptionMessage::FieldDescriptionMessage (FieldDescriptionMessagePrivate *const d) explicit protected
Constructs a FieldDescriptionMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file fielddescriptionmessage.cpp.
                                                                                          : AbstractDataMessage(d)
 {
 }
Member Function Documentation
accumulate()
QString FieldDescriptionMessage::accumulate () const
Returns the FieldDescriptionMessage data message's accumulate field's current value.
Returns
the accumulate field value.
Definition at line 184 of file fielddescriptionmessage.cpp.
 {
     Q_D(const FieldDescriptionMessage);
     return d->accumulate;
 }
Referenced by setAccumulate().
array()
quint8 FieldDescriptionMessage::array () const
Returns the FieldDescriptionMessage data message's array field's current value.
Returns
the array field value.
Definition at line 118 of file fielddescriptionmessage.cpp.
 {
     Q_D(const FieldDescriptionMessage);
     return d->array;
 }
Referenced by setArray().
bits()
QString FieldDescriptionMessage::bits () const
Returns the FieldDescriptionMessage data message's bits field's current value.
Returns
the bits field value.
Definition at line 173 of file fielddescriptionmessage.cpp.
 {
     Q_D(const FieldDescriptionMessage);
     return d->bits;
 }
Referenced by setBits().
components()
QString FieldDescriptionMessage::components () const
Returns the FieldDescriptionMessage data message's components field's current value.
Returns
the components field value.
Definition at line 129 of file fielddescriptionmessage.cpp.
 {
     Q_D(const FieldDescriptionMessage);
     return d->components;
 }
Referenced by setComponents().
developerDataIndex()
quint8 FieldDescriptionMessage::developerDataIndex () const
Returns the FieldDescriptionMessage data message's developerDataIndex field's current value.
Returns
the developerDataIndex field value.
Definition at line 74 of file fielddescriptionmessage.cpp.
 {
     Q_D(const FieldDescriptionMessage);
     return d->developerDataIndex;
 }
Referenced by setDeveloperDataIndex().
fieldDefinitionNumber()
quint8 FieldDescriptionMessage::fieldDefinitionNumber () const
Returns the FieldDescriptionMessage data message's fieldDefinitionNumber field's current value.
Returns
the fieldDefinitionNumber field value.
Definition at line 85 of file fielddescriptionmessage.cpp.
 {
     Q_D(const FieldDescriptionMessage);
     return d->fieldDefinitionNumber;
 }
Referenced by setFieldDefinitionNumber().
fieldName()
QString FieldDescriptionMessage::fieldName () const
Returns the FieldDescriptionMessage data message's fieldName field's current value.
Returns
the fieldName field value.
Definition at line 107 of file fielddescriptionmessage.cpp.
 {
     Q_D(const FieldDescriptionMessage);
     return d->fieldName;
 }
Referenced by setFieldName().
fitBaseTypeId()
FitBaseType FieldDescriptionMessage::fitBaseTypeId () const
Returns the FieldDescriptionMessage data message's fitBaseTypeId field's current value.
Returns
the fitBaseTypeId field value.
Definition at line 96 of file fielddescriptionmessage.cpp.
 {
     Q_D(const FieldDescriptionMessage);
     return d->fitBaseTypeId;
 }
Referenced by setFitBaseTypeId().
fitBaseUnitId()
FitBaseUnit FieldDescriptionMessage::fitBaseUnitId () const
Returns the FieldDescriptionMessage data message's fitBaseUnitId field's current value.
Returns
the fitBaseUnitId field value.
Definition at line 195 of file fielddescriptionmessage.cpp.
 {
     Q_D(const FieldDescriptionMessage);
     return d->fitBaseUnitId;
 }
Referenced by setFitBaseUnitId().
nativeFieldNum()
quint8 FieldDescriptionMessage::nativeFieldNum () const
Returns the FieldDescriptionMessage data message's nativeFieldNum field's current value.
Returns
the nativeFieldNum field value.
Definition at line 217 of file fielddescriptionmessage.cpp.
 {
     Q_D(const FieldDescriptionMessage);
     return d->nativeFieldNum;
 }
Referenced by setNativeFieldNum().
nativeMesgNum()
MesgNum FieldDescriptionMessage::nativeMesgNum () const
Returns the FieldDescriptionMessage data message's nativeMesgNum field's current value.
Returns
the nativeMesgNum field value.
Definition at line 206 of file fielddescriptionmessage.cpp.
 {
     Q_D(const FieldDescriptionMessage);
     return d->nativeMesgNum;
 }
Referenced by setNativeMesgNum().
offset()
qint8 FieldDescriptionMessage::offset () const
Returns the FieldDescriptionMessage data message's offset field's current value.
Returns
the offset field value.
Definition at line 151 of file fielddescriptionmessage.cpp.
 {
     Q_D(const FieldDescriptionMessage);
     return d->offset;
 }
Referenced by setOffset().
scale()
quint8 FieldDescriptionMessage::scale () const
Returns the FieldDescriptionMessage data message's scale field's current value.
Returns
the scale field value.
Definition at line 140 of file fielddescriptionmessage.cpp.
 {
     Q_D(const FieldDescriptionMessage);
     return d->scale;
 }
Referenced by setScale().
setAccumulate()
void FieldDescriptionMessage::setAccumulate (const QString accumulate)
Sets the accumulate field to accumulate.
Parameters
accumulate The field value to set.
Definition at line 328 of file fielddescriptionmessage.cpp.
 {
     Q_D(FieldDescriptionMessage);
     d->accumulate = accumulate;
 }
References accumulate().
setArray()
void FieldDescriptionMessage::setArray (const quint8 array)
Sets the array field to array.
Parameters
array The field value to set.
Definition at line 268 of file fielddescriptionmessage.cpp.
 {
     Q_D(FieldDescriptionMessage);
     d->array = array;
 }
References array().
setBits()
void FieldDescriptionMessage::setBits (const QString bits)
Sets the bits field to bits.
Parameters
bits The field value to set.
Definition at line 318 of file fielddescriptionmessage.cpp.
 {
     Q_D(FieldDescriptionMessage);
     d->bits = bits;
 }
References bits().
setComponents()
void FieldDescriptionMessage::setComponents (const QString components)
Sets the components field to components.
Parameters
components The field value to set.
Definition at line 278 of file fielddescriptionmessage.cpp.
 {
     Q_D(FieldDescriptionMessage);
     d->components = components;
 }
References components().
setDeveloperDataIndex()
void FieldDescriptionMessage::setDeveloperDataIndex (const quint8 developerDataIndex)
Sets the developerDataIndex field to developerDataIndex.
Parameters
developerDataIndex The field value to set.
Definition at line 228 of file fielddescriptionmessage.cpp.
 {
     Q_D(FieldDescriptionMessage);
     d->developerDataIndex = developerDataIndex;
 }
References developerDataIndex().
setFieldDefinitionNumber()
void FieldDescriptionMessage::setFieldDefinitionNumber (const quint8 fieldDefinitionNumber)
Sets the fieldDefinitionNumber field to fieldDefinitionNumber.
Parameters
fieldDefinitionNumber The field value to set.
Definition at line 238 of file fielddescriptionmessage.cpp.
 {
     Q_D(FieldDescriptionMessage);
     d->fieldDefinitionNumber = fieldDefinitionNumber;
 }
References fieldDefinitionNumber().
setFieldName()
void FieldDescriptionMessage::setFieldName (const QString fieldName)
Sets the fieldName field to fieldName.
Parameters
fieldName The field value to set.
Definition at line 258 of file fielddescriptionmessage.cpp.
 {
     Q_D(FieldDescriptionMessage);
     d->fieldName = fieldName;
 }
References fieldName().
setFitBaseTypeId()
void FieldDescriptionMessage::setFitBaseTypeId (const FitBaseType fitBaseTypeId)
Sets the fitBaseTypeId field to fitBaseTypeId.
Parameters
fitBaseTypeId The field value to set.
Definition at line 248 of file fielddescriptionmessage.cpp.
 {
     Q_D(FieldDescriptionMessage);
     d->fitBaseTypeId = fitBaseTypeId;
 }
References fitBaseTypeId().
setFitBaseUnitId()
void FieldDescriptionMessage::setFitBaseUnitId (const FitBaseUnit fitBaseUnitId)
Sets the fitBaseUnitId field to fitBaseUnitId.
Parameters
fitBaseUnitId The field value to set.
Definition at line 338 of file fielddescriptionmessage.cpp.
 {
     Q_D(FieldDescriptionMessage);
     d->fitBaseUnitId = fitBaseUnitId;
 }
References fitBaseUnitId().
setNativeFieldNum()
void FieldDescriptionMessage::setNativeFieldNum (const quint8 nativeFieldNum)
Sets the nativeFieldNum field to nativeFieldNum.
Parameters
nativeFieldNum The field value to set.
Definition at line 358 of file fielddescriptionmessage.cpp.
 {
     Q_D(FieldDescriptionMessage);
     d->nativeFieldNum = nativeFieldNum;
 }
References nativeFieldNum().
setNativeMesgNum()
void FieldDescriptionMessage::setNativeMesgNum (const MesgNum nativeMesgNum)
Sets the nativeMesgNum field to nativeMesgNum.
Parameters
nativeMesgNum The field value to set.
Definition at line 348 of file fielddescriptionmessage.cpp.
 {
     Q_D(FieldDescriptionMessage);
     d->nativeMesgNum = nativeMesgNum;
 }
References nativeMesgNum().
setOffset()
void FieldDescriptionMessage::setOffset (const qint8 offset)
Sets the offset field to offset.
Parameters
offset The field value to set.
Definition at line 298 of file fielddescriptionmessage.cpp.
 {
     Q_D(FieldDescriptionMessage);
     d->offset = offset;
 }
References offset().
setScale()
void FieldDescriptionMessage::setScale (const quint8 scale)
Sets the scale field to scale.
Parameters
scale The field value to set.
Definition at line 288 of file fielddescriptionmessage.cpp.
 {
     Q_D(FieldDescriptionMessage);
     d->scale = scale;
 }
References scale().
setUnits()
void FieldDescriptionMessage::setUnits (const QString units)
Sets the units field to units.
Parameters
units The field value to set.
Definition at line 308 of file fielddescriptionmessage.cpp.
 {
     Q_D(FieldDescriptionMessage);
     d->units = units;
 }
References units().
units()
QString FieldDescriptionMessage::units () const
Returns the FieldDescriptionMessage data message's units field's current value.
Returns
the units field value.
Definition at line 162 of file fielddescriptionmessage.cpp.
 {
     Q_D(const FieldDescriptionMessage);
     return d->units;
 }
Referenced by setUnits().
The documentation for this class was generated from the following files:
fielddescriptionmessage.h
fielddescriptionmessage.cpp