QtFit: FitStreamReader Class Reference
FitStreamReader Class Reference
The FitStreamReader class provides a streaming parser for reading Garmin FIT files.
Public Member Functions
FitStreamReader ()
Constructs a FIT stream reader with no initial data.
FitStreamReader (const QByteArray &data)
Constructs a FIT stream reader that reads from data.
FitStreamReader (QIODevice *device)
Constructs a FIT stream reader that reads from device.
~FitStreamReader ()
Destroys the FIT stream reader.
void addData (const QByteArray &data)
Adds more data to read.
bool atEnd () const
Returns true if the reader has reached the end of the underlying data or device, or an error has occurred.
void clear ()
Clears the FIT stream reader.
QIODevice * device () const
Returns the current device associated with the reader, or nullptr if no device is assigned.
void setDevice (QIODevice *device)
Sets the current device to device, and resets the stream to its initial state.
QVersionNumber protocolVersion () const
Returns the protocol version read from the FIT file header, otherwise a null QVersionNumber.
QVersionNumber profileVersion () const
Returns the profile version read from the FIT file header, otherwise a null QVersionNumber.
AbstractDataMessage * readNext ()
Returns the next FIT data message from the underlying stream, or a null data message if none could be read.
Protected Member Functions
FitStreamReader (FitStreamReaderPrivate *const d)
Constructs a FIT stream reader with private implementation d.
Protected Attributes
FitStreamReaderPrivate *const d_ptr
Internal d-pointer.
Detailed Description
The FitStreamReader class provides a streaming parser for reading Garmin FIT files.
Todo:
Mention that this is a lower-level class, a users should probably use some yet-to-be FitFile class, that wraps up the calls to this one.
See also
https://developer.garmin.com/fit/protocol/
Definition at line 37 of file fitstreamreader.h.
Constructor & Destructor Documentation
FitStreamReader() [1/4]
FitStreamReader::FitStreamReader ()
Constructs a FIT stream reader with no initial data.
Use addData() or setDevice() to provide data when ready.
See also
addData
setDevice
Definition at line 54 of file fitstreamreader.cpp.
                                  : d_ptr(new FitStreamReaderPrivate(this))
 {
 }
FitStreamReader() [2/4]
FitStreamReader::FitStreamReader (const QByteArray & data) explicit
Constructs a FIT stream reader that reads from data.
data may be empty or incomplete, in which case more data can be added later via addData().
Parameters
data FIT data to begin reading.
See also
addData
Definition at line 68 of file fitstreamreader.cpp.
                                                        : d_ptr(new FitStreamReaderPrivate(this))
 {
     Q_D(FitStreamReader);
     d->data = data;
     d->parseFileHeader<QByteArray>();
 }
FitStreamReader() [3/4]
FitStreamReader::FitStreamReader (QIODevice * device) explicit
Constructs a FIT stream reader that reads from device.
device must be open for reading, but does not need to have any bytes available yet.
Note
The caller is responsible for ensuring that device remains valid for the lifetime of the constructed reader, or until clear() or setDevice() is used to clear or replace the device.
Parameters
device Device to to begin reading.
See also
clear
setDevice
Definition at line 88 of file fitstreamreader.cpp.
                                                   : d_ptr(new FitStreamReaderPrivate(this))
 {
     Q_D(FitStreamReader);
     d->device = device;
     d->parseFileHeader<QIODevice>();
 }
References device().
FitStreamReader() [4/4]
FitStreamReader::FitStreamReader (FitStreamReaderPrivate *const d) explicit protected
Constructs a FIT stream reader with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 102 of file fitstreamreader.cpp.
                                                                  : d_ptr(d)
 {
 }
Member Function Documentation
addData()
void FitStreamReader::addData (const QByteArray & data)
Adds more data to read.
Note
It is not valid to use this function if a device has been assigned, ie via either the FitStreamReader(QIODevice *device) constructor, or setDevice().
Parameters
data Additonal data to read.
Definition at line 124 of file fitstreamreader.cpp.
 {
     Q_D(FitStreamReader);
     if (d->device != nullptr) {
         qWarning("FitStreamReader: addData() with device()");
         Q_ASSERT(d->device != nullptr);
         return;
     }
     d->data += data;
 }
atEnd()
bool FitStreamReader::atEnd () const
Returns true if the reader has reached the end of the underlying data or device, or an error has occurred.
Todo:
Implement this method.
Returns
true if the reader has reached the end of the underlying data or device.
Todo:
Implement this method.
Definition at line 143 of file fitstreamreader.cpp.
 {
     return false; /// \todo Implement this method.
 }
clear()
void FitStreamReader::clear ()
Clears the FIT stream reader.
This returns the reader to a state equivalent to having just been default-constructed.
See also
FitStreamReader()
Definition at line 155 of file fitstreamreader.cpp.
 {
     Q_D(FitStreamReader);
     d->data.clear();
     d->dataOffset = 0;
     d->device = nullptr;
 //    d->headerSize = 0;
 //    d->expectedChecksum = 0;
     d->expectedDataSize = 0;
     d->protocolVersion = QVersionNumber();
     d->profileVersion = QVersionNumber();
     d->dataDefinitions.clear();
     d->recordSizes.clear();
 }
Referenced by setDevice().
device()
QIODevice * FitStreamReader::device () const
Returns the current device associated with the reader, or nullptr if no device is assigned.
Returns
the current device associated with the reader, or nullptr if no device is assigned.
See also
setDevice
Definition at line 177 of file fitstreamreader.cpp.
 {
     Q_D(const FitStreamReader);
     return d->device;
 }
Referenced by FitStreamReader(), and setDevice().
profileVersion()
QVersionNumber FitStreamReader::profileVersion () const
Returns the profile version read from the FIT file header, otherwise a null QVersionNumber.
FIT profile versions have only two components - major and minor. Both have a maximum value of 15, as the underlying format uses 4-bits for each component.
Returns
the profile version read from the FIT file header, otherwise a null QVersionNumber.
Definition at line 211 of file fitstreamreader.cpp.
 {
     Q_D(const FitStreamReader);
     return d->profileVersion;
 }
protocolVersion()
QVersionNumber FitStreamReader::protocolVersion () const
Returns the protocol version read from the FIT file header, otherwise a null QVersionNumber.
FIT protocol versions have only two components - major and minor. The minor component is limited to the range 0 to 100, whereas the major component may be (theoreticlly) 0 to 655.
Returns
the protocol version read from the FIT file header, otherwise a null QVersionNumber.
Definition at line 225 of file fitstreamreader.cpp.
 {
     Q_D(const FitStreamReader);
     return d->protocolVersion;
 }
readNext()
AbstractDataMessage * FitStreamReader::readNext ()
Returns the next FIT data message from the underlying stream, or a null data message if none could be read.
If FIT header has not been read yet, it will be read first. If any FIT definition messages are found, they will be parsed, and kept in a dictionary, to used for interpretation of subsequent data messages. Reading will continue until the next FIT data message is found, or no more bytes are available for reading.
Todo:
Document how the caller should distinguish errors, from more-data-needed.
Returns
the next FIT data message, or a null data message.
See also
addData
Definition at line 246 of file fitstreamreader.cpp.
 {
     Q_D(FitStreamReader);
     return (d->device == nullptr)
         ? d->readNextDataMessage<QByteArray>() : d->readNextDataMessage<QIODevice>();
 }
setDevice()
void FitStreamReader::setDevice (QIODevice * device)
Sets the current device to device, and resets the stream to its initial state.
device must be open for reading, but does not need to have any bytes available yet.
Note
The caller is responsible for ensuring that device remains valid for the lifetime of the constructed reader, or until clear() or setDevice() is used to clear or replace the device.
Parameters
device IO device to read from.
See also
device
Definition at line 195 of file fitstreamreader.cpp.
 {
     Q_D(FitStreamReader);
     if (device) clear();
     d->device = device;
     if (device) d->parseFileHeader<QIODevice>();
 }
References clear(), and device().
The documentation for this class was generated from the following files:
fitstreamreader.h
fitstreamreader.cpp