QtFit: DiveAlarmMessage Class Reference
DiveAlarmMessage Class Reference
The DiveAlarmMessage class represents a FIT DiveAlarmMessage data message.
Public Member Functions
DiveAlarmMessage ()
Constructs a DiveAlarmMessage object.
MessageIndex messageIndex () const
Returns the DiveAlarmMessage data message's messageIndex field's current value.
quint32 depth () const
Returns the DiveAlarmMessage data message's depth field's current value.
qint32 time () const
Returns the DiveAlarmMessage data message's time field's current value.
bool enabled () const
Returns the DiveAlarmMessage data message's enabled field's current value.
DiveAlarmType alarmType () const
Returns the DiveAlarmMessage data message's alarmType field's current value.
Tone sound () const
Returns the DiveAlarmMessage data message's sound field's current value.
SubSport diveTypes () const
Returns the DiveAlarmMessage data message's diveTypes field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setDepth (const quint32 depth)
Sets the depth field to depth.
void setTime (const qint32 time)
Sets the time field to time.
void setEnabled (const bool enabled)
Sets the enabled field to enabled.
void setAlarmType (const DiveAlarmType alarmType)
Sets the alarmType field to alarmType.
void setSound (const Tone sound)
Sets the sound field to sound.
void setDiveTypes (const SubSport diveTypes)
Sets the diveTypes field to diveTypes.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
DiveAlarmMessage (DiveAlarmMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The DiveAlarmMessage class represents a FIT DiveAlarmMessage data message.
See also
DataMessage
Definition at line 34 of file divealarmmessage.h.
Constructor & Destructor Documentation
DiveAlarmMessage() [1/2]
DiveAlarmMessage::DiveAlarmMessage ()
Constructs a DiveAlarmMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file divealarmmessage.cpp.
                                    : AbstractDataMessage(new DiveAlarmMessagePrivate(this))
 {
 }
DiveAlarmMessage() [2/2]
DiveAlarmMessage::DiveAlarmMessage (DiveAlarmMessagePrivate *const d) explicit protected
Constructs a DiveAlarmMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file divealarmmessage.cpp.
                                                                     : AbstractDataMessage(d)
 {
 }
Member Function Documentation
alarmType()
DiveAlarmType DiveAlarmMessage::alarmType () const
Returns the DiveAlarmMessage data message's alarmType field's current value.
Returns
the alarmType field value.
Definition at line 115 of file divealarmmessage.cpp.
 {
     Q_D(const DiveAlarmMessage);
     return d->alarmType;
 }
Referenced by setAlarmType().
depth()
quint32 DiveAlarmMessage::depth () const
Returns the DiveAlarmMessage data message's depth field's current value.
Returns
the depth field value.
Definition at line 82 of file divealarmmessage.cpp.
 {
     Q_D(const DiveAlarmMessage);
     return d->depth;
 }
Referenced by setDepth().
diveTypes()
SubSport DiveAlarmMessage::diveTypes () const
Returns the DiveAlarmMessage data message's diveTypes field's current value.
Returns
the diveTypes field value.
Definition at line 137 of file divealarmmessage.cpp.
 {
     Q_D(const DiveAlarmMessage);
     return d->diveTypes;
 }
Referenced by setDiveTypes().
enabled()
bool DiveAlarmMessage::enabled () const
Returns the DiveAlarmMessage data message's enabled field's current value.
Returns
the enabled field value.
Definition at line 104 of file divealarmmessage.cpp.
 {
     Q_D(const DiveAlarmMessage);
     return d->enabled;
 }
Referenced by setEnabled().
messageIndex()
MessageIndex DiveAlarmMessage::messageIndex () const
Returns the DiveAlarmMessage data message's messageIndex field's current value.
Index of the alarm
Returns
the messageIndex field value.
Definition at line 71 of file divealarmmessage.cpp.
 {
     Q_D(const DiveAlarmMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
setAlarmType()
void DiveAlarmMessage::setAlarmType (const DiveAlarmType alarmType)
Sets the alarmType field to alarmType.
Parameters
alarmType The field value to set.
Definition at line 188 of file divealarmmessage.cpp.
 {
     Q_D(DiveAlarmMessage);
     d->alarmType = alarmType;
 }
References alarmType().
setDepth()
void DiveAlarmMessage::setDepth (const quint32 depth)
Sets the depth field to depth.
Parameters
depth The field value to set.
Definition at line 158 of file divealarmmessage.cpp.
 {
     Q_D(DiveAlarmMessage);
     d->depth = depth;
 }
References depth().
setDiveTypes()
void DiveAlarmMessage::setDiveTypes (const SubSport diveTypes)
Sets the diveTypes field to diveTypes.
Parameters
diveTypes The field value to set.
Definition at line 208 of file divealarmmessage.cpp.
 {
     Q_D(DiveAlarmMessage);
     d->diveTypes = diveTypes;
 }
References diveTypes().
setEnabled()
void DiveAlarmMessage::setEnabled (const bool enabled)
Sets the enabled field to enabled.
Parameters
enabled The field value to set.
Definition at line 178 of file divealarmmessage.cpp.
 {
     Q_D(DiveAlarmMessage);
     d->enabled = enabled;
 }
References enabled().
setMessageIndex()
void DiveAlarmMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 148 of file divealarmmessage.cpp.
 {
     Q_D(DiveAlarmMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setSound()
void DiveAlarmMessage::setSound (const Tone sound)
Sets the sound field to sound.
Parameters
sound The field value to set.
Definition at line 198 of file divealarmmessage.cpp.
 {
     Q_D(DiveAlarmMessage);
     d->sound = sound;
 }
References sound().
setTime()
void DiveAlarmMessage::setTime (const qint32 time)
Sets the time field to time.
Parameters
time The field value to set.
Definition at line 168 of file divealarmmessage.cpp.
 {
     Q_D(DiveAlarmMessage);
     d->time = time;
 }
References time().
sound()
Tone DiveAlarmMessage::sound () const
Returns the DiveAlarmMessage data message's sound field's current value.
Returns
the sound field value.
Definition at line 126 of file divealarmmessage.cpp.
 {
     Q_D(const DiveAlarmMessage);
     return d->sound;
 }
Referenced by setSound().
time()
qint32 DiveAlarmMessage::time () const
Returns the DiveAlarmMessage data message's time field's current value.
Returns
the time field value.
Definition at line 93 of file divealarmmessage.cpp.
 {
     Q_D(const DiveAlarmMessage);
     return d->time;
 }
Referenced by setTime().
The documentation for this class was generated from the following files:
divealarmmessage.h
divealarmmessage.cpp