QtFit: WorkoutStepMessage Class Reference
WorkoutStepMessage Class Reference
The WorkoutStepMessage class represents a FIT WorkoutStepMessage data message.
Public Member Functions
WorkoutStepMessage ()
Constructs a WorkoutStepMessage object.
MessageIndex messageIndex () const
Returns the WorkoutStepMessage data message's messageIndex field's current value.
QString wktStepName () const
Returns the WorkoutStepMessage data message's wktStepName field's current value.
WktStepDuration durationType () const
Returns the WorkoutStepMessage data message's durationType field's current value.
quint32 durationValue () const
Returns the WorkoutStepMessage data message's durationValue field's current value.
WktStepTarget targetType () const
Returns the WorkoutStepMessage data message's targetType field's current value.
quint32 targetValue () const
Returns the WorkoutStepMessage data message's targetValue field's current value.
quint32 customTargetValueLow () const
Returns the WorkoutStepMessage data message's customTargetValueLow field's current value.
quint32 customTargetValueHigh () const
Returns the WorkoutStepMessage data message's customTargetValueHigh field's current value.
Intensity intensity () const
Returns the WorkoutStepMessage data message's intensity field's current value.
QString notes () const
Returns the WorkoutStepMessage data message's notes field's current value.
WorkoutEquipment equipment () const
Returns the WorkoutStepMessage data message's equipment field's current value.
ExerciseCategory exerciseCategory () const
Returns the WorkoutStepMessage data message's exerciseCategory field's current value.
quint16 exerciseName () const
Returns the WorkoutStepMessage data message's exerciseName field's current value.
quint16 exerciseWeight () const
Returns the WorkoutStepMessage data message's exerciseWeight field's current value.
FitBaseUnit weightDisplayUnit () const
Returns the WorkoutStepMessage data message's weightDisplayUnit field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setWktStepName (const QString wktStepName)
Sets the wktStepName field to wktStepName.
void setDurationType (const WktStepDuration durationType)
Sets the durationType field to durationType.
void setDurationValue (const quint32 durationValue)
Sets the durationValue field to durationValue.
void setTargetType (const WktStepTarget targetType)
Sets the targetType field to targetType.
void setTargetValue (const quint32 targetValue)
Sets the targetValue field to targetValue.
void setCustomTargetValueLow (const quint32 customTargetValueLow)
Sets the customTargetValueLow field to customTargetValueLow.
void setCustomTargetValueHigh (const quint32 customTargetValueHigh)
Sets the customTargetValueHigh field to customTargetValueHigh.
void setIntensity (const Intensity intensity)
Sets the intensity field to intensity.
void setNotes (const QString notes)
Sets the notes field to notes.
void setEquipment (const WorkoutEquipment equipment)
Sets the equipment field to equipment.
void setExerciseCategory (const ExerciseCategory exerciseCategory)
Sets the exerciseCategory field to exerciseCategory.
void setExerciseName (const quint16 exerciseName)
Sets the exerciseName field to exerciseName.
void setExerciseWeight (const quint16 exerciseWeight)
Sets the exerciseWeight field to exerciseWeight.
void setWeightDisplayUnit (const FitBaseUnit weightDisplayUnit)
Sets the weightDisplayUnit field to weightDisplayUnit.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
WorkoutStepMessage (WorkoutStepMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The WorkoutStepMessage class represents a FIT WorkoutStepMessage data message.
See also
DataMessage
Definition at line 39 of file workoutstepmessage.h.
Constructor & Destructor Documentation
WorkoutStepMessage() [1/2]
WorkoutStepMessage::WorkoutStepMessage ()
Constructs a WorkoutStepMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file workoutstepmessage.cpp.
                                        : AbstractDataMessage(new WorkoutStepMessagePrivate(this))
 {
 }
WorkoutStepMessage() [2/2]
WorkoutStepMessage::WorkoutStepMessage (WorkoutStepMessagePrivate *const d) explicit protected
Constructs a WorkoutStepMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file workoutstepmessage.cpp.
                                                                           : AbstractDataMessage(d)
 {
 }
Member Function Documentation
customTargetValueHigh()
quint32 WorkoutStepMessage::customTargetValueHigh () const
Returns the WorkoutStepMessage data message's customTargetValueHigh field's current value.
Returns
the customTargetValueHigh field value.
Definition at line 151 of file workoutstepmessage.cpp.
 {
     Q_D(const WorkoutStepMessage);
     return d->customTargetValueHigh;
 }
Referenced by setCustomTargetValueHigh().
customTargetValueLow()
quint32 WorkoutStepMessage::customTargetValueLow () const
Returns the WorkoutStepMessage data message's customTargetValueLow field's current value.
Returns
the customTargetValueLow field value.
Definition at line 140 of file workoutstepmessage.cpp.
 {
     Q_D(const WorkoutStepMessage);
     return d->customTargetValueLow;
 }
Referenced by setCustomTargetValueLow().
durationType()
WktStepDuration WorkoutStepMessage::durationType () const
Returns the WorkoutStepMessage data message's durationType field's current value.
Returns
the durationType field value.
Definition at line 96 of file workoutstepmessage.cpp.
 {
     Q_D(const WorkoutStepMessage);
     return d->durationType;
 }
Referenced by setDurationType().
durationValue()
quint32 WorkoutStepMessage::durationValue () const
Returns the WorkoutStepMessage data message's durationValue field's current value.
Returns
the durationValue field value.
Definition at line 107 of file workoutstepmessage.cpp.
 {
     Q_D(const WorkoutStepMessage);
     return d->durationValue;
 }
Referenced by setDurationValue().
equipment()
WorkoutEquipment WorkoutStepMessage::equipment () const
Returns the WorkoutStepMessage data message's equipment field's current value.
Returns
the equipment field value.
Definition at line 184 of file workoutstepmessage.cpp.
 {
     Q_D(const WorkoutStepMessage);
     return d->equipment;
 }
Referenced by setEquipment().
exerciseCategory()
ExerciseCategory WorkoutStepMessage::exerciseCategory () const
Returns the WorkoutStepMessage data message's exerciseCategory field's current value.
Returns
the exerciseCategory field value.
Definition at line 195 of file workoutstepmessage.cpp.
 {
     Q_D(const WorkoutStepMessage);
     return d->exerciseCategory;
 }
Referenced by setExerciseCategory().
exerciseName()
quint16 WorkoutStepMessage::exerciseName () const
Returns the WorkoutStepMessage data message's exerciseName field's current value.
Returns
the exerciseName field value.
Definition at line 206 of file workoutstepmessage.cpp.
 {
     Q_D(const WorkoutStepMessage);
     return d->exerciseName;
 }
Referenced by setExerciseName().
exerciseWeight()
quint16 WorkoutStepMessage::exerciseWeight () const
Returns the WorkoutStepMessage data message's exerciseWeight field's current value.
Returns
the exerciseWeight field value.
Definition at line 217 of file workoutstepmessage.cpp.
 {
     Q_D(const WorkoutStepMessage);
     return d->exerciseWeight;
 }
Referenced by setExerciseWeight().
intensity()
Intensity WorkoutStepMessage::intensity () const
Returns the WorkoutStepMessage data message's intensity field's current value.
Returns
the intensity field value.
Definition at line 162 of file workoutstepmessage.cpp.
 {
     Q_D(const WorkoutStepMessage);
     return d->intensity;
 }
Referenced by setIntensity().
messageIndex()
MessageIndex WorkoutStepMessage::messageIndex () const
Returns the WorkoutStepMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 74 of file workoutstepmessage.cpp.
 {
     Q_D(const WorkoutStepMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
notes()
QString WorkoutStepMessage::notes () const
Returns the WorkoutStepMessage data message's notes field's current value.
Returns
the notes field value.
Definition at line 173 of file workoutstepmessage.cpp.
 {
     Q_D(const WorkoutStepMessage);
     return d->notes;
 }
Referenced by setNotes().
setCustomTargetValueHigh()
void WorkoutStepMessage::setCustomTargetValueHigh (const quint32 customTargetValueHigh)
Sets the customTargetValueHigh field to customTargetValueHigh.
Parameters
customTargetValueHigh The field value to set.
Definition at line 309 of file workoutstepmessage.cpp.
 {
     Q_D(WorkoutStepMessage);
     d->customTargetValueHigh = customTargetValueHigh;
 }
References customTargetValueHigh().
setCustomTargetValueLow()
void WorkoutStepMessage::setCustomTargetValueLow (const quint32 customTargetValueLow)
Sets the customTargetValueLow field to customTargetValueLow.
Parameters
customTargetValueLow The field value to set.
Definition at line 299 of file workoutstepmessage.cpp.
 {
     Q_D(WorkoutStepMessage);
     d->customTargetValueLow = customTargetValueLow;
 }
References customTargetValueLow().
setDurationType()
void WorkoutStepMessage::setDurationType (const WktStepDuration durationType)
Sets the durationType field to durationType.
Parameters
durationType The field value to set.
Definition at line 259 of file workoutstepmessage.cpp.
 {
     Q_D(WorkoutStepMessage);
     d->durationType = durationType;
 }
References durationType().
setDurationValue()
void WorkoutStepMessage::setDurationValue (const quint32 durationValue)
Sets the durationValue field to durationValue.
Parameters
durationValue The field value to set.
Definition at line 269 of file workoutstepmessage.cpp.
 {
     Q_D(WorkoutStepMessage);
     d->durationValue = durationValue;
 }
References durationValue().
setEquipment()
void WorkoutStepMessage::setEquipment (const WorkoutEquipment equipment)
Sets the equipment field to equipment.
Parameters
equipment The field value to set.
Definition at line 339 of file workoutstepmessage.cpp.
 {
     Q_D(WorkoutStepMessage);
     d->equipment = equipment;
 }
References equipment().
setExerciseCategory()
void WorkoutStepMessage::setExerciseCategory (const ExerciseCategory exerciseCategory)
Sets the exerciseCategory field to exerciseCategory.
Parameters
exerciseCategory The field value to set.
Definition at line 349 of file workoutstepmessage.cpp.
 {
     Q_D(WorkoutStepMessage);
     d->exerciseCategory = exerciseCategory;
 }
References exerciseCategory().
setExerciseName()
void WorkoutStepMessage::setExerciseName (const quint16 exerciseName)
Sets the exerciseName field to exerciseName.
Parameters
exerciseName The field value to set.
Definition at line 359 of file workoutstepmessage.cpp.
 {
     Q_D(WorkoutStepMessage);
     d->exerciseName = exerciseName;
 }
References exerciseName().
setExerciseWeight()
void WorkoutStepMessage::setExerciseWeight (const quint16 exerciseWeight)
Sets the exerciseWeight field to exerciseWeight.
Parameters
exerciseWeight The field value to set.
Definition at line 369 of file workoutstepmessage.cpp.
 {
     Q_D(WorkoutStepMessage);
     d->exerciseWeight = exerciseWeight;
 }
References exerciseWeight().
setIntensity()
void WorkoutStepMessage::setIntensity (const Intensity intensity)
Sets the intensity field to intensity.
Parameters
intensity The field value to set.
Definition at line 319 of file workoutstepmessage.cpp.
 {
     Q_D(WorkoutStepMessage);
     d->intensity = intensity;
 }
References intensity().
setMessageIndex()
void WorkoutStepMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 239 of file workoutstepmessage.cpp.
 {
     Q_D(WorkoutStepMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setNotes()
void WorkoutStepMessage::setNotes (const QString notes)
Sets the notes field to notes.
Parameters
notes The field value to set.
Definition at line 329 of file workoutstepmessage.cpp.
 {
     Q_D(WorkoutStepMessage);
     d->notes = notes;
 }
References notes().
setTargetType()
void WorkoutStepMessage::setTargetType (const WktStepTarget targetType)
Sets the targetType field to targetType.
Parameters
targetType The field value to set.
Definition at line 279 of file workoutstepmessage.cpp.
 {
     Q_D(WorkoutStepMessage);
     d->targetType = targetType;
 }
References targetType().
setTargetValue()
void WorkoutStepMessage::setTargetValue (const quint32 targetValue)
Sets the targetValue field to targetValue.
Parameters
targetValue The field value to set.
Definition at line 289 of file workoutstepmessage.cpp.
 {
     Q_D(WorkoutStepMessage);
     d->targetValue = targetValue;
 }
References targetValue().
setWeightDisplayUnit()
void WorkoutStepMessage::setWeightDisplayUnit (const FitBaseUnit weightDisplayUnit)
Sets the weightDisplayUnit field to weightDisplayUnit.
Parameters
weightDisplayUnit The field value to set.
Definition at line 379 of file workoutstepmessage.cpp.
 {
     Q_D(WorkoutStepMessage);
     d->weightDisplayUnit = weightDisplayUnit;
 }
References weightDisplayUnit().
setWktStepName()
void WorkoutStepMessage::setWktStepName (const QString wktStepName)
Sets the wktStepName field to wktStepName.
Parameters
wktStepName The field value to set.
Definition at line 249 of file workoutstepmessage.cpp.
 {
     Q_D(WorkoutStepMessage);
     d->wktStepName = wktStepName;
 }
References wktStepName().
targetType()
WktStepTarget WorkoutStepMessage::targetType () const
Returns the WorkoutStepMessage data message's targetType field's current value.
Returns
the targetType field value.
Definition at line 118 of file workoutstepmessage.cpp.
 {
     Q_D(const WorkoutStepMessage);
     return d->targetType;
 }
Referenced by setTargetType().
targetValue()
quint32 WorkoutStepMessage::targetValue () const
Returns the WorkoutStepMessage data message's targetValue field's current value.
Returns
the targetValue field value.
Definition at line 129 of file workoutstepmessage.cpp.
 {
     Q_D(const WorkoutStepMessage);
     return d->targetValue;
 }
Referenced by setTargetValue().
weightDisplayUnit()
FitBaseUnit WorkoutStepMessage::weightDisplayUnit () const
Returns the WorkoutStepMessage data message's weightDisplayUnit field's current value.
Returns
the weightDisplayUnit field value.
Definition at line 228 of file workoutstepmessage.cpp.
 {
     Q_D(const WorkoutStepMessage);
     return d->weightDisplayUnit;
 }
Referenced by setWeightDisplayUnit().
wktStepName()
QString WorkoutStepMessage::wktStepName () const
Returns the WorkoutStepMessage data message's wktStepName field's current value.
Returns
the wktStepName field value.
Definition at line 85 of file workoutstepmessage.cpp.
 {
     Q_D(const WorkoutStepMessage);
     return d->wktStepName;
 }
Referenced by setWktStepName().
The documentation for this class was generated from the following files:
workoutstepmessage.h
workoutstepmessage.cpp