QtFit: VideoFrameMessage Class Reference
VideoFrameMessage Class Reference
The VideoFrameMessage class represents a FIT VideoFrameMessage data message.
Public Member Functions
VideoFrameMessage ()
Constructs a VideoFrameMessage object.
DateTime timestamp () const
Returns the VideoFrameMessage data message's timestamp field's current value.
quint16 timestampMs () const
Returns the VideoFrameMessage data message's timestampMs field's current value.
quint32 frameNumber () const
Returns the VideoFrameMessage data message's frameNumber field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
void setFrameNumber (const quint32 frameNumber)
Sets the frameNumber field to frameNumber.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
VideoFrameMessage (VideoFrameMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The VideoFrameMessage class represents a FIT VideoFrameMessage data message.
See also
DataMessage
Definition at line 39 of file videoframemessage.h.
Constructor & Destructor Documentation
VideoFrameMessage() [1/2]
VideoFrameMessage::VideoFrameMessage ()
Constructs a VideoFrameMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file videoframemessage.cpp.
                                      : AbstractDataMessage(new VideoFrameMessagePrivate(this))
 {
 }
VideoFrameMessage() [2/2]
VideoFrameMessage::VideoFrameMessage (VideoFrameMessagePrivate *const d) explicit protected
Constructs a VideoFrameMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file videoframemessage.cpp.
                                                                        : AbstractDataMessage(d)
 {
 }
Member Function Documentation
frameNumber()
quint32 VideoFrameMessage::frameNumber () const
Returns the VideoFrameMessage data message's frameNumber field's current value.
Number of the frame that the timestamp and timestamp_ms correlate to
Returns
the frameNumber field value.
Definition at line 102 of file videoframemessage.cpp.
 {
     Q_D(const VideoFrameMessage);
     return d->frameNumber;
 }
Referenced by setFrameNumber().
setFrameNumber()
void VideoFrameMessage::setFrameNumber (const quint32 frameNumber)
Sets the frameNumber field to frameNumber.
Parameters
frameNumber The field value to set.
Definition at line 133 of file videoframemessage.cpp.
 {
     Q_D(VideoFrameMessage);
     d->frameNumber = frameNumber;
 }
References frameNumber().
setTimestamp()
void VideoFrameMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 113 of file videoframemessage.cpp.
 {
     Q_D(VideoFrameMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setTimestampMs()
void VideoFrameMessage::setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
Parameters
timestampMs The field value to set.
Definition at line 123 of file videoframemessage.cpp.
 {
     Q_D(VideoFrameMessage);
     d->timestampMs = timestampMs;
 }
References timestampMs().
timestamp()
DateTime VideoFrameMessage::timestamp () const
Returns the VideoFrameMessage data message's timestamp field's current value.
Whole second part of the timestamp
Returns
the timestamp field value.
Definition at line 76 of file videoframemessage.cpp.
 {
     Q_D(const VideoFrameMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
timestampMs()
quint16 VideoFrameMessage::timestampMs () const
Returns the VideoFrameMessage data message's timestampMs field's current value.
Millisecond part of the timestamp.
Returns
the timestampMs field value.
Definition at line 89 of file videoframemessage.cpp.
 {
     Q_D(const VideoFrameMessage);
     return d->timestampMs;
 }
Referenced by setTimestampMs().
The documentation for this class was generated from the following files:
videoframemessage.h
videoframemessage.cpp