QtFit: MonitoringInfoMessage Class Reference
MonitoringInfoMessage Class Reference
The MonitoringInfoMessage class represents a FIT MonitoringInfoMessage data message.
Public Member Functions
MonitoringInfoMessage ()
Constructs a MonitoringInfoMessage object.
DateTime timestamp () const
Returns the MonitoringInfoMessage data message's timestamp field's current value.
LocalDateTime localTimestamp () const
Returns the MonitoringInfoMessage data message's localTimestamp field's current value.
ActivityType activityType () const
Returns the MonitoringInfoMessage data message's activityType field's current value.
quint16 cyclesToDistance () const
Returns the MonitoringInfoMessage data message's cyclesToDistance field's current value.
quint16 cyclesToCalories () const
Returns the MonitoringInfoMessage data message's cyclesToCalories field's current value.
quint16 restingMetabolicRate () const
Returns the MonitoringInfoMessage data message's restingMetabolicRate field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setLocalTimestamp (const LocalDateTime localTimestamp)
Sets the localTimestamp field to localTimestamp.
void setActivityType (const ActivityType activityType)
Sets the activityType field to activityType.
void setCyclesToDistance (const quint16 cyclesToDistance)
Sets the cyclesToDistance field to cyclesToDistance.
void setCyclesToCalories (const quint16 cyclesToCalories)
Sets the cyclesToCalories field to cyclesToCalories.
void setRestingMetabolicRate (const quint16 restingMetabolicRate)
Sets the restingMetabolicRate field to restingMetabolicRate.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
MonitoringInfoMessage (MonitoringInfoMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The MonitoringInfoMessage class represents a FIT MonitoringInfoMessage data message.
See also
DataMessage
Definition at line 34 of file monitoringinfomessage.h.
Constructor & Destructor Documentation
MonitoringInfoMessage() [1/2]
MonitoringInfoMessage::MonitoringInfoMessage ()
Constructs a MonitoringInfoMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file monitoringinfomessage.cpp.
                                              : AbstractDataMessage(new MonitoringInfoMessagePrivate(this))
 {
 }
MonitoringInfoMessage() [2/2]
MonitoringInfoMessage::MonitoringInfoMessage (MonitoringInfoMessagePrivate *const d) explicit protected
Constructs a MonitoringInfoMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file monitoringinfomessage.cpp.
                                                                                    : AbstractDataMessage(d)
 {
 }
Member Function Documentation
activityType()
ActivityType MonitoringInfoMessage::activityType () const
Returns the MonitoringInfoMessage data message's activityType field's current value.
Returns
the activityType field value.
Definition at line 94 of file monitoringinfomessage.cpp.
 {
     Q_D(const MonitoringInfoMessage);
     return d->activityType;
 }
Referenced by setActivityType().
cyclesToCalories()
quint16 MonitoringInfoMessage::cyclesToCalories () const
Returns the MonitoringInfoMessage data message's cyclesToCalories field's current value.
Indexed by activity_type
Returns
the cyclesToCalories field value.
Definition at line 120 of file monitoringinfomessage.cpp.
 {
     Q_D(const MonitoringInfoMessage);
     return d->cyclesToCalories;
 }
Referenced by setCyclesToCalories().
cyclesToDistance()
quint16 MonitoringInfoMessage::cyclesToDistance () const
Returns the MonitoringInfoMessage data message's cyclesToDistance field's current value.
Indexed by activity_type
Returns
the cyclesToDistance field value.
Definition at line 107 of file monitoringinfomessage.cpp.
 {
     Q_D(const MonitoringInfoMessage);
     return d->cyclesToDistance;
 }
Referenced by setCyclesToDistance().
localTimestamp()
LocalDateTime MonitoringInfoMessage::localTimestamp () const
Returns the MonitoringInfoMessage data message's localTimestamp field's current value.
Use to convert activity timestamps to local time if device does not support time zone and daylight savings time correction.
Returns
the localTimestamp field value.
Definition at line 83 of file monitoringinfomessage.cpp.
 {
     Q_D(const MonitoringInfoMessage);
     return d->localTimestamp;
 }
Referenced by setLocalTimestamp().
restingMetabolicRate()
quint16 MonitoringInfoMessage::restingMetabolicRate () const
Returns the MonitoringInfoMessage data message's restingMetabolicRate field's current value.
Returns
the restingMetabolicRate field value.
Definition at line 131 of file monitoringinfomessage.cpp.
 {
     Q_D(const MonitoringInfoMessage);
     return d->restingMetabolicRate;
 }
Referenced by setRestingMetabolicRate().
setActivityType()
void MonitoringInfoMessage::setActivityType (const ActivityType activityType)
Sets the activityType field to activityType.
Parameters
activityType The field value to set.
Definition at line 162 of file monitoringinfomessage.cpp.
 {
     Q_D(MonitoringInfoMessage);
     d->activityType = activityType;
 }
References activityType().
setCyclesToCalories()
void MonitoringInfoMessage::setCyclesToCalories (const quint16 cyclesToCalories)
Sets the cyclesToCalories field to cyclesToCalories.
Parameters
cyclesToCalories The field value to set.
Definition at line 182 of file monitoringinfomessage.cpp.
 {
     Q_D(MonitoringInfoMessage);
     d->cyclesToCalories = cyclesToCalories;
 }
References cyclesToCalories().
setCyclesToDistance()
void MonitoringInfoMessage::setCyclesToDistance (const quint16 cyclesToDistance)
Sets the cyclesToDistance field to cyclesToDistance.
Parameters
cyclesToDistance The field value to set.
Definition at line 172 of file monitoringinfomessage.cpp.
 {
     Q_D(MonitoringInfoMessage);
     d->cyclesToDistance = cyclesToDistance;
 }
References cyclesToDistance().
setLocalTimestamp()
void MonitoringInfoMessage::setLocalTimestamp (const LocalDateTime localTimestamp)
Sets the localTimestamp field to localTimestamp.
Parameters
localTimestamp The field value to set.
Definition at line 152 of file monitoringinfomessage.cpp.
 {
     Q_D(MonitoringInfoMessage);
     d->localTimestamp = localTimestamp;
 }
References localTimestamp().
setRestingMetabolicRate()
void MonitoringInfoMessage::setRestingMetabolicRate (const quint16 restingMetabolicRate)
Sets the restingMetabolicRate field to restingMetabolicRate.
Parameters
restingMetabolicRate The field value to set.
Definition at line 192 of file monitoringinfomessage.cpp.
 {
     Q_D(MonitoringInfoMessage);
     d->restingMetabolicRate = restingMetabolicRate;
 }
References restingMetabolicRate().
setTimestamp()
void MonitoringInfoMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 142 of file monitoringinfomessage.cpp.
 {
     Q_D(MonitoringInfoMessage);
     d->timestamp = timestamp;
 }
References timestamp().
timestamp()
DateTime MonitoringInfoMessage::timestamp () const
Returns the MonitoringInfoMessage data message's timestamp field's current value.
Returns
the timestamp field value.
Definition at line 69 of file monitoringinfomessage.cpp.
 {
     Q_D(const MonitoringInfoMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
The documentation for this class was generated from the following files:
monitoringinfomessage.h
monitoringinfomessage.cpp