QtFit: NmeaSentenceMessage Class Reference
NmeaSentenceMessage Class Reference
The NmeaSentenceMessage class represents a FIT NmeaSentenceMessage data message.
Public Member Functions
NmeaSentenceMessage ()
Constructs a NmeaSentenceMessage object.
DateTime timestamp () const
Returns the NmeaSentenceMessage data message's timestamp field's current value.
quint16 timestampMs () const
Returns the NmeaSentenceMessage data message's timestampMs field's current value.
QString sentence () const
Returns the NmeaSentenceMessage data message's sentence field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
void setSentence (const QString sentence)
Sets the sentence field to sentence.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
NmeaSentenceMessage (NmeaSentenceMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The NmeaSentenceMessage class represents a FIT NmeaSentenceMessage data message.
See also
DataMessage
Definition at line 34 of file nmeasentencemessage.h.
Constructor & Destructor Documentation
NmeaSentenceMessage() [1/2]
NmeaSentenceMessage::NmeaSentenceMessage ()
Constructs a NmeaSentenceMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file nmeasentencemessage.cpp.
                                          : AbstractDataMessage(new NmeaSentenceMessagePrivate(this))
 {
 }
NmeaSentenceMessage() [2/2]
NmeaSentenceMessage::NmeaSentenceMessage (NmeaSentenceMessagePrivate *const d) explicit protected
Constructs a NmeaSentenceMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file nmeasentencemessage.cpp.
                                                                              : AbstractDataMessage(d)
 {
 }
Member Function Documentation
sentence()
QString NmeaSentenceMessage::sentence () const
Returns the NmeaSentenceMessage data message's sentence field's current value.
NMEA sentence
Returns
the sentence field value.
Definition at line 97 of file nmeasentencemessage.cpp.
 {
     Q_D(const NmeaSentenceMessage);
     return d->sentence;
 }
Referenced by setSentence().
setSentence()
void NmeaSentenceMessage::setSentence (const QString sentence)
Sets the sentence field to sentence.
Parameters
sentence The field value to set.
Definition at line 128 of file nmeasentencemessage.cpp.
 {
     Q_D(NmeaSentenceMessage);
     d->sentence = sentence;
 }
References sentence().
setTimestamp()
void NmeaSentenceMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 108 of file nmeasentencemessage.cpp.
 {
     Q_D(NmeaSentenceMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setTimestampMs()
void NmeaSentenceMessage::setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
Parameters
timestampMs The field value to set.
Definition at line 118 of file nmeasentencemessage.cpp.
 {
     Q_D(NmeaSentenceMessage);
     d->timestampMs = timestampMs;
 }
References timestampMs().
timestamp()
DateTime NmeaSentenceMessage::timestamp () const
Returns the NmeaSentenceMessage data message's timestamp field's current value.
Timestamp message was output
Returns
the timestamp field value.
Definition at line 71 of file nmeasentencemessage.cpp.
 {
     Q_D(const NmeaSentenceMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
timestampMs()
quint16 NmeaSentenceMessage::timestampMs () const
Returns the NmeaSentenceMessage data message's timestampMs field's current value.
Fractional part of timestamp, added to timestamp
Returns
the timestampMs field value.
Definition at line 84 of file nmeasentencemessage.cpp.
 {
     Q_D(const NmeaSentenceMessage);
     return d->timestampMs;
 }
Referenced by setTimestampMs().
The documentation for this class was generated from the following files:
nmeasentencemessage.h
nmeasentencemessage.cpp