QtFit: CourseMessage Class Reference
CourseMessage Class Reference
The CourseMessage class represents a FIT CourseMessage data message.
Public Member Functions
CourseMessage ()
Constructs a CourseMessage object.
Sport sport () const
Returns the CourseMessage data message's sport field's current value.
QString name () const
Returns the CourseMessage data message's name field's current value.
CourseCapabilities capabilities () const
Returns the CourseMessage data message's capabilities field's current value.
SubSport subSport () const
Returns the CourseMessage data message's subSport field's current value.
void setSport (const Sport sport)
Sets the sport field to sport.
void setName (const QString name)
Sets the name field to name.
void setCapabilities (const CourseCapabilities capabilities)
Sets the capabilities field to capabilities.
void setSubSport (const SubSport subSport)
Sets the subSport field to subSport.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
CourseMessage (CourseMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The CourseMessage class represents a FIT CourseMessage data message.
See also
DataMessage
Definition at line 39 of file coursemessage.h.
Constructor & Destructor Documentation
CourseMessage() [1/2]
CourseMessage::CourseMessage ()
Constructs a CourseMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file coursemessage.cpp.
                              : AbstractDataMessage(new CourseMessagePrivate(this))
 {
 }
CourseMessage() [2/2]
CourseMessage::CourseMessage (CourseMessagePrivate *const d) explicit protected
Constructs a CourseMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file coursemessage.cpp.
                                                            : AbstractDataMessage(d)
 {
 }
Member Function Documentation
capabilities()
CourseCapabilities CourseMessage::capabilities () const
Returns the CourseMessage data message's capabilities field's current value.
Returns
the capabilities field value.
Definition at line 96 of file coursemessage.cpp.
 {
     Q_D(const CourseMessage);
     return d->capabilities;
 }
Referenced by setCapabilities().
name()
QString CourseMessage::name () const
Returns the CourseMessage data message's name field's current value.
Returns
the name field value.
Definition at line 85 of file coursemessage.cpp.
 {
     Q_D(const CourseMessage);
     return d->name;
 }
Referenced by setName().
setCapabilities()
void CourseMessage::setCapabilities (const CourseCapabilities capabilities)
Sets the capabilities field to capabilities.
Parameters
capabilities The field value to set.
Definition at line 138 of file coursemessage.cpp.
 {
     Q_D(CourseMessage);
     d->capabilities = capabilities;
 }
References capabilities().
setName()
void CourseMessage::setName (const QString name)
Sets the name field to name.
Parameters
name The field value to set.
Definition at line 128 of file coursemessage.cpp.
 {
     Q_D(CourseMessage);
     d->name = name;
 }
References name().
setSport()
void CourseMessage::setSport (const Sport sport)
Sets the sport field to sport.
Parameters
sport The field value to set.
Definition at line 118 of file coursemessage.cpp.
 {
     Q_D(CourseMessage);
     d->sport = sport;
 }
References sport().
setSubSport()
void CourseMessage::setSubSport (const SubSport subSport)
Sets the subSport field to subSport.
Parameters
subSport The field value to set.
Definition at line 148 of file coursemessage.cpp.
 {
     Q_D(CourseMessage);
     d->subSport = subSport;
 }
References subSport().
sport()
Sport CourseMessage::sport () const
Returns the CourseMessage data message's sport field's current value.
Returns
the sport field value.
Definition at line 74 of file coursemessage.cpp.
 {
     Q_D(const CourseMessage);
     return d->sport;
 }
Referenced by setSport().
subSport()
SubSport CourseMessage::subSport () const
Returns the CourseMessage data message's subSport field's current value.
Returns
the subSport field value.
Definition at line 107 of file coursemessage.cpp.
 {
     Q_D(const CourseMessage);
     return d->subSport;
 }
Referenced by setSubSport().
The documentation for this class was generated from the following files:
coursemessage.h
coursemessage.cpp