QtFit: EventMessage Class Reference
EventMessage Class Reference
The EventMessage class represents a FIT EventMessage data message.
Public Member Functions
EventMessage ()
Constructs a EventMessage object.
DateTime timestamp () const
Returns the EventMessage data message's timestamp field's current value.
Event event () const
Returns the EventMessage data message's event field's current value.
EventType eventType () const
Returns the EventMessage data message's eventType field's current value.
quint16 data16 () const
Returns the EventMessage data message's data16 field's current value.
quint32 data () const
Returns the EventMessage data message's data field's current value.
quint8 eventGroup () const
Returns the EventMessage data message's eventGroup field's current value.
quint16 score () const
Returns the EventMessage data message's score field's current value.
quint16 opponentScore () const
Returns the EventMessage data message's opponentScore field's current value.
quint8z frontGearNum () const
Returns the EventMessage data message's frontGearNum field's current value.
quint8z frontGear () const
Returns the EventMessage data message's frontGear field's current value.
quint8z rearGearNum () const
Returns the EventMessage data message's rearGearNum field's current value.
quint8z rearGear () const
Returns the EventMessage data message's rearGear field's current value.
DeviceIndex deviceIndex () const
Returns the EventMessage data message's deviceIndex field's current value.
RadarThreatLevelType radarThreatLevelMax () const
Returns the EventMessage data message's radarThreatLevelMax field's current value.
quint8 radarThreatCount () const
Returns the EventMessage data message's radarThreatCount field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setEvent (const Event event)
Sets the event field to event.
void setEventType (const EventType eventType)
Sets the eventType field to eventType.
void setData16 (const quint16 data16)
Sets the data16 field to data16.
void setData (const quint32 data)
Sets the data field to data.
void setEventGroup (const quint8 eventGroup)
Sets the eventGroup field to eventGroup.
void setScore (const quint16 score)
Sets the score field to score.
void setOpponentScore (const quint16 opponentScore)
Sets the opponentScore field to opponentScore.
void setFrontGearNum (const quint8z frontGearNum)
Sets the frontGearNum field to frontGearNum.
void setFrontGear (const quint8z frontGear)
Sets the frontGear field to frontGear.
void setRearGearNum (const quint8z rearGearNum)
Sets the rearGearNum field to rearGearNum.
void setRearGear (const quint8z rearGear)
Sets the rearGear field to rearGear.
void setDeviceIndex (const DeviceIndex deviceIndex)
Sets the deviceIndex field to deviceIndex.
void setRadarThreatLevelMax (const RadarThreatLevelType radarThreatLevelMax)
Sets the radarThreatLevelMax field to radarThreatLevelMax.
void setRadarThreatCount (const quint8 radarThreatCount)
Sets the radarThreatCount field to radarThreatCount.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
EventMessage (EventMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The EventMessage class represents a FIT EventMessage data message.
See also
DataMessage
Definition at line 34 of file eventmessage.h.
Constructor & Destructor Documentation
EventMessage() [1/2]
EventMessage::EventMessage ()
Constructs a EventMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file eventmessage.cpp.
                            : AbstractDataMessage(new EventMessagePrivate(this))
 {
 }
EventMessage() [2/2]
EventMessage::EventMessage (EventMessagePrivate *const d) explicit protected
Constructs a EventMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file eventmessage.cpp.
                                                         : AbstractDataMessage(d)
 {
 }
Member Function Documentation
data()
quint32 EventMessage::data () const
Returns the EventMessage data message's data field's current value.
Returns
the data field value.
Definition at line 113 of file eventmessage.cpp.
 {
     Q_D(const EventMessage);
     return d->data;
 }
Referenced by setData().
data16()
quint16 EventMessage::data16 () const
Returns the EventMessage data message's data16 field's current value.
Returns
the data16 field value.
Definition at line 102 of file eventmessage.cpp.
 {
     Q_D(const EventMessage);
     return d->data16;
 }
Referenced by setData16().
deviceIndex()
DeviceIndex EventMessage::deviceIndex () const
Returns the EventMessage data message's deviceIndex field's current value.
Returns
the deviceIndex field value.
Definition at line 217 of file eventmessage.cpp.
 {
     Q_D(const EventMessage);
     return d->deviceIndex;
 }
Referenced by setDeviceIndex().
event()
Event EventMessage::event () const
Returns the EventMessage data message's event field's current value.
Returns
the event field value.
Definition at line 80 of file eventmessage.cpp.
 {
     Q_D(const EventMessage);
     return d->event;
 }
Referenced by setEvent().
eventGroup()
quint8 EventMessage::eventGroup () const
Returns the EventMessage data message's eventGroup field's current value.
Returns
the eventGroup field value.
Definition at line 124 of file eventmessage.cpp.
 {
     Q_D(const EventMessage);
     return d->eventGroup;
 }
Referenced by setEventGroup().
eventType()
EventType EventMessage::eventType () const
Returns the EventMessage data message's eventType field's current value.
Returns
the eventType field value.
Definition at line 91 of file eventmessage.cpp.
 {
     Q_D(const EventMessage);
     return d->eventType;
 }
Referenced by setEventType().
frontGear()
quint8z EventMessage::frontGear () const
Returns the EventMessage data message's frontGear field's current value.
Do not populate directly. Autogenerated by decoder for gear_change subfield components. Number of front teeth.
Returns
the frontGear field value.
Definition at line 178 of file eventmessage.cpp.
 {
     Q_D(const EventMessage);
     return d->frontGear;
 }
Referenced by setFrontGear().
frontGearNum()
quint8z EventMessage::frontGearNum () const
Returns the EventMessage data message's frontGearNum field's current value.
Do not populate directly. Autogenerated by decoder for gear_change subfield components. Front gear number. 1 is innermost.
Returns
the frontGearNum field value.
Definition at line 164 of file eventmessage.cpp.
 {
     Q_D(const EventMessage);
     return d->frontGearNum;
 }
Referenced by setFrontGearNum().
opponentScore()
quint16 EventMessage::opponentScore () const
Returns the EventMessage data message's opponentScore field's current value.
Do not populate directly. Autogenerated by decoder for sport_point subfield components
Returns
the opponentScore field value.
Definition at line 150 of file eventmessage.cpp.
 {
     Q_D(const EventMessage);
     return d->opponentScore;
 }
Referenced by setOpponentScore().
radarThreatCount()
quint8 EventMessage::radarThreatCount () const
Returns the EventMessage data message's radarThreatCount field's current value.
Do not populate directly. Autogenerated by decoder for threat_alert subfield components.
Returns
the radarThreatCount field value.
Definition at line 243 of file eventmessage.cpp.
 {
     Q_D(const EventMessage);
     return d->radarThreatCount;
 }
Referenced by setRadarThreatCount().
radarThreatLevelMax()
RadarThreatLevelType EventMessage::radarThreatLevelMax () const
Returns the EventMessage data message's radarThreatLevelMax field's current value.
Do not populate directly. Autogenerated by decoder for threat_alert subfield components.
Returns
the radarThreatLevelMax field value.
Definition at line 230 of file eventmessage.cpp.
 {
     Q_D(const EventMessage);
     return d->radarThreatLevelMax;
 }
Referenced by setRadarThreatLevelMax().
rearGear()
quint8z EventMessage::rearGear () const
Returns the EventMessage data message's rearGear field's current value.
Do not populate directly. Autogenerated by decoder for gear_change subfield components. Number of rear teeth.
Returns
the rearGear field value.
Definition at line 206 of file eventmessage.cpp.
 {
     Q_D(const EventMessage);
     return d->rearGear;
 }
Referenced by setRearGear().
rearGearNum()
quint8z EventMessage::rearGearNum () const
Returns the EventMessage data message's rearGearNum field's current value.
Do not populate directly. Autogenerated by decoder for gear_change subfield components. Rear gear number. 1 is innermost.
Returns
the rearGearNum field value.
Definition at line 192 of file eventmessage.cpp.
 {
     Q_D(const EventMessage);
     return d->rearGearNum;
 }
Referenced by setRearGearNum().
score()
quint16 EventMessage::score () const
Returns the EventMessage data message's score field's current value.
Do not populate directly. Autogenerated by decoder for sport_point subfield components
Returns
the score field value.
Definition at line 137 of file eventmessage.cpp.
 {
     Q_D(const EventMessage);
     return d->score;
 }
Referenced by setScore().
setData()
void EventMessage::setData (const quint32 data)
Sets the data field to data.
Parameters
data The field value to set.
Definition at line 294 of file eventmessage.cpp.
 {
     Q_D(EventMessage);
     d->data = data;
 }
References data().
setData16()
void EventMessage::setData16 (const quint16 data16)
Sets the data16 field to data16.
Parameters
data16 The field value to set.
Definition at line 284 of file eventmessage.cpp.
 {
     Q_D(EventMessage);
     d->data16 = data16;
 }
References data16().
setDeviceIndex()
void EventMessage::setDeviceIndex (const DeviceIndex deviceIndex)
Sets the deviceIndex field to deviceIndex.
Parameters
deviceIndex The field value to set.
Definition at line 374 of file eventmessage.cpp.
 {
     Q_D(EventMessage);
     d->deviceIndex = deviceIndex;
 }
References deviceIndex().
setEvent()
void EventMessage::setEvent (const Event event)
Sets the event field to event.
Parameters
event The field value to set.
Definition at line 264 of file eventmessage.cpp.
 {
     Q_D(EventMessage);
     d->event = event;
 }
References event().
setEventGroup()
void EventMessage::setEventGroup (const quint8 eventGroup)
Sets the eventGroup field to eventGroup.
Parameters
eventGroup The field value to set.
Definition at line 304 of file eventmessage.cpp.
 {
     Q_D(EventMessage);
     d->eventGroup = eventGroup;
 }
References eventGroup().
setEventType()
void EventMessage::setEventType (const EventType eventType)
Sets the eventType field to eventType.
Parameters
eventType The field value to set.
Definition at line 274 of file eventmessage.cpp.
 {
     Q_D(EventMessage);
     d->eventType = eventType;
 }
References eventType().
setFrontGear()
void EventMessage::setFrontGear (const quint8z frontGear)
Sets the frontGear field to frontGear.
Parameters
frontGear The field value to set.
Definition at line 344 of file eventmessage.cpp.
 {
     Q_D(EventMessage);
     d->frontGear = frontGear;
 }
References frontGear().
setFrontGearNum()
void EventMessage::setFrontGearNum (const quint8z frontGearNum)
Sets the frontGearNum field to frontGearNum.
Parameters
frontGearNum The field value to set.
Definition at line 334 of file eventmessage.cpp.
 {
     Q_D(EventMessage);
     d->frontGearNum = frontGearNum;
 }
References frontGearNum().
setOpponentScore()
void EventMessage::setOpponentScore (const quint16 opponentScore)
Sets the opponentScore field to opponentScore.
Parameters
opponentScore The field value to set.
Definition at line 324 of file eventmessage.cpp.
 {
     Q_D(EventMessage);
     d->opponentScore = opponentScore;
 }
References opponentScore().
setRadarThreatCount()
void EventMessage::setRadarThreatCount (const quint8 radarThreatCount)
Sets the radarThreatCount field to radarThreatCount.
Parameters
radarThreatCount The field value to set.
Definition at line 394 of file eventmessage.cpp.
 {
     Q_D(EventMessage);
     d->radarThreatCount = radarThreatCount;
 }
References radarThreatCount().
setRadarThreatLevelMax()
void EventMessage::setRadarThreatLevelMax (const RadarThreatLevelType radarThreatLevelMax)
Sets the radarThreatLevelMax field to radarThreatLevelMax.
Parameters
radarThreatLevelMax The field value to set.
Definition at line 384 of file eventmessage.cpp.
 {
     Q_D(EventMessage);
     d->radarThreatLevelMax = radarThreatLevelMax;
 }
References radarThreatLevelMax().
setRearGear()
void EventMessage::setRearGear (const quint8z rearGear)
Sets the rearGear field to rearGear.
Parameters
rearGear The field value to set.
Definition at line 364 of file eventmessage.cpp.
 {
     Q_D(EventMessage);
     d->rearGear = rearGear;
 }
References rearGear().
setRearGearNum()
void EventMessage::setRearGearNum (const quint8z rearGearNum)
Sets the rearGearNum field to rearGearNum.
Parameters
rearGearNum The field value to set.
Definition at line 354 of file eventmessage.cpp.
 {
     Q_D(EventMessage);
     d->rearGearNum = rearGearNum;
 }
References rearGearNum().
setScore()
void EventMessage::setScore (const quint16 score)
Sets the score field to score.
Parameters
score The field value to set.
Definition at line 314 of file eventmessage.cpp.
 {
     Q_D(EventMessage);
     d->score = score;
 }
References score().
setTimestamp()
void EventMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 254 of file eventmessage.cpp.
 {
     Q_D(EventMessage);
     d->timestamp = timestamp;
 }
References timestamp().
timestamp()
DateTime EventMessage::timestamp () const
Returns the EventMessage data message's timestamp field's current value.
Returns
the timestamp field value.
Definition at line 69 of file eventmessage.cpp.
 {
     Q_D(const EventMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
The documentation for this class was generated from the following files:
eventmessage.h
eventmessage.cpp