QtFit: CameraEventMessage Class Reference
CameraEventMessage Class Reference
The CameraEventMessage class represents a FIT CameraEventMessage data message.
Public Member Functions
CameraEventMessage ()
Constructs a CameraEventMessage object.
DateTime timestamp () const
Returns the CameraEventMessage data message's timestamp field's current value.
quint16 timestampMs () const
Returns the CameraEventMessage data message's timestampMs field's current value.
CameraEventType cameraEventType () const
Returns the CameraEventMessage data message's cameraEventType field's current value.
QString cameraFileUuid () const
Returns the CameraEventMessage data message's cameraFileUuid field's current value.
CameraOrientationType cameraOrientation () const
Returns the CameraEventMessage data message's cameraOrientation field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
void setCameraEventType (const CameraEventType cameraEventType)
Sets the cameraEventType field to cameraEventType.
void setCameraFileUuid (const QString cameraFileUuid)
Sets the cameraFileUuid field to cameraFileUuid.
void setCameraOrientation (const CameraOrientationType cameraOrientation)
Sets the cameraOrientation field to cameraOrientation.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
CameraEventMessage (CameraEventMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The CameraEventMessage class represents a FIT CameraEventMessage data message.
See also
DataMessage
Definition at line 34 of file cameraeventmessage.h.
Constructor & Destructor Documentation
CameraEventMessage() [1/2]
CameraEventMessage::CameraEventMessage ()
Constructs a CameraEventMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file cameraeventmessage.cpp.
                                        : AbstractDataMessage(new CameraEventMessagePrivate(this))
 {
 }
CameraEventMessage() [2/2]
CameraEventMessage::CameraEventMessage (CameraEventMessagePrivate *const d) explicit protected
Constructs a CameraEventMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file cameraeventmessage.cpp.
                                                                           : AbstractDataMessage(d)
 {
 }
Member Function Documentation
cameraEventType()
CameraEventType CameraEventMessage::cameraEventType () const
Returns the CameraEventMessage data message's cameraEventType field's current value.
Returns
the cameraEventType field value.
Definition at line 95 of file cameraeventmessage.cpp.
 {
     Q_D(const CameraEventMessage);
     return d->cameraEventType;
 }
Referenced by setCameraEventType().
cameraFileUuid()
QString CameraEventMessage::cameraFileUuid () const
Returns the CameraEventMessage data message's cameraFileUuid field's current value.
Returns
the cameraFileUuid field value.
Definition at line 106 of file cameraeventmessage.cpp.
 {
     Q_D(const CameraEventMessage);
     return d->cameraFileUuid;
 }
Referenced by setCameraFileUuid().
cameraOrientation()
CameraOrientationType CameraEventMessage::cameraOrientation () const
Returns the CameraEventMessage data message's cameraOrientation field's current value.
Returns
the cameraOrientation field value.
Definition at line 117 of file cameraeventmessage.cpp.
 {
     Q_D(const CameraEventMessage);
     return d->cameraOrientation;
 }
Referenced by setCameraOrientation().
setCameraEventType()
void CameraEventMessage::setCameraEventType (const CameraEventType cameraEventType)
Sets the cameraEventType field to cameraEventType.
Parameters
cameraEventType The field value to set.
Definition at line 148 of file cameraeventmessage.cpp.
 {
     Q_D(CameraEventMessage);
     d->cameraEventType = cameraEventType;
 }
References cameraEventType().
setCameraFileUuid()
void CameraEventMessage::setCameraFileUuid (const QString cameraFileUuid)
Sets the cameraFileUuid field to cameraFileUuid.
Parameters
cameraFileUuid The field value to set.
Definition at line 158 of file cameraeventmessage.cpp.
 {
     Q_D(CameraEventMessage);
     d->cameraFileUuid = cameraFileUuid;
 }
References cameraFileUuid().
setCameraOrientation()
void CameraEventMessage::setCameraOrientation (const CameraOrientationType cameraOrientation)
Sets the cameraOrientation field to cameraOrientation.
Parameters
cameraOrientation The field value to set.
Definition at line 168 of file cameraeventmessage.cpp.
 {
     Q_D(CameraEventMessage);
     d->cameraOrientation = cameraOrientation;
 }
References cameraOrientation().
setTimestamp()
void CameraEventMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 128 of file cameraeventmessage.cpp.
 {
     Q_D(CameraEventMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setTimestampMs()
void CameraEventMessage::setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
Parameters
timestampMs The field value to set.
Definition at line 138 of file cameraeventmessage.cpp.
 {
     Q_D(CameraEventMessage);
     d->timestampMs = timestampMs;
 }
References timestampMs().
timestamp()
DateTime CameraEventMessage::timestamp () const
Returns the CameraEventMessage data message's timestamp field's current value.
Whole second part of the timestamp.
Returns
the timestamp field value.
Definition at line 71 of file cameraeventmessage.cpp.
 {
     Q_D(const CameraEventMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
timestampMs()
quint16 CameraEventMessage::timestampMs () const
Returns the CameraEventMessage data message's timestampMs field's current value.
Millisecond part of the timestamp.
Returns
the timestampMs field value.
Definition at line 84 of file cameraeventmessage.cpp.
 {
     Q_D(const CameraEventMessage);
     return d->timestampMs;
 }
Referenced by setTimestampMs().
The documentation for this class was generated from the following files:
cameraeventmessage.h
cameraeventmessage.cpp