QtFit: TotalsMessage Class Reference
TotalsMessage Class Reference
The TotalsMessage class represents a FIT TotalsMessage data message.
Public Member Functions
TotalsMessage ()
Constructs a TotalsMessage object.
MessageIndex messageIndex () const
Returns the TotalsMessage data message's messageIndex field's current value.
DateTime timestamp () const
Returns the TotalsMessage data message's timestamp field's current value.
quint32 timerTime () const
Returns the TotalsMessage data message's timerTime field's current value.
quint32 distance () const
Returns the TotalsMessage data message's distance field's current value.
quint32 calories () const
Returns the TotalsMessage data message's calories field's current value.
Sport sport () const
Returns the TotalsMessage data message's sport field's current value.
quint32 elapsedTime () const
Returns the TotalsMessage data message's elapsedTime field's current value.
quint16 sessions () const
Returns the TotalsMessage data message's sessions field's current value.
quint32 activeTime () const
Returns the TotalsMessage data message's activeTime field's current value.
quint8 sportIndex () const
Returns the TotalsMessage data message's sportIndex field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setTimerTime (const quint32 timerTime)
Sets the timerTime field to timerTime.
void setDistance (const quint32 distance)
Sets the distance field to distance.
void setCalories (const quint32 calories)
Sets the calories field to calories.
void setSport (const Sport sport)
Sets the sport field to sport.
void setElapsedTime (const quint32 elapsedTime)
Sets the elapsedTime field to elapsedTime.
void setSessions (const quint16 sessions)
Sets the sessions field to sessions.
void setActiveTime (const quint32 activeTime)
Sets the activeTime field to activeTime.
void setSportIndex (const quint8 sportIndex)
Sets the sportIndex field to sportIndex.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
TotalsMessage (TotalsMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The TotalsMessage class represents a FIT TotalsMessage data message.
See also
DataMessage
Definition at line 34 of file totalsmessage.h.
Constructor & Destructor Documentation
TotalsMessage() [1/2]
TotalsMessage::TotalsMessage ()
Constructs a TotalsMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file totalsmessage.cpp.
                              : AbstractDataMessage(new TotalsMessagePrivate(this))
 {
 }
TotalsMessage() [2/2]
TotalsMessage::TotalsMessage (TotalsMessagePrivate *const d) explicit protected
Constructs a TotalsMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file totalsmessage.cpp.
                                                            : AbstractDataMessage(d)
 {
 }
Member Function Documentation
activeTime()
quint32 TotalsMessage::activeTime () const
Returns the TotalsMessage data message's activeTime field's current value.
Returns
the activeTime field value.
Definition at line 161 of file totalsmessage.cpp.
 {
     Q_D(const TotalsMessage);
     return d->activeTime;
 }
Referenced by setActiveTime().
calories()
quint32 TotalsMessage::calories () const
Returns the TotalsMessage data message's calories field's current value.
Returns
the calories field value.
Definition at line 115 of file totalsmessage.cpp.
 {
     Q_D(const TotalsMessage);
     return d->calories;
 }
Referenced by setCalories().
distance()
quint32 TotalsMessage::distance () const
Returns the TotalsMessage data message's distance field's current value.
Returns
the distance field value.
Definition at line 104 of file totalsmessage.cpp.
 {
     Q_D(const TotalsMessage);
     return d->distance;
 }
Referenced by setDistance().
elapsedTime()
quint32 TotalsMessage::elapsedTime () const
Returns the TotalsMessage data message's elapsedTime field's current value.
Includes pauses
Returns
the elapsedTime field value.
Definition at line 139 of file totalsmessage.cpp.
 {
     Q_D(const TotalsMessage);
     return d->elapsedTime;
 }
Referenced by setElapsedTime().
messageIndex()
MessageIndex TotalsMessage::messageIndex () const
Returns the TotalsMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 69 of file totalsmessage.cpp.
 {
     Q_D(const TotalsMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
sessions()
quint16 TotalsMessage::sessions () const
Returns the TotalsMessage data message's sessions field's current value.
Returns
the sessions field value.
Definition at line 150 of file totalsmessage.cpp.
 {
     Q_D(const TotalsMessage);
     return d->sessions;
 }
Referenced by setSessions().
setActiveTime()
void TotalsMessage::setActiveTime (const quint32 activeTime)
Sets the activeTime field to activeTime.
Parameters
activeTime The field value to set.
Definition at line 263 of file totalsmessage.cpp.
 {
     Q_D(TotalsMessage);
     d->activeTime = activeTime;
 }
References activeTime().
setCalories()
void TotalsMessage::setCalories (const quint32 calories)
Sets the calories field to calories.
Parameters
calories The field value to set.
Definition at line 223 of file totalsmessage.cpp.
 {
     Q_D(TotalsMessage);
     d->calories = calories;
 }
References calories().
setDistance()
void TotalsMessage::setDistance (const quint32 distance)
Sets the distance field to distance.
Parameters
distance The field value to set.
Definition at line 213 of file totalsmessage.cpp.
 {
     Q_D(TotalsMessage);
     d->distance = distance;
 }
References distance().
setElapsedTime()
void TotalsMessage::setElapsedTime (const quint32 elapsedTime)
Sets the elapsedTime field to elapsedTime.
Parameters
elapsedTime The field value to set.
Definition at line 243 of file totalsmessage.cpp.
 {
     Q_D(TotalsMessage);
     d->elapsedTime = elapsedTime;
 }
References elapsedTime().
setMessageIndex()
void TotalsMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 183 of file totalsmessage.cpp.
 {
     Q_D(TotalsMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setSessions()
void TotalsMessage::setSessions (const quint16 sessions)
Sets the sessions field to sessions.
Parameters
sessions The field value to set.
Definition at line 253 of file totalsmessage.cpp.
 {
     Q_D(TotalsMessage);
     d->sessions = sessions;
 }
References sessions().
setSport()
void TotalsMessage::setSport (const Sport sport)
Sets the sport field to sport.
Parameters
sport The field value to set.
Definition at line 233 of file totalsmessage.cpp.
 {
     Q_D(TotalsMessage);
     d->sport = sport;
 }
References sport().
setSportIndex()
void TotalsMessage::setSportIndex (const quint8 sportIndex)
Sets the sportIndex field to sportIndex.
Parameters
sportIndex The field value to set.
Definition at line 273 of file totalsmessage.cpp.
 {
     Q_D(TotalsMessage);
     d->sportIndex = sportIndex;
 }
References sportIndex().
setTimerTime()
void TotalsMessage::setTimerTime (const quint32 timerTime)
Sets the timerTime field to timerTime.
Parameters
timerTime The field value to set.
Definition at line 203 of file totalsmessage.cpp.
 {
     Q_D(TotalsMessage);
     d->timerTime = timerTime;
 }
References timerTime().
setTimestamp()
void TotalsMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 193 of file totalsmessage.cpp.
 {
     Q_D(TotalsMessage);
     d->timestamp = timestamp;
 }
References timestamp().
sport()
Sport TotalsMessage::sport () const
Returns the TotalsMessage data message's sport field's current value.
Returns
the sport field value.
Definition at line 126 of file totalsmessage.cpp.
 {
     Q_D(const TotalsMessage);
     return d->sport;
 }
Referenced by setSport().
sportIndex()
quint8 TotalsMessage::sportIndex () const
Returns the TotalsMessage data message's sportIndex field's current value.
Returns
the sportIndex field value.
Definition at line 172 of file totalsmessage.cpp.
 {
     Q_D(const TotalsMessage);
     return d->sportIndex;
 }
Referenced by setSportIndex().
timerTime()
quint32 TotalsMessage::timerTime () const
Returns the TotalsMessage data message's timerTime field's current value.
Excludes pauses
Returns
the timerTime field value.
Definition at line 93 of file totalsmessage.cpp.
 {
     Q_D(const TotalsMessage);
     return d->timerTime;
 }
Referenced by setTimerTime().
timestamp()
DateTime TotalsMessage::timestamp () const
Returns the TotalsMessage data message's timestamp field's current value.
Returns
the timestamp field value.
Definition at line 80 of file totalsmessage.cpp.
 {
     Q_D(const TotalsMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
The documentation for this class was generated from the following files:
totalsmessage.h
totalsmessage.cpp