QtFit: MetZoneMessage Class Reference
MetZoneMessage Class Reference
The MetZoneMessage class represents a FIT MetZoneMessage data message.
Public Member Functions
MetZoneMessage ()
Constructs a MetZoneMessage object.
MessageIndex messageIndex () const
Returns the MetZoneMessage data message's messageIndex field's current value.
quint8 highBpm () const
Returns the MetZoneMessage data message's highBpm field's current value.
quint16 calories () const
Returns the MetZoneMessage data message's calories field's current value.
quint8 fatCalories () const
Returns the MetZoneMessage data message's fatCalories field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setHighBpm (const quint8 highBpm)
Sets the highBpm field to highBpm.
void setCalories (const quint16 calories)
Sets the calories field to calories.
void setFatCalories (const quint8 fatCalories)
Sets the fatCalories field to fatCalories.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
MetZoneMessage (MetZoneMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The MetZoneMessage class represents a FIT MetZoneMessage data message.
See also
DataMessage
Definition at line 39 of file metzonemessage.h.
Constructor & Destructor Documentation
MetZoneMessage() [1/2]
MetZoneMessage::MetZoneMessage ()
Constructs a MetZoneMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file metzonemessage.cpp.
                                : AbstractDataMessage(new MetZoneMessagePrivate(this))
 {
 }
MetZoneMessage() [2/2]
MetZoneMessage::MetZoneMessage (MetZoneMessagePrivate *const d) explicit protected
Constructs a MetZoneMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file metzonemessage.cpp.
                                                               : AbstractDataMessage(d)
 {
 }
Member Function Documentation
calories()
quint16 MetZoneMessage::calories () const
Returns the MetZoneMessage data message's calories field's current value.
Returns
the calories field value.
Definition at line 96 of file metzonemessage.cpp.
 {
     Q_D(const MetZoneMessage);
     return d->calories;
 }
Referenced by setCalories().
fatCalories()
quint8 MetZoneMessage::fatCalories () const
Returns the MetZoneMessage data message's fatCalories field's current value.
Returns
the fatCalories field value.
Definition at line 107 of file metzonemessage.cpp.
 {
     Q_D(const MetZoneMessage);
     return d->fatCalories;
 }
Referenced by setFatCalories().
highBpm()
quint8 MetZoneMessage::highBpm () const
Returns the MetZoneMessage data message's highBpm field's current value.
Returns
the highBpm field value.
Definition at line 85 of file metzonemessage.cpp.
 {
     Q_D(const MetZoneMessage);
     return d->highBpm;
 }
Referenced by setHighBpm().
messageIndex()
MessageIndex MetZoneMessage::messageIndex () const
Returns the MetZoneMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 74 of file metzonemessage.cpp.
 {
     Q_D(const MetZoneMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
setCalories()
void MetZoneMessage::setCalories (const quint16 calories)
Sets the calories field to calories.
Parameters
calories The field value to set.
Definition at line 138 of file metzonemessage.cpp.
 {
     Q_D(MetZoneMessage);
     d->calories = calories;
 }
References calories().
setFatCalories()
void MetZoneMessage::setFatCalories (const quint8 fatCalories)
Sets the fatCalories field to fatCalories.
Parameters
fatCalories The field value to set.
Definition at line 148 of file metzonemessage.cpp.
 {
     Q_D(MetZoneMessage);
     d->fatCalories = fatCalories;
 }
References fatCalories().
setHighBpm()
void MetZoneMessage::setHighBpm (const quint8 highBpm)
Sets the highBpm field to highBpm.
Parameters
highBpm The field value to set.
Definition at line 128 of file metzonemessage.cpp.
 {
     Q_D(MetZoneMessage);
     d->highBpm = highBpm;
 }
References highBpm().
setMessageIndex()
void MetZoneMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 118 of file metzonemessage.cpp.
 {
     Q_D(MetZoneMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
The documentation for this class was generated from the following files:
metzonemessage.h
metzonemessage.cpp