QtFit: ConnectivityMessage Class Reference
ConnectivityMessage Class Reference
The ConnectivityMessage class represents a FIT ConnectivityMessage data message.
Public Member Functions
ConnectivityMessage ()
Constructs a ConnectivityMessage object.
bool bluetoothEnabled () const
Returns the ConnectivityMessage data message's bluetoothEnabled field's current value.
bool bluetoothLeEnabled () const
Returns the ConnectivityMessage data message's bluetoothLeEnabled field's current value.
bool antEnabled () const
Returns the ConnectivityMessage data message's antEnabled field's current value.
QString name () const
Returns the ConnectivityMessage data message's name field's current value.
bool liveTrackingEnabled () const
Returns the ConnectivityMessage data message's liveTrackingEnabled field's current value.
bool weatherConditionsEnabled () const
Returns the ConnectivityMessage data message's weatherConditionsEnabled field's current value.
bool weatherAlertsEnabled () const
Returns the ConnectivityMessage data message's weatherAlertsEnabled field's current value.
bool autoActivityUploadEnabled () const
Returns the ConnectivityMessage data message's autoActivityUploadEnabled field's current value.
bool courseDownloadEnabled () const
Returns the ConnectivityMessage data message's courseDownloadEnabled field's current value.
bool workoutDownloadEnabled () const
Returns the ConnectivityMessage data message's workoutDownloadEnabled field's current value.
bool gpsEphemerisDownloadEnabled () const
Returns the ConnectivityMessage data message's gpsEphemerisDownloadEnabled field's current value.
bool incidentDetectionEnabled () const
Returns the ConnectivityMessage data message's incidentDetectionEnabled field's current value.
bool grouptrackEnabled () const
Returns the ConnectivityMessage data message's grouptrackEnabled field's current value.
void setBluetoothEnabled (const bool bluetoothEnabled)
Sets the bluetoothEnabled field to bluetoothEnabled.
void setBluetoothLeEnabled (const bool bluetoothLeEnabled)
Sets the bluetoothLeEnabled field to bluetoothLeEnabled.
void setAntEnabled (const bool antEnabled)
Sets the antEnabled field to antEnabled.
void setName (const QString name)
Sets the name field to name.
void setLiveTrackingEnabled (const bool liveTrackingEnabled)
Sets the liveTrackingEnabled field to liveTrackingEnabled.
void setWeatherConditionsEnabled (const bool weatherConditionsEnabled)
Sets the weatherConditionsEnabled field to weatherConditionsEnabled.
void setWeatherAlertsEnabled (const bool weatherAlertsEnabled)
Sets the weatherAlertsEnabled field to weatherAlertsEnabled.
void setAutoActivityUploadEnabled (const bool autoActivityUploadEnabled)
Sets the autoActivityUploadEnabled field to autoActivityUploadEnabled.
void setCourseDownloadEnabled (const bool courseDownloadEnabled)
Sets the courseDownloadEnabled field to courseDownloadEnabled.
void setWorkoutDownloadEnabled (const bool workoutDownloadEnabled)
Sets the workoutDownloadEnabled field to workoutDownloadEnabled.
void setGpsEphemerisDownloadEnabled (const bool gpsEphemerisDownloadEnabled)
Sets the gpsEphemerisDownloadEnabled field to gpsEphemerisDownloadEnabled.
void setIncidentDetectionEnabled (const bool incidentDetectionEnabled)
Sets the incidentDetectionEnabled field to incidentDetectionEnabled.
void setGrouptrackEnabled (const bool grouptrackEnabled)
Sets the grouptrackEnabled field to grouptrackEnabled.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
ConnectivityMessage (ConnectivityMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The ConnectivityMessage class represents a FIT ConnectivityMessage data message.
See also
DataMessage
Definition at line 39 of file connectivitymessage.h.
Constructor & Destructor Documentation
ConnectivityMessage() [1/2]
ConnectivityMessage::ConnectivityMessage ()
Constructs a ConnectivityMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file connectivitymessage.cpp.
                                          : AbstractDataMessage(new ConnectivityMessagePrivate(this))
 {
 }
ConnectivityMessage() [2/2]
ConnectivityMessage::ConnectivityMessage (ConnectivityMessagePrivate *const d) explicit protected
Constructs a ConnectivityMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file connectivitymessage.cpp.
                                                                              : AbstractDataMessage(d)
 {
 }
Member Function Documentation
antEnabled()
bool ConnectivityMessage::antEnabled () const
Returns the ConnectivityMessage data message's antEnabled field's current value.
Use ANT for connectivity features
Returns
the antEnabled field value.
Definition at line 102 of file connectivitymessage.cpp.
 {
     Q_D(const ConnectivityMessage);
     return d->antEnabled;
 }
Referenced by setAntEnabled().
autoActivityUploadEnabled()
bool ConnectivityMessage::autoActivityUploadEnabled () const
Returns the ConnectivityMessage data message's autoActivityUploadEnabled field's current value.
Returns
the autoActivityUploadEnabled field value.
Definition at line 157 of file connectivitymessage.cpp.
 {
     Q_D(const ConnectivityMessage);
     return d->autoActivityUploadEnabled;
 }
Referenced by setAutoActivityUploadEnabled().
bluetoothEnabled()
bool ConnectivityMessage::bluetoothEnabled () const
Returns the ConnectivityMessage data message's bluetoothEnabled field's current value.
Use Bluetooth for connectivity features
Returns
the bluetoothEnabled field value.
Definition at line 76 of file connectivitymessage.cpp.
 {
     Q_D(const ConnectivityMessage);
     return d->bluetoothEnabled;
 }
Referenced by setBluetoothEnabled().
bluetoothLeEnabled()
bool ConnectivityMessage::bluetoothLeEnabled () const
Returns the ConnectivityMessage data message's bluetoothLeEnabled field's current value.
Use Bluetooth Low Energy for connectivity features
Returns
the bluetoothLeEnabled field value.
Definition at line 89 of file connectivitymessage.cpp.
 {
     Q_D(const ConnectivityMessage);
     return d->bluetoothLeEnabled;
 }
Referenced by setBluetoothLeEnabled().
courseDownloadEnabled()
bool ConnectivityMessage::courseDownloadEnabled () const
Returns the ConnectivityMessage data message's courseDownloadEnabled field's current value.
Returns
the courseDownloadEnabled field value.
Definition at line 168 of file connectivitymessage.cpp.
 {
     Q_D(const ConnectivityMessage);
     return d->courseDownloadEnabled;
 }
Referenced by setCourseDownloadEnabled().
gpsEphemerisDownloadEnabled()
bool ConnectivityMessage::gpsEphemerisDownloadEnabled () const
Returns the ConnectivityMessage data message's gpsEphemerisDownloadEnabled field's current value.
Returns
the gpsEphemerisDownloadEnabled field value.
Definition at line 190 of file connectivitymessage.cpp.
 {
     Q_D(const ConnectivityMessage);
     return d->gpsEphemerisDownloadEnabled;
 }
Referenced by setGpsEphemerisDownloadEnabled().
grouptrackEnabled()
bool ConnectivityMessage::grouptrackEnabled () const
Returns the ConnectivityMessage data message's grouptrackEnabled field's current value.
Returns
the grouptrackEnabled field value.
Definition at line 212 of file connectivitymessage.cpp.
 {
     Q_D(const ConnectivityMessage);
     return d->grouptrackEnabled;
 }
Referenced by setGrouptrackEnabled().
incidentDetectionEnabled()
bool ConnectivityMessage::incidentDetectionEnabled () const
Returns the ConnectivityMessage data message's incidentDetectionEnabled field's current value.
Returns
the incidentDetectionEnabled field value.
Definition at line 201 of file connectivitymessage.cpp.
 {
     Q_D(const ConnectivityMessage);
     return d->incidentDetectionEnabled;
 }
Referenced by setIncidentDetectionEnabled().
liveTrackingEnabled()
bool ConnectivityMessage::liveTrackingEnabled () const
Returns the ConnectivityMessage data message's liveTrackingEnabled field's current value.
Returns
the liveTrackingEnabled field value.
Definition at line 124 of file connectivitymessage.cpp.
 {
     Q_D(const ConnectivityMessage);
     return d->liveTrackingEnabled;
 }
Referenced by setLiveTrackingEnabled().
name()
QString ConnectivityMessage::name () const
Returns the ConnectivityMessage data message's name field's current value.
Returns
the name field value.
Definition at line 113 of file connectivitymessage.cpp.
 {
     Q_D(const ConnectivityMessage);
     return d->name;
 }
Referenced by setName().
setAntEnabled()
void ConnectivityMessage::setAntEnabled (const bool antEnabled)
Sets the antEnabled field to antEnabled.
Parameters
antEnabled The field value to set.
Definition at line 243 of file connectivitymessage.cpp.
 {
     Q_D(ConnectivityMessage);
     d->antEnabled = antEnabled;
 }
References antEnabled().
setAutoActivityUploadEnabled()
void ConnectivityMessage::setAutoActivityUploadEnabled (const bool autoActivityUploadEnabled)
Sets the autoActivityUploadEnabled field to autoActivityUploadEnabled.
Parameters
autoActivityUploadEnabled The field value to set.
Definition at line 293 of file connectivitymessage.cpp.
 {
     Q_D(ConnectivityMessage);
     d->autoActivityUploadEnabled = autoActivityUploadEnabled;
 }
References autoActivityUploadEnabled().
setBluetoothEnabled()
void ConnectivityMessage::setBluetoothEnabled (const bool bluetoothEnabled)
Sets the bluetoothEnabled field to bluetoothEnabled.
Parameters
bluetoothEnabled The field value to set.
Definition at line 223 of file connectivitymessage.cpp.
 {
     Q_D(ConnectivityMessage);
     d->bluetoothEnabled = bluetoothEnabled;
 }
References bluetoothEnabled().
setBluetoothLeEnabled()
void ConnectivityMessage::setBluetoothLeEnabled (const bool bluetoothLeEnabled)
Sets the bluetoothLeEnabled field to bluetoothLeEnabled.
Parameters
bluetoothLeEnabled The field value to set.
Definition at line 233 of file connectivitymessage.cpp.
 {
     Q_D(ConnectivityMessage);
     d->bluetoothLeEnabled = bluetoothLeEnabled;
 }
References bluetoothLeEnabled().
setCourseDownloadEnabled()
void ConnectivityMessage::setCourseDownloadEnabled (const bool courseDownloadEnabled)
Sets the courseDownloadEnabled field to courseDownloadEnabled.
Parameters
courseDownloadEnabled The field value to set.
Definition at line 303 of file connectivitymessage.cpp.
 {
     Q_D(ConnectivityMessage);
     d->courseDownloadEnabled = courseDownloadEnabled;
 }
References courseDownloadEnabled().
setGpsEphemerisDownloadEnabled()
void ConnectivityMessage::setGpsEphemerisDownloadEnabled (const bool gpsEphemerisDownloadEnabled)
Sets the gpsEphemerisDownloadEnabled field to gpsEphemerisDownloadEnabled.
Parameters
gpsEphemerisDownloadEnabled The field value to set.
Definition at line 323 of file connectivitymessage.cpp.
 {
     Q_D(ConnectivityMessage);
     d->gpsEphemerisDownloadEnabled = gpsEphemerisDownloadEnabled;
 }
References gpsEphemerisDownloadEnabled().
setGrouptrackEnabled()
void ConnectivityMessage::setGrouptrackEnabled (const bool grouptrackEnabled)
Sets the grouptrackEnabled field to grouptrackEnabled.
Parameters
grouptrackEnabled The field value to set.
Definition at line 343 of file connectivitymessage.cpp.
 {
     Q_D(ConnectivityMessage);
     d->grouptrackEnabled = grouptrackEnabled;
 }
References grouptrackEnabled().
setIncidentDetectionEnabled()
void ConnectivityMessage::setIncidentDetectionEnabled (const bool incidentDetectionEnabled)
Sets the incidentDetectionEnabled field to incidentDetectionEnabled.
Parameters
incidentDetectionEnabled The field value to set.
Definition at line 333 of file connectivitymessage.cpp.
 {
     Q_D(ConnectivityMessage);
     d->incidentDetectionEnabled = incidentDetectionEnabled;
 }
References incidentDetectionEnabled().
setLiveTrackingEnabled()
void ConnectivityMessage::setLiveTrackingEnabled (const bool liveTrackingEnabled)
Sets the liveTrackingEnabled field to liveTrackingEnabled.
Parameters
liveTrackingEnabled The field value to set.
Definition at line 263 of file connectivitymessage.cpp.
 {
     Q_D(ConnectivityMessage);
     d->liveTrackingEnabled = liveTrackingEnabled;
 }
References liveTrackingEnabled().
setName()
void ConnectivityMessage::setName (const QString name)
Sets the name field to name.
Parameters
name The field value to set.
Definition at line 253 of file connectivitymessage.cpp.
 {
     Q_D(ConnectivityMessage);
     d->name = name;
 }
References name().
setWeatherAlertsEnabled()
void ConnectivityMessage::setWeatherAlertsEnabled (const bool weatherAlertsEnabled)
Sets the weatherAlertsEnabled field to weatherAlertsEnabled.
Parameters
weatherAlertsEnabled The field value to set.
Definition at line 283 of file connectivitymessage.cpp.
 {
     Q_D(ConnectivityMessage);
     d->weatherAlertsEnabled = weatherAlertsEnabled;
 }
References weatherAlertsEnabled().
setWeatherConditionsEnabled()
void ConnectivityMessage::setWeatherConditionsEnabled (const bool weatherConditionsEnabled)
Sets the weatherConditionsEnabled field to weatherConditionsEnabled.
Parameters
weatherConditionsEnabled The field value to set.
Definition at line 273 of file connectivitymessage.cpp.
 {
     Q_D(ConnectivityMessage);
     d->weatherConditionsEnabled = weatherConditionsEnabled;
 }
References weatherConditionsEnabled().
setWorkoutDownloadEnabled()
void ConnectivityMessage::setWorkoutDownloadEnabled (const bool workoutDownloadEnabled)
Sets the workoutDownloadEnabled field to workoutDownloadEnabled.
Parameters
workoutDownloadEnabled The field value to set.
Definition at line 313 of file connectivitymessage.cpp.
 {
     Q_D(ConnectivityMessage);
     d->workoutDownloadEnabled = workoutDownloadEnabled;
 }
References workoutDownloadEnabled().
weatherAlertsEnabled()
bool ConnectivityMessage::weatherAlertsEnabled () const
Returns the ConnectivityMessage data message's weatherAlertsEnabled field's current value.
Returns
the weatherAlertsEnabled field value.
Definition at line 146 of file connectivitymessage.cpp.
 {
     Q_D(const ConnectivityMessage);
     return d->weatherAlertsEnabled;
 }
Referenced by setWeatherAlertsEnabled().
weatherConditionsEnabled()
bool ConnectivityMessage::weatherConditionsEnabled () const
Returns the ConnectivityMessage data message's weatherConditionsEnabled field's current value.
Returns
the weatherConditionsEnabled field value.
Definition at line 135 of file connectivitymessage.cpp.
 {
     Q_D(const ConnectivityMessage);
     return d->weatherConditionsEnabled;
 }
Referenced by setWeatherConditionsEnabled().
workoutDownloadEnabled()
bool ConnectivityMessage::workoutDownloadEnabled () const
Returns the ConnectivityMessage data message's workoutDownloadEnabled field's current value.
Returns
the workoutDownloadEnabled field value.
Definition at line 179 of file connectivitymessage.cpp.
 {
     Q_D(const ConnectivityMessage);
     return d->workoutDownloadEnabled;
 }
Referenced by setWorkoutDownloadEnabled().
The documentation for this class was generated from the following files:
connectivitymessage.h
connectivitymessage.cpp