QtFit: FitDataMessagePrivate Class Reference
FitDataMessagePrivate Class Reference
#include <fitdatamessage_p.h>
Public Member Functions
FitDataMessagePrivate ()=delete
FitDataMessagePrivate (FitDataMessage *const q)
virtual ~FitDataMessagePrivate ()
bool setFields (const DataDefinition *const defn, const QByteArray &record)
Public Attributes
MesgNum globalMessageNumber
bool isNull
Protected Member Functions
virtual bool setField (const int fieldId, const QByteArray &data, const FitBaseType baseType, const bool bigEndian)
bool verify (const QByteArray &data, const FitBaseType actualType, const int expectedSize, const FitBaseType expectedType, const char *messageFieldName)
\interal
Protected Attributes
FitDataMessage *const q_ptr
Internal q-pointer.
Detailed Description
Definition at line 31 of file fitdatamessage_p.h.
Constructor & Destructor Documentation
FitDataMessagePrivate() [1/2]
FitDataMessagePrivate::FitDataMessagePrivate () delete
FitDataMessagePrivate() [2/2]
FitDataMessagePrivate::FitDataMessagePrivate (FitDataMessage *const q) explicit
Constructs a FitDataMessagePrivate object with public implementation q.
Parameters
q Pointer to public implementation.
Definition at line 118 of file fitdatamessage.cpp.
     : globalMessageNumber(static_cast<MesgNum>(0xFFFF)), isNull(true), q_ptr(q)
 {
 }
~FitDataMessagePrivate()
FitDataMessagePrivate::~FitDataMessagePrivate () virtual
Destroys the FitDataMessagePrivate object.
Definition at line 129 of file fitdatamessage.cpp.
 {
 }
Member Function Documentation
setField()
bool FitDataMessagePrivate::setField (const int fieldId, const QByteArray & data, const FitBaseType baseType, const bool bigEndian) protected virtual
Set a value of a data message field.
This base implementation simply logs a warning, and ignores the field. Derived classes should override this implementation to set the relevant class members.
Parameters
fieldId The field number within the given FIT data message.
data The raw data to extract the field value from.
baseType The FIT base type for the field.
bigEndian Whether or not multibyte values in record are big-endian.
Returns
true if the field was set, or skipped; false if the field was corrupt or invalid.
Reimplemented in ZonesTargetMessagePrivate, WorkoutStepMessagePrivate, WorkoutSessionMessagePrivate, WorkoutMessagePrivate, WeightScaleMessagePrivate, WeatherConditionsMessagePrivate, WeatherAlertMessagePrivate, WatchfaceSettingsMessagePrivate, VideoTitleMessagePrivate, VideoMessagePrivate, VideoFrameMessagePrivate, VideoDescriptionMessagePrivate, VideoClipMessagePrivate, UserProfileMessagePrivate, TrainingFileMessagePrivate, TotalsMessagePrivate, TimestampCorrelationMessagePrivate, ThreeDSensorCalibrationMessagePrivate, StressLevelMessagePrivate, SportMessagePrivate, SpeedZoneMessagePrivate, SoftwareMessagePrivate, SlaveDeviceMessagePrivate, SetMessagePrivate, SessionMessagePrivate, SegmentPointMessagePrivate, SegmentLeaderboardEntryMessagePrivate, SegmentLapMessagePrivate, SegmentIdMessagePrivate, SegmentFileMessagePrivate, SdmProfileMessagePrivate, ScheduleMessagePrivate, RecordMessagePrivate, PowerZoneMessagePrivate, OneDSensorCalibrationMessagePrivate, OhrSettingsMessagePrivate, ObdiiDataMessagePrivate, NmeaSentenceMessagePrivate, MonitoringMessagePrivate, MonitoringInfoMessagePrivate, MetZoneMessagePrivate, MesgCapabilitiesMessagePrivate, MemoGlobMessagePrivate, MagnetometerDataMessagePrivate, LengthMessagePrivate, LapMessagePrivate, JumpMessagePrivate, HrZoneMessagePrivate, HrvMessagePrivate, HrmProfileMessagePrivate, HrMessagePrivate, GyroscopeDataMessagePrivate, GpsMetadataMessagePrivate, GoalMessagePrivate, FileIdMessagePrivate, FileCreatorMessagePrivate, FileCapabilitiesMessagePrivate, FieldDescriptionMessagePrivate, FieldCapabilitiesMessagePrivate, ExerciseTitleMessagePrivate, ExdScreenConfigurationMessagePrivate, ExdDataFieldConfigurationMessagePrivate, ExdDataConceptConfigurationMessagePrivate, EventMessagePrivate, DiveSummaryMessagePrivate, DiveSettingsMessagePrivate, DiveGasMessagePrivate, DiveAlarmMessagePrivate, DeviceSettingsMessagePrivate, DeviceInfoMessagePrivate, DeveloperDataIdMessagePrivate, CoursePointMessagePrivate, CourseMessagePrivate, ConnectivityMessagePrivate, ClimbProMessagePrivate, CapabilitiesMessagePrivate, CameraEventMessagePrivate, CadenceZoneMessagePrivate, BloodPressureMessagePrivate, BikeProfileMessagePrivate, BarometerDataMessagePrivate, AviationAttitudeMessagePrivate, AntTxMessagePrivate, AntRxMessagePrivate, AntChannelIdMessagePrivate, ActivityMessagePrivate, and AccelerometerDataMessagePrivate.
Definition at line 178 of file fitdatamessage.cpp.
 {
     Q_UNUSED(bigEndian)
     qWarning() << "ignoring unknown field" << fieldId << data << baseType;
     return true; // True because we "handled it safely", and can continue parsing.
 }
Referenced by AccelerometerDataMessagePrivate::setField(), ActivityMessagePrivate::setField(), AntChannelIdMessagePrivate::setField(), AntRxMessagePrivate::setField(), AntTxMessagePrivate::setField(), AviationAttitudeMessagePrivate::setField(), BarometerDataMessagePrivate::setField(), BikeProfileMessagePrivate::setField(), BloodPressureMessagePrivate::setField(), CadenceZoneMessagePrivate::setField(), CameraEventMessagePrivate::setField(), CapabilitiesMessagePrivate::setField(), ClimbProMessagePrivate::setField(), ConnectivityMessagePrivate::setField(), CourseMessagePrivate::setField(), CoursePointMessagePrivate::setField(), DeveloperDataIdMessagePrivate::setField(), DeviceInfoMessagePrivate::setField(), DeviceSettingsMessagePrivate::setField(), DiveAlarmMessagePrivate::setField(), DiveGasMessagePrivate::setField(), DiveSettingsMessagePrivate::setField(), DiveSummaryMessagePrivate::setField(), EventMessagePrivate::setField(), ExdDataConceptConfigurationMessagePrivate::setField(), ExdDataFieldConfigurationMessagePrivate::setField(), ExdScreenConfigurationMessagePrivate::setField(), ExerciseTitleMessagePrivate::setField(), FieldCapabilitiesMessagePrivate::setField(), FieldDescriptionMessagePrivate::setField(), FileCapabilitiesMessagePrivate::setField(), FileCreatorMessagePrivate::setField(), FileIdMessagePrivate::setField(), GoalMessagePrivate::setField(), GpsMetadataMessagePrivate::setField(), GyroscopeDataMessagePrivate::setField(), HrMessagePrivate::setField(), HrmProfileMessagePrivate::setField(), HrvMessagePrivate::setField(), HrZoneMessagePrivate::setField(), JumpMessagePrivate::setField(), LapMessagePrivate::setField(), LengthMessagePrivate::setField(), MagnetometerDataMessagePrivate::setField(), MemoGlobMessagePrivate::setField(), MesgCapabilitiesMessagePrivate::setField(), MetZoneMessagePrivate::setField(), MonitoringInfoMessagePrivate::setField(), MonitoringMessagePrivate::setField(), NmeaSentenceMessagePrivate::setField(), ObdiiDataMessagePrivate::setField(), OhrSettingsMessagePrivate::setField(), OneDSensorCalibrationMessagePrivate::setField(), PowerZoneMessagePrivate::setField(), RecordMessagePrivate::setField(), ScheduleMessagePrivate::setField(), SdmProfileMessagePrivate::setField(), SegmentFileMessagePrivate::setField(), SegmentIdMessagePrivate::setField(), SegmentLapMessagePrivate::setField(), SegmentLeaderboardEntryMessagePrivate::setField(), SegmentPointMessagePrivate::setField(), SessionMessagePrivate::setField(), SetMessagePrivate::setField(), SlaveDeviceMessagePrivate::setField(), SoftwareMessagePrivate::setField(), SpeedZoneMessagePrivate::setField(), SportMessagePrivate::setField(), StressLevelMessagePrivate::setField(), ThreeDSensorCalibrationMessagePrivate::setField(), TimestampCorrelationMessagePrivate::setField(), TotalsMessagePrivate::setField(), TrainingFileMessagePrivate::setField(), UserProfileMessagePrivate::setField(), VideoClipMessagePrivate::setField(), VideoDescriptionMessagePrivate::setField(), VideoFrameMessagePrivate::setField(), VideoMessagePrivate::setField(), VideoTitleMessagePrivate::setField(), WatchfaceSettingsMessagePrivate::setField(), WeatherAlertMessagePrivate::setField(), WeatherConditionsMessagePrivate::setField(), WeightScaleMessagePrivate::setField(), WorkoutMessagePrivate::setField(), WorkoutSessionMessagePrivate::setField(), WorkoutStepMessagePrivate::setField(), ZonesTargetMessagePrivate::setField(), and setFields().
setFields()
bool FitDataMessagePrivate::setFields (const DataDefinition *const defn, const QByteArray & record)
Set the current FIT data message's fields.
The method iterates through the record, invoking the virtual setField method to assign the extraced values to the relevant data message fields. Derived classes are expected to override setField to implement that field number to class member mapping.
Parameters
defn Data field definition describing the record layout.
record The FIT data record to read fields from.
Returns
true if all fields were parsed safely.
See also
setField
Definition at line 150 of file fitdatamessage.cpp.
 {
     Q_ASSERT(defn->globalMessageNumber == this->globalMessageNumber);
     int dataOffset=0; // Next field's offset within dataRecord.
     for (const FieldDefinition &field: defn->fieldDefinitions) {
         if (!setField(field.number, record.mid(dataOffset,field.size), field.baseType,
                       (defn->architecture == Architecture::BigEndian)))
             return false;
         dataOffset += field.size;
     }
     return true;
 }
References DataDefinition::architecture, FieldDefinition::baseType, BigEndian, DataDefinition::fieldDefinitions, DataDefinition::globalMessageNumber, FieldDefinition::number, setField(), and FieldDefinition::size.
verify()
bool FitDataMessagePrivate::verify (const QByteArray & data, const FitBaseType actualType, const int expectedSize, const FitBaseType expectedType, const char * messageFieldName) protected
\interal
Verifies the size and type of FIT Data Message fields.
Parameters
data Data to verify the size of.
actualType Actual base type.
expectedSize Expected size of data.
expectedType Expected base type.
messageFieldName Name of the field being verified.
Returns
true if the size and type match, false otherwise.
Definition at line 235 of file fitdatamessage.cpp.
 {
     return (verifyBaseType(actualType, expectedType, messageFieldName) &&
             verifyDataSieze(data, expectedSize, messageFieldName));
 }
References verifyBaseType(), and verifyDataSieze().
Referenced by AccelerometerDataMessagePrivate::setField(), ActivityMessagePrivate::setField(), AntChannelIdMessagePrivate::setField(), AntRxMessagePrivate::setField(), AntTxMessagePrivate::setField(), AviationAttitudeMessagePrivate::setField(), BarometerDataMessagePrivate::setField(), BikeProfileMessagePrivate::setField(), BloodPressureMessagePrivate::setField(), CadenceZoneMessagePrivate::setField(), CameraEventMessagePrivate::setField(), CapabilitiesMessagePrivate::setField(), ClimbProMessagePrivate::setField(), ConnectivityMessagePrivate::setField(), CourseMessagePrivate::setField(), CoursePointMessagePrivate::setField(), DeveloperDataIdMessagePrivate::setField(), DeviceInfoMessagePrivate::setField(), DeviceSettingsMessagePrivate::setField(), DiveAlarmMessagePrivate::setField(), DiveGasMessagePrivate::setField(), DiveSettingsMessagePrivate::setField(), DiveSummaryMessagePrivate::setField(), EventMessagePrivate::setField(), ExdDataConceptConfigurationMessagePrivate::setField(), ExdDataFieldConfigurationMessagePrivate::setField(), ExdScreenConfigurationMessagePrivate::setField(), ExerciseTitleMessagePrivate::setField(), FieldCapabilitiesMessagePrivate::setField(), FieldDescriptionMessagePrivate::setField(), FileCapabilitiesMessagePrivate::setField(), FileCreatorMessagePrivate::setField(), FileIdMessagePrivate::setField(), GoalMessagePrivate::setField(), GpsMetadataMessagePrivate::setField(), GyroscopeDataMessagePrivate::setField(), HrMessagePrivate::setField(), HrmProfileMessagePrivate::setField(), HrvMessagePrivate::setField(), HrZoneMessagePrivate::setField(), JumpMessagePrivate::setField(), LapMessagePrivate::setField(), LengthMessagePrivate::setField(), MagnetometerDataMessagePrivate::setField(), MemoGlobMessagePrivate::setField(), MesgCapabilitiesMessagePrivate::setField(), MetZoneMessagePrivate::setField(), MonitoringInfoMessagePrivate::setField(), MonitoringMessagePrivate::setField(), NmeaSentenceMessagePrivate::setField(), ObdiiDataMessagePrivate::setField(), OhrSettingsMessagePrivate::setField(), OneDSensorCalibrationMessagePrivate::setField(), PowerZoneMessagePrivate::setField(), RecordMessagePrivate::setField(), ScheduleMessagePrivate::setField(), SdmProfileMessagePrivate::setField(), SegmentFileMessagePrivate::setField(), SegmentIdMessagePrivate::setField(), SegmentLapMessagePrivate::setField(), SegmentLeaderboardEntryMessagePrivate::setField(), SegmentPointMessagePrivate::setField(), SessionMessagePrivate::setField(), SetMessagePrivate::setField(), SlaveDeviceMessagePrivate::setField(), SoftwareMessagePrivate::setField(), SpeedZoneMessagePrivate::setField(), SportMessagePrivate::setField(), StressLevelMessagePrivate::setField(), ThreeDSensorCalibrationMessagePrivate::setField(), TimestampCorrelationMessagePrivate::setField(), TotalsMessagePrivate::setField(), TrainingFileMessagePrivate::setField(), UserProfileMessagePrivate::setField(), VideoClipMessagePrivate::setField(), VideoDescriptionMessagePrivate::setField(), VideoFrameMessagePrivate::setField(), VideoMessagePrivate::setField(), VideoTitleMessagePrivate::setField(), WatchfaceSettingsMessagePrivate::setField(), WeatherAlertMessagePrivate::setField(), WeatherConditionsMessagePrivate::setField(), WeightScaleMessagePrivate::setField(), WorkoutMessagePrivate::setField(), WorkoutSessionMessagePrivate::setField(), WorkoutStepMessagePrivate::setField(), and ZonesTargetMessagePrivate::setField().
Member Data Documentation
globalMessageNumber
MesgNum FitDataMessagePrivate::globalMessageNumber
Definition at line 34 of file fitdatamessage_p.h.
Referenced by AccelerometerDataMessagePrivate::AccelerometerDataMessagePrivate(), ActivityMessagePrivate::ActivityMessagePrivate(), AntChannelIdMessagePrivate::AntChannelIdMessagePrivate(), AntRxMessagePrivate::AntRxMessagePrivate(), AntTxMessagePrivate::AntTxMessagePrivate(), AviationAttitudeMessagePrivate::AviationAttitudeMessagePrivate(), BarometerDataMessagePrivate::BarometerDataMessagePrivate(), BikeProfileMessagePrivate::BikeProfileMessagePrivate(), BloodPressureMessagePrivate::BloodPressureMessagePrivate(), CadenceZoneMessagePrivate::CadenceZoneMessagePrivate(), CameraEventMessagePrivate::CameraEventMessagePrivate(), CapabilitiesMessagePrivate::CapabilitiesMessagePrivate(), ClimbProMessagePrivate::ClimbProMessagePrivate(), ConnectivityMessagePrivate::ConnectivityMessagePrivate(), CourseMessagePrivate::CourseMessagePrivate(), CoursePointMessagePrivate::CoursePointMessagePrivate(), DeveloperDataIdMessagePrivate::DeveloperDataIdMessagePrivate(), DeviceInfoMessagePrivate::DeviceInfoMessagePrivate(), DeviceSettingsMessagePrivate::DeviceSettingsMessagePrivate(), DiveAlarmMessagePrivate::DiveAlarmMessagePrivate(), DiveGasMessagePrivate::DiveGasMessagePrivate(), DiveSettingsMessagePrivate::DiveSettingsMessagePrivate(), DiveSummaryMessagePrivate::DiveSummaryMessagePrivate(), EventMessagePrivate::EventMessagePrivate(), ExdDataConceptConfigurationMessagePrivate::ExdDataConceptConfigurationMessagePrivate(), ExdDataFieldConfigurationMessagePrivate::ExdDataFieldConfigurationMessagePrivate(), ExdScreenConfigurationMessagePrivate::ExdScreenConfigurationMessagePrivate(), ExerciseTitleMessagePrivate::ExerciseTitleMessagePrivate(), FieldCapabilitiesMessagePrivate::FieldCapabilitiesMessagePrivate(), FieldDescriptionMessagePrivate::FieldDescriptionMessagePrivate(), FileCapabilitiesMessagePrivate::FileCapabilitiesMessagePrivate(), FileCreatorMessagePrivate::FileCreatorMessagePrivate(), FileIdMessagePrivate::FileIdMessagePrivate(), GoalMessagePrivate::GoalMessagePrivate(), GpsMetadataMessagePrivate::GpsMetadataMessagePrivate(), GyroscopeDataMessagePrivate::GyroscopeDataMessagePrivate(), HrMessagePrivate::HrMessagePrivate(), HrmProfileMessagePrivate::HrmProfileMessagePrivate(), HrvMessagePrivate::HrvMessagePrivate(), HrZoneMessagePrivate::HrZoneMessagePrivate(), JumpMessagePrivate::JumpMessagePrivate(), LapMessagePrivate::LapMessagePrivate(), LengthMessagePrivate::LengthMessagePrivate(), MagnetometerDataMessagePrivate::MagnetometerDataMessagePrivate(), MemoGlobMessagePrivate::MemoGlobMessagePrivate(), MesgCapabilitiesMessagePrivate::MesgCapabilitiesMessagePrivate(), MetZoneMessagePrivate::MetZoneMessagePrivate(), MonitoringInfoMessagePrivate::MonitoringInfoMessagePrivate(), MonitoringMessagePrivate::MonitoringMessagePrivate(), NmeaSentenceMessagePrivate::NmeaSentenceMessagePrivate(), ObdiiDataMessagePrivate::ObdiiDataMessagePrivate(), OhrSettingsMessagePrivate::OhrSettingsMessagePrivate(), OneDSensorCalibrationMessagePrivate::OneDSensorCalibrationMessagePrivate(), PowerZoneMessagePrivate::PowerZoneMessagePrivate(), RecordMessagePrivate::RecordMessagePrivate(), ScheduleMessagePrivate::ScheduleMessagePrivate(), SdmProfileMessagePrivate::SdmProfileMessagePrivate(), SegmentFileMessagePrivate::SegmentFileMessagePrivate(), SegmentIdMessagePrivate::SegmentIdMessagePrivate(), SegmentLapMessagePrivate::SegmentLapMessagePrivate(), SegmentLeaderboardEntryMessagePrivate::SegmentLeaderboardEntryMessagePrivate(), SegmentPointMessagePrivate::SegmentPointMessagePrivate(), SessionMessagePrivate::SessionMessagePrivate(), SetMessagePrivate::SetMessagePrivate(), SlaveDeviceMessagePrivate::SlaveDeviceMessagePrivate(), SoftwareMessagePrivate::SoftwareMessagePrivate(), SpeedZoneMessagePrivate::SpeedZoneMessagePrivate(), SportMessagePrivate::SportMessagePrivate(), StressLevelMessagePrivate::StressLevelMessagePrivate(), ThreeDSensorCalibrationMessagePrivate::ThreeDSensorCalibrationMessagePrivate(), TimestampCorrelationMessagePrivate::TimestampCorrelationMessagePrivate(), TotalsMessagePrivate::TotalsMessagePrivate(), TrainingFileMessagePrivate::TrainingFileMessagePrivate(), UserProfileMessagePrivate::UserProfileMessagePrivate(), VideoClipMessagePrivate::VideoClipMessagePrivate(), VideoDescriptionMessagePrivate::VideoDescriptionMessagePrivate(), VideoFrameMessagePrivate::VideoFrameMessagePrivate(), VideoMessagePrivate::VideoMessagePrivate(), VideoTitleMessagePrivate::VideoTitleMessagePrivate(), WatchfaceSettingsMessagePrivate::WatchfaceSettingsMessagePrivate(), WeatherAlertMessagePrivate::WeatherAlertMessagePrivate(), WeatherConditionsMessagePrivate::WeatherConditionsMessagePrivate(), WeightScaleMessagePrivate::WeightScaleMessagePrivate(), WorkoutMessagePrivate::WorkoutMessagePrivate(), WorkoutSessionMessagePrivate::WorkoutSessionMessagePrivate(), WorkoutStepMessagePrivate::WorkoutStepMessagePrivate(), and ZonesTargetMessagePrivate::ZonesTargetMessagePrivate().
isNull
bool FitDataMessagePrivate::isNull
Definition at line 35 of file fitdatamessage_p.h.
q_ptr
FitDataMessage* const FitDataMessagePrivate::q_ptr protected
Internal q-pointer.
Definition at line 44 of file fitdatamessage_p.h.
The documentation for this class was generated from the following files:
fitdatamessage_p.h
fitdatamessage.cpp