QtFit: StressLevelMessage Class Reference
StressLevelMessage Class Reference
The StressLevelMessage class represents a FIT StressLevelMessage data message.
Public Member Functions
StressLevelMessage ()
Constructs a StressLevelMessage object.
qint16 stressLevelValue () const
Returns the StressLevelMessage data message's stressLevelValue field's current value.
DateTime stressLevelTime () const
Returns the StressLevelMessage data message's stressLevelTime field's current value.
void setStressLevelValue (const qint16 stressLevelValue)
Sets the stressLevelValue field to stressLevelValue.
void setStressLevelTime (const DateTime stressLevelTime)
Sets the stressLevelTime field to stressLevelTime.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
StressLevelMessage (StressLevelMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The StressLevelMessage class represents a FIT StressLevelMessage data message.
See also
DataMessage
Definition at line 39 of file stresslevelmessage.h.
Constructor & Destructor Documentation
StressLevelMessage() [1/2]
StressLevelMessage::StressLevelMessage ()
Constructs a StressLevelMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file stresslevelmessage.cpp.
                                        : AbstractDataMessage(new StressLevelMessagePrivate(this))
 {
 }
StressLevelMessage() [2/2]
StressLevelMessage::StressLevelMessage (StressLevelMessagePrivate *const d) explicit protected
Constructs a StressLevelMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file stresslevelmessage.cpp.
                                                                           : AbstractDataMessage(d)
 {
 }
Member Function Documentation
setStressLevelTime()
void StressLevelMessage::setStressLevelTime (const DateTime stressLevelTime)
Sets the stressLevelTime field to stressLevelTime.
Parameters
stressLevelTime The field value to set.
Definition at line 108 of file stresslevelmessage.cpp.
 {
     Q_D(StressLevelMessage);
     d->stressLevelTime = stressLevelTime;
 }
References stressLevelTime().
setStressLevelValue()
void StressLevelMessage::setStressLevelValue (const qint16 stressLevelValue)
Sets the stressLevelValue field to stressLevelValue.
Parameters
stressLevelValue The field value to set.
Definition at line 98 of file stresslevelmessage.cpp.
 {
     Q_D(StressLevelMessage);
     d->stressLevelValue = stressLevelValue;
 }
References stressLevelValue().
stressLevelTime()
DateTime StressLevelMessage::stressLevelTime () const
Returns the StressLevelMessage data message's stressLevelTime field's current value.
Time stress score was calculated
Returns
the stressLevelTime field value.
Definition at line 87 of file stresslevelmessage.cpp.
 {
     Q_D(const StressLevelMessage);
     return d->stressLevelTime;
 }
Referenced by setStressLevelTime().
stressLevelValue()
qint16 StressLevelMessage::stressLevelValue () const
Returns the StressLevelMessage data message's stressLevelValue field's current value.
Returns
the stressLevelValue field value.
Definition at line 74 of file stresslevelmessage.cpp.
 {
     Q_D(const StressLevelMessage);
     return d->stressLevelValue;
 }
Referenced by setStressLevelValue().
The documentation for this class was generated from the following files:
stresslevelmessage.h
stresslevelmessage.cpp