QtFit: UserProfileMessage Class Reference
UserProfileMessage Class Reference
The UserProfileMessage class represents a FIT UserProfileMessage data message.
Public Member Functions
UserProfileMessage ()
Constructs a UserProfileMessage object.
MessageIndex messageIndex () const
Returns the UserProfileMessage data message's messageIndex field's current value.
QString friendlyName () const
Returns the UserProfileMessage data message's friendlyName field's current value.
Gender gender () const
Returns the UserProfileMessage data message's gender field's current value.
quint8 age () const
Returns the UserProfileMessage data message's age field's current value.
quint8 height () const
Returns the UserProfileMessage data message's height field's current value.
quint16 weight () const
Returns the UserProfileMessage data message's weight field's current value.
Language language () const
Returns the UserProfileMessage data message's language field's current value.
DisplayMeasure elevSetting () const
Returns the UserProfileMessage data message's elevSetting field's current value.
DisplayMeasure weightSetting () const
Returns the UserProfileMessage data message's weightSetting field's current value.
quint8 restingHeartRate () const
Returns the UserProfileMessage data message's restingHeartRate field's current value.
quint8 defaultMaxRunningHeartRate () const
Returns the UserProfileMessage data message's defaultMaxRunningHeartRate field's current value.
quint8 defaultMaxBikingHeartRate () const
Returns the UserProfileMessage data message's defaultMaxBikingHeartRate field's current value.
quint8 defaultMaxHeartRate () const
Returns the UserProfileMessage data message's defaultMaxHeartRate field's current value.
DisplayHeart hrSetting () const
Returns the UserProfileMessage data message's hrSetting field's current value.
DisplayMeasure speedSetting () const
Returns the UserProfileMessage data message's speedSetting field's current value.
DisplayMeasure distSetting () const
Returns the UserProfileMessage data message's distSetting field's current value.
DisplayPower powerSetting () const
Returns the UserProfileMessage data message's powerSetting field's current value.
ActivityClass activityClass () const
Returns the UserProfileMessage data message's activityClass field's current value.
DisplayPosition positionSetting () const
Returns the UserProfileMessage data message's positionSetting field's current value.
DisplayMeasure temperatureSetting () const
Returns the UserProfileMessage data message's temperatureSetting field's current value.
UserLocalId localId () const
Returns the UserProfileMessage data message's localId field's current value.
quint8 globalId () const
Returns the UserProfileMessage data message's globalId field's current value.
LocaltimeIntoDay wakeTime () const
Returns the UserProfileMessage data message's wakeTime field's current value.
LocaltimeIntoDay sleepTime () const
Returns the UserProfileMessage data message's sleepTime field's current value.
DisplayMeasure heightSetting () const
Returns the UserProfileMessage data message's heightSetting field's current value.
quint16 userRunningStepLength () const
Returns the UserProfileMessage data message's userRunningStepLength field's current value.
quint16 userWalkingStepLength () const
Returns the UserProfileMessage data message's userWalkingStepLength field's current value.
DisplayMeasure depthSetting () const
Returns the UserProfileMessage data message's depthSetting field's current value.
quint32 diveCount () const
Returns the UserProfileMessage data message's diveCount field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setFriendlyName (const QString friendlyName)
Sets the friendlyName field to friendlyName.
void setGender (const Gender gender)
Sets the gender field to gender.
void setAge (const quint8 age)
Sets the age field to age.
void setHeight (const quint8 height)
Sets the height field to height.
void setWeight (const quint16 weight)
Sets the weight field to weight.
void setLanguage (const Language language)
Sets the language field to language.
void setElevSetting (const DisplayMeasure elevSetting)
Sets the elevSetting field to elevSetting.
void setWeightSetting (const DisplayMeasure weightSetting)
Sets the weightSetting field to weightSetting.
void setRestingHeartRate (const quint8 restingHeartRate)
Sets the restingHeartRate field to restingHeartRate.
void setDefaultMaxRunningHeartRate (const quint8 defaultMaxRunningHeartRate)
Sets the defaultMaxRunningHeartRate field to defaultMaxRunningHeartRate.
void setDefaultMaxBikingHeartRate (const quint8 defaultMaxBikingHeartRate)
Sets the defaultMaxBikingHeartRate field to defaultMaxBikingHeartRate.
void setDefaultMaxHeartRate (const quint8 defaultMaxHeartRate)
Sets the defaultMaxHeartRate field to defaultMaxHeartRate.
void setHrSetting (const DisplayHeart hrSetting)
Sets the hrSetting field to hrSetting.
void setSpeedSetting (const DisplayMeasure speedSetting)
Sets the speedSetting field to speedSetting.
void setDistSetting (const DisplayMeasure distSetting)
Sets the distSetting field to distSetting.
void setPowerSetting (const DisplayPower powerSetting)
Sets the powerSetting field to powerSetting.
void setActivityClass (const ActivityClass activityClass)
Sets the activityClass field to activityClass.
void setPositionSetting (const DisplayPosition positionSetting)
Sets the positionSetting field to positionSetting.
void setTemperatureSetting (const DisplayMeasure temperatureSetting)
Sets the temperatureSetting field to temperatureSetting.
void setLocalId (const UserLocalId localId)
Sets the localId field to localId.
void setGlobalId (const quint8 globalId)
Sets the globalId field to globalId.
void setWakeTime (const LocaltimeIntoDay wakeTime)
Sets the wakeTime field to wakeTime.
void setSleepTime (const LocaltimeIntoDay sleepTime)
Sets the sleepTime field to sleepTime.
void setHeightSetting (const DisplayMeasure heightSetting)
Sets the heightSetting field to heightSetting.
void setUserRunningStepLength (const quint16 userRunningStepLength)
Sets the userRunningStepLength field to userRunningStepLength.
void setUserWalkingStepLength (const quint16 userWalkingStepLength)
Sets the userWalkingStepLength field to userWalkingStepLength.
void setDepthSetting (const DisplayMeasure depthSetting)
Sets the depthSetting field to depthSetting.
void setDiveCount (const quint32 diveCount)
Sets the diveCount field to diveCount.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
UserProfileMessage (UserProfileMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The UserProfileMessage class represents a FIT UserProfileMessage data message.
See also
DataMessage
Definition at line 39 of file userprofilemessage.h.
Constructor & Destructor Documentation
UserProfileMessage() [1/2]
UserProfileMessage::UserProfileMessage ()
Constructs a UserProfileMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file userprofilemessage.cpp.
                                        : AbstractDataMessage(new UserProfileMessagePrivate(this))
 {
 }
UserProfileMessage() [2/2]
UserProfileMessage::UserProfileMessage (UserProfileMessagePrivate *const d) explicit protected
Constructs a UserProfileMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file userprofilemessage.cpp.
                                                                           : AbstractDataMessage(d)
 {
 }
Member Function Documentation
activityClass()
ActivityClass UserProfileMessage::activityClass () const
Returns the UserProfileMessage data message's activityClass field's current value.
Returns
the activityClass field value.
Definition at line 261 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->activityClass;
 }
Referenced by setActivityClass().
age()
quint8 UserProfileMessage::age () const
Returns the UserProfileMessage data message's age field's current value.
Returns
the age field value.
Definition at line 107 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->age;
 }
Referenced by setAge().
defaultMaxBikingHeartRate()
quint8 UserProfileMessage::defaultMaxBikingHeartRate () const
Returns the UserProfileMessage data message's defaultMaxBikingHeartRate field's current value.
Returns
the defaultMaxBikingHeartRate field value.
Definition at line 195 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->defaultMaxBikingHeartRate;
 }
Referenced by setDefaultMaxBikingHeartRate().
defaultMaxHeartRate()
quint8 UserProfileMessage::defaultMaxHeartRate () const
Returns the UserProfileMessage data message's defaultMaxHeartRate field's current value.
Returns
the defaultMaxHeartRate field value.
Definition at line 206 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->defaultMaxHeartRate;
 }
Referenced by setDefaultMaxHeartRate().
defaultMaxRunningHeartRate()
quint8 UserProfileMessage::defaultMaxRunningHeartRate () const
Returns the UserProfileMessage data message's defaultMaxRunningHeartRate field's current value.
Returns
the defaultMaxRunningHeartRate field value.
Definition at line 184 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->defaultMaxRunningHeartRate;
 }
Referenced by setDefaultMaxRunningHeartRate().
depthSetting()
DisplayMeasure UserProfileMessage::depthSetting () const
Returns the UserProfileMessage data message's depthSetting field's current value.
Returns
the depthSetting field value.
Definition at line 379 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->depthSetting;
 }
Referenced by setDepthSetting().
distSetting()
DisplayMeasure UserProfileMessage::distSetting () const
Returns the UserProfileMessage data message's distSetting field's current value.
Returns
the distSetting field value.
Definition at line 239 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->distSetting;
 }
Referenced by setDistSetting().
diveCount()
quint32 UserProfileMessage::diveCount () const
Returns the UserProfileMessage data message's diveCount field's current value.
Returns
the diveCount field value.
Definition at line 390 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->diveCount;
 }
Referenced by setDiveCount().
elevSetting()
DisplayMeasure UserProfileMessage::elevSetting () const
Returns the UserProfileMessage data message's elevSetting field's current value.
Returns
the elevSetting field value.
Definition at line 151 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->elevSetting;
 }
Referenced by setElevSetting().
friendlyName()
QString UserProfileMessage::friendlyName () const
Returns the UserProfileMessage data message's friendlyName field's current value.
Returns
the friendlyName field value.
Definition at line 85 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->friendlyName;
 }
Referenced by setFriendlyName().
gender()
Gender UserProfileMessage::gender () const
Returns the UserProfileMessage data message's gender field's current value.
Returns
the gender field value.
Definition at line 96 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->gender;
 }
Referenced by setGender().
globalId()
quint8 UserProfileMessage::globalId () const
Returns the UserProfileMessage data message's globalId field's current value.
Returns
the globalId field value.
Definition at line 305 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->globalId;
 }
Referenced by setGlobalId().
height()
quint8 UserProfileMessage::height () const
Returns the UserProfileMessage data message's height field's current value.
Returns
the height field value.
Definition at line 118 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->height;
 }
Referenced by setHeight().
heightSetting()
DisplayMeasure UserProfileMessage::heightSetting () const
Returns the UserProfileMessage data message's heightSetting field's current value.
Returns
the heightSetting field value.
Definition at line 342 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->heightSetting;
 }
Referenced by setHeightSetting().
hrSetting()
DisplayHeart UserProfileMessage::hrSetting () const
Returns the UserProfileMessage data message's hrSetting field's current value.
Returns
the hrSetting field value.
Definition at line 217 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->hrSetting;
 }
Referenced by setHrSetting().
language()
Language UserProfileMessage::language () const
Returns the UserProfileMessage data message's language field's current value.
Returns
the language field value.
Definition at line 140 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->language;
 }
Referenced by setLanguage().
localId()
UserLocalId UserProfileMessage::localId () const
Returns the UserProfileMessage data message's localId field's current value.
Returns
the localId field value.
Definition at line 294 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->localId;
 }
Referenced by setLocalId().
messageIndex()
MessageIndex UserProfileMessage::messageIndex () const
Returns the UserProfileMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 74 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
positionSetting()
DisplayPosition UserProfileMessage::positionSetting () const
Returns the UserProfileMessage data message's positionSetting field's current value.
Returns
the positionSetting field value.
Definition at line 272 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->positionSetting;
 }
Referenced by setPositionSetting().
powerSetting()
DisplayPower UserProfileMessage::powerSetting () const
Returns the UserProfileMessage data message's powerSetting field's current value.
Returns
the powerSetting field value.
Definition at line 250 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->powerSetting;
 }
Referenced by setPowerSetting().
restingHeartRate()
quint8 UserProfileMessage::restingHeartRate () const
Returns the UserProfileMessage data message's restingHeartRate field's current value.
Returns
the restingHeartRate field value.
Definition at line 173 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->restingHeartRate;
 }
Referenced by setRestingHeartRate().
setActivityClass()
void UserProfileMessage::setActivityClass (const ActivityClass activityClass)
Sets the activityClass field to activityClass.
Parameters
activityClass The field value to set.
Definition at line 571 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->activityClass = activityClass;
 }
References activityClass().
setAge()
void UserProfileMessage::setAge (const quint8 age)
Sets the age field to age.
Parameters
age The field value to set.
Definition at line 431 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->age = age;
 }
References age().
setDefaultMaxBikingHeartRate()
void UserProfileMessage::setDefaultMaxBikingHeartRate (const quint8 defaultMaxBikingHeartRate)
Sets the defaultMaxBikingHeartRate field to defaultMaxBikingHeartRate.
Parameters
defaultMaxBikingHeartRate The field value to set.
Definition at line 511 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->defaultMaxBikingHeartRate = defaultMaxBikingHeartRate;
 }
References defaultMaxBikingHeartRate().
setDefaultMaxHeartRate()
void UserProfileMessage::setDefaultMaxHeartRate (const quint8 defaultMaxHeartRate)
Sets the defaultMaxHeartRate field to defaultMaxHeartRate.
Parameters
defaultMaxHeartRate The field value to set.
Definition at line 521 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->defaultMaxHeartRate = defaultMaxHeartRate;
 }
References defaultMaxHeartRate().
setDefaultMaxRunningHeartRate()
void UserProfileMessage::setDefaultMaxRunningHeartRate (const quint8 defaultMaxRunningHeartRate)
Sets the defaultMaxRunningHeartRate field to defaultMaxRunningHeartRate.
Parameters
defaultMaxRunningHeartRate The field value to set.
Definition at line 501 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->defaultMaxRunningHeartRate = defaultMaxRunningHeartRate;
 }
References defaultMaxRunningHeartRate().
setDepthSetting()
void UserProfileMessage::setDepthSetting (const DisplayMeasure depthSetting)
Sets the depthSetting field to depthSetting.
Parameters
depthSetting The field value to set.
Definition at line 671 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->depthSetting = depthSetting;
 }
References depthSetting().
setDistSetting()
void UserProfileMessage::setDistSetting (const DisplayMeasure distSetting)
Sets the distSetting field to distSetting.
Parameters
distSetting The field value to set.
Definition at line 551 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->distSetting = distSetting;
 }
References distSetting().
setDiveCount()
void UserProfileMessage::setDiveCount (const quint32 diveCount)
Sets the diveCount field to diveCount.
Parameters
diveCount The field value to set.
Definition at line 681 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->diveCount = diveCount;
 }
References diveCount().
setElevSetting()
void UserProfileMessage::setElevSetting (const DisplayMeasure elevSetting)
Sets the elevSetting field to elevSetting.
Parameters
elevSetting The field value to set.
Definition at line 471 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->elevSetting = elevSetting;
 }
References elevSetting().
setFriendlyName()
void UserProfileMessage::setFriendlyName (const QString friendlyName)
Sets the friendlyName field to friendlyName.
Parameters
friendlyName The field value to set.
Definition at line 411 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->friendlyName = friendlyName;
 }
References friendlyName().
setGender()
void UserProfileMessage::setGender (const Gender gender)
Sets the gender field to gender.
Parameters
gender The field value to set.
Definition at line 421 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->gender = gender;
 }
References gender().
setGlobalId()
void UserProfileMessage::setGlobalId (const quint8 globalId)
Sets the globalId field to globalId.
Parameters
globalId The field value to set.
Definition at line 611 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->globalId = globalId;
 }
References globalId().
setHeight()
void UserProfileMessage::setHeight (const quint8 height)
Sets the height field to height.
Parameters
height The field value to set.
Definition at line 441 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->height = height;
 }
References height().
setHeightSetting()
void UserProfileMessage::setHeightSetting (const DisplayMeasure heightSetting)
Sets the heightSetting field to heightSetting.
Parameters
heightSetting The field value to set.
Definition at line 641 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->heightSetting = heightSetting;
 }
References heightSetting().
setHrSetting()
void UserProfileMessage::setHrSetting (const DisplayHeart hrSetting)
Sets the hrSetting field to hrSetting.
Parameters
hrSetting The field value to set.
Definition at line 531 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->hrSetting = hrSetting;
 }
References hrSetting().
setLanguage()
void UserProfileMessage::setLanguage (const Language language)
Sets the language field to language.
Parameters
language The field value to set.
Definition at line 461 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->language = language;
 }
References language().
setLocalId()
void UserProfileMessage::setLocalId (const UserLocalId localId)
Sets the localId field to localId.
Parameters
localId The field value to set.
Definition at line 601 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->localId = localId;
 }
References localId().
setMessageIndex()
void UserProfileMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 401 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setPositionSetting()
void UserProfileMessage::setPositionSetting (const DisplayPosition positionSetting)
Sets the positionSetting field to positionSetting.
Parameters
positionSetting The field value to set.
Definition at line 581 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->positionSetting = positionSetting;
 }
References positionSetting().
setPowerSetting()
void UserProfileMessage::setPowerSetting (const DisplayPower powerSetting)
Sets the powerSetting field to powerSetting.
Parameters
powerSetting The field value to set.
Definition at line 561 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->powerSetting = powerSetting;
 }
References powerSetting().
setRestingHeartRate()
void UserProfileMessage::setRestingHeartRate (const quint8 restingHeartRate)
Sets the restingHeartRate field to restingHeartRate.
Parameters
restingHeartRate The field value to set.
Definition at line 491 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->restingHeartRate = restingHeartRate;
 }
References restingHeartRate().
setSleepTime()
void UserProfileMessage::setSleepTime (const LocaltimeIntoDay sleepTime)
Sets the sleepTime field to sleepTime.
Parameters
sleepTime The field value to set.
Definition at line 631 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->sleepTime = sleepTime;
 }
References sleepTime().
setSpeedSetting()
void UserProfileMessage::setSpeedSetting (const DisplayMeasure speedSetting)
Sets the speedSetting field to speedSetting.
Parameters
speedSetting The field value to set.
Definition at line 541 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->speedSetting = speedSetting;
 }
References speedSetting().
setTemperatureSetting()
void UserProfileMessage::setTemperatureSetting (const DisplayMeasure temperatureSetting)
Sets the temperatureSetting field to temperatureSetting.
Parameters
temperatureSetting The field value to set.
Definition at line 591 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->temperatureSetting = temperatureSetting;
 }
References temperatureSetting().
setUserRunningStepLength()
void UserProfileMessage::setUserRunningStepLength (const quint16 userRunningStepLength)
Sets the userRunningStepLength field to userRunningStepLength.
Parameters
userRunningStepLength The field value to set.
Definition at line 651 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->userRunningStepLength = userRunningStepLength;
 }
References userRunningStepLength().
setUserWalkingStepLength()
void UserProfileMessage::setUserWalkingStepLength (const quint16 userWalkingStepLength)
Sets the userWalkingStepLength field to userWalkingStepLength.
Parameters
userWalkingStepLength The field value to set.
Definition at line 661 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->userWalkingStepLength = userWalkingStepLength;
 }
References userWalkingStepLength().
setWakeTime()
void UserProfileMessage::setWakeTime (const LocaltimeIntoDay wakeTime)
Sets the wakeTime field to wakeTime.
Parameters
wakeTime The field value to set.
Definition at line 621 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->wakeTime = wakeTime;
 }
References wakeTime().
setWeight()
void UserProfileMessage::setWeight (const quint16 weight)
Sets the weight field to weight.
Parameters
weight The field value to set.
Definition at line 451 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->weight = weight;
 }
References weight().
setWeightSetting()
void UserProfileMessage::setWeightSetting (const DisplayMeasure weightSetting)
Sets the weightSetting field to weightSetting.
Parameters
weightSetting The field value to set.
Definition at line 481 of file userprofilemessage.cpp.
 {
     Q_D(UserProfileMessage);
     d->weightSetting = weightSetting;
 }
References weightSetting().
sleepTime()
LocaltimeIntoDay UserProfileMessage::sleepTime () const
Returns the UserProfileMessage data message's sleepTime field's current value.
Typical bed time
Returns
the sleepTime field value.
Definition at line 331 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->sleepTime;
 }
Referenced by setSleepTime().
speedSetting()
DisplayMeasure UserProfileMessage::speedSetting () const
Returns the UserProfileMessage data message's speedSetting field's current value.
Returns
the speedSetting field value.
Definition at line 228 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->speedSetting;
 }
Referenced by setSpeedSetting().
temperatureSetting()
DisplayMeasure UserProfileMessage::temperatureSetting () const
Returns the UserProfileMessage data message's temperatureSetting field's current value.
Returns
the temperatureSetting field value.
Definition at line 283 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->temperatureSetting;
 }
Referenced by setTemperatureSetting().
userRunningStepLength()
quint16 UserProfileMessage::userRunningStepLength () const
Returns the UserProfileMessage data message's userRunningStepLength field's current value.
User defined running step length set to 0 for auto length
Returns
the userRunningStepLength field value.
Definition at line 355 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->userRunningStepLength;
 }
Referenced by setUserRunningStepLength().
userWalkingStepLength()
quint16 UserProfileMessage::userWalkingStepLength () const
Returns the UserProfileMessage data message's userWalkingStepLength field's current value.
User defined walking step length set to 0 for auto length
Returns
the userWalkingStepLength field value.
Definition at line 368 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->userWalkingStepLength;
 }
Referenced by setUserWalkingStepLength().
wakeTime()
LocaltimeIntoDay UserProfileMessage::wakeTime () const
Returns the UserProfileMessage data message's wakeTime field's current value.
Typical wake time
Returns
the wakeTime field value.
Definition at line 318 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->wakeTime;
 }
Referenced by setWakeTime().
weight()
quint16 UserProfileMessage::weight () const
Returns the UserProfileMessage data message's weight field's current value.
Returns
the weight field value.
Definition at line 129 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->weight;
 }
Referenced by setWeight().
weightSetting()
DisplayMeasure UserProfileMessage::weightSetting () const
Returns the UserProfileMessage data message's weightSetting field's current value.
Returns
the weightSetting field value.
Definition at line 162 of file userprofilemessage.cpp.
 {
     Q_D(const UserProfileMessage);
     return d->weightSetting;
 }
Referenced by setWeightSetting().
The documentation for this class was generated from the following files:
userprofilemessage.h
userprofilemessage.cpp