QtFit: SdmProfileMessage Class Reference
SdmProfileMessage Class Reference
The SdmProfileMessage class represents a FIT SdmProfileMessage data message.
Public Member Functions
SdmProfileMessage ()
Constructs a SdmProfileMessage object.
MessageIndex messageIndex () const
Returns the SdmProfileMessage data message's messageIndex field's current value.
bool enabled () const
Returns the SdmProfileMessage data message's enabled field's current value.
quint16z sdmAntId () const
Returns the SdmProfileMessage data message's sdmAntId field's current value.
quint16 sdmCalFactor () const
Returns the SdmProfileMessage data message's sdmCalFactor field's current value.
quint32 odometer () const
Returns the SdmProfileMessage data message's odometer field's current value.
bool speedSource () const
Returns the SdmProfileMessage data message's speedSource field's current value.
quint8z sdmAntIdTransType () const
Returns the SdmProfileMessage data message's sdmAntIdTransType field's current value.
quint8 odometerRollover () const
Returns the SdmProfileMessage data message's odometerRollover field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setEnabled (const bool enabled)
Sets the enabled field to enabled.
void setSdmAntId (const quint16z sdmAntId)
Sets the sdmAntId field to sdmAntId.
void setSdmCalFactor (const quint16 sdmCalFactor)
Sets the sdmCalFactor field to sdmCalFactor.
void setOdometer (const quint32 odometer)
Sets the odometer field to odometer.
void setSpeedSource (const bool speedSource)
Sets the speedSource field to speedSource.
void setSdmAntIdTransType (const quint8z sdmAntIdTransType)
Sets the sdmAntIdTransType field to sdmAntIdTransType.
void setOdometerRollover (const quint8 odometerRollover)
Sets the odometerRollover field to odometerRollover.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
SdmProfileMessage (SdmProfileMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The SdmProfileMessage class represents a FIT SdmProfileMessage data message.
See also
DataMessage
Definition at line 34 of file sdmprofilemessage.h.
Constructor & Destructor Documentation
SdmProfileMessage() [1/2]
SdmProfileMessage::SdmProfileMessage ()
Constructs a SdmProfileMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file sdmprofilemessage.cpp.
                                      : AbstractDataMessage(new SdmProfileMessagePrivate(this))
 {
 }
SdmProfileMessage() [2/2]
SdmProfileMessage::SdmProfileMessage (SdmProfileMessagePrivate *const d) explicit protected
Constructs a SdmProfileMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file sdmprofilemessage.cpp.
                                                                        : AbstractDataMessage(d)
 {
 }
Member Function Documentation
enabled()
bool SdmProfileMessage::enabled () const
Returns the SdmProfileMessage data message's enabled field's current value.
Returns
the enabled field value.
Definition at line 80 of file sdmprofilemessage.cpp.
 {
     Q_D(const SdmProfileMessage);
     return d->enabled;
 }
Referenced by setEnabled().
messageIndex()
MessageIndex SdmProfileMessage::messageIndex () const
Returns the SdmProfileMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 69 of file sdmprofilemessage.cpp.
 {
     Q_D(const SdmProfileMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
odometer()
quint32 SdmProfileMessage::odometer () const
Returns the SdmProfileMessage data message's odometer field's current value.
Returns
the odometer field value.
Definition at line 113 of file sdmprofilemessage.cpp.
 {
     Q_D(const SdmProfileMessage);
     return d->odometer;
 }
Referenced by setOdometer().
odometerRollover()
quint8 SdmProfileMessage::odometerRollover () const
Returns the SdmProfileMessage data message's odometerRollover field's current value.
Rollover counter that can be used to extend the odometer
Returns
the odometerRollover field value.
Definition at line 150 of file sdmprofilemessage.cpp.
 {
     Q_D(const SdmProfileMessage);
     return d->odometerRollover;
 }
Referenced by setOdometerRollover().
sdmAntId()
quint16z SdmProfileMessage::sdmAntId () const
Returns the SdmProfileMessage data message's sdmAntId field's current value.
Returns
the sdmAntId field value.
Definition at line 91 of file sdmprofilemessage.cpp.
 {
     Q_D(const SdmProfileMessage);
     return d->sdmAntId;
 }
Referenced by setSdmAntId().
sdmAntIdTransType()
quint8z SdmProfileMessage::sdmAntIdTransType () const
Returns the SdmProfileMessage data message's sdmAntIdTransType field's current value.
Returns
the sdmAntIdTransType field value.
Definition at line 137 of file sdmprofilemessage.cpp.
 {
     Q_D(const SdmProfileMessage);
     return d->sdmAntIdTransType;
 }
Referenced by setSdmAntIdTransType().
sdmCalFactor()
quint16 SdmProfileMessage::sdmCalFactor () const
Returns the SdmProfileMessage data message's sdmCalFactor field's current value.
Returns
the sdmCalFactor field value.
Definition at line 102 of file sdmprofilemessage.cpp.
 {
     Q_D(const SdmProfileMessage);
     return d->sdmCalFactor;
 }
Referenced by setSdmCalFactor().
setEnabled()
void SdmProfileMessage::setEnabled (const bool enabled)
Sets the enabled field to enabled.
Parameters
enabled The field value to set.
Definition at line 171 of file sdmprofilemessage.cpp.
 {
     Q_D(SdmProfileMessage);
     d->enabled = enabled;
 }
References enabled().
setMessageIndex()
void SdmProfileMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 161 of file sdmprofilemessage.cpp.
 {
     Q_D(SdmProfileMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setOdometer()
void SdmProfileMessage::setOdometer (const quint32 odometer)
Sets the odometer field to odometer.
Parameters
odometer The field value to set.
Definition at line 201 of file sdmprofilemessage.cpp.
 {
     Q_D(SdmProfileMessage);
     d->odometer = odometer;
 }
References odometer().
setOdometerRollover()
void SdmProfileMessage::setOdometerRollover (const quint8 odometerRollover)
Sets the odometerRollover field to odometerRollover.
Parameters
odometerRollover The field value to set.
Definition at line 231 of file sdmprofilemessage.cpp.
 {
     Q_D(SdmProfileMessage);
     d->odometerRollover = odometerRollover;
 }
References odometerRollover().
setSdmAntId()
void SdmProfileMessage::setSdmAntId (const quint16z sdmAntId)
Sets the sdmAntId field to sdmAntId.
Parameters
sdmAntId The field value to set.
Definition at line 181 of file sdmprofilemessage.cpp.
 {
     Q_D(SdmProfileMessage);
     d->sdmAntId = sdmAntId;
 }
References sdmAntId().
setSdmAntIdTransType()
void SdmProfileMessage::setSdmAntIdTransType (const quint8z sdmAntIdTransType)
Sets the sdmAntIdTransType field to sdmAntIdTransType.
Parameters
sdmAntIdTransType The field value to set.
Definition at line 221 of file sdmprofilemessage.cpp.
 {
     Q_D(SdmProfileMessage);
     d->sdmAntIdTransType = sdmAntIdTransType;
 }
References sdmAntIdTransType().
setSdmCalFactor()
void SdmProfileMessage::setSdmCalFactor (const quint16 sdmCalFactor)
Sets the sdmCalFactor field to sdmCalFactor.
Parameters
sdmCalFactor The field value to set.
Definition at line 191 of file sdmprofilemessage.cpp.
 {
     Q_D(SdmProfileMessage);
     d->sdmCalFactor = sdmCalFactor;
 }
References sdmCalFactor().
setSpeedSource()
void SdmProfileMessage::setSpeedSource (const bool speedSource)
Sets the speedSource field to speedSource.
Parameters
speedSource The field value to set.
Definition at line 211 of file sdmprofilemessage.cpp.
 {
     Q_D(SdmProfileMessage);
     d->speedSource = speedSource;
 }
References speedSource().
speedSource()
bool SdmProfileMessage::speedSource () const
Returns the SdmProfileMessage data message's speedSource field's current value.
Use footpod for speed source instead of GPS
Returns
the speedSource field value.
Definition at line 126 of file sdmprofilemessage.cpp.
 {
     Q_D(const SdmProfileMessage);
     return d->speedSource;
 }
Referenced by setSpeedSource().
The documentation for this class was generated from the following files:
sdmprofilemessage.h
sdmprofilemessage.cpp