QtFit: DeviceSettingsMessage Class Reference
DeviceSettingsMessage Class Reference
The DeviceSettingsMessage class represents a FIT DeviceSettingsMessage data message.
Public Member Functions
DeviceSettingsMessage ()
Constructs a DeviceSettingsMessage object.
quint8 activeTimeZone () const
Returns the DeviceSettingsMessage data message's activeTimeZone field's current value.
quint32 utcOffset () const
Returns the DeviceSettingsMessage data message's utcOffset field's current value.
quint32 timeOffset () const
Returns the DeviceSettingsMessage data message's timeOffset field's current value.
TimeMode timeMode () const
Returns the DeviceSettingsMessage data message's timeMode field's current value.
qint8 timeZoneOffset () const
Returns the DeviceSettingsMessage data message's timeZoneOffset field's current value.
BacklightMode backlightMode () const
Returns the DeviceSettingsMessage data message's backlightMode field's current value.
bool activityTrackerEnabled () const
Returns the DeviceSettingsMessage data message's activityTrackerEnabled field's current value.
DateTime clockTime () const
Returns the DeviceSettingsMessage data message's clockTime field's current value.
quint16 pagesEnabled () const
Returns the DeviceSettingsMessage data message's pagesEnabled field's current value.
bool moveAlertEnabled () const
Returns the DeviceSettingsMessage data message's moveAlertEnabled field's current value.
DateMode dateMode () const
Returns the DeviceSettingsMessage data message's dateMode field's current value.
DisplayOrientation displayOrientation () const
Returns the DeviceSettingsMessage data message's displayOrientation field's current value.
Side mountingSide () const
Returns the DeviceSettingsMessage data message's mountingSide field's current value.
quint16 defaultPage () const
Returns the DeviceSettingsMessage data message's defaultPage field's current value.
quint16 autosyncMinSteps () const
Returns the DeviceSettingsMessage data message's autosyncMinSteps field's current value.
quint16 autosyncMinTime () const
Returns the DeviceSettingsMessage data message's autosyncMinTime field's current value.
bool lactateThresholdAutodetectEnabled () const
Returns the DeviceSettingsMessage data message's lactateThresholdAutodetectEnabled field's current value.
bool bleAutoUploadEnabled () const
Returns the DeviceSettingsMessage data message's bleAutoUploadEnabled field's current value.
AutoSyncFrequency autoSyncFrequency () const
Returns the DeviceSettingsMessage data message's autoSyncFrequency field's current value.
AutoActivityDetect autoActivityDetect () const
Returns the DeviceSettingsMessage data message's autoActivityDetect field's current value.
quint8 numberOfScreens () const
Returns the DeviceSettingsMessage data message's numberOfScreens field's current value.
DisplayOrientation smartNotificationDisplayOrientation () const
Returns the DeviceSettingsMessage data message's smartNotificationDisplayOrientation field's current value.
Switch tapInterface () const
Returns the DeviceSettingsMessage data message's tapInterface field's current value.
TapSensitivity tapSensitivity () const
Returns the DeviceSettingsMessage data message's tapSensitivity field's current value.
void setActiveTimeZone (const quint8 activeTimeZone)
Sets the activeTimeZone field to activeTimeZone.
void setUtcOffset (const quint32 utcOffset)
Sets the utcOffset field to utcOffset.
void setTimeOffset (const quint32 timeOffset)
Sets the timeOffset field to timeOffset.
void setTimeMode (const TimeMode timeMode)
Sets the timeMode field to timeMode.
void setTimeZoneOffset (const qint8 timeZoneOffset)
Sets the timeZoneOffset field to timeZoneOffset.
void setBacklightMode (const BacklightMode backlightMode)
Sets the backlightMode field to backlightMode.
void setActivityTrackerEnabled (const bool activityTrackerEnabled)
Sets the activityTrackerEnabled field to activityTrackerEnabled.
void setClockTime (const DateTime clockTime)
Sets the clockTime field to clockTime.
void setPagesEnabled (const quint16 pagesEnabled)
Sets the pagesEnabled field to pagesEnabled.
void setMoveAlertEnabled (const bool moveAlertEnabled)
Sets the moveAlertEnabled field to moveAlertEnabled.
void setDateMode (const DateMode dateMode)
Sets the dateMode field to dateMode.
void setDisplayOrientation (const DisplayOrientation displayOrientation)
Sets the displayOrientation field to displayOrientation.
void setMountingSide (const Side mountingSide)
Sets the mountingSide field to mountingSide.
void setDefaultPage (const quint16 defaultPage)
Sets the defaultPage field to defaultPage.
void setAutosyncMinSteps (const quint16 autosyncMinSteps)
Sets the autosyncMinSteps field to autosyncMinSteps.
void setAutosyncMinTime (const quint16 autosyncMinTime)
Sets the autosyncMinTime field to autosyncMinTime.
void setLactateThresholdAutodetectEnabled (const bool lactateThresholdAutodetectEnabled)
Sets the lactateThresholdAutodetectEnabled field to lactateThresholdAutodetectEnabled.
void setBleAutoUploadEnabled (const bool bleAutoUploadEnabled)
Sets the bleAutoUploadEnabled field to bleAutoUploadEnabled.
void setAutoSyncFrequency (const AutoSyncFrequency autoSyncFrequency)
Sets the autoSyncFrequency field to autoSyncFrequency.
void setAutoActivityDetect (const AutoActivityDetect autoActivityDetect)
Sets the autoActivityDetect field to autoActivityDetect.
void setNumberOfScreens (const quint8 numberOfScreens)
Sets the numberOfScreens field to numberOfScreens.
void setSmartNotificationDisplayOrientation (const DisplayOrientation smartNotificationDisplayOrientation)
Sets the smartNotificationDisplayOrientation field to smartNotificationDisplayOrientation.
void setTapInterface (const Switch tapInterface)
Sets the tapInterface field to tapInterface.
void setTapSensitivity (const TapSensitivity tapSensitivity)
Sets the tapSensitivity field to tapSensitivity.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
DeviceSettingsMessage (DeviceSettingsMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The DeviceSettingsMessage class represents a FIT DeviceSettingsMessage data message.
See also
DataMessage
Definition at line 39 of file devicesettingsmessage.h.
Constructor & Destructor Documentation
DeviceSettingsMessage() [1/2]
DeviceSettingsMessage::DeviceSettingsMessage ()
Constructs a DeviceSettingsMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file devicesettingsmessage.cpp.
                                              : AbstractDataMessage(new DeviceSettingsMessagePrivate(this))
 {
 }
DeviceSettingsMessage() [2/2]
DeviceSettingsMessage::DeviceSettingsMessage (DeviceSettingsMessagePrivate *const d) explicit protected
Constructs a DeviceSettingsMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file devicesettingsmessage.cpp.
                                                                                    : AbstractDataMessage(d)
 {
 }
Member Function Documentation
activeTimeZone()
quint8 DeviceSettingsMessage::activeTimeZone () const
Returns the DeviceSettingsMessage data message's activeTimeZone field's current value.
Index into time zone arrays.
Returns
the activeTimeZone field value.
Definition at line 76 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->activeTimeZone;
 }
Referenced by setActiveTimeZone().
activityTrackerEnabled()
bool DeviceSettingsMessage::activityTrackerEnabled () const
Returns the DeviceSettingsMessage data message's activityTrackerEnabled field's current value.
Enabled state of the activity tracker functionality
Returns
the activityTrackerEnabled field value.
Definition at line 154 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->activityTrackerEnabled;
 }
Referenced by setActivityTrackerEnabled().
autoActivityDetect()
AutoActivityDetect DeviceSettingsMessage::autoActivityDetect () const
Returns the DeviceSettingsMessage data message's autoActivityDetect field's current value.
Allows setting specific activities auto-activity detect enabled/disabled settings
Returns
the autoActivityDetect field value.
Definition at line 319 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->autoActivityDetect;
 }
Referenced by setAutoActivityDetect().
autoSyncFrequency()
AutoSyncFrequency DeviceSettingsMessage::autoSyncFrequency () const
Returns the DeviceSettingsMessage data message's autoSyncFrequency field's current value.
Helps to conserve battery by changing modes
Returns
the autoSyncFrequency field value.
Definition at line 306 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->autoSyncFrequency;
 }
Referenced by setAutoSyncFrequency().
autosyncMinSteps()
quint16 DeviceSettingsMessage::autosyncMinSteps () const
Returns the DeviceSettingsMessage data message's autosyncMinSteps field's current value.
Minimum steps before an autosync can occur
Returns
the autosyncMinSteps field value.
Definition at line 254 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->autosyncMinSteps;
 }
Referenced by setAutosyncMinSteps().
autosyncMinTime()
quint16 DeviceSettingsMessage::autosyncMinTime () const
Returns the DeviceSettingsMessage data message's autosyncMinTime field's current value.
Minimum minutes before an autosync can occur
Returns
the autosyncMinTime field value.
Definition at line 267 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->autosyncMinTime;
 }
Referenced by setAutosyncMinTime().
backlightMode()
BacklightMode DeviceSettingsMessage::backlightMode () const
Returns the DeviceSettingsMessage data message's backlightMode field's current value.
Mode for backlight
Returns
the backlightMode field value.
Definition at line 141 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->backlightMode;
 }
Referenced by setBacklightMode().
bleAutoUploadEnabled()
bool DeviceSettingsMessage::bleAutoUploadEnabled () const
Returns the DeviceSettingsMessage data message's bleAutoUploadEnabled field's current value.
Automatically upload using BLE
Returns
the bleAutoUploadEnabled field value.
Definition at line 293 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->bleAutoUploadEnabled;
 }
Referenced by setBleAutoUploadEnabled().
clockTime()
DateTime DeviceSettingsMessage::clockTime () const
Returns the DeviceSettingsMessage data message's clockTime field's current value.
UTC timestamp used to set the devices clock and date
Returns
the clockTime field value.
Definition at line 167 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->clockTime;
 }
Referenced by setClockTime().
dateMode()
DateMode DeviceSettingsMessage::dateMode () const
Returns the DeviceSettingsMessage data message's dateMode field's current value.
Display mode for the date
Returns
the dateMode field value.
Definition at line 206 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->dateMode;
 }
Referenced by setDateMode().
defaultPage()
quint16 DeviceSettingsMessage::defaultPage () const
Returns the DeviceSettingsMessage data message's defaultPage field's current value.
Bitfield to indicate one page as default for each supported loop
Returns
the defaultPage field value.
Definition at line 241 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->defaultPage;
 }
Referenced by setDefaultPage().
displayOrientation()
DisplayOrientation DeviceSettingsMessage::displayOrientation () const
Returns the DeviceSettingsMessage data message's displayOrientation field's current value.
Returns
the displayOrientation field value.
Definition at line 217 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->displayOrientation;
 }
Referenced by setDisplayOrientation().
lactateThresholdAutodetectEnabled()
bool DeviceSettingsMessage::lactateThresholdAutodetectEnabled () const
Returns the DeviceSettingsMessage data message's lactateThresholdAutodetectEnabled field's current value.
Enable auto-detect setting for the lactate threshold feature.
Returns
the lactateThresholdAutodetectEnabled field value.
Definition at line 280 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->lactateThresholdAutodetectEnabled;
 }
Referenced by setLactateThresholdAutodetectEnabled().
mountingSide()
Side DeviceSettingsMessage::mountingSide () const
Returns the DeviceSettingsMessage data message's mountingSide field's current value.
Returns
the mountingSide field value.
Definition at line 228 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->mountingSide;
 }
Referenced by setMountingSide().
moveAlertEnabled()
bool DeviceSettingsMessage::moveAlertEnabled () const
Returns the DeviceSettingsMessage data message's moveAlertEnabled field's current value.
Enabled state of the move alert
Returns
the moveAlertEnabled field value.
Definition at line 193 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->moveAlertEnabled;
 }
Referenced by setMoveAlertEnabled().
numberOfScreens()
quint8 DeviceSettingsMessage::numberOfScreens () const
Returns the DeviceSettingsMessage data message's numberOfScreens field's current value.
Number of screens configured to display
Returns
the numberOfScreens field value.
Definition at line 332 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->numberOfScreens;
 }
Referenced by setNumberOfScreens().
pagesEnabled()
quint16 DeviceSettingsMessage::pagesEnabled () const
Returns the DeviceSettingsMessage data message's pagesEnabled field's current value.
Bitfield to configure enabled screens for each supported loop
Returns
the pagesEnabled field value.
Definition at line 180 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->pagesEnabled;
 }
Referenced by setPagesEnabled().
setActiveTimeZone()
void DeviceSettingsMessage::setActiveTimeZone (const quint8 activeTimeZone)
Sets the activeTimeZone field to activeTimeZone.
Parameters
activeTimeZone The field value to set.
Definition at line 380 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->activeTimeZone = activeTimeZone;
 }
References activeTimeZone().
setActivityTrackerEnabled()
void DeviceSettingsMessage::setActivityTrackerEnabled (const bool activityTrackerEnabled)
Sets the activityTrackerEnabled field to activityTrackerEnabled.
Parameters
activityTrackerEnabled The field value to set.
Definition at line 440 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->activityTrackerEnabled = activityTrackerEnabled;
 }
References activityTrackerEnabled().
setAutoActivityDetect()
void DeviceSettingsMessage::setAutoActivityDetect (const AutoActivityDetect autoActivityDetect)
Sets the autoActivityDetect field to autoActivityDetect.
Parameters
autoActivityDetect The field value to set.
Definition at line 570 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->autoActivityDetect = autoActivityDetect;
 }
References autoActivityDetect().
setAutoSyncFrequency()
void DeviceSettingsMessage::setAutoSyncFrequency (const AutoSyncFrequency autoSyncFrequency)
Sets the autoSyncFrequency field to autoSyncFrequency.
Parameters
autoSyncFrequency The field value to set.
Definition at line 560 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->autoSyncFrequency = autoSyncFrequency;
 }
References autoSyncFrequency().
setAutosyncMinSteps()
void DeviceSettingsMessage::setAutosyncMinSteps (const quint16 autosyncMinSteps)
Sets the autosyncMinSteps field to autosyncMinSteps.
Parameters
autosyncMinSteps The field value to set.
Definition at line 520 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->autosyncMinSteps = autosyncMinSteps;
 }
References autosyncMinSteps().
setAutosyncMinTime()
void DeviceSettingsMessage::setAutosyncMinTime (const quint16 autosyncMinTime)
Sets the autosyncMinTime field to autosyncMinTime.
Parameters
autosyncMinTime The field value to set.
Definition at line 530 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->autosyncMinTime = autosyncMinTime;
 }
References autosyncMinTime().
setBacklightMode()
void DeviceSettingsMessage::setBacklightMode (const BacklightMode backlightMode)
Sets the backlightMode field to backlightMode.
Parameters
backlightMode The field value to set.
Definition at line 430 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->backlightMode = backlightMode;
 }
References backlightMode().
setBleAutoUploadEnabled()
void DeviceSettingsMessage::setBleAutoUploadEnabled (const bool bleAutoUploadEnabled)
Sets the bleAutoUploadEnabled field to bleAutoUploadEnabled.
Parameters
bleAutoUploadEnabled The field value to set.
Definition at line 550 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->bleAutoUploadEnabled = bleAutoUploadEnabled;
 }
References bleAutoUploadEnabled().
setClockTime()
void DeviceSettingsMessage::setClockTime (const DateTime clockTime)
Sets the clockTime field to clockTime.
Parameters
clockTime The field value to set.
Definition at line 450 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->clockTime = clockTime;
 }
References clockTime().
setDateMode()
void DeviceSettingsMessage::setDateMode (const DateMode dateMode)
Sets the dateMode field to dateMode.
Parameters
dateMode The field value to set.
Definition at line 480 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->dateMode = dateMode;
 }
References dateMode().
setDefaultPage()
void DeviceSettingsMessage::setDefaultPage (const quint16 defaultPage)
Sets the defaultPage field to defaultPage.
Parameters
defaultPage The field value to set.
Definition at line 510 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->defaultPage = defaultPage;
 }
References defaultPage().
setDisplayOrientation()
void DeviceSettingsMessage::setDisplayOrientation (const DisplayOrientation displayOrientation)
Sets the displayOrientation field to displayOrientation.
Parameters
displayOrientation The field value to set.
Definition at line 490 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->displayOrientation = displayOrientation;
 }
References displayOrientation().
setLactateThresholdAutodetectEnabled()
void DeviceSettingsMessage::setLactateThresholdAutodetectEnabled (const bool lactateThresholdAutodetectEnabled)
Sets the lactateThresholdAutodetectEnabled field to lactateThresholdAutodetectEnabled.
Parameters
lactateThresholdAutodetectEnabled The field value to set.
Definition at line 540 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->lactateThresholdAutodetectEnabled = lactateThresholdAutodetectEnabled;
 }
References lactateThresholdAutodetectEnabled().
setMountingSide()
void DeviceSettingsMessage::setMountingSide (const Side mountingSide)
Sets the mountingSide field to mountingSide.
Parameters
mountingSide The field value to set.
Definition at line 500 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->mountingSide = mountingSide;
 }
References mountingSide().
setMoveAlertEnabled()
void DeviceSettingsMessage::setMoveAlertEnabled (const bool moveAlertEnabled)
Sets the moveAlertEnabled field to moveAlertEnabled.
Parameters
moveAlertEnabled The field value to set.
Definition at line 470 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->moveAlertEnabled = moveAlertEnabled;
 }
References moveAlertEnabled().
setNumberOfScreens()
void DeviceSettingsMessage::setNumberOfScreens (const quint8 numberOfScreens)
Sets the numberOfScreens field to numberOfScreens.
Parameters
numberOfScreens The field value to set.
Definition at line 580 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->numberOfScreens = numberOfScreens;
 }
References numberOfScreens().
setPagesEnabled()
void DeviceSettingsMessage::setPagesEnabled (const quint16 pagesEnabled)
Sets the pagesEnabled field to pagesEnabled.
Parameters
pagesEnabled The field value to set.
Definition at line 460 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->pagesEnabled = pagesEnabled;
 }
References pagesEnabled().
setSmartNotificationDisplayOrientation()
void DeviceSettingsMessage::setSmartNotificationDisplayOrientation (const DisplayOrientation smartNotificationDisplayOrientation)
Sets the smartNotificationDisplayOrientation field to smartNotificationDisplayOrientation.
Parameters
smartNotificationDisplayOrientation The field value to set.
Definition at line 590 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->smartNotificationDisplayOrientation = smartNotificationDisplayOrientation;
 }
References smartNotificationDisplayOrientation().
setTapInterface()
void DeviceSettingsMessage::setTapInterface (const Switch tapInterface)
Sets the tapInterface field to tapInterface.
Parameters
tapInterface The field value to set.
Definition at line 600 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->tapInterface = tapInterface;
 }
References tapInterface().
setTapSensitivity()
void DeviceSettingsMessage::setTapSensitivity (const TapSensitivity tapSensitivity)
Sets the tapSensitivity field to tapSensitivity.
Parameters
tapSensitivity The field value to set.
Definition at line 610 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->tapSensitivity = tapSensitivity;
 }
References tapSensitivity().
setTimeMode()
void DeviceSettingsMessage::setTimeMode (const TimeMode timeMode)
Sets the timeMode field to timeMode.
Parameters
timeMode The field value to set.
Definition at line 410 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->timeMode = timeMode;
 }
References timeMode().
setTimeOffset()
void DeviceSettingsMessage::setTimeOffset (const quint32 timeOffset)
Sets the timeOffset field to timeOffset.
Parameters
timeOffset The field value to set.
Definition at line 400 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->timeOffset = timeOffset;
 }
References timeOffset().
setTimeZoneOffset()
void DeviceSettingsMessage::setTimeZoneOffset (const qint8 timeZoneOffset)
Sets the timeZoneOffset field to timeZoneOffset.
Parameters
timeZoneOffset The field value to set.
Definition at line 420 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->timeZoneOffset = timeZoneOffset;
 }
References timeZoneOffset().
setUtcOffset()
void DeviceSettingsMessage::setUtcOffset (const quint32 utcOffset)
Sets the utcOffset field to utcOffset.
Parameters
utcOffset The field value to set.
Definition at line 390 of file devicesettingsmessage.cpp.
 {
     Q_D(DeviceSettingsMessage);
     d->utcOffset = utcOffset;
 }
References utcOffset().
smartNotificationDisplayOrientation()
DisplayOrientation DeviceSettingsMessage::smartNotificationDisplayOrientation () const
Returns the DeviceSettingsMessage data message's smartNotificationDisplayOrientation field's current value.
Smart Notification display orientation
Returns
the smartNotificationDisplayOrientation field value.
Definition at line 345 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->smartNotificationDisplayOrientation;
 }
Referenced by setSmartNotificationDisplayOrientation().
tapInterface()
Switch DeviceSettingsMessage::tapInterface () const
Returns the DeviceSettingsMessage data message's tapInterface field's current value.
Returns
the tapInterface field value.
Definition at line 356 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->tapInterface;
 }
Referenced by setTapInterface().
tapSensitivity()
TapSensitivity DeviceSettingsMessage::tapSensitivity () const
Returns the DeviceSettingsMessage data message's tapSensitivity field's current value.
Used to hold the tap threshold setting
Returns
the tapSensitivity field value.
Definition at line 369 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->tapSensitivity;
 }
Referenced by setTapSensitivity().
timeMode()
TimeMode DeviceSettingsMessage::timeMode () const
Returns the DeviceSettingsMessage data message's timeMode field's current value.
Display mode for the time
Returns
the timeMode field value.
Definition at line 115 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->timeMode;
 }
Referenced by setTimeMode().
timeOffset()
quint32 DeviceSettingsMessage::timeOffset () const
Returns the DeviceSettingsMessage data message's timeOffset field's current value.
Offset from system time.
Returns
the timeOffset field value.
Definition at line 102 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->timeOffset;
 }
Referenced by setTimeOffset().
timeZoneOffset()
qint8 DeviceSettingsMessage::timeZoneOffset () const
Returns the DeviceSettingsMessage data message's timeZoneOffset field's current value.
timezone offset in 1/4 hour increments
Returns
the timeZoneOffset field value.
Definition at line 128 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->timeZoneOffset;
 }
Referenced by setTimeZoneOffset().
utcOffset()
quint32 DeviceSettingsMessage::utcOffset () const
Returns the DeviceSettingsMessage data message's utcOffset field's current value.
Offset from system time. Required to convert timestamp from system time to UTC.
Returns
the utcOffset field value.
Definition at line 89 of file devicesettingsmessage.cpp.
 {
     Q_D(const DeviceSettingsMessage);
     return d->utcOffset;
 }
Referenced by setUtcOffset().
The documentation for this class was generated from the following files:
devicesettingsmessage.h
devicesettingsmessage.cpp