QtFit: TimestampCorrelationMessage Class Reference
TimestampCorrelationMessage Class Reference
The TimestampCorrelationMessage class represents a FIT TimestampCorrelationMessage data message.
Public Member Functions
TimestampCorrelationMessage ()
Constructs a TimestampCorrelationMessage object.
DateTime timestamp () const
Returns the TimestampCorrelationMessage data message's timestamp field's current value.
quint16 fractionalTimestamp () const
Returns the TimestampCorrelationMessage data message's fractionalTimestamp field's current value.
DateTime systemTimestamp () const
Returns the TimestampCorrelationMessage data message's systemTimestamp field's current value.
quint16 fractionalSystemTimestamp () const
Returns the TimestampCorrelationMessage data message's fractionalSystemTimestamp field's current value.
LocalDateTime localTimestamp () const
Returns the TimestampCorrelationMessage data message's localTimestamp field's current value.
quint16 timestampMs () const
Returns the TimestampCorrelationMessage data message's timestampMs field's current value.
quint16 systemTimestampMs () const
Returns the TimestampCorrelationMessage data message's systemTimestampMs field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setFractionalTimestamp (const quint16 fractionalTimestamp)
Sets the fractionalTimestamp field to fractionalTimestamp.
void setSystemTimestamp (const DateTime systemTimestamp)
Sets the systemTimestamp field to systemTimestamp.
void setFractionalSystemTimestamp (const quint16 fractionalSystemTimestamp)
Sets the fractionalSystemTimestamp field to fractionalSystemTimestamp.
void setLocalTimestamp (const LocalDateTime localTimestamp)
Sets the localTimestamp field to localTimestamp.
void setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
void setSystemTimestampMs (const quint16 systemTimestampMs)
Sets the systemTimestampMs field to systemTimestampMs.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
TimestampCorrelationMessage (TimestampCorrelationMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The TimestampCorrelationMessage class represents a FIT TimestampCorrelationMessage data message.
See also
DataMessage
Definition at line 39 of file timestampcorrelationmessage.h.
Constructor & Destructor Documentation
TimestampCorrelationMessage() [1/2]
TimestampCorrelationMessage::TimestampCorrelationMessage ()
Constructs a TimestampCorrelationMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file timestampcorrelationmessage.cpp.
                                                          : AbstractDataMessage(new TimestampCorrelationMessagePrivate(this))
 {
 }
TimestampCorrelationMessage() [2/2]
TimestampCorrelationMessage::TimestampCorrelationMessage (TimestampCorrelationMessagePrivate *const d) explicit protected
Constructs a TimestampCorrelationMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file timestampcorrelationmessage.cpp.
                                                                                                      : AbstractDataMessage(d)
 {
 }
Member Function Documentation
fractionalSystemTimestamp()
quint16 TimestampCorrelationMessage::fractionalSystemTimestamp () const
Returns the TimestampCorrelationMessage data message's fractionalSystemTimestamp field's current value.
Fractional part of the system timestamp
Returns
the fractionalSystemTimestamp field value.
Definition at line 115 of file timestampcorrelationmessage.cpp.
 {
     Q_D(const TimestampCorrelationMessage);
     return d->fractionalSystemTimestamp;
 }
Referenced by setFractionalSystemTimestamp().
fractionalTimestamp()
quint16 TimestampCorrelationMessage::fractionalTimestamp () const
Returns the TimestampCorrelationMessage data message's fractionalTimestamp field's current value.
Fractional part of the UTC timestamp at the time the system timestamp was recorded.
Returns
the fractionalTimestamp field value.
Definition at line 89 of file timestampcorrelationmessage.cpp.
 {
     Q_D(const TimestampCorrelationMessage);
     return d->fractionalTimestamp;
 }
Referenced by setFractionalTimestamp().
localTimestamp()
LocalDateTime TimestampCorrelationMessage::localTimestamp () const
Returns the TimestampCorrelationMessage data message's localTimestamp field's current value.
timestamp epoch expressed in local time used to convert timestamps to local time
Returns
the localTimestamp field value.
Definition at line 128 of file timestampcorrelationmessage.cpp.
 {
     Q_D(const TimestampCorrelationMessage);
     return d->localTimestamp;
 }
Referenced by setLocalTimestamp().
setFractionalSystemTimestamp()
void TimestampCorrelationMessage::setFractionalSystemTimestamp (const quint16 fractionalSystemTimestamp)
Sets the fractionalSystemTimestamp field to fractionalSystemTimestamp.
Parameters
fractionalSystemTimestamp The field value to set.
Definition at line 195 of file timestampcorrelationmessage.cpp.
 {
     Q_D(TimestampCorrelationMessage);
     d->fractionalSystemTimestamp = fractionalSystemTimestamp;
 }
References fractionalSystemTimestamp().
setFractionalTimestamp()
void TimestampCorrelationMessage::setFractionalTimestamp (const quint16 fractionalTimestamp)
Sets the fractionalTimestamp field to fractionalTimestamp.
Parameters
fractionalTimestamp The field value to set.
Definition at line 175 of file timestampcorrelationmessage.cpp.
 {
     Q_D(TimestampCorrelationMessage);
     d->fractionalTimestamp = fractionalTimestamp;
 }
References fractionalTimestamp().
setLocalTimestamp()
void TimestampCorrelationMessage::setLocalTimestamp (const LocalDateTime localTimestamp)
Sets the localTimestamp field to localTimestamp.
Parameters
localTimestamp The field value to set.
Definition at line 205 of file timestampcorrelationmessage.cpp.
 {
     Q_D(TimestampCorrelationMessage);
     d->localTimestamp = localTimestamp;
 }
References localTimestamp().
setSystemTimestamp()
void TimestampCorrelationMessage::setSystemTimestamp (const DateTime systemTimestamp)
Sets the systemTimestamp field to systemTimestamp.
Parameters
systemTimestamp The field value to set.
Definition at line 185 of file timestampcorrelationmessage.cpp.
 {
     Q_D(TimestampCorrelationMessage);
     d->systemTimestamp = systemTimestamp;
 }
References systemTimestamp().
setSystemTimestampMs()
void TimestampCorrelationMessage::setSystemTimestampMs (const quint16 systemTimestampMs)
Sets the systemTimestampMs field to systemTimestampMs.
Parameters
systemTimestampMs The field value to set.
Definition at line 225 of file timestampcorrelationmessage.cpp.
 {
     Q_D(TimestampCorrelationMessage);
     d->systemTimestampMs = systemTimestampMs;
 }
References systemTimestampMs().
setTimestamp()
void TimestampCorrelationMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 165 of file timestampcorrelationmessage.cpp.
 {
     Q_D(TimestampCorrelationMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setTimestampMs()
void TimestampCorrelationMessage::setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
Parameters
timestampMs The field value to set.
Definition at line 215 of file timestampcorrelationmessage.cpp.
 {
     Q_D(TimestampCorrelationMessage);
     d->timestampMs = timestampMs;
 }
References timestampMs().
systemTimestamp()
DateTime TimestampCorrelationMessage::systemTimestamp () const
Returns the TimestampCorrelationMessage data message's systemTimestamp field's current value.
Whole second part of the system timestamp
Returns
the systemTimestamp field value.
Definition at line 102 of file timestampcorrelationmessage.cpp.
 {
     Q_D(const TimestampCorrelationMessage);
     return d->systemTimestamp;
 }
Referenced by setSystemTimestamp().
systemTimestampMs()
quint16 TimestampCorrelationMessage::systemTimestampMs () const
Returns the TimestampCorrelationMessage data message's systemTimestampMs field's current value.
Millisecond part of the system timestamp
Returns
the systemTimestampMs field value.
Definition at line 154 of file timestampcorrelationmessage.cpp.
 {
     Q_D(const TimestampCorrelationMessage);
     return d->systemTimestampMs;
 }
Referenced by setSystemTimestampMs().
timestamp()
DateTime TimestampCorrelationMessage::timestamp () const
Returns the TimestampCorrelationMessage data message's timestamp field's current value.
Whole second part of UTC timestamp at the time the system timestamp was recorded.
Returns
the timestamp field value.
Definition at line 76 of file timestampcorrelationmessage.cpp.
 {
     Q_D(const TimestampCorrelationMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
timestampMs()
quint16 TimestampCorrelationMessage::timestampMs () const
Returns the TimestampCorrelationMessage data message's timestampMs field's current value.
Millisecond part of the UTC timestamp at the time the system timestamp was recorded.
Returns
the timestampMs field value.
Definition at line 141 of file timestampcorrelationmessage.cpp.
 {
     Q_D(const TimestampCorrelationMessage);
     return d->timestampMs;
 }
Referenced by setTimestampMs().
The documentation for this class was generated from the following files:
timestampcorrelationmessage.h
timestampcorrelationmessage.cpp