QtFit: HrmProfileMessage Class Reference
HrmProfileMessage Class Reference
The HrmProfileMessage class represents a FIT HrmProfileMessage data message.
Public Member Functions
HrmProfileMessage ()
Constructs a HrmProfileMessage object.
MessageIndex messageIndex () const
Returns the HrmProfileMessage data message's messageIndex field's current value.
bool enabled () const
Returns the HrmProfileMessage data message's enabled field's current value.
quint16z hrmAntId () const
Returns the HrmProfileMessage data message's hrmAntId field's current value.
bool logHrv () const
Returns the HrmProfileMessage data message's logHrv field's current value.
quint8z hrmAntIdTransType () const
Returns the HrmProfileMessage data message's hrmAntIdTransType field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setEnabled (const bool enabled)
Sets the enabled field to enabled.
void setHrmAntId (const quint16z hrmAntId)
Sets the hrmAntId field to hrmAntId.
void setLogHrv (const bool logHrv)
Sets the logHrv field to logHrv.
void setHrmAntIdTransType (const quint8z hrmAntIdTransType)
Sets the hrmAntIdTransType field to hrmAntIdTransType.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
HrmProfileMessage (HrmProfileMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The HrmProfileMessage class represents a FIT HrmProfileMessage data message.
See also
DataMessage
Definition at line 34 of file hrmprofilemessage.h.
Constructor & Destructor Documentation
HrmProfileMessage() [1/2]
HrmProfileMessage::HrmProfileMessage ()
Constructs a HrmProfileMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file hrmprofilemessage.cpp.
                                      : AbstractDataMessage(new HrmProfileMessagePrivate(this))
 {
 }
HrmProfileMessage() [2/2]
HrmProfileMessage::HrmProfileMessage (HrmProfileMessagePrivate *const d) explicit protected
Constructs a HrmProfileMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file hrmprofilemessage.cpp.
                                                                        : AbstractDataMessage(d)
 {
 }
Member Function Documentation
enabled()
bool HrmProfileMessage::enabled () const
Returns the HrmProfileMessage data message's enabled field's current value.
Returns
the enabled field value.
Definition at line 80 of file hrmprofilemessage.cpp.
 {
     Q_D(const HrmProfileMessage);
     return d->enabled;
 }
Referenced by setEnabled().
hrmAntId()
quint16z HrmProfileMessage::hrmAntId () const
Returns the HrmProfileMessage data message's hrmAntId field's current value.
Returns
the hrmAntId field value.
Definition at line 91 of file hrmprofilemessage.cpp.
 {
     Q_D(const HrmProfileMessage);
     return d->hrmAntId;
 }
Referenced by setHrmAntId().
hrmAntIdTransType()
quint8z HrmProfileMessage::hrmAntIdTransType () const
Returns the HrmProfileMessage data message's hrmAntIdTransType field's current value.
Returns
the hrmAntIdTransType field value.
Definition at line 113 of file hrmprofilemessage.cpp.
 {
     Q_D(const HrmProfileMessage);
     return d->hrmAntIdTransType;
 }
Referenced by setHrmAntIdTransType().
logHrv()
bool HrmProfileMessage::logHrv () const
Returns the HrmProfileMessage data message's logHrv field's current value.
Returns
the logHrv field value.
Definition at line 102 of file hrmprofilemessage.cpp.
 {
     Q_D(const HrmProfileMessage);
     return d->logHrv;
 }
Referenced by setLogHrv().
messageIndex()
MessageIndex HrmProfileMessage::messageIndex () const
Returns the HrmProfileMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 69 of file hrmprofilemessage.cpp.
 {
     Q_D(const HrmProfileMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
setEnabled()
void HrmProfileMessage::setEnabled (const bool enabled)
Sets the enabled field to enabled.
Parameters
enabled The field value to set.
Definition at line 134 of file hrmprofilemessage.cpp.
 {
     Q_D(HrmProfileMessage);
     d->enabled = enabled;
 }
References enabled().
setHrmAntId()
void HrmProfileMessage::setHrmAntId (const quint16z hrmAntId)
Sets the hrmAntId field to hrmAntId.
Parameters
hrmAntId The field value to set.
Definition at line 144 of file hrmprofilemessage.cpp.
 {
     Q_D(HrmProfileMessage);
     d->hrmAntId = hrmAntId;
 }
References hrmAntId().
setHrmAntIdTransType()
void HrmProfileMessage::setHrmAntIdTransType (const quint8z hrmAntIdTransType)
Sets the hrmAntIdTransType field to hrmAntIdTransType.
Parameters
hrmAntIdTransType The field value to set.
Definition at line 164 of file hrmprofilemessage.cpp.
 {
     Q_D(HrmProfileMessage);
     d->hrmAntIdTransType = hrmAntIdTransType;
 }
References hrmAntIdTransType().
setLogHrv()
void HrmProfileMessage::setLogHrv (const bool logHrv)
Sets the logHrv field to logHrv.
Parameters
logHrv The field value to set.
Definition at line 154 of file hrmprofilemessage.cpp.
 {
     Q_D(HrmProfileMessage);
     d->logHrv = logHrv;
 }
References logHrv().
setMessageIndex()
void HrmProfileMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 124 of file hrmprofilemessage.cpp.
 {
     Q_D(HrmProfileMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
The documentation for this class was generated from the following files:
hrmprofilemessage.h
hrmprofilemessage.cpp