QtFit: SoftwareMessage Class Reference
SoftwareMessage Class Reference
The SoftwareMessage class represents a FIT SoftwareMessage data message.
Public Member Functions
SoftwareMessage ()
Constructs a SoftwareMessage object.
MessageIndex messageIndex () const
Returns the SoftwareMessage data message's messageIndex field's current value.
quint16 version () const
Returns the SoftwareMessage data message's version field's current value.
QString partNumber () const
Returns the SoftwareMessage data message's partNumber field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setVersion (const quint16 version)
Sets the version field to version.
void setPartNumber (const QString partNumber)
Sets the partNumber field to partNumber.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
SoftwareMessage (SoftwareMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The SoftwareMessage class represents a FIT SoftwareMessage data message.
See also
DataMessage
Definition at line 34 of file softwaremessage.h.
Constructor & Destructor Documentation
SoftwareMessage() [1/2]
SoftwareMessage::SoftwareMessage ()
Constructs a SoftwareMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file softwaremessage.cpp.
                                  : AbstractDataMessage(new SoftwareMessagePrivate(this))
 {
 }
SoftwareMessage() [2/2]
SoftwareMessage::SoftwareMessage (SoftwareMessagePrivate *const d) explicit protected
Constructs a SoftwareMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file softwaremessage.cpp.
                                                                  : AbstractDataMessage(d)
 {
 }
Member Function Documentation
messageIndex()
MessageIndex SoftwareMessage::messageIndex () const
Returns the SoftwareMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 69 of file softwaremessage.cpp.
 {
     Q_D(const SoftwareMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
partNumber()
QString SoftwareMessage::partNumber () const
Returns the SoftwareMessage data message's partNumber field's current value.
Returns
the partNumber field value.
Definition at line 91 of file softwaremessage.cpp.
 {
     Q_D(const SoftwareMessage);
     return d->partNumber;
 }
Referenced by setPartNumber().
setMessageIndex()
void SoftwareMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 102 of file softwaremessage.cpp.
 {
     Q_D(SoftwareMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setPartNumber()
void SoftwareMessage::setPartNumber (const QString partNumber)
Sets the partNumber field to partNumber.
Parameters
partNumber The field value to set.
Definition at line 122 of file softwaremessage.cpp.
 {
     Q_D(SoftwareMessage);
     d->partNumber = partNumber;
 }
References partNumber().
setVersion()
void SoftwareMessage::setVersion (const quint16 version)
Sets the version field to version.
Parameters
version The field value to set.
Definition at line 112 of file softwaremessage.cpp.
 {
     Q_D(SoftwareMessage);
     d->version = version;
 }
References version().
version()
quint16 SoftwareMessage::version () const
Returns the SoftwareMessage data message's version field's current value.
Returns
the version field value.
Definition at line 80 of file softwaremessage.cpp.
 {
     Q_D(const SoftwareMessage);
     return d->version;
 }
Referenced by setVersion().
The documentation for this class was generated from the following files:
softwaremessage.h
softwaremessage.cpp