QtFit: SegmentFileMessage Class Reference
SegmentFileMessage Class Reference
The SegmentFileMessage class represents a FIT SegmentFileMessage data message.
Public Member Functions
SegmentFileMessage ()
Constructs a SegmentFileMessage object.
MessageIndex messageIndex () const
Returns the SegmentFileMessage data message's messageIndex field's current value.
QString fileUuid () const
Returns the SegmentFileMessage data message's fileUuid field's current value.
bool enabled () const
Returns the SegmentFileMessage data message's enabled field's current value.
quint32 userProfilePrimaryKey () const
Returns the SegmentFileMessage data message's userProfilePrimaryKey field's current value.
SegmentLeaderboardType leaderType () const
Returns the SegmentFileMessage data message's leaderType field's current value.
quint32 leaderGroupPrimaryKey () const
Returns the SegmentFileMessage data message's leaderGroupPrimaryKey field's current value.
quint32 leaderActivityId () const
Returns the SegmentFileMessage data message's leaderActivityId field's current value.
QString leaderActivityIdString () const
Returns the SegmentFileMessage data message's leaderActivityIdString field's current value.
quint8 defaultRaceLeader () const
Returns the SegmentFileMessage data message's defaultRaceLeader field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setFileUuid (const QString fileUuid)
Sets the fileUuid field to fileUuid.
void setEnabled (const bool enabled)
Sets the enabled field to enabled.
void setUserProfilePrimaryKey (const quint32 userProfilePrimaryKey)
Sets the userProfilePrimaryKey field to userProfilePrimaryKey.
void setLeaderType (const SegmentLeaderboardType leaderType)
Sets the leaderType field to leaderType.
void setLeaderGroupPrimaryKey (const quint32 leaderGroupPrimaryKey)
Sets the leaderGroupPrimaryKey field to leaderGroupPrimaryKey.
void setLeaderActivityId (const quint32 leaderActivityId)
Sets the leaderActivityId field to leaderActivityId.
void setLeaderActivityIdString (const QString leaderActivityIdString)
Sets the leaderActivityIdString field to leaderActivityIdString.
void setDefaultRaceLeader (const quint8 defaultRaceLeader)
Sets the defaultRaceLeader field to defaultRaceLeader.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
SegmentFileMessage (SegmentFileMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The SegmentFileMessage class represents a FIT SegmentFileMessage data message.
See also
DataMessage
Definition at line 34 of file segmentfilemessage.h.
Constructor & Destructor Documentation
SegmentFileMessage() [1/2]
SegmentFileMessage::SegmentFileMessage ()
Constructs a SegmentFileMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file segmentfilemessage.cpp.
                                        : AbstractDataMessage(new SegmentFileMessagePrivate(this))
 {
 }
SegmentFileMessage() [2/2]
SegmentFileMessage::SegmentFileMessage (SegmentFileMessagePrivate *const d) explicit protected
Constructs a SegmentFileMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file segmentfilemessage.cpp.
                                                                           : AbstractDataMessage(d)
 {
 }
Member Function Documentation
defaultRaceLeader()
quint8 SegmentFileMessage::defaultRaceLeader () const
Returns the SegmentFileMessage data message's defaultRaceLeader field's current value.
Index for the Leader Board entry selected as the default race participant
Returns
the defaultRaceLeader field value.
Definition at line 174 of file segmentfilemessage.cpp.
 {
     Q_D(const SegmentFileMessage);
     return d->defaultRaceLeader;
 }
Referenced by setDefaultRaceLeader().
enabled()
bool SegmentFileMessage::enabled () const
Returns the SegmentFileMessage data message's enabled field's current value.
Enabled state of the segment file
Returns
the enabled field value.
Definition at line 95 of file segmentfilemessage.cpp.
 {
     Q_D(const SegmentFileMessage);
     return d->enabled;
 }
Referenced by setEnabled().
fileUuid()
QString SegmentFileMessage::fileUuid () const
Returns the SegmentFileMessage data message's fileUuid field's current value.
UUID of the segment file
Returns
the fileUuid field value.
Definition at line 82 of file segmentfilemessage.cpp.
 {
     Q_D(const SegmentFileMessage);
     return d->fileUuid;
 }
Referenced by setFileUuid().
leaderActivityId()
quint32 SegmentFileMessage::leaderActivityId () const
Returns the SegmentFileMessage data message's leaderActivityId field's current value.
Activity ID of each leader in the segment file
Returns
the leaderActivityId field value.
Definition at line 147 of file segmentfilemessage.cpp.
 {
     Q_D(const SegmentFileMessage);
     return d->leaderActivityId;
 }
Referenced by setLeaderActivityId().
leaderActivityIdString()
QString SegmentFileMessage::leaderActivityIdString () const
Returns the SegmentFileMessage data message's leaderActivityIdString field's current value.
String version of the activity ID of each leader in the segment file. 21 characters long for each ID, express in decimal
Returns
the leaderActivityIdString field value.
Definition at line 161 of file segmentfilemessage.cpp.
 {
     Q_D(const SegmentFileMessage);
     return d->leaderActivityIdString;
 }
Referenced by setLeaderActivityIdString().
leaderGroupPrimaryKey()
quint32 SegmentFileMessage::leaderGroupPrimaryKey () const
Returns the SegmentFileMessage data message's leaderGroupPrimaryKey field's current value.
Group primary key of each leader in the segment file
Returns
the leaderGroupPrimaryKey field value.
Definition at line 134 of file segmentfilemessage.cpp.
 {
     Q_D(const SegmentFileMessage);
     return d->leaderGroupPrimaryKey;
 }
Referenced by setLeaderGroupPrimaryKey().
leaderType()
SegmentLeaderboardType SegmentFileMessage::leaderType () const
Returns the SegmentFileMessage data message's leaderType field's current value.
Leader type of each leader in the segment file
Returns
the leaderType field value.
Definition at line 121 of file segmentfilemessage.cpp.
 {
     Q_D(const SegmentFileMessage);
     return d->leaderType;
 }
Referenced by setLeaderType().
messageIndex()
MessageIndex SegmentFileMessage::messageIndex () const
Returns the SegmentFileMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 69 of file segmentfilemessage.cpp.
 {
     Q_D(const SegmentFileMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
setDefaultRaceLeader()
void SegmentFileMessage::setDefaultRaceLeader (const quint8 defaultRaceLeader)
Sets the defaultRaceLeader field to defaultRaceLeader.
Parameters
defaultRaceLeader The field value to set.
Definition at line 265 of file segmentfilemessage.cpp.
 {
     Q_D(SegmentFileMessage);
     d->defaultRaceLeader = defaultRaceLeader;
 }
References defaultRaceLeader().
setEnabled()
void SegmentFileMessage::setEnabled (const bool enabled)
Sets the enabled field to enabled.
Parameters
enabled The field value to set.
Definition at line 205 of file segmentfilemessage.cpp.
 {
     Q_D(SegmentFileMessage);
     d->enabled = enabled;
 }
References enabled().
setFileUuid()
void SegmentFileMessage::setFileUuid (const QString fileUuid)
Sets the fileUuid field to fileUuid.
Parameters
fileUuid The field value to set.
Definition at line 195 of file segmentfilemessage.cpp.
 {
     Q_D(SegmentFileMessage);
     d->fileUuid = fileUuid;
 }
References fileUuid().
setLeaderActivityId()
void SegmentFileMessage::setLeaderActivityId (const quint32 leaderActivityId)
Sets the leaderActivityId field to leaderActivityId.
Parameters
leaderActivityId The field value to set.
Definition at line 245 of file segmentfilemessage.cpp.
 {
     Q_D(SegmentFileMessage);
     d->leaderActivityId = leaderActivityId;
 }
References leaderActivityId().
setLeaderActivityIdString()
void SegmentFileMessage::setLeaderActivityIdString (const QString leaderActivityIdString)
Sets the leaderActivityIdString field to leaderActivityIdString.
Parameters
leaderActivityIdString The field value to set.
Definition at line 255 of file segmentfilemessage.cpp.
 {
     Q_D(SegmentFileMessage);
     d->leaderActivityIdString = leaderActivityIdString;
 }
References leaderActivityIdString().
setLeaderGroupPrimaryKey()
void SegmentFileMessage::setLeaderGroupPrimaryKey (const quint32 leaderGroupPrimaryKey)
Sets the leaderGroupPrimaryKey field to leaderGroupPrimaryKey.
Parameters
leaderGroupPrimaryKey The field value to set.
Definition at line 235 of file segmentfilemessage.cpp.
 {
     Q_D(SegmentFileMessage);
     d->leaderGroupPrimaryKey = leaderGroupPrimaryKey;
 }
References leaderGroupPrimaryKey().
setLeaderType()
void SegmentFileMessage::setLeaderType (const SegmentLeaderboardType leaderType)
Sets the leaderType field to leaderType.
Parameters
leaderType The field value to set.
Definition at line 225 of file segmentfilemessage.cpp.
 {
     Q_D(SegmentFileMessage);
     d->leaderType = leaderType;
 }
References leaderType().
setMessageIndex()
void SegmentFileMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 185 of file segmentfilemessage.cpp.
 {
     Q_D(SegmentFileMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setUserProfilePrimaryKey()
void SegmentFileMessage::setUserProfilePrimaryKey (const quint32 userProfilePrimaryKey)
Sets the userProfilePrimaryKey field to userProfilePrimaryKey.
Parameters
userProfilePrimaryKey The field value to set.
Definition at line 215 of file segmentfilemessage.cpp.
 {
     Q_D(SegmentFileMessage);
     d->userProfilePrimaryKey = userProfilePrimaryKey;
 }
References userProfilePrimaryKey().
userProfilePrimaryKey()
quint32 SegmentFileMessage::userProfilePrimaryKey () const
Returns the SegmentFileMessage data message's userProfilePrimaryKey field's current value.
Primary key of the user that created the segment file
Returns
the userProfilePrimaryKey field value.
Definition at line 108 of file segmentfilemessage.cpp.
 {
     Q_D(const SegmentFileMessage);
     return d->userProfilePrimaryKey;
 }
Referenced by setUserProfilePrimaryKey().
The documentation for this class was generated from the following files:
segmentfilemessage.h
segmentfilemessage.cpp