QtFit: SetMessage Class Reference
SetMessage Class Reference
The SetMessage class represents a FIT SetMessage data message.
Public Member Functions
SetMessage ()
Constructs a SetMessage object.
DateTime timestamp () const
Returns the SetMessage data message's timestamp field's current value.
quint32 duration () const
Returns the SetMessage data message's duration field's current value.
quint16 repetitions () const
Returns the SetMessage data message's repetitions field's current value.
quint16 weight () const
Returns the SetMessage data message's weight field's current value.
SetType setType () const
Returns the SetMessage data message's setType field's current value.
DateTime startTime () const
Returns the SetMessage data message's startTime field's current value.
ExerciseCategory category () const
Returns the SetMessage data message's category field's current value.
quint16 categorySubtype () const
Returns the SetMessage data message's categorySubtype field's current value.
FitBaseUnit weightDisplayUnit () const
Returns the SetMessage data message's weightDisplayUnit field's current value.
MessageIndex messageIndex () const
Returns the SetMessage data message's messageIndex field's current value.
MessageIndex wktStepIndex () const
Returns the SetMessage data message's wktStepIndex field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setDuration (const quint32 duration)
Sets the duration field to duration.
void setRepetitions (const quint16 repetitions)
Sets the repetitions field to repetitions.
void setWeight (const quint16 weight)
Sets the weight field to weight.
void setSetType (const SetType setType)
Sets the setType field to setType.
void setStartTime (const DateTime startTime)
Sets the startTime field to startTime.
void setCategory (const ExerciseCategory category)
Sets the category field to category.
void setCategorySubtype (const quint16 categorySubtype)
Sets the categorySubtype field to categorySubtype.
void setWeightDisplayUnit (const FitBaseUnit weightDisplayUnit)
Sets the weightDisplayUnit field to weightDisplayUnit.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setWktStepIndex (const MessageIndex wktStepIndex)
Sets the wktStepIndex field to wktStepIndex.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
SetMessage (SetMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The SetMessage class represents a FIT SetMessage data message.
See also
DataMessage
Definition at line 39 of file setmessage.h.
Constructor & Destructor Documentation
SetMessage() [1/2]
SetMessage::SetMessage ()
Constructs a SetMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file setmessage.cpp.
                        : AbstractDataMessage(new SetMessagePrivate(this))
 {
 }
SetMessage() [2/2]
SetMessage::SetMessage (SetMessagePrivate *const d) explicit protected
Constructs a SetMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file setmessage.cpp.
                                                   : AbstractDataMessage(d)
 {
 }
Member Function Documentation
category()
ExerciseCategory SetMessage::category () const
Returns the SetMessage data message's category field's current value.
Returns
the category field value.
Definition at line 148 of file setmessage.cpp.
 {
     Q_D(const SetMessage);
     return d->category;
 }
Referenced by setCategory().
categorySubtype()
quint16 SetMessage::categorySubtype () const
Returns the SetMessage data message's categorySubtype field's current value.
Based on the associated category, see [category]_exercise_names
Returns
the categorySubtype field value.
Definition at line 161 of file setmessage.cpp.
 {
     Q_D(const SetMessage);
     return d->categorySubtype;
 }
Referenced by setCategorySubtype().
duration()
quint32 SetMessage::duration () const
Returns the SetMessage data message's duration field's current value.
Returns
the duration field value.
Definition at line 87 of file setmessage.cpp.
 {
     Q_D(const SetMessage);
     return d->duration;
 }
Referenced by setDuration().
messageIndex()
MessageIndex SetMessage::messageIndex () const
Returns the SetMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 183 of file setmessage.cpp.
 {
     Q_D(const SetMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
repetitions()
quint16 SetMessage::repetitions () const
Returns the SetMessage data message's repetitions field's current value.
of repitions of the movement
Returns
the repetitions field value.
Definition at line 100 of file setmessage.cpp.
 {
     Q_D(const SetMessage);
     return d->repetitions;
 }
Referenced by setRepetitions().
setCategory()
void SetMessage::setCategory (const ExerciseCategory category)
Sets the category field to category.
Parameters
category The field value to set.
Definition at line 265 of file setmessage.cpp.
 {
     Q_D(SetMessage);
     d->category = category;
 }
References category().
setCategorySubtype()
void SetMessage::setCategorySubtype (const quint16 categorySubtype)
Sets the categorySubtype field to categorySubtype.
Parameters
categorySubtype The field value to set.
Definition at line 275 of file setmessage.cpp.
 {
     Q_D(SetMessage);
     d->categorySubtype = categorySubtype;
 }
References categorySubtype().
setDuration()
void SetMessage::setDuration (const quint32 duration)
Sets the duration field to duration.
Parameters
duration The field value to set.
Definition at line 215 of file setmessage.cpp.
 {
     Q_D(SetMessage);
     d->duration = duration;
 }
References duration().
setMessageIndex()
void SetMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 295 of file setmessage.cpp.
 {
     Q_D(SetMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setRepetitions()
void SetMessage::setRepetitions (const quint16 repetitions)
Sets the repetitions field to repetitions.
Parameters
repetitions The field value to set.
Definition at line 225 of file setmessage.cpp.
 {
     Q_D(SetMessage);
     d->repetitions = repetitions;
 }
References repetitions().
setSetType()
void SetMessage::setSetType (const SetType setType)
Sets the setType field to setType.
Parameters
setType The field value to set.
Definition at line 245 of file setmessage.cpp.
 {
     Q_D(SetMessage);
     d->setType = setType;
 }
References setType().
setStartTime()
void SetMessage::setStartTime (const DateTime startTime)
Sets the startTime field to startTime.
Parameters
startTime The field value to set.
Definition at line 255 of file setmessage.cpp.
 {
     Q_D(SetMessage);
     d->startTime = startTime;
 }
References startTime().
setTimestamp()
void SetMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 205 of file setmessage.cpp.
 {
     Q_D(SetMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setType()
SetType SetMessage::setType () const
Returns the SetMessage data message's setType field's current value.
Returns
the setType field value.
Definition at line 124 of file setmessage.cpp.
 {
     Q_D(const SetMessage);
     return d->setType;
 }
Referenced by setSetType().
setWeight()
void SetMessage::setWeight (const quint16 weight)
Sets the weight field to weight.
Parameters
weight The field value to set.
Definition at line 235 of file setmessage.cpp.
 {
     Q_D(SetMessage);
     d->weight = weight;
 }
References weight().
setWeightDisplayUnit()
void SetMessage::setWeightDisplayUnit (const FitBaseUnit weightDisplayUnit)
Sets the weightDisplayUnit field to weightDisplayUnit.
Parameters
weightDisplayUnit The field value to set.
Definition at line 285 of file setmessage.cpp.
 {
     Q_D(SetMessage);
     d->weightDisplayUnit = weightDisplayUnit;
 }
References weightDisplayUnit().
setWktStepIndex()
void SetMessage::setWktStepIndex (const MessageIndex wktStepIndex)
Sets the wktStepIndex field to wktStepIndex.
Parameters
wktStepIndex The field value to set.
Definition at line 305 of file setmessage.cpp.
 {
     Q_D(SetMessage);
     d->wktStepIndex = wktStepIndex;
 }
References wktStepIndex().
startTime()
DateTime SetMessage::startTime () const
Returns the SetMessage data message's startTime field's current value.
Start time of the set
Returns
the startTime field value.
Definition at line 137 of file setmessage.cpp.
 {
     Q_D(const SetMessage);
     return d->startTime;
 }
Referenced by setStartTime().
timestamp()
DateTime SetMessage::timestamp () const
Returns the SetMessage data message's timestamp field's current value.
Timestamp of the set
Returns
the timestamp field value.
Definition at line 76 of file setmessage.cpp.
 {
     Q_D(const SetMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
weight()
quint16 SetMessage::weight () const
Returns the SetMessage data message's weight field's current value.
Amount of weight applied for the set
Returns
the weight field value.
Definition at line 113 of file setmessage.cpp.
 {
     Q_D(const SetMessage);
     return d->weight;
 }
Referenced by setWeight().
weightDisplayUnit()
FitBaseUnit SetMessage::weightDisplayUnit () const
Returns the SetMessage data message's weightDisplayUnit field's current value.
Returns
the weightDisplayUnit field value.
Definition at line 172 of file setmessage.cpp.
 {
     Q_D(const SetMessage);
     return d->weightDisplayUnit;
 }
Referenced by setWeightDisplayUnit().
wktStepIndex()
MessageIndex SetMessage::wktStepIndex () const
Returns the SetMessage data message's wktStepIndex field's current value.
Returns
the wktStepIndex field value.
Definition at line 194 of file setmessage.cpp.
 {
     Q_D(const SetMessage);
     return d->wktStepIndex;
 }
Referenced by setWktStepIndex().
The documentation for this class was generated from the following files:
setmessage.h
setmessage.cpp