QtFit: HrZoneMessage Class Reference
HrZoneMessage Class Reference
The HrZoneMessage class represents a FIT HrZoneMessage data message.
Public Member Functions
HrZoneMessage ()
Constructs a HrZoneMessage object.
MessageIndex messageIndex () const
Returns the HrZoneMessage data message's messageIndex field's current value.
quint8 highBpm () const
Returns the HrZoneMessage data message's highBpm field's current value.
QString name () const
Returns the HrZoneMessage data message's name field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setHighBpm (const quint8 highBpm)
Sets the highBpm field to highBpm.
void setName (const QString name)
Sets the name field to name.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
HrZoneMessage (HrZoneMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The HrZoneMessage class represents a FIT HrZoneMessage data message.
See also
DataMessage
Definition at line 39 of file hrzonemessage.h.
Constructor & Destructor Documentation
HrZoneMessage() [1/2]
HrZoneMessage::HrZoneMessage ()
Constructs a HrZoneMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file hrzonemessage.cpp.
                              : AbstractDataMessage(new HrZoneMessagePrivate(this))
 {
 }
HrZoneMessage() [2/2]
HrZoneMessage::HrZoneMessage (HrZoneMessagePrivate *const d) explicit protected
Constructs a HrZoneMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file hrzonemessage.cpp.
                                                            : AbstractDataMessage(d)
 {
 }
Member Function Documentation
highBpm()
quint8 HrZoneMessage::highBpm () const
Returns the HrZoneMessage data message's highBpm field's current value.
Returns
the highBpm field value.
Definition at line 85 of file hrzonemessage.cpp.
 {
     Q_D(const HrZoneMessage);
     return d->highBpm;
 }
Referenced by setHighBpm().
messageIndex()
MessageIndex HrZoneMessage::messageIndex () const
Returns the HrZoneMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 74 of file hrzonemessage.cpp.
 {
     Q_D(const HrZoneMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
name()
QString HrZoneMessage::name () const
Returns the HrZoneMessage data message's name field's current value.
Returns
the name field value.
Definition at line 96 of file hrzonemessage.cpp.
 {
     Q_D(const HrZoneMessage);
     return d->name;
 }
Referenced by setName().
setHighBpm()
void HrZoneMessage::setHighBpm (const quint8 highBpm)
Sets the highBpm field to highBpm.
Parameters
highBpm The field value to set.
Definition at line 117 of file hrzonemessage.cpp.
 {
     Q_D(HrZoneMessage);
     d->highBpm = highBpm;
 }
References highBpm().
setMessageIndex()
void HrZoneMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 107 of file hrzonemessage.cpp.
 {
     Q_D(HrZoneMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setName()
void HrZoneMessage::setName (const QString name)
Sets the name field to name.
Parameters
name The field value to set.
Definition at line 127 of file hrzonemessage.cpp.
 {
     Q_D(HrZoneMessage);
     d->name = name;
 }
References name().
The documentation for this class was generated from the following files:
hrzonemessage.h
hrzonemessage.cpp