QtFit: ZonesTargetMessage Class Reference
ZonesTargetMessage Class Reference
The ZonesTargetMessage class represents a FIT ZonesTargetMessage data message.
Public Member Functions
ZonesTargetMessage ()
Constructs a ZonesTargetMessage object.
quint8 maxHeartRate () const
Returns the ZonesTargetMessage data message's maxHeartRate field's current value.
quint8 thresholdHeartRate () const
Returns the ZonesTargetMessage data message's thresholdHeartRate field's current value.
quint16 functionalThresholdPower () const
Returns the ZonesTargetMessage data message's functionalThresholdPower field's current value.
HrZoneCalc hrCalcType () const
Returns the ZonesTargetMessage data message's hrCalcType field's current value.
PwrZoneCalc pwrCalcType () const
Returns the ZonesTargetMessage data message's pwrCalcType field's current value.
void setMaxHeartRate (const quint8 maxHeartRate)
Sets the maxHeartRate field to maxHeartRate.
void setThresholdHeartRate (const quint8 thresholdHeartRate)
Sets the thresholdHeartRate field to thresholdHeartRate.
void setFunctionalThresholdPower (const quint16 functionalThresholdPower)
Sets the functionalThresholdPower field to functionalThresholdPower.
void setHrCalcType (const HrZoneCalc hrCalcType)
Sets the hrCalcType field to hrCalcType.
void setPwrCalcType (const PwrZoneCalc pwrCalcType)
Sets the pwrCalcType field to pwrCalcType.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
ZonesTargetMessage (ZonesTargetMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The ZonesTargetMessage class represents a FIT ZonesTargetMessage data message.
See also
DataMessage
Definition at line 39 of file zonestargetmessage.h.
Constructor & Destructor Documentation
ZonesTargetMessage() [1/2]
ZonesTargetMessage::ZonesTargetMessage ()
Constructs a ZonesTargetMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file zonestargetmessage.cpp.
                                        : AbstractDataMessage(new ZonesTargetMessagePrivate(this))
 {
 }
ZonesTargetMessage() [2/2]
ZonesTargetMessage::ZonesTargetMessage (ZonesTargetMessagePrivate *const d) explicit protected
Constructs a ZonesTargetMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file zonestargetmessage.cpp.
                                                                           : AbstractDataMessage(d)
 {
 }
Member Function Documentation
functionalThresholdPower()
quint16 ZonesTargetMessage::functionalThresholdPower () const
Returns the ZonesTargetMessage data message's functionalThresholdPower field's current value.
Returns
the functionalThresholdPower field value.
Definition at line 96 of file zonestargetmessage.cpp.
 {
     Q_D(const ZonesTargetMessage);
     return d->functionalThresholdPower;
 }
Referenced by setFunctionalThresholdPower().
hrCalcType()
HrZoneCalc ZonesTargetMessage::hrCalcType () const
Returns the ZonesTargetMessage data message's hrCalcType field's current value.
Returns
the hrCalcType field value.
Definition at line 107 of file zonestargetmessage.cpp.
 {
     Q_D(const ZonesTargetMessage);
     return d->hrCalcType;
 }
Referenced by setHrCalcType().
maxHeartRate()
quint8 ZonesTargetMessage::maxHeartRate () const
Returns the ZonesTargetMessage data message's maxHeartRate field's current value.
Returns
the maxHeartRate field value.
Definition at line 74 of file zonestargetmessage.cpp.
 {
     Q_D(const ZonesTargetMessage);
     return d->maxHeartRate;
 }
Referenced by setMaxHeartRate().
pwrCalcType()
PwrZoneCalc ZonesTargetMessage::pwrCalcType () const
Returns the ZonesTargetMessage data message's pwrCalcType field's current value.
Returns
the pwrCalcType field value.
Definition at line 118 of file zonestargetmessage.cpp.
 {
     Q_D(const ZonesTargetMessage);
     return d->pwrCalcType;
 }
Referenced by setPwrCalcType().
setFunctionalThresholdPower()
void ZonesTargetMessage::setFunctionalThresholdPower (const quint16 functionalThresholdPower)
Sets the functionalThresholdPower field to functionalThresholdPower.
Parameters
functionalThresholdPower The field value to set.
Definition at line 149 of file zonestargetmessage.cpp.
 {
     Q_D(ZonesTargetMessage);
     d->functionalThresholdPower = functionalThresholdPower;
 }
References functionalThresholdPower().
setHrCalcType()
void ZonesTargetMessage::setHrCalcType (const HrZoneCalc hrCalcType)
Sets the hrCalcType field to hrCalcType.
Parameters
hrCalcType The field value to set.
Definition at line 159 of file zonestargetmessage.cpp.
 {
     Q_D(ZonesTargetMessage);
     d->hrCalcType = hrCalcType;
 }
References hrCalcType().
setMaxHeartRate()
void ZonesTargetMessage::setMaxHeartRate (const quint8 maxHeartRate)
Sets the maxHeartRate field to maxHeartRate.
Parameters
maxHeartRate The field value to set.
Definition at line 129 of file zonestargetmessage.cpp.
 {
     Q_D(ZonesTargetMessage);
     d->maxHeartRate = maxHeartRate;
 }
References maxHeartRate().
setPwrCalcType()
void ZonesTargetMessage::setPwrCalcType (const PwrZoneCalc pwrCalcType)
Sets the pwrCalcType field to pwrCalcType.
Parameters
pwrCalcType The field value to set.
Definition at line 169 of file zonestargetmessage.cpp.
 {
     Q_D(ZonesTargetMessage);
     d->pwrCalcType = pwrCalcType;
 }
References pwrCalcType().
setThresholdHeartRate()
void ZonesTargetMessage::setThresholdHeartRate (const quint8 thresholdHeartRate)
Sets the thresholdHeartRate field to thresholdHeartRate.
Parameters
thresholdHeartRate The field value to set.
Definition at line 139 of file zonestargetmessage.cpp.
 {
     Q_D(ZonesTargetMessage);
     d->thresholdHeartRate = thresholdHeartRate;
 }
References thresholdHeartRate().
thresholdHeartRate()
quint8 ZonesTargetMessage::thresholdHeartRate () const
Returns the ZonesTargetMessage data message's thresholdHeartRate field's current value.
Returns
the thresholdHeartRate field value.
Definition at line 85 of file zonestargetmessage.cpp.
 {
     Q_D(const ZonesTargetMessage);
     return d->thresholdHeartRate;
 }
Referenced by setThresholdHeartRate().
The documentation for this class was generated from the following files:
zonestargetmessage.h
zonestargetmessage.cpp