QtFit: ExdScreenConfigurationMessage Class Reference
ExdScreenConfigurationMessage Class Reference
#include <exdscreenconfigurationmessage.h>
Public Member Functions
ExdScreenConfigurationMessage ()
~ExdScreenConfigurationMessage ()
quint8 screenIndex () const
quint8 fieldCount () const
ExdLayout layout () const
bool screenEnabled () const
void setScreenIndex (const quint8 screenIndex)
void setFieldCount (const quint8 fieldCount)
void setLayout (const ExdLayout layout)
void setScreenEnabled (const bool screenEnabled)
Public Member Functions inherited from FitDataMessage
FitDataMessage ()
FitDataMessage (const FitDataMessage &other)
FitDataMessage & operator= (const FitDataMessage &other)
~FitDataMessage ()
MesgNum globalMessageNumber () const
bool isNull () const
Additional Inherited Members
Static Public Member Functions inherited from FitDataMessage
static FitDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Detailed Description
Definition at line 34 of file exdscreenconfigurationmessage.h.
Constructor & Destructor Documentation
ExdScreenConfigurationMessage()
QTFIT_BEGIN_NAMESPACE ExdScreenConfigurationMessage::ExdScreenConfigurationMessage ()
Definition at line 30 of file exdscreenconfigurationmessage.cpp.
                                                              : FitDataMessage(new ExdScreenConfigurationMessagePrivate(this))
 {
 }
~ExdScreenConfigurationMessage()
ExdScreenConfigurationMessage::~ExdScreenConfigurationMessage ()
Member Function Documentation
fieldCount()
quint8 ExdScreenConfigurationMessage::fieldCount () const
Definition at line 41 of file exdscreenconfigurationmessage.cpp.
 {
     Q_D(const ExdScreenConfigurationMessage);
     return d->fieldCount;
 }
Referenced by setFieldCount().
layout()
ExdLayout ExdScreenConfigurationMessage::layout () const
Definition at line 47 of file exdscreenconfigurationmessage.cpp.
 {
     Q_D(const ExdScreenConfigurationMessage);
     return d->layout;
 }
Referenced by setLayout().
screenEnabled()
bool ExdScreenConfigurationMessage::screenEnabled () const
Definition at line 53 of file exdscreenconfigurationmessage.cpp.
 {
     Q_D(const ExdScreenConfigurationMessage);
     return d->screenEnabled;
 }
Referenced by setScreenEnabled().
screenIndex()
quint8 ExdScreenConfigurationMessage::screenIndex () const
Definition at line 35 of file exdscreenconfigurationmessage.cpp.
 {
     Q_D(const ExdScreenConfigurationMessage);
     return d->screenIndex;
 }
Referenced by setScreenIndex().
setFieldCount()
void ExdScreenConfigurationMessage::setFieldCount (const quint8 fieldCount)
Definition at line 64 of file exdscreenconfigurationmessage.cpp.
 {
     Q_D(ExdScreenConfigurationMessage);
     d->fieldCount = fieldCount;
 }
References fieldCount().
setLayout()
void ExdScreenConfigurationMessage::setLayout (const ExdLayout layout)
Definition at line 69 of file exdscreenconfigurationmessage.cpp.
 {
     Q_D(ExdScreenConfigurationMessage);
     d->layout = layout;
 }
References layout().
setScreenEnabled()
void ExdScreenConfigurationMessage::setScreenEnabled (const bool screenEnabled)
Definition at line 74 of file exdscreenconfigurationmessage.cpp.
 {
     Q_D(ExdScreenConfigurationMessage);
     d->screenEnabled = screenEnabled;
 }
References screenEnabled().
setScreenIndex()
void ExdScreenConfigurationMessage::setScreenIndex (const quint8 screenIndex)
Definition at line 59 of file exdscreenconfigurationmessage.cpp.
 {
     Q_D(ExdScreenConfigurationMessage);
     d->screenIndex = screenIndex;
 }
References screenIndex().
The documentation for this class was generated from the following files:
exdscreenconfigurationmessage.h
exdscreenconfigurationmessage.cpp