QtFit: VideoClipMessage Class Reference
VideoClipMessage Class Reference
The VideoClipMessage class represents a FIT VideoClipMessage data message.
Public Member Functions
VideoClipMessage ()
Constructs a VideoClipMessage object.
quint16 clipNumber () const
Returns the VideoClipMessage data message's clipNumber field's current value.
DateTime startTimestamp () const
Returns the VideoClipMessage data message's startTimestamp field's current value.
quint16 startTimestampMs () const
Returns the VideoClipMessage data message's startTimestampMs field's current value.
DateTime endTimestamp () const
Returns the VideoClipMessage data message's endTimestamp field's current value.
quint16 endTimestampMs () const
Returns the VideoClipMessage data message's endTimestampMs field's current value.
quint32 clipStart () const
Returns the VideoClipMessage data message's clipStart field's current value.
quint32 clipEnd () const
Returns the VideoClipMessage data message's clipEnd field's current value.
void setClipNumber (const quint16 clipNumber)
Sets the clipNumber field to clipNumber.
void setStartTimestamp (const DateTime startTimestamp)
Sets the startTimestamp field to startTimestamp.
void setStartTimestampMs (const quint16 startTimestampMs)
Sets the startTimestampMs field to startTimestampMs.
void setEndTimestamp (const DateTime endTimestamp)
Sets the endTimestamp field to endTimestamp.
void setEndTimestampMs (const quint16 endTimestampMs)
Sets the endTimestampMs field to endTimestampMs.
void setClipStart (const quint32 clipStart)
Sets the clipStart field to clipStart.
void setClipEnd (const quint32 clipEnd)
Sets the clipEnd field to clipEnd.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
VideoClipMessage (VideoClipMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The VideoClipMessage class represents a FIT VideoClipMessage data message.
See also
DataMessage
Definition at line 34 of file videoclipmessage.h.
Constructor & Destructor Documentation
VideoClipMessage() [1/2]
VideoClipMessage::VideoClipMessage ()
Constructs a VideoClipMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file videoclipmessage.cpp.
                                    : AbstractDataMessage(new VideoClipMessagePrivate(this))
 {
 }
VideoClipMessage() [2/2]
VideoClipMessage::VideoClipMessage (VideoClipMessagePrivate *const d) explicit protected
Constructs a VideoClipMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file videoclipmessage.cpp.
                                                                     : AbstractDataMessage(d)
 {
 }
Member Function Documentation
clipEnd()
quint32 VideoClipMessage::clipEnd () const
Returns the VideoClipMessage data message's clipEnd field's current value.
End of clip in video time
Returns
the clipEnd field value.
Definition at line 139 of file videoclipmessage.cpp.
 {
     Q_D(const VideoClipMessage);
     return d->clipEnd;
 }
Referenced by setClipEnd().
clipNumber()
quint16 VideoClipMessage::clipNumber () const
Returns the VideoClipMessage data message's clipNumber field's current value.
Returns
the clipNumber field value.
Definition at line 69 of file videoclipmessage.cpp.
 {
     Q_D(const VideoClipMessage);
     return d->clipNumber;
 }
Referenced by setClipNumber().
clipStart()
quint32 VideoClipMessage::clipStart () const
Returns the VideoClipMessage data message's clipStart field's current value.
Start of clip in video time
Returns
the clipStart field value.
Definition at line 126 of file videoclipmessage.cpp.
 {
     Q_D(const VideoClipMessage);
     return d->clipStart;
 }
Referenced by setClipStart().
endTimestamp()
DateTime VideoClipMessage::endTimestamp () const
Returns the VideoClipMessage data message's endTimestamp field's current value.
Returns
the endTimestamp field value.
Definition at line 102 of file videoclipmessage.cpp.
 {
     Q_D(const VideoClipMessage);
     return d->endTimestamp;
 }
Referenced by setEndTimestamp().
endTimestampMs()
quint16 VideoClipMessage::endTimestampMs () const
Returns the VideoClipMessage data message's endTimestampMs field's current value.
Returns
the endTimestampMs field value.
Definition at line 113 of file videoclipmessage.cpp.
 {
     Q_D(const VideoClipMessage);
     return d->endTimestampMs;
 }
Referenced by setEndTimestampMs().
setClipEnd()
void VideoClipMessage::setClipEnd (const quint32 clipEnd)
Sets the clipEnd field to clipEnd.
Parameters
clipEnd The field value to set.
Definition at line 210 of file videoclipmessage.cpp.
 {
     Q_D(VideoClipMessage);
     d->clipEnd = clipEnd;
 }
References clipEnd().
setClipNumber()
void VideoClipMessage::setClipNumber (const quint16 clipNumber)
Sets the clipNumber field to clipNumber.
Parameters
clipNumber The field value to set.
Definition at line 150 of file videoclipmessage.cpp.
 {
     Q_D(VideoClipMessage);
     d->clipNumber = clipNumber;
 }
References clipNumber().
setClipStart()
void VideoClipMessage::setClipStart (const quint32 clipStart)
Sets the clipStart field to clipStart.
Parameters
clipStart The field value to set.
Definition at line 200 of file videoclipmessage.cpp.
 {
     Q_D(VideoClipMessage);
     d->clipStart = clipStart;
 }
References clipStart().
setEndTimestamp()
void VideoClipMessage::setEndTimestamp (const DateTime endTimestamp)
Sets the endTimestamp field to endTimestamp.
Parameters
endTimestamp The field value to set.
Definition at line 180 of file videoclipmessage.cpp.
 {
     Q_D(VideoClipMessage);
     d->endTimestamp = endTimestamp;
 }
References endTimestamp().
setEndTimestampMs()
void VideoClipMessage::setEndTimestampMs (const quint16 endTimestampMs)
Sets the endTimestampMs field to endTimestampMs.
Parameters
endTimestampMs The field value to set.
Definition at line 190 of file videoclipmessage.cpp.
 {
     Q_D(VideoClipMessage);
     d->endTimestampMs = endTimestampMs;
 }
References endTimestampMs().
setStartTimestamp()
void VideoClipMessage::setStartTimestamp (const DateTime startTimestamp)
Sets the startTimestamp field to startTimestamp.
Parameters
startTimestamp The field value to set.
Definition at line 160 of file videoclipmessage.cpp.
 {
     Q_D(VideoClipMessage);
     d->startTimestamp = startTimestamp;
 }
References startTimestamp().
setStartTimestampMs()
void VideoClipMessage::setStartTimestampMs (const quint16 startTimestampMs)
Sets the startTimestampMs field to startTimestampMs.
Parameters
startTimestampMs The field value to set.
Definition at line 170 of file videoclipmessage.cpp.
 {
     Q_D(VideoClipMessage);
     d->startTimestampMs = startTimestampMs;
 }
References startTimestampMs().
startTimestamp()
DateTime VideoClipMessage::startTimestamp () const
Returns the VideoClipMessage data message's startTimestamp field's current value.
Returns
the startTimestamp field value.
Definition at line 80 of file videoclipmessage.cpp.
 {
     Q_D(const VideoClipMessage);
     return d->startTimestamp;
 }
Referenced by setStartTimestamp().
startTimestampMs()
quint16 VideoClipMessage::startTimestampMs () const
Returns the VideoClipMessage data message's startTimestampMs field's current value.
Returns
the startTimestampMs field value.
Definition at line 91 of file videoclipmessage.cpp.
 {
     Q_D(const VideoClipMessage);
     return d->startTimestampMs;
 }
Referenced by setStartTimestampMs().
The documentation for this class was generated from the following files:
videoclipmessage.h
videoclipmessage.cpp