QtFit: ExdDataConceptConfigurationMessage Class Reference
ExdDataConceptConfigurationMessage Class Reference
The ExdDataConceptConfigurationMessage class represents a FIT ExdDataConceptConfigurationMessage data message.
Public Member Functions
ExdDataConceptConfigurationMessage ()
Constructs a ExdDataConceptConfigurationMessage object.
quint8 screenIndex () const
Returns the ExdDataConceptConfigurationMessage data message's screenIndex field's current value.
quint8 conceptField () const
Returns the ExdDataConceptConfigurationMessage data message's conceptField field's current value.
quint8 fieldId () const
Returns the ExdDataConceptConfigurationMessage data message's fieldId field's current value.
quint8 conceptIndex () const
Returns the ExdDataConceptConfigurationMessage data message's conceptIndex field's current value.
quint8 dataPage () const
Returns the ExdDataConceptConfigurationMessage data message's dataPage field's current value.
quint8 conceptKey () const
Returns the ExdDataConceptConfigurationMessage data message's conceptKey field's current value.
quint8 scaling () const
Returns the ExdDataConceptConfigurationMessage data message's scaling field's current value.
ExdDataUnits dataUnits () const
Returns the ExdDataConceptConfigurationMessage data message's dataUnits field's current value.
ExdQualifiers qualifier () const
Returns the ExdDataConceptConfigurationMessage data message's qualifier field's current value.
ExdDescriptors descriptor () const
Returns the ExdDataConceptConfigurationMessage data message's descriptor field's current value.
bool isSigned () const
Returns the ExdDataConceptConfigurationMessage data message's isSigned field's current value.
void setScreenIndex (const quint8 screenIndex)
Sets the screenIndex field to screenIndex.
void setConceptField (const quint8 conceptField)
Sets the conceptField field to conceptField.
void setFieldId (const quint8 fieldId)
Sets the fieldId field to fieldId.
void setConceptIndex (const quint8 conceptIndex)
Sets the conceptIndex field to conceptIndex.
void setDataPage (const quint8 dataPage)
Sets the dataPage field to dataPage.
void setConceptKey (const quint8 conceptKey)
Sets the conceptKey field to conceptKey.
void setScaling (const quint8 scaling)
Sets the scaling field to scaling.
void setDataUnits (const ExdDataUnits dataUnits)
Sets the dataUnits field to dataUnits.
void setQualifier (const ExdQualifiers qualifier)
Sets the qualifier field to qualifier.
void setDescriptor (const ExdDescriptors descriptor)
Sets the descriptor field to descriptor.
void setIsSigned (const bool isSigned)
Sets the isSigned field to isSigned.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
ExdDataConceptConfigurationMessage (ExdDataConceptConfigurationMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The ExdDataConceptConfigurationMessage class represents a FIT ExdDataConceptConfigurationMessage data message.
See also
DataMessage
Definition at line 39 of file exddataconceptconfigurationmessage.h.
Constructor & Destructor Documentation
ExdDataConceptConfigurationMessage() [1/2]
ExdDataConceptConfigurationMessage::ExdDataConceptConfigurationMessage ()
Constructs a ExdDataConceptConfigurationMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file exddataconceptconfigurationmessage.cpp.
                                                                        : AbstractDataMessage(new ExdDataConceptConfigurationMessagePrivate(this))
 {
 }
ExdDataConceptConfigurationMessage() [2/2]
ExdDataConceptConfigurationMessage::ExdDataConceptConfigurationMessage (ExdDataConceptConfigurationMessagePrivate *const d) explicit protected
Constructs a ExdDataConceptConfigurationMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file exddataconceptconfigurationmessage.cpp.
                                                                                                                           : AbstractDataMessage(d)
 {
 }
Member Function Documentation
conceptField()
quint8 ExdDataConceptConfigurationMessage::conceptField () const
Returns the ExdDataConceptConfigurationMessage data message's conceptField field's current value.
Returns
the conceptField field value.
Definition at line 85 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(const ExdDataConceptConfigurationMessage);
     return d->conceptField;
 }
Referenced by setConceptField().
conceptIndex()
quint8 ExdDataConceptConfigurationMessage::conceptIndex () const
Returns the ExdDataConceptConfigurationMessage data message's conceptIndex field's current value.
Returns
the conceptIndex field value.
Definition at line 107 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(const ExdDataConceptConfigurationMessage);
     return d->conceptIndex;
 }
Referenced by setConceptIndex().
conceptKey()
quint8 ExdDataConceptConfigurationMessage::conceptKey () const
Returns the ExdDataConceptConfigurationMessage data message's conceptKey field's current value.
Returns
the conceptKey field value.
Definition at line 129 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(const ExdDataConceptConfigurationMessage);
     return d->conceptKey;
 }
Referenced by setConceptKey().
dataPage()
quint8 ExdDataConceptConfigurationMessage::dataPage () const
Returns the ExdDataConceptConfigurationMessage data message's dataPage field's current value.
Returns
the dataPage field value.
Definition at line 118 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(const ExdDataConceptConfigurationMessage);
     return d->dataPage;
 }
Referenced by setDataPage().
dataUnits()
ExdDataUnits ExdDataConceptConfigurationMessage::dataUnits () const
Returns the ExdDataConceptConfigurationMessage data message's dataUnits field's current value.
Returns
the dataUnits field value.
Definition at line 151 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(const ExdDataConceptConfigurationMessage);
     return d->dataUnits;
 }
Referenced by setDataUnits().
descriptor()
ExdDescriptors ExdDataConceptConfigurationMessage::descriptor () const
Returns the ExdDataConceptConfigurationMessage data message's descriptor field's current value.
Returns
the descriptor field value.
Definition at line 173 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(const ExdDataConceptConfigurationMessage);
     return d->descriptor;
 }
Referenced by setDescriptor().
fieldId()
quint8 ExdDataConceptConfigurationMessage::fieldId () const
Returns the ExdDataConceptConfigurationMessage data message's fieldId field's current value.
Returns
the fieldId field value.
Definition at line 96 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(const ExdDataConceptConfigurationMessage);
     return d->fieldId;
 }
Referenced by setFieldId().
isSigned()
bool ExdDataConceptConfigurationMessage::isSigned () const
Returns the ExdDataConceptConfigurationMessage data message's isSigned field's current value.
Returns
the isSigned field value.
Definition at line 184 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(const ExdDataConceptConfigurationMessage);
     return d->isSigned;
 }
Referenced by setIsSigned().
qualifier()
ExdQualifiers ExdDataConceptConfigurationMessage::qualifier () const
Returns the ExdDataConceptConfigurationMessage data message's qualifier field's current value.
Returns
the qualifier field value.
Definition at line 162 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(const ExdDataConceptConfigurationMessage);
     return d->qualifier;
 }
Referenced by setQualifier().
scaling()
quint8 ExdDataConceptConfigurationMessage::scaling () const
Returns the ExdDataConceptConfigurationMessage data message's scaling field's current value.
Returns
the scaling field value.
Definition at line 140 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(const ExdDataConceptConfigurationMessage);
     return d->scaling;
 }
Referenced by setScaling().
screenIndex()
quint8 ExdDataConceptConfigurationMessage::screenIndex () const
Returns the ExdDataConceptConfigurationMessage data message's screenIndex field's current value.
Returns
the screenIndex field value.
Definition at line 74 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(const ExdDataConceptConfigurationMessage);
     return d->screenIndex;
 }
Referenced by setScreenIndex().
setConceptField()
void ExdDataConceptConfigurationMessage::setConceptField (const quint8 conceptField)
Sets the conceptField field to conceptField.
Parameters
conceptField The field value to set.
Definition at line 205 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(ExdDataConceptConfigurationMessage);
     d->conceptField = conceptField;
 }
References conceptField().
setConceptIndex()
void ExdDataConceptConfigurationMessage::setConceptIndex (const quint8 conceptIndex)
Sets the conceptIndex field to conceptIndex.
Parameters
conceptIndex The field value to set.
Definition at line 225 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(ExdDataConceptConfigurationMessage);
     d->conceptIndex = conceptIndex;
 }
References conceptIndex().
setConceptKey()
void ExdDataConceptConfigurationMessage::setConceptKey (const quint8 conceptKey)
Sets the conceptKey field to conceptKey.
Parameters
conceptKey The field value to set.
Definition at line 245 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(ExdDataConceptConfigurationMessage);
     d->conceptKey = conceptKey;
 }
References conceptKey().
setDataPage()
void ExdDataConceptConfigurationMessage::setDataPage (const quint8 dataPage)
Sets the dataPage field to dataPage.
Parameters
dataPage The field value to set.
Definition at line 235 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(ExdDataConceptConfigurationMessage);
     d->dataPage = dataPage;
 }
References dataPage().
setDataUnits()
void ExdDataConceptConfigurationMessage::setDataUnits (const ExdDataUnits dataUnits)
Sets the dataUnits field to dataUnits.
Parameters
dataUnits The field value to set.
Definition at line 265 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(ExdDataConceptConfigurationMessage);
     d->dataUnits = dataUnits;
 }
References dataUnits().
setDescriptor()
void ExdDataConceptConfigurationMessage::setDescriptor (const ExdDescriptors descriptor)
Sets the descriptor field to descriptor.
Parameters
descriptor The field value to set.
Definition at line 285 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(ExdDataConceptConfigurationMessage);
     d->descriptor = descriptor;
 }
References descriptor().
setFieldId()
void ExdDataConceptConfigurationMessage::setFieldId (const quint8 fieldId)
Sets the fieldId field to fieldId.
Parameters
fieldId The field value to set.
Definition at line 215 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(ExdDataConceptConfigurationMessage);
     d->fieldId = fieldId;
 }
References fieldId().
setIsSigned()
void ExdDataConceptConfigurationMessage::setIsSigned (const bool isSigned)
Sets the isSigned field to isSigned.
Parameters
isSigned The field value to set.
Definition at line 295 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(ExdDataConceptConfigurationMessage);
     d->isSigned = isSigned;
 }
References isSigned().
setQualifier()
void ExdDataConceptConfigurationMessage::setQualifier (const ExdQualifiers qualifier)
Sets the qualifier field to qualifier.
Parameters
qualifier The field value to set.
Definition at line 275 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(ExdDataConceptConfigurationMessage);
     d->qualifier = qualifier;
 }
References qualifier().
setScaling()
void ExdDataConceptConfigurationMessage::setScaling (const quint8 scaling)
Sets the scaling field to scaling.
Parameters
scaling The field value to set.
Definition at line 255 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(ExdDataConceptConfigurationMessage);
     d->scaling = scaling;
 }
References scaling().
setScreenIndex()
void ExdDataConceptConfigurationMessage::setScreenIndex (const quint8 screenIndex)
Sets the screenIndex field to screenIndex.
Parameters
screenIndex The field value to set.
Definition at line 195 of file exddataconceptconfigurationmessage.cpp.
 {
     Q_D(ExdDataConceptConfigurationMessage);
     d->screenIndex = screenIndex;
 }
References screenIndex().
The documentation for this class was generated from the following files:
exddataconceptconfigurationmessage.h
exddataconceptconfigurationmessage.cpp