QtFit: SegmentLeaderboardEntryMessage Class Reference
SegmentLeaderboardEntryMessage Class Reference
The SegmentLeaderboardEntryMessage class represents a FIT SegmentLeaderboardEntryMessage data message.
#include <segmentleaderboardentrymessage.h>
Public Member Functions
SegmentLeaderboardEntryMessage ()
Constructs an invalid SegmentLeaderboardEntryMessage object.
~SegmentLeaderboardEntryMessage ()
MessageIndex messageIndex () const
Returns the SegmentLeaderboardEntryMessage data message's messageIndex field's current value.
QString name () const
Returns the SegmentLeaderboardEntryMessage data message's name field's current value.
SegmentLeaderboardType type () const
Returns the SegmentLeaderboardEntryMessage data message's type field's current value.
quint32 groupPrimaryKey () const
Returns the SegmentLeaderboardEntryMessage data message's groupPrimaryKey field's current value.
quint32 activityId () const
Returns the SegmentLeaderboardEntryMessage data message's activityId field's current value.
quint32 segmentTime () const
Returns the SegmentLeaderboardEntryMessage data message's segmentTime field's current value.
QString activityIdString () const
Returns the SegmentLeaderboardEntryMessage data message's activityIdString field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setName (const QString name)
Sets the name field to name.
void setType (const SegmentLeaderboardType type)
Sets the type field to type.
void setGroupPrimaryKey (const quint32 groupPrimaryKey)
Sets the groupPrimaryKey field to groupPrimaryKey.
void setActivityId (const quint32 activityId)
Sets the activityId field to activityId.
void setSegmentTime (const quint32 segmentTime)
Sets the segmentTime field to segmentTime.
void setActivityIdString (const QString activityIdString)
Sets the activityIdString field to activityIdString.
Public Member Functions inherited from FitDataMessage
FitDataMessage ()
Constructs a invalid, null FitDataMessage object.
FitDataMessage (const FitDataMessage &other)
Copies a FitDataMessage.
FitDataMessage & operator= (const FitDataMessage &other)
Assigns a FitDataMessage to this one.
~FitDataMessage ()
Destroys the FitDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
bool isNull () const
Returns true if this is not a valid data message, otherwise false.
Additional Inherited Members
Static Public Member Functions inherited from FitDataMessage
static FitDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant FitDataMessage-derived class to parse record according to defn.
Detailed Description
The SegmentLeaderboardEntryMessage class represents a FIT SegmentLeaderboardEntryMessage data message.
See also
DataMessage
Definition at line 34 of file segmentleaderboardentrymessage.h.
Constructor & Destructor Documentation
SegmentLeaderboardEntryMessage()
SegmentLeaderboardEntryMessage::SegmentLeaderboardEntryMessage ()
Constructs an invalid SegmentLeaderboardEntryMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file segmentleaderboardentrymessage.cpp.
                                                                : FitDataMessage(new SegmentLeaderboardEntryMessagePrivate(this))
 {
 }
~SegmentLeaderboardEntryMessage()
SegmentLeaderboardEntryMessage::~SegmentLeaderboardEntryMessage ()
Member Function Documentation
activityId()
quint32 SegmentLeaderboardEntryMessage::activityId () const
Returns the SegmentLeaderboardEntryMessage data message's activityId field's current value.
Returns
the activityId field value.
Definition at line 101 of file segmentleaderboardentrymessage.cpp.
 {
     Q_D(const SegmentLeaderboardEntryMessage);
     return d->activityId;
 }
Referenced by setActivityId().
activityIdString()
QString SegmentLeaderboardEntryMessage::activityIdString () const
Returns the SegmentLeaderboardEntryMessage data message's activityIdString field's current value.
Returns
the activityIdString field value.
Definition at line 123 of file segmentleaderboardentrymessage.cpp.
 {
     Q_D(const SegmentLeaderboardEntryMessage);
     return d->activityIdString;
 }
Referenced by setActivityIdString().
groupPrimaryKey()
quint32 SegmentLeaderboardEntryMessage::groupPrimaryKey () const
Returns the SegmentLeaderboardEntryMessage data message's groupPrimaryKey field's current value.
Returns
the groupPrimaryKey field value.
Definition at line 90 of file segmentleaderboardentrymessage.cpp.
 {
     Q_D(const SegmentLeaderboardEntryMessage);
     return d->groupPrimaryKey;
 }
Referenced by setGroupPrimaryKey().
messageIndex()
MessageIndex SegmentLeaderboardEntryMessage::messageIndex () const
Returns the SegmentLeaderboardEntryMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 57 of file segmentleaderboardentrymessage.cpp.
 {
     Q_D(const SegmentLeaderboardEntryMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
name()
QString SegmentLeaderboardEntryMessage::name () const
Returns the SegmentLeaderboardEntryMessage data message's name field's current value.
Returns
the name field value.
Definition at line 68 of file segmentleaderboardentrymessage.cpp.
 {
     Q_D(const SegmentLeaderboardEntryMessage);
     return d->name;
 }
Referenced by setName().
segmentTime()
quint32 SegmentLeaderboardEntryMessage::segmentTime () const
Returns the SegmentLeaderboardEntryMessage data message's segmentTime field's current value.
Returns
the segmentTime field value.
Definition at line 112 of file segmentleaderboardentrymessage.cpp.
 {
     Q_D(const SegmentLeaderboardEntryMessage);
     return d->segmentTime;
 }
Referenced by setSegmentTime().
setActivityId()
void SegmentLeaderboardEntryMessage::setActivityId (const quint32 activityId)
Sets the activityId field to activityId.
Parameters
activityId The field value to set.
Definition at line 174 of file segmentleaderboardentrymessage.cpp.
 {
     Q_D(SegmentLeaderboardEntryMessage);
     d->activityId = activityId;
 }
References activityId().
setActivityIdString()
void SegmentLeaderboardEntryMessage::setActivityIdString (const QString activityIdString)
Sets the activityIdString field to activityIdString.
Parameters
activityIdString The field value to set.
Definition at line 194 of file segmentleaderboardentrymessage.cpp.
 {
     Q_D(SegmentLeaderboardEntryMessage);
     d->activityIdString = activityIdString;
 }
References activityIdString().
setGroupPrimaryKey()
void SegmentLeaderboardEntryMessage::setGroupPrimaryKey (const quint32 groupPrimaryKey)
Sets the groupPrimaryKey field to groupPrimaryKey.
Parameters
groupPrimaryKey The field value to set.
Definition at line 164 of file segmentleaderboardentrymessage.cpp.
 {
     Q_D(SegmentLeaderboardEntryMessage);
     d->groupPrimaryKey = groupPrimaryKey;
 }
References groupPrimaryKey().
setMessageIndex()
void SegmentLeaderboardEntryMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 134 of file segmentleaderboardentrymessage.cpp.
 {
     Q_D(SegmentLeaderboardEntryMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setName()
void SegmentLeaderboardEntryMessage::setName (const QString name)
Sets the name field to name.
Parameters
name The field value to set.
Definition at line 144 of file segmentleaderboardentrymessage.cpp.
 {
     Q_D(SegmentLeaderboardEntryMessage);
     d->name = name;
 }
References name().
setSegmentTime()
void SegmentLeaderboardEntryMessage::setSegmentTime (const quint32 segmentTime)
Sets the segmentTime field to segmentTime.
Parameters
segmentTime The field value to set.
Definition at line 184 of file segmentleaderboardentrymessage.cpp.
 {
     Q_D(SegmentLeaderboardEntryMessage);
     d->segmentTime = segmentTime;
 }
References segmentTime().
setType()
void SegmentLeaderboardEntryMessage::setType (const SegmentLeaderboardType type)
Sets the type field to type.
Parameters
type The field value to set.
Definition at line 154 of file segmentleaderboardentrymessage.cpp.
 {
     Q_D(SegmentLeaderboardEntryMessage);
     d->type = type;
 }
References type().
type()
SegmentLeaderboardType SegmentLeaderboardEntryMessage::type () const
Returns the SegmentLeaderboardEntryMessage data message's type field's current value.
Returns
the type field value.
Definition at line 79 of file segmentleaderboardentrymessage.cpp.
 {
     Q_D(const SegmentLeaderboardEntryMessage);
     return d->type;
 }
Referenced by setType().
The documentation for this class was generated from the following files:
segmentleaderboardentrymessage.h
segmentleaderboardentrymessage.cpp