QtFit: DiveSettingsMessage Class Reference
DiveSettingsMessage Class Reference
The DiveSettingsMessage class represents a FIT DiveSettingsMessage data message.
Public Member Functions
DiveSettingsMessage ()
Constructs a DiveSettingsMessage object.
MessageIndex messageIndex () const
Returns the DiveSettingsMessage data message's messageIndex field's current value.
QString name () const
Returns the DiveSettingsMessage data message's name field's current value.
TissueModelType model () const
Returns the DiveSettingsMessage data message's model field's current value.
quint8 gfLow () const
Returns the DiveSettingsMessage data message's gfLow field's current value.
quint8 gfHigh () const
Returns the DiveSettingsMessage data message's gfHigh field's current value.
WaterType waterType () const
Returns the DiveSettingsMessage data message's waterType field's current value.
float waterDensity () const
Returns the DiveSettingsMessage data message's waterDensity field's current value.
quint8 po2Warn () const
Returns the DiveSettingsMessage data message's po2Warn field's current value.
quint8 po2Critical () const
Returns the DiveSettingsMessage data message's po2Critical field's current value.
quint8 po2Deco () const
Returns the DiveSettingsMessage data message's po2Deco field's current value.
bool safetyStopEnabled () const
Returns the DiveSettingsMessage data message's safetyStopEnabled field's current value.
float bottomDepth () const
Returns the DiveSettingsMessage data message's bottomDepth field's current value.
quint32 bottomTime () const
Returns the DiveSettingsMessage data message's bottomTime field's current value.
bool apneaCountdownEnabled () const
Returns the DiveSettingsMessage data message's apneaCountdownEnabled field's current value.
quint32 apneaCountdownTime () const
Returns the DiveSettingsMessage data message's apneaCountdownTime field's current value.
DiveBacklightMode backlightMode () const
Returns the DiveSettingsMessage data message's backlightMode field's current value.
quint8 backlightBrightness () const
Returns the DiveSettingsMessage data message's backlightBrightness field's current value.
BacklightTimeout backlightTimeout () const
Returns the DiveSettingsMessage data message's backlightTimeout field's current value.
quint16 repeatDiveInterval () const
Returns the DiveSettingsMessage data message's repeatDiveInterval field's current value.
quint16 safetyStopTime () const
Returns the DiveSettingsMessage data message's safetyStopTime field's current value.
SourceType heartRateSourceType () const
Returns the DiveSettingsMessage data message's heartRateSourceType field's current value.
quint8 heartRateSource () const
Returns the DiveSettingsMessage data message's heartRateSource field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setName (const QString name)
Sets the name field to name.
void setModel (const TissueModelType model)
Sets the model field to model.
void setGfLow (const quint8 gfLow)
Sets the gfLow field to gfLow.
void setGfHigh (const quint8 gfHigh)
Sets the gfHigh field to gfHigh.
void setWaterType (const WaterType waterType)
Sets the waterType field to waterType.
void setWaterDensity (const float waterDensity)
Sets the waterDensity field to waterDensity.
void setPo2Warn (const quint8 po2Warn)
Sets the po2Warn field to po2Warn.
void setPo2Critical (const quint8 po2Critical)
Sets the po2Critical field to po2Critical.
void setPo2Deco (const quint8 po2Deco)
Sets the po2Deco field to po2Deco.
void setSafetyStopEnabled (const bool safetyStopEnabled)
Sets the safetyStopEnabled field to safetyStopEnabled.
void setBottomDepth (const float bottomDepth)
Sets the bottomDepth field to bottomDepth.
void setBottomTime (const quint32 bottomTime)
Sets the bottomTime field to bottomTime.
void setApneaCountdownEnabled (const bool apneaCountdownEnabled)
Sets the apneaCountdownEnabled field to apneaCountdownEnabled.
void setApneaCountdownTime (const quint32 apneaCountdownTime)
Sets the apneaCountdownTime field to apneaCountdownTime.
void setBacklightMode (const DiveBacklightMode backlightMode)
Sets the backlightMode field to backlightMode.
void setBacklightBrightness (const quint8 backlightBrightness)
Sets the backlightBrightness field to backlightBrightness.
void setBacklightTimeout (const BacklightTimeout backlightTimeout)
Sets the backlightTimeout field to backlightTimeout.
void setRepeatDiveInterval (const quint16 repeatDiveInterval)
Sets the repeatDiveInterval field to repeatDiveInterval.
void setSafetyStopTime (const quint16 safetyStopTime)
Sets the safetyStopTime field to safetyStopTime.
void setHeartRateSourceType (const SourceType heartRateSourceType)
Sets the heartRateSourceType field to heartRateSourceType.
void setHeartRateSource (const quint8 heartRateSource)
Sets the heartRateSource field to heartRateSource.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
DiveSettingsMessage (DiveSettingsMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The DiveSettingsMessage class represents a FIT DiveSettingsMessage data message.
See also
DataMessage
Definition at line 39 of file divesettingsmessage.h.
Constructor & Destructor Documentation
DiveSettingsMessage() [1/2]
DiveSettingsMessage::DiveSettingsMessage ()
Constructs a DiveSettingsMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file divesettingsmessage.cpp.
                                          : AbstractDataMessage(new DiveSettingsMessagePrivate(this))
 {
 }
DiveSettingsMessage() [2/2]
DiveSettingsMessage::DiveSettingsMessage (DiveSettingsMessagePrivate *const d) explicit protected
Constructs a DiveSettingsMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file divesettingsmessage.cpp.
                                                                              : AbstractDataMessage(d)
 {
 }
Member Function Documentation
apneaCountdownEnabled()
bool DiveSettingsMessage::apneaCountdownEnabled () const
Returns the DiveSettingsMessage data message's apneaCountdownEnabled field's current value.
Returns
the apneaCountdownEnabled field value.
Definition at line 223 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->apneaCountdownEnabled;
 }
Referenced by setApneaCountdownEnabled().
apneaCountdownTime()
quint32 DiveSettingsMessage::apneaCountdownTime () const
Returns the DiveSettingsMessage data message's apneaCountdownTime field's current value.
Returns
the apneaCountdownTime field value.
Definition at line 234 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->apneaCountdownTime;
 }
Referenced by setApneaCountdownTime().
backlightBrightness()
quint8 DiveSettingsMessage::backlightBrightness () const
Returns the DiveSettingsMessage data message's backlightBrightness field's current value.
Returns
the backlightBrightness field value.
Definition at line 256 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->backlightBrightness;
 }
Referenced by setBacklightBrightness().
backlightMode()
DiveBacklightMode DiveSettingsMessage::backlightMode () const
Returns the DiveSettingsMessage data message's backlightMode field's current value.
Returns
the backlightMode field value.
Definition at line 245 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->backlightMode;
 }
Referenced by setBacklightMode().
backlightTimeout()
BacklightTimeout DiveSettingsMessage::backlightTimeout () const
Returns the DiveSettingsMessage data message's backlightTimeout field's current value.
Returns
the backlightTimeout field value.
Definition at line 267 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->backlightTimeout;
 }
Referenced by setBacklightTimeout().
bottomDepth()
float DiveSettingsMessage::bottomDepth () const
Returns the DiveSettingsMessage data message's bottomDepth field's current value.
Returns
the bottomDepth field value.
Definition at line 201 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->bottomDepth;
 }
Referenced by setBottomDepth().
bottomTime()
quint32 DiveSettingsMessage::bottomTime () const
Returns the DiveSettingsMessage data message's bottomTime field's current value.
Returns
the bottomTime field value.
Definition at line 212 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->bottomTime;
 }
Referenced by setBottomTime().
gfHigh()
quint8 DiveSettingsMessage::gfHigh () const
Returns the DiveSettingsMessage data message's gfHigh field's current value.
Returns
the gfHigh field value.
Definition at line 118 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->gfHigh;
 }
Referenced by setGfHigh().
gfLow()
quint8 DiveSettingsMessage::gfLow () const
Returns the DiveSettingsMessage data message's gfLow field's current value.
Returns
the gfLow field value.
Definition at line 107 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->gfLow;
 }
Referenced by setGfLow().
heartRateSource()
quint8 DiveSettingsMessage::heartRateSource () const
Returns the DiveSettingsMessage data message's heartRateSource field's current value.
Returns
the heartRateSource field value.
Definition at line 315 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->heartRateSource;
 }
Referenced by setHeartRateSource().
heartRateSourceType()
SourceType DiveSettingsMessage::heartRateSourceType () const
Returns the DiveSettingsMessage data message's heartRateSourceType field's current value.
Returns
the heartRateSourceType field value.
Definition at line 304 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->heartRateSourceType;
 }
Referenced by setHeartRateSourceType().
messageIndex()
MessageIndex DiveSettingsMessage::messageIndex () const
Returns the DiveSettingsMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 74 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
model()
TissueModelType DiveSettingsMessage::model () const
Returns the DiveSettingsMessage data message's model field's current value.
Returns
the model field value.
Definition at line 96 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->model;
 }
Referenced by setModel().
name()
QString DiveSettingsMessage::name () const
Returns the DiveSettingsMessage data message's name field's current value.
Returns
the name field value.
Definition at line 85 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->name;
 }
Referenced by setName().
po2Critical()
quint8 DiveSettingsMessage::po2Critical () const
Returns the DiveSettingsMessage data message's po2Critical field's current value.
Typically 1.60
Returns
the po2Critical field value.
Definition at line 168 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->po2Critical;
 }
Referenced by setPo2Critical().
po2Deco()
quint8 DiveSettingsMessage::po2Deco () const
Returns the DiveSettingsMessage data message's po2Deco field's current value.
Returns
the po2Deco field value.
Definition at line 179 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->po2Deco;
 }
Referenced by setPo2Deco().
po2Warn()
quint8 DiveSettingsMessage::po2Warn () const
Returns the DiveSettingsMessage data message's po2Warn field's current value.
Typically 1.40
Returns
the po2Warn field value.
Definition at line 155 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->po2Warn;
 }
Referenced by setPo2Warn().
repeatDiveInterval()
quint16 DiveSettingsMessage::repeatDiveInterval () const
Returns the DiveSettingsMessage data message's repeatDiveInterval field's current value.
Time between surfacing and ending the activity
Returns
the repeatDiveInterval field value.
Definition at line 280 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->repeatDiveInterval;
 }
Referenced by setRepeatDiveInterval().
safetyStopEnabled()
bool DiveSettingsMessage::safetyStopEnabled () const
Returns the DiveSettingsMessage data message's safetyStopEnabled field's current value.
Returns
the safetyStopEnabled field value.
Definition at line 190 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->safetyStopEnabled;
 }
Referenced by setSafetyStopEnabled().
safetyStopTime()
quint16 DiveSettingsMessage::safetyStopTime () const
Returns the DiveSettingsMessage data message's safetyStopTime field's current value.
Time at safety stop (if enabled)
Returns
the safetyStopTime field value.
Definition at line 293 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->safetyStopTime;
 }
Referenced by setSafetyStopTime().
setApneaCountdownEnabled()
void DiveSettingsMessage::setApneaCountdownEnabled (const bool apneaCountdownEnabled)
Sets the apneaCountdownEnabled field to apneaCountdownEnabled.
Parameters
apneaCountdownEnabled The field value to set.
Definition at line 456 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->apneaCountdownEnabled = apneaCountdownEnabled;
 }
References apneaCountdownEnabled().
setApneaCountdownTime()
void DiveSettingsMessage::setApneaCountdownTime (const quint32 apneaCountdownTime)
Sets the apneaCountdownTime field to apneaCountdownTime.
Parameters
apneaCountdownTime The field value to set.
Definition at line 466 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->apneaCountdownTime = apneaCountdownTime;
 }
References apneaCountdownTime().
setBacklightBrightness()
void DiveSettingsMessage::setBacklightBrightness (const quint8 backlightBrightness)
Sets the backlightBrightness field to backlightBrightness.
Parameters
backlightBrightness The field value to set.
Definition at line 486 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->backlightBrightness = backlightBrightness;
 }
References backlightBrightness().
setBacklightMode()
void DiveSettingsMessage::setBacklightMode (const DiveBacklightMode backlightMode)
Sets the backlightMode field to backlightMode.
Parameters
backlightMode The field value to set.
Definition at line 476 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->backlightMode = backlightMode;
 }
References backlightMode().
setBacklightTimeout()
void DiveSettingsMessage::setBacklightTimeout (const BacklightTimeout backlightTimeout)
Sets the backlightTimeout field to backlightTimeout.
Parameters
backlightTimeout The field value to set.
Definition at line 496 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->backlightTimeout = backlightTimeout;
 }
References backlightTimeout().
setBottomDepth()
void DiveSettingsMessage::setBottomDepth (const float bottomDepth)
Sets the bottomDepth field to bottomDepth.
Parameters
bottomDepth The field value to set.
Definition at line 436 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->bottomDepth = bottomDepth;
 }
References bottomDepth().
setBottomTime()
void DiveSettingsMessage::setBottomTime (const quint32 bottomTime)
Sets the bottomTime field to bottomTime.
Parameters
bottomTime The field value to set.
Definition at line 446 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->bottomTime = bottomTime;
 }
References bottomTime().
setGfHigh()
void DiveSettingsMessage::setGfHigh (const quint8 gfHigh)
Sets the gfHigh field to gfHigh.
Parameters
gfHigh The field value to set.
Definition at line 366 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->gfHigh = gfHigh;
 }
References gfHigh().
setGfLow()
void DiveSettingsMessage::setGfLow (const quint8 gfLow)
Sets the gfLow field to gfLow.
Parameters
gfLow The field value to set.
Definition at line 356 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->gfLow = gfLow;
 }
References gfLow().
setHeartRateSource()
void DiveSettingsMessage::setHeartRateSource (const quint8 heartRateSource)
Sets the heartRateSource field to heartRateSource.
Parameters
heartRateSource The field value to set.
Definition at line 536 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->heartRateSource = heartRateSource;
 }
References heartRateSource().
setHeartRateSourceType()
void DiveSettingsMessage::setHeartRateSourceType (const SourceType heartRateSourceType)
Sets the heartRateSourceType field to heartRateSourceType.
Parameters
heartRateSourceType The field value to set.
Definition at line 526 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->heartRateSourceType = heartRateSourceType;
 }
References heartRateSourceType().
setMessageIndex()
void DiveSettingsMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 326 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setModel()
void DiveSettingsMessage::setModel (const TissueModelType model)
Sets the model field to model.
Parameters
model The field value to set.
Definition at line 346 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->model = model;
 }
References model().
setName()
void DiveSettingsMessage::setName (const QString name)
Sets the name field to name.
Parameters
name The field value to set.
Definition at line 336 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->name = name;
 }
References name().
setPo2Critical()
void DiveSettingsMessage::setPo2Critical (const quint8 po2Critical)
Sets the po2Critical field to po2Critical.
Parameters
po2Critical The field value to set.
Definition at line 406 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->po2Critical = po2Critical;
 }
References po2Critical().
setPo2Deco()
void DiveSettingsMessage::setPo2Deco (const quint8 po2Deco)
Sets the po2Deco field to po2Deco.
Parameters
po2Deco The field value to set.
Definition at line 416 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->po2Deco = po2Deco;
 }
References po2Deco().
setPo2Warn()
void DiveSettingsMessage::setPo2Warn (const quint8 po2Warn)
Sets the po2Warn field to po2Warn.
Parameters
po2Warn The field value to set.
Definition at line 396 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->po2Warn = po2Warn;
 }
References po2Warn().
setRepeatDiveInterval()
void DiveSettingsMessage::setRepeatDiveInterval (const quint16 repeatDiveInterval)
Sets the repeatDiveInterval field to repeatDiveInterval.
Parameters
repeatDiveInterval The field value to set.
Definition at line 506 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->repeatDiveInterval = repeatDiveInterval;
 }
References repeatDiveInterval().
setSafetyStopEnabled()
void DiveSettingsMessage::setSafetyStopEnabled (const bool safetyStopEnabled)
Sets the safetyStopEnabled field to safetyStopEnabled.
Parameters
safetyStopEnabled The field value to set.
Definition at line 426 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->safetyStopEnabled = safetyStopEnabled;
 }
References safetyStopEnabled().
setSafetyStopTime()
void DiveSettingsMessage::setSafetyStopTime (const quint16 safetyStopTime)
Sets the safetyStopTime field to safetyStopTime.
Parameters
safetyStopTime The field value to set.
Definition at line 516 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->safetyStopTime = safetyStopTime;
 }
References safetyStopTime().
setWaterDensity()
void DiveSettingsMessage::setWaterDensity (const float waterDensity)
Sets the waterDensity field to waterDensity.
Parameters
waterDensity The field value to set.
Definition at line 386 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->waterDensity = waterDensity;
 }
References waterDensity().
setWaterType()
void DiveSettingsMessage::setWaterType (const WaterType waterType)
Sets the waterType field to waterType.
Parameters
waterType The field value to set.
Definition at line 376 of file divesettingsmessage.cpp.
 {
     Q_D(DiveSettingsMessage);
     d->waterType = waterType;
 }
References waterType().
waterDensity()
float DiveSettingsMessage::waterDensity () const
Returns the DiveSettingsMessage data message's waterDensity field's current value.
Fresh water is usually 1000; salt water is usually 1025
Returns
the waterDensity field value.
Definition at line 142 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->waterDensity;
 }
Referenced by setWaterDensity().
waterType()
WaterType DiveSettingsMessage::waterType () const
Returns the DiveSettingsMessage data message's waterType field's current value.
Returns
the waterType field value.
Definition at line 129 of file divesettingsmessage.cpp.
 {
     Q_D(const DiveSettingsMessage);
     return d->waterType;
 }
Referenced by setWaterType().
The documentation for this class was generated from the following files:
divesettingsmessage.h
divesettingsmessage.cpp