QtFit: ClimbProMessage Class Reference
ClimbProMessage Class Reference
The ClimbProMessage class represents a FIT ClimbProMessage data message.
Public Member Functions
ClimbProMessage ()
Constructs a ClimbProMessage object.
DateTime timestamp () const
Returns the ClimbProMessage data message's timestamp field's current value.
qint32 positionLat () const
Returns the ClimbProMessage data message's positionLat field's current value.
qint32 positionLong () const
Returns the ClimbProMessage data message's positionLong field's current value.
ClimbProEvent climbProEvent () const
Returns the ClimbProMessage data message's climbProEvent field's current value.
quint16 climbNumber () const
Returns the ClimbProMessage data message's climbNumber field's current value.
quint8 climbCategory () const
Returns the ClimbProMessage data message's climbCategory field's current value.
float currentDist () const
Returns the ClimbProMessage data message's currentDist field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setPositionLat (const qint32 positionLat)
Sets the positionLat field to positionLat.
void setPositionLong (const qint32 positionLong)
Sets the positionLong field to positionLong.
void setClimbProEvent (const ClimbProEvent climbProEvent)
Sets the climbProEvent field to climbProEvent.
void setClimbNumber (const quint16 climbNumber)
Sets the climbNumber field to climbNumber.
void setClimbCategory (const quint8 climbCategory)
Sets the climbCategory field to climbCategory.
void setCurrentDist (const float currentDist)
Sets the currentDist field to currentDist.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
ClimbProMessage (ClimbProMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The ClimbProMessage class represents a FIT ClimbProMessage data message.
See also
DataMessage
Definition at line 34 of file climbpromessage.h.
Constructor & Destructor Documentation
ClimbProMessage() [1/2]
ClimbProMessage::ClimbProMessage ()
Constructs a ClimbProMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file climbpromessage.cpp.
                                  : AbstractDataMessage(new ClimbProMessagePrivate(this))
 {
 }
ClimbProMessage() [2/2]
ClimbProMessage::ClimbProMessage (ClimbProMessagePrivate *const d) explicit protected
Constructs a ClimbProMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file climbpromessage.cpp.
                                                                  : AbstractDataMessage(d)
 {
 }
Member Function Documentation
climbCategory()
quint8 ClimbProMessage::climbCategory () const
Returns the ClimbProMessage data message's climbCategory field's current value.
Returns
the climbCategory field value.
Definition at line 124 of file climbpromessage.cpp.
 {
     Q_D(const ClimbProMessage);
     return d->climbCategory;
 }
Referenced by setClimbCategory().
climbNumber()
quint16 ClimbProMessage::climbNumber () const
Returns the ClimbProMessage data message's climbNumber field's current value.
Returns
the climbNumber field value.
Definition at line 113 of file climbpromessage.cpp.
 {
     Q_D(const ClimbProMessage);
     return d->climbNumber;
 }
Referenced by setClimbNumber().
climbProEvent()
ClimbProEvent ClimbProMessage::climbProEvent () const
Returns the ClimbProMessage data message's climbProEvent field's current value.
Returns
the climbProEvent field value.
Definition at line 102 of file climbpromessage.cpp.
 {
     Q_D(const ClimbProMessage);
     return d->climbProEvent;
 }
Referenced by setClimbProEvent().
currentDist()
float ClimbProMessage::currentDist () const
Returns the ClimbProMessage data message's currentDist field's current value.
Returns
the currentDist field value.
Definition at line 135 of file climbpromessage.cpp.
 {
     Q_D(const ClimbProMessage);
     return d->currentDist;
 }
Referenced by setCurrentDist().
positionLat()
qint32 ClimbProMessage::positionLat () const
Returns the ClimbProMessage data message's positionLat field's current value.
Returns
the positionLat field value.
Definition at line 80 of file climbpromessage.cpp.
 {
     Q_D(const ClimbProMessage);
     return d->positionLat;
 }
Referenced by setPositionLat().
positionLong()
qint32 ClimbProMessage::positionLong () const
Returns the ClimbProMessage data message's positionLong field's current value.
Returns
the positionLong field value.
Definition at line 91 of file climbpromessage.cpp.
 {
     Q_D(const ClimbProMessage);
     return d->positionLong;
 }
Referenced by setPositionLong().
setClimbCategory()
void ClimbProMessage::setClimbCategory (const quint8 climbCategory)
Sets the climbCategory field to climbCategory.
Parameters
climbCategory The field value to set.
Definition at line 196 of file climbpromessage.cpp.
 {
     Q_D(ClimbProMessage);
     d->climbCategory = climbCategory;
 }
References climbCategory().
setClimbNumber()
void ClimbProMessage::setClimbNumber (const quint16 climbNumber)
Sets the climbNumber field to climbNumber.
Parameters
climbNumber The field value to set.
Definition at line 186 of file climbpromessage.cpp.
 {
     Q_D(ClimbProMessage);
     d->climbNumber = climbNumber;
 }
References climbNumber().
setClimbProEvent()
void ClimbProMessage::setClimbProEvent (const ClimbProEvent climbProEvent)
Sets the climbProEvent field to climbProEvent.
Parameters
climbProEvent The field value to set.
Definition at line 176 of file climbpromessage.cpp.
 {
     Q_D(ClimbProMessage);
     d->climbProEvent = climbProEvent;
 }
References climbProEvent().
setCurrentDist()
void ClimbProMessage::setCurrentDist (const float currentDist)
Sets the currentDist field to currentDist.
Parameters
currentDist The field value to set.
Definition at line 206 of file climbpromessage.cpp.
 {
     Q_D(ClimbProMessage);
     d->currentDist = currentDist;
 }
References currentDist().
setPositionLat()
void ClimbProMessage::setPositionLat (const qint32 positionLat)
Sets the positionLat field to positionLat.
Parameters
positionLat The field value to set.
Definition at line 156 of file climbpromessage.cpp.
 {
     Q_D(ClimbProMessage);
     d->positionLat = positionLat;
 }
References positionLat().
setPositionLong()
void ClimbProMessage::setPositionLong (const qint32 positionLong)
Sets the positionLong field to positionLong.
Parameters
positionLong The field value to set.
Definition at line 166 of file climbpromessage.cpp.
 {
     Q_D(ClimbProMessage);
     d->positionLong = positionLong;
 }
References positionLong().
setTimestamp()
void ClimbProMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 146 of file climbpromessage.cpp.
 {
     Q_D(ClimbProMessage);
     d->timestamp = timestamp;
 }
References timestamp().
timestamp()
DateTime ClimbProMessage::timestamp () const
Returns the ClimbProMessage data message's timestamp field's current value.
Returns
the timestamp field value.
Definition at line 69 of file climbpromessage.cpp.
 {
     Q_D(const ClimbProMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
The documentation for this class was generated from the following files:
climbpromessage.h
climbpromessage.cpp