QtFit: CoursePointMessage Class Reference
CoursePointMessage Class Reference
The CoursePointMessage class represents a FIT CoursePointMessage data message.
Public Member Functions
CoursePointMessage ()
Constructs a CoursePointMessage object.
MessageIndex messageIndex () const
Returns the CoursePointMessage data message's messageIndex field's current value.
DateTime timestamp () const
Returns the CoursePointMessage data message's timestamp field's current value.
qint32 positionLat () const
Returns the CoursePointMessage data message's positionLat field's current value.
qint32 positionLong () const
Returns the CoursePointMessage data message's positionLong field's current value.
quint32 distance () const
Returns the CoursePointMessage data message's distance field's current value.
CoursePoint type () const
Returns the CoursePointMessage data message's type field's current value.
QString name () const
Returns the CoursePointMessage data message's name field's current value.
bool favorite () const
Returns the CoursePointMessage data message's favorite field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setPositionLat (const qint32 positionLat)
Sets the positionLat field to positionLat.
void setPositionLong (const qint32 positionLong)
Sets the positionLong field to positionLong.
void setDistance (const quint32 distance)
Sets the distance field to distance.
void setType (const CoursePoint type)
Sets the type field to type.
void setName (const QString name)
Sets the name field to name.
void setFavorite (const bool favorite)
Sets the favorite field to favorite.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
CoursePointMessage (CoursePointMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The CoursePointMessage class represents a FIT CoursePointMessage data message.
See also
DataMessage
Definition at line 34 of file coursepointmessage.h.
Constructor & Destructor Documentation
CoursePointMessage() [1/2]
CoursePointMessage::CoursePointMessage ()
Constructs a CoursePointMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file coursepointmessage.cpp.
                                        : AbstractDataMessage(new CoursePointMessagePrivate(this))
 {
 }
CoursePointMessage() [2/2]
CoursePointMessage::CoursePointMessage (CoursePointMessagePrivate *const d) explicit protected
Constructs a CoursePointMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file coursepointmessage.cpp.
                                                                           : AbstractDataMessage(d)
 {
 }
Member Function Documentation
distance()
quint32 CoursePointMessage::distance () const
Returns the CoursePointMessage data message's distance field's current value.
Returns
the distance field value.
Definition at line 113 of file coursepointmessage.cpp.
 {
     Q_D(const CoursePointMessage);
     return d->distance;
 }
Referenced by setDistance().
favorite()
bool CoursePointMessage::favorite () const
Returns the CoursePointMessage data message's favorite field's current value.
Returns
the favorite field value.
Definition at line 146 of file coursepointmessage.cpp.
 {
     Q_D(const CoursePointMessage);
     return d->favorite;
 }
Referenced by setFavorite().
messageIndex()
MessageIndex CoursePointMessage::messageIndex () const
Returns the CoursePointMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 69 of file coursepointmessage.cpp.
 {
     Q_D(const CoursePointMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
name()
QString CoursePointMessage::name () const
Returns the CoursePointMessage data message's name field's current value.
Returns
the name field value.
Definition at line 135 of file coursepointmessage.cpp.
 {
     Q_D(const CoursePointMessage);
     return d->name;
 }
Referenced by setName().
positionLat()
qint32 CoursePointMessage::positionLat () const
Returns the CoursePointMessage data message's positionLat field's current value.
Returns
the positionLat field value.
Definition at line 91 of file coursepointmessage.cpp.
 {
     Q_D(const CoursePointMessage);
     return d->positionLat;
 }
Referenced by setPositionLat().
positionLong()
qint32 CoursePointMessage::positionLong () const
Returns the CoursePointMessage data message's positionLong field's current value.
Returns
the positionLong field value.
Definition at line 102 of file coursepointmessage.cpp.
 {
     Q_D(const CoursePointMessage);
     return d->positionLong;
 }
Referenced by setPositionLong().
setDistance()
void CoursePointMessage::setDistance (const quint32 distance)
Sets the distance field to distance.
Parameters
distance The field value to set.
Definition at line 197 of file coursepointmessage.cpp.
 {
     Q_D(CoursePointMessage);
     d->distance = distance;
 }
References distance().
setFavorite()
void CoursePointMessage::setFavorite (const bool favorite)
Sets the favorite field to favorite.
Parameters
favorite The field value to set.
Definition at line 227 of file coursepointmessage.cpp.
 {
     Q_D(CoursePointMessage);
     d->favorite = favorite;
 }
References favorite().
setMessageIndex()
void CoursePointMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 157 of file coursepointmessage.cpp.
 {
     Q_D(CoursePointMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setName()
void CoursePointMessage::setName (const QString name)
Sets the name field to name.
Parameters
name The field value to set.
Definition at line 217 of file coursepointmessage.cpp.
 {
     Q_D(CoursePointMessage);
     d->name = name;
 }
References name().
setPositionLat()
void CoursePointMessage::setPositionLat (const qint32 positionLat)
Sets the positionLat field to positionLat.
Parameters
positionLat The field value to set.
Definition at line 177 of file coursepointmessage.cpp.
 {
     Q_D(CoursePointMessage);
     d->positionLat = positionLat;
 }
References positionLat().
setPositionLong()
void CoursePointMessage::setPositionLong (const qint32 positionLong)
Sets the positionLong field to positionLong.
Parameters
positionLong The field value to set.
Definition at line 187 of file coursepointmessage.cpp.
 {
     Q_D(CoursePointMessage);
     d->positionLong = positionLong;
 }
References positionLong().
setTimestamp()
void CoursePointMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 167 of file coursepointmessage.cpp.
 {
     Q_D(CoursePointMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setType()
void CoursePointMessage::setType (const CoursePoint type)
Sets the type field to type.
Parameters
type The field value to set.
Definition at line 207 of file coursepointmessage.cpp.
 {
     Q_D(CoursePointMessage);
     d->type = type;
 }
References type().
timestamp()
DateTime CoursePointMessage::timestamp () const
Returns the CoursePointMessage data message's timestamp field's current value.
Returns
the timestamp field value.
Definition at line 80 of file coursepointmessage.cpp.
 {
     Q_D(const CoursePointMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
type()
CoursePoint CoursePointMessage::type () const
Returns the CoursePointMessage data message's type field's current value.
Returns
the type field value.
Definition at line 124 of file coursepointmessage.cpp.
 {
     Q_D(const CoursePointMessage);
     return d->type;
 }
Referenced by setType().
The documentation for this class was generated from the following files:
coursepointmessage.h
coursepointmessage.cpp