QtFit: SegmentIdMessage Class Reference
SegmentIdMessage Class Reference
The SegmentIdMessage class represents a FIT SegmentIdMessage data message.
Public Member Functions
SegmentIdMessage ()
Constructs a SegmentIdMessage object.
QString name () const
Returns the SegmentIdMessage data message's name field's current value.
QString uuid () const
Returns the SegmentIdMessage data message's uuid field's current value.
Sport sport () const
Returns the SegmentIdMessage data message's sport field's current value.
bool enabled () const
Returns the SegmentIdMessage data message's enabled field's current value.
quint32 userProfilePrimaryKey () const
Returns the SegmentIdMessage data message's userProfilePrimaryKey field's current value.
quint32 deviceId () const
Returns the SegmentIdMessage data message's deviceId field's current value.
quint8 defaultRaceLeader () const
Returns the SegmentIdMessage data message's defaultRaceLeader field's current value.
SegmentDeleteStatus deleteStatus () const
Returns the SegmentIdMessage data message's deleteStatus field's current value.
SegmentSelectionType selectionType () const
Returns the SegmentIdMessage data message's selectionType field's current value.
void setName (const QString name)
Sets the name field to name.
void setUuid (const QString uuid)
Sets the uuid field to uuid.
void setSport (const Sport sport)
Sets the sport field to sport.
void setEnabled (const bool enabled)
Sets the enabled field to enabled.
void setUserProfilePrimaryKey (const quint32 userProfilePrimaryKey)
Sets the userProfilePrimaryKey field to userProfilePrimaryKey.
void setDeviceId (const quint32 deviceId)
Sets the deviceId field to deviceId.
void setDefaultRaceLeader (const quint8 defaultRaceLeader)
Sets the defaultRaceLeader field to defaultRaceLeader.
void setDeleteStatus (const SegmentDeleteStatus deleteStatus)
Sets the deleteStatus field to deleteStatus.
void setSelectionType (const SegmentSelectionType selectionType)
Sets the selectionType field to selectionType.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
SegmentIdMessage (SegmentIdMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The SegmentIdMessage class represents a FIT SegmentIdMessage data message.
See also
DataMessage
Definition at line 39 of file segmentidmessage.h.
Constructor & Destructor Documentation
SegmentIdMessage() [1/2]
SegmentIdMessage::SegmentIdMessage ()
Constructs a SegmentIdMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file segmentidmessage.cpp.
                                    : AbstractDataMessage(new SegmentIdMessagePrivate(this))
 {
 }
SegmentIdMessage() [2/2]
SegmentIdMessage::SegmentIdMessage (SegmentIdMessagePrivate *const d) explicit protected
Constructs a SegmentIdMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file segmentidmessage.cpp.
                                                                     : AbstractDataMessage(d)
 {
 }
Member Function Documentation
defaultRaceLeader()
quint8 SegmentIdMessage::defaultRaceLeader () const
Returns the SegmentIdMessage data message's defaultRaceLeader field's current value.
Index for the Leader Board entry selected as the default race participant
Returns
the defaultRaceLeader field value.
Definition at line 154 of file segmentidmessage.cpp.
 {
     Q_D(const SegmentIdMessage);
     return d->defaultRaceLeader;
 }
Referenced by setDefaultRaceLeader().
deleteStatus()
SegmentDeleteStatus SegmentIdMessage::deleteStatus () const
Returns the SegmentIdMessage data message's deleteStatus field's current value.
Indicates if any segments should be deleted
Returns
the deleteStatus field value.
Definition at line 167 of file segmentidmessage.cpp.
 {
     Q_D(const SegmentIdMessage);
     return d->deleteStatus;
 }
Referenced by setDeleteStatus().
deviceId()
quint32 SegmentIdMessage::deviceId () const
Returns the SegmentIdMessage data message's deviceId field's current value.
ID of the device that created the segment
Returns
the deviceId field value.
Definition at line 141 of file segmentidmessage.cpp.
 {
     Q_D(const SegmentIdMessage);
     return d->deviceId;
 }
Referenced by setDeviceId().
enabled()
bool SegmentIdMessage::enabled () const
Returns the SegmentIdMessage data message's enabled field's current value.
Segment enabled for evaluation
Returns
the enabled field value.
Definition at line 115 of file segmentidmessage.cpp.
 {
     Q_D(const SegmentIdMessage);
     return d->enabled;
 }
Referenced by setEnabled().
name()
QString SegmentIdMessage::name () const
Returns the SegmentIdMessage data message's name field's current value.
Friendly name assigned to segment
Returns
the name field value.
Definition at line 76 of file segmentidmessage.cpp.
 {
     Q_D(const SegmentIdMessage);
     return d->name;
 }
Referenced by setName().
selectionType()
SegmentSelectionType SegmentIdMessage::selectionType () const
Returns the SegmentIdMessage data message's selectionType field's current value.
Indicates how the segment was selected to be sent to the device
Returns
the selectionType field value.
Definition at line 180 of file segmentidmessage.cpp.
 {
     Q_D(const SegmentIdMessage);
     return d->selectionType;
 }
Referenced by setSelectionType().
setDefaultRaceLeader()
void SegmentIdMessage::setDefaultRaceLeader (const quint8 defaultRaceLeader)
Sets the defaultRaceLeader field to defaultRaceLeader.
Parameters
defaultRaceLeader The field value to set.
Definition at line 251 of file segmentidmessage.cpp.
 {
     Q_D(SegmentIdMessage);
     d->defaultRaceLeader = defaultRaceLeader;
 }
References defaultRaceLeader().
setDeleteStatus()
void SegmentIdMessage::setDeleteStatus (const SegmentDeleteStatus deleteStatus)
Sets the deleteStatus field to deleteStatus.
Parameters
deleteStatus The field value to set.
Definition at line 261 of file segmentidmessage.cpp.
 {
     Q_D(SegmentIdMessage);
     d->deleteStatus = deleteStatus;
 }
References deleteStatus().
setDeviceId()
void SegmentIdMessage::setDeviceId (const quint32 deviceId)
Sets the deviceId field to deviceId.
Parameters
deviceId The field value to set.
Definition at line 241 of file segmentidmessage.cpp.
 {
     Q_D(SegmentIdMessage);
     d->deviceId = deviceId;
 }
References deviceId().
setEnabled()
void SegmentIdMessage::setEnabled (const bool enabled)
Sets the enabled field to enabled.
Parameters
enabled The field value to set.
Definition at line 221 of file segmentidmessage.cpp.
 {
     Q_D(SegmentIdMessage);
     d->enabled = enabled;
 }
References enabled().
setName()
void SegmentIdMessage::setName (const QString name)
Sets the name field to name.
Parameters
name The field value to set.
Definition at line 191 of file segmentidmessage.cpp.
 {
     Q_D(SegmentIdMessage);
     d->name = name;
 }
References name().
setSelectionType()
void SegmentIdMessage::setSelectionType (const SegmentSelectionType selectionType)
Sets the selectionType field to selectionType.
Parameters
selectionType The field value to set.
Definition at line 271 of file segmentidmessage.cpp.
 {
     Q_D(SegmentIdMessage);
     d->selectionType = selectionType;
 }
References selectionType().
setSport()
void SegmentIdMessage::setSport (const Sport sport)
Sets the sport field to sport.
Parameters
sport The field value to set.
Definition at line 211 of file segmentidmessage.cpp.
 {
     Q_D(SegmentIdMessage);
     d->sport = sport;
 }
References sport().
setUserProfilePrimaryKey()
void SegmentIdMessage::setUserProfilePrimaryKey (const quint32 userProfilePrimaryKey)
Sets the userProfilePrimaryKey field to userProfilePrimaryKey.
Parameters
userProfilePrimaryKey The field value to set.
Definition at line 231 of file segmentidmessage.cpp.
 {
     Q_D(SegmentIdMessage);
     d->userProfilePrimaryKey = userProfilePrimaryKey;
 }
References userProfilePrimaryKey().
setUuid()
void SegmentIdMessage::setUuid (const QString uuid)
Sets the uuid field to uuid.
Parameters
uuid The field value to set.
Definition at line 201 of file segmentidmessage.cpp.
 {
     Q_D(SegmentIdMessage);
     d->uuid = uuid;
 }
References uuid().
sport()
Sport SegmentIdMessage::sport () const
Returns the SegmentIdMessage data message's sport field's current value.
Sport associated with the segment
Returns
the sport field value.
Definition at line 102 of file segmentidmessage.cpp.
 {
     Q_D(const SegmentIdMessage);
     return d->sport;
 }
Referenced by setSport().
userProfilePrimaryKey()
quint32 SegmentIdMessage::userProfilePrimaryKey () const
Returns the SegmentIdMessage data message's userProfilePrimaryKey field's current value.
Primary key of the user that created the segment
Returns
the userProfilePrimaryKey field value.
Definition at line 128 of file segmentidmessage.cpp.
 {
     Q_D(const SegmentIdMessage);
     return d->userProfilePrimaryKey;
 }
Referenced by setUserProfilePrimaryKey().
uuid()
QString SegmentIdMessage::uuid () const
Returns the SegmentIdMessage data message's uuid field's current value.
UUID of the segment
Returns
the uuid field value.
Definition at line 89 of file segmentidmessage.cpp.
 {
     Q_D(const SegmentIdMessage);
     return d->uuid;
 }
Referenced by setUuid().
The documentation for this class was generated from the following files:
segmentidmessage.h
segmentidmessage.cpp