QtFit: LengthMessage Class Reference
LengthMessage Class Reference
The LengthMessage class represents a FIT LengthMessage data message.
Public Member Functions
LengthMessage ()
Constructs a LengthMessage object.
MessageIndex messageIndex () const
Returns the LengthMessage data message's messageIndex field's current value.
DateTime timestamp () const
Returns the LengthMessage data message's timestamp field's current value.
Event event () const
Returns the LengthMessage data message's event field's current value.
EventType eventType () const
Returns the LengthMessage data message's eventType field's current value.
DateTime startTime () const
Returns the LengthMessage data message's startTime field's current value.
quint32 totalElapsedTime () const
Returns the LengthMessage data message's totalElapsedTime field's current value.
quint32 totalTimerTime () const
Returns the LengthMessage data message's totalTimerTime field's current value.
quint16 totalStrokes () const
Returns the LengthMessage data message's totalStrokes field's current value.
quint16 avgSpeed () const
Returns the LengthMessage data message's avgSpeed field's current value.
SwimStroke swimStroke () const
Returns the LengthMessage data message's swimStroke field's current value.
quint8 avgSwimmingCadence () const
Returns the LengthMessage data message's avgSwimmingCadence field's current value.
quint8 eventGroup () const
Returns the LengthMessage data message's eventGroup field's current value.
quint16 totalCalories () const
Returns the LengthMessage data message's totalCalories field's current value.
LengthType lengthType () const
Returns the LengthMessage data message's lengthType field's current value.
quint16 playerScore () const
Returns the LengthMessage data message's playerScore field's current value.
quint16 opponentScore () const
Returns the LengthMessage data message's opponentScore field's current value.
quint16 strokeCount () const
Returns the LengthMessage data message's strokeCount field's current value.
quint16 zoneCount () const
Returns the LengthMessage data message's zoneCount field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setEvent (const Event event)
Sets the event field to event.
void setEventType (const EventType eventType)
Sets the eventType field to eventType.
void setStartTime (const DateTime startTime)
Sets the startTime field to startTime.
void setTotalElapsedTime (const quint32 totalElapsedTime)
Sets the totalElapsedTime field to totalElapsedTime.
void setTotalTimerTime (const quint32 totalTimerTime)
Sets the totalTimerTime field to totalTimerTime.
void setTotalStrokes (const quint16 totalStrokes)
Sets the totalStrokes field to totalStrokes.
void setAvgSpeed (const quint16 avgSpeed)
Sets the avgSpeed field to avgSpeed.
void setSwimStroke (const SwimStroke swimStroke)
Sets the swimStroke field to swimStroke.
void setAvgSwimmingCadence (const quint8 avgSwimmingCadence)
Sets the avgSwimmingCadence field to avgSwimmingCadence.
void setEventGroup (const quint8 eventGroup)
Sets the eventGroup field to eventGroup.
void setTotalCalories (const quint16 totalCalories)
Sets the totalCalories field to totalCalories.
void setLengthType (const LengthType lengthType)
Sets the lengthType field to lengthType.
void setPlayerScore (const quint16 playerScore)
Sets the playerScore field to playerScore.
void setOpponentScore (const quint16 opponentScore)
Sets the opponentScore field to opponentScore.
void setStrokeCount (const quint16 strokeCount)
Sets the strokeCount field to strokeCount.
void setZoneCount (const quint16 zoneCount)
Sets the zoneCount field to zoneCount.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
LengthMessage (LengthMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The LengthMessage class represents a FIT LengthMessage data message.
See also
DataMessage
Definition at line 39 of file lengthmessage.h.
Constructor & Destructor Documentation
LengthMessage() [1/2]
LengthMessage::LengthMessage ()
Constructs a LengthMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file lengthmessage.cpp.
                              : AbstractDataMessage(new LengthMessagePrivate(this))
 {
 }
LengthMessage() [2/2]
LengthMessage::LengthMessage (LengthMessagePrivate *const d) explicit protected
Constructs a LengthMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file lengthmessage.cpp.
                                                            : AbstractDataMessage(d)
 {
 }
Member Function Documentation
avgSpeed()
quint16 LengthMessage::avgSpeed () const
Returns the LengthMessage data message's avgSpeed field's current value.
Returns
the avgSpeed field value.
Definition at line 162 of file lengthmessage.cpp.
 {
     Q_D(const LengthMessage);
     return d->avgSpeed;
 }
Referenced by setAvgSpeed().
avgSwimmingCadence()
quint8 LengthMessage::avgSwimmingCadence () const
Returns the LengthMessage data message's avgSwimmingCadence field's current value.
Returns
the avgSwimmingCadence field value.
Definition at line 184 of file lengthmessage.cpp.
 {
     Q_D(const LengthMessage);
     return d->avgSwimmingCadence;
 }
Referenced by setAvgSwimmingCadence().
event()
Event LengthMessage::event () const
Returns the LengthMessage data message's event field's current value.
Returns
the event field value.
Definition at line 96 of file lengthmessage.cpp.
 {
     Q_D(const LengthMessage);
     return d->event;
 }
Referenced by setEvent().
eventGroup()
quint8 LengthMessage::eventGroup () const
Returns the LengthMessage data message's eventGroup field's current value.
Returns
the eventGroup field value.
Definition at line 195 of file lengthmessage.cpp.
 {
     Q_D(const LengthMessage);
     return d->eventGroup;
 }
Referenced by setEventGroup().
eventType()
EventType LengthMessage::eventType () const
Returns the LengthMessage data message's eventType field's current value.
Returns
the eventType field value.
Definition at line 107 of file lengthmessage.cpp.
 {
     Q_D(const LengthMessage);
     return d->eventType;
 }
Referenced by setEventType().
lengthType()
LengthType LengthMessage::lengthType () const
Returns the LengthMessage data message's lengthType field's current value.
Returns
the lengthType field value.
Definition at line 217 of file lengthmessage.cpp.
 {
     Q_D(const LengthMessage);
     return d->lengthType;
 }
Referenced by setLengthType().
messageIndex()
MessageIndex LengthMessage::messageIndex () const
Returns the LengthMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 74 of file lengthmessage.cpp.
 {
     Q_D(const LengthMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
opponentScore()
quint16 LengthMessage::opponentScore () const
Returns the LengthMessage data message's opponentScore field's current value.
Returns
the opponentScore field value.
Definition at line 239 of file lengthmessage.cpp.
 {
     Q_D(const LengthMessage);
     return d->opponentScore;
 }
Referenced by setOpponentScore().
playerScore()
quint16 LengthMessage::playerScore () const
Returns the LengthMessage data message's playerScore field's current value.
Returns
the playerScore field value.
Definition at line 228 of file lengthmessage.cpp.
 {
     Q_D(const LengthMessage);
     return d->playerScore;
 }
Referenced by setPlayerScore().
setAvgSpeed()
void LengthMessage::setAvgSpeed (const quint16 avgSpeed)
Sets the avgSpeed field to avgSpeed.
Parameters
avgSpeed The field value to set.
Definition at line 356 of file lengthmessage.cpp.
 {
     Q_D(LengthMessage);
     d->avgSpeed = avgSpeed;
 }
References avgSpeed().
setAvgSwimmingCadence()
void LengthMessage::setAvgSwimmingCadence (const quint8 avgSwimmingCadence)
Sets the avgSwimmingCadence field to avgSwimmingCadence.
Parameters
avgSwimmingCadence The field value to set.
Definition at line 376 of file lengthmessage.cpp.
 {
     Q_D(LengthMessage);
     d->avgSwimmingCadence = avgSwimmingCadence;
 }
References avgSwimmingCadence().
setEvent()
void LengthMessage::setEvent (const Event event)
Sets the event field to event.
Parameters
event The field value to set.
Definition at line 296 of file lengthmessage.cpp.
 {
     Q_D(LengthMessage);
     d->event = event;
 }
References event().
setEventGroup()
void LengthMessage::setEventGroup (const quint8 eventGroup)
Sets the eventGroup field to eventGroup.
Parameters
eventGroup The field value to set.
Definition at line 386 of file lengthmessage.cpp.
 {
     Q_D(LengthMessage);
     d->eventGroup = eventGroup;
 }
References eventGroup().
setEventType()
void LengthMessage::setEventType (const EventType eventType)
Sets the eventType field to eventType.
Parameters
eventType The field value to set.
Definition at line 306 of file lengthmessage.cpp.
 {
     Q_D(LengthMessage);
     d->eventType = eventType;
 }
References eventType().
setLengthType()
void LengthMessage::setLengthType (const LengthType lengthType)
Sets the lengthType field to lengthType.
Parameters
lengthType The field value to set.
Definition at line 406 of file lengthmessage.cpp.
 {
     Q_D(LengthMessage);
     d->lengthType = lengthType;
 }
References lengthType().
setMessageIndex()
void LengthMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 276 of file lengthmessage.cpp.
 {
     Q_D(LengthMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setOpponentScore()
void LengthMessage::setOpponentScore (const quint16 opponentScore)
Sets the opponentScore field to opponentScore.
Parameters
opponentScore The field value to set.
Definition at line 426 of file lengthmessage.cpp.
 {
     Q_D(LengthMessage);
     d->opponentScore = opponentScore;
 }
References opponentScore().
setPlayerScore()
void LengthMessage::setPlayerScore (const quint16 playerScore)
Sets the playerScore field to playerScore.
Parameters
playerScore The field value to set.
Definition at line 416 of file lengthmessage.cpp.
 {
     Q_D(LengthMessage);
     d->playerScore = playerScore;
 }
References playerScore().
setStartTime()
void LengthMessage::setStartTime (const DateTime startTime)
Sets the startTime field to startTime.
Parameters
startTime The field value to set.
Definition at line 316 of file lengthmessage.cpp.
 {
     Q_D(LengthMessage);
     d->startTime = startTime;
 }
References startTime().
setStrokeCount()
void LengthMessage::setStrokeCount (const quint16 strokeCount)
Sets the strokeCount field to strokeCount.
Parameters
strokeCount The field value to set.
Definition at line 436 of file lengthmessage.cpp.
 {
     Q_D(LengthMessage);
     d->strokeCount = strokeCount;
 }
References strokeCount().
setSwimStroke()
void LengthMessage::setSwimStroke (const SwimStroke swimStroke)
Sets the swimStroke field to swimStroke.
Parameters
swimStroke The field value to set.
Definition at line 366 of file lengthmessage.cpp.
 {
     Q_D(LengthMessage);
     d->swimStroke = swimStroke;
 }
References swimStroke().
setTimestamp()
void LengthMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 286 of file lengthmessage.cpp.
 {
     Q_D(LengthMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setTotalCalories()
void LengthMessage::setTotalCalories (const quint16 totalCalories)
Sets the totalCalories field to totalCalories.
Parameters
totalCalories The field value to set.
Definition at line 396 of file lengthmessage.cpp.
 {
     Q_D(LengthMessage);
     d->totalCalories = totalCalories;
 }
References totalCalories().
setTotalElapsedTime()
void LengthMessage::setTotalElapsedTime (const quint32 totalElapsedTime)
Sets the totalElapsedTime field to totalElapsedTime.
Parameters
totalElapsedTime The field value to set.
Definition at line 326 of file lengthmessage.cpp.
 {
     Q_D(LengthMessage);
     d->totalElapsedTime = totalElapsedTime;
 }
References totalElapsedTime().
setTotalStrokes()
void LengthMessage::setTotalStrokes (const quint16 totalStrokes)
Sets the totalStrokes field to totalStrokes.
Parameters
totalStrokes The field value to set.
Definition at line 346 of file lengthmessage.cpp.
 {
     Q_D(LengthMessage);
     d->totalStrokes = totalStrokes;
 }
References totalStrokes().
setTotalTimerTime()
void LengthMessage::setTotalTimerTime (const quint32 totalTimerTime)
Sets the totalTimerTime field to totalTimerTime.
Parameters
totalTimerTime The field value to set.
Definition at line 336 of file lengthmessage.cpp.
 {
     Q_D(LengthMessage);
     d->totalTimerTime = totalTimerTime;
 }
References totalTimerTime().
setZoneCount()
void LengthMessage::setZoneCount (const quint16 zoneCount)
Sets the zoneCount field to zoneCount.
Parameters
zoneCount The field value to set.
Definition at line 446 of file lengthmessage.cpp.
 {
     Q_D(LengthMessage);
     d->zoneCount = zoneCount;
 }
References zoneCount().
startTime()
DateTime LengthMessage::startTime () const
Returns the LengthMessage data message's startTime field's current value.
Returns
the startTime field value.
Definition at line 118 of file lengthmessage.cpp.
 {
     Q_D(const LengthMessage);
     return d->startTime;
 }
Referenced by setStartTime().
strokeCount()
quint16 LengthMessage::strokeCount () const
Returns the LengthMessage data message's strokeCount field's current value.
stroke_type enum used as the index
Returns
the strokeCount field value.
Definition at line 252 of file lengthmessage.cpp.
 {
     Q_D(const LengthMessage);
     return d->strokeCount;
 }
Referenced by setStrokeCount().
swimStroke()
SwimStroke LengthMessage::swimStroke () const
Returns the LengthMessage data message's swimStroke field's current value.
Returns
the swimStroke field value.
Definition at line 173 of file lengthmessage.cpp.
 {
     Q_D(const LengthMessage);
     return d->swimStroke;
 }
Referenced by setSwimStroke().
timestamp()
DateTime LengthMessage::timestamp () const
Returns the LengthMessage data message's timestamp field's current value.
Returns
the timestamp field value.
Definition at line 85 of file lengthmessage.cpp.
 {
     Q_D(const LengthMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
totalCalories()
quint16 LengthMessage::totalCalories () const
Returns the LengthMessage data message's totalCalories field's current value.
Returns
the totalCalories field value.
Definition at line 206 of file lengthmessage.cpp.
 {
     Q_D(const LengthMessage);
     return d->totalCalories;
 }
Referenced by setTotalCalories().
totalElapsedTime()
quint32 LengthMessage::totalElapsedTime () const
Returns the LengthMessage data message's totalElapsedTime field's current value.
Returns
the totalElapsedTime field value.
Definition at line 129 of file lengthmessage.cpp.
 {
     Q_D(const LengthMessage);
     return d->totalElapsedTime;
 }
Referenced by setTotalElapsedTime().
totalStrokes()
quint16 LengthMessage::totalStrokes () const
Returns the LengthMessage data message's totalStrokes field's current value.
Returns
the totalStrokes field value.
Definition at line 151 of file lengthmessage.cpp.
 {
     Q_D(const LengthMessage);
     return d->totalStrokes;
 }
Referenced by setTotalStrokes().
totalTimerTime()
quint32 LengthMessage::totalTimerTime () const
Returns the LengthMessage data message's totalTimerTime field's current value.
Returns
the totalTimerTime field value.
Definition at line 140 of file lengthmessage.cpp.
 {
     Q_D(const LengthMessage);
     return d->totalTimerTime;
 }
Referenced by setTotalTimerTime().
zoneCount()
quint16 LengthMessage::zoneCount () const
Returns the LengthMessage data message's zoneCount field's current value.
zone number used as the index
Returns
the zoneCount field value.
Definition at line 265 of file lengthmessage.cpp.
 {
     Q_D(const LengthMessage);
     return d->zoneCount;
 }
Referenced by setZoneCount().
The documentation for this class was generated from the following files:
lengthmessage.h
lengthmessage.cpp