QtFit: SlaveDeviceMessage Class Reference
SlaveDeviceMessage Class Reference
The SlaveDeviceMessage class represents a FIT SlaveDeviceMessage data message.
Public Member Functions
SlaveDeviceMessage ()
Constructs a SlaveDeviceMessage object.
Manufacturer manufacturer () const
Returns the SlaveDeviceMessage data message's manufacturer field's current value.
quint16 product () const
Returns the SlaveDeviceMessage data message's product field's current value.
void setManufacturer (const Manufacturer manufacturer)
Sets the manufacturer field to manufacturer.
void setProduct (const quint16 product)
Sets the product field to product.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
SlaveDeviceMessage (SlaveDeviceMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The SlaveDeviceMessage class represents a FIT SlaveDeviceMessage data message.
See also
DataMessage
Definition at line 34 of file slavedevicemessage.h.
Constructor & Destructor Documentation
SlaveDeviceMessage() [1/2]
SlaveDeviceMessage::SlaveDeviceMessage ()
Constructs a SlaveDeviceMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file slavedevicemessage.cpp.
                                        : AbstractDataMessage(new SlaveDeviceMessagePrivate(this))
 {
 }
SlaveDeviceMessage() [2/2]
SlaveDeviceMessage::SlaveDeviceMessage (SlaveDeviceMessagePrivate *const d) explicit protected
Constructs a SlaveDeviceMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file slavedevicemessage.cpp.
                                                                           : AbstractDataMessage(d)
 {
 }
Member Function Documentation
manufacturer()
Manufacturer SlaveDeviceMessage::manufacturer () const
Returns the SlaveDeviceMessage data message's manufacturer field's current value.
Returns
the manufacturer field value.
Definition at line 69 of file slavedevicemessage.cpp.
 {
     Q_D(const SlaveDeviceMessage);
     return d->manufacturer;
 }
Referenced by setManufacturer().
product()
quint16 SlaveDeviceMessage::product () const
Returns the SlaveDeviceMessage data message's product field's current value.
Returns
the product field value.
Definition at line 80 of file slavedevicemessage.cpp.
 {
     Q_D(const SlaveDeviceMessage);
     return d->product;
 }
Referenced by setProduct().
setManufacturer()
void SlaveDeviceMessage::setManufacturer (const Manufacturer manufacturer)
Sets the manufacturer field to manufacturer.
Parameters
manufacturer The field value to set.
Definition at line 91 of file slavedevicemessage.cpp.
 {
     Q_D(SlaveDeviceMessage);
     d->manufacturer = manufacturer;
 }
References manufacturer().
setProduct()
void SlaveDeviceMessage::setProduct (const quint16 product)
Sets the product field to product.
Parameters
product The field value to set.
Definition at line 101 of file slavedevicemessage.cpp.
 {
     Q_D(SlaveDeviceMessage);
     d->product = product;
 }
References product().
The documentation for this class was generated from the following files:
slavedevicemessage.h
slavedevicemessage.cpp