QtFit: WorkoutMessage Class Reference
WorkoutMessage Class Reference
The WorkoutMessage class represents a FIT WorkoutMessage data message.
Public Member Functions
WorkoutMessage ()
Constructs a WorkoutMessage object.
Sport sport () const
Returns the WorkoutMessage data message's sport field's current value.
WorkoutCapabilities capabilities () const
Returns the WorkoutMessage data message's capabilities field's current value.
quint16 numValidSteps () const
Returns the WorkoutMessage data message's numValidSteps field's current value.
QString wktName () const
Returns the WorkoutMessage data message's wktName field's current value.
SubSport subSport () const
Returns the WorkoutMessage data message's subSport field's current value.
quint16 poolLength () const
Returns the WorkoutMessage data message's poolLength field's current value.
DisplayMeasure poolLengthUnit () const
Returns the WorkoutMessage data message's poolLengthUnit field's current value.
void setSport (const Sport sport)
Sets the sport field to sport.
void setCapabilities (const WorkoutCapabilities capabilities)
Sets the capabilities field to capabilities.
void setNumValidSteps (const quint16 numValidSteps)
Sets the numValidSteps field to numValidSteps.
void setWktName (const QString wktName)
Sets the wktName field to wktName.
void setSubSport (const SubSport subSport)
Sets the subSport field to subSport.
void setPoolLength (const quint16 poolLength)
Sets the poolLength field to poolLength.
void setPoolLengthUnit (const DisplayMeasure poolLengthUnit)
Sets the poolLengthUnit field to poolLengthUnit.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
WorkoutMessage (WorkoutMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The WorkoutMessage class represents a FIT WorkoutMessage data message.
See also
DataMessage
Definition at line 34 of file workoutmessage.h.
Constructor & Destructor Documentation
WorkoutMessage() [1/2]
WorkoutMessage::WorkoutMessage ()
Constructs a WorkoutMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file workoutmessage.cpp.
                                : AbstractDataMessage(new WorkoutMessagePrivate(this))
 {
 }
WorkoutMessage() [2/2]
WorkoutMessage::WorkoutMessage (WorkoutMessagePrivate *const d) explicit protected
Constructs a WorkoutMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file workoutmessage.cpp.
                                                               : AbstractDataMessage(d)
 {
 }
Member Function Documentation
capabilities()
WorkoutCapabilities WorkoutMessage::capabilities () const
Returns the WorkoutMessage data message's capabilities field's current value.
Returns
the capabilities field value.
Definition at line 80 of file workoutmessage.cpp.
 {
     Q_D(const WorkoutMessage);
     return d->capabilities;
 }
Referenced by setCapabilities().
numValidSteps()
quint16 WorkoutMessage::numValidSteps () const
Returns the WorkoutMessage data message's numValidSteps field's current value.
number of valid steps
Returns
the numValidSteps field value.
Definition at line 93 of file workoutmessage.cpp.
 {
     Q_D(const WorkoutMessage);
     return d->numValidSteps;
 }
Referenced by setNumValidSteps().
poolLength()
quint16 WorkoutMessage::poolLength () const
Returns the WorkoutMessage data message's poolLength field's current value.
Returns
the poolLength field value.
Definition at line 126 of file workoutmessage.cpp.
 {
     Q_D(const WorkoutMessage);
     return d->poolLength;
 }
Referenced by setPoolLength().
poolLengthUnit()
DisplayMeasure WorkoutMessage::poolLengthUnit () const
Returns the WorkoutMessage data message's poolLengthUnit field's current value.
Returns
the poolLengthUnit field value.
Definition at line 137 of file workoutmessage.cpp.
 {
     Q_D(const WorkoutMessage);
     return d->poolLengthUnit;
 }
Referenced by setPoolLengthUnit().
setCapabilities()
void WorkoutMessage::setCapabilities (const WorkoutCapabilities capabilities)
Sets the capabilities field to capabilities.
Parameters
capabilities The field value to set.
Definition at line 158 of file workoutmessage.cpp.
 {
     Q_D(WorkoutMessage);
     d->capabilities = capabilities;
 }
References capabilities().
setNumValidSteps()
void WorkoutMessage::setNumValidSteps (const quint16 numValidSteps)
Sets the numValidSteps field to numValidSteps.
Parameters
numValidSteps The field value to set.
Definition at line 168 of file workoutmessage.cpp.
 {
     Q_D(WorkoutMessage);
     d->numValidSteps = numValidSteps;
 }
References numValidSteps().
setPoolLength()
void WorkoutMessage::setPoolLength (const quint16 poolLength)
Sets the poolLength field to poolLength.
Parameters
poolLength The field value to set.
Definition at line 198 of file workoutmessage.cpp.
 {
     Q_D(WorkoutMessage);
     d->poolLength = poolLength;
 }
References poolLength().
setPoolLengthUnit()
void WorkoutMessage::setPoolLengthUnit (const DisplayMeasure poolLengthUnit)
Sets the poolLengthUnit field to poolLengthUnit.
Parameters
poolLengthUnit The field value to set.
Definition at line 208 of file workoutmessage.cpp.
 {
     Q_D(WorkoutMessage);
     d->poolLengthUnit = poolLengthUnit;
 }
References poolLengthUnit().
setSport()
void WorkoutMessage::setSport (const Sport sport)
Sets the sport field to sport.
Parameters
sport The field value to set.
Definition at line 148 of file workoutmessage.cpp.
 {
     Q_D(WorkoutMessage);
     d->sport = sport;
 }
References sport().
setSubSport()
void WorkoutMessage::setSubSport (const SubSport subSport)
Sets the subSport field to subSport.
Parameters
subSport The field value to set.
Definition at line 188 of file workoutmessage.cpp.
 {
     Q_D(WorkoutMessage);
     d->subSport = subSport;
 }
References subSport().
setWktName()
void WorkoutMessage::setWktName (const QString wktName)
Sets the wktName field to wktName.
Parameters
wktName The field value to set.
Definition at line 178 of file workoutmessage.cpp.
 {
     Q_D(WorkoutMessage);
     d->wktName = wktName;
 }
References wktName().
sport()
Sport WorkoutMessage::sport () const
Returns the WorkoutMessage data message's sport field's current value.
Returns
the sport field value.
Definition at line 69 of file workoutmessage.cpp.
 {
     Q_D(const WorkoutMessage);
     return d->sport;
 }
Referenced by setSport().
subSport()
SubSport WorkoutMessage::subSport () const
Returns the WorkoutMessage data message's subSport field's current value.
Returns
the subSport field value.
Definition at line 115 of file workoutmessage.cpp.
 {
     Q_D(const WorkoutMessage);
     return d->subSport;
 }
Referenced by setSubSport().
wktName()
QString WorkoutMessage::wktName () const
Returns the WorkoutMessage data message's wktName field's current value.
Returns
the wktName field value.
Definition at line 104 of file workoutmessage.cpp.
 {
     Q_D(const WorkoutMessage);
     return d->wktName;
 }
Referenced by setWktName().
The documentation for this class was generated from the following files:
workoutmessage.h
workoutmessage.cpp