QtFit: GoalMessage Class Reference
GoalMessage Class Reference
The GoalMessage class represents a FIT GoalMessage data message.
Public Member Functions
GoalMessage ()
Constructs a GoalMessage object.
MessageIndex messageIndex () const
Returns the GoalMessage data message's messageIndex field's current value.
Sport sport () const
Returns the GoalMessage data message's sport field's current value.
SubSport subSport () const
Returns the GoalMessage data message's subSport field's current value.
DateTime startDate () const
Returns the GoalMessage data message's startDate field's current value.
DateTime endDate () const
Returns the GoalMessage data message's endDate field's current value.
Goal type () const
Returns the GoalMessage data message's type field's current value.
quint32 value () const
Returns the GoalMessage data message's value field's current value.
bool repeat () const
Returns the GoalMessage data message's repeat field's current value.
quint32 targetValue () const
Returns the GoalMessage data message's targetValue field's current value.
GoalRecurrence recurrence () const
Returns the GoalMessage data message's recurrence field's current value.
quint16 recurrenceValue () const
Returns the GoalMessage data message's recurrenceValue field's current value.
bool enabled () const
Returns the GoalMessage data message's enabled field's current value.
GoalSource source () const
Returns the GoalMessage data message's source field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setSport (const Sport sport)
Sets the sport field to sport.
void setSubSport (const SubSport subSport)
Sets the subSport field to subSport.
void setStartDate (const DateTime startDate)
Sets the startDate field to startDate.
void setEndDate (const DateTime endDate)
Sets the endDate field to endDate.
void setType (const Goal type)
Sets the type field to type.
void setValue (const quint32 value)
Sets the value field to value.
void setRepeat (const bool repeat)
Sets the repeat field to repeat.
void setTargetValue (const quint32 targetValue)
Sets the targetValue field to targetValue.
void setRecurrence (const GoalRecurrence recurrence)
Sets the recurrence field to recurrence.
void setRecurrenceValue (const quint16 recurrenceValue)
Sets the recurrenceValue field to recurrenceValue.
void setEnabled (const bool enabled)
Sets the enabled field to enabled.
void setSource (const GoalSource source)
Sets the source field to source.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
GoalMessage (GoalMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The GoalMessage class represents a FIT GoalMessage data message.
See also
DataMessage
Definition at line 39 of file goalmessage.h.
Constructor & Destructor Documentation
GoalMessage() [1/2]
GoalMessage::GoalMessage ()
Constructs a GoalMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file goalmessage.cpp.
                          : AbstractDataMessage(new GoalMessagePrivate(this))
 {
 }
GoalMessage() [2/2]
GoalMessage::GoalMessage (GoalMessagePrivate *const d) explicit protected
Constructs a GoalMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file goalmessage.cpp.
                                                      : AbstractDataMessage(d)
 {
 }
Member Function Documentation
enabled()
bool GoalMessage::enabled () const
Returns the GoalMessage data message's enabled field's current value.
Returns
the enabled field value.
Definition at line 195 of file goalmessage.cpp.
 {
     Q_D(const GoalMessage);
     return d->enabled;
 }
Referenced by setEnabled().
endDate()
DateTime GoalMessage::endDate () const
Returns the GoalMessage data message's endDate field's current value.
Returns
the endDate field value.
Definition at line 118 of file goalmessage.cpp.
 {
     Q_D(const GoalMessage);
     return d->endDate;
 }
Referenced by setEndDate().
messageIndex()
MessageIndex GoalMessage::messageIndex () const
Returns the GoalMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 74 of file goalmessage.cpp.
 {
     Q_D(const GoalMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
recurrence()
GoalRecurrence GoalMessage::recurrence () const
Returns the GoalMessage data message's recurrence field's current value.
Returns
the recurrence field value.
Definition at line 173 of file goalmessage.cpp.
 {
     Q_D(const GoalMessage);
     return d->recurrence;
 }
Referenced by setRecurrence().
recurrenceValue()
quint16 GoalMessage::recurrenceValue () const
Returns the GoalMessage data message's recurrenceValue field's current value.
Returns
the recurrenceValue field value.
Definition at line 184 of file goalmessage.cpp.
 {
     Q_D(const GoalMessage);
     return d->recurrenceValue;
 }
Referenced by setRecurrenceValue().
repeat()
bool GoalMessage::repeat () const
Returns the GoalMessage data message's repeat field's current value.
Returns
the repeat field value.
Definition at line 151 of file goalmessage.cpp.
 {
     Q_D(const GoalMessage);
     return d->repeat;
 }
Referenced by setRepeat().
setEnabled()
void GoalMessage::setEnabled (const bool enabled)
Sets the enabled field to enabled.
Parameters
enabled The field value to set.
Definition at line 327 of file goalmessage.cpp.
 {
     Q_D(GoalMessage);
     d->enabled = enabled;
 }
References enabled().
setEndDate()
void GoalMessage::setEndDate (const DateTime endDate)
Sets the endDate field to endDate.
Parameters
endDate The field value to set.
Definition at line 257 of file goalmessage.cpp.
 {
     Q_D(GoalMessage);
     d->endDate = endDate;
 }
References endDate().
setMessageIndex()
void GoalMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 217 of file goalmessage.cpp.
 {
     Q_D(GoalMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setRecurrence()
void GoalMessage::setRecurrence (const GoalRecurrence recurrence)
Sets the recurrence field to recurrence.
Parameters
recurrence The field value to set.
Definition at line 307 of file goalmessage.cpp.
 {
     Q_D(GoalMessage);
     d->recurrence = recurrence;
 }
References recurrence().
setRecurrenceValue()
void GoalMessage::setRecurrenceValue (const quint16 recurrenceValue)
Sets the recurrenceValue field to recurrenceValue.
Parameters
recurrenceValue The field value to set.
Definition at line 317 of file goalmessage.cpp.
 {
     Q_D(GoalMessage);
     d->recurrenceValue = recurrenceValue;
 }
References recurrenceValue().
setRepeat()
void GoalMessage::setRepeat (const bool repeat)
Sets the repeat field to repeat.
Parameters
repeat The field value to set.
Definition at line 287 of file goalmessage.cpp.
 {
     Q_D(GoalMessage);
     d->repeat = repeat;
 }
References repeat().
setSource()
void GoalMessage::setSource (const GoalSource source)
Sets the source field to source.
Parameters
source The field value to set.
Definition at line 337 of file goalmessage.cpp.
 {
     Q_D(GoalMessage);
     d->source = source;
 }
References source().
setSport()
void GoalMessage::setSport (const Sport sport)
Sets the sport field to sport.
Parameters
sport The field value to set.
Definition at line 227 of file goalmessage.cpp.
 {
     Q_D(GoalMessage);
     d->sport = sport;
 }
References sport().
setStartDate()
void GoalMessage::setStartDate (const DateTime startDate)
Sets the startDate field to startDate.
Parameters
startDate The field value to set.
Definition at line 247 of file goalmessage.cpp.
 {
     Q_D(GoalMessage);
     d->startDate = startDate;
 }
References startDate().
setSubSport()
void GoalMessage::setSubSport (const SubSport subSport)
Sets the subSport field to subSport.
Parameters
subSport The field value to set.
Definition at line 237 of file goalmessage.cpp.
 {
     Q_D(GoalMessage);
     d->subSport = subSport;
 }
References subSport().
setTargetValue()
void GoalMessage::setTargetValue (const quint32 targetValue)
Sets the targetValue field to targetValue.
Parameters
targetValue The field value to set.
Definition at line 297 of file goalmessage.cpp.
 {
     Q_D(GoalMessage);
     d->targetValue = targetValue;
 }
References targetValue().
setType()
void GoalMessage::setType (const Goal type)
Sets the type field to type.
Parameters
type The field value to set.
Definition at line 267 of file goalmessage.cpp.
 {
     Q_D(GoalMessage);
     d->type = type;
 }
References type().
setValue()
void GoalMessage::setValue (const quint32 value)
Sets the value field to value.
Parameters
value The field value to set.
Definition at line 277 of file goalmessage.cpp.
 {
     Q_D(GoalMessage);
     d->value = value;
 }
References value().
source()
GoalSource GoalMessage::source () const
Returns the GoalMessage data message's source field's current value.
Returns
the source field value.
Definition at line 206 of file goalmessage.cpp.
 {
     Q_D(const GoalMessage);
     return d->source;
 }
Referenced by setSource().
sport()
Sport GoalMessage::sport () const
Returns the GoalMessage data message's sport field's current value.
Returns
the sport field value.
Definition at line 85 of file goalmessage.cpp.
 {
     Q_D(const GoalMessage);
     return d->sport;
 }
Referenced by setSport().
startDate()
DateTime GoalMessage::startDate () const
Returns the GoalMessage data message's startDate field's current value.
Returns
the startDate field value.
Definition at line 107 of file goalmessage.cpp.
 {
     Q_D(const GoalMessage);
     return d->startDate;
 }
Referenced by setStartDate().
subSport()
SubSport GoalMessage::subSport () const
Returns the GoalMessage data message's subSport field's current value.
Returns
the subSport field value.
Definition at line 96 of file goalmessage.cpp.
 {
     Q_D(const GoalMessage);
     return d->subSport;
 }
Referenced by setSubSport().
targetValue()
quint32 GoalMessage::targetValue () const
Returns the GoalMessage data message's targetValue field's current value.
Returns
the targetValue field value.
Definition at line 162 of file goalmessage.cpp.
 {
     Q_D(const GoalMessage);
     return d->targetValue;
 }
Referenced by setTargetValue().
type()
Goal GoalMessage::type () const
Returns the GoalMessage data message's type field's current value.
Returns
the type field value.
Definition at line 129 of file goalmessage.cpp.
 {
     Q_D(const GoalMessage);
     return d->type;
 }
Referenced by setType().
value()
quint32 GoalMessage::value () const
Returns the GoalMessage data message's value field's current value.
Returns
the value field value.
Definition at line 140 of file goalmessage.cpp.
 {
     Q_D(const GoalMessage);
     return d->value;
 }
Referenced by setValue().
The documentation for this class was generated from the following files:
goalmessage.h
goalmessage.cpp