QtFit: ExerciseTitleMessage Class Reference
ExerciseTitleMessage Class Reference
The ExerciseTitleMessage class represents a FIT ExerciseTitleMessage data message.
Public Member Functions
ExerciseTitleMessage ()
Constructs a ExerciseTitleMessage object.
MessageIndex messageIndex () const
Returns the ExerciseTitleMessage data message's messageIndex field's current value.
ExerciseCategory exerciseCategory () const
Returns the ExerciseTitleMessage data message's exerciseCategory field's current value.
quint16 exerciseName () const
Returns the ExerciseTitleMessage data message's exerciseName field's current value.
QString wktStepName () const
Returns the ExerciseTitleMessage data message's wktStepName field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setExerciseCategory (const ExerciseCategory exerciseCategory)
Sets the exerciseCategory field to exerciseCategory.
void setExerciseName (const quint16 exerciseName)
Sets the exerciseName field to exerciseName.
void setWktStepName (const QString wktStepName)
Sets the wktStepName field to wktStepName.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
ExerciseTitleMessage (ExerciseTitleMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The ExerciseTitleMessage class represents a FIT ExerciseTitleMessage data message.
See also
DataMessage
Definition at line 34 of file exercisetitlemessage.h.
Constructor & Destructor Documentation
ExerciseTitleMessage() [1/2]
ExerciseTitleMessage::ExerciseTitleMessage ()
Constructs a ExerciseTitleMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file exercisetitlemessage.cpp.
                                            : AbstractDataMessage(new ExerciseTitleMessagePrivate(this))
 {
 }
ExerciseTitleMessage() [2/2]
ExerciseTitleMessage::ExerciseTitleMessage (ExerciseTitleMessagePrivate *const d) explicit protected
Constructs a ExerciseTitleMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file exercisetitlemessage.cpp.
                                                                                 : AbstractDataMessage(d)
 {
 }
Member Function Documentation
exerciseCategory()
ExerciseCategory ExerciseTitleMessage::exerciseCategory () const
Returns the ExerciseTitleMessage data message's exerciseCategory field's current value.
Returns
the exerciseCategory field value.
Definition at line 80 of file exercisetitlemessage.cpp.
 {
     Q_D(const ExerciseTitleMessage);
     return d->exerciseCategory;
 }
Referenced by setExerciseCategory().
exerciseName()
quint16 ExerciseTitleMessage::exerciseName () const
Returns the ExerciseTitleMessage data message's exerciseName field's current value.
Returns
the exerciseName field value.
Definition at line 91 of file exercisetitlemessage.cpp.
 {
     Q_D(const ExerciseTitleMessage);
     return d->exerciseName;
 }
Referenced by setExerciseName().
messageIndex()
MessageIndex ExerciseTitleMessage::messageIndex () const
Returns the ExerciseTitleMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 69 of file exercisetitlemessage.cpp.
 {
     Q_D(const ExerciseTitleMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
setExerciseCategory()
void ExerciseTitleMessage::setExerciseCategory (const ExerciseCategory exerciseCategory)
Sets the exerciseCategory field to exerciseCategory.
Parameters
exerciseCategory The field value to set.
Definition at line 123 of file exercisetitlemessage.cpp.
 {
     Q_D(ExerciseTitleMessage);
     d->exerciseCategory = exerciseCategory;
 }
References exerciseCategory().
setExerciseName()
void ExerciseTitleMessage::setExerciseName (const quint16 exerciseName)
Sets the exerciseName field to exerciseName.
Parameters
exerciseName The field value to set.
Definition at line 133 of file exercisetitlemessage.cpp.
 {
     Q_D(ExerciseTitleMessage);
     d->exerciseName = exerciseName;
 }
References exerciseName().
setMessageIndex()
void ExerciseTitleMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 113 of file exercisetitlemessage.cpp.
 {
     Q_D(ExerciseTitleMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setWktStepName()
void ExerciseTitleMessage::setWktStepName (const QString wktStepName)
Sets the wktStepName field to wktStepName.
Parameters
wktStepName The field value to set.
Definition at line 143 of file exercisetitlemessage.cpp.
 {
     Q_D(ExerciseTitleMessage);
     d->wktStepName = wktStepName;
 }
References wktStepName().
wktStepName()
QString ExerciseTitleMessage::wktStepName () const
Returns the ExerciseTitleMessage data message's wktStepName field's current value.
Returns
the wktStepName field value.
Definition at line 102 of file exercisetitlemessage.cpp.
 {
     Q_D(const ExerciseTitleMessage);
     return d->wktStepName;
 }
Referenced by setWktStepName().
The documentation for this class was generated from the following files:
exercisetitlemessage.h
exercisetitlemessage.cpp