QtFit: BikeProfileMessage Class Reference
BikeProfileMessage Class Reference
The BikeProfileMessage class represents a FIT BikeProfileMessage data message.
Public Member Functions
BikeProfileMessage ()
Constructs a BikeProfileMessage object.
MessageIndex messageIndex () const
Returns the BikeProfileMessage data message's messageIndex field's current value.
QString name () const
Returns the BikeProfileMessage data message's name field's current value.
Sport sport () const
Returns the BikeProfileMessage data message's sport field's current value.
SubSport subSport () const
Returns the BikeProfileMessage data message's subSport field's current value.
quint32 odometer () const
Returns the BikeProfileMessage data message's odometer field's current value.
quint16z bikeSpdAntId () const
Returns the BikeProfileMessage data message's bikeSpdAntId field's current value.
quint16z bikeCadAntId () const
Returns the BikeProfileMessage data message's bikeCadAntId field's current value.
quint16z bikeSpdcadAntId () const
Returns the BikeProfileMessage data message's bikeSpdcadAntId field's current value.
quint16z bikePowerAntId () const
Returns the BikeProfileMessage data message's bikePowerAntId field's current value.
quint16 customWheelsize () const
Returns the BikeProfileMessage data message's customWheelsize field's current value.
quint16 autoWheelsize () const
Returns the BikeProfileMessage data message's autoWheelsize field's current value.
quint16 bikeWeight () const
Returns the BikeProfileMessage data message's bikeWeight field's current value.
quint16 powerCalFactor () const
Returns the BikeProfileMessage data message's powerCalFactor field's current value.
bool autoWheelCal () const
Returns the BikeProfileMessage data message's autoWheelCal field's current value.
bool autoPowerZero () const
Returns the BikeProfileMessage data message's autoPowerZero field's current value.
quint8 id () const
Returns the BikeProfileMessage data message's id field's current value.
bool spdEnabled () const
Returns the BikeProfileMessage data message's spdEnabled field's current value.
bool cadEnabled () const
Returns the BikeProfileMessage data message's cadEnabled field's current value.
bool spdcadEnabled () const
Returns the BikeProfileMessage data message's spdcadEnabled field's current value.
bool powerEnabled () const
Returns the BikeProfileMessage data message's powerEnabled field's current value.
quint8 crankLength () const
Returns the BikeProfileMessage data message's crankLength field's current value.
bool enabled () const
Returns the BikeProfileMessage data message's enabled field's current value.
quint8z bikeSpdAntIdTransType () const
Returns the BikeProfileMessage data message's bikeSpdAntIdTransType field's current value.
quint8z bikeCadAntIdTransType () const
Returns the BikeProfileMessage data message's bikeCadAntIdTransType field's current value.
quint8z bikeSpdcadAntIdTransType () const
Returns the BikeProfileMessage data message's bikeSpdcadAntIdTransType field's current value.
quint8z bikePowerAntIdTransType () const
Returns the BikeProfileMessage data message's bikePowerAntIdTransType field's current value.
quint8 odometerRollover () const
Returns the BikeProfileMessage data message's odometerRollover field's current value.
quint8z frontGearNum () const
Returns the BikeProfileMessage data message's frontGearNum field's current value.
quint8z frontGear () const
Returns the BikeProfileMessage data message's frontGear field's current value.
quint8z rearGearNum () const
Returns the BikeProfileMessage data message's rearGearNum field's current value.
quint8z rearGear () const
Returns the BikeProfileMessage data message's rearGear field's current value.
bool shimanoDi2Enabled () const
Returns the BikeProfileMessage data message's shimanoDi2Enabled field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setName (const QString name)
Sets the name field to name.
void setSport (const Sport sport)
Sets the sport field to sport.
void setSubSport (const SubSport subSport)
Sets the subSport field to subSport.
void setOdometer (const quint32 odometer)
Sets the odometer field to odometer.
void setBikeSpdAntId (const quint16z bikeSpdAntId)
Sets the bikeSpdAntId field to bikeSpdAntId.
void setBikeCadAntId (const quint16z bikeCadAntId)
Sets the bikeCadAntId field to bikeCadAntId.
void setBikeSpdcadAntId (const quint16z bikeSpdcadAntId)
Sets the bikeSpdcadAntId field to bikeSpdcadAntId.
void setBikePowerAntId (const quint16z bikePowerAntId)
Sets the bikePowerAntId field to bikePowerAntId.
void setCustomWheelsize (const quint16 customWheelsize)
Sets the customWheelsize field to customWheelsize.
void setAutoWheelsize (const quint16 autoWheelsize)
Sets the autoWheelsize field to autoWheelsize.
void setBikeWeight (const quint16 bikeWeight)
Sets the bikeWeight field to bikeWeight.
void setPowerCalFactor (const quint16 powerCalFactor)
Sets the powerCalFactor field to powerCalFactor.
void setAutoWheelCal (const bool autoWheelCal)
Sets the autoWheelCal field to autoWheelCal.
void setAutoPowerZero (const bool autoPowerZero)
Sets the autoPowerZero field to autoPowerZero.
void setId (const quint8 id)
Sets the id field to id.
void setSpdEnabled (const bool spdEnabled)
Sets the spdEnabled field to spdEnabled.
void setCadEnabled (const bool cadEnabled)
Sets the cadEnabled field to cadEnabled.
void setSpdcadEnabled (const bool spdcadEnabled)
Sets the spdcadEnabled field to spdcadEnabled.
void setPowerEnabled (const bool powerEnabled)
Sets the powerEnabled field to powerEnabled.
void setCrankLength (const quint8 crankLength)
Sets the crankLength field to crankLength.
void setEnabled (const bool enabled)
Sets the enabled field to enabled.
void setBikeSpdAntIdTransType (const quint8z bikeSpdAntIdTransType)
Sets the bikeSpdAntIdTransType field to bikeSpdAntIdTransType.
void setBikeCadAntIdTransType (const quint8z bikeCadAntIdTransType)
Sets the bikeCadAntIdTransType field to bikeCadAntIdTransType.
void setBikeSpdcadAntIdTransType (const quint8z bikeSpdcadAntIdTransType)
Sets the bikeSpdcadAntIdTransType field to bikeSpdcadAntIdTransType.
void setBikePowerAntIdTransType (const quint8z bikePowerAntIdTransType)
Sets the bikePowerAntIdTransType field to bikePowerAntIdTransType.
void setOdometerRollover (const quint8 odometerRollover)
Sets the odometerRollover field to odometerRollover.
void setFrontGearNum (const quint8z frontGearNum)
Sets the frontGearNum field to frontGearNum.
void setFrontGear (const quint8z frontGear)
Sets the frontGear field to frontGear.
void setRearGearNum (const quint8z rearGearNum)
Sets the rearGearNum field to rearGearNum.
void setRearGear (const quint8z rearGear)
Sets the rearGear field to rearGear.
void setShimanoDi2Enabled (const bool shimanoDi2Enabled)
Sets the shimanoDi2Enabled field to shimanoDi2Enabled.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
BikeProfileMessage (BikeProfileMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The BikeProfileMessage class represents a FIT BikeProfileMessage data message.
See also
DataMessage
Definition at line 39 of file bikeprofilemessage.h.
Constructor & Destructor Documentation
BikeProfileMessage() [1/2]
BikeProfileMessage::BikeProfileMessage ()
Constructs a BikeProfileMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file bikeprofilemessage.cpp.
                                        : AbstractDataMessage(new BikeProfileMessagePrivate(this))
 {
 }
BikeProfileMessage() [2/2]
BikeProfileMessage::BikeProfileMessage (BikeProfileMessagePrivate *const d) explicit protected
Constructs a BikeProfileMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file bikeprofilemessage.cpp.
                                                                           : AbstractDataMessage(d)
 {
 }
Member Function Documentation
autoPowerZero()
bool BikeProfileMessage::autoPowerZero () const
Returns the BikeProfileMessage data message's autoPowerZero field's current value.
Returns
the autoPowerZero field value.
Definition at line 228 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->autoPowerZero;
 }
Referenced by setAutoPowerZero().
autoWheelCal()
bool BikeProfileMessage::autoWheelCal () const
Returns the BikeProfileMessage data message's autoWheelCal field's current value.
Returns
the autoWheelCal field value.
Definition at line 217 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->autoWheelCal;
 }
Referenced by setAutoWheelCal().
autoWheelsize()
quint16 BikeProfileMessage::autoWheelsize () const
Returns the BikeProfileMessage data message's autoWheelsize field's current value.
Returns
the autoWheelsize field value.
Definition at line 184 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->autoWheelsize;
 }
Referenced by setAutoWheelsize().
bikeCadAntId()
quint16z BikeProfileMessage::bikeCadAntId () const
Returns the BikeProfileMessage data message's bikeCadAntId field's current value.
Returns
the bikeCadAntId field value.
Definition at line 140 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->bikeCadAntId;
 }
Referenced by setBikeCadAntId().
bikeCadAntIdTransType()
quint8z BikeProfileMessage::bikeCadAntIdTransType () const
Returns the BikeProfileMessage data message's bikeCadAntIdTransType field's current value.
Returns
the bikeCadAntIdTransType field value.
Definition at line 327 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->bikeCadAntIdTransType;
 }
Referenced by setBikeCadAntIdTransType().
bikePowerAntId()
quint16z BikeProfileMessage::bikePowerAntId () const
Returns the BikeProfileMessage data message's bikePowerAntId field's current value.
Returns
the bikePowerAntId field value.
Definition at line 162 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->bikePowerAntId;
 }
Referenced by setBikePowerAntId().
bikePowerAntIdTransType()
quint8z BikeProfileMessage::bikePowerAntIdTransType () const
Returns the BikeProfileMessage data message's bikePowerAntIdTransType field's current value.
Returns
the bikePowerAntIdTransType field value.
Definition at line 349 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->bikePowerAntIdTransType;
 }
Referenced by setBikePowerAntIdTransType().
bikeSpdAntId()
quint16z BikeProfileMessage::bikeSpdAntId () const
Returns the BikeProfileMessage data message's bikeSpdAntId field's current value.
Returns
the bikeSpdAntId field value.
Definition at line 129 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->bikeSpdAntId;
 }
Referenced by setBikeSpdAntId().
bikeSpdAntIdTransType()
quint8z BikeProfileMessage::bikeSpdAntIdTransType () const
Returns the BikeProfileMessage data message's bikeSpdAntIdTransType field's current value.
Returns
the bikeSpdAntIdTransType field value.
Definition at line 316 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->bikeSpdAntIdTransType;
 }
Referenced by setBikeSpdAntIdTransType().
bikeSpdcadAntId()
quint16z BikeProfileMessage::bikeSpdcadAntId () const
Returns the BikeProfileMessage data message's bikeSpdcadAntId field's current value.
Returns
the bikeSpdcadAntId field value.
Definition at line 151 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->bikeSpdcadAntId;
 }
Referenced by setBikeSpdcadAntId().
bikeSpdcadAntIdTransType()
quint8z BikeProfileMessage::bikeSpdcadAntIdTransType () const
Returns the BikeProfileMessage data message's bikeSpdcadAntIdTransType field's current value.
Returns
the bikeSpdcadAntIdTransType field value.
Definition at line 338 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->bikeSpdcadAntIdTransType;
 }
Referenced by setBikeSpdcadAntIdTransType().
bikeWeight()
quint16 BikeProfileMessage::bikeWeight () const
Returns the BikeProfileMessage data message's bikeWeight field's current value.
Returns
the bikeWeight field value.
Definition at line 195 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->bikeWeight;
 }
Referenced by setBikeWeight().
cadEnabled()
bool BikeProfileMessage::cadEnabled () const
Returns the BikeProfileMessage data message's cadEnabled field's current value.
Returns
the cadEnabled field value.
Definition at line 261 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->cadEnabled;
 }
Referenced by setCadEnabled().
crankLength()
quint8 BikeProfileMessage::crankLength () const
Returns the BikeProfileMessage data message's crankLength field's current value.
Returns
the crankLength field value.
Definition at line 294 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->crankLength;
 }
Referenced by setCrankLength().
customWheelsize()
quint16 BikeProfileMessage::customWheelsize () const
Returns the BikeProfileMessage data message's customWheelsize field's current value.
Returns
the customWheelsize field value.
Definition at line 173 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->customWheelsize;
 }
Referenced by setCustomWheelsize().
enabled()
bool BikeProfileMessage::enabled () const
Returns the BikeProfileMessage data message's enabled field's current value.
Returns
the enabled field value.
Definition at line 305 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->enabled;
 }
Referenced by setEnabled().
frontGear()
quint8z BikeProfileMessage::frontGear () const
Returns the BikeProfileMessage data message's frontGear field's current value.
Number of teeth on each gear 0 is innermost
Returns
the frontGear field value.
Definition at line 388 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->frontGear;
 }
Referenced by setFrontGear().
frontGearNum()
quint8z BikeProfileMessage::frontGearNum () const
Returns the BikeProfileMessage data message's frontGearNum field's current value.
Number of front gears
Returns
the frontGearNum field value.
Definition at line 375 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->frontGearNum;
 }
Referenced by setFrontGearNum().
id()
quint8 BikeProfileMessage::id () const
Returns the BikeProfileMessage data message's id field's current value.
Returns
the id field value.
Definition at line 239 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->id;
 }
Referenced by setId().
messageIndex()
MessageIndex BikeProfileMessage::messageIndex () const
Returns the BikeProfileMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 74 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
name()
QString BikeProfileMessage::name () const
Returns the BikeProfileMessage data message's name field's current value.
Returns
the name field value.
Definition at line 85 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->name;
 }
Referenced by setName().
odometer()
quint32 BikeProfileMessage::odometer () const
Returns the BikeProfileMessage data message's odometer field's current value.
Returns
the odometer field value.
Definition at line 118 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->odometer;
 }
Referenced by setOdometer().
odometerRollover()
quint8 BikeProfileMessage::odometerRollover () const
Returns the BikeProfileMessage data message's odometerRollover field's current value.
Rollover counter that can be used to extend the odometer
Returns
the odometerRollover field value.
Definition at line 362 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->odometerRollover;
 }
Referenced by setOdometerRollover().
powerCalFactor()
quint16 BikeProfileMessage::powerCalFactor () const
Returns the BikeProfileMessage data message's powerCalFactor field's current value.
Returns
the powerCalFactor field value.
Definition at line 206 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->powerCalFactor;
 }
Referenced by setPowerCalFactor().
powerEnabled()
bool BikeProfileMessage::powerEnabled () const
Returns the BikeProfileMessage data message's powerEnabled field's current value.
Returns
the powerEnabled field value.
Definition at line 283 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->powerEnabled;
 }
Referenced by setPowerEnabled().
rearGear()
quint8z BikeProfileMessage::rearGear () const
Returns the BikeProfileMessage data message's rearGear field's current value.
Number of teeth on each gear 0 is innermost
Returns
the rearGear field value.
Definition at line 414 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->rearGear;
 }
Referenced by setRearGear().
rearGearNum()
quint8z BikeProfileMessage::rearGearNum () const
Returns the BikeProfileMessage data message's rearGearNum field's current value.
Number of rear gears
Returns
the rearGearNum field value.
Definition at line 401 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->rearGearNum;
 }
Referenced by setRearGearNum().
setAutoPowerZero()
void BikeProfileMessage::setAutoPowerZero (const bool autoPowerZero)
Sets the autoPowerZero field to autoPowerZero.
Parameters
autoPowerZero The field value to set.
Definition at line 576 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->autoPowerZero = autoPowerZero;
 }
References autoPowerZero().
setAutoWheelCal()
void BikeProfileMessage::setAutoWheelCal (const bool autoWheelCal)
Sets the autoWheelCal field to autoWheelCal.
Parameters
autoWheelCal The field value to set.
Definition at line 566 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->autoWheelCal = autoWheelCal;
 }
References autoWheelCal().
setAutoWheelsize()
void BikeProfileMessage::setAutoWheelsize (const quint16 autoWheelsize)
Sets the autoWheelsize field to autoWheelsize.
Parameters
autoWheelsize The field value to set.
Definition at line 536 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->autoWheelsize = autoWheelsize;
 }
References autoWheelsize().
setBikeCadAntId()
void BikeProfileMessage::setBikeCadAntId (const quint16z bikeCadAntId)
Sets the bikeCadAntId field to bikeCadAntId.
Parameters
bikeCadAntId The field value to set.
Definition at line 496 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->bikeCadAntId = bikeCadAntId;
 }
References bikeCadAntId().
setBikeCadAntIdTransType()
void BikeProfileMessage::setBikeCadAntIdTransType (const quint8z bikeCadAntIdTransType)
Sets the bikeCadAntIdTransType field to bikeCadAntIdTransType.
Parameters
bikeCadAntIdTransType The field value to set.
Definition at line 666 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->bikeCadAntIdTransType = bikeCadAntIdTransType;
 }
References bikeCadAntIdTransType().
setBikePowerAntId()
void BikeProfileMessage::setBikePowerAntId (const quint16z bikePowerAntId)
Sets the bikePowerAntId field to bikePowerAntId.
Parameters
bikePowerAntId The field value to set.
Definition at line 516 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->bikePowerAntId = bikePowerAntId;
 }
References bikePowerAntId().
setBikePowerAntIdTransType()
void BikeProfileMessage::setBikePowerAntIdTransType (const quint8z bikePowerAntIdTransType)
Sets the bikePowerAntIdTransType field to bikePowerAntIdTransType.
Parameters
bikePowerAntIdTransType The field value to set.
Definition at line 686 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->bikePowerAntIdTransType = bikePowerAntIdTransType;
 }
References bikePowerAntIdTransType().
setBikeSpdAntId()
void BikeProfileMessage::setBikeSpdAntId (const quint16z bikeSpdAntId)
Sets the bikeSpdAntId field to bikeSpdAntId.
Parameters
bikeSpdAntId The field value to set.
Definition at line 486 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->bikeSpdAntId = bikeSpdAntId;
 }
References bikeSpdAntId().
setBikeSpdAntIdTransType()
void BikeProfileMessage::setBikeSpdAntIdTransType (const quint8z bikeSpdAntIdTransType)
Sets the bikeSpdAntIdTransType field to bikeSpdAntIdTransType.
Parameters
bikeSpdAntIdTransType The field value to set.
Definition at line 656 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->bikeSpdAntIdTransType = bikeSpdAntIdTransType;
 }
References bikeSpdAntIdTransType().
setBikeSpdcadAntId()
void BikeProfileMessage::setBikeSpdcadAntId (const quint16z bikeSpdcadAntId)
Sets the bikeSpdcadAntId field to bikeSpdcadAntId.
Parameters
bikeSpdcadAntId The field value to set.
Definition at line 506 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->bikeSpdcadAntId = bikeSpdcadAntId;
 }
References bikeSpdcadAntId().
setBikeSpdcadAntIdTransType()
void BikeProfileMessage::setBikeSpdcadAntIdTransType (const quint8z bikeSpdcadAntIdTransType)
Sets the bikeSpdcadAntIdTransType field to bikeSpdcadAntIdTransType.
Parameters
bikeSpdcadAntIdTransType The field value to set.
Definition at line 676 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->bikeSpdcadAntIdTransType = bikeSpdcadAntIdTransType;
 }
References bikeSpdcadAntIdTransType().
setBikeWeight()
void BikeProfileMessage::setBikeWeight (const quint16 bikeWeight)
Sets the bikeWeight field to bikeWeight.
Parameters
bikeWeight The field value to set.
Definition at line 546 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->bikeWeight = bikeWeight;
 }
References bikeWeight().
setCadEnabled()
void BikeProfileMessage::setCadEnabled (const bool cadEnabled)
Sets the cadEnabled field to cadEnabled.
Parameters
cadEnabled The field value to set.
Definition at line 606 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->cadEnabled = cadEnabled;
 }
References cadEnabled().
setCrankLength()
void BikeProfileMessage::setCrankLength (const quint8 crankLength)
Sets the crankLength field to crankLength.
Parameters
crankLength The field value to set.
Definition at line 636 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->crankLength = crankLength;
 }
References crankLength().
setCustomWheelsize()
void BikeProfileMessage::setCustomWheelsize (const quint16 customWheelsize)
Sets the customWheelsize field to customWheelsize.
Parameters
customWheelsize The field value to set.
Definition at line 526 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->customWheelsize = customWheelsize;
 }
References customWheelsize().
setEnabled()
void BikeProfileMessage::setEnabled (const bool enabled)
Sets the enabled field to enabled.
Parameters
enabled The field value to set.
Definition at line 646 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->enabled = enabled;
 }
References enabled().
setFrontGear()
void BikeProfileMessage::setFrontGear (const quint8z frontGear)
Sets the frontGear field to frontGear.
Parameters
frontGear The field value to set.
Definition at line 716 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->frontGear = frontGear;
 }
References frontGear().
setFrontGearNum()
void BikeProfileMessage::setFrontGearNum (const quint8z frontGearNum)
Sets the frontGearNum field to frontGearNum.
Parameters
frontGearNum The field value to set.
Definition at line 706 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->frontGearNum = frontGearNum;
 }
References frontGearNum().
setId()
void BikeProfileMessage::setId (const quint8 id)
Sets the id field to id.
Parameters
id The field value to set.
Definition at line 586 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->id = id;
 }
References id().
setMessageIndex()
void BikeProfileMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 436 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setName()
void BikeProfileMessage::setName (const QString name)
Sets the name field to name.
Parameters
name The field value to set.
Definition at line 446 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->name = name;
 }
References name().
setOdometer()
void BikeProfileMessage::setOdometer (const quint32 odometer)
Sets the odometer field to odometer.
Parameters
odometer The field value to set.
Definition at line 476 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->odometer = odometer;
 }
References odometer().
setOdometerRollover()
void BikeProfileMessage::setOdometerRollover (const quint8 odometerRollover)
Sets the odometerRollover field to odometerRollover.
Parameters
odometerRollover The field value to set.
Definition at line 696 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->odometerRollover = odometerRollover;
 }
References odometerRollover().
setPowerCalFactor()
void BikeProfileMessage::setPowerCalFactor (const quint16 powerCalFactor)
Sets the powerCalFactor field to powerCalFactor.
Parameters
powerCalFactor The field value to set.
Definition at line 556 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->powerCalFactor = powerCalFactor;
 }
References powerCalFactor().
setPowerEnabled()
void BikeProfileMessage::setPowerEnabled (const bool powerEnabled)
Sets the powerEnabled field to powerEnabled.
Parameters
powerEnabled The field value to set.
Definition at line 626 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->powerEnabled = powerEnabled;
 }
References powerEnabled().
setRearGear()
void BikeProfileMessage::setRearGear (const quint8z rearGear)
Sets the rearGear field to rearGear.
Parameters
rearGear The field value to set.
Definition at line 736 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->rearGear = rearGear;
 }
References rearGear().
setRearGearNum()
void BikeProfileMessage::setRearGearNum (const quint8z rearGearNum)
Sets the rearGearNum field to rearGearNum.
Parameters
rearGearNum The field value to set.
Definition at line 726 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->rearGearNum = rearGearNum;
 }
References rearGearNum().
setShimanoDi2Enabled()
void BikeProfileMessage::setShimanoDi2Enabled (const bool shimanoDi2Enabled)
Sets the shimanoDi2Enabled field to shimanoDi2Enabled.
Parameters
shimanoDi2Enabled The field value to set.
Definition at line 746 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->shimanoDi2Enabled = shimanoDi2Enabled;
 }
References shimanoDi2Enabled().
setSpdcadEnabled()
void BikeProfileMessage::setSpdcadEnabled (const bool spdcadEnabled)
Sets the spdcadEnabled field to spdcadEnabled.
Parameters
spdcadEnabled The field value to set.
Definition at line 616 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->spdcadEnabled = spdcadEnabled;
 }
References spdcadEnabled().
setSpdEnabled()
void BikeProfileMessage::setSpdEnabled (const bool spdEnabled)
Sets the spdEnabled field to spdEnabled.
Parameters
spdEnabled The field value to set.
Definition at line 596 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->spdEnabled = spdEnabled;
 }
References spdEnabled().
setSport()
void BikeProfileMessage::setSport (const Sport sport)
Sets the sport field to sport.
Parameters
sport The field value to set.
Definition at line 456 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->sport = sport;
 }
References sport().
setSubSport()
void BikeProfileMessage::setSubSport (const SubSport subSport)
Sets the subSport field to subSport.
Parameters
subSport The field value to set.
Definition at line 466 of file bikeprofilemessage.cpp.
 {
     Q_D(BikeProfileMessage);
     d->subSport = subSport;
 }
References subSport().
shimanoDi2Enabled()
bool BikeProfileMessage::shimanoDi2Enabled () const
Returns the BikeProfileMessage data message's shimanoDi2Enabled field's current value.
Returns
the shimanoDi2Enabled field value.
Definition at line 425 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->shimanoDi2Enabled;
 }
Referenced by setShimanoDi2Enabled().
spdcadEnabled()
bool BikeProfileMessage::spdcadEnabled () const
Returns the BikeProfileMessage data message's spdcadEnabled field's current value.
Returns
the spdcadEnabled field value.
Definition at line 272 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->spdcadEnabled;
 }
Referenced by setSpdcadEnabled().
spdEnabled()
bool BikeProfileMessage::spdEnabled () const
Returns the BikeProfileMessage data message's spdEnabled field's current value.
Returns
the spdEnabled field value.
Definition at line 250 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->spdEnabled;
 }
Referenced by setSpdEnabled().
sport()
Sport BikeProfileMessage::sport () const
Returns the BikeProfileMessage data message's sport field's current value.
Returns
the sport field value.
Definition at line 96 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->sport;
 }
Referenced by setSport().
subSport()
SubSport BikeProfileMessage::subSport () const
Returns the BikeProfileMessage data message's subSport field's current value.
Returns
the subSport field value.
Definition at line 107 of file bikeprofilemessage.cpp.
 {
     Q_D(const BikeProfileMessage);
     return d->subSport;
 }
Referenced by setSubSport().
The documentation for this class was generated from the following files:
bikeprofilemessage.h
bikeprofilemessage.cpp