QtFit: AntTxMessage Class Reference
AntTxMessage Class Reference
The AntTxMessage class represents a FIT AntTxMessage data message.
Public Member Functions
AntTxMessage ()
Constructs a AntTxMessage object.
DateTime timestamp () const
Returns the AntTxMessage data message's timestamp field's current value.
quint16 fractionalTimestamp () const
Returns the AntTxMessage data message's fractionalTimestamp field's current value.
quint8 mesgId () const
Returns the AntTxMessage data message's mesgId field's current value.
quint8 mesgData () const
Returns the AntTxMessage data message's mesgData field's current value.
quint8 channelNumber () const
Returns the AntTxMessage data message's channelNumber field's current value.
quint8 data () const
Returns the AntTxMessage data message's data field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setFractionalTimestamp (const quint16 fractionalTimestamp)
Sets the fractionalTimestamp field to fractionalTimestamp.
void setMesgId (const quint8 mesgId)
Sets the mesgId field to mesgId.
void setMesgData (const quint8 mesgData)
Sets the mesgData field to mesgData.
void setChannelNumber (const quint8 channelNumber)
Sets the channelNumber field to channelNumber.
void setData (const quint8 data)
Sets the data field to data.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
AntTxMessage (AntTxMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The AntTxMessage class represents a FIT AntTxMessage data message.
See also
DataMessage
Definition at line 34 of file anttxmessage.h.
Constructor & Destructor Documentation
AntTxMessage() [1/2]
AntTxMessage::AntTxMessage ()
Constructs a AntTxMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file anttxmessage.cpp.
                            : AbstractDataMessage(new AntTxMessagePrivate(this))
 {
 }
AntTxMessage() [2/2]
AntTxMessage::AntTxMessage (AntTxMessagePrivate *const d) explicit protected
Constructs a AntTxMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file anttxmessage.cpp.
                                                         : AbstractDataMessage(d)
 {
 }
Member Function Documentation
channelNumber()
quint8 AntTxMessage::channelNumber () const
Returns the AntTxMessage data message's channelNumber field's current value.
Returns
the channelNumber field value.
Definition at line 113 of file anttxmessage.cpp.
 {
     Q_D(const AntTxMessage);
     return d->channelNumber;
 }
Referenced by setChannelNumber().
data()
quint8 AntTxMessage::data () const
Returns the AntTxMessage data message's data field's current value.
Returns
the data field value.
Definition at line 124 of file anttxmessage.cpp.
 {
     Q_D(const AntTxMessage);
     return d->data;
 }
Referenced by setData().
fractionalTimestamp()
quint16 AntTxMessage::fractionalTimestamp () const
Returns the AntTxMessage data message's fractionalTimestamp field's current value.
Returns
the fractionalTimestamp field value.
Definition at line 80 of file anttxmessage.cpp.
 {
     Q_D(const AntTxMessage);
     return d->fractionalTimestamp;
 }
Referenced by setFractionalTimestamp().
mesgData()
quint8 AntTxMessage::mesgData () const
Returns the AntTxMessage data message's mesgData field's current value.
Returns
the mesgData field value.
Definition at line 102 of file anttxmessage.cpp.
 {
     Q_D(const AntTxMessage);
     return d->mesgData;
 }
Referenced by setMesgData().
mesgId()
quint8 AntTxMessage::mesgId () const
Returns the AntTxMessage data message's mesgId field's current value.
Returns
the mesgId field value.
Definition at line 91 of file anttxmessage.cpp.
 {
     Q_D(const AntTxMessage);
     return d->mesgId;
 }
Referenced by setMesgId().
setChannelNumber()
void AntTxMessage::setChannelNumber (const quint8 channelNumber)
Sets the channelNumber field to channelNumber.
Parameters
channelNumber The field value to set.
Definition at line 175 of file anttxmessage.cpp.
 {
     Q_D(AntTxMessage);
     d->channelNumber = channelNumber;
 }
References channelNumber().
setData()
void AntTxMessage::setData (const quint8 data)
Sets the data field to data.
Parameters
data The field value to set.
Definition at line 185 of file anttxmessage.cpp.
 {
     Q_D(AntTxMessage);
     d->data = data;
 }
References data().
setFractionalTimestamp()
void AntTxMessage::setFractionalTimestamp (const quint16 fractionalTimestamp)
Sets the fractionalTimestamp field to fractionalTimestamp.
Parameters
fractionalTimestamp The field value to set.
Definition at line 145 of file anttxmessage.cpp.
 {
     Q_D(AntTxMessage);
     d->fractionalTimestamp = fractionalTimestamp;
 }
References fractionalTimestamp().
setMesgData()
void AntTxMessage::setMesgData (const quint8 mesgData)
Sets the mesgData field to mesgData.
Parameters
mesgData The field value to set.
Definition at line 165 of file anttxmessage.cpp.
 {
     Q_D(AntTxMessage);
     d->mesgData = mesgData;
 }
References mesgData().
setMesgId()
void AntTxMessage::setMesgId (const quint8 mesgId)
Sets the mesgId field to mesgId.
Parameters
mesgId The field value to set.
Definition at line 155 of file anttxmessage.cpp.
 {
     Q_D(AntTxMessage);
     d->mesgId = mesgId;
 }
References mesgId().
setTimestamp()
void AntTxMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 135 of file anttxmessage.cpp.
 {
     Q_D(AntTxMessage);
     d->timestamp = timestamp;
 }
References timestamp().
timestamp()
DateTime AntTxMessage::timestamp () const
Returns the AntTxMessage data message's timestamp field's current value.
Returns
the timestamp field value.
Definition at line 69 of file anttxmessage.cpp.
 {
     Q_D(const AntTxMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
The documentation for this class was generated from the following files:
anttxmessage.h
anttxmessage.cpp