QtFit: GyroscopeDataMessage Class Reference
GyroscopeDataMessage Class Reference
The GyroscopeDataMessage class represents a FIT GyroscopeDataMessage data message.
Public Member Functions
GyroscopeDataMessage ()
Constructs a GyroscopeDataMessage object.
DateTime timestamp () const
Returns the GyroscopeDataMessage data message's timestamp field's current value.
quint16 timestampMs () const
Returns the GyroscopeDataMessage data message's timestampMs field's current value.
quint16 sampleTimeOffset () const
Returns the GyroscopeDataMessage data message's sampleTimeOffset field's current value.
quint16 gyroX () const
Returns the GyroscopeDataMessage data message's gyroX field's current value.
quint16 gyroY () const
Returns the GyroscopeDataMessage data message's gyroY field's current value.
quint16 gyroZ () const
Returns the GyroscopeDataMessage data message's gyroZ field's current value.
float calibratedGyroX () const
Returns the GyroscopeDataMessage data message's calibratedGyroX field's current value.
float calibratedGyroY () const
Returns the GyroscopeDataMessage data message's calibratedGyroY field's current value.
float calibratedGyroZ () const
Returns the GyroscopeDataMessage data message's calibratedGyroZ field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
void setSampleTimeOffset (const quint16 sampleTimeOffset)
Sets the sampleTimeOffset field to sampleTimeOffset.
void setGyroX (const quint16 gyroX)
Sets the gyroX field to gyroX.
void setGyroY (const quint16 gyroY)
Sets the gyroY field to gyroY.
void setGyroZ (const quint16 gyroZ)
Sets the gyroZ field to gyroZ.
void setCalibratedGyroX (const float calibratedGyroX)
Sets the calibratedGyroX field to calibratedGyroX.
void setCalibratedGyroY (const float calibratedGyroY)
Sets the calibratedGyroY field to calibratedGyroY.
void setCalibratedGyroZ (const float calibratedGyroZ)
Sets the calibratedGyroZ field to calibratedGyroZ.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
GyroscopeDataMessage (GyroscopeDataMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The GyroscopeDataMessage class represents a FIT GyroscopeDataMessage data message.
See also
DataMessage
Definition at line 39 of file gyroscopedatamessage.h.
Constructor & Destructor Documentation
GyroscopeDataMessage() [1/2]
GyroscopeDataMessage::GyroscopeDataMessage ()
Constructs a GyroscopeDataMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file gyroscopedatamessage.cpp.
                                            : AbstractDataMessage(new GyroscopeDataMessagePrivate(this))
 {
 }
GyroscopeDataMessage() [2/2]
GyroscopeDataMessage::GyroscopeDataMessage (GyroscopeDataMessagePrivate *const d) explicit protected
Constructs a GyroscopeDataMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file gyroscopedatamessage.cpp.
                                                                                 : AbstractDataMessage(d)
 {
 }
Member Function Documentation
calibratedGyroX()
float GyroscopeDataMessage::calibratedGyroX () const
Returns the GyroscopeDataMessage data message's calibratedGyroX field's current value.
Calibrated gyro reading
Returns
the calibratedGyroX field value.
Definition at line 159 of file gyroscopedatamessage.cpp.
 {
     Q_D(const GyroscopeDataMessage);
     return d->calibratedGyroX;
 }
Referenced by setCalibratedGyroX().
calibratedGyroY()
float GyroscopeDataMessage::calibratedGyroY () const
Returns the GyroscopeDataMessage data message's calibratedGyroY field's current value.
Calibrated gyro reading
Returns
the calibratedGyroY field value.
Definition at line 172 of file gyroscopedatamessage.cpp.
 {
     Q_D(const GyroscopeDataMessage);
     return d->calibratedGyroY;
 }
Referenced by setCalibratedGyroY().
calibratedGyroZ()
float GyroscopeDataMessage::calibratedGyroZ () const
Returns the GyroscopeDataMessage data message's calibratedGyroZ field's current value.
Calibrated gyro reading
Returns
the calibratedGyroZ field value.
Definition at line 185 of file gyroscopedatamessage.cpp.
 {
     Q_D(const GyroscopeDataMessage);
     return d->calibratedGyroZ;
 }
Referenced by setCalibratedGyroZ().
gyroX()
quint16 GyroscopeDataMessage::gyroX () const
Returns the GyroscopeDataMessage data message's gyroX field's current value.
These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
Returns
the gyroX field value.
Definition at line 118 of file gyroscopedatamessage.cpp.
 {
     Q_D(const GyroscopeDataMessage);
     return d->gyroX;
 }
Referenced by setGyroX().
gyroY()
quint16 GyroscopeDataMessage::gyroY () const
Returns the GyroscopeDataMessage data message's gyroY field's current value.
These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
Returns
the gyroY field value.
Definition at line 132 of file gyroscopedatamessage.cpp.
 {
     Q_D(const GyroscopeDataMessage);
     return d->gyroY;
 }
Referenced by setGyroY().
gyroZ()
quint16 GyroscopeDataMessage::gyroZ () const
Returns the GyroscopeDataMessage data message's gyroZ field's current value.
These are the raw ADC reading. Maximum number of samples is 30 in each message. The samples may span across seconds. A conversion will need to be done on this data once read.
Returns
the gyroZ field value.
Definition at line 146 of file gyroscopedatamessage.cpp.
 {
     Q_D(const GyroscopeDataMessage);
     return d->gyroZ;
 }
Referenced by setGyroZ().
sampleTimeOffset()
quint16 GyroscopeDataMessage::sampleTimeOffset () const
Returns the GyroscopeDataMessage data message's sampleTimeOffset field's current value.
Each time in the array describes the time at which the gyro sample with the corrosponding index was taken. Limited to 30 samples in each message. The samples may span across seconds. Array size must match the number of samples in gyro_x and gyro_y and gyro_z
Returns
the sampleTimeOffset field value.
Definition at line 104 of file gyroscopedatamessage.cpp.
 {
     Q_D(const GyroscopeDataMessage);
     return d->sampleTimeOffset;
 }
Referenced by setSampleTimeOffset().
setCalibratedGyroX()
void GyroscopeDataMessage::setCalibratedGyroX (const float calibratedGyroX)
Sets the calibratedGyroX field to calibratedGyroX.
Parameters
calibratedGyroX The field value to set.
Definition at line 256 of file gyroscopedatamessage.cpp.
 {
     Q_D(GyroscopeDataMessage);
     d->calibratedGyroX = calibratedGyroX;
 }
References calibratedGyroX().
setCalibratedGyroY()
void GyroscopeDataMessage::setCalibratedGyroY (const float calibratedGyroY)
Sets the calibratedGyroY field to calibratedGyroY.
Parameters
calibratedGyroY The field value to set.
Definition at line 266 of file gyroscopedatamessage.cpp.
 {
     Q_D(GyroscopeDataMessage);
     d->calibratedGyroY = calibratedGyroY;
 }
References calibratedGyroY().
setCalibratedGyroZ()
void GyroscopeDataMessage::setCalibratedGyroZ (const float calibratedGyroZ)
Sets the calibratedGyroZ field to calibratedGyroZ.
Parameters
calibratedGyroZ The field value to set.
Definition at line 276 of file gyroscopedatamessage.cpp.
 {
     Q_D(GyroscopeDataMessage);
     d->calibratedGyroZ = calibratedGyroZ;
 }
References calibratedGyroZ().
setGyroX()
void GyroscopeDataMessage::setGyroX (const quint16 gyroX)
Sets the gyroX field to gyroX.
Parameters
gyroX The field value to set.
Definition at line 226 of file gyroscopedatamessage.cpp.
 {
     Q_D(GyroscopeDataMessage);
     d->gyroX = gyroX;
 }
References gyroX().
setGyroY()
void GyroscopeDataMessage::setGyroY (const quint16 gyroY)
Sets the gyroY field to gyroY.
Parameters
gyroY The field value to set.
Definition at line 236 of file gyroscopedatamessage.cpp.
 {
     Q_D(GyroscopeDataMessage);
     d->gyroY = gyroY;
 }
References gyroY().
setGyroZ()
void GyroscopeDataMessage::setGyroZ (const quint16 gyroZ)
Sets the gyroZ field to gyroZ.
Parameters
gyroZ The field value to set.
Definition at line 246 of file gyroscopedatamessage.cpp.
 {
     Q_D(GyroscopeDataMessage);
     d->gyroZ = gyroZ;
 }
References gyroZ().
setSampleTimeOffset()
void GyroscopeDataMessage::setSampleTimeOffset (const quint16 sampleTimeOffset)
Sets the sampleTimeOffset field to sampleTimeOffset.
Parameters
sampleTimeOffset The field value to set.
Definition at line 216 of file gyroscopedatamessage.cpp.
 {
     Q_D(GyroscopeDataMessage);
     d->sampleTimeOffset = sampleTimeOffset;
 }
References sampleTimeOffset().
setTimestamp()
void GyroscopeDataMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 196 of file gyroscopedatamessage.cpp.
 {
     Q_D(GyroscopeDataMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setTimestampMs()
void GyroscopeDataMessage::setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
Parameters
timestampMs The field value to set.
Definition at line 206 of file gyroscopedatamessage.cpp.
 {
     Q_D(GyroscopeDataMessage);
     d->timestampMs = timestampMs;
 }
References timestampMs().
timestamp()
DateTime GyroscopeDataMessage::timestamp () const
Returns the GyroscopeDataMessage data message's timestamp field's current value.
Whole second part of the timestamp
Returns
the timestamp field value.
Definition at line 76 of file gyroscopedatamessage.cpp.
 {
     Q_D(const GyroscopeDataMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
timestampMs()
quint16 GyroscopeDataMessage::timestampMs () const
Returns the GyroscopeDataMessage data message's timestampMs field's current value.
Millisecond part of the timestamp.
Returns
the timestampMs field value.
Definition at line 89 of file gyroscopedatamessage.cpp.
 {
     Q_D(const GyroscopeDataMessage);
     return d->timestampMs;
 }
Referenced by setTimestampMs().
The documentation for this class was generated from the following files:
gyroscopedatamessage.h
gyroscopedatamessage.cpp