QtFit: RecordMessage Class Reference
RecordMessage Class Reference
The RecordMessage class represents a FIT RecordMessage data message.
Public Member Functions
RecordMessage ()
Constructs a RecordMessage object.
DateTime timestamp () const
Returns the RecordMessage data message's timestamp field's current value.
qint32 positionLat () const
Returns the RecordMessage data message's positionLat field's current value.
qint32 positionLong () const
Returns the RecordMessage data message's positionLong field's current value.
quint16 altitude () const
Returns the RecordMessage data message's altitude field's current value.
quint8 heartRate () const
Returns the RecordMessage data message's heartRate field's current value.
quint8 cadence () const
Returns the RecordMessage data message's cadence field's current value.
quint32 distance () const
Returns the RecordMessage data message's distance field's current value.
quint16 speed () const
Returns the RecordMessage data message's speed field's current value.
quint16 power () const
Returns the RecordMessage data message's power field's current value.
quint8 compressedSpeedDistance () const
Returns the RecordMessage data message's compressedSpeedDistance field's current value.
qint16 grade () const
Returns the RecordMessage data message's grade field's current value.
quint8 resistance () const
Returns the RecordMessage data message's resistance field's current value.
qint32 timeFromCourse () const
Returns the RecordMessage data message's timeFromCourse field's current value.
quint8 cycleLength () const
Returns the RecordMessage data message's cycleLength field's current value.
qint8 temperature () const
Returns the RecordMessage data message's temperature field's current value.
quint8 speed1s () const
Returns the RecordMessage data message's speed1s field's current value.
quint8 cycles () const
Returns the RecordMessage data message's cycles field's current value.
quint32 totalCycles () const
Returns the RecordMessage data message's totalCycles field's current value.
quint16 compressedAccumulatedPower () const
Returns the RecordMessage data message's compressedAccumulatedPower field's current value.
quint32 accumulatedPower () const
Returns the RecordMessage data message's accumulatedPower field's current value.
LeftRightBalance leftRightBalance () const
Returns the RecordMessage data message's leftRightBalance field's current value.
quint8 gpsAccuracy () const
Returns the RecordMessage data message's gpsAccuracy field's current value.
qint16 verticalSpeed () const
Returns the RecordMessage data message's verticalSpeed field's current value.
quint16 calories () const
Returns the RecordMessage data message's calories field's current value.
quint16 verticalOscillation () const
Returns the RecordMessage data message's verticalOscillation field's current value.
quint16 stanceTimePercent () const
Returns the RecordMessage data message's stanceTimePercent field's current value.
quint16 stanceTime () const
Returns the RecordMessage data message's stanceTime field's current value.
ActivityType activityType () const
Returns the RecordMessage data message's activityType field's current value.
quint8 leftTorqueEffectiveness () const
Returns the RecordMessage data message's leftTorqueEffectiveness field's current value.
quint8 rightTorqueEffectiveness () const
Returns the RecordMessage data message's rightTorqueEffectiveness field's current value.
quint8 leftPedalSmoothness () const
Returns the RecordMessage data message's leftPedalSmoothness field's current value.
quint8 rightPedalSmoothness () const
Returns the RecordMessage data message's rightPedalSmoothness field's current value.
quint8 combinedPedalSmoothness () const
Returns the RecordMessage data message's combinedPedalSmoothness field's current value.
quint8 time128 () const
Returns the RecordMessage data message's time128 field's current value.
StrokeType strokeType () const
Returns the RecordMessage data message's strokeType field's current value.
quint8 zone () const
Returns the RecordMessage data message's zone field's current value.
quint16 ballSpeed () const
Returns the RecordMessage data message's ballSpeed field's current value.
quint16 cadence256 () const
Returns the RecordMessage data message's cadence256 field's current value.
quint8 fractionalCadence () const
Returns the RecordMessage data message's fractionalCadence field's current value.
quint16 totalHemoglobinConc () const
Returns the RecordMessage data message's totalHemoglobinConc field's current value.
quint16 totalHemoglobinConcMin () const
Returns the RecordMessage data message's totalHemoglobinConcMin field's current value.
quint16 totalHemoglobinConcMax () const
Returns the RecordMessage data message's totalHemoglobinConcMax field's current value.
quint16 saturatedHemoglobinPercent () const
Returns the RecordMessage data message's saturatedHemoglobinPercent field's current value.
quint16 saturatedHemoglobinPercentMin () const
Returns the RecordMessage data message's saturatedHemoglobinPercentMin field's current value.
quint16 saturatedHemoglobinPercentMax () const
Returns the RecordMessage data message's saturatedHemoglobinPercentMax field's current value.
DeviceIndex deviceIndex () const
Returns the RecordMessage data message's deviceIndex field's current value.
qint8 leftPco () const
Returns the RecordMessage data message's leftPco field's current value.
qint8 rightPco () const
Returns the RecordMessage data message's rightPco field's current value.
quint8 leftPowerPhase () const
Returns the RecordMessage data message's leftPowerPhase field's current value.
quint8 leftPowerPhasePeak () const
Returns the RecordMessage data message's leftPowerPhasePeak field's current value.
quint8 rightPowerPhase () const
Returns the RecordMessage data message's rightPowerPhase field's current value.
quint8 rightPowerPhasePeak () const
Returns the RecordMessage data message's rightPowerPhasePeak field's current value.
quint32 enhancedSpeed () const
Returns the RecordMessage data message's enhancedSpeed field's current value.
quint32 enhancedAltitude () const
Returns the RecordMessage data message's enhancedAltitude field's current value.
quint8 batterySoc () const
Returns the RecordMessage data message's batterySoc field's current value.
quint16 motorPower () const
Returns the RecordMessage data message's motorPower field's current value.
quint16 verticalRatio () const
Returns the RecordMessage data message's verticalRatio field's current value.
quint16 stanceTimeBalance () const
Returns the RecordMessage data message's stanceTimeBalance field's current value.
quint16 stepLength () const
Returns the RecordMessage data message's stepLength field's current value.
quint32 absolutePressure () const
Returns the RecordMessage data message's absolutePressure field's current value.
quint32 depth () const
Returns the RecordMessage data message's depth field's current value.
quint32 nextStopDepth () const
Returns the RecordMessage data message's nextStopDepth field's current value.
quint32 nextStopTime () const
Returns the RecordMessage data message's nextStopTime field's current value.
quint32 timeToSurface () const
Returns the RecordMessage data message's timeToSurface field's current value.
quint32 ndlTime () const
Returns the RecordMessage data message's ndlTime field's current value.
quint8 cnsLoad () const
Returns the RecordMessage data message's cnsLoad field's current value.
quint16 n2Load () const
Returns the RecordMessage data message's n2Load field's current value.
float grit () const
Returns the RecordMessage data message's grit field's current value.
float flow () const
Returns the RecordMessage data message's flow field's current value.
quint16 ebikeTravelRange () const
Returns the RecordMessage data message's ebikeTravelRange field's current value.
quint8 ebikeBatteryLevel () const
Returns the RecordMessage data message's ebikeBatteryLevel field's current value.
quint8 ebikeAssistMode () const
Returns the RecordMessage data message's ebikeAssistMode field's current value.
quint8 ebikeAssistLevelPercent () const
Returns the RecordMessage data message's ebikeAssistLevelPercent field's current value.
quint16 coreTemperature () const
Returns the RecordMessage data message's coreTemperature field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setPositionLat (const qint32 positionLat)
Sets the positionLat field to positionLat.
void setPositionLong (const qint32 positionLong)
Sets the positionLong field to positionLong.
void setAltitude (const quint16 altitude)
Sets the altitude field to altitude.
void setHeartRate (const quint8 heartRate)
Sets the heartRate field to heartRate.
void setCadence (const quint8 cadence)
Sets the cadence field to cadence.
void setDistance (const quint32 distance)
Sets the distance field to distance.
void setSpeed (const quint16 speed)
Sets the speed field to speed.
void setPower (const quint16 power)
Sets the power field to power.
void setCompressedSpeedDistance (const quint8 compressedSpeedDistance)
Sets the compressedSpeedDistance field to compressedSpeedDistance.
void setGrade (const qint16 grade)
Sets the grade field to grade.
void setResistance (const quint8 resistance)
Sets the resistance field to resistance.
void setTimeFromCourse (const qint32 timeFromCourse)
Sets the timeFromCourse field to timeFromCourse.
void setCycleLength (const quint8 cycleLength)
Sets the cycleLength field to cycleLength.
void setTemperature (const qint8 temperature)
Sets the temperature field to temperature.
void setSpeed1s (const quint8 speed1s)
Sets the speed1s field to speed1s.
void setCycles (const quint8 cycles)
Sets the cycles field to cycles.
void setTotalCycles (const quint32 totalCycles)
Sets the totalCycles field to totalCycles.
void setCompressedAccumulatedPower (const quint16 compressedAccumulatedPower)
Sets the compressedAccumulatedPower field to compressedAccumulatedPower.
void setAccumulatedPower (const quint32 accumulatedPower)
Sets the accumulatedPower field to accumulatedPower.
void setLeftRightBalance (const LeftRightBalance leftRightBalance)
Sets the leftRightBalance field to leftRightBalance.
void setGpsAccuracy (const quint8 gpsAccuracy)
Sets the gpsAccuracy field to gpsAccuracy.
void setVerticalSpeed (const qint16 verticalSpeed)
Sets the verticalSpeed field to verticalSpeed.
void setCalories (const quint16 calories)
Sets the calories field to calories.
void setVerticalOscillation (const quint16 verticalOscillation)
Sets the verticalOscillation field to verticalOscillation.
void setStanceTimePercent (const quint16 stanceTimePercent)
Sets the stanceTimePercent field to stanceTimePercent.
void setStanceTime (const quint16 stanceTime)
Sets the stanceTime field to stanceTime.
void setActivityType (const ActivityType activityType)
Sets the activityType field to activityType.
void setLeftTorqueEffectiveness (const quint8 leftTorqueEffectiveness)
Sets the leftTorqueEffectiveness field to leftTorqueEffectiveness.
void setRightTorqueEffectiveness (const quint8 rightTorqueEffectiveness)
Sets the rightTorqueEffectiveness field to rightTorqueEffectiveness.
void setLeftPedalSmoothness (const quint8 leftPedalSmoothness)
Sets the leftPedalSmoothness field to leftPedalSmoothness.
void setRightPedalSmoothness (const quint8 rightPedalSmoothness)
Sets the rightPedalSmoothness field to rightPedalSmoothness.
void setCombinedPedalSmoothness (const quint8 combinedPedalSmoothness)
Sets the combinedPedalSmoothness field to combinedPedalSmoothness.
void setTime128 (const quint8 time128)
Sets the time128 field to time128.
void setStrokeType (const StrokeType strokeType)
Sets the strokeType field to strokeType.
void setZone (const quint8 zone)
Sets the zone field to zone.
void setBallSpeed (const quint16 ballSpeed)
Sets the ballSpeed field to ballSpeed.
void setCadence256 (const quint16 cadence256)
Sets the cadence256 field to cadence256.
void setFractionalCadence (const quint8 fractionalCadence)
Sets the fractionalCadence field to fractionalCadence.
void setTotalHemoglobinConc (const quint16 totalHemoglobinConc)
Sets the totalHemoglobinConc field to totalHemoglobinConc.
void setTotalHemoglobinConcMin (const quint16 totalHemoglobinConcMin)
Sets the totalHemoglobinConcMin field to totalHemoglobinConcMin.
void setTotalHemoglobinConcMax (const quint16 totalHemoglobinConcMax)
Sets the totalHemoglobinConcMax field to totalHemoglobinConcMax.
void setSaturatedHemoglobinPercent (const quint16 saturatedHemoglobinPercent)
Sets the saturatedHemoglobinPercent field to saturatedHemoglobinPercent.
void setSaturatedHemoglobinPercentMin (const quint16 saturatedHemoglobinPercentMin)
Sets the saturatedHemoglobinPercentMin field to saturatedHemoglobinPercentMin.
void setSaturatedHemoglobinPercentMax (const quint16 saturatedHemoglobinPercentMax)
Sets the saturatedHemoglobinPercentMax field to saturatedHemoglobinPercentMax.
void setDeviceIndex (const DeviceIndex deviceIndex)
Sets the deviceIndex field to deviceIndex.
void setLeftPco (const qint8 leftPco)
Sets the leftPco field to leftPco.
void setRightPco (const qint8 rightPco)
Sets the rightPco field to rightPco.
void setLeftPowerPhase (const quint8 leftPowerPhase)
Sets the leftPowerPhase field to leftPowerPhase.
void setLeftPowerPhasePeak (const quint8 leftPowerPhasePeak)
Sets the leftPowerPhasePeak field to leftPowerPhasePeak.
void setRightPowerPhase (const quint8 rightPowerPhase)
Sets the rightPowerPhase field to rightPowerPhase.
void setRightPowerPhasePeak (const quint8 rightPowerPhasePeak)
Sets the rightPowerPhasePeak field to rightPowerPhasePeak.
void setEnhancedSpeed (const quint32 enhancedSpeed)
Sets the enhancedSpeed field to enhancedSpeed.
void setEnhancedAltitude (const quint32 enhancedAltitude)
Sets the enhancedAltitude field to enhancedAltitude.
void setBatterySoc (const quint8 batterySoc)
Sets the batterySoc field to batterySoc.
void setMotorPower (const quint16 motorPower)
Sets the motorPower field to motorPower.
void setVerticalRatio (const quint16 verticalRatio)
Sets the verticalRatio field to verticalRatio.
void setStanceTimeBalance (const quint16 stanceTimeBalance)
Sets the stanceTimeBalance field to stanceTimeBalance.
void setStepLength (const quint16 stepLength)
Sets the stepLength field to stepLength.
void setAbsolutePressure (const quint32 absolutePressure)
Sets the absolutePressure field to absolutePressure.
void setDepth (const quint32 depth)
Sets the depth field to depth.
void setNextStopDepth (const quint32 nextStopDepth)
Sets the nextStopDepth field to nextStopDepth.
void setNextStopTime (const quint32 nextStopTime)
Sets the nextStopTime field to nextStopTime.
void setTimeToSurface (const quint32 timeToSurface)
Sets the timeToSurface field to timeToSurface.
void setNdlTime (const quint32 ndlTime)
Sets the ndlTime field to ndlTime.
void setCnsLoad (const quint8 cnsLoad)
Sets the cnsLoad field to cnsLoad.
void setN2Load (const quint16 n2Load)
Sets the n2Load field to n2Load.
void setGrit (const float grit)
Sets the grit field to grit.
void setFlow (const float flow)
Sets the flow field to flow.
void setEbikeTravelRange (const quint16 ebikeTravelRange)
Sets the ebikeTravelRange field to ebikeTravelRange.
void setEbikeBatteryLevel (const quint8 ebikeBatteryLevel)
Sets the ebikeBatteryLevel field to ebikeBatteryLevel.
void setEbikeAssistMode (const quint8 ebikeAssistMode)
Sets the ebikeAssistMode field to ebikeAssistMode.
void setEbikeAssistLevelPercent (const quint8 ebikeAssistLevelPercent)
Sets the ebikeAssistLevelPercent field to ebikeAssistLevelPercent.
void setCoreTemperature (const quint16 coreTemperature)
Sets the coreTemperature field to coreTemperature.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
RecordMessage (RecordMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The RecordMessage class represents a FIT RecordMessage data message.
See also
DataMessage
Definition at line 39 of file recordmessage.h.
Constructor & Destructor Documentation
RecordMessage() [1/2]
RecordMessage::RecordMessage ()
Constructs a RecordMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file recordmessage.cpp.
                              : AbstractDataMessage(new RecordMessagePrivate(this))
 {
 }
RecordMessage() [2/2]
RecordMessage::RecordMessage (RecordMessagePrivate *const d) explicit protected
Constructs a RecordMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file recordmessage.cpp.
                                                            : AbstractDataMessage(d)
 {
 }
Member Function Documentation
absolutePressure()
quint32 RecordMessage::absolutePressure () const
Returns the RecordMessage data message's absolutePressure field's current value.
Includes atmospheric pressure
Returns
the absolutePressure field value.
Definition at line 759 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->absolutePressure;
 }
Referenced by setAbsolutePressure().
accumulatedPower()
quint32 RecordMessage::accumulatedPower () const
Returns the RecordMessage data message's accumulatedPower field's current value.
Returns
the accumulatedPower field value.
Definition at line 287 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->accumulatedPower;
 }
Referenced by setAccumulatedPower().
activityType()
ActivityType RecordMessage::activityType () const
Returns the RecordMessage data message's activityType field's current value.
Returns
the activityType field value.
Definition at line 375 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->activityType;
 }
Referenced by setActivityType().
altitude()
quint16 RecordMessage::altitude () const
Returns the RecordMessage data message's altitude field's current value.
Returns
the altitude field value.
Definition at line 107 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->altitude;
 }
Referenced by setAltitude().
ballSpeed()
quint16 RecordMessage::ballSpeed () const
Returns the RecordMessage data message's ballSpeed field's current value.
Returns
the ballSpeed field value.
Definition at line 474 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->ballSpeed;
 }
Referenced by setBallSpeed().
batterySoc()
quint8 RecordMessage::batterySoc () const
Returns the RecordMessage data message's batterySoc field's current value.
lev battery state of charge
Returns
the batterySoc field value.
Definition at line 700 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->batterySoc;
 }
Referenced by setBatterySoc().
cadence()
quint8 RecordMessage::cadence () const
Returns the RecordMessage data message's cadence field's current value.
Returns
the cadence field value.
Definition at line 129 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->cadence;
 }
Referenced by setCadence().
cadence256()
quint16 RecordMessage::cadence256 () const
Returns the RecordMessage data message's cadence256 field's current value.
Log cadence and fractional cadence for backwards compatability
Returns
the cadence256 field value.
Definition at line 487 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->cadence256;
 }
Referenced by setCadence256().
calories()
quint16 RecordMessage::calories () const
Returns the RecordMessage data message's calories field's current value.
Returns
the calories field value.
Definition at line 331 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->calories;
 }
Referenced by setCalories().
cnsLoad()
quint8 RecordMessage::cnsLoad () const
Returns the RecordMessage data message's cnsLoad field's current value.
Returns
the cnsLoad field value.
Definition at line 829 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->cnsLoad;
 }
Referenced by setCnsLoad().
combinedPedalSmoothness()
quint8 RecordMessage::combinedPedalSmoothness () const
Returns the RecordMessage data message's combinedPedalSmoothness field's current value.
Returns
the combinedPedalSmoothness field value.
Definition at line 430 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->combinedPedalSmoothness;
 }
Referenced by setCombinedPedalSmoothness().
compressedAccumulatedPower()
quint16 RecordMessage::compressedAccumulatedPower () const
Returns the RecordMessage data message's compressedAccumulatedPower field's current value.
Returns
the compressedAccumulatedPower field value.
Definition at line 276 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->compressedAccumulatedPower;
 }
Referenced by setCompressedAccumulatedPower().
compressedSpeedDistance()
quint8 RecordMessage::compressedSpeedDistance () const
Returns the RecordMessage data message's compressedSpeedDistance field's current value.
Returns
the compressedSpeedDistance field value.
Definition at line 173 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->compressedSpeedDistance;
 }
Referenced by setCompressedSpeedDistance().
coreTemperature()
quint16 RecordMessage::coreTemperature () const
Returns the RecordMessage data message's coreTemperature field's current value.
Returns
the coreTemperature field value.
Definition at line 923 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->coreTemperature;
 }
Referenced by setCoreTemperature().
cycleLength()
quint8 RecordMessage::cycleLength () const
Returns the RecordMessage data message's cycleLength field's current value.
Returns
the cycleLength field value.
Definition at line 219 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->cycleLength;
 }
Referenced by setCycleLength().
cycles()
quint8 RecordMessage::cycles () const
Returns the RecordMessage data message's cycles field's current value.
Returns
the cycles field value.
Definition at line 254 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->cycles;
 }
Referenced by setCycles().
depth()
quint32 RecordMessage::depth () const
Returns the RecordMessage data message's depth field's current value.
0 if above water
Returns
the depth field value.
Definition at line 772 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->depth;
 }
Referenced by setDepth().
deviceIndex()
DeviceIndex RecordMessage::deviceIndex () const
Returns the RecordMessage data message's deviceIndex field's current value.
Returns
the deviceIndex field value.
Definition at line 587 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->deviceIndex;
 }
Referenced by setDeviceIndex().
distance()
quint32 RecordMessage::distance () const
Returns the RecordMessage data message's distance field's current value.
Returns
the distance field value.
Definition at line 140 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->distance;
 }
Referenced by setDistance().
ebikeAssistLevelPercent()
quint8 RecordMessage::ebikeAssistLevelPercent () const
Returns the RecordMessage data message's ebikeAssistLevelPercent field's current value.
Returns
the ebikeAssistLevelPercent field value.
Definition at line 912 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->ebikeAssistLevelPercent;
 }
Referenced by setEbikeAssistLevelPercent().
ebikeAssistMode()
quint8 RecordMessage::ebikeAssistMode () const
Returns the RecordMessage data message's ebikeAssistMode field's current value.
Returns
the ebikeAssistMode field value.
Definition at line 901 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->ebikeAssistMode;
 }
Referenced by setEbikeAssistMode().
ebikeBatteryLevel()
quint8 RecordMessage::ebikeBatteryLevel () const
Returns the RecordMessage data message's ebikeBatteryLevel field's current value.
Returns
the ebikeBatteryLevel field value.
Definition at line 890 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->ebikeBatteryLevel;
 }
Referenced by setEbikeBatteryLevel().
ebikeTravelRange()
quint16 RecordMessage::ebikeTravelRange () const
Returns the RecordMessage data message's ebikeTravelRange field's current value.
Returns
the ebikeTravelRange field value.
Definition at line 879 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->ebikeTravelRange;
 }
Referenced by setEbikeTravelRange().
enhancedAltitude()
quint32 RecordMessage::enhancedAltitude () const
Returns the RecordMessage data message's enhancedAltitude field's current value.
Returns
the enhancedAltitude field value.
Definition at line 687 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->enhancedAltitude;
 }
Referenced by setEnhancedAltitude().
enhancedSpeed()
quint32 RecordMessage::enhancedSpeed () const
Returns the RecordMessage data message's enhancedSpeed field's current value.
Returns
the enhancedSpeed field value.
Definition at line 676 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->enhancedSpeed;
 }
Referenced by setEnhancedSpeed().
flow()
float RecordMessage::flow () const
Returns the RecordMessage data message's flow field's current value.
The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.
Returns
the flow field value.
Definition at line 868 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->flow;
 }
Referenced by setFlow().
fractionalCadence()
quint8 RecordMessage::fractionalCadence () const
Returns the RecordMessage data message's fractionalCadence field's current value.
Returns
the fractionalCadence field value.
Definition at line 498 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->fractionalCadence;
 }
Referenced by setFractionalCadence().
gpsAccuracy()
quint8 RecordMessage::gpsAccuracy () const
Returns the RecordMessage data message's gpsAccuracy field's current value.
Returns
the gpsAccuracy field value.
Definition at line 309 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->gpsAccuracy;
 }
Referenced by setGpsAccuracy().
grade()
qint16 RecordMessage::grade () const
Returns the RecordMessage data message's grade field's current value.
Returns
the grade field value.
Definition at line 184 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->grade;
 }
Referenced by setGrade().
grit()
float RecordMessage::grit () const
Returns the RecordMessage data message's grit field's current value.
The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.
Returns
the grit field value.
Definition at line 854 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->grit;
 }
Referenced by setGrit().
heartRate()
quint8 RecordMessage::heartRate () const
Returns the RecordMessage data message's heartRate field's current value.
Returns
the heartRate field value.
Definition at line 118 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->heartRate;
 }
Referenced by setHeartRate().
leftPco()
qint8 RecordMessage::leftPco () const
Returns the RecordMessage data message's leftPco field's current value.
Left platform center offset
Returns
the leftPco field value.
Definition at line 600 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->leftPco;
 }
Referenced by setLeftPco().
leftPedalSmoothness()
quint8 RecordMessage::leftPedalSmoothness () const
Returns the RecordMessage data message's leftPedalSmoothness field's current value.
Returns
the leftPedalSmoothness field value.
Definition at line 408 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->leftPedalSmoothness;
 }
Referenced by setLeftPedalSmoothness().
leftPowerPhase()
quint8 RecordMessage::leftPowerPhase () const
Returns the RecordMessage data message's leftPowerPhase field's current value.
Left power phase angles. Data value indexes defined by power_phase_type.
Returns
the leftPowerPhase field value.
Definition at line 626 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->leftPowerPhase;
 }
Referenced by setLeftPowerPhase().
leftPowerPhasePeak()
quint8 RecordMessage::leftPowerPhasePeak () const
Returns the RecordMessage data message's leftPowerPhasePeak field's current value.
Left power phase peak angles. Data value indexes defined by power_phase_type.
Returns
the leftPowerPhasePeak field value.
Definition at line 639 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->leftPowerPhasePeak;
 }
Referenced by setLeftPowerPhasePeak().
leftRightBalance()
LeftRightBalance RecordMessage::leftRightBalance () const
Returns the RecordMessage data message's leftRightBalance field's current value.
Returns
the leftRightBalance field value.
Definition at line 298 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->leftRightBalance;
 }
Referenced by setLeftRightBalance().
leftTorqueEffectiveness()
quint8 RecordMessage::leftTorqueEffectiveness () const
Returns the RecordMessage data message's leftTorqueEffectiveness field's current value.
Returns
the leftTorqueEffectiveness field value.
Definition at line 386 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->leftTorqueEffectiveness;
 }
Referenced by setLeftTorqueEffectiveness().
motorPower()
quint16 RecordMessage::motorPower () const
Returns the RecordMessage data message's motorPower field's current value.
lev motor power
Returns
the motorPower field value.
Definition at line 713 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->motorPower;
 }
Referenced by setMotorPower().
n2Load()
quint16 RecordMessage::n2Load () const
Returns the RecordMessage data message's n2Load field's current value.
Returns
the n2Load field value.
Definition at line 840 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->n2Load;
 }
Referenced by setN2Load().
ndlTime()
quint32 RecordMessage::ndlTime () const
Returns the RecordMessage data message's ndlTime field's current value.
Returns
the ndlTime field value.
Definition at line 818 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->ndlTime;
 }
Referenced by setNdlTime().
nextStopDepth()
quint32 RecordMessage::nextStopDepth () const
Returns the RecordMessage data message's nextStopDepth field's current value.
0 if above water
Returns
the nextStopDepth field value.
Definition at line 785 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->nextStopDepth;
 }
Referenced by setNextStopDepth().
nextStopTime()
quint32 RecordMessage::nextStopTime () const
Returns the RecordMessage data message's nextStopTime field's current value.
Returns
the nextStopTime field value.
Definition at line 796 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->nextStopTime;
 }
Referenced by setNextStopTime().
positionLat()
qint32 RecordMessage::positionLat () const
Returns the RecordMessage data message's positionLat field's current value.
Returns
the positionLat field value.
Definition at line 85 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->positionLat;
 }
Referenced by setPositionLat().
positionLong()
qint32 RecordMessage::positionLong () const
Returns the RecordMessage data message's positionLong field's current value.
Returns
the positionLong field value.
Definition at line 96 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->positionLong;
 }
Referenced by setPositionLong().
power()
quint16 RecordMessage::power () const
Returns the RecordMessage data message's power field's current value.
Returns
the power field value.
Definition at line 162 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->power;
 }
Referenced by setPower().
resistance()
quint8 RecordMessage::resistance () const
Returns the RecordMessage data message's resistance field's current value.
Relative. 0 is none 254 is Max.
Returns
the resistance field value.
Definition at line 197 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->resistance;
 }
Referenced by setResistance().
rightPco()
qint8 RecordMessage::rightPco () const
Returns the RecordMessage data message's rightPco field's current value.
Right platform center offset
Returns
the rightPco field value.
Definition at line 613 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->rightPco;
 }
Referenced by setRightPco().
rightPedalSmoothness()
quint8 RecordMessage::rightPedalSmoothness () const
Returns the RecordMessage data message's rightPedalSmoothness field's current value.
Returns
the rightPedalSmoothness field value.
Definition at line 419 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->rightPedalSmoothness;
 }
Referenced by setRightPedalSmoothness().
rightPowerPhase()
quint8 RecordMessage::rightPowerPhase () const
Returns the RecordMessage data message's rightPowerPhase field's current value.
Right power phase angles. Data value indexes defined by power_phase_type.
Returns
the rightPowerPhase field value.
Definition at line 652 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->rightPowerPhase;
 }
Referenced by setRightPowerPhase().
rightPowerPhasePeak()
quint8 RecordMessage::rightPowerPhasePeak () const
Returns the RecordMessage data message's rightPowerPhasePeak field's current value.
Right power phase peak angles. Data value indexes defined by power_phase_type.
Returns
the rightPowerPhasePeak field value.
Definition at line 665 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->rightPowerPhasePeak;
 }
Referenced by setRightPowerPhasePeak().
rightTorqueEffectiveness()
quint8 RecordMessage::rightTorqueEffectiveness () const
Returns the RecordMessage data message's rightTorqueEffectiveness field's current value.
Returns
the rightTorqueEffectiveness field value.
Definition at line 397 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->rightTorqueEffectiveness;
 }
Referenced by setRightTorqueEffectiveness().
saturatedHemoglobinPercent()
quint16 RecordMessage::saturatedHemoglobinPercent () const
Returns the RecordMessage data message's saturatedHemoglobinPercent field's current value.
Percentage of hemoglobin saturated with oxygen
Returns
the saturatedHemoglobinPercent field value.
Definition at line 550 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->saturatedHemoglobinPercent;
 }
Referenced by setSaturatedHemoglobinPercent().
saturatedHemoglobinPercentMax()
quint16 RecordMessage::saturatedHemoglobinPercentMax () const
Returns the RecordMessage data message's saturatedHemoglobinPercentMax field's current value.
Max percentage of hemoglobin saturated with oxygen
Returns
the saturatedHemoglobinPercentMax field value.
Definition at line 576 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->saturatedHemoglobinPercentMax;
 }
Referenced by setSaturatedHemoglobinPercentMax().
saturatedHemoglobinPercentMin()
quint16 RecordMessage::saturatedHemoglobinPercentMin () const
Returns the RecordMessage data message's saturatedHemoglobinPercentMin field's current value.
Min percentage of hemoglobin saturated with oxygen
Returns
the saturatedHemoglobinPercentMin field value.
Definition at line 563 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->saturatedHemoglobinPercentMin;
 }
Referenced by setSaturatedHemoglobinPercentMin().
setAbsolutePressure()
void RecordMessage::setAbsolutePressure (const quint32 absolutePressure)
Sets the absolutePressure field to absolutePressure.
Parameters
absolutePressure The field value to set.
Definition at line 1524 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->absolutePressure = absolutePressure;
 }
References absolutePressure().
setAccumulatedPower()
void RecordMessage::setAccumulatedPower (const quint32 accumulatedPower)
Sets the accumulatedPower field to accumulatedPower.
Parameters
accumulatedPower The field value to set.
Definition at line 1124 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->accumulatedPower = accumulatedPower;
 }
References accumulatedPower().
setActivityType()
void RecordMessage::setActivityType (const ActivityType activityType)
Sets the activityType field to activityType.
Parameters
activityType The field value to set.
Definition at line 1204 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->activityType = activityType;
 }
References activityType().
setAltitude()
void RecordMessage::setAltitude (const quint16 altitude)
Sets the altitude field to altitude.
Parameters
altitude The field value to set.
Definition at line 964 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->altitude = altitude;
 }
References altitude().
setBallSpeed()
void RecordMessage::setBallSpeed (const quint16 ballSpeed)
Sets the ballSpeed field to ballSpeed.
Parameters
ballSpeed The field value to set.
Definition at line 1294 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->ballSpeed = ballSpeed;
 }
References ballSpeed().
setBatterySoc()
void RecordMessage::setBatterySoc (const quint8 batterySoc)
Sets the batterySoc field to batterySoc.
Parameters
batterySoc The field value to set.
Definition at line 1474 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->batterySoc = batterySoc;
 }
References batterySoc().
setCadence()
void RecordMessage::setCadence (const quint8 cadence)
Sets the cadence field to cadence.
Parameters
cadence The field value to set.
Definition at line 984 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->cadence = cadence;
 }
References cadence().
setCadence256()
void RecordMessage::setCadence256 (const quint16 cadence256)
Sets the cadence256 field to cadence256.
Parameters
cadence256 The field value to set.
Definition at line 1304 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->cadence256 = cadence256;
 }
References cadence256().
setCalories()
void RecordMessage::setCalories (const quint16 calories)
Sets the calories field to calories.
Parameters
calories The field value to set.
Definition at line 1164 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->calories = calories;
 }
References calories().
setCnsLoad()
void RecordMessage::setCnsLoad (const quint8 cnsLoad)
Sets the cnsLoad field to cnsLoad.
Parameters
cnsLoad The field value to set.
Definition at line 1584 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->cnsLoad = cnsLoad;
 }
References cnsLoad().
setCombinedPedalSmoothness()
void RecordMessage::setCombinedPedalSmoothness (const quint8 combinedPedalSmoothness)
Sets the combinedPedalSmoothness field to combinedPedalSmoothness.
Parameters
combinedPedalSmoothness The field value to set.
Definition at line 1254 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->combinedPedalSmoothness = combinedPedalSmoothness;
 }
References combinedPedalSmoothness().
setCompressedAccumulatedPower()
void RecordMessage::setCompressedAccumulatedPower (const quint16 compressedAccumulatedPower)
Sets the compressedAccumulatedPower field to compressedAccumulatedPower.
Parameters
compressedAccumulatedPower The field value to set.
Definition at line 1114 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->compressedAccumulatedPower = compressedAccumulatedPower;
 }
References compressedAccumulatedPower().
setCompressedSpeedDistance()
void RecordMessage::setCompressedSpeedDistance (const quint8 compressedSpeedDistance)
Sets the compressedSpeedDistance field to compressedSpeedDistance.
Parameters
compressedSpeedDistance The field value to set.
Definition at line 1024 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->compressedSpeedDistance = compressedSpeedDistance;
 }
References compressedSpeedDistance().
setCoreTemperature()
void RecordMessage::setCoreTemperature (const quint16 coreTemperature)
Sets the coreTemperature field to coreTemperature.
Parameters
coreTemperature The field value to set.
Definition at line 1664 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->coreTemperature = coreTemperature;
 }
References coreTemperature().
setCycleLength()
void RecordMessage::setCycleLength (const quint8 cycleLength)
Sets the cycleLength field to cycleLength.
Parameters
cycleLength The field value to set.
Definition at line 1064 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->cycleLength = cycleLength;
 }
References cycleLength().
setCycles()
void RecordMessage::setCycles (const quint8 cycles)
Sets the cycles field to cycles.
Parameters
cycles The field value to set.
Definition at line 1094 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->cycles = cycles;
 }
References cycles().
setDepth()
void RecordMessage::setDepth (const quint32 depth)
Sets the depth field to depth.
Parameters
depth The field value to set.
Definition at line 1534 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->depth = depth;
 }
References depth().
setDeviceIndex()
void RecordMessage::setDeviceIndex (const DeviceIndex deviceIndex)
Sets the deviceIndex field to deviceIndex.
Parameters
deviceIndex The field value to set.
Definition at line 1384 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->deviceIndex = deviceIndex;
 }
References deviceIndex().
setDistance()
void RecordMessage::setDistance (const quint32 distance)
Sets the distance field to distance.
Parameters
distance The field value to set.
Definition at line 994 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->distance = distance;
 }
References distance().
setEbikeAssistLevelPercent()
void RecordMessage::setEbikeAssistLevelPercent (const quint8 ebikeAssistLevelPercent)
Sets the ebikeAssistLevelPercent field to ebikeAssistLevelPercent.
Parameters
ebikeAssistLevelPercent The field value to set.
Definition at line 1654 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->ebikeAssistLevelPercent = ebikeAssistLevelPercent;
 }
References ebikeAssistLevelPercent().
setEbikeAssistMode()
void RecordMessage::setEbikeAssistMode (const quint8 ebikeAssistMode)
Sets the ebikeAssistMode field to ebikeAssistMode.
Parameters
ebikeAssistMode The field value to set.
Definition at line 1644 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->ebikeAssistMode = ebikeAssistMode;
 }
References ebikeAssistMode().
setEbikeBatteryLevel()
void RecordMessage::setEbikeBatteryLevel (const quint8 ebikeBatteryLevel)
Sets the ebikeBatteryLevel field to ebikeBatteryLevel.
Parameters
ebikeBatteryLevel The field value to set.
Definition at line 1634 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->ebikeBatteryLevel = ebikeBatteryLevel;
 }
References ebikeBatteryLevel().
setEbikeTravelRange()
void RecordMessage::setEbikeTravelRange (const quint16 ebikeTravelRange)
Sets the ebikeTravelRange field to ebikeTravelRange.
Parameters
ebikeTravelRange The field value to set.
Definition at line 1624 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->ebikeTravelRange = ebikeTravelRange;
 }
References ebikeTravelRange().
setEnhancedAltitude()
void RecordMessage::setEnhancedAltitude (const quint32 enhancedAltitude)
Sets the enhancedAltitude field to enhancedAltitude.
Parameters
enhancedAltitude The field value to set.
Definition at line 1464 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->enhancedAltitude = enhancedAltitude;
 }
References enhancedAltitude().
setEnhancedSpeed()
void RecordMessage::setEnhancedSpeed (const quint32 enhancedSpeed)
Sets the enhancedSpeed field to enhancedSpeed.
Parameters
enhancedSpeed The field value to set.
Definition at line 1454 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->enhancedSpeed = enhancedSpeed;
 }
References enhancedSpeed().
setFlow()
void RecordMessage::setFlow (const float flow)
Sets the flow field to flow.
Parameters
flow The field value to set.
Definition at line 1614 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->flow = flow;
 }
References flow().
setFractionalCadence()
void RecordMessage::setFractionalCadence (const quint8 fractionalCadence)
Sets the fractionalCadence field to fractionalCadence.
Parameters
fractionalCadence The field value to set.
Definition at line 1314 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->fractionalCadence = fractionalCadence;
 }
References fractionalCadence().
setGpsAccuracy()
void RecordMessage::setGpsAccuracy (const quint8 gpsAccuracy)
Sets the gpsAccuracy field to gpsAccuracy.
Parameters
gpsAccuracy The field value to set.
Definition at line 1144 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->gpsAccuracy = gpsAccuracy;
 }
References gpsAccuracy().
setGrade()
void RecordMessage::setGrade (const qint16 grade)
Sets the grade field to grade.
Parameters
grade The field value to set.
Definition at line 1034 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->grade = grade;
 }
References grade().
setGrit()
void RecordMessage::setGrit (const float grit)
Sets the grit field to grit.
Parameters
grit The field value to set.
Definition at line 1604 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->grit = grit;
 }
References grit().
setHeartRate()
void RecordMessage::setHeartRate (const quint8 heartRate)
Sets the heartRate field to heartRate.
Parameters
heartRate The field value to set.
Definition at line 974 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->heartRate = heartRate;
 }
References heartRate().
setLeftPco()
void RecordMessage::setLeftPco (const qint8 leftPco)
Sets the leftPco field to leftPco.
Parameters
leftPco The field value to set.
Definition at line 1394 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->leftPco = leftPco;
 }
References leftPco().
setLeftPedalSmoothness()
void RecordMessage::setLeftPedalSmoothness (const quint8 leftPedalSmoothness)
Sets the leftPedalSmoothness field to leftPedalSmoothness.
Parameters
leftPedalSmoothness The field value to set.
Definition at line 1234 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->leftPedalSmoothness = leftPedalSmoothness;
 }
References leftPedalSmoothness().
setLeftPowerPhase()
void RecordMessage::setLeftPowerPhase (const quint8 leftPowerPhase)
Sets the leftPowerPhase field to leftPowerPhase.
Parameters
leftPowerPhase The field value to set.
Definition at line 1414 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->leftPowerPhase = leftPowerPhase;
 }
References leftPowerPhase().
setLeftPowerPhasePeak()
void RecordMessage::setLeftPowerPhasePeak (const quint8 leftPowerPhasePeak)
Sets the leftPowerPhasePeak field to leftPowerPhasePeak.
Parameters
leftPowerPhasePeak The field value to set.
Definition at line 1424 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->leftPowerPhasePeak = leftPowerPhasePeak;
 }
References leftPowerPhasePeak().
setLeftRightBalance()
void RecordMessage::setLeftRightBalance (const LeftRightBalance leftRightBalance)
Sets the leftRightBalance field to leftRightBalance.
Parameters
leftRightBalance The field value to set.
Definition at line 1134 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->leftRightBalance = leftRightBalance;
 }
References leftRightBalance().
setLeftTorqueEffectiveness()
void RecordMessage::setLeftTorqueEffectiveness (const quint8 leftTorqueEffectiveness)
Sets the leftTorqueEffectiveness field to leftTorqueEffectiveness.
Parameters
leftTorqueEffectiveness The field value to set.
Definition at line 1214 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->leftTorqueEffectiveness = leftTorqueEffectiveness;
 }
References leftTorqueEffectiveness().
setMotorPower()
void RecordMessage::setMotorPower (const quint16 motorPower)
Sets the motorPower field to motorPower.
Parameters
motorPower The field value to set.
Definition at line 1484 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->motorPower = motorPower;
 }
References motorPower().
setN2Load()
void RecordMessage::setN2Load (const quint16 n2Load)
Sets the n2Load field to n2Load.
Parameters
n2Load The field value to set.
Definition at line 1594 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->n2Load = n2Load;
 }
References n2Load().
setNdlTime()
void RecordMessage::setNdlTime (const quint32 ndlTime)
Sets the ndlTime field to ndlTime.
Parameters
ndlTime The field value to set.
Definition at line 1574 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->ndlTime = ndlTime;
 }
References ndlTime().
setNextStopDepth()
void RecordMessage::setNextStopDepth (const quint32 nextStopDepth)
Sets the nextStopDepth field to nextStopDepth.
Parameters
nextStopDepth The field value to set.
Definition at line 1544 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->nextStopDepth = nextStopDepth;
 }
References nextStopDepth().
setNextStopTime()
void RecordMessage::setNextStopTime (const quint32 nextStopTime)
Sets the nextStopTime field to nextStopTime.
Parameters
nextStopTime The field value to set.
Definition at line 1554 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->nextStopTime = nextStopTime;
 }
References nextStopTime().
setPositionLat()
void RecordMessage::setPositionLat (const qint32 positionLat)
Sets the positionLat field to positionLat.
Parameters
positionLat The field value to set.
Definition at line 944 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->positionLat = positionLat;
 }
References positionLat().
setPositionLong()
void RecordMessage::setPositionLong (const qint32 positionLong)
Sets the positionLong field to positionLong.
Parameters
positionLong The field value to set.
Definition at line 954 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->positionLong = positionLong;
 }
References positionLong().
setPower()
void RecordMessage::setPower (const quint16 power)
Sets the power field to power.
Parameters
power The field value to set.
Definition at line 1014 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->power = power;
 }
References power().
setResistance()
void RecordMessage::setResistance (const quint8 resistance)
Sets the resistance field to resistance.
Parameters
resistance The field value to set.
Definition at line 1044 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->resistance = resistance;
 }
References resistance().
setRightPco()
void RecordMessage::setRightPco (const qint8 rightPco)
Sets the rightPco field to rightPco.
Parameters
rightPco The field value to set.
Definition at line 1404 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->rightPco = rightPco;
 }
References rightPco().
setRightPedalSmoothness()
void RecordMessage::setRightPedalSmoothness (const quint8 rightPedalSmoothness)
Sets the rightPedalSmoothness field to rightPedalSmoothness.
Parameters
rightPedalSmoothness The field value to set.
Definition at line 1244 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->rightPedalSmoothness = rightPedalSmoothness;
 }
References rightPedalSmoothness().
setRightPowerPhase()
void RecordMessage::setRightPowerPhase (const quint8 rightPowerPhase)
Sets the rightPowerPhase field to rightPowerPhase.
Parameters
rightPowerPhase The field value to set.
Definition at line 1434 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->rightPowerPhase = rightPowerPhase;
 }
References rightPowerPhase().
setRightPowerPhasePeak()
void RecordMessage::setRightPowerPhasePeak (const quint8 rightPowerPhasePeak)
Sets the rightPowerPhasePeak field to rightPowerPhasePeak.
Parameters
rightPowerPhasePeak The field value to set.
Definition at line 1444 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->rightPowerPhasePeak = rightPowerPhasePeak;
 }
References rightPowerPhasePeak().
setRightTorqueEffectiveness()
void RecordMessage::setRightTorqueEffectiveness (const quint8 rightTorqueEffectiveness)
Sets the rightTorqueEffectiveness field to rightTorqueEffectiveness.
Parameters
rightTorqueEffectiveness The field value to set.
Definition at line 1224 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->rightTorqueEffectiveness = rightTorqueEffectiveness;
 }
References rightTorqueEffectiveness().
setSaturatedHemoglobinPercent()
void RecordMessage::setSaturatedHemoglobinPercent (const quint16 saturatedHemoglobinPercent)
Sets the saturatedHemoglobinPercent field to saturatedHemoglobinPercent.
Parameters
saturatedHemoglobinPercent The field value to set.
Definition at line 1354 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->saturatedHemoglobinPercent = saturatedHemoglobinPercent;
 }
References saturatedHemoglobinPercent().
setSaturatedHemoglobinPercentMax()
void RecordMessage::setSaturatedHemoglobinPercentMax (const quint16 saturatedHemoglobinPercentMax)
Sets the saturatedHemoglobinPercentMax field to saturatedHemoglobinPercentMax.
Parameters
saturatedHemoglobinPercentMax The field value to set.
Definition at line 1374 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->saturatedHemoglobinPercentMax = saturatedHemoglobinPercentMax;
 }
References saturatedHemoglobinPercentMax().
setSaturatedHemoglobinPercentMin()
void RecordMessage::setSaturatedHemoglobinPercentMin (const quint16 saturatedHemoglobinPercentMin)
Sets the saturatedHemoglobinPercentMin field to saturatedHemoglobinPercentMin.
Parameters
saturatedHemoglobinPercentMin The field value to set.
Definition at line 1364 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->saturatedHemoglobinPercentMin = saturatedHemoglobinPercentMin;
 }
References saturatedHemoglobinPercentMin().
setSpeed()
void RecordMessage::setSpeed (const quint16 speed)
Sets the speed field to speed.
Parameters
speed The field value to set.
Definition at line 1004 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->speed = speed;
 }
References speed().
setSpeed1s()
void RecordMessage::setSpeed1s (const quint8 speed1s)
Sets the speed1s field to speed1s.
Parameters
speed1s The field value to set.
Definition at line 1084 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->speed1s = speed1s;
 }
References speed1s().
setStanceTime()
void RecordMessage::setStanceTime (const quint16 stanceTime)
Sets the stanceTime field to stanceTime.
Parameters
stanceTime The field value to set.
Definition at line 1194 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->stanceTime = stanceTime;
 }
References stanceTime().
setStanceTimeBalance()
void RecordMessage::setStanceTimeBalance (const quint16 stanceTimeBalance)
Sets the stanceTimeBalance field to stanceTimeBalance.
Parameters
stanceTimeBalance The field value to set.
Definition at line 1504 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->stanceTimeBalance = stanceTimeBalance;
 }
References stanceTimeBalance().
setStanceTimePercent()
void RecordMessage::setStanceTimePercent (const quint16 stanceTimePercent)
Sets the stanceTimePercent field to stanceTimePercent.
Parameters
stanceTimePercent The field value to set.
Definition at line 1184 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->stanceTimePercent = stanceTimePercent;
 }
References stanceTimePercent().
setStepLength()
void RecordMessage::setStepLength (const quint16 stepLength)
Sets the stepLength field to stepLength.
Parameters
stepLength The field value to set.
Definition at line 1514 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->stepLength = stepLength;
 }
References stepLength().
setStrokeType()
void RecordMessage::setStrokeType (const StrokeType strokeType)
Sets the strokeType field to strokeType.
Parameters
strokeType The field value to set.
Definition at line 1274 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->strokeType = strokeType;
 }
References strokeType().
setTemperature()
void RecordMessage::setTemperature (const qint8 temperature)
Sets the temperature field to temperature.
Parameters
temperature The field value to set.
Definition at line 1074 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->temperature = temperature;
 }
References temperature().
setTime128()
void RecordMessage::setTime128 (const quint8 time128)
Sets the time128 field to time128.
Parameters
time128 The field value to set.
Definition at line 1264 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->time128 = time128;
 }
References time128().
setTimeFromCourse()
void RecordMessage::setTimeFromCourse (const qint32 timeFromCourse)
Sets the timeFromCourse field to timeFromCourse.
Parameters
timeFromCourse The field value to set.
Definition at line 1054 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->timeFromCourse = timeFromCourse;
 }
References timeFromCourse().
setTimestamp()
void RecordMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 934 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setTimeToSurface()
void RecordMessage::setTimeToSurface (const quint32 timeToSurface)
Sets the timeToSurface field to timeToSurface.
Parameters
timeToSurface The field value to set.
Definition at line 1564 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->timeToSurface = timeToSurface;
 }
References timeToSurface().
setTotalCycles()
void RecordMessage::setTotalCycles (const quint32 totalCycles)
Sets the totalCycles field to totalCycles.
Parameters
totalCycles The field value to set.
Definition at line 1104 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->totalCycles = totalCycles;
 }
References totalCycles().
setTotalHemoglobinConc()
void RecordMessage::setTotalHemoglobinConc (const quint16 totalHemoglobinConc)
Sets the totalHemoglobinConc field to totalHemoglobinConc.
Parameters
totalHemoglobinConc The field value to set.
Definition at line 1324 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->totalHemoglobinConc = totalHemoglobinConc;
 }
References totalHemoglobinConc().
setTotalHemoglobinConcMax()
void RecordMessage::setTotalHemoglobinConcMax (const quint16 totalHemoglobinConcMax)
Sets the totalHemoglobinConcMax field to totalHemoglobinConcMax.
Parameters
totalHemoglobinConcMax The field value to set.
Definition at line 1344 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->totalHemoglobinConcMax = totalHemoglobinConcMax;
 }
References totalHemoglobinConcMax().
setTotalHemoglobinConcMin()
void RecordMessage::setTotalHemoglobinConcMin (const quint16 totalHemoglobinConcMin)
Sets the totalHemoglobinConcMin field to totalHemoglobinConcMin.
Parameters
totalHemoglobinConcMin The field value to set.
Definition at line 1334 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->totalHemoglobinConcMin = totalHemoglobinConcMin;
 }
References totalHemoglobinConcMin().
setVerticalOscillation()
void RecordMessage::setVerticalOscillation (const quint16 verticalOscillation)
Sets the verticalOscillation field to verticalOscillation.
Parameters
verticalOscillation The field value to set.
Definition at line 1174 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->verticalOscillation = verticalOscillation;
 }
References verticalOscillation().
setVerticalRatio()
void RecordMessage::setVerticalRatio (const quint16 verticalRatio)
Sets the verticalRatio field to verticalRatio.
Parameters
verticalRatio The field value to set.
Definition at line 1494 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->verticalRatio = verticalRatio;
 }
References verticalRatio().
setVerticalSpeed()
void RecordMessage::setVerticalSpeed (const qint16 verticalSpeed)
Sets the verticalSpeed field to verticalSpeed.
Parameters
verticalSpeed The field value to set.
Definition at line 1154 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->verticalSpeed = verticalSpeed;
 }
References verticalSpeed().
setZone()
void RecordMessage::setZone (const quint8 zone)
Sets the zone field to zone.
Parameters
zone The field value to set.
Definition at line 1284 of file recordmessage.cpp.
 {
     Q_D(RecordMessage);
     d->zone = zone;
 }
References zone().
speed()
quint16 RecordMessage::speed () const
Returns the RecordMessage data message's speed field's current value.
Returns
the speed field value.
Definition at line 151 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->speed;
 }
Referenced by setSpeed().
speed1s()
quint8 RecordMessage::speed1s () const
Returns the RecordMessage data message's speed1s field's current value.
Speed at 1s intervals. Timestamp field indicates time of last array element.
Returns
the speed1s field value.
Definition at line 243 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->speed1s;
 }
Referenced by setSpeed1s().
stanceTime()
quint16 RecordMessage::stanceTime () const
Returns the RecordMessage data message's stanceTime field's current value.
Returns
the stanceTime field value.
Definition at line 364 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->stanceTime;
 }
Referenced by setStanceTime().
stanceTimeBalance()
quint16 RecordMessage::stanceTimeBalance () const
Returns the RecordMessage data message's stanceTimeBalance field's current value.
Returns
the stanceTimeBalance field value.
Definition at line 735 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->stanceTimeBalance;
 }
Referenced by setStanceTimeBalance().
stanceTimePercent()
quint16 RecordMessage::stanceTimePercent () const
Returns the RecordMessage data message's stanceTimePercent field's current value.
Returns
the stanceTimePercent field value.
Definition at line 353 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->stanceTimePercent;
 }
Referenced by setStanceTimePercent().
stepLength()
quint16 RecordMessage::stepLength () const
Returns the RecordMessage data message's stepLength field's current value.
Returns
the stepLength field value.
Definition at line 746 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->stepLength;
 }
Referenced by setStepLength().
strokeType()
StrokeType RecordMessage::strokeType () const
Returns the RecordMessage data message's strokeType field's current value.
Returns
the strokeType field value.
Definition at line 452 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->strokeType;
 }
Referenced by setStrokeType().
temperature()
qint8 RecordMessage::temperature () const
Returns the RecordMessage data message's temperature field's current value.
Returns
the temperature field value.
Definition at line 230 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->temperature;
 }
Referenced by setTemperature().
time128()
quint8 RecordMessage::time128 () const
Returns the RecordMessage data message's time128 field's current value.
Returns
the time128 field value.
Definition at line 441 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->time128;
 }
Referenced by setTime128().
timeFromCourse()
qint32 RecordMessage::timeFromCourse () const
Returns the RecordMessage data message's timeFromCourse field's current value.
Returns
the timeFromCourse field value.
Definition at line 208 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->timeFromCourse;
 }
Referenced by setTimeFromCourse().
timestamp()
DateTime RecordMessage::timestamp () const
Returns the RecordMessage data message's timestamp field's current value.
Returns
the timestamp field value.
Definition at line 74 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
timeToSurface()
quint32 RecordMessage::timeToSurface () const
Returns the RecordMessage data message's timeToSurface field's current value.
Returns
the timeToSurface field value.
Definition at line 807 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->timeToSurface;
 }
Referenced by setTimeToSurface().
totalCycles()
quint32 RecordMessage::totalCycles () const
Returns the RecordMessage data message's totalCycles field's current value.
Returns
the totalCycles field value.
Definition at line 265 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->totalCycles;
 }
Referenced by setTotalCycles().
totalHemoglobinConc()
quint16 RecordMessage::totalHemoglobinConc () const
Returns the RecordMessage data message's totalHemoglobinConc field's current value.
Total saturated and unsaturated hemoglobin
Returns
the totalHemoglobinConc field value.
Definition at line 511 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->totalHemoglobinConc;
 }
Referenced by setTotalHemoglobinConc().
totalHemoglobinConcMax()
quint16 RecordMessage::totalHemoglobinConcMax () const
Returns the RecordMessage data message's totalHemoglobinConcMax field's current value.
Max saturated and unsaturated hemoglobin
Returns
the totalHemoglobinConcMax field value.
Definition at line 537 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->totalHemoglobinConcMax;
 }
Referenced by setTotalHemoglobinConcMax().
totalHemoglobinConcMin()
quint16 RecordMessage::totalHemoglobinConcMin () const
Returns the RecordMessage data message's totalHemoglobinConcMin field's current value.
Min saturated and unsaturated hemoglobin
Returns
the totalHemoglobinConcMin field value.
Definition at line 524 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->totalHemoglobinConcMin;
 }
Referenced by setTotalHemoglobinConcMin().
verticalOscillation()
quint16 RecordMessage::verticalOscillation () const
Returns the RecordMessage data message's verticalOscillation field's current value.
Returns
the verticalOscillation field value.
Definition at line 342 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->verticalOscillation;
 }
Referenced by setVerticalOscillation().
verticalRatio()
quint16 RecordMessage::verticalRatio () const
Returns the RecordMessage data message's verticalRatio field's current value.
Returns
the verticalRatio field value.
Definition at line 724 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->verticalRatio;
 }
Referenced by setVerticalRatio().
verticalSpeed()
qint16 RecordMessage::verticalSpeed () const
Returns the RecordMessage data message's verticalSpeed field's current value.
Returns
the verticalSpeed field value.
Definition at line 320 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->verticalSpeed;
 }
Referenced by setVerticalSpeed().
zone()
quint8 RecordMessage::zone () const
Returns the RecordMessage data message's zone field's current value.
Returns
the zone field value.
Definition at line 463 of file recordmessage.cpp.
 {
     Q_D(const RecordMessage);
     return d->zone;
 }
Referenced by setZone().
The documentation for this class was generated from the following files:
recordmessage.h
recordmessage.cpp