QtFit: VideoMessage Class Reference
VideoMessage Class Reference
The VideoMessage class represents a FIT VideoMessage data message.
Public Member Functions
VideoMessage ()
Constructs a VideoMessage object.
QString url () const
Returns the VideoMessage data message's url field's current value.
QString hostingProvider () const
Returns the VideoMessage data message's hostingProvider field's current value.
quint32 duration () const
Returns the VideoMessage data message's duration field's current value.
void setUrl (const QString url)
Sets the url field to url.
void setHostingProvider (const QString hostingProvider)
Sets the hostingProvider field to hostingProvider.
void setDuration (const quint32 duration)
Sets the duration field to duration.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
VideoMessage (VideoMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The VideoMessage class represents a FIT VideoMessage data message.
See also
DataMessage
Definition at line 34 of file videomessage.h.
Constructor & Destructor Documentation
VideoMessage() [1/2]
VideoMessage::VideoMessage ()
Constructs a VideoMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file videomessage.cpp.
                            : AbstractDataMessage(new VideoMessagePrivate(this))
 {
 }
VideoMessage() [2/2]
VideoMessage::VideoMessage (VideoMessagePrivate *const d) explicit protected
Constructs a VideoMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file videomessage.cpp.
                                                         : AbstractDataMessage(d)
 {
 }
Member Function Documentation
duration()
quint32 VideoMessage::duration () const
Returns the VideoMessage data message's duration field's current value.
Playback time of video
Returns
the duration field value.
Definition at line 93 of file videomessage.cpp.
 {
     Q_D(const VideoMessage);
     return d->duration;
 }
Referenced by setDuration().
hostingProvider()
QString VideoMessage::hostingProvider () const
Returns the VideoMessage data message's hostingProvider field's current value.
Returns
the hostingProvider field value.
Definition at line 80 of file videomessage.cpp.
 {
     Q_D(const VideoMessage);
     return d->hostingProvider;
 }
Referenced by setHostingProvider().
setDuration()
void VideoMessage::setDuration (const quint32 duration)
Sets the duration field to duration.
Parameters
duration The field value to set.
Definition at line 124 of file videomessage.cpp.
 {
     Q_D(VideoMessage);
     d->duration = duration;
 }
References duration().
setHostingProvider()
void VideoMessage::setHostingProvider (const QString hostingProvider)
Sets the hostingProvider field to hostingProvider.
Parameters
hostingProvider The field value to set.
Definition at line 114 of file videomessage.cpp.
 {
     Q_D(VideoMessage);
     d->hostingProvider = hostingProvider;
 }
References hostingProvider().
setUrl()
void VideoMessage::setUrl (const QString url)
Sets the url field to url.
Parameters
url The field value to set.
Definition at line 104 of file videomessage.cpp.
 {
     Q_D(VideoMessage);
     d->url = url;
 }
References url().
url()
QString VideoMessage::url () const
Returns the VideoMessage data message's url field's current value.
Returns
the url field value.
Definition at line 69 of file videomessage.cpp.
 {
     Q_D(const VideoMessage);
     return d->url;
 }
Referenced by setUrl().
The documentation for this class was generated from the following files:
videomessage.h
videomessage.cpp