QtFit: SegmentPointMessage Class Reference
SegmentPointMessage Class Reference
The SegmentPointMessage class represents a FIT SegmentPointMessage data message.
Public Member Functions
SegmentPointMessage ()
Constructs a SegmentPointMessage object.
MessageIndex messageIndex () const
Returns the SegmentPointMessage data message's messageIndex field's current value.
qint32 positionLat () const
Returns the SegmentPointMessage data message's positionLat field's current value.
qint32 positionLong () const
Returns the SegmentPointMessage data message's positionLong field's current value.
quint32 distance () const
Returns the SegmentPointMessage data message's distance field's current value.
quint16 altitude () const
Returns the SegmentPointMessage data message's altitude field's current value.
quint32 leaderTime () const
Returns the SegmentPointMessage data message's leaderTime field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setPositionLat (const qint32 positionLat)
Sets the positionLat field to positionLat.
void setPositionLong (const qint32 positionLong)
Sets the positionLong field to positionLong.
void setDistance (const quint32 distance)
Sets the distance field to distance.
void setAltitude (const quint16 altitude)
Sets the altitude field to altitude.
void setLeaderTime (const quint32 leaderTime)
Sets the leaderTime field to leaderTime.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
SegmentPointMessage (SegmentPointMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The SegmentPointMessage class represents a FIT SegmentPointMessage data message.
See also
DataMessage
Definition at line 39 of file segmentpointmessage.h.
Constructor & Destructor Documentation
SegmentPointMessage() [1/2]
SegmentPointMessage::SegmentPointMessage ()
Constructs a SegmentPointMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file segmentpointmessage.cpp.
                                          : AbstractDataMessage(new SegmentPointMessagePrivate(this))
 {
 }
SegmentPointMessage() [2/2]
SegmentPointMessage::SegmentPointMessage (SegmentPointMessagePrivate *const d) explicit protected
Constructs a SegmentPointMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file segmentpointmessage.cpp.
                                                                              : AbstractDataMessage(d)
 {
 }
Member Function Documentation
altitude()
quint16 SegmentPointMessage::altitude () const
Returns the SegmentPointMessage data message's altitude field's current value.
Accumulated altitude along the segment at the described point
Returns
the altitude field value.
Definition at line 122 of file segmentpointmessage.cpp.
 {
     Q_D(const SegmentPointMessage);
     return d->altitude;
 }
Referenced by setAltitude().
distance()
quint32 SegmentPointMessage::distance () const
Returns the SegmentPointMessage data message's distance field's current value.
Accumulated distance along the segment at the described point
Returns
the distance field value.
Definition at line 109 of file segmentpointmessage.cpp.
 {
     Q_D(const SegmentPointMessage);
     return d->distance;
 }
Referenced by setDistance().
leaderTime()
quint32 SegmentPointMessage::leaderTime () const
Returns the SegmentPointMessage data message's leaderTime field's current value.
Accumualted time each leader board member required to reach the described point. This value is zero for all leader board members at the starting point of the segment.
Returns
the leaderTime field value.
Definition at line 136 of file segmentpointmessage.cpp.
 {
     Q_D(const SegmentPointMessage);
     return d->leaderTime;
 }
Referenced by setLeaderTime().
messageIndex()
MessageIndex SegmentPointMessage::messageIndex () const
Returns the SegmentPointMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 74 of file segmentpointmessage.cpp.
 {
     Q_D(const SegmentPointMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
positionLat()
qint32 SegmentPointMessage::positionLat () const
Returns the SegmentPointMessage data message's positionLat field's current value.
Returns
the positionLat field value.
Definition at line 85 of file segmentpointmessage.cpp.
 {
     Q_D(const SegmentPointMessage);
     return d->positionLat;
 }
Referenced by setPositionLat().
positionLong()
qint32 SegmentPointMessage::positionLong () const
Returns the SegmentPointMessage data message's positionLong field's current value.
Returns
the positionLong field value.
Definition at line 96 of file segmentpointmessage.cpp.
 {
     Q_D(const SegmentPointMessage);
     return d->positionLong;
 }
Referenced by setPositionLong().
setAltitude()
void SegmentPointMessage::setAltitude (const quint16 altitude)
Sets the altitude field to altitude.
Parameters
altitude The field value to set.
Definition at line 187 of file segmentpointmessage.cpp.
 {
     Q_D(SegmentPointMessage);
     d->altitude = altitude;
 }
References altitude().
setDistance()
void SegmentPointMessage::setDistance (const quint32 distance)
Sets the distance field to distance.
Parameters
distance The field value to set.
Definition at line 177 of file segmentpointmessage.cpp.
 {
     Q_D(SegmentPointMessage);
     d->distance = distance;
 }
References distance().
setLeaderTime()
void SegmentPointMessage::setLeaderTime (const quint32 leaderTime)
Sets the leaderTime field to leaderTime.
Parameters
leaderTime The field value to set.
Definition at line 197 of file segmentpointmessage.cpp.
 {
     Q_D(SegmentPointMessage);
     d->leaderTime = leaderTime;
 }
References leaderTime().
setMessageIndex()
void SegmentPointMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 147 of file segmentpointmessage.cpp.
 {
     Q_D(SegmentPointMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setPositionLat()
void SegmentPointMessage::setPositionLat (const qint32 positionLat)
Sets the positionLat field to positionLat.
Parameters
positionLat The field value to set.
Definition at line 157 of file segmentpointmessage.cpp.
 {
     Q_D(SegmentPointMessage);
     d->positionLat = positionLat;
 }
References positionLat().
setPositionLong()
void SegmentPointMessage::setPositionLong (const qint32 positionLong)
Sets the positionLong field to positionLong.
Parameters
positionLong The field value to set.
Definition at line 167 of file segmentpointmessage.cpp.
 {
     Q_D(SegmentPointMessage);
     d->positionLong = positionLong;
 }
References positionLong().
The documentation for this class was generated from the following files:
segmentpointmessage.h
segmentpointmessage.cpp