QtFit: VideoTitleMessage Class Reference
VideoTitleMessage Class Reference
The VideoTitleMessage class represents a FIT VideoTitleMessage data message.
Public Member Functions
VideoTitleMessage ()
Constructs a VideoTitleMessage object.
MessageIndex messageIndex () const
Returns the VideoTitleMessage data message's messageIndex field's current value.
quint16 messageCount () const
Returns the VideoTitleMessage data message's messageCount field's current value.
QString text () const
Returns the VideoTitleMessage data message's text field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setMessageCount (const quint16 messageCount)
Sets the messageCount field to messageCount.
void setText (const QString text)
Sets the text field to text.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
VideoTitleMessage (VideoTitleMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The VideoTitleMessage class represents a FIT VideoTitleMessage data message.
See also
DataMessage
Definition at line 34 of file videotitlemessage.h.
Constructor & Destructor Documentation
VideoTitleMessage() [1/2]
VideoTitleMessage::VideoTitleMessage ()
Constructs a VideoTitleMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file videotitlemessage.cpp.
                                      : AbstractDataMessage(new VideoTitleMessagePrivate(this))
 {
 }
VideoTitleMessage() [2/2]
VideoTitleMessage::VideoTitleMessage (VideoTitleMessagePrivate *const d) explicit protected
Constructs a VideoTitleMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file videotitlemessage.cpp.
                                                                        : AbstractDataMessage(d)
 {
 }
Member Function Documentation
messageCount()
quint16 VideoTitleMessage::messageCount () const
Returns the VideoTitleMessage data message's messageCount field's current value.
Total number of title parts
Returns
the messageCount field value.
Definition at line 84 of file videotitlemessage.cpp.
 {
     Q_D(const VideoTitleMessage);
     return d->messageCount;
 }
Referenced by setMessageCount().
messageIndex()
MessageIndex VideoTitleMessage::messageIndex () const
Returns the VideoTitleMessage data message's messageIndex field's current value.
Long titles will be split into multiple parts
Returns
the messageIndex field value.
Definition at line 71 of file videotitlemessage.cpp.
 {
     Q_D(const VideoTitleMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
setMessageCount()
void VideoTitleMessage::setMessageCount (const quint16 messageCount)
Sets the messageCount field to messageCount.
Parameters
messageCount The field value to set.
Definition at line 116 of file videotitlemessage.cpp.
 {
     Q_D(VideoTitleMessage);
     d->messageCount = messageCount;
 }
References messageCount().
setMessageIndex()
void VideoTitleMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 106 of file videotitlemessage.cpp.
 {
     Q_D(VideoTitleMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setText()
void VideoTitleMessage::setText (const QString text)
Sets the text field to text.
Parameters
text The field value to set.
Definition at line 126 of file videotitlemessage.cpp.
 {
     Q_D(VideoTitleMessage);
     d->text = text;
 }
References text().
text()
QString VideoTitleMessage::text () const
Returns the VideoTitleMessage data message's text field's current value.
Returns
the text field value.
Definition at line 95 of file videotitlemessage.cpp.
 {
     Q_D(const VideoTitleMessage);
     return d->text;
 }
Referenced by setText().
The documentation for this class was generated from the following files:
videotitlemessage.h
videotitlemessage.cpp