QtFit: ActivityMessage Class Reference
ActivityMessage Class Reference
The ActivityMessage class represents a FIT ActivityMessage data message.
Public Member Functions
ActivityMessage ()
Constructs a ActivityMessage object.
DateTime timestamp () const
Returns the ActivityMessage data message's timestamp field's current value.
quint32 totalTimerTime () const
Returns the ActivityMessage data message's totalTimerTime field's current value.
quint16 numSessions () const
Returns the ActivityMessage data message's numSessions field's current value.
Activity type () const
Returns the ActivityMessage data message's type field's current value.
Event event () const
Returns the ActivityMessage data message's event field's current value.
EventType eventType () const
Returns the ActivityMessage data message's eventType field's current value.
LocalDateTime localTimestamp () const
Returns the ActivityMessage data message's localTimestamp field's current value.
quint8 eventGroup () const
Returns the ActivityMessage data message's eventGroup field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setTotalTimerTime (const quint32 totalTimerTime)
Sets the totalTimerTime field to totalTimerTime.
void setNumSessions (const quint16 numSessions)
Sets the numSessions field to numSessions.
void setType (const Activity type)
Sets the type field to type.
void setEvent (const Event event)
Sets the event field to event.
void setEventType (const EventType eventType)
Sets the eventType field to eventType.
void setLocalTimestamp (const LocalDateTime localTimestamp)
Sets the localTimestamp field to localTimestamp.
void setEventGroup (const quint8 eventGroup)
Sets the eventGroup field to eventGroup.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
ActivityMessage (ActivityMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The ActivityMessage class represents a FIT ActivityMessage data message.
See also
DataMessage
Definition at line 34 of file activitymessage.h.
Constructor & Destructor Documentation
ActivityMessage() [1/2]
ActivityMessage::ActivityMessage ()
Constructs a ActivityMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file activitymessage.cpp.
                                  : AbstractDataMessage(new ActivityMessagePrivate(this))
 {
 }
ActivityMessage() [2/2]
ActivityMessage::ActivityMessage (ActivityMessagePrivate *const d) explicit protected
Constructs a ActivityMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file activitymessage.cpp.
                                                                  : AbstractDataMessage(d)
 {
 }
Member Function Documentation
event()
Event ActivityMessage::event () const
Returns the ActivityMessage data message's event field's current value.
Returns
the event field value.
Definition at line 115 of file activitymessage.cpp.
 {
     Q_D(const ActivityMessage);
     return d->event;
 }
Referenced by setEvent().
eventGroup()
quint8 ActivityMessage::eventGroup () const
Returns the ActivityMessage data message's eventGroup field's current value.
Returns
the eventGroup field value.
Definition at line 150 of file activitymessage.cpp.
 {
     Q_D(const ActivityMessage);
     return d->eventGroup;
 }
Referenced by setEventGroup().
eventType()
EventType ActivityMessage::eventType () const
Returns the ActivityMessage data message's eventType field's current value.
Returns
the eventType field value.
Definition at line 126 of file activitymessage.cpp.
 {
     Q_D(const ActivityMessage);
     return d->eventType;
 }
Referenced by setEventType().
localTimestamp()
LocalDateTime ActivityMessage::localTimestamp () const
Returns the ActivityMessage data message's localTimestamp field's current value.
timestamp epoch expressed in local time, used to convert activity timestamps to local time
Returns
the localTimestamp field value.
Definition at line 139 of file activitymessage.cpp.
 {
     Q_D(const ActivityMessage);
     return d->localTimestamp;
 }
Referenced by setLocalTimestamp().
numSessions()
quint16 ActivityMessage::numSessions () const
Returns the ActivityMessage data message's numSessions field's current value.
Returns
the numSessions field value.
Definition at line 93 of file activitymessage.cpp.
 {
     Q_D(const ActivityMessage);
     return d->numSessions;
 }
Referenced by setNumSessions().
setEvent()
void ActivityMessage::setEvent (const Event event)
Sets the event field to event.
Parameters
event The field value to set.
Definition at line 201 of file activitymessage.cpp.
 {
     Q_D(ActivityMessage);
     d->event = event;
 }
References event().
setEventGroup()
void ActivityMessage::setEventGroup (const quint8 eventGroup)
Sets the eventGroup field to eventGroup.
Parameters
eventGroup The field value to set.
Definition at line 231 of file activitymessage.cpp.
 {
     Q_D(ActivityMessage);
     d->eventGroup = eventGroup;
 }
References eventGroup().
setEventType()
void ActivityMessage::setEventType (const EventType eventType)
Sets the eventType field to eventType.
Parameters
eventType The field value to set.
Definition at line 211 of file activitymessage.cpp.
 {
     Q_D(ActivityMessage);
     d->eventType = eventType;
 }
References eventType().
setLocalTimestamp()
void ActivityMessage::setLocalTimestamp (const LocalDateTime localTimestamp)
Sets the localTimestamp field to localTimestamp.
Parameters
localTimestamp The field value to set.
Definition at line 221 of file activitymessage.cpp.
 {
     Q_D(ActivityMessage);
     d->localTimestamp = localTimestamp;
 }
References localTimestamp().
setNumSessions()
void ActivityMessage::setNumSessions (const quint16 numSessions)
Sets the numSessions field to numSessions.
Parameters
numSessions The field value to set.
Definition at line 181 of file activitymessage.cpp.
 {
     Q_D(ActivityMessage);
     d->numSessions = numSessions;
 }
References numSessions().
setTimestamp()
void ActivityMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 161 of file activitymessage.cpp.
 {
     Q_D(ActivityMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setTotalTimerTime()
void ActivityMessage::setTotalTimerTime (const quint32 totalTimerTime)
Sets the totalTimerTime field to totalTimerTime.
Parameters
totalTimerTime The field value to set.
Definition at line 171 of file activitymessage.cpp.
 {
     Q_D(ActivityMessage);
     d->totalTimerTime = totalTimerTime;
 }
References totalTimerTime().
setType()
void ActivityMessage::setType (const Activity type)
Sets the type field to type.
Parameters
type The field value to set.
Definition at line 191 of file activitymessage.cpp.
 {
     Q_D(ActivityMessage);
     d->type = type;
 }
References type().
timestamp()
DateTime ActivityMessage::timestamp () const
Returns the ActivityMessage data message's timestamp field's current value.
Returns
the timestamp field value.
Definition at line 69 of file activitymessage.cpp.
 {
     Q_D(const ActivityMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
totalTimerTime()
quint32 ActivityMessage::totalTimerTime () const
Returns the ActivityMessage data message's totalTimerTime field's current value.
Exclude pauses
Returns
the totalTimerTime field value.
Definition at line 82 of file activitymessage.cpp.
 {
     Q_D(const ActivityMessage);
     return d->totalTimerTime;
 }
Referenced by setTotalTimerTime().
type()
Activity ActivityMessage::type () const
Returns the ActivityMessage data message's type field's current value.
Returns
the type field value.
Definition at line 104 of file activitymessage.cpp.
 {
     Q_D(const ActivityMessage);
     return d->type;
 }
Referenced by setType().
The documentation for this class was generated from the following files:
activitymessage.h
activitymessage.cpp