QtFit: SessionMessage Class Reference
SessionMessage Class Reference
The SessionMessage class represents a FIT SessionMessage data message.
Public Member Functions
SessionMessage ()
Constructs a SessionMessage object.
MessageIndex messageIndex () const
Returns the SessionMessage data message's messageIndex field's current value.
DateTime timestamp () const
Returns the SessionMessage data message's timestamp field's current value.
Event event () const
Returns the SessionMessage data message's event field's current value.
EventType eventType () const
Returns the SessionMessage data message's eventType field's current value.
DateTime startTime () const
Returns the SessionMessage data message's startTime field's current value.
qint32 startPositionLat () const
Returns the SessionMessage data message's startPositionLat field's current value.
qint32 startPositionLong () const
Returns the SessionMessage data message's startPositionLong field's current value.
Sport sport () const
Returns the SessionMessage data message's sport field's current value.
SubSport subSport () const
Returns the SessionMessage data message's subSport field's current value.
quint32 totalElapsedTime () const
Returns the SessionMessage data message's totalElapsedTime field's current value.
quint32 totalTimerTime () const
Returns the SessionMessage data message's totalTimerTime field's current value.
quint32 totalDistance () const
Returns the SessionMessage data message's totalDistance field's current value.
quint32 totalCycles () const
Returns the SessionMessage data message's totalCycles field's current value.
quint16 totalCalories () const
Returns the SessionMessage data message's totalCalories field's current value.
quint16 totalFatCalories () const
Returns the SessionMessage data message's totalFatCalories field's current value.
quint16 avgSpeed () const
Returns the SessionMessage data message's avgSpeed field's current value.
quint16 maxSpeed () const
Returns the SessionMessage data message's maxSpeed field's current value.
quint8 avgHeartRate () const
Returns the SessionMessage data message's avgHeartRate field's current value.
quint8 maxHeartRate () const
Returns the SessionMessage data message's maxHeartRate field's current value.
quint8 avgCadence () const
Returns the SessionMessage data message's avgCadence field's current value.
quint8 maxCadence () const
Returns the SessionMessage data message's maxCadence field's current value.
quint16 avgPower () const
Returns the SessionMessage data message's avgPower field's current value.
quint16 maxPower () const
Returns the SessionMessage data message's maxPower field's current value.
quint16 totalAscent () const
Returns the SessionMessage data message's totalAscent field's current value.
quint16 totalDescent () const
Returns the SessionMessage data message's totalDescent field's current value.
quint8 totalTrainingEffect () const
Returns the SessionMessage data message's totalTrainingEffect field's current value.
quint16 firstLapIndex () const
Returns the SessionMessage data message's firstLapIndex field's current value.
quint16 numLaps () const
Returns the SessionMessage data message's numLaps field's current value.
quint8 eventGroup () const
Returns the SessionMessage data message's eventGroup field's current value.
SessionTrigger trigger () const
Returns the SessionMessage data message's trigger field's current value.
qint32 necLat () const
Returns the SessionMessage data message's necLat field's current value.
qint32 necLong () const
Returns the SessionMessage data message's necLong field's current value.
qint32 swcLat () const
Returns the SessionMessage data message's swcLat field's current value.
qint32 swcLong () const
Returns the SessionMessage data message's swcLong field's current value.
quint16 numLengths () const
Returns the SessionMessage data message's numLengths field's current value.
quint16 normalizedPower () const
Returns the SessionMessage data message's normalizedPower field's current value.
quint16 trainingStressScore () const
Returns the SessionMessage data message's trainingStressScore field's current value.
quint16 intensityFactor () const
Returns the SessionMessage data message's intensityFactor field's current value.
LeftRightBalance100 leftRightBalance () const
Returns the SessionMessage data message's leftRightBalance field's current value.
quint32 avgStrokeCount () const
Returns the SessionMessage data message's avgStrokeCount field's current value.
quint16 avgStrokeDistance () const
Returns the SessionMessage data message's avgStrokeDistance field's current value.
SwimStroke swimStroke () const
Returns the SessionMessage data message's swimStroke field's current value.
quint16 poolLength () const
Returns the SessionMessage data message's poolLength field's current value.
quint16 thresholdPower () const
Returns the SessionMessage data message's thresholdPower field's current value.
DisplayMeasure poolLengthUnit () const
Returns the SessionMessage data message's poolLengthUnit field's current value.
quint16 numActiveLengths () const
Returns the SessionMessage data message's numActiveLengths field's current value.
quint32 totalWork () const
Returns the SessionMessage data message's totalWork field's current value.
quint16 avgAltitude () const
Returns the SessionMessage data message's avgAltitude field's current value.
quint16 maxAltitude () const
Returns the SessionMessage data message's maxAltitude field's current value.
quint8 gpsAccuracy () const
Returns the SessionMessage data message's gpsAccuracy field's current value.
qint16 avgGrade () const
Returns the SessionMessage data message's avgGrade field's current value.
qint16 avgPosGrade () const
Returns the SessionMessage data message's avgPosGrade field's current value.
qint16 avgNegGrade () const
Returns the SessionMessage data message's avgNegGrade field's current value.
qint16 maxPosGrade () const
Returns the SessionMessage data message's maxPosGrade field's current value.
qint16 maxNegGrade () const
Returns the SessionMessage data message's maxNegGrade field's current value.
qint8 avgTemperature () const
Returns the SessionMessage data message's avgTemperature field's current value.
qint8 maxTemperature () const
Returns the SessionMessage data message's maxTemperature field's current value.
quint32 totalMovingTime () const
Returns the SessionMessage data message's totalMovingTime field's current value.
qint16 avgPosVerticalSpeed () const
Returns the SessionMessage data message's avgPosVerticalSpeed field's current value.
qint16 avgNegVerticalSpeed () const
Returns the SessionMessage data message's avgNegVerticalSpeed field's current value.
qint16 maxPosVerticalSpeed () const
Returns the SessionMessage data message's maxPosVerticalSpeed field's current value.
qint16 maxNegVerticalSpeed () const
Returns the SessionMessage data message's maxNegVerticalSpeed field's current value.
quint8 minHeartRate () const
Returns the SessionMessage data message's minHeartRate field's current value.
quint32 timeInHrZone () const
Returns the SessionMessage data message's timeInHrZone field's current value.
quint32 timeInSpeedZone () const
Returns the SessionMessage data message's timeInSpeedZone field's current value.
quint32 timeInCadenceZone () const
Returns the SessionMessage data message's timeInCadenceZone field's current value.
quint32 timeInPowerZone () const
Returns the SessionMessage data message's timeInPowerZone field's current value.
quint32 avgLapTime () const
Returns the SessionMessage data message's avgLapTime field's current value.
quint16 bestLapIndex () const
Returns the SessionMessage data message's bestLapIndex field's current value.
quint16 minAltitude () const
Returns the SessionMessage data message's minAltitude field's current value.
quint16 playerScore () const
Returns the SessionMessage data message's playerScore field's current value.
quint16 opponentScore () const
Returns the SessionMessage data message's opponentScore field's current value.
QString opponentName () const
Returns the SessionMessage data message's opponentName field's current value.
quint16 strokeCount () const
Returns the SessionMessage data message's strokeCount field's current value.
quint16 zoneCount () const
Returns the SessionMessage data message's zoneCount field's current value.
quint16 maxBallSpeed () const
Returns the SessionMessage data message's maxBallSpeed field's current value.
quint16 avgBallSpeed () const
Returns the SessionMessage data message's avgBallSpeed field's current value.
quint16 avgVerticalOscillation () const
Returns the SessionMessage data message's avgVerticalOscillation field's current value.
quint16 avgStanceTimePercent () const
Returns the SessionMessage data message's avgStanceTimePercent field's current value.
quint16 avgStanceTime () const
Returns the SessionMessage data message's avgStanceTime field's current value.
quint8 avgFractionalCadence () const
Returns the SessionMessage data message's avgFractionalCadence field's current value.
quint8 maxFractionalCadence () const
Returns the SessionMessage data message's maxFractionalCadence field's current value.
quint8 totalFractionalCycles () const
Returns the SessionMessage data message's totalFractionalCycles field's current value.
quint16 avgTotalHemoglobinConc () const
Returns the SessionMessage data message's avgTotalHemoglobinConc field's current value.
quint16 minTotalHemoglobinConc () const
Returns the SessionMessage data message's minTotalHemoglobinConc field's current value.
quint16 maxTotalHemoglobinConc () const
Returns the SessionMessage data message's maxTotalHemoglobinConc field's current value.
quint16 avgSaturatedHemoglobinPercent () const
Returns the SessionMessage data message's avgSaturatedHemoglobinPercent field's current value.
quint16 minSaturatedHemoglobinPercent () const
Returns the SessionMessage data message's minSaturatedHemoglobinPercent field's current value.
quint16 maxSaturatedHemoglobinPercent () const
Returns the SessionMessage data message's maxSaturatedHemoglobinPercent field's current value.
quint8 avgLeftTorqueEffectiveness () const
Returns the SessionMessage data message's avgLeftTorqueEffectiveness field's current value.
quint8 avgRightTorqueEffectiveness () const
Returns the SessionMessage data message's avgRightTorqueEffectiveness field's current value.
quint8 avgLeftPedalSmoothness () const
Returns the SessionMessage data message's avgLeftPedalSmoothness field's current value.
quint8 avgRightPedalSmoothness () const
Returns the SessionMessage data message's avgRightPedalSmoothness field's current value.
quint8 avgCombinedPedalSmoothness () const
Returns the SessionMessage data message's avgCombinedPedalSmoothness field's current value.
quint8 sportIndex () const
Returns the SessionMessage data message's sportIndex field's current value.
quint32 timeStanding () const
Returns the SessionMessage data message's timeStanding field's current value.
quint16 standCount () const
Returns the SessionMessage data message's standCount field's current value.
qint8 avgLeftPco () const
Returns the SessionMessage data message's avgLeftPco field's current value.
qint8 avgRightPco () const
Returns the SessionMessage data message's avgRightPco field's current value.
quint8 avgLeftPowerPhase () const
Returns the SessionMessage data message's avgLeftPowerPhase field's current value.
quint8 avgLeftPowerPhasePeak () const
Returns the SessionMessage data message's avgLeftPowerPhasePeak field's current value.
quint8 avgRightPowerPhase () const
Returns the SessionMessage data message's avgRightPowerPhase field's current value.
quint8 avgRightPowerPhasePeak () const
Returns the SessionMessage data message's avgRightPowerPhasePeak field's current value.
quint16 avgPowerPosition () const
Returns the SessionMessage data message's avgPowerPosition field's current value.
quint16 maxPowerPosition () const
Returns the SessionMessage data message's maxPowerPosition field's current value.
quint8 avgCadencePosition () const
Returns the SessionMessage data message's avgCadencePosition field's current value.
quint8 maxCadencePosition () const
Returns the SessionMessage data message's maxCadencePosition field's current value.
quint32 enhancedAvgSpeed () const
Returns the SessionMessage data message's enhancedAvgSpeed field's current value.
quint32 enhancedMaxSpeed () const
Returns the SessionMessage data message's enhancedMaxSpeed field's current value.
quint32 enhancedAvgAltitude () const
Returns the SessionMessage data message's enhancedAvgAltitude field's current value.
quint32 enhancedMinAltitude () const
Returns the SessionMessage data message's enhancedMinAltitude field's current value.
quint32 enhancedMaxAltitude () const
Returns the SessionMessage data message's enhancedMaxAltitude field's current value.
quint16 avgLevMotorPower () const
Returns the SessionMessage data message's avgLevMotorPower field's current value.
quint16 maxLevMotorPower () const
Returns the SessionMessage data message's maxLevMotorPower field's current value.
quint8 levBatteryConsumption () const
Returns the SessionMessage data message's levBatteryConsumption field's current value.
quint16 avgVerticalRatio () const
Returns the SessionMessage data message's avgVerticalRatio field's current value.
quint16 avgStanceTimeBalance () const
Returns the SessionMessage data message's avgStanceTimeBalance field's current value.
quint16 avgStepLength () const
Returns the SessionMessage data message's avgStepLength field's current value.
quint8 totalAnaerobicTrainingEffect () const
Returns the SessionMessage data message's totalAnaerobicTrainingEffect field's current value.
quint16 avgVam () const
Returns the SessionMessage data message's avgVam field's current value.
float totalGrit () const
Returns the SessionMessage data message's totalGrit field's current value.
float totalFlow () const
Returns the SessionMessage data message's totalFlow field's current value.
quint16 jumpCount () const
Returns the SessionMessage data message's jumpCount field's current value.
float avgGrit () const
Returns the SessionMessage data message's avgGrit field's current value.
float avgFlow () const
Returns the SessionMessage data message's avgFlow field's current value.
quint8 totalFractionalAscent () const
Returns the SessionMessage data message's totalFractionalAscent field's current value.
quint8 totalFractionalDescent () const
Returns the SessionMessage data message's totalFractionalDescent field's current value.
quint16 avgCoreTemperature () const
Returns the SessionMessage data message's avgCoreTemperature field's current value.
quint16 minCoreTemperature () const
Returns the SessionMessage data message's minCoreTemperature field's current value.
quint16 maxCoreTemperature () const
Returns the SessionMessage data message's maxCoreTemperature field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setEvent (const Event event)
Sets the event field to event.
void setEventType (const EventType eventType)
Sets the eventType field to eventType.
void setStartTime (const DateTime startTime)
Sets the startTime field to startTime.
void setStartPositionLat (const qint32 startPositionLat)
Sets the startPositionLat field to startPositionLat.
void setStartPositionLong (const qint32 startPositionLong)
Sets the startPositionLong field to startPositionLong.
void setSport (const Sport sport)
Sets the sport field to sport.
void setSubSport (const SubSport subSport)
Sets the subSport field to subSport.
void setTotalElapsedTime (const quint32 totalElapsedTime)
Sets the totalElapsedTime field to totalElapsedTime.
void setTotalTimerTime (const quint32 totalTimerTime)
Sets the totalTimerTime field to totalTimerTime.
void setTotalDistance (const quint32 totalDistance)
Sets the totalDistance field to totalDistance.
void setTotalCycles (const quint32 totalCycles)
Sets the totalCycles field to totalCycles.
void setTotalCalories (const quint16 totalCalories)
Sets the totalCalories field to totalCalories.
void setTotalFatCalories (const quint16 totalFatCalories)
Sets the totalFatCalories field to totalFatCalories.
void setAvgSpeed (const quint16 avgSpeed)
Sets the avgSpeed field to avgSpeed.
void setMaxSpeed (const quint16 maxSpeed)
Sets the maxSpeed field to maxSpeed.
void setAvgHeartRate (const quint8 avgHeartRate)
Sets the avgHeartRate field to avgHeartRate.
void setMaxHeartRate (const quint8 maxHeartRate)
Sets the maxHeartRate field to maxHeartRate.
void setAvgCadence (const quint8 avgCadence)
Sets the avgCadence field to avgCadence.
void setMaxCadence (const quint8 maxCadence)
Sets the maxCadence field to maxCadence.
void setAvgPower (const quint16 avgPower)
Sets the avgPower field to avgPower.
void setMaxPower (const quint16 maxPower)
Sets the maxPower field to maxPower.
void setTotalAscent (const quint16 totalAscent)
Sets the totalAscent field to totalAscent.
void setTotalDescent (const quint16 totalDescent)
Sets the totalDescent field to totalDescent.
void setTotalTrainingEffect (const quint8 totalTrainingEffect)
Sets the totalTrainingEffect field to totalTrainingEffect.
void setFirstLapIndex (const quint16 firstLapIndex)
Sets the firstLapIndex field to firstLapIndex.
void setNumLaps (const quint16 numLaps)
Sets the numLaps field to numLaps.
void setEventGroup (const quint8 eventGroup)
Sets the eventGroup field to eventGroup.
void setTrigger (const SessionTrigger trigger)
Sets the trigger field to trigger.
void setNecLat (const qint32 necLat)
Sets the necLat field to necLat.
void setNecLong (const qint32 necLong)
Sets the necLong field to necLong.
void setSwcLat (const qint32 swcLat)
Sets the swcLat field to swcLat.
void setSwcLong (const qint32 swcLong)
Sets the swcLong field to swcLong.
void setNumLengths (const quint16 numLengths)
Sets the numLengths field to numLengths.
void setNormalizedPower (const quint16 normalizedPower)
Sets the normalizedPower field to normalizedPower.
void setTrainingStressScore (const quint16 trainingStressScore)
Sets the trainingStressScore field to trainingStressScore.
void setIntensityFactor (const quint16 intensityFactor)
Sets the intensityFactor field to intensityFactor.
void setLeftRightBalance (const LeftRightBalance100 leftRightBalance)
Sets the leftRightBalance field to leftRightBalance.
void setAvgStrokeCount (const quint32 avgStrokeCount)
Sets the avgStrokeCount field to avgStrokeCount.
void setAvgStrokeDistance (const quint16 avgStrokeDistance)
Sets the avgStrokeDistance field to avgStrokeDistance.
void setSwimStroke (const SwimStroke swimStroke)
Sets the swimStroke field to swimStroke.
void setPoolLength (const quint16 poolLength)
Sets the poolLength field to poolLength.
void setThresholdPower (const quint16 thresholdPower)
Sets the thresholdPower field to thresholdPower.
void setPoolLengthUnit (const DisplayMeasure poolLengthUnit)
Sets the poolLengthUnit field to poolLengthUnit.
void setNumActiveLengths (const quint16 numActiveLengths)
Sets the numActiveLengths field to numActiveLengths.
void setTotalWork (const quint32 totalWork)
Sets the totalWork field to totalWork.
void setAvgAltitude (const quint16 avgAltitude)
Sets the avgAltitude field to avgAltitude.
void setMaxAltitude (const quint16 maxAltitude)
Sets the maxAltitude field to maxAltitude.
void setGpsAccuracy (const quint8 gpsAccuracy)
Sets the gpsAccuracy field to gpsAccuracy.
void setAvgGrade (const qint16 avgGrade)
Sets the avgGrade field to avgGrade.
void setAvgPosGrade (const qint16 avgPosGrade)
Sets the avgPosGrade field to avgPosGrade.
void setAvgNegGrade (const qint16 avgNegGrade)
Sets the avgNegGrade field to avgNegGrade.
void setMaxPosGrade (const qint16 maxPosGrade)
Sets the maxPosGrade field to maxPosGrade.
void setMaxNegGrade (const qint16 maxNegGrade)
Sets the maxNegGrade field to maxNegGrade.
void setAvgTemperature (const qint8 avgTemperature)
Sets the avgTemperature field to avgTemperature.
void setMaxTemperature (const qint8 maxTemperature)
Sets the maxTemperature field to maxTemperature.
void setTotalMovingTime (const quint32 totalMovingTime)
Sets the totalMovingTime field to totalMovingTime.
void setAvgPosVerticalSpeed (const qint16 avgPosVerticalSpeed)
Sets the avgPosVerticalSpeed field to avgPosVerticalSpeed.
void setAvgNegVerticalSpeed (const qint16 avgNegVerticalSpeed)
Sets the avgNegVerticalSpeed field to avgNegVerticalSpeed.
void setMaxPosVerticalSpeed (const qint16 maxPosVerticalSpeed)
Sets the maxPosVerticalSpeed field to maxPosVerticalSpeed.
void setMaxNegVerticalSpeed (const qint16 maxNegVerticalSpeed)
Sets the maxNegVerticalSpeed field to maxNegVerticalSpeed.
void setMinHeartRate (const quint8 minHeartRate)
Sets the minHeartRate field to minHeartRate.
void setTimeInHrZone (const quint32 timeInHrZone)
Sets the timeInHrZone field to timeInHrZone.
void setTimeInSpeedZone (const quint32 timeInSpeedZone)
Sets the timeInSpeedZone field to timeInSpeedZone.
void setTimeInCadenceZone (const quint32 timeInCadenceZone)
Sets the timeInCadenceZone field to timeInCadenceZone.
void setTimeInPowerZone (const quint32 timeInPowerZone)
Sets the timeInPowerZone field to timeInPowerZone.
void setAvgLapTime (const quint32 avgLapTime)
Sets the avgLapTime field to avgLapTime.
void setBestLapIndex (const quint16 bestLapIndex)
Sets the bestLapIndex field to bestLapIndex.
void setMinAltitude (const quint16 minAltitude)
Sets the minAltitude field to minAltitude.
void setPlayerScore (const quint16 playerScore)
Sets the playerScore field to playerScore.
void setOpponentScore (const quint16 opponentScore)
Sets the opponentScore field to opponentScore.
void setOpponentName (const QString opponentName)
Sets the opponentName field to opponentName.
void setStrokeCount (const quint16 strokeCount)
Sets the strokeCount field to strokeCount.
void setZoneCount (const quint16 zoneCount)
Sets the zoneCount field to zoneCount.
void setMaxBallSpeed (const quint16 maxBallSpeed)
Sets the maxBallSpeed field to maxBallSpeed.
void setAvgBallSpeed (const quint16 avgBallSpeed)
Sets the avgBallSpeed field to avgBallSpeed.
void setAvgVerticalOscillation (const quint16 avgVerticalOscillation)
Sets the avgVerticalOscillation field to avgVerticalOscillation.
void setAvgStanceTimePercent (const quint16 avgStanceTimePercent)
Sets the avgStanceTimePercent field to avgStanceTimePercent.
void setAvgStanceTime (const quint16 avgStanceTime)
Sets the avgStanceTime field to avgStanceTime.
void setAvgFractionalCadence (const quint8 avgFractionalCadence)
Sets the avgFractionalCadence field to avgFractionalCadence.
void setMaxFractionalCadence (const quint8 maxFractionalCadence)
Sets the maxFractionalCadence field to maxFractionalCadence.
void setTotalFractionalCycles (const quint8 totalFractionalCycles)
Sets the totalFractionalCycles field to totalFractionalCycles.
void setAvgTotalHemoglobinConc (const quint16 avgTotalHemoglobinConc)
Sets the avgTotalHemoglobinConc field to avgTotalHemoglobinConc.
void setMinTotalHemoglobinConc (const quint16 minTotalHemoglobinConc)
Sets the minTotalHemoglobinConc field to minTotalHemoglobinConc.
void setMaxTotalHemoglobinConc (const quint16 maxTotalHemoglobinConc)
Sets the maxTotalHemoglobinConc field to maxTotalHemoglobinConc.
void setAvgSaturatedHemoglobinPercent (const quint16 avgSaturatedHemoglobinPercent)
Sets the avgSaturatedHemoglobinPercent field to avgSaturatedHemoglobinPercent.
void setMinSaturatedHemoglobinPercent (const quint16 minSaturatedHemoglobinPercent)
Sets the minSaturatedHemoglobinPercent field to minSaturatedHemoglobinPercent.
void setMaxSaturatedHemoglobinPercent (const quint16 maxSaturatedHemoglobinPercent)
Sets the maxSaturatedHemoglobinPercent field to maxSaturatedHemoglobinPercent.
void setAvgLeftTorqueEffectiveness (const quint8 avgLeftTorqueEffectiveness)
Sets the avgLeftTorqueEffectiveness field to avgLeftTorqueEffectiveness.
void setAvgRightTorqueEffectiveness (const quint8 avgRightTorqueEffectiveness)
Sets the avgRightTorqueEffectiveness field to avgRightTorqueEffectiveness.
void setAvgLeftPedalSmoothness (const quint8 avgLeftPedalSmoothness)
Sets the avgLeftPedalSmoothness field to avgLeftPedalSmoothness.
void setAvgRightPedalSmoothness (const quint8 avgRightPedalSmoothness)
Sets the avgRightPedalSmoothness field to avgRightPedalSmoothness.
void setAvgCombinedPedalSmoothness (const quint8 avgCombinedPedalSmoothness)
Sets the avgCombinedPedalSmoothness field to avgCombinedPedalSmoothness.
void setSportIndex (const quint8 sportIndex)
Sets the sportIndex field to sportIndex.
void setTimeStanding (const quint32 timeStanding)
Sets the timeStanding field to timeStanding.
void setStandCount (const quint16 standCount)
Sets the standCount field to standCount.
void setAvgLeftPco (const qint8 avgLeftPco)
Sets the avgLeftPco field to avgLeftPco.
void setAvgRightPco (const qint8 avgRightPco)
Sets the avgRightPco field to avgRightPco.
void setAvgLeftPowerPhase (const quint8 avgLeftPowerPhase)
Sets the avgLeftPowerPhase field to avgLeftPowerPhase.
void setAvgLeftPowerPhasePeak (const quint8 avgLeftPowerPhasePeak)
Sets the avgLeftPowerPhasePeak field to avgLeftPowerPhasePeak.
void setAvgRightPowerPhase (const quint8 avgRightPowerPhase)
Sets the avgRightPowerPhase field to avgRightPowerPhase.
void setAvgRightPowerPhasePeak (const quint8 avgRightPowerPhasePeak)
Sets the avgRightPowerPhasePeak field to avgRightPowerPhasePeak.
void setAvgPowerPosition (const quint16 avgPowerPosition)
Sets the avgPowerPosition field to avgPowerPosition.
void setMaxPowerPosition (const quint16 maxPowerPosition)
Sets the maxPowerPosition field to maxPowerPosition.
void setAvgCadencePosition (const quint8 avgCadencePosition)
Sets the avgCadencePosition field to avgCadencePosition.
void setMaxCadencePosition (const quint8 maxCadencePosition)
Sets the maxCadencePosition field to maxCadencePosition.
void setEnhancedAvgSpeed (const quint32 enhancedAvgSpeed)
Sets the enhancedAvgSpeed field to enhancedAvgSpeed.
void setEnhancedMaxSpeed (const quint32 enhancedMaxSpeed)
Sets the enhancedMaxSpeed field to enhancedMaxSpeed.
void setEnhancedAvgAltitude (const quint32 enhancedAvgAltitude)
Sets the enhancedAvgAltitude field to enhancedAvgAltitude.
void setEnhancedMinAltitude (const quint32 enhancedMinAltitude)
Sets the enhancedMinAltitude field to enhancedMinAltitude.
void setEnhancedMaxAltitude (const quint32 enhancedMaxAltitude)
Sets the enhancedMaxAltitude field to enhancedMaxAltitude.
void setAvgLevMotorPower (const quint16 avgLevMotorPower)
Sets the avgLevMotorPower field to avgLevMotorPower.
void setMaxLevMotorPower (const quint16 maxLevMotorPower)
Sets the maxLevMotorPower field to maxLevMotorPower.
void setLevBatteryConsumption (const quint8 levBatteryConsumption)
Sets the levBatteryConsumption field to levBatteryConsumption.
void setAvgVerticalRatio (const quint16 avgVerticalRatio)
Sets the avgVerticalRatio field to avgVerticalRatio.
void setAvgStanceTimeBalance (const quint16 avgStanceTimeBalance)
Sets the avgStanceTimeBalance field to avgStanceTimeBalance.
void setAvgStepLength (const quint16 avgStepLength)
Sets the avgStepLength field to avgStepLength.
void setTotalAnaerobicTrainingEffect (const quint8 totalAnaerobicTrainingEffect)
Sets the totalAnaerobicTrainingEffect field to totalAnaerobicTrainingEffect.
void setAvgVam (const quint16 avgVam)
Sets the avgVam field to avgVam.
void setTotalGrit (const float totalGrit)
Sets the totalGrit field to totalGrit.
void setTotalFlow (const float totalFlow)
Sets the totalFlow field to totalFlow.
void setJumpCount (const quint16 jumpCount)
Sets the jumpCount field to jumpCount.
void setAvgGrit (const float avgGrit)
Sets the avgGrit field to avgGrit.
void setAvgFlow (const float avgFlow)
Sets the avgFlow field to avgFlow.
void setTotalFractionalAscent (const quint8 totalFractionalAscent)
Sets the totalFractionalAscent field to totalFractionalAscent.
void setTotalFractionalDescent (const quint8 totalFractionalDescent)
Sets the totalFractionalDescent field to totalFractionalDescent.
void setAvgCoreTemperature (const quint16 avgCoreTemperature)
Sets the avgCoreTemperature field to avgCoreTemperature.
void setMinCoreTemperature (const quint16 minCoreTemperature)
Sets the minCoreTemperature field to minCoreTemperature.
void setMaxCoreTemperature (const quint16 maxCoreTemperature)
Sets the maxCoreTemperature field to maxCoreTemperature.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
SessionMessage (SessionMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The SessionMessage class represents a FIT SessionMessage data message.
See also
DataMessage
Definition at line 39 of file sessionmessage.h.
Constructor & Destructor Documentation
SessionMessage() [1/2]
SessionMessage::SessionMessage ()
Constructs a SessionMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file sessionmessage.cpp.
                                : AbstractDataMessage(new SessionMessagePrivate(this))
 {
 }
SessionMessage() [2/2]
SessionMessage::SessionMessage (SessionMessagePrivate *const d) explicit protected
Constructs a SessionMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file sessionmessage.cpp.
                                                               : AbstractDataMessage(d)
 {
 }
Member Function Documentation
avgAltitude()
quint16 SessionMessage::avgAltitude () const
Returns the SessionMessage data message's avgAltitude field's current value.
Returns
the avgAltitude field value.
Definition at line 625 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgAltitude;
 }
Referenced by setAvgAltitude().
avgBallSpeed()
quint16 SessionMessage::avgBallSpeed () const
Returns the SessionMessage data message's avgBallSpeed field's current value.
Returns
the avgBallSpeed field value.
Definition at line 948 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgBallSpeed;
 }
Referenced by setAvgBallSpeed().
avgCadence()
quint8 SessionMessage::avgCadence () const
Returns the SessionMessage data message's avgCadence field's current value.
total_cycles / total_timer_time if non_zero_avg_cadence otherwise total_cycles / total_elapsed_time
Returns
the avgCadence field value.
Definition at line 302 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgCadence;
 }
Referenced by setAvgCadence().
avgCadencePosition()
quint8 SessionMessage::avgCadencePosition () const
Returns the SessionMessage data message's avgCadencePosition field's current value.
Average cadence by position. Data value indexes defined by rider_position_type.
Returns
the avgCadencePosition field value.
Definition at line 1307 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgCadencePosition;
 }
Referenced by setAvgCadencePosition().
avgCombinedPedalSmoothness()
quint8 SessionMessage::avgCombinedPedalSmoothness () const
Returns the SessionMessage data message's avgCombinedPedalSmoothness field's current value.
Returns
the avgCombinedPedalSmoothness field value.
Definition at line 1153 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgCombinedPedalSmoothness;
 }
Referenced by setAvgCombinedPedalSmoothness().
avgCoreTemperature()
quint16 SessionMessage::avgCoreTemperature () const
Returns the SessionMessage data message's avgCoreTemperature field's current value.
Returns
the avgCoreTemperature field value.
Definition at line 1575 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgCoreTemperature;
 }
Referenced by setAvgCoreTemperature().
avgFlow()
float SessionMessage::avgFlow () const
Returns the SessionMessage data message's avgFlow field's current value.
The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.
Returns
the avgFlow field value.
Definition at line 1538 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgFlow;
 }
Referenced by setAvgFlow().
avgFractionalCadence()
quint8 SessionMessage::avgFractionalCadence () const
Returns the SessionMessage data message's avgFractionalCadence field's current value.
fractional part of the avg_cadence
Returns
the avgFractionalCadence field value.
Definition at line 994 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgFractionalCadence;
 }
Referenced by setAvgFractionalCadence().
avgGrade()
qint16 SessionMessage::avgGrade () const
Returns the SessionMessage data message's avgGrade field's current value.
Returns
the avgGrade field value.
Definition at line 658 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgGrade;
 }
Referenced by setAvgGrade().
avgGrit()
float SessionMessage::avgGrit () const
Returns the SessionMessage data message's avgGrit field's current value.
The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.
Returns
the avgGrit field value.
Definition at line 1524 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgGrit;
 }
Referenced by setAvgGrit().
avgHeartRate()
quint8 SessionMessage::avgHeartRate () const
Returns the SessionMessage data message's avgHeartRate field's current value.
average heart rate (excludes pause time)
Returns
the avgHeartRate field value.
Definition at line 277 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgHeartRate;
 }
Referenced by setAvgHeartRate().
avgLapTime()
quint32 SessionMessage::avgLapTime () const
Returns the SessionMessage data message's avgLapTime field's current value.
Returns
the avgLapTime field value.
Definition at line 845 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgLapTime;
 }
Referenced by setAvgLapTime().
avgLeftPco()
qint8 SessionMessage::avgLeftPco () const
Returns the SessionMessage data message's avgLeftPco field's current value.
Average platform center offset Left
Returns
the avgLeftPco field value.
Definition at line 1203 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgLeftPco;
 }
Referenced by setAvgLeftPco().
avgLeftPedalSmoothness()
quint8 SessionMessage::avgLeftPedalSmoothness () const
Returns the SessionMessage data message's avgLeftPedalSmoothness field's current value.
Returns
the avgLeftPedalSmoothness field value.
Definition at line 1131 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgLeftPedalSmoothness;
 }
Referenced by setAvgLeftPedalSmoothness().
avgLeftPowerPhase()
quint8 SessionMessage::avgLeftPowerPhase () const
Returns the SessionMessage data message's avgLeftPowerPhase field's current value.
Average left power phase angles. Indexes defined by power_phase_type.
Returns
the avgLeftPowerPhase field value.
Definition at line 1229 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgLeftPowerPhase;
 }
Referenced by setAvgLeftPowerPhase().
avgLeftPowerPhasePeak()
quint8 SessionMessage::avgLeftPowerPhasePeak () const
Returns the SessionMessage data message's avgLeftPowerPhasePeak field's current value.
Average left power phase peak angles. Data value indexes defined by power_phase_type.
Returns
the avgLeftPowerPhasePeak field value.
Definition at line 1242 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgLeftPowerPhasePeak;
 }
Referenced by setAvgLeftPowerPhasePeak().
avgLeftTorqueEffectiveness()
quint8 SessionMessage::avgLeftTorqueEffectiveness () const
Returns the SessionMessage data message's avgLeftTorqueEffectiveness field's current value.
Returns
the avgLeftTorqueEffectiveness field value.
Definition at line 1109 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgLeftTorqueEffectiveness;
 }
Referenced by setAvgLeftTorqueEffectiveness().
avgLevMotorPower()
quint16 SessionMessage::avgLevMotorPower () const
Returns the SessionMessage data message's avgLevMotorPower field's current value.
lev average motor power during session
Returns
the avgLevMotorPower field value.
Definition at line 1390 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgLevMotorPower;
 }
Referenced by setAvgLevMotorPower().
avgNegGrade()
qint16 SessionMessage::avgNegGrade () const
Returns the SessionMessage data message's avgNegGrade field's current value.
Returns
the avgNegGrade field value.
Definition at line 680 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgNegGrade;
 }
Referenced by setAvgNegGrade().
avgNegVerticalSpeed()
qint16 SessionMessage::avgNegVerticalSpeed () const
Returns the SessionMessage data message's avgNegVerticalSpeed field's current value.
Returns
the avgNegVerticalSpeed field value.
Definition at line 757 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgNegVerticalSpeed;
 }
Referenced by setAvgNegVerticalSpeed().
avgPosGrade()
qint16 SessionMessage::avgPosGrade () const
Returns the SessionMessage data message's avgPosGrade field's current value.
Returns
the avgPosGrade field value.
Definition at line 669 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgPosGrade;
 }
Referenced by setAvgPosGrade().
avgPosVerticalSpeed()
qint16 SessionMessage::avgPosVerticalSpeed () const
Returns the SessionMessage data message's avgPosVerticalSpeed field's current value.
Returns
the avgPosVerticalSpeed field value.
Definition at line 746 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgPosVerticalSpeed;
 }
Referenced by setAvgPosVerticalSpeed().
avgPower()
quint16 SessionMessage::avgPower () const
Returns the SessionMessage data message's avgPower field's current value.
total_power / total_timer_time if non_zero_avg_power otherwise total_power / total_elapsed_time
Returns
the avgPower field value.
Definition at line 327 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgPower;
 }
Referenced by setAvgPower().
avgPowerPosition()
quint16 SessionMessage::avgPowerPosition () const
Returns the SessionMessage data message's avgPowerPosition field's current value.
Average power by position. Data value indexes defined by rider_position_type.
Returns
the avgPowerPosition field value.
Definition at line 1281 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgPowerPosition;
 }
Referenced by setAvgPowerPosition().
avgRightPco()
qint8 SessionMessage::avgRightPco () const
Returns the SessionMessage data message's avgRightPco field's current value.
Average platform center offset Right
Returns
the avgRightPco field value.
Definition at line 1216 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgRightPco;
 }
Referenced by setAvgRightPco().
avgRightPedalSmoothness()
quint8 SessionMessage::avgRightPedalSmoothness () const
Returns the SessionMessage data message's avgRightPedalSmoothness field's current value.
Returns
the avgRightPedalSmoothness field value.
Definition at line 1142 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgRightPedalSmoothness;
 }
Referenced by setAvgRightPedalSmoothness().
avgRightPowerPhase()
quint8 SessionMessage::avgRightPowerPhase () const
Returns the SessionMessage data message's avgRightPowerPhase field's current value.
Average right power phase angles. Data value indexes defined by power_phase_type.
Returns
the avgRightPowerPhase field value.
Definition at line 1255 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgRightPowerPhase;
 }
Referenced by setAvgRightPowerPhase().
avgRightPowerPhasePeak()
quint8 SessionMessage::avgRightPowerPhasePeak () const
Returns the SessionMessage data message's avgRightPowerPhasePeak field's current value.
Average right power phase peak angles data value indexes defined by power_phase_type.
Returns
the avgRightPowerPhasePeak field value.
Definition at line 1268 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgRightPowerPhasePeak;
 }
Referenced by setAvgRightPowerPhasePeak().
avgRightTorqueEffectiveness()
quint8 SessionMessage::avgRightTorqueEffectiveness () const
Returns the SessionMessage data message's avgRightTorqueEffectiveness field's current value.
Returns
the avgRightTorqueEffectiveness field value.
Definition at line 1120 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgRightTorqueEffectiveness;
 }
Referenced by setAvgRightTorqueEffectiveness().
avgSaturatedHemoglobinPercent()
quint16 SessionMessage::avgSaturatedHemoglobinPercent () const
Returns the SessionMessage data message's avgSaturatedHemoglobinPercent field's current value.
Avg percentage of hemoglobin saturated with oxygen
Returns
the avgSaturatedHemoglobinPercent field value.
Definition at line 1072 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgSaturatedHemoglobinPercent;
 }
Referenced by setAvgSaturatedHemoglobinPercent().
avgSpeed()
quint16 SessionMessage::avgSpeed () const
Returns the SessionMessage data message's avgSpeed field's current value.
total_distance / total_timer_time
Returns
the avgSpeed field value.
Definition at line 253 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgSpeed;
 }
Referenced by setAvgSpeed().
avgStanceTime()
quint16 SessionMessage::avgStanceTime () const
Returns the SessionMessage data message's avgStanceTime field's current value.
Returns
the avgStanceTime field value.
Definition at line 981 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgStanceTime;
 }
Referenced by setAvgStanceTime().
avgStanceTimeBalance()
quint16 SessionMessage::avgStanceTimeBalance () const
Returns the SessionMessage data message's avgStanceTimeBalance field's current value.
Returns
the avgStanceTimeBalance field value.
Definition at line 1438 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgStanceTimeBalance;
 }
Referenced by setAvgStanceTimeBalance().
avgStanceTimePercent()
quint16 SessionMessage::avgStanceTimePercent () const
Returns the SessionMessage data message's avgStanceTimePercent field's current value.
Returns
the avgStanceTimePercent field value.
Definition at line 970 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgStanceTimePercent;
 }
Referenced by setAvgStanceTimePercent().
avgStepLength()
quint16 SessionMessage::avgStepLength () const
Returns the SessionMessage data message's avgStepLength field's current value.
Returns
the avgStepLength field value.
Definition at line 1449 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgStepLength;
 }
Referenced by setAvgStepLength().
avgStrokeCount()
quint32 SessionMessage::avgStrokeCount () const
Returns the SessionMessage data message's avgStrokeCount field's current value.
Returns
the avgStrokeCount field value.
Definition at line 535 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgStrokeCount;
 }
Referenced by setAvgStrokeCount().
avgStrokeDistance()
quint16 SessionMessage::avgStrokeDistance () const
Returns the SessionMessage data message's avgStrokeDistance field's current value.
Returns
the avgStrokeDistance field value.
Definition at line 546 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgStrokeDistance;
 }
Referenced by setAvgStrokeDistance().
avgTemperature()
qint8 SessionMessage::avgTemperature () const
Returns the SessionMessage data message's avgTemperature field's current value.
Returns
the avgTemperature field value.
Definition at line 713 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgTemperature;
 }
Referenced by setAvgTemperature().
avgTotalHemoglobinConc()
quint16 SessionMessage::avgTotalHemoglobinConc () const
Returns the SessionMessage data message's avgTotalHemoglobinConc field's current value.
Avg saturated and unsaturated hemoglobin
Returns
the avgTotalHemoglobinConc field value.
Definition at line 1033 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgTotalHemoglobinConc;
 }
Referenced by setAvgTotalHemoglobinConc().
avgVam()
quint16 SessionMessage::avgVam () const
Returns the SessionMessage data message's avgVam field's current value.
Returns
the avgVam field value.
Definition at line 1471 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgVam;
 }
Referenced by setAvgVam().
avgVerticalOscillation()
quint16 SessionMessage::avgVerticalOscillation () const
Returns the SessionMessage data message's avgVerticalOscillation field's current value.
Returns
the avgVerticalOscillation field value.
Definition at line 959 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgVerticalOscillation;
 }
Referenced by setAvgVerticalOscillation().
avgVerticalRatio()
quint16 SessionMessage::avgVerticalRatio () const
Returns the SessionMessage data message's avgVerticalRatio field's current value.
Returns
the avgVerticalRatio field value.
Definition at line 1427 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->avgVerticalRatio;
 }
Referenced by setAvgVerticalRatio().
bestLapIndex()
quint16 SessionMessage::bestLapIndex () const
Returns the SessionMessage data message's bestLapIndex field's current value.
Returns
the bestLapIndex field value.
Definition at line 856 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->bestLapIndex;
 }
Referenced by setBestLapIndex().
enhancedAvgAltitude()
quint32 SessionMessage::enhancedAvgAltitude () const
Returns the SessionMessage data message's enhancedAvgAltitude field's current value.
Returns
the enhancedAvgAltitude field value.
Definition at line 1355 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->enhancedAvgAltitude;
 }
Referenced by setEnhancedAvgAltitude().
enhancedAvgSpeed()
quint32 SessionMessage::enhancedAvgSpeed () const
Returns the SessionMessage data message's enhancedAvgSpeed field's current value.
total_distance / total_timer_time
Returns
the enhancedAvgSpeed field value.
Definition at line 1333 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->enhancedAvgSpeed;
 }
Referenced by setEnhancedAvgSpeed().
enhancedMaxAltitude()
quint32 SessionMessage::enhancedMaxAltitude () const
Returns the SessionMessage data message's enhancedMaxAltitude field's current value.
Returns
the enhancedMaxAltitude field value.
Definition at line 1377 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->enhancedMaxAltitude;
 }
Referenced by setEnhancedMaxAltitude().
enhancedMaxSpeed()
quint32 SessionMessage::enhancedMaxSpeed () const
Returns the SessionMessage data message's enhancedMaxSpeed field's current value.
Returns
the enhancedMaxSpeed field value.
Definition at line 1344 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->enhancedMaxSpeed;
 }
Referenced by setEnhancedMaxSpeed().
enhancedMinAltitude()
quint32 SessionMessage::enhancedMinAltitude () const
Returns the SessionMessage data message's enhancedMinAltitude field's current value.
Returns
the enhancedMinAltitude field value.
Definition at line 1366 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->enhancedMinAltitude;
 }
Referenced by setEnhancedMinAltitude().
event()
Event SessionMessage::event () const
Returns the SessionMessage data message's event field's current value.
session
Returns
the event field value.
Definition at line 102 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->event;
 }
Referenced by setEvent().
eventGroup()
quint8 SessionMessage::eventGroup () const
Returns the SessionMessage data message's eventGroup field's current value.
Returns
the eventGroup field value.
Definition at line 404 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->eventGroup;
 }
Referenced by setEventGroup().
eventType()
EventType SessionMessage::eventType () const
Returns the SessionMessage data message's eventType field's current value.
stop
Returns
the eventType field value.
Definition at line 115 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->eventType;
 }
Referenced by setEventType().
firstLapIndex()
quint16 SessionMessage::firstLapIndex () const
Returns the SessionMessage data message's firstLapIndex field's current value.
Returns
the firstLapIndex field value.
Definition at line 382 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->firstLapIndex;
 }
Referenced by setFirstLapIndex().
gpsAccuracy()
quint8 SessionMessage::gpsAccuracy () const
Returns the SessionMessage data message's gpsAccuracy field's current value.
Returns
the gpsAccuracy field value.
Definition at line 647 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->gpsAccuracy;
 }
Referenced by setGpsAccuracy().
intensityFactor()
quint16 SessionMessage::intensityFactor () const
Returns the SessionMessage data message's intensityFactor field's current value.
Returns
the intensityFactor field value.
Definition at line 513 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->intensityFactor;
 }
Referenced by setIntensityFactor().
jumpCount()
quint16 SessionMessage::jumpCount () const
Returns the SessionMessage data message's jumpCount field's current value.
Returns
the jumpCount field value.
Definition at line 1510 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->jumpCount;
 }
Referenced by setJumpCount().
leftRightBalance()
LeftRightBalance100 SessionMessage::leftRightBalance () const
Returns the SessionMessage data message's leftRightBalance field's current value.
Returns
the leftRightBalance field value.
Definition at line 524 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->leftRightBalance;
 }
Referenced by setLeftRightBalance().
levBatteryConsumption()
quint8 SessionMessage::levBatteryConsumption () const
Returns the SessionMessage data message's levBatteryConsumption field's current value.
lev battery consumption during session
Returns
the levBatteryConsumption field value.
Definition at line 1416 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->levBatteryConsumption;
 }
Referenced by setLevBatteryConsumption().
maxAltitude()
quint16 SessionMessage::maxAltitude () const
Returns the SessionMessage data message's maxAltitude field's current value.
Returns
the maxAltitude field value.
Definition at line 636 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->maxAltitude;
 }
Referenced by setMaxAltitude().
maxBallSpeed()
quint16 SessionMessage::maxBallSpeed () const
Returns the SessionMessage data message's maxBallSpeed field's current value.
Returns
the maxBallSpeed field value.
Definition at line 937 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->maxBallSpeed;
 }
Referenced by setMaxBallSpeed().
maxCadence()
quint8 SessionMessage::maxCadence () const
Returns the SessionMessage data message's maxCadence field's current value.
Returns
the maxCadence field value.
Definition at line 313 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->maxCadence;
 }
Referenced by setMaxCadence().
maxCadencePosition()
quint8 SessionMessage::maxCadencePosition () const
Returns the SessionMessage data message's maxCadencePosition field's current value.
Maximum cadence by position. Data value indexes defined by rider_position_type.
Returns
the maxCadencePosition field value.
Definition at line 1320 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->maxCadencePosition;
 }
Referenced by setMaxCadencePosition().
maxCoreTemperature()
quint16 SessionMessage::maxCoreTemperature () const
Returns the SessionMessage data message's maxCoreTemperature field's current value.
Returns
the maxCoreTemperature field value.
Definition at line 1597 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->maxCoreTemperature;
 }
Referenced by setMaxCoreTemperature().
maxFractionalCadence()
quint8 SessionMessage::maxFractionalCadence () const
Returns the SessionMessage data message's maxFractionalCadence field's current value.
fractional part of the max_cadence
Returns
the maxFractionalCadence field value.
Definition at line 1007 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->maxFractionalCadence;
 }
Referenced by setMaxFractionalCadence().
maxHeartRate()
quint8 SessionMessage::maxHeartRate () const
Returns the SessionMessage data message's maxHeartRate field's current value.
Returns
the maxHeartRate field value.
Definition at line 288 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->maxHeartRate;
 }
Referenced by setMaxHeartRate().
maxLevMotorPower()
quint16 SessionMessage::maxLevMotorPower () const
Returns the SessionMessage data message's maxLevMotorPower field's current value.
lev maximum motor power during session
Returns
the maxLevMotorPower field value.
Definition at line 1403 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->maxLevMotorPower;
 }
Referenced by setMaxLevMotorPower().
maxNegGrade()
qint16 SessionMessage::maxNegGrade () const
Returns the SessionMessage data message's maxNegGrade field's current value.
Returns
the maxNegGrade field value.
Definition at line 702 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->maxNegGrade;
 }
Referenced by setMaxNegGrade().
maxNegVerticalSpeed()
qint16 SessionMessage::maxNegVerticalSpeed () const
Returns the SessionMessage data message's maxNegVerticalSpeed field's current value.
Returns
the maxNegVerticalSpeed field value.
Definition at line 779 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->maxNegVerticalSpeed;
 }
Referenced by setMaxNegVerticalSpeed().
maxPosGrade()
qint16 SessionMessage::maxPosGrade () const
Returns the SessionMessage data message's maxPosGrade field's current value.
Returns
the maxPosGrade field value.
Definition at line 691 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->maxPosGrade;
 }
Referenced by setMaxPosGrade().
maxPosVerticalSpeed()
qint16 SessionMessage::maxPosVerticalSpeed () const
Returns the SessionMessage data message's maxPosVerticalSpeed field's current value.
Returns
the maxPosVerticalSpeed field value.
Definition at line 768 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->maxPosVerticalSpeed;
 }
Referenced by setMaxPosVerticalSpeed().
maxPower()
quint16 SessionMessage::maxPower () const
Returns the SessionMessage data message's maxPower field's current value.
Returns
the maxPower field value.
Definition at line 338 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->maxPower;
 }
Referenced by setMaxPower().
maxPowerPosition()
quint16 SessionMessage::maxPowerPosition () const
Returns the SessionMessage data message's maxPowerPosition field's current value.
Maximum power by position. Data value indexes defined by rider_position_type.
Returns
the maxPowerPosition field value.
Definition at line 1294 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->maxPowerPosition;
 }
Referenced by setMaxPowerPosition().
maxSaturatedHemoglobinPercent()
quint16 SessionMessage::maxSaturatedHemoglobinPercent () const
Returns the SessionMessage data message's maxSaturatedHemoglobinPercent field's current value.
Max percentage of hemoglobin saturated with oxygen
Returns
the maxSaturatedHemoglobinPercent field value.
Definition at line 1098 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->maxSaturatedHemoglobinPercent;
 }
Referenced by setMaxSaturatedHemoglobinPercent().
maxSpeed()
quint16 SessionMessage::maxSpeed () const
Returns the SessionMessage data message's maxSpeed field's current value.
Returns
the maxSpeed field value.
Definition at line 264 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->maxSpeed;
 }
Referenced by setMaxSpeed().
maxTemperature()
qint8 SessionMessage::maxTemperature () const
Returns the SessionMessage data message's maxTemperature field's current value.
Returns
the maxTemperature field value.
Definition at line 724 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->maxTemperature;
 }
Referenced by setMaxTemperature().
maxTotalHemoglobinConc()
quint16 SessionMessage::maxTotalHemoglobinConc () const
Returns the SessionMessage data message's maxTotalHemoglobinConc field's current value.
Max saturated and unsaturated hemoglobin
Returns
the maxTotalHemoglobinConc field value.
Definition at line 1059 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->maxTotalHemoglobinConc;
 }
Referenced by setMaxTotalHemoglobinConc().
messageIndex()
MessageIndex SessionMessage::messageIndex () const
Returns the SessionMessage data message's messageIndex field's current value.
Selected bit is set for the current session.
Returns
the messageIndex field value.
Definition at line 76 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
minAltitude()
quint16 SessionMessage::minAltitude () const
Returns the SessionMessage data message's minAltitude field's current value.
Returns
the minAltitude field value.
Definition at line 867 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->minAltitude;
 }
Referenced by setMinAltitude().
minCoreTemperature()
quint16 SessionMessage::minCoreTemperature () const
Returns the SessionMessage data message's minCoreTemperature field's current value.
Returns
the minCoreTemperature field value.
Definition at line 1586 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->minCoreTemperature;
 }
Referenced by setMinCoreTemperature().
minHeartRate()
quint8 SessionMessage::minHeartRate () const
Returns the SessionMessage data message's minHeartRate field's current value.
Returns
the minHeartRate field value.
Definition at line 790 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->minHeartRate;
 }
Referenced by setMinHeartRate().
minSaturatedHemoglobinPercent()
quint16 SessionMessage::minSaturatedHemoglobinPercent () const
Returns the SessionMessage data message's minSaturatedHemoglobinPercent field's current value.
Min percentage of hemoglobin saturated with oxygen
Returns
the minSaturatedHemoglobinPercent field value.
Definition at line 1085 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->minSaturatedHemoglobinPercent;
 }
Referenced by setMinSaturatedHemoglobinPercent().
minTotalHemoglobinConc()
quint16 SessionMessage::minTotalHemoglobinConc () const
Returns the SessionMessage data message's minTotalHemoglobinConc field's current value.
Min saturated and unsaturated hemoglobin
Returns
the minTotalHemoglobinConc field value.
Definition at line 1046 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->minTotalHemoglobinConc;
 }
Referenced by setMinTotalHemoglobinConc().
necLat()
qint32 SessionMessage::necLat () const
Returns the SessionMessage data message's necLat field's current value.
North east corner latitude
Returns
the necLat field value.
Definition at line 428 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->necLat;
 }
Referenced by setNecLat().
necLong()
qint32 SessionMessage::necLong () const
Returns the SessionMessage data message's necLong field's current value.
North east corner longitude
Returns
the necLong field value.
Definition at line 441 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->necLong;
 }
Referenced by setNecLong().
normalizedPower()
quint16 SessionMessage::normalizedPower () const
Returns the SessionMessage data message's normalizedPower field's current value.
Returns
the normalizedPower field value.
Definition at line 491 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->normalizedPower;
 }
Referenced by setNormalizedPower().
numActiveLengths()
quint16 SessionMessage::numActiveLengths () const
Returns the SessionMessage data message's numActiveLengths field's current value.
of active lengths of swim pool
Returns
the numActiveLengths field value.
Definition at line 603 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->numActiveLengths;
 }
Referenced by setNumActiveLengths().
numLaps()
quint16 SessionMessage::numLaps () const
Returns the SessionMessage data message's numLaps field's current value.
Returns
the numLaps field value.
Definition at line 393 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->numLaps;
 }
Referenced by setNumLaps().
numLengths()
quint16 SessionMessage::numLengths () const
Returns the SessionMessage data message's numLengths field's current value.
of lengths of swim pool
Returns
the numLengths field value.
Definition at line 480 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->numLengths;
 }
Referenced by setNumLengths().
opponentName()
QString SessionMessage::opponentName () const
Returns the SessionMessage data message's opponentName field's current value.
Returns
the opponentName field value.
Definition at line 900 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->opponentName;
 }
Referenced by setOpponentName().
opponentScore()
quint16 SessionMessage::opponentScore () const
Returns the SessionMessage data message's opponentScore field's current value.
Returns
the opponentScore field value.
Definition at line 889 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->opponentScore;
 }
Referenced by setOpponentScore().
playerScore()
quint16 SessionMessage::playerScore () const
Returns the SessionMessage data message's playerScore field's current value.
Returns
the playerScore field value.
Definition at line 878 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->playerScore;
 }
Referenced by setPlayerScore().
poolLength()
quint16 SessionMessage::poolLength () const
Returns the SessionMessage data message's poolLength field's current value.
Returns
the poolLength field value.
Definition at line 568 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->poolLength;
 }
Referenced by setPoolLength().
poolLengthUnit()
DisplayMeasure SessionMessage::poolLengthUnit () const
Returns the SessionMessage data message's poolLengthUnit field's current value.
Returns
the poolLengthUnit field value.
Definition at line 590 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->poolLengthUnit;
 }
Referenced by setPoolLengthUnit().
setAvgAltitude()
void SessionMessage::setAvgAltitude (const quint16 avgAltitude)
Sets the avgAltitude field to avgAltitude.
Parameters
avgAltitude The field value to set.
Definition at line 2078 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgAltitude = avgAltitude;
 }
References avgAltitude().
setAvgBallSpeed()
void SessionMessage::setAvgBallSpeed (const quint16 avgBallSpeed)
Sets the avgBallSpeed field to avgBallSpeed.
Parameters
avgBallSpeed The field value to set.
Definition at line 2368 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgBallSpeed = avgBallSpeed;
 }
References avgBallSpeed().
setAvgCadence()
void SessionMessage::setAvgCadence (const quint8 avgCadence)
Sets the avgCadence field to avgCadence.
Parameters
avgCadence The field value to set.
Definition at line 1798 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgCadence = avgCadence;
 }
References avgCadence().
setAvgCadencePosition()
void SessionMessage::setAvgCadencePosition (const quint8 avgCadencePosition)
Sets the avgCadencePosition field to avgCadencePosition.
Parameters
avgCadencePosition The field value to set.
Definition at line 2658 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgCadencePosition = avgCadencePosition;
 }
References avgCadencePosition().
setAvgCombinedPedalSmoothness()
void SessionMessage::setAvgCombinedPedalSmoothness (const quint8 avgCombinedPedalSmoothness)
Sets the avgCombinedPedalSmoothness field to avgCombinedPedalSmoothness.
Parameters
avgCombinedPedalSmoothness The field value to set.
Definition at line 2538 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgCombinedPedalSmoothness = avgCombinedPedalSmoothness;
 }
References avgCombinedPedalSmoothness().
setAvgCoreTemperature()
void SessionMessage::setAvgCoreTemperature (const quint16 avgCoreTemperature)
Sets the avgCoreTemperature field to avgCoreTemperature.
Parameters
avgCoreTemperature The field value to set.
Definition at line 2878 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgCoreTemperature = avgCoreTemperature;
 }
References avgCoreTemperature().
setAvgFlow()
void SessionMessage::setAvgFlow (const float avgFlow)
Sets the avgFlow field to avgFlow.
Parameters
avgFlow The field value to set.
Definition at line 2848 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgFlow = avgFlow;
 }
References avgFlow().
setAvgFractionalCadence()
void SessionMessage::setAvgFractionalCadence (const quint8 avgFractionalCadence)
Sets the avgFractionalCadence field to avgFractionalCadence.
Parameters
avgFractionalCadence The field value to set.
Definition at line 2408 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgFractionalCadence = avgFractionalCadence;
 }
References avgFractionalCadence().
setAvgGrade()
void SessionMessage::setAvgGrade (const qint16 avgGrade)
Sets the avgGrade field to avgGrade.
Parameters
avgGrade The field value to set.
Definition at line 2108 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgGrade = avgGrade;
 }
References avgGrade().
setAvgGrit()
void SessionMessage::setAvgGrit (const float avgGrit)
Sets the avgGrit field to avgGrit.
Parameters
avgGrit The field value to set.
Definition at line 2838 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgGrit = avgGrit;
 }
References avgGrit().
setAvgHeartRate()
void SessionMessage::setAvgHeartRate (const quint8 avgHeartRate)
Sets the avgHeartRate field to avgHeartRate.
Parameters
avgHeartRate The field value to set.
Definition at line 1778 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgHeartRate = avgHeartRate;
 }
References avgHeartRate().
setAvgLapTime()
void SessionMessage::setAvgLapTime (const quint32 avgLapTime)
Sets the avgLapTime field to avgLapTime.
Parameters
avgLapTime The field value to set.
Definition at line 2278 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgLapTime = avgLapTime;
 }
References avgLapTime().
setAvgLeftPco()
void SessionMessage::setAvgLeftPco (const qint8 avgLeftPco)
Sets the avgLeftPco field to avgLeftPco.
Parameters
avgLeftPco The field value to set.
Definition at line 2578 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgLeftPco = avgLeftPco;
 }
References avgLeftPco().
setAvgLeftPedalSmoothness()
void SessionMessage::setAvgLeftPedalSmoothness (const quint8 avgLeftPedalSmoothness)
Sets the avgLeftPedalSmoothness field to avgLeftPedalSmoothness.
Parameters
avgLeftPedalSmoothness The field value to set.
Definition at line 2518 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgLeftPedalSmoothness = avgLeftPedalSmoothness;
 }
References avgLeftPedalSmoothness().
setAvgLeftPowerPhase()
void SessionMessage::setAvgLeftPowerPhase (const quint8 avgLeftPowerPhase)
Sets the avgLeftPowerPhase field to avgLeftPowerPhase.
Parameters
avgLeftPowerPhase The field value to set.
Definition at line 2598 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgLeftPowerPhase = avgLeftPowerPhase;
 }
References avgLeftPowerPhase().
setAvgLeftPowerPhasePeak()
void SessionMessage::setAvgLeftPowerPhasePeak (const quint8 avgLeftPowerPhasePeak)
Sets the avgLeftPowerPhasePeak field to avgLeftPowerPhasePeak.
Parameters
avgLeftPowerPhasePeak The field value to set.
Definition at line 2608 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgLeftPowerPhasePeak = avgLeftPowerPhasePeak;
 }
References avgLeftPowerPhasePeak().
setAvgLeftTorqueEffectiveness()
void SessionMessage::setAvgLeftTorqueEffectiveness (const quint8 avgLeftTorqueEffectiveness)
Sets the avgLeftTorqueEffectiveness field to avgLeftTorqueEffectiveness.
Parameters
avgLeftTorqueEffectiveness The field value to set.
Definition at line 2498 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgLeftTorqueEffectiveness = avgLeftTorqueEffectiveness;
 }
References avgLeftTorqueEffectiveness().
setAvgLevMotorPower()
void SessionMessage::setAvgLevMotorPower (const quint16 avgLevMotorPower)
Sets the avgLevMotorPower field to avgLevMotorPower.
Parameters
avgLevMotorPower The field value to set.
Definition at line 2728 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgLevMotorPower = avgLevMotorPower;
 }
References avgLevMotorPower().
setAvgNegGrade()
void SessionMessage::setAvgNegGrade (const qint16 avgNegGrade)
Sets the avgNegGrade field to avgNegGrade.
Parameters
avgNegGrade The field value to set.
Definition at line 2128 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgNegGrade = avgNegGrade;
 }
References avgNegGrade().
setAvgNegVerticalSpeed()
void SessionMessage::setAvgNegVerticalSpeed (const qint16 avgNegVerticalSpeed)
Sets the avgNegVerticalSpeed field to avgNegVerticalSpeed.
Parameters
avgNegVerticalSpeed The field value to set.
Definition at line 2198 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgNegVerticalSpeed = avgNegVerticalSpeed;
 }
References avgNegVerticalSpeed().
setAvgPosGrade()
void SessionMessage::setAvgPosGrade (const qint16 avgPosGrade)
Sets the avgPosGrade field to avgPosGrade.
Parameters
avgPosGrade The field value to set.
Definition at line 2118 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgPosGrade = avgPosGrade;
 }
References avgPosGrade().
setAvgPosVerticalSpeed()
void SessionMessage::setAvgPosVerticalSpeed (const qint16 avgPosVerticalSpeed)
Sets the avgPosVerticalSpeed field to avgPosVerticalSpeed.
Parameters
avgPosVerticalSpeed The field value to set.
Definition at line 2188 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgPosVerticalSpeed = avgPosVerticalSpeed;
 }
References avgPosVerticalSpeed().
setAvgPower()
void SessionMessage::setAvgPower (const quint16 avgPower)
Sets the avgPower field to avgPower.
Parameters
avgPower The field value to set.
Definition at line 1818 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgPower = avgPower;
 }
References avgPower().
setAvgPowerPosition()
void SessionMessage::setAvgPowerPosition (const quint16 avgPowerPosition)
Sets the avgPowerPosition field to avgPowerPosition.
Parameters
avgPowerPosition The field value to set.
Definition at line 2638 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgPowerPosition = avgPowerPosition;
 }
References avgPowerPosition().
setAvgRightPco()
void SessionMessage::setAvgRightPco (const qint8 avgRightPco)
Sets the avgRightPco field to avgRightPco.
Parameters
avgRightPco The field value to set.
Definition at line 2588 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgRightPco = avgRightPco;
 }
References avgRightPco().
setAvgRightPedalSmoothness()
void SessionMessage::setAvgRightPedalSmoothness (const quint8 avgRightPedalSmoothness)
Sets the avgRightPedalSmoothness field to avgRightPedalSmoothness.
Parameters
avgRightPedalSmoothness The field value to set.
Definition at line 2528 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgRightPedalSmoothness = avgRightPedalSmoothness;
 }
References avgRightPedalSmoothness().
setAvgRightPowerPhase()
void SessionMessage::setAvgRightPowerPhase (const quint8 avgRightPowerPhase)
Sets the avgRightPowerPhase field to avgRightPowerPhase.
Parameters
avgRightPowerPhase The field value to set.
Definition at line 2618 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgRightPowerPhase = avgRightPowerPhase;
 }
References avgRightPowerPhase().
setAvgRightPowerPhasePeak()
void SessionMessage::setAvgRightPowerPhasePeak (const quint8 avgRightPowerPhasePeak)
Sets the avgRightPowerPhasePeak field to avgRightPowerPhasePeak.
Parameters
avgRightPowerPhasePeak The field value to set.
Definition at line 2628 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgRightPowerPhasePeak = avgRightPowerPhasePeak;
 }
References avgRightPowerPhasePeak().
setAvgRightTorqueEffectiveness()
void SessionMessage::setAvgRightTorqueEffectiveness (const quint8 avgRightTorqueEffectiveness)
Sets the avgRightTorqueEffectiveness field to avgRightTorqueEffectiveness.
Parameters
avgRightTorqueEffectiveness The field value to set.
Definition at line 2508 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgRightTorqueEffectiveness = avgRightTorqueEffectiveness;
 }
References avgRightTorqueEffectiveness().
setAvgSaturatedHemoglobinPercent()
void SessionMessage::setAvgSaturatedHemoglobinPercent (const quint16 avgSaturatedHemoglobinPercent)
Sets the avgSaturatedHemoglobinPercent field to avgSaturatedHemoglobinPercent.
Parameters
avgSaturatedHemoglobinPercent The field value to set.
Definition at line 2468 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgSaturatedHemoglobinPercent = avgSaturatedHemoglobinPercent;
 }
References avgSaturatedHemoglobinPercent().
setAvgSpeed()
void SessionMessage::setAvgSpeed (const quint16 avgSpeed)
Sets the avgSpeed field to avgSpeed.
Parameters
avgSpeed The field value to set.
Definition at line 1758 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgSpeed = avgSpeed;
 }
References avgSpeed().
setAvgStanceTime()
void SessionMessage::setAvgStanceTime (const quint16 avgStanceTime)
Sets the avgStanceTime field to avgStanceTime.
Parameters
avgStanceTime The field value to set.
Definition at line 2398 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgStanceTime = avgStanceTime;
 }
References avgStanceTime().
setAvgStanceTimeBalance()
void SessionMessage::setAvgStanceTimeBalance (const quint16 avgStanceTimeBalance)
Sets the avgStanceTimeBalance field to avgStanceTimeBalance.
Parameters
avgStanceTimeBalance The field value to set.
Definition at line 2768 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgStanceTimeBalance = avgStanceTimeBalance;
 }
References avgStanceTimeBalance().
setAvgStanceTimePercent()
void SessionMessage::setAvgStanceTimePercent (const quint16 avgStanceTimePercent)
Sets the avgStanceTimePercent field to avgStanceTimePercent.
Parameters
avgStanceTimePercent The field value to set.
Definition at line 2388 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgStanceTimePercent = avgStanceTimePercent;
 }
References avgStanceTimePercent().
setAvgStepLength()
void SessionMessage::setAvgStepLength (const quint16 avgStepLength)
Sets the avgStepLength field to avgStepLength.
Parameters
avgStepLength The field value to set.
Definition at line 2778 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgStepLength = avgStepLength;
 }
References avgStepLength().
setAvgStrokeCount()
void SessionMessage::setAvgStrokeCount (const quint32 avgStrokeCount)
Sets the avgStrokeCount field to avgStrokeCount.
Parameters
avgStrokeCount The field value to set.
Definition at line 1998 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgStrokeCount = avgStrokeCount;
 }
References avgStrokeCount().
setAvgStrokeDistance()
void SessionMessage::setAvgStrokeDistance (const quint16 avgStrokeDistance)
Sets the avgStrokeDistance field to avgStrokeDistance.
Parameters
avgStrokeDistance The field value to set.
Definition at line 2008 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgStrokeDistance = avgStrokeDistance;
 }
References avgStrokeDistance().
setAvgTemperature()
void SessionMessage::setAvgTemperature (const qint8 avgTemperature)
Sets the avgTemperature field to avgTemperature.
Parameters
avgTemperature The field value to set.
Definition at line 2158 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgTemperature = avgTemperature;
 }
References avgTemperature().
setAvgTotalHemoglobinConc()
void SessionMessage::setAvgTotalHemoglobinConc (const quint16 avgTotalHemoglobinConc)
Sets the avgTotalHemoglobinConc field to avgTotalHemoglobinConc.
Parameters
avgTotalHemoglobinConc The field value to set.
Definition at line 2438 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgTotalHemoglobinConc = avgTotalHemoglobinConc;
 }
References avgTotalHemoglobinConc().
setAvgVam()
void SessionMessage::setAvgVam (const quint16 avgVam)
Sets the avgVam field to avgVam.
Parameters
avgVam The field value to set.
Definition at line 2798 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgVam = avgVam;
 }
References avgVam().
setAvgVerticalOscillation()
void SessionMessage::setAvgVerticalOscillation (const quint16 avgVerticalOscillation)
Sets the avgVerticalOscillation field to avgVerticalOscillation.
Parameters
avgVerticalOscillation The field value to set.
Definition at line 2378 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgVerticalOscillation = avgVerticalOscillation;
 }
References avgVerticalOscillation().
setAvgVerticalRatio()
void SessionMessage::setAvgVerticalRatio (const quint16 avgVerticalRatio)
Sets the avgVerticalRatio field to avgVerticalRatio.
Parameters
avgVerticalRatio The field value to set.
Definition at line 2758 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->avgVerticalRatio = avgVerticalRatio;
 }
References avgVerticalRatio().
setBestLapIndex()
void SessionMessage::setBestLapIndex (const quint16 bestLapIndex)
Sets the bestLapIndex field to bestLapIndex.
Parameters
bestLapIndex The field value to set.
Definition at line 2288 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->bestLapIndex = bestLapIndex;
 }
References bestLapIndex().
setEnhancedAvgAltitude()
void SessionMessage::setEnhancedAvgAltitude (const quint32 enhancedAvgAltitude)
Sets the enhancedAvgAltitude field to enhancedAvgAltitude.
Parameters
enhancedAvgAltitude The field value to set.
Definition at line 2698 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->enhancedAvgAltitude = enhancedAvgAltitude;
 }
References enhancedAvgAltitude().
setEnhancedAvgSpeed()
void SessionMessage::setEnhancedAvgSpeed (const quint32 enhancedAvgSpeed)
Sets the enhancedAvgSpeed field to enhancedAvgSpeed.
Parameters
enhancedAvgSpeed The field value to set.
Definition at line 2678 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->enhancedAvgSpeed = enhancedAvgSpeed;
 }
References enhancedAvgSpeed().
setEnhancedMaxAltitude()
void SessionMessage::setEnhancedMaxAltitude (const quint32 enhancedMaxAltitude)
Sets the enhancedMaxAltitude field to enhancedMaxAltitude.
Parameters
enhancedMaxAltitude The field value to set.
Definition at line 2718 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->enhancedMaxAltitude = enhancedMaxAltitude;
 }
References enhancedMaxAltitude().
setEnhancedMaxSpeed()
void SessionMessage::setEnhancedMaxSpeed (const quint32 enhancedMaxSpeed)
Sets the enhancedMaxSpeed field to enhancedMaxSpeed.
Parameters
enhancedMaxSpeed The field value to set.
Definition at line 2688 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->enhancedMaxSpeed = enhancedMaxSpeed;
 }
References enhancedMaxSpeed().
setEnhancedMinAltitude()
void SessionMessage::setEnhancedMinAltitude (const quint32 enhancedMinAltitude)
Sets the enhancedMinAltitude field to enhancedMinAltitude.
Parameters
enhancedMinAltitude The field value to set.
Definition at line 2708 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->enhancedMinAltitude = enhancedMinAltitude;
 }
References enhancedMinAltitude().
setEvent()
void SessionMessage::setEvent (const Event event)
Sets the event field to event.
Parameters
event The field value to set.
Definition at line 1628 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->event = event;
 }
References event().
setEventGroup()
void SessionMessage::setEventGroup (const quint8 eventGroup)
Sets the eventGroup field to eventGroup.
Parameters
eventGroup The field value to set.
Definition at line 1888 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->eventGroup = eventGroup;
 }
References eventGroup().
setEventType()
void SessionMessage::setEventType (const EventType eventType)
Sets the eventType field to eventType.
Parameters
eventType The field value to set.
Definition at line 1638 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->eventType = eventType;
 }
References eventType().
setFirstLapIndex()
void SessionMessage::setFirstLapIndex (const quint16 firstLapIndex)
Sets the firstLapIndex field to firstLapIndex.
Parameters
firstLapIndex The field value to set.
Definition at line 1868 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->firstLapIndex = firstLapIndex;
 }
References firstLapIndex().
setGpsAccuracy()
void SessionMessage::setGpsAccuracy (const quint8 gpsAccuracy)
Sets the gpsAccuracy field to gpsAccuracy.
Parameters
gpsAccuracy The field value to set.
Definition at line 2098 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->gpsAccuracy = gpsAccuracy;
 }
References gpsAccuracy().
setIntensityFactor()
void SessionMessage::setIntensityFactor (const quint16 intensityFactor)
Sets the intensityFactor field to intensityFactor.
Parameters
intensityFactor The field value to set.
Definition at line 1978 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->intensityFactor = intensityFactor;
 }
References intensityFactor().
setJumpCount()
void SessionMessage::setJumpCount (const quint16 jumpCount)
Sets the jumpCount field to jumpCount.
Parameters
jumpCount The field value to set.
Definition at line 2828 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->jumpCount = jumpCount;
 }
References jumpCount().
setLeftRightBalance()
void SessionMessage::setLeftRightBalance (const LeftRightBalance100 leftRightBalance)
Sets the leftRightBalance field to leftRightBalance.
Parameters
leftRightBalance The field value to set.
Definition at line 1988 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->leftRightBalance = leftRightBalance;
 }
References leftRightBalance().
setLevBatteryConsumption()
void SessionMessage::setLevBatteryConsumption (const quint8 levBatteryConsumption)
Sets the levBatteryConsumption field to levBatteryConsumption.
Parameters
levBatteryConsumption The field value to set.
Definition at line 2748 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->levBatteryConsumption = levBatteryConsumption;
 }
References levBatteryConsumption().
setMaxAltitude()
void SessionMessage::setMaxAltitude (const quint16 maxAltitude)
Sets the maxAltitude field to maxAltitude.
Parameters
maxAltitude The field value to set.
Definition at line 2088 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->maxAltitude = maxAltitude;
 }
References maxAltitude().
setMaxBallSpeed()
void SessionMessage::setMaxBallSpeed (const quint16 maxBallSpeed)
Sets the maxBallSpeed field to maxBallSpeed.
Parameters
maxBallSpeed The field value to set.
Definition at line 2358 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->maxBallSpeed = maxBallSpeed;
 }
References maxBallSpeed().
setMaxCadence()
void SessionMessage::setMaxCadence (const quint8 maxCadence)
Sets the maxCadence field to maxCadence.
Parameters
maxCadence The field value to set.
Definition at line 1808 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->maxCadence = maxCadence;
 }
References maxCadence().
setMaxCadencePosition()
void SessionMessage::setMaxCadencePosition (const quint8 maxCadencePosition)
Sets the maxCadencePosition field to maxCadencePosition.
Parameters
maxCadencePosition The field value to set.
Definition at line 2668 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->maxCadencePosition = maxCadencePosition;
 }
References maxCadencePosition().
setMaxCoreTemperature()
void SessionMessage::setMaxCoreTemperature (const quint16 maxCoreTemperature)
Sets the maxCoreTemperature field to maxCoreTemperature.
Parameters
maxCoreTemperature The field value to set.
Definition at line 2898 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->maxCoreTemperature = maxCoreTemperature;
 }
References maxCoreTemperature().
setMaxFractionalCadence()
void SessionMessage::setMaxFractionalCadence (const quint8 maxFractionalCadence)
Sets the maxFractionalCadence field to maxFractionalCadence.
Parameters
maxFractionalCadence The field value to set.
Definition at line 2418 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->maxFractionalCadence = maxFractionalCadence;
 }
References maxFractionalCadence().
setMaxHeartRate()
void SessionMessage::setMaxHeartRate (const quint8 maxHeartRate)
Sets the maxHeartRate field to maxHeartRate.
Parameters
maxHeartRate The field value to set.
Definition at line 1788 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->maxHeartRate = maxHeartRate;
 }
References maxHeartRate().
setMaxLevMotorPower()
void SessionMessage::setMaxLevMotorPower (const quint16 maxLevMotorPower)
Sets the maxLevMotorPower field to maxLevMotorPower.
Parameters
maxLevMotorPower The field value to set.
Definition at line 2738 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->maxLevMotorPower = maxLevMotorPower;
 }
References maxLevMotorPower().
setMaxNegGrade()
void SessionMessage::setMaxNegGrade (const qint16 maxNegGrade)
Sets the maxNegGrade field to maxNegGrade.
Parameters
maxNegGrade The field value to set.
Definition at line 2148 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->maxNegGrade = maxNegGrade;
 }
References maxNegGrade().
setMaxNegVerticalSpeed()
void SessionMessage::setMaxNegVerticalSpeed (const qint16 maxNegVerticalSpeed)
Sets the maxNegVerticalSpeed field to maxNegVerticalSpeed.
Parameters
maxNegVerticalSpeed The field value to set.
Definition at line 2218 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->maxNegVerticalSpeed = maxNegVerticalSpeed;
 }
References maxNegVerticalSpeed().
setMaxPosGrade()
void SessionMessage::setMaxPosGrade (const qint16 maxPosGrade)
Sets the maxPosGrade field to maxPosGrade.
Parameters
maxPosGrade The field value to set.
Definition at line 2138 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->maxPosGrade = maxPosGrade;
 }
References maxPosGrade().
setMaxPosVerticalSpeed()
void SessionMessage::setMaxPosVerticalSpeed (const qint16 maxPosVerticalSpeed)
Sets the maxPosVerticalSpeed field to maxPosVerticalSpeed.
Parameters
maxPosVerticalSpeed The field value to set.
Definition at line 2208 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->maxPosVerticalSpeed = maxPosVerticalSpeed;
 }
References maxPosVerticalSpeed().
setMaxPower()
void SessionMessage::setMaxPower (const quint16 maxPower)
Sets the maxPower field to maxPower.
Parameters
maxPower The field value to set.
Definition at line 1828 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->maxPower = maxPower;
 }
References maxPower().
setMaxPowerPosition()
void SessionMessage::setMaxPowerPosition (const quint16 maxPowerPosition)
Sets the maxPowerPosition field to maxPowerPosition.
Parameters
maxPowerPosition The field value to set.
Definition at line 2648 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->maxPowerPosition = maxPowerPosition;
 }
References maxPowerPosition().
setMaxSaturatedHemoglobinPercent()
void SessionMessage::setMaxSaturatedHemoglobinPercent (const quint16 maxSaturatedHemoglobinPercent)
Sets the maxSaturatedHemoglobinPercent field to maxSaturatedHemoglobinPercent.
Parameters
maxSaturatedHemoglobinPercent The field value to set.
Definition at line 2488 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->maxSaturatedHemoglobinPercent = maxSaturatedHemoglobinPercent;
 }
References maxSaturatedHemoglobinPercent().
setMaxSpeed()
void SessionMessage::setMaxSpeed (const quint16 maxSpeed)
Sets the maxSpeed field to maxSpeed.
Parameters
maxSpeed The field value to set.
Definition at line 1768 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->maxSpeed = maxSpeed;
 }
References maxSpeed().
setMaxTemperature()
void SessionMessage::setMaxTemperature (const qint8 maxTemperature)
Sets the maxTemperature field to maxTemperature.
Parameters
maxTemperature The field value to set.
Definition at line 2168 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->maxTemperature = maxTemperature;
 }
References maxTemperature().
setMaxTotalHemoglobinConc()
void SessionMessage::setMaxTotalHemoglobinConc (const quint16 maxTotalHemoglobinConc)
Sets the maxTotalHemoglobinConc field to maxTotalHemoglobinConc.
Parameters
maxTotalHemoglobinConc The field value to set.
Definition at line 2458 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->maxTotalHemoglobinConc = maxTotalHemoglobinConc;
 }
References maxTotalHemoglobinConc().
setMessageIndex()
void SessionMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 1608 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setMinAltitude()
void SessionMessage::setMinAltitude (const quint16 minAltitude)
Sets the minAltitude field to minAltitude.
Parameters
minAltitude The field value to set.
Definition at line 2298 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->minAltitude = minAltitude;
 }
References minAltitude().
setMinCoreTemperature()
void SessionMessage::setMinCoreTemperature (const quint16 minCoreTemperature)
Sets the minCoreTemperature field to minCoreTemperature.
Parameters
minCoreTemperature The field value to set.
Definition at line 2888 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->minCoreTemperature = minCoreTemperature;
 }
References minCoreTemperature().
setMinHeartRate()
void SessionMessage::setMinHeartRate (const quint8 minHeartRate)
Sets the minHeartRate field to minHeartRate.
Parameters
minHeartRate The field value to set.
Definition at line 2228 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->minHeartRate = minHeartRate;
 }
References minHeartRate().
setMinSaturatedHemoglobinPercent()
void SessionMessage::setMinSaturatedHemoglobinPercent (const quint16 minSaturatedHemoglobinPercent)
Sets the minSaturatedHemoglobinPercent field to minSaturatedHemoglobinPercent.
Parameters
minSaturatedHemoglobinPercent The field value to set.
Definition at line 2478 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->minSaturatedHemoglobinPercent = minSaturatedHemoglobinPercent;
 }
References minSaturatedHemoglobinPercent().
setMinTotalHemoglobinConc()
void SessionMessage::setMinTotalHemoglobinConc (const quint16 minTotalHemoglobinConc)
Sets the minTotalHemoglobinConc field to minTotalHemoglobinConc.
Parameters
minTotalHemoglobinConc The field value to set.
Definition at line 2448 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->minTotalHemoglobinConc = minTotalHemoglobinConc;
 }
References minTotalHemoglobinConc().
setNecLat()
void SessionMessage::setNecLat (const qint32 necLat)
Sets the necLat field to necLat.
Parameters
necLat The field value to set.
Definition at line 1908 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->necLat = necLat;
 }
References necLat().
setNecLong()
void SessionMessage::setNecLong (const qint32 necLong)
Sets the necLong field to necLong.
Parameters
necLong The field value to set.
Definition at line 1918 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->necLong = necLong;
 }
References necLong().
setNormalizedPower()
void SessionMessage::setNormalizedPower (const quint16 normalizedPower)
Sets the normalizedPower field to normalizedPower.
Parameters
normalizedPower The field value to set.
Definition at line 1958 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->normalizedPower = normalizedPower;
 }
References normalizedPower().
setNumActiveLengths()
void SessionMessage::setNumActiveLengths (const quint16 numActiveLengths)
Sets the numActiveLengths field to numActiveLengths.
Parameters
numActiveLengths The field value to set.
Definition at line 2058 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->numActiveLengths = numActiveLengths;
 }
References numActiveLengths().
setNumLaps()
void SessionMessage::setNumLaps (const quint16 numLaps)
Sets the numLaps field to numLaps.
Parameters
numLaps The field value to set.
Definition at line 1878 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->numLaps = numLaps;
 }
References numLaps().
setNumLengths()
void SessionMessage::setNumLengths (const quint16 numLengths)
Sets the numLengths field to numLengths.
Parameters
numLengths The field value to set.
Definition at line 1948 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->numLengths = numLengths;
 }
References numLengths().
setOpponentName()
void SessionMessage::setOpponentName (const QString opponentName)
Sets the opponentName field to opponentName.
Parameters
opponentName The field value to set.
Definition at line 2328 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->opponentName = opponentName;
 }
References opponentName().
setOpponentScore()
void SessionMessage::setOpponentScore (const quint16 opponentScore)
Sets the opponentScore field to opponentScore.
Parameters
opponentScore The field value to set.
Definition at line 2318 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->opponentScore = opponentScore;
 }
References opponentScore().
setPlayerScore()
void SessionMessage::setPlayerScore (const quint16 playerScore)
Sets the playerScore field to playerScore.
Parameters
playerScore The field value to set.
Definition at line 2308 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->playerScore = playerScore;
 }
References playerScore().
setPoolLength()
void SessionMessage::setPoolLength (const quint16 poolLength)
Sets the poolLength field to poolLength.
Parameters
poolLength The field value to set.
Definition at line 2028 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->poolLength = poolLength;
 }
References poolLength().
setPoolLengthUnit()
void SessionMessage::setPoolLengthUnit (const DisplayMeasure poolLengthUnit)
Sets the poolLengthUnit field to poolLengthUnit.
Parameters
poolLengthUnit The field value to set.
Definition at line 2048 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->poolLengthUnit = poolLengthUnit;
 }
References poolLengthUnit().
setSport()
void SessionMessage::setSport (const Sport sport)
Sets the sport field to sport.
Parameters
sport The field value to set.
Definition at line 1678 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->sport = sport;
 }
References sport().
setSportIndex()
void SessionMessage::setSportIndex (const quint8 sportIndex)
Sets the sportIndex field to sportIndex.
Parameters
sportIndex The field value to set.
Definition at line 2548 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->sportIndex = sportIndex;
 }
References sportIndex().
setStandCount()
void SessionMessage::setStandCount (const quint16 standCount)
Sets the standCount field to standCount.
Parameters
standCount The field value to set.
Definition at line 2568 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->standCount = standCount;
 }
References standCount().
setStartPositionLat()
void SessionMessage::setStartPositionLat (const qint32 startPositionLat)
Sets the startPositionLat field to startPositionLat.
Parameters
startPositionLat The field value to set.
Definition at line 1658 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->startPositionLat = startPositionLat;
 }
References startPositionLat().
setStartPositionLong()
void SessionMessage::setStartPositionLong (const qint32 startPositionLong)
Sets the startPositionLong field to startPositionLong.
Parameters
startPositionLong The field value to set.
Definition at line 1668 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->startPositionLong = startPositionLong;
 }
References startPositionLong().
setStartTime()
void SessionMessage::setStartTime (const DateTime startTime)
Sets the startTime field to startTime.
Parameters
startTime The field value to set.
Definition at line 1648 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->startTime = startTime;
 }
References startTime().
setStrokeCount()
void SessionMessage::setStrokeCount (const quint16 strokeCount)
Sets the strokeCount field to strokeCount.
Parameters
strokeCount The field value to set.
Definition at line 2338 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->strokeCount = strokeCount;
 }
References strokeCount().
setSubSport()
void SessionMessage::setSubSport (const SubSport subSport)
Sets the subSport field to subSport.
Parameters
subSport The field value to set.
Definition at line 1688 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->subSport = subSport;
 }
References subSport().
setSwcLat()
void SessionMessage::setSwcLat (const qint32 swcLat)
Sets the swcLat field to swcLat.
Parameters
swcLat The field value to set.
Definition at line 1928 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->swcLat = swcLat;
 }
References swcLat().
setSwcLong()
void SessionMessage::setSwcLong (const qint32 swcLong)
Sets the swcLong field to swcLong.
Parameters
swcLong The field value to set.
Definition at line 1938 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->swcLong = swcLong;
 }
References swcLong().
setSwimStroke()
void SessionMessage::setSwimStroke (const SwimStroke swimStroke)
Sets the swimStroke field to swimStroke.
Parameters
swimStroke The field value to set.
Definition at line 2018 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->swimStroke = swimStroke;
 }
References swimStroke().
setThresholdPower()
void SessionMessage::setThresholdPower (const quint16 thresholdPower)
Sets the thresholdPower field to thresholdPower.
Parameters
thresholdPower The field value to set.
Definition at line 2038 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->thresholdPower = thresholdPower;
 }
References thresholdPower().
setTimeInCadenceZone()
void SessionMessage::setTimeInCadenceZone (const quint32 timeInCadenceZone)
Sets the timeInCadenceZone field to timeInCadenceZone.
Parameters
timeInCadenceZone The field value to set.
Definition at line 2258 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->timeInCadenceZone = timeInCadenceZone;
 }
References timeInCadenceZone().
setTimeInHrZone()
void SessionMessage::setTimeInHrZone (const quint32 timeInHrZone)
Sets the timeInHrZone field to timeInHrZone.
Parameters
timeInHrZone The field value to set.
Definition at line 2238 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->timeInHrZone = timeInHrZone;
 }
References timeInHrZone().
setTimeInPowerZone()
void SessionMessage::setTimeInPowerZone (const quint32 timeInPowerZone)
Sets the timeInPowerZone field to timeInPowerZone.
Parameters
timeInPowerZone The field value to set.
Definition at line 2268 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->timeInPowerZone = timeInPowerZone;
 }
References timeInPowerZone().
setTimeInSpeedZone()
void SessionMessage::setTimeInSpeedZone (const quint32 timeInSpeedZone)
Sets the timeInSpeedZone field to timeInSpeedZone.
Parameters
timeInSpeedZone The field value to set.
Definition at line 2248 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->timeInSpeedZone = timeInSpeedZone;
 }
References timeInSpeedZone().
setTimestamp()
void SessionMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 1618 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setTimeStanding()
void SessionMessage::setTimeStanding (const quint32 timeStanding)
Sets the timeStanding field to timeStanding.
Parameters
timeStanding The field value to set.
Definition at line 2558 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->timeStanding = timeStanding;
 }
References timeStanding().
setTotalAnaerobicTrainingEffect()
void SessionMessage::setTotalAnaerobicTrainingEffect (const quint8 totalAnaerobicTrainingEffect)
Sets the totalAnaerobicTrainingEffect field to totalAnaerobicTrainingEffect.
Parameters
totalAnaerobicTrainingEffect The field value to set.
Definition at line 2788 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->totalAnaerobicTrainingEffect = totalAnaerobicTrainingEffect;
 }
References totalAnaerobicTrainingEffect().
setTotalAscent()
void SessionMessage::setTotalAscent (const quint16 totalAscent)
Sets the totalAscent field to totalAscent.
Parameters
totalAscent The field value to set.
Definition at line 1838 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->totalAscent = totalAscent;
 }
References totalAscent().
setTotalCalories()
void SessionMessage::setTotalCalories (const quint16 totalCalories)
Sets the totalCalories field to totalCalories.
Parameters
totalCalories The field value to set.
Definition at line 1738 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->totalCalories = totalCalories;
 }
References totalCalories().
setTotalCycles()
void SessionMessage::setTotalCycles (const quint32 totalCycles)
Sets the totalCycles field to totalCycles.
Parameters
totalCycles The field value to set.
Definition at line 1728 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->totalCycles = totalCycles;
 }
References totalCycles().
setTotalDescent()
void SessionMessage::setTotalDescent (const quint16 totalDescent)
Sets the totalDescent field to totalDescent.
Parameters
totalDescent The field value to set.
Definition at line 1848 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->totalDescent = totalDescent;
 }
References totalDescent().
setTotalDistance()
void SessionMessage::setTotalDistance (const quint32 totalDistance)
Sets the totalDistance field to totalDistance.
Parameters
totalDistance The field value to set.
Definition at line 1718 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->totalDistance = totalDistance;
 }
References totalDistance().
setTotalElapsedTime()
void SessionMessage::setTotalElapsedTime (const quint32 totalElapsedTime)
Sets the totalElapsedTime field to totalElapsedTime.
Parameters
totalElapsedTime The field value to set.
Definition at line 1698 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->totalElapsedTime = totalElapsedTime;
 }
References totalElapsedTime().
setTotalFatCalories()
void SessionMessage::setTotalFatCalories (const quint16 totalFatCalories)
Sets the totalFatCalories field to totalFatCalories.
Parameters
totalFatCalories The field value to set.
Definition at line 1748 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->totalFatCalories = totalFatCalories;
 }
References totalFatCalories().
setTotalFlow()
void SessionMessage::setTotalFlow (const float totalFlow)
Sets the totalFlow field to totalFlow.
Parameters
totalFlow The field value to set.
Definition at line 2818 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->totalFlow = totalFlow;
 }
References totalFlow().
setTotalFractionalAscent()
void SessionMessage::setTotalFractionalAscent (const quint8 totalFractionalAscent)
Sets the totalFractionalAscent field to totalFractionalAscent.
Parameters
totalFractionalAscent The field value to set.
Definition at line 2858 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->totalFractionalAscent = totalFractionalAscent;
 }
References totalFractionalAscent().
setTotalFractionalCycles()
void SessionMessage::setTotalFractionalCycles (const quint8 totalFractionalCycles)
Sets the totalFractionalCycles field to totalFractionalCycles.
Parameters
totalFractionalCycles The field value to set.
Definition at line 2428 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->totalFractionalCycles = totalFractionalCycles;
 }
References totalFractionalCycles().
setTotalFractionalDescent()
void SessionMessage::setTotalFractionalDescent (const quint8 totalFractionalDescent)
Sets the totalFractionalDescent field to totalFractionalDescent.
Parameters
totalFractionalDescent The field value to set.
Definition at line 2868 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->totalFractionalDescent = totalFractionalDescent;
 }
References totalFractionalDescent().
setTotalGrit()
void SessionMessage::setTotalGrit (const float totalGrit)
Sets the totalGrit field to totalGrit.
Parameters
totalGrit The field value to set.
Definition at line 2808 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->totalGrit = totalGrit;
 }
References totalGrit().
setTotalMovingTime()
void SessionMessage::setTotalMovingTime (const quint32 totalMovingTime)
Sets the totalMovingTime field to totalMovingTime.
Parameters
totalMovingTime The field value to set.
Definition at line 2178 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->totalMovingTime = totalMovingTime;
 }
References totalMovingTime().
setTotalTimerTime()
void SessionMessage::setTotalTimerTime (const quint32 totalTimerTime)
Sets the totalTimerTime field to totalTimerTime.
Parameters
totalTimerTime The field value to set.
Definition at line 1708 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->totalTimerTime = totalTimerTime;
 }
References totalTimerTime().
setTotalTrainingEffect()
void SessionMessage::setTotalTrainingEffect (const quint8 totalTrainingEffect)
Sets the totalTrainingEffect field to totalTrainingEffect.
Parameters
totalTrainingEffect The field value to set.
Definition at line 1858 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->totalTrainingEffect = totalTrainingEffect;
 }
References totalTrainingEffect().
setTotalWork()
void SessionMessage::setTotalWork (const quint32 totalWork)
Sets the totalWork field to totalWork.
Parameters
totalWork The field value to set.
Definition at line 2068 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->totalWork = totalWork;
 }
References totalWork().
setTrainingStressScore()
void SessionMessage::setTrainingStressScore (const quint16 trainingStressScore)
Sets the trainingStressScore field to trainingStressScore.
Parameters
trainingStressScore The field value to set.
Definition at line 1968 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->trainingStressScore = trainingStressScore;
 }
References trainingStressScore().
setTrigger()
void SessionMessage::setTrigger (const SessionTrigger trigger)
Sets the trigger field to trigger.
Parameters
trigger The field value to set.
Definition at line 1898 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->trigger = trigger;
 }
References trigger().
setZoneCount()
void SessionMessage::setZoneCount (const quint16 zoneCount)
Sets the zoneCount field to zoneCount.
Parameters
zoneCount The field value to set.
Definition at line 2348 of file sessionmessage.cpp.
 {
     Q_D(SessionMessage);
     d->zoneCount = zoneCount;
 }
References zoneCount().
sport()
Sport SessionMessage::sport () const
Returns the SessionMessage data message's sport field's current value.
Returns
the sport field value.
Definition at line 159 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->sport;
 }
Referenced by setSport().
sportIndex()
quint8 SessionMessage::sportIndex () const
Returns the SessionMessage data message's sportIndex field's current value.
Returns
the sportIndex field value.
Definition at line 1164 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->sportIndex;
 }
Referenced by setSportIndex().
standCount()
quint16 SessionMessage::standCount () const
Returns the SessionMessage data message's standCount field's current value.
Number of transitions to the standing state
Returns
the standCount field value.
Definition at line 1190 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->standCount;
 }
Referenced by setStandCount().
startPositionLat()
qint32 SessionMessage::startPositionLat () const
Returns the SessionMessage data message's startPositionLat field's current value.
Returns
the startPositionLat field value.
Definition at line 137 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->startPositionLat;
 }
Referenced by setStartPositionLat().
startPositionLong()
qint32 SessionMessage::startPositionLong () const
Returns the SessionMessage data message's startPositionLong field's current value.
Returns
the startPositionLong field value.
Definition at line 148 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->startPositionLong;
 }
Referenced by setStartPositionLong().
startTime()
DateTime SessionMessage::startTime () const
Returns the SessionMessage data message's startTime field's current value.
Returns
the startTime field value.
Definition at line 126 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->startTime;
 }
Referenced by setStartTime().
strokeCount()
quint16 SessionMessage::strokeCount () const
Returns the SessionMessage data message's strokeCount field's current value.
stroke_type enum used as the index
Returns
the strokeCount field value.
Definition at line 913 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->strokeCount;
 }
Referenced by setStrokeCount().
subSport()
SubSport SessionMessage::subSport () const
Returns the SessionMessage data message's subSport field's current value.
Returns
the subSport field value.
Definition at line 170 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->subSport;
 }
Referenced by setSubSport().
swcLat()
qint32 SessionMessage::swcLat () const
Returns the SessionMessage data message's swcLat field's current value.
South west corner latitude
Returns
the swcLat field value.
Definition at line 454 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->swcLat;
 }
Referenced by setSwcLat().
swcLong()
qint32 SessionMessage::swcLong () const
Returns the SessionMessage data message's swcLong field's current value.
South west corner longitude
Returns
the swcLong field value.
Definition at line 467 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->swcLong;
 }
Referenced by setSwcLong().
swimStroke()
SwimStroke SessionMessage::swimStroke () const
Returns the SessionMessage data message's swimStroke field's current value.
Returns
the swimStroke field value.
Definition at line 557 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->swimStroke;
 }
Referenced by setSwimStroke().
thresholdPower()
quint16 SessionMessage::thresholdPower () const
Returns the SessionMessage data message's thresholdPower field's current value.
Returns
the thresholdPower field value.
Definition at line 579 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->thresholdPower;
 }
Referenced by setThresholdPower().
timeInCadenceZone()
quint32 SessionMessage::timeInCadenceZone () const
Returns the SessionMessage data message's timeInCadenceZone field's current value.
Returns
the timeInCadenceZone field value.
Definition at line 823 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->timeInCadenceZone;
 }
Referenced by setTimeInCadenceZone().
timeInHrZone()
quint32 SessionMessage::timeInHrZone () const
Returns the SessionMessage data message's timeInHrZone field's current value.
Returns
the timeInHrZone field value.
Definition at line 801 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->timeInHrZone;
 }
Referenced by setTimeInHrZone().
timeInPowerZone()
quint32 SessionMessage::timeInPowerZone () const
Returns the SessionMessage data message's timeInPowerZone field's current value.
Returns
the timeInPowerZone field value.
Definition at line 834 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->timeInPowerZone;
 }
Referenced by setTimeInPowerZone().
timeInSpeedZone()
quint32 SessionMessage::timeInSpeedZone () const
Returns the SessionMessage data message's timeInSpeedZone field's current value.
Returns
the timeInSpeedZone field value.
Definition at line 812 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->timeInSpeedZone;
 }
Referenced by setTimeInSpeedZone().
timestamp()
DateTime SessionMessage::timestamp () const
Returns the SessionMessage data message's timestamp field's current value.
Sesson end time.
Returns
the timestamp field value.
Definition at line 89 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
timeStanding()
quint32 SessionMessage::timeStanding () const
Returns the SessionMessage data message's timeStanding field's current value.
Total time spend in the standing position
Returns
the timeStanding field value.
Definition at line 1177 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->timeStanding;
 }
Referenced by setTimeStanding().
totalAnaerobicTrainingEffect()
quint8 SessionMessage::totalAnaerobicTrainingEffect () const
Returns the SessionMessage data message's totalAnaerobicTrainingEffect field's current value.
Returns
the totalAnaerobicTrainingEffect field value.
Definition at line 1460 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->totalAnaerobicTrainingEffect;
 }
Referenced by setTotalAnaerobicTrainingEffect().
totalAscent()
quint16 SessionMessage::totalAscent () const
Returns the SessionMessage data message's totalAscent field's current value.
Returns
the totalAscent field value.
Definition at line 349 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->totalAscent;
 }
Referenced by setTotalAscent().
totalCalories()
quint16 SessionMessage::totalCalories () const
Returns the SessionMessage data message's totalCalories field's current value.
Returns
the totalCalories field value.
Definition at line 229 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->totalCalories;
 }
Referenced by setTotalCalories().
totalCycles()
quint32 SessionMessage::totalCycles () const
Returns the SessionMessage data message's totalCycles field's current value.
Returns
the totalCycles field value.
Definition at line 218 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->totalCycles;
 }
Referenced by setTotalCycles().
totalDescent()
quint16 SessionMessage::totalDescent () const
Returns the SessionMessage data message's totalDescent field's current value.
Returns
the totalDescent field value.
Definition at line 360 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->totalDescent;
 }
Referenced by setTotalDescent().
totalDistance()
quint32 SessionMessage::totalDistance () const
Returns the SessionMessage data message's totalDistance field's current value.
Returns
the totalDistance field value.
Definition at line 207 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->totalDistance;
 }
Referenced by setTotalDistance().
totalElapsedTime()
quint32 SessionMessage::totalElapsedTime () const
Returns the SessionMessage data message's totalElapsedTime field's current value.
Time (includes pauses)
Returns
the totalElapsedTime field value.
Definition at line 183 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->totalElapsedTime;
 }
Referenced by setTotalElapsedTime().
totalFatCalories()
quint16 SessionMessage::totalFatCalories () const
Returns the SessionMessage data message's totalFatCalories field's current value.
Returns
the totalFatCalories field value.
Definition at line 240 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->totalFatCalories;
 }
Referenced by setTotalFatCalories().
totalFlow()
float SessionMessage::totalFlow () const
Returns the SessionMessage data message's totalFlow field's current value.
The flow score estimates how long distance wise a cyclist deaccelerates over intervals where deacceleration is unnecessary such as smooth turns or small grade angle intervals.
Returns
the totalFlow field value.
Definition at line 1499 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->totalFlow;
 }
Referenced by setTotalFlow().
totalFractionalAscent()
quint8 SessionMessage::totalFractionalAscent () const
Returns the SessionMessage data message's totalFractionalAscent field's current value.
fractional part of total_ascent
Returns
the totalFractionalAscent field value.
Definition at line 1551 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->totalFractionalAscent;
 }
Referenced by setTotalFractionalAscent().
totalFractionalCycles()
quint8 SessionMessage::totalFractionalCycles () const
Returns the SessionMessage data message's totalFractionalCycles field's current value.
fractional part of the total_cycles
Returns
the totalFractionalCycles field value.
Definition at line 1020 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->totalFractionalCycles;
 }
Referenced by setTotalFractionalCycles().
totalFractionalDescent()
quint8 SessionMessage::totalFractionalDescent () const
Returns the SessionMessage data message's totalFractionalDescent field's current value.
fractional part of total_descent
Returns
the totalFractionalDescent field value.
Definition at line 1564 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->totalFractionalDescent;
 }
Referenced by setTotalFractionalDescent().
totalGrit()
float SessionMessage::totalGrit () const
Returns the SessionMessage data message's totalGrit field's current value.
The grit score estimates how challenging a route could be for a cyclist in terms of time spent going over sharp turns or large grade slopes.
Returns
the totalGrit field value.
Definition at line 1485 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->totalGrit;
 }
Referenced by setTotalGrit().
totalMovingTime()
quint32 SessionMessage::totalMovingTime () const
Returns the SessionMessage data message's totalMovingTime field's current value.
Returns
the totalMovingTime field value.
Definition at line 735 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->totalMovingTime;
 }
Referenced by setTotalMovingTime().
totalTimerTime()
quint32 SessionMessage::totalTimerTime () const
Returns the SessionMessage data message's totalTimerTime field's current value.
Timer Time (excludes pauses)
Returns
the totalTimerTime field value.
Definition at line 196 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->totalTimerTime;
 }
Referenced by setTotalTimerTime().
totalTrainingEffect()
quint8 SessionMessage::totalTrainingEffect () const
Returns the SessionMessage data message's totalTrainingEffect field's current value.
Returns
the totalTrainingEffect field value.
Definition at line 371 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->totalTrainingEffect;
 }
Referenced by setTotalTrainingEffect().
totalWork()
quint32 SessionMessage::totalWork () const
Returns the SessionMessage data message's totalWork field's current value.
Returns
the totalWork field value.
Definition at line 614 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->totalWork;
 }
Referenced by setTotalWork().
trainingStressScore()
quint16 SessionMessage::trainingStressScore () const
Returns the SessionMessage data message's trainingStressScore field's current value.
Returns
the trainingStressScore field value.
Definition at line 502 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->trainingStressScore;
 }
Referenced by setTrainingStressScore().
trigger()
SessionTrigger SessionMessage::trigger () const
Returns the SessionMessage data message's trigger field's current value.
Returns
the trigger field value.
Definition at line 415 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->trigger;
 }
Referenced by setTrigger().
zoneCount()
quint16 SessionMessage::zoneCount () const
Returns the SessionMessage data message's zoneCount field's current value.
zone number used as the index
Returns
the zoneCount field value.
Definition at line 926 of file sessionmessage.cpp.
 {
     Q_D(const SessionMessage);
     return d->zoneCount;
 }
Referenced by setZoneCount().
The documentation for this class was generated from the following files:
sessionmessage.h
sessionmessage.cpp