QtFit: ObdiiDataMessage Class Reference
ObdiiDataMessage Class Reference
The ObdiiDataMessage class represents a FIT ObdiiDataMessage data message.
Public Member Functions
ObdiiDataMessage ()
Constructs a ObdiiDataMessage object.
DateTime timestamp () const
Returns the ObdiiDataMessage data message's timestamp field's current value.
quint16 timestampMs () const
Returns the ObdiiDataMessage data message's timestampMs field's current value.
quint16 timeOffset () const
Returns the ObdiiDataMessage data message's timeOffset field's current value.
quint8 pid () const
Returns the ObdiiDataMessage data message's pid field's current value.
quint8 rawData () const
Returns the ObdiiDataMessage data message's rawData field's current value.
quint8 pidDataSize () const
Returns the ObdiiDataMessage data message's pidDataSize field's current value.
quint32 systemTime () const
Returns the ObdiiDataMessage data message's systemTime field's current value.
DateTime startTimestamp () const
Returns the ObdiiDataMessage data message's startTimestamp field's current value.
quint16 startTimestampMs () const
Returns the ObdiiDataMessage data message's startTimestampMs field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
void setTimeOffset (const quint16 timeOffset)
Sets the timeOffset field to timeOffset.
void setPid (const quint8 pid)
Sets the pid field to pid.
void setRawData (const quint8 rawData)
Sets the rawData field to rawData.
void setPidDataSize (const quint8 pidDataSize)
Sets the pidDataSize field to pidDataSize.
void setSystemTime (const quint32 systemTime)
Sets the systemTime field to systemTime.
void setStartTimestamp (const DateTime startTimestamp)
Sets the startTimestamp field to startTimestamp.
void setStartTimestampMs (const quint16 startTimestampMs)
Sets the startTimestampMs field to startTimestampMs.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
ObdiiDataMessage (ObdiiDataMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The ObdiiDataMessage class represents a FIT ObdiiDataMessage data message.
See also
DataMessage
Definition at line 34 of file obdiidatamessage.h.
Constructor & Destructor Documentation
ObdiiDataMessage() [1/2]
ObdiiDataMessage::ObdiiDataMessage ()
Constructs a ObdiiDataMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file obdiidatamessage.cpp.
                                    : AbstractDataMessage(new ObdiiDataMessagePrivate(this))
 {
 }
ObdiiDataMessage() [2/2]
ObdiiDataMessage::ObdiiDataMessage (ObdiiDataMessagePrivate *const d) explicit protected
Constructs a ObdiiDataMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file obdiidatamessage.cpp.
                                                                     : AbstractDataMessage(d)
 {
 }
Member Function Documentation
pid()
quint8 ObdiiDataMessage::pid () const
Returns the ObdiiDataMessage data message's pid field's current value.
Parameter ID
Returns
the pid field value.
Definition at line 111 of file obdiidatamessage.cpp.
 {
     Q_D(const ObdiiDataMessage);
     return d->pid;
 }
Referenced by setPid().
pidDataSize()
quint8 ObdiiDataMessage::pidDataSize () const
Returns the ObdiiDataMessage data message's pidDataSize field's current value.
Optional, data size of PID[i]. If not specified refer to SAE J1979.
Returns
the pidDataSize field value.
Definition at line 137 of file obdiidatamessage.cpp.
 {
     Q_D(const ObdiiDataMessage);
     return d->pidDataSize;
 }
Referenced by setPidDataSize().
rawData()
quint8 ObdiiDataMessage::rawData () const
Returns the ObdiiDataMessage data message's rawData field's current value.
Raw parameter data
Returns
the rawData field value.
Definition at line 124 of file obdiidatamessage.cpp.
 {
     Q_D(const ObdiiDataMessage);
     return d->rawData;
 }
Referenced by setRawData().
setPid()
void ObdiiDataMessage::setPid (const quint8 pid)
Sets the pid field to pid.
Parameters
pid The field value to set.
Definition at line 220 of file obdiidatamessage.cpp.
 {
     Q_D(ObdiiDataMessage);
     d->pid = pid;
 }
References pid().
setPidDataSize()
void ObdiiDataMessage::setPidDataSize (const quint8 pidDataSize)
Sets the pidDataSize field to pidDataSize.
Parameters
pidDataSize The field value to set.
Definition at line 240 of file obdiidatamessage.cpp.
 {
     Q_D(ObdiiDataMessage);
     d->pidDataSize = pidDataSize;
 }
References pidDataSize().
setRawData()
void ObdiiDataMessage::setRawData (const quint8 rawData)
Sets the rawData field to rawData.
Parameters
rawData The field value to set.
Definition at line 230 of file obdiidatamessage.cpp.
 {
     Q_D(ObdiiDataMessage);
     d->rawData = rawData;
 }
References rawData().
setStartTimestamp()
void ObdiiDataMessage::setStartTimestamp (const DateTime startTimestamp)
Sets the startTimestamp field to startTimestamp.
Parameters
startTimestamp The field value to set.
Definition at line 260 of file obdiidatamessage.cpp.
 {
     Q_D(ObdiiDataMessage);
     d->startTimestamp = startTimestamp;
 }
References startTimestamp().
setStartTimestampMs()
void ObdiiDataMessage::setStartTimestampMs (const quint16 startTimestampMs)
Sets the startTimestampMs field to startTimestampMs.
Parameters
startTimestampMs The field value to set.
Definition at line 270 of file obdiidatamessage.cpp.
 {
     Q_D(ObdiiDataMessage);
     d->startTimestampMs = startTimestampMs;
 }
References startTimestampMs().
setSystemTime()
void ObdiiDataMessage::setSystemTime (const quint32 systemTime)
Sets the systemTime field to systemTime.
Parameters
systemTime The field value to set.
Definition at line 250 of file obdiidatamessage.cpp.
 {
     Q_D(ObdiiDataMessage);
     d->systemTime = systemTime;
 }
References systemTime().
setTimeOffset()
void ObdiiDataMessage::setTimeOffset (const quint16 timeOffset)
Sets the timeOffset field to timeOffset.
Parameters
timeOffset The field value to set.
Definition at line 210 of file obdiidatamessage.cpp.
 {
     Q_D(ObdiiDataMessage);
     d->timeOffset = timeOffset;
 }
References timeOffset().
setTimestamp()
void ObdiiDataMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 190 of file obdiidatamessage.cpp.
 {
     Q_D(ObdiiDataMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setTimestampMs()
void ObdiiDataMessage::setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
Parameters
timestampMs The field value to set.
Definition at line 200 of file obdiidatamessage.cpp.
 {
     Q_D(ObdiiDataMessage);
     d->timestampMs = timestampMs;
 }
References timestampMs().
startTimestamp()
DateTime ObdiiDataMessage::startTimestamp () const
Returns the ObdiiDataMessage data message's startTimestamp field's current value.
Timestamp of first sample recorded in the message. Used with time_offset to generate time of each sample
Returns
the startTimestamp field value.
Definition at line 166 of file obdiidatamessage.cpp.
 {
     Q_D(const ObdiiDataMessage);
     return d->startTimestamp;
 }
Referenced by setStartTimestamp().
startTimestampMs()
quint16 ObdiiDataMessage::startTimestampMs () const
Returns the ObdiiDataMessage data message's startTimestampMs field's current value.
Fractional part of start_timestamp
Returns
the startTimestampMs field value.
Definition at line 179 of file obdiidatamessage.cpp.
 {
     Q_D(const ObdiiDataMessage);
     return d->startTimestampMs;
 }
Referenced by setStartTimestampMs().
systemTime()
quint32 ObdiiDataMessage::systemTime () const
Returns the ObdiiDataMessage data message's systemTime field's current value.
System time associated with sample expressed in ms, can be used instead of time_offset. There will be a system_time value for each raw_data element. For multibyte pids the system_time is repeated.
Returns
the systemTime field value.
Definition at line 152 of file obdiidatamessage.cpp.
 {
     Q_D(const ObdiiDataMessage);
     return d->systemTime;
 }
Referenced by setSystemTime().
timeOffset()
quint16 ObdiiDataMessage::timeOffset () const
Returns the ObdiiDataMessage data message's timeOffset field's current value.
Offset of PID reading [i] from start_timestamp+start_timestamp_ms. Readings may span accross seconds.
Returns
the timeOffset field value.
Definition at line 98 of file obdiidatamessage.cpp.
 {
     Q_D(const ObdiiDataMessage);
     return d->timeOffset;
 }
Referenced by setTimeOffset().
timestamp()
DateTime ObdiiDataMessage::timestamp () const
Returns the ObdiiDataMessage data message's timestamp field's current value.
Timestamp message was output
Returns
the timestamp field value.
Definition at line 71 of file obdiidatamessage.cpp.
 {
     Q_D(const ObdiiDataMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
timestampMs()
quint16 ObdiiDataMessage::timestampMs () const
Returns the ObdiiDataMessage data message's timestampMs field's current value.
Fractional part of timestamp, added to timestamp
Returns
the timestampMs field value.
Definition at line 84 of file obdiidatamessage.cpp.
 {
     Q_D(const ObdiiDataMessage);
     return d->timestampMs;
 }
Referenced by setTimestampMs().
The documentation for this class was generated from the following files:
obdiidatamessage.h
obdiidatamessage.cpp