QtFit: PowerZoneMessage Class Reference
PowerZoneMessage Class Reference
The PowerZoneMessage class represents a FIT PowerZoneMessage data message.
Public Member Functions
PowerZoneMessage ()
Constructs a PowerZoneMessage object.
MessageIndex messageIndex () const
Returns the PowerZoneMessage data message's messageIndex field's current value.
quint16 highValue () const
Returns the PowerZoneMessage data message's highValue field's current value.
QString name () const
Returns the PowerZoneMessage data message's name field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setHighValue (const quint16 highValue)
Sets the highValue field to highValue.
void setName (const QString name)
Sets the name field to name.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
PowerZoneMessage (PowerZoneMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The PowerZoneMessage class represents a FIT PowerZoneMessage data message.
See also
DataMessage
Definition at line 34 of file powerzonemessage.h.
Constructor & Destructor Documentation
PowerZoneMessage() [1/2]
PowerZoneMessage::PowerZoneMessage ()
Constructs a PowerZoneMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file powerzonemessage.cpp.
                                    : AbstractDataMessage(new PowerZoneMessagePrivate(this))
 {
 }
PowerZoneMessage() [2/2]
PowerZoneMessage::PowerZoneMessage (PowerZoneMessagePrivate *const d) explicit protected
Constructs a PowerZoneMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file powerzonemessage.cpp.
                                                                     : AbstractDataMessage(d)
 {
 }
Member Function Documentation
highValue()
quint16 PowerZoneMessage::highValue () const
Returns the PowerZoneMessage data message's highValue field's current value.
Returns
the highValue field value.
Definition at line 80 of file powerzonemessage.cpp.
 {
     Q_D(const PowerZoneMessage);
     return d->highValue;
 }
Referenced by setHighValue().
messageIndex()
MessageIndex PowerZoneMessage::messageIndex () const
Returns the PowerZoneMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 69 of file powerzonemessage.cpp.
 {
     Q_D(const PowerZoneMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
name()
QString PowerZoneMessage::name () const
Returns the PowerZoneMessage data message's name field's current value.
Returns
the name field value.
Definition at line 91 of file powerzonemessage.cpp.
 {
     Q_D(const PowerZoneMessage);
     return d->name;
 }
Referenced by setName().
setHighValue()
void PowerZoneMessage::setHighValue (const quint16 highValue)
Sets the highValue field to highValue.
Parameters
highValue The field value to set.
Definition at line 112 of file powerzonemessage.cpp.
 {
     Q_D(PowerZoneMessage);
     d->highValue = highValue;
 }
References highValue().
setMessageIndex()
void PowerZoneMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 102 of file powerzonemessage.cpp.
 {
     Q_D(PowerZoneMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setName()
void PowerZoneMessage::setName (const QString name)
Sets the name field to name.
Parameters
name The field value to set.
Definition at line 122 of file powerzonemessage.cpp.
 {
     Q_D(PowerZoneMessage);
     d->name = name;
 }
References name().
The documentation for this class was generated from the following files:
powerzonemessage.h
powerzonemessage.cpp