QtFit: CadenceZoneMessage Class Reference
CadenceZoneMessage Class Reference
The CadenceZoneMessage class represents a FIT CadenceZoneMessage data message.
Public Member Functions
CadenceZoneMessage ()
Constructs a CadenceZoneMessage object.
MessageIndex messageIndex () const
Returns the CadenceZoneMessage data message's messageIndex field's current value.
quint8 highValue () const
Returns the CadenceZoneMessage data message's highValue field's current value.
QString name () const
Returns the CadenceZoneMessage data message's name field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setHighValue (const quint8 highValue)
Sets the highValue field to highValue.
void setName (const QString name)
Sets the name field to name.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
CadenceZoneMessage (CadenceZoneMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The CadenceZoneMessage class represents a FIT CadenceZoneMessage data message.
See also
DataMessage
Definition at line 34 of file cadencezonemessage.h.
Constructor & Destructor Documentation
CadenceZoneMessage() [1/2]
CadenceZoneMessage::CadenceZoneMessage ()
Constructs a CadenceZoneMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file cadencezonemessage.cpp.
                                        : AbstractDataMessage(new CadenceZoneMessagePrivate(this))
 {
 }
CadenceZoneMessage() [2/2]
CadenceZoneMessage::CadenceZoneMessage (CadenceZoneMessagePrivate *const d) explicit protected
Constructs a CadenceZoneMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file cadencezonemessage.cpp.
                                                                           : AbstractDataMessage(d)
 {
 }
Member Function Documentation
highValue()
quint8 CadenceZoneMessage::highValue () const
Returns the CadenceZoneMessage data message's highValue field's current value.
Returns
the highValue field value.
Definition at line 80 of file cadencezonemessage.cpp.
 {
     Q_D(const CadenceZoneMessage);
     return d->highValue;
 }
Referenced by setHighValue().
messageIndex()
MessageIndex CadenceZoneMessage::messageIndex () const
Returns the CadenceZoneMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 69 of file cadencezonemessage.cpp.
 {
     Q_D(const CadenceZoneMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
name()
QString CadenceZoneMessage::name () const
Returns the CadenceZoneMessage data message's name field's current value.
Returns
the name field value.
Definition at line 91 of file cadencezonemessage.cpp.
 {
     Q_D(const CadenceZoneMessage);
     return d->name;
 }
Referenced by setName().
setHighValue()
void CadenceZoneMessage::setHighValue (const quint8 highValue)
Sets the highValue field to highValue.
Parameters
highValue The field value to set.
Definition at line 112 of file cadencezonemessage.cpp.
 {
     Q_D(CadenceZoneMessage);
     d->highValue = highValue;
 }
References highValue().
setMessageIndex()
void CadenceZoneMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 102 of file cadencezonemessage.cpp.
 {
     Q_D(CadenceZoneMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setName()
void CadenceZoneMessage::setName (const QString name)
Sets the name field to name.
Parameters
name The field value to set.
Definition at line 122 of file cadencezonemessage.cpp.
 {
     Q_D(CadenceZoneMessage);
     d->name = name;
 }
References name().
The documentation for this class was generated from the following files:
cadencezonemessage.h
cadencezonemessage.cpp