QtFit: WatchfaceSettingsMessage Class Reference
WatchfaceSettingsMessage Class Reference
The WatchfaceSettingsMessage class represents a FIT WatchfaceSettingsMessage data message.
Public Member Functions
WatchfaceSettingsMessage ()
Constructs a WatchfaceSettingsMessage object.
MessageIndex messageIndex () const
Returns the WatchfaceSettingsMessage data message's messageIndex field's current value.
WatchfaceMode mode () const
Returns the WatchfaceSettingsMessage data message's mode field's current value.
quint8 layout () const
Returns the WatchfaceSettingsMessage data message's layout field's current value.
void setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
void setMode (const WatchfaceMode mode)
Sets the mode field to mode.
void setLayout (const quint8 layout)
Sets the layout field to layout.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
WatchfaceSettingsMessage (WatchfaceSettingsMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The WatchfaceSettingsMessage class represents a FIT WatchfaceSettingsMessage data message.
See also
DataMessage
Definition at line 39 of file watchfacesettingsmessage.h.
Constructor & Destructor Documentation
WatchfaceSettingsMessage() [1/2]
WatchfaceSettingsMessage::WatchfaceSettingsMessage ()
Constructs a WatchfaceSettingsMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file watchfacesettingsmessage.cpp.
                                                    : AbstractDataMessage(new WatchfaceSettingsMessagePrivate(this))
 {
 }
WatchfaceSettingsMessage() [2/2]
WatchfaceSettingsMessage::WatchfaceSettingsMessage (WatchfaceSettingsMessagePrivate *const d) explicit protected
Constructs a WatchfaceSettingsMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file watchfacesettingsmessage.cpp.
                                                                                             : AbstractDataMessage(d)
 {
 }
Member Function Documentation
layout()
quint8 WatchfaceSettingsMessage::layout () const
Returns the WatchfaceSettingsMessage data message's layout field's current value.
Returns
the layout field value.
Definition at line 96 of file watchfacesettingsmessage.cpp.
 {
     Q_D(const WatchfaceSettingsMessage);
     return d->layout;
 }
Referenced by setLayout().
messageIndex()
MessageIndex WatchfaceSettingsMessage::messageIndex () const
Returns the WatchfaceSettingsMessage data message's messageIndex field's current value.
Returns
the messageIndex field value.
Definition at line 74 of file watchfacesettingsmessage.cpp.
 {
     Q_D(const WatchfaceSettingsMessage);
     return d->messageIndex;
 }
Referenced by setMessageIndex().
mode()
WatchfaceMode WatchfaceSettingsMessage::mode () const
Returns the WatchfaceSettingsMessage data message's mode field's current value.
Returns
the mode field value.
Definition at line 85 of file watchfacesettingsmessage.cpp.
 {
     Q_D(const WatchfaceSettingsMessage);
     return d->mode;
 }
Referenced by setMode().
setLayout()
void WatchfaceSettingsMessage::setLayout (const quint8 layout)
Sets the layout field to layout.
Parameters
layout The field value to set.
Definition at line 127 of file watchfacesettingsmessage.cpp.
 {
     Q_D(WatchfaceSettingsMessage);
     d->layout = layout;
 }
References layout().
setMessageIndex()
void WatchfaceSettingsMessage::setMessageIndex (const MessageIndex messageIndex)
Sets the messageIndex field to messageIndex.
Parameters
messageIndex The field value to set.
Definition at line 107 of file watchfacesettingsmessage.cpp.
 {
     Q_D(WatchfaceSettingsMessage);
     d->messageIndex = messageIndex;
 }
References messageIndex().
setMode()
void WatchfaceSettingsMessage::setMode (const WatchfaceMode mode)
Sets the mode field to mode.
Parameters
mode The field value to set.
Definition at line 117 of file watchfacesettingsmessage.cpp.
 {
     Q_D(WatchfaceSettingsMessage);
     d->mode = mode;
 }
References mode().
The documentation for this class was generated from the following files:
watchfacesettingsmessage.h
watchfacesettingsmessage.cpp