QtFit: BarometerDataMessage Class Reference
BarometerDataMessage Class Reference
The BarometerDataMessage class represents a FIT BarometerDataMessage data message.
Public Member Functions
BarometerDataMessage ()
Constructs a BarometerDataMessage object.
DateTime timestamp () const
Returns the BarometerDataMessage data message's timestamp field's current value.
quint16 timestampMs () const
Returns the BarometerDataMessage data message's timestampMs field's current value.
quint16 sampleTimeOffset () const
Returns the BarometerDataMessage data message's sampleTimeOffset field's current value.
quint32 baroPres () const
Returns the BarometerDataMessage data message's baroPres field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
void setSampleTimeOffset (const quint16 sampleTimeOffset)
Sets the sampleTimeOffset field to sampleTimeOffset.
void setBaroPres (const quint32 baroPres)
Sets the baroPres field to baroPres.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
BarometerDataMessage (BarometerDataMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The BarometerDataMessage class represents a FIT BarometerDataMessage data message.
See also
DataMessage
Definition at line 39 of file barometerdatamessage.h.
Constructor & Destructor Documentation
BarometerDataMessage() [1/2]
BarometerDataMessage::BarometerDataMessage ()
Constructs a BarometerDataMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file barometerdatamessage.cpp.
                                            : AbstractDataMessage(new BarometerDataMessagePrivate(this))
 {
 }
BarometerDataMessage() [2/2]
BarometerDataMessage::BarometerDataMessage (BarometerDataMessagePrivate *const d) explicit protected
Constructs a BarometerDataMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file barometerdatamessage.cpp.
                                                                                 : AbstractDataMessage(d)
 {
 }
Member Function Documentation
baroPres()
quint32 BarometerDataMessage::baroPres () const
Returns the BarometerDataMessage data message's baroPres field's current value.
These are the raw ADC reading. The samples may span across seconds. A conversion will need to be done on this data once read.
Returns
the baroPres field value.
Definition at line 118 of file barometerdatamessage.cpp.
 {
     Q_D(const BarometerDataMessage);
     return d->baroPres;
 }
Referenced by setBaroPres().
sampleTimeOffset()
quint16 BarometerDataMessage::sampleTimeOffset () const
Returns the BarometerDataMessage data message's sampleTimeOffset field's current value.
Each time in the array describes the time at which the barometer sample with the corrosponding index was taken. The samples may span across seconds. Array size must match the number of samples in baro_cal
Returns
the sampleTimeOffset field value.
Definition at line 104 of file barometerdatamessage.cpp.
 {
     Q_D(const BarometerDataMessage);
     return d->sampleTimeOffset;
 }
Referenced by setSampleTimeOffset().
setBaroPres()
void BarometerDataMessage::setBaroPres (const quint32 baroPres)
Sets the baroPres field to baroPres.
Parameters
baroPres The field value to set.
Definition at line 159 of file barometerdatamessage.cpp.
 {
     Q_D(BarometerDataMessage);
     d->baroPres = baroPres;
 }
References baroPres().
setSampleTimeOffset()
void BarometerDataMessage::setSampleTimeOffset (const quint16 sampleTimeOffset)
Sets the sampleTimeOffset field to sampleTimeOffset.
Parameters
sampleTimeOffset The field value to set.
Definition at line 149 of file barometerdatamessage.cpp.
 {
     Q_D(BarometerDataMessage);
     d->sampleTimeOffset = sampleTimeOffset;
 }
References sampleTimeOffset().
setTimestamp()
void BarometerDataMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 129 of file barometerdatamessage.cpp.
 {
     Q_D(BarometerDataMessage);
     d->timestamp = timestamp;
 }
References timestamp().
setTimestampMs()
void BarometerDataMessage::setTimestampMs (const quint16 timestampMs)
Sets the timestampMs field to timestampMs.
Parameters
timestampMs The field value to set.
Definition at line 139 of file barometerdatamessage.cpp.
 {
     Q_D(BarometerDataMessage);
     d->timestampMs = timestampMs;
 }
References timestampMs().
timestamp()
DateTime BarometerDataMessage::timestamp () const
Returns the BarometerDataMessage data message's timestamp field's current value.
Whole second part of the timestamp
Returns
the timestamp field value.
Definition at line 76 of file barometerdatamessage.cpp.
 {
     Q_D(const BarometerDataMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
timestampMs()
quint16 BarometerDataMessage::timestampMs () const
Returns the BarometerDataMessage data message's timestampMs field's current value.
Millisecond part of the timestamp.
Returns
the timestampMs field value.
Definition at line 89 of file barometerdatamessage.cpp.
 {
     Q_D(const BarometerDataMessage);
     return d->timestampMs;
 }
Referenced by setTimestampMs().
The documentation for this class was generated from the following files:
barometerdatamessage.h
barometerdatamessage.cpp