QtFit: ExdDataFieldConfigurationMessage Class Reference
ExdDataFieldConfigurationMessage Class Reference
The ExdDataFieldConfigurationMessage class represents a FIT ExdDataFieldConfigurationMessage data message.
Public Member Functions
ExdDataFieldConfigurationMessage ()
Constructs a ExdDataFieldConfigurationMessage object.
quint8 screenIndex () const
Returns the ExdDataFieldConfigurationMessage data message's screenIndex field's current value.
quint8 conceptField () const
Returns the ExdDataFieldConfigurationMessage data message's conceptField field's current value.
quint8 fieldId () const
Returns the ExdDataFieldConfigurationMessage data message's fieldId field's current value.
quint8 conceptCount () const
Returns the ExdDataFieldConfigurationMessage data message's conceptCount field's current value.
ExdDisplayType displayType () const
Returns the ExdDataFieldConfigurationMessage data message's displayType field's current value.
QString title () const
Returns the ExdDataFieldConfigurationMessage data message's title field's current value.
void setScreenIndex (const quint8 screenIndex)
Sets the screenIndex field to screenIndex.
void setConceptField (const quint8 conceptField)
Sets the conceptField field to conceptField.
void setFieldId (const quint8 fieldId)
Sets the fieldId field to fieldId.
void setConceptCount (const quint8 conceptCount)
Sets the conceptCount field to conceptCount.
void setDisplayType (const ExdDisplayType displayType)
Sets the displayType field to displayType.
void setTitle (const QString title)
Sets the title field to title.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
ExdDataFieldConfigurationMessage (ExdDataFieldConfigurationMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The ExdDataFieldConfigurationMessage class represents a FIT ExdDataFieldConfigurationMessage data message.
See also
DataMessage
Definition at line 34 of file exddatafieldconfigurationmessage.h.
Constructor & Destructor Documentation
ExdDataFieldConfigurationMessage() [1/2]
ExdDataFieldConfigurationMessage::ExdDataFieldConfigurationMessage ()
Constructs a ExdDataFieldConfigurationMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 47 of file exddatafieldconfigurationmessage.cpp.
                                                                    : AbstractDataMessage(new ExdDataFieldConfigurationMessagePrivate(this))
 {
 }
ExdDataFieldConfigurationMessage() [2/2]
ExdDataFieldConfigurationMessage::ExdDataFieldConfigurationMessage (ExdDataFieldConfigurationMessagePrivate *const d) explicit protected
Constructs a ExdDataFieldConfigurationMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 59 of file exddatafieldconfigurationmessage.cpp.
                                                                                                                     : AbstractDataMessage(d)
 {
 }
Member Function Documentation
conceptCount()
quint8 ExdDataFieldConfigurationMessage::conceptCount () const
Returns the ExdDataFieldConfigurationMessage data message's conceptCount field's current value.
Returns
the conceptCount field value.
Definition at line 102 of file exddatafieldconfigurationmessage.cpp.
 {
     Q_D(const ExdDataFieldConfigurationMessage);
     return d->conceptCount;
 }
Referenced by setConceptCount().
conceptField()
quint8 ExdDataFieldConfigurationMessage::conceptField () const
Returns the ExdDataFieldConfigurationMessage data message's conceptField field's current value.
Returns
the conceptField field value.
Definition at line 80 of file exddatafieldconfigurationmessage.cpp.
 {
     Q_D(const ExdDataFieldConfigurationMessage);
     return d->conceptField;
 }
Referenced by setConceptField().
displayType()
ExdDisplayType ExdDataFieldConfigurationMessage::displayType () const
Returns the ExdDataFieldConfigurationMessage data message's displayType field's current value.
Returns
the displayType field value.
Definition at line 113 of file exddatafieldconfigurationmessage.cpp.
 {
     Q_D(const ExdDataFieldConfigurationMessage);
     return d->displayType;
 }
Referenced by setDisplayType().
fieldId()
quint8 ExdDataFieldConfigurationMessage::fieldId () const
Returns the ExdDataFieldConfigurationMessage data message's fieldId field's current value.
Returns
the fieldId field value.
Definition at line 91 of file exddatafieldconfigurationmessage.cpp.
 {
     Q_D(const ExdDataFieldConfigurationMessage);
     return d->fieldId;
 }
Referenced by setFieldId().
screenIndex()
quint8 ExdDataFieldConfigurationMessage::screenIndex () const
Returns the ExdDataFieldConfigurationMessage data message's screenIndex field's current value.
Returns
the screenIndex field value.
Definition at line 69 of file exddatafieldconfigurationmessage.cpp.
 {
     Q_D(const ExdDataFieldConfigurationMessage);
     return d->screenIndex;
 }
Referenced by setScreenIndex().
setConceptCount()
void ExdDataFieldConfigurationMessage::setConceptCount (const quint8 conceptCount)
Sets the conceptCount field to conceptCount.
Parameters
conceptCount The field value to set.
Definition at line 165 of file exddatafieldconfigurationmessage.cpp.
 {
     Q_D(ExdDataFieldConfigurationMessage);
     d->conceptCount = conceptCount;
 }
References conceptCount().
setConceptField()
void ExdDataFieldConfigurationMessage::setConceptField (const quint8 conceptField)
Sets the conceptField field to conceptField.
Parameters
conceptField The field value to set.
Definition at line 145 of file exddatafieldconfigurationmessage.cpp.
 {
     Q_D(ExdDataFieldConfigurationMessage);
     d->conceptField = conceptField;
 }
References conceptField().
setDisplayType()
void ExdDataFieldConfigurationMessage::setDisplayType (const ExdDisplayType displayType)
Sets the displayType field to displayType.
Parameters
displayType The field value to set.
Definition at line 175 of file exddatafieldconfigurationmessage.cpp.
 {
     Q_D(ExdDataFieldConfigurationMessage);
     d->displayType = displayType;
 }
References displayType().
setFieldId()
void ExdDataFieldConfigurationMessage::setFieldId (const quint8 fieldId)
Sets the fieldId field to fieldId.
Parameters
fieldId The field value to set.
Definition at line 155 of file exddatafieldconfigurationmessage.cpp.
 {
     Q_D(ExdDataFieldConfigurationMessage);
     d->fieldId = fieldId;
 }
References fieldId().
setScreenIndex()
void ExdDataFieldConfigurationMessage::setScreenIndex (const quint8 screenIndex)
Sets the screenIndex field to screenIndex.
Parameters
screenIndex The field value to set.
Definition at line 135 of file exddatafieldconfigurationmessage.cpp.
 {
     Q_D(ExdDataFieldConfigurationMessage);
     d->screenIndex = screenIndex;
 }
References screenIndex().
setTitle()
void ExdDataFieldConfigurationMessage::setTitle (const QString title)
Sets the title field to title.
Parameters
title The field value to set.
Definition at line 185 of file exddatafieldconfigurationmessage.cpp.
 {
     Q_D(ExdDataFieldConfigurationMessage);
     d->title = title;
 }
References title().
title()
QString ExdDataFieldConfigurationMessage::title () const
Returns the ExdDataFieldConfigurationMessage data message's title field's current value.
Returns
the title field value.
Definition at line 124 of file exddatafieldconfigurationmessage.cpp.
 {
     Q_D(const ExdDataFieldConfigurationMessage);
     return d->title;
 }
Referenced by setTitle().
The documentation for this class was generated from the following files:
exddatafieldconfigurationmessage.h
exddatafieldconfigurationmessage.cpp