QtFit: AntRxMessage Class Reference
AntRxMessage Class Reference
The AntRxMessage class represents a FIT AntRxMessage data message.
Public Member Functions
AntRxMessage ()
Constructs a AntRxMessage object.
DateTime timestamp () const
Returns the AntRxMessage data message's timestamp field's current value.
quint16 fractionalTimestamp () const
Returns the AntRxMessage data message's fractionalTimestamp field's current value.
quint8 mesgId () const
Returns the AntRxMessage data message's mesgId field's current value.
quint8 mesgData () const
Returns the AntRxMessage data message's mesgData field's current value.
quint8 channelNumber () const
Returns the AntRxMessage data message's channelNumber field's current value.
quint8 data () const
Returns the AntRxMessage data message's data field's current value.
void setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
void setFractionalTimestamp (const quint16 fractionalTimestamp)
Sets the fractionalTimestamp field to fractionalTimestamp.
void setMesgId (const quint8 mesgId)
Sets the mesgId field to mesgId.
void setMesgData (const quint8 mesgData)
Sets the mesgData field to mesgData.
void setChannelNumber (const quint8 channelNumber)
Sets the channelNumber field to channelNumber.
void setData (const quint8 data)
Sets the data field to data.
Public Member Functions inherited from AbstractDataMessage
~AbstractDataMessage ()
Destroys the AbstractDataMessage object.
MesgNum globalMessageNumber () const
Returns the data message's global message number.
Protected Member Functions
AntRxMessage (AntRxMessagePrivate *const d)
Protected Member Functions inherited from AbstractDataMessage
AbstractDataMessage (AbstractDataMessagePrivate *const d)
Additional Inherited Members
Static Public Member Functions inherited from AbstractDataMessage
static AbstractDataMessage * fromData (const DataDefinition *const defn, const QByteArray &record)
Constructs the relevant AbstractDataMessage-derived class to parse record according to defn.
Protected Attributes inherited from AbstractDataMessage
AbstractDataMessagePrivate *const d_ptr
Internal d-pointer.
Detailed Description
The AntRxMessage class represents a FIT AntRxMessage data message.
See also
DataMessage
Definition at line 39 of file antrxmessage.h.
Constructor & Destructor Documentation
AntRxMessage() [1/2]
AntRxMessage::AntRxMessage ()
Constructs a AntRxMessage object.
Typically, instances of this class will be returned by FitStreamReader::readNext, but this constructor may be used, along with the relevant setter methods, to create a valid message.
Definition at line 52 of file antrxmessage.cpp.
                            : AbstractDataMessage(new AntRxMessagePrivate(this))
 {
 }
AntRxMessage() [2/2]
AntRxMessage::AntRxMessage (AntRxMessagePrivate *const d) explicit protected
Constructs a AntRxMessage object with private implementation d.
Parameters
d Pointer to private implementation.
Definition at line 64 of file antrxmessage.cpp.
                                                         : AbstractDataMessage(d)
 {
 }
Member Function Documentation
channelNumber()
quint8 AntRxMessage::channelNumber () const
Returns the AntRxMessage data message's channelNumber field's current value.
Returns
the channelNumber field value.
Definition at line 118 of file antrxmessage.cpp.
 {
     Q_D(const AntRxMessage);
     return d->channelNumber;
 }
Referenced by setChannelNumber().
data()
quint8 AntRxMessage::data () const
Returns the AntRxMessage data message's data field's current value.
Returns
the data field value.
Definition at line 129 of file antrxmessage.cpp.
 {
     Q_D(const AntRxMessage);
     return d->data;
 }
Referenced by setData().
fractionalTimestamp()
quint16 AntRxMessage::fractionalTimestamp () const
Returns the AntRxMessage data message's fractionalTimestamp field's current value.
Returns
the fractionalTimestamp field value.
Definition at line 85 of file antrxmessage.cpp.
 {
     Q_D(const AntRxMessage);
     return d->fractionalTimestamp;
 }
Referenced by setFractionalTimestamp().
mesgData()
quint8 AntRxMessage::mesgData () const
Returns the AntRxMessage data message's mesgData field's current value.
Returns
the mesgData field value.
Definition at line 107 of file antrxmessage.cpp.
 {
     Q_D(const AntRxMessage);
     return d->mesgData;
 }
Referenced by setMesgData().
mesgId()
quint8 AntRxMessage::mesgId () const
Returns the AntRxMessage data message's mesgId field's current value.
Returns
the mesgId field value.
Definition at line 96 of file antrxmessage.cpp.
 {
     Q_D(const AntRxMessage);
     return d->mesgId;
 }
Referenced by setMesgId().
setChannelNumber()
void AntRxMessage::setChannelNumber (const quint8 channelNumber)
Sets the channelNumber field to channelNumber.
Parameters
channelNumber The field value to set.
Definition at line 180 of file antrxmessage.cpp.
 {
     Q_D(AntRxMessage);
     d->channelNumber = channelNumber;
 }
References channelNumber().
setData()
void AntRxMessage::setData (const quint8 data)
Sets the data field to data.
Parameters
data The field value to set.
Definition at line 190 of file antrxmessage.cpp.
 {
     Q_D(AntRxMessage);
     d->data = data;
 }
References data().
setFractionalTimestamp()
void AntRxMessage::setFractionalTimestamp (const quint16 fractionalTimestamp)
Sets the fractionalTimestamp field to fractionalTimestamp.
Parameters
fractionalTimestamp The field value to set.
Definition at line 150 of file antrxmessage.cpp.
 {
     Q_D(AntRxMessage);
     d->fractionalTimestamp = fractionalTimestamp;
 }
References fractionalTimestamp().
setMesgData()
void AntRxMessage::setMesgData (const quint8 mesgData)
Sets the mesgData field to mesgData.
Parameters
mesgData The field value to set.
Definition at line 170 of file antrxmessage.cpp.
 {
     Q_D(AntRxMessage);
     d->mesgData = mesgData;
 }
References mesgData().
setMesgId()
void AntRxMessage::setMesgId (const quint8 mesgId)
Sets the mesgId field to mesgId.
Parameters
mesgId The field value to set.
Definition at line 160 of file antrxmessage.cpp.
 {
     Q_D(AntRxMessage);
     d->mesgId = mesgId;
 }
References mesgId().
setTimestamp()
void AntRxMessage::setTimestamp (const DateTime timestamp)
Sets the timestamp field to timestamp.
Parameters
timestamp The field value to set.
Definition at line 140 of file antrxmessage.cpp.
 {
     Q_D(AntRxMessage);
     d->timestamp = timestamp;
 }
References timestamp().
timestamp()
DateTime AntRxMessage::timestamp () const
Returns the AntRxMessage data message's timestamp field's current value.
Returns
the timestamp field value.
Definition at line 74 of file antrxmessage.cpp.
 {
     Q_D(const AntRxMessage);
     return d->timestamp;
 }
Referenced by setTimestamp().
The documentation for this class was generated from the following files:
antrxmessage.h
antrxmessage.cpp