name: Build

on: [push, pull_request]

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        env:
        - { cc: clang, cxx: clang++ }
        - { cc: gcc, cxx: g++ }
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      run: sudo apt update && sudo apt upgrade && sudo apt install qtbase5-dev
    - name: Build
      env:
        CC:  ${{ matrix.env.cc }}
        CXX: ${{ matrix.env.cxx }}
      run: |
        cmake -D CMAKE_BUILD_TYPE=Release -S "$GITHUB_WORKSPACE" -B "$RUNNER_TEMP"
        cmake --build "$RUNNER_TEMP"
    - name: Test
      run: ctest --verbose
      working-directory: ${{ runner.temp }}

  linux-qts:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        qt: [ '5.9.9', '5.12.12', '5.15.2', '6.0.4', '6.1.3', '6.2.2' ]
        env:
        - { cc: clang, cxx: clang++ }
        - { cc: gcc, cxx: g++ }
    steps:
    - uses: actions/checkout@v2
    - name: Install Tools
      run: sudo apt update && sudo apt upgrade && sudo apt install clang
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}
    - name: Build
      env:
        CC:  ${{ matrix.env.cc }}
        CXX: ${{ matrix.env.cxx }}
      run: |
        cmake -D CMAKE_BUILD_TYPE=Release -S "$GITHUB_WORKSPACE" -B "$RUNNER_TEMP"
        cmake --build "$RUNNER_TEMP"
    - name: Test
      run: ctest --verbose
      working-directory: ${{ runner.temp }}

  mac:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macOs-latest ]
        qt: [ '5.9.9', '5.12.12', '5.15.2' ]
        env:
        - { cc: clang, cxx: clang++ }
        - { cc: gcc-11, cxx: g++-11 }
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}
    - name: Build
      env:
        CC:  ${{ matrix.env.cc }}
        CXX: ${{ matrix.env.cxx }}
      run: |
        cmake -D CMAKE_BUILD_TYPE=Release -S "$GITHUB_WORKSPACE" -B "$RUNNER_TEMP"
        cmake --build "$RUNNER_TEMP"
    - name: Test
      run: ctest --verbose
      working-directory: ${{ runner.temp }}

  win:
    runs-on: ${{ matrix.os }}
    defaults: { run: { shell: cmd } }
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        qt: [ '5.12.12', '5.15.2', '6.0.4', '6.1.3', '6.2.2' ]
        generator: [ 'MinGW Makefiles', 'NMake Makefiles' ]
        include:
        - qt: '5.12.11'
          arch: win64_mingw73
        - qt: '5.15.2'
          arch: win64_mingw81
        - qt: '6.0.4'
          arch: win64_mingw81
        - qt: '6.1.2'
          arch: win64_mingw81
        - qt: '6.2.0'
          arch: win64_mingw81
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt (mingw)
      if: ${{ contains(matrix.generator, 'mingw') }}
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}
        arch: ${{ matrix.arch }}
    - name: Install Qt (msvc)
      if: ${{ contains(matrix.generator, 'nmake') }}
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}
    - name: Configure MSVC
      if: ${{ contains(matrix.generator, 'nmake') }}
      uses: ilammy/msvc-dev-cmd@v1
    - name: Build
      run: |
        cmake -D CMAKE_BUILD_TYPE=Release -G "${{ matrix.generator }}" -S "%GITHUB_WORKSPACE%" -B "%RUNNER_TEMP%"
        cmake --build "%RUNNER_TEMP%"
    - name: Install DLL for Tests
      if: ${{ contains(matrix.generator, 'mingw') }}
      run: |
        copy /v /b src\libQtFit.dll /b test\opaque
        copy /v /b src\libQtFit.dll /b test\unit
      working-directory: ${{ runner.temp }}
    - name: Install DLL for Tests
      if: ${{ contains(matrix.generator, 'nmake') }}
      run: |
        copy /v /b src\QtFit.dll /b test\opaque
        copy /v /b src\QtFit.dll /b test\unit
      working-directory: ${{ runner.temp }}
    - name: Test
      run: |
        dir
        dir src
        dir test
        dir .\src
        dir .\test
        ctest --verbose
      working-directory: ${{ runner.temp }}
