name: Test Coverage

on: [push, pull_request]

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        env:
        - { cc: gcc, cxx: g++ }
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      run: sudo apt install lcov qtbase5-dev
    - name: Build
      env:
        CC:  ${{ matrix.env.cc }}
        CXX: ${{ matrix.env.cxx }}
      run: |
        cmake -D CMAKE_BUILD_TYPE=Release -D ENABLE_COVERAGE=ON -S "$GITHUB_WORKSPACE" -B "$RUNNER_TEMP"
        cmake --build "$RUNNER_TEMP"
    - name: Test
      run: ctest --verbose
      working-directory: ${{ runner.temp }}
    - name: Collate Coverage
      run: make coverage
      working-directory: ${{ runner.temp }}
    - name: Generate HTML Report
      run: make coverage-html
      working-directory: ${{ runner.temp }}
    - name: Upload HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: Test Coverage HTML Report
        path: "${{ runner.temp }}/coverage"
    - name: Submit to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: "${{ runner.temp }}/coverage.info"
        fail_ci_if_error: true
    - name: Submit to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: "${{ runner.temp }}/coverage.info"
